### ISSUE TITLE
Behaviors of map matcher's OfflineMatch

### ISSUE THREAD

**Issue by ptpt** [valhalla/valhalla#1018]
It's unclear what `OfflineMatch` returns for some corner cases. Here is its declaration:
```c++
  std::vector<MatchResults>
  OfflineMatch(const std::vector<Measurement>& measurements, uint32_t k = 1);
```

Proposal:
1. Always return `n` best paths where `0 < n <= k`
2. The last and only the last best path might be broken
3. If `measurements` is empty, return vector that contains only an empty `MatchResults` with confidence 0.0f

@kevinkreiser I wonder if it makes sense to you, or if it's complicated?

**Comment by kevinkreiser** [comment]
im pretty sure `1.` is already true. `2.` seems fine, the current implementation that the the only broken paths we will return will be if the first one was broken. any additional paths will be skipped if they are broken and th elop will stop. `3.` sounds fine

**Comment by ptpt** [comment]
Will revert 2) to what it was.
