### ISSUE TITLE
Request for ability to input seconds for isochrone contour times

### ISSUE THREAD

**Issue by rmglennon** [valhalla/valhalla#1032]
This enhancement request came up at SF office hours (and, conveniently, @dnesbitt61 was in town!). 

The SF Fire Department wants to generate isochrones in portions of a minute. For example, 4.5 minutes for the `contour: time` value. 

@burritojustice tried this, and it just rounded to a full minute as an integer (and converting it to seconds interpreted the value as minutes). 30-seconds does not seem like much, but it is important for emergency response.

Consider allowing the ability to use seconds or decimals to input the time values.

**Comment by kevinkreiser** [comment]
Internally we use seconds so that should be no problem. We would just need add a units to the contour object, default it to minutes and then allow for users to specify seconds as well as minutes.

**Comment by kevinkreiser** [comment]
Scratch that we'll just make the value floating point minutes and get the seconds from that. Way easier.

**Comment by dnesbitt61** [comment]
@kevinkreiser - it looks like this is already done. The directions_options proto uses float for time and the JSON parsing logic gets the value as a float. Perhaps could update the doc to indicate that floating point values are allowed? Otherwise this can be closed I think.

**Comment by dnesbitt61** [comment]
Tested this and we support floating point values for contour times. Updated the doc so I am closing this.
