### ISSUE TITLE
Suspicious 5 minute walk shed around a train station

### ISSUE THREAD

**Issue by stevevance** [valhalla/valhalla#1053]
This is the API called I used:
https://matrix.mapzen.com/isochrone?api_key=XXX&json=%7B%22locations%22%3A%5B%7B%22lat%22%3A%2241.96427%22%2C%22lon%22%3A%22-87.65759%22%7D%5D%2C%22costing%22%3A%22pedestrian%22%2C%22contours%22%3A%5B%7B%22time%22%3A5%7D%5D%2C%22polygons%22%3Atrue%2C%22generalize%22%3A1%7D

It has these parameters:
````
{"locations":[{"lat":"41.96427","lon":"-87.65759"}],"costing":"pedestrian","contours":[{"time":5}],"polygons":true,"generalize":1}
````

The walk shed looks very uneven. How could one walk from the station to Saint Mary of the Lake School to the south in 5 minutes, but not get much north of Leland Avenue in 5 minutes?

![pasted_image_12_6_17__00_33](https://user-images.githubusercontent.com/1330459/33647978-507c8c84-da1d-11e7-8f58-0d8d851aacc4.jpg)

**Comment by dnesbitt61** [comment]
It likely finds this way as the closest: https://www.openstreetmap.org/way/231005444 - meaning you have to walk south first to actually get anywhere. This probably leads to the bias towards southerly (and easterly) points. Locations to the north and west take a little longer since you have to go south and  backtrack

**Comment by stevevance** [comment]
@dnesbitt61 That's a parking aisle - I don't think anyone should be walking on that.

**Comment by dnesbitt61** [comment]
There are lots of places where walking on parking aisles is acceptable. Probably the best solution is to search a small radius and allow starting the isochrone on multiple, nearby ways. That way this could select the walking path just west of the location.

**Comment by dnesbitt61** [comment]
Added an issue: https://github.com/valhalla/valhalla/issues/1059

**Comment by stevevance** [comment]
As a way to get from a parked car to a store entrance, you would walk in the parking aisle, but I don't think the tag should be considered as part of walking directions.
