### ISSUE TITLE
Documentation Omits Instructions For Running Valhalla Usefully

### ISSUE THREAD

**Issue by jvparkourm** [valhalla/valhalla#1073]
The documentation says nothing about where to get the data necessary.  I found  out, by dredging through various Github issues, that the required data for using Valhalla is an OpenStreetMap protocol-buffers-formatted file (.pbf).  HOWEVER, this data must be converted to a valhalla-usable format per the build documentation in the "Readme.md" here (https://github.com/valhalla/valhalla)

I am using Ubuntu 14.04.

*Building the Tiles*
I downloaded the planet.osm.pbf as of 12-25-2017 from one of the mirrors recommended on the OSM web page (yay).  I ran the following to build a "usable" tileset:

`valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json`

`valhalla_build_tiles -c valhalla.json planet.osm.pbf`

`find valhalla_tiles | sort -n | tar cf valhalla_tiles.tar --no-recursion -T -`

*Running the Service*
I tested starting the Valhalla routing service like so: `valhalla_route_service valhalla.json 1`. I tested with some curl commands and got some responses.

**Broken**
I tested running the docker container:
` docker run -d -v /path/to/valhalla_tiles:/data/valhalla -p 8002:8002 --name valhalla valhalla/docker:ppa-1.4.5`

I got an error in the console:

[WARN] Tile extract could not be loaded

Subsequent curl commands yielded errors.  The `/path/to/valhalla_tiles` is the same directory which is listed in the `valhalla.json` created above with the `${pwd}` variable.

*Testing the Service*

To test whether I have the service set up correctly, I tested routes between familiar locations in NYC.  I tested against `valhalla.mapzen.com`, and against my new service on my local machine.  I tested lat,lons for the following addresses, and asked for routes (using `/route`) to / from each of them:

- 9 w 57th st
- 660 Madison Ave 
- 476 5th Ave

For `walking` directions, I got the same exact results between both valhalla.mapzen.com and my local service for all routes.  

For driving and cycling, the results varied.  This leads me to believe that *there is data being used in getting valhalla set up that is omitted from the documentation*.  For example, consider the (abbreviated) routes suggested for driving from 9 w 57th St to 315 7th Ave:

```
Directions from mapzen: start on W 57th St, left on 9th Ave, left on W 28th St, right on 7th Ave, end
Directions from local service : start on W 57th St, left on 9th Ave, left on W 34th St, right on 7th Ave, end
```
The discrepancy in distance here is not egregious; but there has to be some accounting for the differences between what is served at mapzen.com and what I have set up by following the instructions given on the readme for this repository.

Pretty much all of the driving / cycling directions differ between the two services (mapzen and local), and the above is just a semi-readable example.

**Comment by kevinkreiser** [comment]
when you say documentation, do you mean the `valhalla-docs` repo? that repo was meant to be http API docs only. maybe we should have named it `valhalla-api-docs`. all the information about running valhalla yourself can be found in this repo and directly in the `README` as you have found out.

when you ran docker above you have to fill out `/path/to/valhalla_tiles` with the actual path to the location where you built the tiles. in your case it was `${PWD}/valhalla_tiles`. you have to give the docker container access to the tiles you built.

as per different results... the mapzen tiles have transit and elevation data baked into them. you likely do not. driving directions can differ when the OSM data changes (and it changes minutely). so if you dont have the exact same data that mapzen had you can expect some different results.

**Comment by jvparkourm** [comment]
@kevinkreiser Thanks so much for the prompt response!  Is there any way to get transit and elevation data, such that it can be "added to" the OSM ways or otherwise used in the tile generation for valhalla_route_service?  I did not see this information during my browsing, but there is a lot of documentation; I probably just missed it :).

**Comment by dnesbitt61** [comment]
Now that we are no longer part of Mapzen, the pipeline for getting transit data is undefined for now. You can get elevation data using valhalla_build_elevation inside the scripts directory.

**Comment by aparnagottumukkala** [comment]
where is the trace_attributes functionality written in valhalla which is under map matching. My request to that would be sequence of lat, longs specifically looking for edge names. And how that code is checking against the OSM.pbf files.My main goal is to find the bus route based on the lat longs of a region.
