### ISSUE TITLE
No valhalla_service executable in ppa?

### ISSUE THREAD

**Issue by Flohack74** [valhalla/valhalla#1074]
Hi,

with the ppa method I cannot run a server with valhalla_service <arguments> since there is no such executable. Is the documentation out of date or the ppa build is missing smth?

**Comment by kevinkreiser** [comment]
The ppa was only updated on friday. If you installed it before friday this binary was named `valhalla_route_service`. Also if you are using trusty we are no longer building packages for it so it will also use this old named binary

**Comment by Flohack74** [comment]
Ok thanks works ;)
