### ISSUE TITLE
Meili service is slow on embedded devices

### ISSUE THREAD

**Issue by chrisfosterelli** [valhalla/valhalla#1081]
Hi all,

We're working on using Valhalla's Meili subsystem in an embedded context, and discovering that it takes substantial time to run for our device (2.5 seconds) for input vectors containing only a single point.

If we provide no tile data or if the input vector is empty, the task is very quick. However as soon as we add a single point on a real tile set it becomes a 2-3 second operation. Adding more points does not seem to increase the runtime noticeably (we're using this in an online context so we've been testing with 50-200 input vector lengths).

Do you know what is it that leads to this 'base cost'? Is there any way to improve this? It seems unaffected by the number of points provided so I'm wondering if there is an optimization possible here on our end. I've read through the map matching paper and it seems like the operation should scale up with the number of points instead of having a high base cost, but I'm likely misunderstanding something involved. We've also tried tweaking the parameters but it doesn't seem to affect much.

We're using an older version of Valhalla (when Meili was a separate project) if that's relevant, but working on updating to the latest. The current device is a ARM Cortex A5 but we'll be testing on a A7 soon.

Specifically we are timing the `OfflineMatch` function.

The tiles are stored as gph (raw files) on a ubifs-type filesystem. The tiles are an 18MB extract of the Greater Victoria Area in BC, I can provide the exact files if it's useful. The behaviour made me suspect that it may be I/O-bound, however when I watch the output of `vmstat` the process uses very little I/O and almost all of the processor on the device so I believe it's CPU-bound.

**Comment by kevinkreiser** [comment]
Given that its very old code, I would really suggest that you update to the latest and try that. It would be near impossible for us to debug it at this point as the code has been significantly refactored since it was its own repository.

**Comment by chrisfosterelli** [comment]
@kevinkreiser Sounds good, we'll work on that and report back once we get these cross-compile issues with the dependencies sorted. Not sure if you'd be familiar with this but would you expect the A5/A7 to be able to handle map matching?

**Comment by kevinkreiser** [comment]
i dont see why not... the process itself is cpu intensive based on the density of the graph, number of input points, and radii used at each point. its really just a one-to-many dijkstra between each pair of candidates.

**Comment by dnesbitt61** [comment]
In particular, there were changes to optimize the candidate search process (especially the IndexBin method if I recall) that hopefully are a large part of the slowness you see.

**Comment by chrisfosterelli** [comment]
Hey guys, on the latest version of Valhalla we're seeing reductions from 2.5seconds down to 200ms. So much faster, thank you!
