### ISSUE TITLE
valhalla_build_tiles is very slow on small maps

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#1083]
Over in https://github.com/Project-OSRM/osrm-backend/pull/4839, I'm attempting to run some of OSRM's test scenarios against Valhalla to do some side-by-side comparison of turn-by-turn instruction generation.

The way the test suite works is:

  1. Generate a small (usually ~5 node, 2-3 way) OSM XML file for the test scenario.
  2. Convert it to `.pbf` format using `osmium`
  3. Generate a `valhalla.json` file in a clean directory
  4. Call `valhalla_build_tiles` using the generated `.pbf` and the `valhalla.json` from (3)
  5. Make a tarball of the generated tiles.
  6. Run `valhalla_service` using the generated `valhalla.json`, and run some `/route` queries against it.
  7. Convert the response JSON into a common format and compare to the expected test results.

This process basically works, *but* step (4) is very slow - it takes about 25 seconds for `valhalla_build_tiles` to complete on a single tiny test map (<1kb of data).
For comparison, OSRM's pre-processing tools take about 0.25s to prepare the data for routing.

There are about 600 scenarios/maps that I want to run this against - that's 4+ hours of just running `valhalla_build_tiles` with the current speed.

Are there any quick-n-easy ways I could make `valhalla_build_tiles` run faster?

<details>
  <summary>Example OSM XML file</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm generator="osrm-test" version="0.6">
  <node id="1" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.0000449533968134" lat="1.0">
    <tag k="name" v="a"/>
  </node>
  <node id="2" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.0000449533968134" lat="0.9999550466031865">
    <tag k="name" v="b"/>
  </node>
  <node id="3" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.0" lat="0.999820186412746">
    <tag k="name" v="c"/>
  </node>
  <node id="4" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.000089906793627" lat="0.999820186412746">
    <tag k="name" v="d"/>
  </node>
  <node id="5" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.0001348601904405" lat="0.9997302796191189">
    <tag k="name" v="e"/>
  </node>
  <node id="6" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.0" lat="0.9994156058414242">
    <tag k="name" v="g"/>
  </node>
  <node id="7" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z" lon="1.000089906793627" lat="0.9994156058414242">
    <tag k="name" v="f"/>
  </node>
  <way id="8" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z">
    <nd ref="1"/>
    <nd ref="2"/>
    <tag k="highway" v="primary"/>
    <tag k="name" v="road"/>
    <tag k="oneway" v="no"/>
  </way>
  <way id="9" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z">
    <nd ref="2"/>
    <nd ref="3"/>
    <nd ref="6"/>
    <tag k="highway" v="primary"/>
    <tag k="name" v="road"/>
    <tag k="oneway" v="yes"/>
  </way>
  <way id="10" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z">
    <nd ref="7"/>
    <nd ref="4"/>
    <nd ref="2"/>
    <tag k="highway" v="primary"/>
    <tag k="name" v="road"/>
    <tag k="oneway" v="yes"/>
  </way>
  <way id="11" version="1" uid="1" user="osrm" timestamp="2000-01-01T00:00:00Z">
    <nd ref="5"/>
    <nd ref="4"/>
    <tag k="highway" v="primary"/>
    <tag k="name" v="turn"/>
    <tag k="oneway" v="yes"/>
  </way>
</osm>
```
</details>

**Comment by dnesbitt61** [comment]
It looks like perhaps 6 seconds is spent in HierarchyBuilder walking through the local tiles (and skipping over all empty ones). This is done when creating node associations. Passing in a list of local tiles (maybe from the build tiles stage) would speed this up.

It is also done in UpdateTransitConnections (which is not even needed since no transit exists). Adding a flag to indicate whether transit is even present would be a quick and easy way to bypass this method.

**Comment by dnesbitt61** [comment]
Identifying no transit helps remove 2 iterations through the potential list of tiles, saving 5-6 seconds. PR #1084 does this.
There are still 3 points where the entire list of possible local tiles are iterated and checks to see if the file is on disk are made - each of these steps takes approximately 2 seconds. So perhaps forming a set of local tiles in the Build stage and using that set in the enhancer, hierarchy builder, and validation stage could save even more time.

**Comment by kevinkreiser** [comment]
i would suggest we just iterate over what is in the directory each time we need an exhaustive list. even the world wide tileset is something like only 15% (150k out of 1m tiles) of the total number of possible tiles. i think this will be the most robust way to do things and wont require passing even more state between stages of tile making. that said, its not a huge deal to pass more state i guess
