### ISSUE TITLE
Node Binding

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1085]
So lets face it, `libvalhalla` is pretty nice but it is a c++ library. That means for more casual users its harder to make use of. We provide a ton of ways to access it already: http, binary packages, python bindings and the devel libraries. Right now those options are kind of limiting. It would be nice for the javascript crowd to get in on the action and truth be told javascript (esp. node) is pretty popular right now.

As a first pass we should offer nodejs bindings that are basically the same as the python ones. That means just wrapping the `init` stuff and the `actor` class. With just these two bits you can run an entire valhalla server for all of the different http apis we support.

Further down the road we should consider wrapping the more detailed bits like individual functionality from different parts of the library. This can be done on a case by case basis. It would be unfortunate to have to wrap everything when only some of the things are useful. Additionally most of the low level stuff doesnt take JSON as input or produce it as output so that makes things more annoying. Places where we have other easy to use interchange formats like PBF would be easier candidates for this since that's just, like, your bytes, man.

One other thing to consider here is that both node and python have pretty decent built-in HTTP servers.  By exposing these bindings and adding a small nodejs and python server example we could remove prime_server from the set of valhalla dependencies. removing dependencies is good IMHO but it would mean that every time we added something new we'd need to expose it in the bindings' wrappers. This may be automatic a la convention so its probably not a big deal. Frankly I think its a bit risky as we dont yet have a handle on the performance characteristics or pitfalls of running these servers in production.

Ok so what is the work:

- [ ] get some empty bindings or `hello world` bindings building in the project
- [ ] wrap the `init/configure` method in the binding to start
- [ ] wrap the `actor_t` class and expose all of its methods
- [ ] write small python and nodejs servers using the binding
- [ ] optionally remove `valhalla_service` and minimize the `worker` stuff in favor of running this through python or node. this is a small amount of work for not a lot of gain... because it means porting boilerplate stuff from `worker` to both nodejs and python so that people can have a decent server experience. it also means users need to install more than just the valhalla binaries but maybe thats nothing major.

Another big question of this work which we will find out quickly is how we want to actually do the packaging of node modules. Looks like options include `gyp` and the way more full featured `mason`. Upon first glance, `gyp` seems to be the thing you want if you just want to do a native node module whereas `mason` looks like a full package making suite. Because `mason` is more than what we need at the moment and is designed for `cmake` (we use `autotools`) it might be easier to just stick with `gyp` to start. We'll need to look into both to make the right decision.

**Comment by allierowan** [comment]
We have node bindings in place with all `actor_t` methods exposed! I am going to open a new ticket about using the bindings in place of valhalla-svc.
