### ISSUE TITLE
Roundabout Exit Number is always 2

### ISSUE THREAD

**Issue by farough** [valhalla/valhalla#1099]
Hi,

We've been hosting our own server after having used the Mapzen servers in the past. Everything appears to be working fine, however, we recently noticed the roundabouts give a strange exit number.

It doesn't appear to matter which roundabout we're testing or which exit is required, the text and roundabout exit number is **always** 2. This happens for **driving**, **cycling** and **walking** directions.

I've been looking through the code and testing various places, but I'm really not sure what is happening. We see the same behaviour if we get the server code directly or build it from source.

Direct: 
**grab all of the valhalla software from ppa**
sudo add-apt-repository -y ppa:valhalla-core/valhalla
sudo apt-get update
sudo apt-get install -y valhalla-bin

Source: 
git clone git@github.com:valhalla/valhalla.git

Please advise why this might happen or how we might debug this issue. Thank in advance,

Matt

**Comment by dnesbitt61** [comment]
I do not see this behavior with routes I just tested. Do you have an example URL?

**Comment by farough** [comment]
Hi,

Sorry, just to clarify, I don't see this problem when I test it against the test server, only on our own compiled from source or installed directly as I said above.

Here is an example path that gives us exit number 2, only when we're hosting it.
/route?json={%22costing%22:%22bicycle%22,%22costing_options%22:{%22bicycle%22:{%22bicycle_type%22:%22City%22,%22use_ferry%22:0.5,%22use_hills%22:0.5,%22use_roads%22:1.0}},%22directions_options%22:{%22language%22:%22en_US%22,%22narrative%22:%22true%22,%22units%22:%22kilometers%22},%22locations%22:[{%22heading_tolerance%22:45,%22lat%22:45.52126,%22lon%22:-73.64922,%22minimum_reachability%22:50,%22radius%22:0},{%22heading_tolerance%22:45,%22lat%22:45.5198944408425,%22lon%22:-73.65111630409956,%22minimum_reachability%22:50,%22radius%22:0}]}&api_key=<**API_KEY**>

On the map, this is obviously not the second exit, but the text and exit number variables come back as 2. This seems to happen for all roundabouts anywhere in the world, far as I can tell though. Even roundabouts that only have one exit.

Hope that helps, let me know if you need any other information.

**Comment by farough** [comment]
Local host:
![screen shot 2018-02-21 at 1 47 09 pm](https://user-images.githubusercontent.com/16922104/36498953-dffb4c4c-170d-11e8-9dbc-c7b9c58e1ab9.png)

Valhalla Demo Server:
![screen shot 2018-02-21 at 1 47 22 pm](https://user-images.githubusercontent.com/16922104/36498977-ec71f354-170d-11e8-92bc-06e7a4881fcc.png)

Here's a side by side, I don't understand why they are different.

**Comment by farough** [comment]
Do you have any ideas why this might happen? This is already on our production server, so we'd like to solve this issue as soon as possible. I've tried including admin data, which we had trouble generating, but it didn't help. 

Looking through the code a bit I just don't understand how it's possible that it always returns 2 as the exit number.

**Comment by dnesbitt61** [comment]
Can you create a small data set (using an individual state or province from Geofabrik for instance) and test locally? Create a URL to localhost and see what the response is? I could then run the same test here (if you give me the URL) and see if the behavior is the same. I am not sure what could be happening since when I do local testing it looks good. After that if problem is still present for you perhaps you can share your data set and I can test with code on my laptop to see if it might be an issue with the data import.

**Comment by farough** [comment]
That's exactly the test I ran above. I'm using Quebec, Canada to build a local server and asking it for directions. That specific roundabout above is in Montreal. https://www.google.ca/maps/@45.5209792,-73.6502961,17.49z

What kind of data do you need from me? My tiles tar file is 450mb.

**Comment by dnesbitt61** [comment]
Can you share the tar file on Dropbox or somewhere I can download it and test it locally?

**Comment by dnesbitt61** [comment]
you can email me: david.nesbitt@mapbox.com

**Comment by dnesbitt61** [comment]
This can be caused if the "drive_on_right" flag is not set properly during data import. This would indicate an issue with admin processing (or with the config file pointing to the admin.db during tile building).

**Comment by farough** [comment]
Hmm, really? If this were the case wouldn't it both say "take exit number 1" above and draw the polyline going clockwise instead of counterclockwise? Since it's using the same tile information to determine the path? 

Also, I know I've already mentioned it, but it is worth noting that the exit number seems to always be 2. This feels like a default count somehow to me if the properties of the roundabout are having no impact on the output.

![screen shot 2018-02-26 at 11 29 11 am](https://user-images.githubusercontent.com/16922104/36682261-a5622d24-1ae8-11e8-8486-269dfe0bbc74.png)

![screen shot 2018-02-26 at 11 29 45 am](https://user-images.githubusercontent.com/16922104/36682273-aec56a2a-1ae8-11e8-98fe-dbfad548fd5b.png)

![screen shot 2018-02-26 at 11 30 24 am](https://user-images.githubusercontent.com/16922104/36682282-b4c8640e-1ae8-11e8-8de3-e4a0cbe6138d.png)

**Comment by dnesbitt61** [comment]
It does not use drive_on_right to determine oneways and access - so it goes around the roundabout ccw as it should to obey the oneway direction of the roundabout. I evaluated what is different between your data and the data I imported locally and noted the drive on right flag is incorrect. I did not evaluate why it results in roundabout exit count = 2 in these cases.

**Comment by farough** [comment]
Using admin tiles I downloaded for the whole world solved this issue. I got these tiles from here.
https://github.com/gknisely/data/blob/master/admin_2017_07_28-08_45_01.sqlite

Not sure if they will always be available. Either way, this artifact appears to be caused by a bad admins sql file. I will close this case now.

**Comment by gknisely** [comment]
@farough you can always build a planet wide admin db by getting a copy of the planet pbf and running valhalla_build_admins on it.  Glad to see that you are up and running again.

**Comment by farough** [comment]
@gknisely we've tried this several times in the past, but I'm seeing an error like the one in this ticket whenever we try.

https://github.com/valhalla/valhalla/issues/877

I know it says the ticket is supposed to be fixed and resolved, but this same issue is occurring for us now. I have not tried to use print statements in the source code to investigate the issue yet though.

**Comment by gknisely** [comment]
I have not executed valhalla_build_admins in awhile.  I will have to try it out.  Usually it is a bad polygon or name change.  We actually only build this like once a year.  It does not change that much.

**Comment by farough** [comment]
@gknisely this makes sense. But if you don't have any way to get it, it's quite essential to have somewhere to download it, that's why I thought I'd post it on this thread in case anyone else runs into this situation.
