### ISSUE TITLE
Make the waypoint serializer common so that it can be used by route, locate, matrix, etc.

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#1116]
This work is for the project to create an OSRM response from within Valhalla.   We need to create [waypoints](http://project-osrm.org/docs/v5.15.2/api/#waypoint-object) from Valhalla in order to be compatible.  
TODOs:
- [x] Move Location from tripcommon to directions_options.
- [x] Update Location to have the attributes that PathLocation contains.
- Expand this: https://github.com/valhalla/valhalla/blob/master/proto/tripcommon.proto#L13
so that it includes all the stuff from:
https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/pathlocation.h
- Notice that pathlocation is the same as location, but adds this thing called `pathedge`
- We will want to make a `message type pathedge` and then add `repeated string names` to `path edge`.
- Also, we need to add a `bool used` to `path edge`
- [x] Change all the services use locations from directions_options instead of from JSON.
- [x] Start writing a serializer for Location
- [x] Update the serializers to use Location.
- [x] Get unit tests passing again..
- [ ] Test all the valhalla actions and options things!
- [ ] Test all the osrm outputs!

**Comment by dnesbitt61** [comment]
Sample URL:
http://localhost:8002/route?json={"locations":[{"lat":39.626432,"lon":-75.951631},{"lat":39.63791,"lon":-75.945121}],"costing":"auto","directions_options":{"language":"en-US"}}&format=osrm

**Comment by kevinkreiser** [comment]
the `waypoints` branch contains a lot of work towards this with a bunch of bonus moving to protobuf for all IPC. my status is that ive gotten it compiling and the tests passing but i think we need to do a bunch of checking that things work they way they should for all of the different options etc as the chance of a regression here is high (with the sheer amount of refactoring).
