### ISSUE TITLE
On the fedora build

### ISSUE THREAD

**Issue by PayasR** [valhalla/valhalla#1127]
As of today, I was able to cleanly build and run valhalla on my F27 machine :)
If https://github.com/kevinkreiser/prime_server/issues/41 can be fixed, I should be able to make valhalla available on the fedora COPR quickly. @kevinkreiser could you please have a look?
Thanks!

**Comment by kevinkreiser** [comment]
the above has been fixed. im going to close this for now and we can open other issues to track other impediments to a fedora build
