### ISSUE TITLE
osrm compatibility issue: unconnected regions

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#1128]
We are getting the following error with when trying to run a route with a data converted for a particular region.  

code | "InvalidValue"
message | "The successfully parsed query parameters are invalid."

Steps to reproduce.  1.  Convert PA data.  2.  Run the following route:
http://localhost:8002/route?json={%22locations%22:[{%22lat%22:0.9991009320637295,%22lon%22:%221.0%22},{%22lat%22:0.9991009320637295,%22lon%22:1.0008990679362704}],%22costing%22:%22bicycle%22}&format=osrm

You should see the above error.

**Comment by kevinkreiser** [comment]
i dont understand what the issue is here? what should the response be? you are asking for a route at `1,1` which is the ocean right?
