### ISSUE TITLE
optimized_route corrupted output?

### ISSUE THREAD

**Issue by durkie** [valhalla/valhalla#1135]
Hi all -- if I build the valhalla repo (cloned today) and add stock OSM data for Atlanta area, the optimized_route endpoint seems to give out garbage/incomplete data:

This request:
```
GET /optimized_route?json={%22locations%22:[{%22lat%22:33.790098,%22lon%22:-84.362211,%22type%22:%22break%22},{%22lat%22:33.796802,%22lon%22:-84.380708,%22type%22:%22break%22},{%22lat%22:33.796125,%22lon%22:-84.357705,%22type%22:%22break%22}],%22costing%22:%22bicycle%22}&api_key=
```

results in this response:
```
HTTP/1.1 200 OK
Content-type: application/javascript;charset=utf-8
Access-Control-Allow-Origin: *
Content-Length: 4704

î ({"id":"\n\n\rí\/\u0007B\u0015ìÂ¨Â\u0010\u0000X\u0002`\u0001j\n\rÜ\/\u0007B\u0015ìÂ¨Â","trip":{"language":"en-US","summary":{"max_lon":-84.357727,"max_lat":33.797222,"time":519,"length":2.478,"min_lat":33.794525,"min_lon":-84.380707},"locations":[{"original_index":1,"type":"break","lon":-84.380707,"lat":33.796803,"side_of_street":"left"},{"original_index":2,"lon":-84.357704,"lat":33.796124,"type":"break"}],"units":"kilometers","legs":[{"shape":"agxm_Adae}_D?sP?_qAFk_ALyC^wCaDkAmDyBgNkLsBuDcAeEOuEd@qGjBcRl@eO\\iW\\eFjBkKT}Il@{`@\\kLt@eEhB}JxH_IfDiC~HuDl^wXhMmUjBoH~Har@jAaG`CqHnDqGlEsFrFwDfIeEbLwClDkAxBkBlAiB~B_Jk`@{_@kFsFm@m@qGqGiMiMkGcG_S_SoSqR{A{AiCiCuOeO_IqHaB{AyH_Hj`@c\\~X}TsAgD]eEN}pBL_dDFqpATw|DFgNNsG?en@l@mJrAqG","summary":{
...
```

There is a strange character at the beginning of the JSON output that prevents it from being properly parsed, and the `"id"` field is full of unusual characters. The output of valhalla_service is this line over and over:
```
[libprotobuf ERROR google/protobuf/wire_format.cc:1091] String field 'jsonp' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

Additionally, the polyline appears to be incomplete, connecting only 2 of the 3 destinations.

This problem appears regardless of costing method (bicycle or auto) and the `"id"` field doesn't change if I supply my own in the initial request.

Any ideas about what might be going on?

**Comment by kevinkreiser** [comment]
I'm sure this is my fault we are in the middle of changing over all of the internal object representations (between stages of the pipeline) into pbf. i'm sure i just messed something up. i'll check it out later today.

**Comment by durkie** [comment]
thank you! works great now.
