### ISSUE TITLE
valhalla_service crash/runtime error with latest master

### ISSUE THREAD

**Issue by Rui-Santos** [valhalla/valhalla#1137]
I built Valhalla from the latest master, and it built successfully, but when running valhalla_service it abruptly crashes as soon as it starts with the following error

```
2018/03/08 12:25:57.202052 [INFO] Tile extract successfully loaded
terminate called after throwing an instance of 'std::runtime_error'
  what():  Action not supported one_to_many
Aborted (core dumped)
```

I'm compiling the test suite now and will update the issue if any test fails.

**Comment by kevinkreiser** [comment]
we removed that as a valid action but its still in your config file. just regenerate your config or delete those `*_to_* ` actions from your existing config and you'll be fine :smile:

**Comment by Rui-Santos** [comment]
Oh, OK. Will do. Thank you!
