### ISSUE TITLE
Is there a way to specify OSM ways to avoid when doing point-to-point routing?

### ISSUE THREAD

**Issue by araichev** [valhalla/valhalla#1143]
I'd like to build a map to simulate road closures.
Basically the user would pick some OSM ways to block and then drop pins for point-to-point routing that avoids those ways.
Is this possible using Valhalla, either via the Mapbox web service or via an on-premise Valhalla installation?

**Comment by dnesbitt61** [comment]
You can specify avoid_locations. See the API doc under: https://github.com/valhalla/valhalla-docs/blob/master/turn-by-turn/api-reference.md (search for avoid_locations). These are lat,lon locations so Valhalla finds the nearest edge and excludes it from the route.

**Comment by araichev** [comment]
Thanks!
