### ISSUE TITLE
Categorize Performance Impacts that Historical Traffic Might Have

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1147]
Creating a time-sensitive routing method that uses a historical traffic model may be desirable. It is likely that a uni-directional A* method would be required and that shortcuts may not be useful (without special processing of traffic information to add the information to shortcuts as well as regular edges.

To simulate the performance difference that might be expected, we should run some route tests which compare A* to bidirectional A* and also with and without shortcuts.

**Comment by dnesbitt61** [comment]
Running some path finding performance tests using valhalla_run_route (using Lenvoa X1 Carbon with 16GB RAM). This runs a single route, generating the path multiple times in succession to warm the tile cache. The average time over 50 runs is presented. All cases use the planet tar file with memory mapping. Two costing methods were used to determine edge weight: default auto (edge length * speedfactor[speed]) and a simulated edge weighting that uses edge density, highway factor (based on road classification), and weighted grade to generate small factors that perturb the speed very slightly (so the route remains the same). This simulates adding speed computation from a function.

Three route cases were used: 
Mapbox DC to Port Deposit,MD (133km, 1hr 38 min)
Lancaster, PA to Pittsburgh, PA (390km, 3 hr 45 min).
Munich to Berlin: (585km, 5 hr 42 min)

Default auto costing using bidirectional A* with shortcuts:
DC to Port Deposit: 23ms
Lancaster - Pittsburgh: 30ms
Munich - Berlin: 51ms

Default auto costing using A* (forward search only):
DC to Port Deposit: 51ms
Lancaster - Pittsburgh: 26ms
Munich - Berlin: 74ms

Default auto costing using A* (forward search only) without shortcuts:
DC to Port Deposit: 65ms
Lancaster - Pittsburgh: 41ms
Munich - Berlin: 138ms

More complex auto costing using A* (forward search only) without shortcuts:
DC to Port Deposit: 67ms
Lancaster - Pittsburgh: 42ms
Munich - Berlin: 137ms

The performance of the pathfinding algorithm is highly correlated to the number of iterations in the "inner loop" or expansion of the graph search. Extra logic added to costing has much less impact than logic that either prunes or expands the search. Shortcuts and bidirectional A* prune the search compared to A* without shortcuts, so these algorithms are faster than single direction A* without shortcuts.  

Another factor that could impact performance for driving routes with traffic is the highway hierarchy pruning logic. Expanding the hierarchy transition zones to be larger (search more local and arterial roads - further from the origin and destination) can make a large impact on performance. Expanding these zones by a factor of 4 leads to a more dramatic performance drop (using A* without shortcuts):

Expanded local and arterial hierarchy "zones" (A* without shortcuts):
DC to Port Deposit: 108ms
Lancaster - Pittsburgh: 155ms
Munich - Berlin: 565ms

Conclusions:
Analysis of quality vs. performance trade-offs will be needed to tune the hierarchy zones, as this setting has the most impact on performance of A*. Some expansion is likely desirable with traffic influenced routing, but care needs to be taken to keep performance reasonable. 

Retaining shortcuts may be difficult (on the predictive traffic generation side) but would be worth investigating. 

Also, capping the length of routes supported by a full, traffic and time dependent A* algorithm is likely needed. For long routes perhaps a hybrid approach where bidirectional A* is used and one direction uses time dependent, traffic costing, while the other directions does not. For example, in a long route departing at 7am the forward search would consider time and predictive traffic, but the reverse part would not. This would simulate the uncertainty of knowing what time the user may actually traverse parts of the route many hours into the future. This concept would need further development and testing of course but could provide reasonable performance over longer routes while still providing some traffic influence over the initial part of the route.

**Comment by morganherlocker** [comment]
> weighted grade to generate small factors that perturb the speed very slightly (so the route remains the same). This simulates adding speed computation from a function.

Is this grade computed at runtime only, or is a coefficient lookup simulated? Presumably you would need to store (in memory or on disk) something like 5-10 coefficient floats per edge.

**Comment by dnesbitt61** [comment]
weighted grade is just a factor stored in the data. I used that along with a couple other factors and some floating point operations to create a small factor to modify speed with. Just added a few loopkups from the edge data structure and some floating point multiplications to simulate  extra math within the edge cost method. Hopefully did it in such a way that the compiler didn't optimize the code away.

**Comment by morganherlocker** [comment]
> Just added a few loopkups from the edge data structure

Awesome. Is there a way to anticipate or simulate the effect of more lookups? The more we have, the more accurate the predictions will be. Would having dozens of lookups significantly impact performance or RAM usage?
