### ISSUE TITLE
running as non privileged user?

### ISSUE THREAD

**Issue by durkie** [valhalla/valhalla#1156]
Running `valhalla_service` as any user but root on Ubuntu results in this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Address already in use
Aborted (core dumped)
```

This is unclear. No other valhalla service is running so there shouldn't be anything else binding to the address. If I change the interface to be just 127.0.0.1 and port to any other port (greater than 1023), I still get the error. Altering permissions of the various sockets created in /tmp doesn't seem to have any effect either. Ideas?

**Comment by kevinkreiser** [comment]
it drops those ipc sockets on the fly. id say delete those or edit your config file to use other ones to test that part of this out. that being said `address already in use` makes me think its the tcp socket not the ipc ones...

before you run it can you check what ports are in use with `netstat` and be really really sure? also how are you running valhalla exactly? i have never run into this other than when i actually had two services running at once. are you sure you arent running a docker container at the same time that is exposing this port to the host (ie binding on it)

**Comment by durkie** [comment]
ah you're right -- deleting the ipc sockets altogether solved it.
fwiw, i run the service via `valhalla_service valhalla.json 1`

**Comment by kevinkreiser** [comment]
you must have run it once as a `sudo` and then after that you could only run it as `sudo` until you deleted them. glad you got it worked out!
