### ISSUE TITLE
Ubuntu 17.10 support

### ISSUE THREAD

**Issue by stvno** [valhalla/valhalla#1166]
Are there plans to build packages for Ubuntu 17.10? I'm trying to get it running on 17.10 but I'm running into dependency problems where the pakcages are requiring older version of libraries than available.

**Comment by gknisely** [comment]
Why are you looking to support/use 17.10?  We target long term support which will be 18.04.  This is will be released in a month.

**Comment by stvno** [comment]
Ah LTS only makes sense. I was trying to test something locally and that machine was 17.10 and was wondering why there were no packages for anything after 16.04.

**Comment by carlos-mg89** [comment]
It's still not available on Ubuntu 18.04 (tested today).

I've added a comment in this issue as well https://github.com/valhalla/valhalla/issues/708
