### ISSUE TITLE
dinamic maxspeed

### ISSUE THREAD

**Issue by geography** [valhalla/valhalla#1171]
Hi there, first of all thanks for the great work done with valhalla.

I have a question to ask: 
where I can put in the request route the maxspeed tag in order to use a fixed speed? there are some example in doc where I can read?

thanks in advance,
Ema.

**Comment by dnesbitt61** [comment]
Not sure I understand the intent. Valhalla imports OpenStreetMap data in pbf format and uses the maxspeed tags during route path computation and estimating time along the path. If you were able to edit/add a maxspeed tag to every way in the OSM pbf data you want to import then you could inject a fixed speed.

**Comment by kevinkreiser** [comment]
Maybe what is meant here is passing in a fixed speed of travel like we have for bikes and pedestrian routes. Basically ignore the maxspeed data that we get from osm in favor of a user specified speed

**Comment by geography** [comment]
Hi @dnesbitt61 @kevinkreiser my intent is to use maxspeed tag from osm data as explained in this link:[https://github.com/valhalla/valhalla-docs/blob/master/speeds.md](url), but in my osm data the only existings tags are maxspeed_forward and maxspeed_backward. Is there any relation betwen the formers and the latters? If so how can I build my request in order to use my osm data tags? 

Regards,
Ema.

**Comment by kevinkreiser** [comment]
@geography we use all of the speed tags if they are present including `maxspeed:forward` and `maxspeed:backward`. For us what those mean is that traveling in one direction along the way has one speed and the other direction along the way can have another speed. In this case the direction that the nodes in the way are orderer determines the forward direction.

I would guess, without looking at the code that if `maxspeed:forward` or `maxspeed:backward` are present then they would take precedence over `maxspeed`. @gknisely will probably know without looking.

You cant do anything with your request to make sure its using the tags. The use of the speed tags is determined at tile data creation time (so not at run time). We bake the speed data into the tiles for each graph edge. So if your data has the proper speed tags in there then the tiles you create with that data will use those speeds by default.

**Comment by geography** [comment]
@kevinkreiser thanks for quick reply and sorry for my delay in answering now I got your point.

Ema
