### ISSUE TITLE
Transit isochrone is wildly inaccurate in Berlin

### ISSUE THREAD

**Issue by aardila** [valhalla/valhalla#12]
Using the [Mobility Explorer](https://mapzen.com/mobility/explorer), the isochrone with a starting point in [Schönefeld Airport](https://mapzen.com/mobility/explorer/#/isochrones?bbox=13.514149188995361%2C52.38660141430136%2C13.528075218200682%2C52.390661071355865&isochrone_mode=multimodal&pin=52.38901455442912%2C13.518649399411514) shows that it would take significantly more than 60 minutes to reach the city center. A quick look in any of the transit agencies in Berlin ([BVG](http://www.bvg.de/en/), [VBB](http://www.vbb.de/en/index.html), or [S-Bahn](http://www.s-bahn-berlin.de/en)) show that this trip normally takes between 30 to 50 minutes depending on the route.

Such inaccuracies are widespread for any location chosen in the Berlin area. I haven't found a single location which reports correct information.

We were thinking of using the Mobility API for a project at university, but unfortunately the public transport data for Berlin is unusable. It seems to be in the registry at Translitland and I know for a fact that the City makes GTFS data publicly available, so I'm not sure where the problem is. Any help would be appreciated.

**Comment by gknisely** [comment]
Hello,

The Berlin feed is not at import level 4 yet.  This means that it will not
show up in the the valhalla routing software.  I have contacted the
Transitland team to find out why the import level is not set to 4.  Most
likely it has not been validated yet.

I will let you know ASAP.

Thank you for reporting this issue.

--Greg.

**Comment by aardila** [comment]
Thanks for the quick response @gknisely. I don't know what "import level 4" means (nor does it seem to be referenced in the transit.land [registry entry](https://transit.land/feed-registry/operators/o-u33d-berlinerverkehrsbetriebe)), but I assume it means it's not yet ready to be used as a reliable data source. I take it that would also be the reason why a `multimodal` query to Valhalla in Berlin returns `{"error_code":440,"error":"Cannot reach destination - too far from a transit stop","status_code":400,"status":"Bad Request"}`.

Looking forward to your response and hopefully a solution so that we can your API (which we were very much looking forward to doing.) Thanks again!

**Comment by kevinkreiser** [comment]
@aardila yes this is exactly what it means. it means that the feeds covering berlin are not yet imported into valhalla. folks on the transitland team are looking into this.

**Comment by aardila** [comment]
Thanks @kevinkreiser. I did a bit of digging around to see how I could help fix the problem and made a comment with my findings to [this issue over at the Transitland issue tracker](https://github.com/transitland/transitland/issues/56). If there's anything I can do to help, don't hesitate to let me know. Cheers!

**Comment by kevinkreiser** [comment]
@aardila Kein Problem. Es sieht so aus als kommen wir der Sache ja näher. Hoffentlich können wir irgendwie (Bisschen Muskelschmalz) die jenigen Dateien verwenden, die Sie uns vorgeschlagen haben!

**Comment by arne7morgen** [comment]
Is there any progress with this issue. I am also very interested in Berlin.

**Comment by gknisely** [comment]
I am checking with the Transitland team.

**Comment by irees** [comment]
There was an issue with how the updated Berlin feed uses nested zip files ( https://github.com/transitland/transitland-datastore/issues/1022 ); this has been fixed and should be part of the next production release later this week.

**Comment by gknisely** [comment]
This should be resolved.  If it is not please reopen.   
Thanks.
--Greg
