### ISSUE TITLE
enhance() step very slow on macOS due to heavy lock contention

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#1201]
When running `valhalla_build_tiles` on `us-west-latest.osm.pbf` on macOS, I noticed that the `Enhancing local graph...` step took over an hour alone.  Speaking to others about this, it seems that this runs significantly faster on Linux.

Examining the code under a profiler revealed that nearly 60% of the total run time was spent in `std::mutex.lock()` and `std::mutex.unlock()`.  In particular, the lock/unlock cycle here:

https://github.com/valhalla/valhalla/blob/25673fa03b2d3995b722c7ff3a29540a2f6f3d7b/src/mjolnir/graphenhancer.cc#L273-L275

was responsible for about 41% of total run time, and the lock/unlock cycle here:

https://github.com/valhalla/valhalla/blob/25673fa03b2d3995b722c7ff3a29540a2f6f3d7b/src/mjolnir/graphenhancer.cc#L229-L231

held another 18%.  Note that the time spent was on the `lock.lock/unlock` lines, *not* on `GetGraphTile` (the thing being protected).

Here's a screenshot from the profiler:

<img width="929" alt="screen shot 2018-04-11 at 8 04 42 am" src="https://user-images.githubusercontent.com/1892250/38625476-6834e024-3d5f-11e8-9b51-416de955ae81.png">

(the numbers in yellow are sample counts).    Also interesting to note is that the per-core CPU utilization is relatively low:

<img width="828" alt="screen shot 2018-04-11 at 8 05 56 am" src="https://user-images.githubusercontent.com/1892250/38625392-3ad8124a-3d5f-11e8-99c3-ff51583f5001.png">

The TL;DR here is that not only are `std::mutex.lock()/unlock()` calls slow on OSX, there's contention meaning that parallelism in this phase of processing is being destroyed.

According to some benchmarks I found, [`std::mutex.lock()/unlock()` performance on macOS isn't that great](https://www.arangodb.com/2015/02/comparing-atomic-mutex-rwlocks/), and Linux performs significantly better here (roughtly 20x according to that benchmark).

I attempted to replace the use of the exclusive `lock()/unlock()` approach with a `boost::shared_mutex()` and a shared/exclusive approach when populating the cache, but it doesn't seem to really help (in fact, things got slower).

The locking that's most contentions seems to be protecting multi-threaded access to the tile cache.  One possible approach to improving performance might be to pre-populate before the multi-threaded work begins, so operations on the cache become read-only and no locks are required.  I haven't quite dived in deep enough to determine whether this is feasible.

**Comment by kevinkreiser** [comment]
It would only be feasible if you can fit the planet in memory, which for the sake of argument you can't. We could instead write the tile into a tar before running the enhancer and use the memory map tar for the enhancer but this will cost time as well as disk. Another thing we might be able to do is look at exactly what info the enhancer needs and see if just this info can fit in memory. @dnesbitt61 will know the answer to these questions off the top of his head I'm sure!

**Comment by dnesbitt61** [comment]
We definitely need to lock whenever we read a new tile (to make sure that tile is not being written by another thread). I can look at adding code to avoid calls to lock and unlock where the same tile is accessed in succession. I think this can help reduce the prevalence of lock and unlock calls but we can't avoid them entirely.
