### ISSUE TITLE
[WARN] Local Edge Index exceeds max & [ERROR] NodeInfo: edge count exceeds max

### ISSUE THREAD

**Issue by Rui-Santos** [valhalla/valhalla#1221]
First, let me apologize if it is something obvious and I'm being dumb with it, but on the latest transit tiles build I got these warnings that culminated in an error when the warnings reached the count of 220. Can you advise me if there is something I could do about it before I go on a source code hunting trip and change some constant on my fork of valhalla, as I would prefer not to diverge too much from the great work you guys have done. I already changed one constant that deals with the frequency of trips from 8K to 180K(that was how much it took until it stopped erroring), and I already think I probably shouldn't have done that 2 months ago.

```
2018/04/17 15:38:06.211774 [WARN] Local Edge Index exceeds max: 213
2018/04/17 15:38:09.068654 [WARN] Local Edge Index exceeds max: 214
2018/04/17 15:38:11.906204 [WARN] Local Edge Index exceeds max: 215
2018/04/17 15:38:14.783911 [WARN] Local Edge Index exceeds max: 216
2018/04/17 15:38:17.720355 [WARN] Local Edge Index exceeds max: 217
2018/04/17 15:38:20.552034 [WARN] Local Edge Index exceeds max: 218
2018/04/17 15:38:23.401603 [WARN] Local Edge Index exceeds max: 219
2018/04/17 15:38:23.401845 [ERROR] NodeInfo: edge count exceeds max: 220
```

**Comment by gknisely** [comment]
The maximum edges that we store per node is 127.   
https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/nodeinfo.h#L18

So, we are not allowing anymore transit lines to be added passed 127 to that node.  We were going to create another node if we exceeded this max; however, we never got around to implementing this logic.

**Comment by dnesbitt61** [comment]
you can do this locally but will not be able to merge any PRs back into Valhalla since this "breaks" the current tile format. A better solution is to "split" any transit stop nodes that have more than the max. number of edges and create a connection between the 2 nodes. Having entry/station/platform hierarchies for transit stations is meant to help in this situation as stations where more than 128 transit edges exist would have platform child nodes.

**Comment by dnesbitt61** [comment]
note that the kMaxEdgesPerNode value ties into how many bits are used for the edge count within the NodeInfo structure. So simply raising this value without changing the NodeInfo structure would break a lot of things as you risk overwriting other values, while never actually creating enough space in the structure to hold these higher counts.

**Comment by Rui-Santos** [comment]
Ok. I see this is a problem with bad data. The transit operators in this country don't even know where their stops are, as I've seen train stops more than 3km away from the real location, when i compare the data from the gtfs feeds with data from OSM and personal knowledge. Just going to keep the limits you guys set, and tell the transit operators/agencies they need to give us better data, because going by what you say, we shouldn't have reached this limits in any way if not for misconstructed GTFS files, with no platform data, etc. 

Thanks a lot for your help. Sorry if my questions seem dumb and sorry for the time you spend answering them. Going to close the issue, as it isn't really an issue with Valhalla.
