### ISSUE TITLE
Seeing an error I don’t understand: `Unknown:_Map_base::at`

### ISSUE THREAD

**Issue by migurski** [valhalla/valhalla#1231]
I am seeing this error when attempting to map-match against a local copy of Valhalla running under Docker:

```
{'error': 'Unknown:_Map_base::at',
 'error_code': 499,
 'status': 'Bad Request',
 'status_code': 400}
```

Debug output from `valhalla_route_service`:

```
2 2018/04/23 23:37:41.643830 POST /trace_attributes HTTP/1.1
2018/04/23 23:37:41.644008 [INFO] Got Loki Request 2
2018/04/23 23:37:41.644067 [ANALYTICS] costing_type::auto
2018/04/23 23:37:41.644165 [ANALYTICS] trace_size::6
2018/04/23 23:37:41.644197 [ANALYTICS] location_distance::0.545963km
2018/04/23 23:37:41.646030 [INFO] Got Thor Request 2
2018/04/23 23:37:41.646629 [ANALYTICS] travel_mode::0
2018/04/23 23:37:41.646916 [ANALYTICS] 400::_Map_base::at
2 2018/04/23 23:37:41.647147 400 217
```

My request to `/trace_attributes`:

```
{"costing": "auto", "shape_match": "map_snap", "search_radius": 25, "filters": {"action": "include", "attributes": ["shape", "edge.names", "edge.begin_heading", "edge.begin_shape_index", "edge.end_heading", "edge.end_shape_index", "edge.use", "edge.road_class", "edge.way_id", "edge.traversability", "edge.end_node"]}, "shape": [{"lat": 37.810936723610034, "lon": -122.26253271102904}, {"lat": 37.81120796113546, "lon": -122.26431369781493}, {"lat": 37.81144529315285, "lon": -122.26542949676514}, {"lat": 37.81147919766449, "lon": -122.2667384147644}, {"lat": 37.810072147347995, "lon": -122.26755380630493}, {"lat": 37.80900412740055, "lon": -122.26824045181274}]}
```

I had a version of Valhalla from late last year running under Docker successfully responding to this request with an identical set of routing tiles, but when I upgraded to the most recent version I started to see this error. I tried walking back to older versions but found it under 2.4.7, 2.4.3, and 2.4.0.

**Comment by migurski** [comment]
Update: including `edge.end_node` in attributes might have been the problem. After pulling it out I am seeing working responses again.

**Comment by kevinkreiser** [comment]
Definitely looks like a bug to me. I think we should reopen this

**Comment by dnesbitt61** [comment]
edge.end_node is not a valid attribute in the filter.

**Comment by dnesbitt61** [comment]
The node Ids are internal Valhalla Ids so I'm not sure how node Id would help you.  Valhalla does not store OSM node Ids. The forward and backward flags are internal indications of whether EdgeInfo structures are accessed in a forward or reverse direction for shape unpacking so I'm not sure that can be useful externally either.

**Comment by migurski** [comment]
Ah, I had thought the node IDs might be external OSM identifiers. Useful to know that they are not.

In our use-case, we're looking at linear references along segments (you'll recognize these from ~~OSMLR~~ SharedStreets) and wanting to know which LR is being traversed. We can guess this from the sequence of geometries, but knowing the traversal direction directly would save a DB lookup.
