### ISSUE TITLE
arrive by routing.  shape issue

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#1241]
Need to dig into why we are receiving this error with arrive by routing.

[libprotobuf ERROR google/protobuf/wire_format.cc:1091] String field 'shape' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

![image](https://user-images.githubusercontent.com/2676277/39443591-15c0404e-4c83-11e8-800f-430f94fc46b4.png)

`/route?json={%22locations%22:[{%22lat%22:40.760390716878376,%22lon%22:-114.12926674238406,%22type%22:%22break%22},{%22lat%22:40.74361546275168,%22lon%22:-113.9943409000989,%22type%22:%22break%22}],%22costing%22:%22auto%22,%22date_time%22:{%22type%22:2,%22value%22:%222018-04-25T21:00%22}}`

**Comment by kevinkreiser** [comment]
oh i read `shape` and though it was on the `directionsoptions` pbf, this is in the `trippath` pbf object then? sorry for the confusion!
