### ISSUE TITLE
Map matching bus?

### ISSUE THREAD

**Issue by skywave** [valhalla/valhalla#1280]
I try to play around with matching some bus traces on the map matching API (hosted locally via docker). Per https://github.com/valhalla/valhalla-docs/blob/master/map-matching/api-reference.md costing_model "bus" should be available

However trying on any request on the API returns "{"error_code":499,"error":"Unknown:No costing method found for 'bus'","status_code":400,"status":"Bad Request"}" ?

**Comment by kevinkreiser** [comment]
heres the issue: https://github.com/valhalla/valhalla/blob/master/src/meili/map_matcher_factory.cc#L35-L39

notice bus is missing. @dnesbitt61 and @kdiluca are going to be fixing this soon. basically the costings that are allowed are set in different places in the code. they are working to do that all in one place so all the different things that use it will use it.

**Comment by dnesbitt61** [comment]
This was fixed by pr #1271
