### ISSUE TITLE
Port to cucumber for integration tests

### ISSUE THREAD

**Issue by TheMarex** [valhalla/valhalla#1285]
Currently this repository has no portable integration tests. The hard-coded [test routes](https://github.com/valhalla/valhalla/tree/master/test_requests) in are not portable across API versions which is problematic in context of an upcoming API rewrite.

Cucumber offers an easy way to write integration tests in a portable way that are both easy to read, document and upgrade between breaking changes. @danpat had some success with prototyping this in https://github.com/Project-OSRM/osrm-backend/pull/4839 but we should consider building this from scratch with a newer Cucumber version.

**Comment by kevinkreiser** [comment]
Done
