### ISSUE TITLE
add local network data and local GTFS

### ISSUE THREAD

**Issue by udahorn** [valhalla/valhalla#1289]
Hi,

I am faced with two problems and will be happy for help.

1. I'm trying to load transit feed  from transit.land only for Israel without success

i tried differnt way to build the transit 

In addition i tried to use  [BBOX parmeter](https://github.com/valhalla/valhalla/pull/1104)  without success :
`valhalla_build_transit valhalla.json http://transit.land 1000 valhalla_transit 34.31874,29.49219299,35.806584,33.281346`
2. Is there any way to add NOT OSM data to the tiles ?

**Comment by gknisely** [comment]
@udahorn I am not seeing any issues with the above command.  What errors are you seeing?

./valhalla_build_transit ../conf/valhalla.conf http://transit.land 1000 valhalla_transit 34.31874,29.49219299,35.806584,33.281346
2018/05/23 13:10:03.604951 [INFO] Fetching transit feeds
2018/05/23 13:10:04.221393 [INFO] 2/000/687/739.gph should have 5 stations 
2018/05/23 13:10:04.620811 [INFO] 2/000/689/179.gph should have 208 stations 
2018/05/23 13:10:04.966702 [INFO] 2/000/690/619.gph should have 15 stations 
2018/05/23 13:10:05.031139 [INFO] 2/000/690/620.gph should have 18 stations 
2018/05/23 13:10:05.322274 [INFO] 2/000/692/059.gph should have 7 stations 
2018/05/23 13:10:05.390672 [INFO] 2/000/692/060.gph should have 10 stations 
2018/05/23 13:10:05.633670 [INFO] 2/000/693/498.gph should have 1 stations 
2018/05/23 13:10:05.700149 [INFO] 2/000/693/499.gph should have 6 stations 
2018/05/23 13:10:05.764815 [INFO] 2/000/693/500.gph should have 11 stations 
2018/05/23 13:10:06.060445 [INFO] 2/000/694/939.gph should have 47 stations 
2018/05/23 13:10:06.122973 [INFO] 2/000/694/940.gph should have 13 stations 
2018/05/23 13:10:06.350135 [INFO] 2/000/696/377.gph should have 21 stations 
2018/05/23 13:10:06.418273 [INFO] 2/000/696/378.gph should have 20 stations 
2018/05/23 13:10:06.496867 [INFO] 2/000/696/379.gph should have 76 stations 
2018/05/23 13:10:06.562294 [INFO] 2/000/696/380.gph should have 7 stations 
2018/05/23 13:10:06.629351 [INFO] 2/000/696/381.gph should have 9 stations 
2018/05/23 13:10:06.796656 [INFO] 2/000/697/817.gph should have 44 stations 
2018/05/23 13:10:06.864720 [INFO] 2/000/697/818.gph should have 33 stations 
2018/05/23 13:10:07.161995 [INFO] 2/000/697/819.gph should have 377 stations 
2018/05/23 13:10:07.246608 [INFO] 2/000/697/820.gph should have 255 stations 
2018/05/23 13:10:07.314350 [INFO] 2/000/697/821.gph should have 17 stations 
2018/05/23 13:10:07.473390 [INFO] 2/000/699/257.gph should have 39 stations 
2018/05/23 13:10:07.633308 [INFO] 2/000/699/258.gph should have 617 stations 
2018/05/23 13:10:07.735152 [INFO] 2/000/699/259.gph should have 804 stations 
2018/05/23 13:10:07.819301 [INFO] 2/000/699/260.gph should have 205 stations 
2018/05/23 13:10:07.892679 [INFO] 2/000/699/261.gph should have 17 stations 
2018/05/23 13:10:08.138672 [INFO] 2/000/700/698.gph should have 795 stations 
2018/05/23 13:10:08.255826 [INFO] 2/000/700/699.gph should have 605 stations 
2018/05/23 13:10:08.368342 [INFO] 2/000/700/700.gph should have 830 stations 
2018/05/23 13:10:08.448687 [INFO] 2/000/700/701.gph should have 18 stations 
2018/05/23 13:10:08.690939 [INFO] 2/000/702/138.gph should have 828 stations 
2018/05/23 13:10:09.005325 [INFO] 2/000/702/139.gph should have 2141 stations 
2018/05/23 13:10:09.210939 [INFO] 2/000/702/140.gph should have 2596 stations 
2018/05/23 13:10:09.322671 [INFO] 2/000/702/141.gph should have 365 stations 
2018/05/23 13:10:09.390347 [INFO] 2/000/702/142.gph should have 8 stations 
2018/05/23 13:10:09.595465 [INFO] 2/000/703/578.gph should have 101 stations 
2018/05/23 13:10:09.829961 [INFO] 2/000/703/579.gph should have 4466 stations 
2018/05/23 13:10:09.924193 [INFO] 2/000/703/580.gph should have 339 stations 
2018/05/23 13:10:09.998910 [INFO] 2/000/703/581.gph should have 99 stations 
2018/05/23 13:10:10.062582 [INFO] 2/000/703/582.gph should have 2 stations 
2018/05/23 13:10:10.335923 [INFO] 2/000/705/019.gph should have 1496 stations 
2018/05/23 13:10:10.421480 [INFO] 2/000/705/020.gph should have 389 stations 
2018/05/23 13:10:10.500986 [INFO] 2/000/705/021.gph should have 72 stations 
2018/05/23 13:10:10.594590 [INFO] 2/000/705/022.gph should have 65 stations 
2018/05/23 13:10:10.825628 [INFO] 2/000/706/459.gph should have 451 stations 
2018/05/23 13:10:10.952666 [INFO] 2/000/706/460.gph should have 1209 stations 
2018/05/23 13:10:11.058681 [INFO] 2/000/706/461.gph should have 1420 stations 
2018/05/23 13:10:11.136686 [INFO] 2/000/706/462.gph should have 183 stations 
2018/05/23 13:10:11.439251 [INFO] 2/000/707/899.gph should have 737 stations 
2018/05/23 13:10:11.668681 [INFO] 2/000/707/900.gph should have 2372 stations 
2018/05/23 13:10:11.872648 [INFO] 2/000/707/901.gph should have 1429 stations 
2018/05/23 13:10:11.987495 [INFO] 2/000/707/902.gph should have 718 stations 
2018/05/23 13:10:12.283670 [INFO] 2/000/707/903.gph should have 42 stations 
2018/05/23 13:10:12.727891 [INFO] 2/000/709/340.gph should have 349 stations 
2018/05/23 13:10:12.802331 [INFO] 2/000/709/341.gph should have 427 stations 
2018/05/23 13:10:12.904435 [INFO] 2/000/709/342.gph should have 405 stations 
2018/05/23 13:10:12.984455 [INFO] 2/000/709/343.gph should have 55 stations 
2018/05/23 13:10:13.317084 [INFO] 2/000/710/782.gph should have 25 stations 
2018/05/23 13:10:13.383250 [INFO] 2/000/710/783.gph should have 18 stations 
2018/05/23 13:10:13.383349 [INFO] Finished with 59 transit tiles in 1 feeds
2018/05/23 13:10:13.383943 [INFO] Fetching 59 transit tiles with 4 threads...
2018/05/23 13:10:13.384666 [INFO] Fetching valhalla_transit/2/000/703/579.pbf
2018/05/23 13:10:13.385014 [INFO] Fetching valhalla_transit/2/000/702/139.pbf
2018/05/23 13:10:13.384852 [INFO] Fetching valhalla_transit/2/000/702/140.pbf
2018/05/23 13:10:13.384883 [INFO] Fetching valhalla_transit/2/000/707/900.pbf
. . . 

Also, for the second question are you referring to using valhalla_build_tiles?  
Let me know.  Thanks.

**Comment by gknisely** [comment]
Something does not seem correct.  Are you sure you built valhalla_build_transit since this new BB logic has been merged to the master branch?

**Comment by udahorn** [comment]
OK I think that's the problem
I trying to update but I guess I missed something and it didn't work..
I am using Ubuntu and installed via PPA, What is  the correct way do update?

**Comment by udahorn** [comment]
about my second question
i have network data from HERE in ESRI format
i believe that i  can convert it to pbf. 
Can i build tiles  using valhalla_build_tiles? 
What needs to be done to make it work?

Thanks

**Comment by Rui-Santos** [comment]
> I am using Ubuntu and installed via PPA

The PPA is still at version 2.4.7. The BBox logic was introduced in version 2.5.0.

>What is the correct way do update?

You will have to follow the instructions in the README to build it from the source code.
https://github.com/valhalla/valhalla#building-from-source

**Comment by udahorn** [comment]
> I don't think that will work, because as far as I understand valhalla is dependent on OSM data fields, for example osm_way_id's, to build the tiles, and I suppose HERE doesn't have that data.


You're right but i wonder if anyone has already done the conversion , so far the data of HERE have their structure and possibly has a way to convert them to  OSM fields

**Comment by udahorn** [comment]
I succeeded to build transit  :

2018/06/03 22:44:08.186937 [INFO] Finished
2018/06/03 22:44:08.187015 [INFO] Building transit network.
2018/06/03 22:44:08.187084 [INFO] Adding 59 transit tiles to the transit graph..          .
2018/06/03 22:44:08.187928 [INFO] Tile extract successfully loaded
2018/06/03 22:44:08.190415 [WARN] Time zone db /home/yehuda/valhalla_tiles/timez          ones.sqlite not found.  Not saving time zone information from db. 

my config valhalla.json:

    "tile_dir": "/home/yehuda/valhalla_tiles",
    "tile_extract": "/home/yehuda/valhalla_tiles.tar",
    "timezone": "/home/yehuda/valhalla_tiles/timezones.sqlite",
    "transit_dir": "/home/yehuda/valhalla_transit"

but when i'm testing multimodal i receive:

2018/06/04 06:50:08.421646 [INFO] Got Loki Request 5
2018/06/04 06:50:08.421701 [ANALYTICS] locations_count::2
2018/06/04 06:50:08.421710 [ANALYTICS] costing_type::multimodal
2018/06/04 06:50:08.421787 [ANALYTICS] location_distance::0.517855km
2018/06/04 06:50:08.425370 [INFO] Got Thor Request 5
2018/06/04 06:50:08.425668 [ANALYTICS] travel_mode::1
2018/06/04 06:50:08.442420 [ANALYTICS] 400::basic_string::at: __n (which is 0) >= this->size() (which is 0)

my test  (with "costing":"auto" it work..) :
{"locations":[{"lat":31.793621,"lon":35.215285},{"lat":31.7973,"lon":35.218634}], "costing":"multimodal" }

**Comment by dnesbitt61** [comment]
I am not able to replicate this bug. Without transit data I get a valid pedestrian route using your multimodal request.

**Comment by udahorn** [comment]
> I am not able to replicate this bug. Without transit data I get a valid pedestrian route using your multimodal request.

I add "date_time":{"type":1,"value":"2018-06-10T08:00"}} to request and i get a valid pedestrian route but didn't recive a trnsit route ( I increased the distance between the points and i get `Cannot reach destination - too far from a transit stop`)

so i decide to try again from the beginning:

1. I run valhalla_build_transit valhalla.json http://transit.land 1000 valhalla_transit 34.31874,29.49219299,35.806584,33.281346

...

2018/06/06 12:01:15.633810 [INFO] valhalla_transit/2/000/697/821.pbf stitched 4 of 4 stops
2018/06/06 12:01:15.674398 [INFO] valhalla_transit/2/000/690/619.pbf stitched 5 of 5 stops
2018/06/06 12:01:17.313144 [INFO] valhalla_transit/2/000/694/940.pbf stitched 4 of 4 stops
2018/06/06 12:01:17.326054 [INFO] valhalla_transit/2/000/693/500.pbf stitched 4 of 4 stops
2018/06/06 12:01:17.343332 [INFO] valhalla_transit/2/000/692/060.pbf stitched 4 of 4 stops
2018/06/06 12:01:17.414612 [INFO] valhalla_transit/2/000/696/381.pbf stitched 4 of 4 stops
2018/06/06 12:01:17.542101 [INFO] valhalla_transit/2/000/702/142.pbf stitched 6 of 6 stops
2018/06/06 12:01:20.314635 [INFO] valhalla_transit/2/000/696/380.pbf stitched 7 of 7 stops
2018/06/06 12:01:20.320817 [INFO] valhalla_transit/2/000/692/059.pbf stitched 3 of 3 stops
2018/06/06 12:01:20.339331 [INFO] valhalla_transit/2/000/693/499.pbf stitched 2 of 2 stops
2018/06/06 12:01:20.376518 [INFO] valhalla_transit/2/000/687/739.pbf stitched 1 of 1 stops
2018/06/06 12:01:20.400934 [INFO] valhalla_transit/2/000/703/582.pbf stitched 3 of 3 stops
2018/06/06 12:01:20.415365 [INFO] valhalla_transit/2/000/693/498.pbf stitched 1 of 1 stops
2018/06/06 12:01:20.415558 [INFO] Finished
2018/06/06 12:01:20.415657 [INFO] Building transit network.
2018/06/06 12:01:20.415744 [INFO] Adding 59 transit tiles to the transit graph...
2018/06/06 12:01:20.416422 [INFO] Tile extract successfully loaded
valhalla_build_transit: symbol lookup error: valhalla_build_transit: undefined symbol: _ZN8valhalla7mjolnir16GraphTileBuilder11AddEdgeInfoINSt7__cxx114listINS_7midgard7PointLLESaIS6_EEEEEjjRKNS_5baldr7GraphIdESC_mRKT_RKSt6vectorINS3_12basic_stringIcSt11char_traitsIcESaIcEEESaISL_EEtRb

2. I run valhalla_build_tiles -c valhalla.json israel-and-palestine-latest.osm.pbf and as you can see `No transit tiles found. Transit will not be added`

...
2018/06/06 12:19:42.201316 [INFO] Finished with max_density 24.164257 and unreachable 3132
2018/06/06 12:19:42.201490 [INFO] No transit tiles found. Transit will not be added.
2018/06/06 12:19:42.201571 [INFO] HierarchyBuilder
2018/06/06 12:19:44.810290 [INFO] Done HierarchyBuilder
2018/06/06 12:19:44.813353 [INFO] Creating shortcuts on level 1
2018/06/06 12:19:45.910827 [INFO] Finished with 28126 shortcuts
2018/06/06 12:19:45.910978 [INFO] Creating shortcuts on level 0
2018/06/06 12:19:46.125950 [INFO] Finished with 5882 shortcuts
2018/06/06 12:19:46.127922 [INFO] Adding Restrictions at level 2
2018/06/06 12:19:46.809852 [INFO] --Forward restrictions added: 19
2018/06/06 12:19:46.810019 [INFO] --Reverse restrictions added: 15
2018/06/06 12:19:46.810219 [INFO] Adding Restrictions at level 1
2018/06/06 12:19:47.029749 [INFO] --Forward restrictions added: 119
2018/06/06 12:19:47.029869 [INFO] --Reverse restrictions added: 123
2018/06/06 12:19:47.030009 [INFO] Adding Restrictions at level 0
2018/06/06 12:19:47.115749 [INFO] --Forward restrictions added: 44
2018/06/06 12:19:47.115859 [INFO] --Reverse restrictions added: 44
2018/06/06 12:19:47.115874 [INFO] Finished
2018/06/06 12:19:47.115896 [INFO] Validating, finishing and binning tiles...
2018/06/06 12:19:51.053903 [INFO] Finished
2018/06/06 12:19:51.054060 [INFO] Binning inter-tile edges...
2018/06/06 12:19:51.220865 [INFO] Finished
2018/06/06 12:19:51.220997 [WARN] Possible duplicates at level: 0 = 0
2018/06/06 12:19:51.221014 [WARN] Possible duplicates at level: 1 = 54
2018/06/06 12:19:51.221026 [WARN] Possible duplicates at level: 2 = 0

how i can add transit ? 
I can not figure out what I'm not doing right

**Comment by kevinkreiser** [comment]
when you run `valhalla_build_tiles` you need in your `valhalla.json` to set the `transit_dir` to `valhalla_transit` as that is where you told `valhalla_build_transit` to put the transit tile data.

**Comment by kevinkreiser** [comment]
additionally it looks like there is a problem with your build of the code that you are getting that symbol lookup error. where are you building this, what type of machine and operating system and compiler etc?

**Comment by nilsnolde** [comment]
outdated
