### ISSUE TITLE
Move CI builds to Travis

### ISSUE THREAD

**Issue by oxidase** [valhalla/valhalla#1290]
It have OSX builds running one possible solution is to move continuous integration to [Travis CI](http://travis-ci.org/).

Tasks:
 - [ ] convert `.circleci/config.yml` to `.travis.yml`
 - [ ] register valhalla on Travis CI
 - [ ] add OSX build

/cc @kevinkreiser

**Comment by dnesbitt61** [comment]
closing for now. many changes to Circle CI were made along with the move to cmake.
