### ISSUE TITLE
Improve routing behaviour on hov roads

### ISSUE THREAD

**Issue by chaupow** [valhalla/valhalla#1297]
Valhalla currently does not route on with any vehicle

```
hov = designated
hov:lanes = designated|yes|yes|yes
```

I propose:
- route busses on `hov=designated` roads
- route on roads if _any_ lane on the road is not `designated` (even if `hov=designated`)

**Comment by dnesbitt61** [comment]
Is there any specific information on whether buses are allowed on HOV designated ways by default, or based on country? Also, we should evaluate whether motorcycles should be allowed on HOV as well (my limited experience is that they are).

**Comment by chaupow** [comment]
Skimming over the [wikipedia article](https://en.wikipedia.org/wiki/High-occupancy_vehicle_lane):

> Qualification for HOV status varies by scheme, but the following vehicles may be included:
> - Motorcycles  - motorcycles are allowed via federal United States HOV lane law (Title 23, Section 166). They cannot use HOV lanes in Ontario unless they have 2 passengers.
> - Buses designed to transport sixteen or more passengers, including the driver

So seems like we can allow routing for motorbikes and busses in general.

Maybe we could also expose hov usage as another `costing_option` when we run into contradicting behaviour requirements - until then let's pick a behaviour that we feel should be ok.

**Comment by dnesbitt61** [comment]
HOV is actually an allowed costing model - so if the user knows he/she is an an HOV vehicle then that costing model can be used.

**Comment by chaupow** [comment]
@dnesbitt61 but that is it's own `costing` right? It doesn't allow a bus to use the `bus` costing and give information on whether it can (or want) to use `hov` roads or not

**Comment by dnesbitt61** [comment]
@chaupow - right. You would still want buses and motorcycles to use their own costing method (and expect that HOV roads would be allowed). When I said HOV vehicle I probably meant (and should have said) automobile, van, etc. that qualifies for HOV based on number of passengers (but does not qualify as a bus)

**Comment by chaupow** [comment]
@1ec5 I see what you're saying... 
But does that represent common tagging practice?
I see way less tagging of `motorcycle:lanes` than `hov:lanes` and wonder if there are more cases where a `hov:lanes=designated` should be accompanied by `motorvehicle_lanes`
(https://taginfo.openstreetmap.org/keys/hov%3Alanes vs https://taginfo.openstreetmap.org/keys/motor_vehicle%3Alanes)

Hmmm. not sure. Personally, I would be ok with not considering `hov` tags for car access at all and only regard `motor_vehicles` 🤷‍♀️ 

Makes the code even easier.
cc @gknisely
