### ISSUE TITLE
Review release process

### ISSUE THREAD

**Issue by TheMarex** [valhalla/valhalla#1298]
I could not find clear documentation on how to do a valhalla release, but this is how I think it works right now:

1. Someone tags a release using `git tag -a vMAJOR.MINOR.PATCH` and maybe (?) includes a changelog
2. Manually upgrade the version in `valhalla/packaging`
3. Manually publish a new package to a PPA

The full steps for the release process should be captured somewhere similar to the [OSRM](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) documentation.

Some suggestions for modifying the current release process:

- PPA publishing should either be fully automated or removed
- There should be a detailed changelog with human readable changes in the root of the repository like [here](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md).

/cc @kevinkreiser

**Comment by kevinkreiser** [comment]
the changelog gets generated at package build time via the packaging scripts and this bit of markdown: https://github.com/valhalla/valhalla-docs/blob/master/release-notes.md

i never liked this and would prefer we have a proper changelog filled out as you suggested but the team voted that down in the past.

the packaging repository has a CI that when you push the commit changing the version file will test bulids for the target distributions. if those look green, then you can run the publish script.

this is documented in the packaging repo. and yes those steps are manual. this was on purpose and served us well but automated builds would be something worth doing.

i dont think publishing to the PPA would be worth automating. if you really want CI to make packages we probably wont be changing versions every commit so something like docker images are probably a better idea here. also docker is useful on more platforms than just ubuntu.

what are your thoughts?

**Comment by dnesbitt61** [comment]
Valhalla needs to retain the ability for others to generate Docker packages. PPA is a little less certain with more external users prefering Docker, but there still may be a case to occasionally create a PPA. Are you saying that we should automate the production of a new Docker image for Docker hub everytime we tag a release?  I would say that Valhalla has not generally announced official releases - we basically have tagged a release, updated some release notes in a doc, and let those who are following the repo decide when and if they want to update.

**Comment by kevinkreiser** [comment]
i would vote to automate docker builds within CI if that is a possibility and leave the PPA unautomated (but not removed).

i'm not an expert on this but headless PPA uploads seems non-trivial.

**Comment by TheMarex** [comment]
Okay, it seems like the main problem is that Valhalla does not seem to have a formal release process right now, which is important for change management on a production system. I'll draft some release documentation tailored to the Valhalla use-case for you to review.

**Comment by kevinkreiser** [comment]
we had been doing this until mapzen shutdown: https://github.com/valhalla/packaging#libvalhalla-builds

but docker casts a wider net and seems easier to integrate with CI so i'd vote for that.

**Comment by TheMarex** [comment]
This has been merged.
