### ISSUE TITLE
Remove autoconf build system

### ISSUE THREAD

**Issue by TheMarex** [valhalla/valhalla#1299]
After #1272 was merged, this project features two independent build systems that could fall out of sync quickly. To avoid this we should simplify this to only cmake.

@kevinkreiser has pointed out that the PPA packaging assumes that valhalla uses autoconf. We need to determine if updating the packaging would block a release since the PPA packages are outdated already anyway.

**Comment by TheMarex** [comment]
That plan makes sense to me @kevinkreiser. Once we have release documentation in place I'll try to run this out.

**Comment by rinigus** [comment]
Please don't forget to update README (https://github.com/valhalla/valhalla#building-from-source) before removal. I am packaging Valhalla for Sailfish OS and using it as a part of offline map service, so it would be great to get some guidelines on how to build it using cmake. In particular, I would need to specify 

```
--enable-data-tools=no --enable-static=yes --enable-python-bindings=no --enable-services=yes
```

for my use case. Looks like it will be (almost) achieved by specifying 

```
-DENABLE_DATA_TOOLS=OFF -DENABLE_PYTHON_BINDINGS=OFF -DENABLE_SERVICES=ON
```

However, I don't see options to enable static build - probably I am just missing it though.

**Comment by oxidase** [comment]
@rinigus :+1: for updating README. Static builds are enabled with `-DBUILD_SHARED_LIBS=Off`

**Comment by TheMarex** [comment]
This was done :tada:

**Comment by markovendelin** [comment]
Thank you!
