### ISSUE TITLE
Move documentation to main repository

### ISSUE THREAD

**Issue by TheMarex** [valhalla/valhalla#1307]
Keeping the documentation of a software project versioned with source code has multiple advantages:

- It is easy to make both adding/fixing documentation part of a Pull Request
- It is easy to find the documentation for a given version of the software
- It is easy to automatically publish documentation to external sources when a release is tagged

Right now most of the documentation lives in https://github.com/valhalla/valhalla-docs which is not really intuitive given that there is also a `docs` directory in this repository.

I propose to move the documentation to the main repository for the reasons mentioned above.

**Comment by kevinkreiser** [comment]
the documentation wasnt in the main repo for _hysterical raisins_. i think we'd all be happy to move it.

**Comment by dnesbitt61** [comment]
One concern is that there are various links to the doc pages. Internal (to valhalla) links can be changed easily but what about possible external links? Should we keep the current valhalla-docs repo and add to the Readme that the contents are being maintained in a separate location going forward?

**Comment by TheMarex** [comment]
> what about possible external links

Do you have an example of that?

In general when we deprecate repositories we just add `DEPRECATED` to the description/readme and keep the content.

**Comment by dnesbitt61** [comment]
No examples - but blogs on Medium / Postzen may reference the API and perhaps other Valhalla users may reference valhalla-docs. I think it is fine to mark as DEPRECATED and keep the content.

**Comment by dnesbitt61** [comment]
#1328 closes this issue
