### ISSUE TITLE
Time dependent routing not working

### ISSUE THREAD

**Issue by runetvilum** [valhalla/valhalla#1313]
I can not get time dependent routing to work.
I have tested the area in PR #1248 
<img width="2559" alt="skaermbillede 2018-05-28 kl 14 36 11" src="https://user-images.githubusercontent.com/866843/40615281-6a555c34-6286-11e8-9665-4e7edde59f8d.png">

key | value
--|--
bicycle:conditional | no @ (Su 08:00-18:00)
highway | residential
maxspeed | 25 mph
motor_vehicle:conditional | no @ (Su 08:00-18:00)
name | Orchard Street
oneway | yes

1. I have downloaded the OSM area around way https://www.openstreetmap.org/way/384898122 to map.osm
2. convert to pbf: `osmosis --rx map.osm --wb map.osm.pbf`
3. created a docker image [valhalla/docker](https://github.com/valhalla/docker) from the latest source: `./build.sh source latest`
4. created timezones: `docker run -v $(pwd)/data/valhalla:/data/valhalla valhalla/docker:source-latest valhalla_build_timezones /conf/valhalla.json`
5. build tiles: `docker run -v $(pwd)/data/valhalla:/data/valhalla valhalla/docker:source-latest valhalla_build_tiles -c /conf/valhalla.json /data/valhalla/map.osm.pbf`
6. created tar: `find valhalla | sort -n | tar cf tiles.tar --no-recursion -T -`
7. started service: `docker run -p 8002:8002 -v $(pwd)/data/valhalla:/data/valhalla valhalla/docker:source-2.5.0`
```
2018/05/28 11:02:30.827237 [INFO] Tile extract successfully loaded
2018/05/28 11:02:30.831138 [INFO] Tile extract successfully loaded
2018/05/28 11:02:30.856546 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
11 2018/05/28 12:30:50.265068 GET /route?json={%22locations%22:[{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:40.718489370441965,%22lng%22:-73.99004274979234},%22_initHooksCalled%22:true,%22lat%22:40.718489370441965,%22lon%22:-73.99004274979234},{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:40.721380106009285,%22lng%22:-73.98822957649827},%22_initHooksCalled%22:true,%22lat%22:40.721380106009285,%22lon%22:-73.98822957649827}],%22costing%22:%22auto%22,%22directions_options%22:{%22language%22:%22en-US%22},%22date_time%22:{%22type%22:1,%22value%22:%222018-05-30T14:25%22}}&api_key= HTTP/1.1
2018/05/28 12:30:50.265357 [INFO] Got Loki Request 11
2018/05/28 12:30:50.265458 [ANALYTICS] locations_count::2
2018/05/28 12:30:50.265587 [ANALYTICS] costing_type::auto
2018/05/28 12:30:50.265642 [ANALYTICS] location_distance::0.356100km
2018/05/28 12:30:50.266521 [INFO] Got Thor Request 11
2018/05/28 12:30:50.266676 [ANALYTICS] travel_mode::0
2018/05/28 12:30:50.267537 [ANALYTICS] admin_state_iso::
2018/05/28 12:30:50.267568 [ANALYTICS] admin_country_iso::
2018/05/28 12:30:50.267841 [INFO] Got Odin Request 11
2018/05/28 12:30:50.267948 [INFO] trip_path_->node_size()=8
2018/05/28 12:30:50.268175 [INFO] maneuver_count::5
11 2018/05/28 12:30:50.268553 200 2816
```
8.  Request route from demo page:
<img width="2558" alt="skaermbillede 2018-05-28 kl 14 31 03" src="https://user-images.githubusercontent.com/866843/40615853-e0a0e2bc-6288-11e8-9f08-7894441d6fd4.png">
It should be allowed to drive and bike at Orchard Street except on sunday, but no matter which date I select, the route looks as in the above image.

From the PR #1248 the image should look like:
![39548136-9ea68b66-4e27-11e8-810e-bf39ac540c9a](https://user-images.githubusercontent.com/866843/40616265-b57cd968-628a-11e8-87a1-845af416131a.png)

The request:

```
http://localhost:8002/route?json={"locations":[{"options":{"allowUTurn":false},"latLng":{"lat":40.718489370441965,"lng":-73.99004274979234},"_initHooksCalled":true,"lat":40.718489370441965,"lon":-73.99004274979234},{"options":{"allowUTurn":false},"latLng":{"lat":40.721380106009285,"lng":-73.98822957649827},"_initHooksCalled":true,"lat":40.721380106009285,"lon":-73.98822957649827}],"costing":"auto","directions_options":{"language":"en-US"},"date_time":{"type":1,"value":"2018-05-30T14:25"}}&api_key=
```
The response:
```
{
  "trip": {
    "language": "en-US",
    "summary": {
      "max_lon": -73.988098,
      "max_lat": 40.721455,
      "time": 286,
      "length": 0.391,
      "min_lat": 40.718513,
      "min_lon": -73.990036
    },
    "locations": [
      {
        "type": "break",
        "lat": 40.718502,
        "lon": -73.989998,
        "original_index": 0,
        "date_time": "2018-05-28T11:17-04:00"
      },
      {
        "type": "break",
        "lat": 40.721321,
        "lon": -73.988098,
        "original_index": 1,
        "date_time": "2018-05-28T11:22-04:00"
      }
    ],
    "units": "kilometers",
    "legs": [
      {
        "shape": "ajgtlAhx~blC}ToJoDkAwHgDwDiBoNsFst@uZcdAwb@sAm@zFeY",
        "summary": {
          "max_lon": -73.988098,
          "max_lat": 40.721455,
          "time": 286,
          "length": 0.391,
          "min_lat": 40.718513,
          "min_lon": -73.990036
        },
        "maneuvers": [
          {
            "travel_mode": "pedestrian",
            "begin_shape_index": 0,
            "length": 0.353,
            "time": 259,
            "type": 1,
            "end_shape_index": 8,
            "instruction": "Walk north on Orchard Street.",
            "verbal_pre_transition_instruction": "Walk north on Orchard Street for 400 meters.",
            "travel_type": "foot",
            "street_names": [
              "Orchard Street"
            ]
          },
          {
            "travel_type": "foot",
            "travel_mode": "pedestrian",
            "verbal_pre_transition_instruction": "Turn right onto Stanton Street.",
            "verbal_transition_alert_instruction": "Turn right onto Stanton Street.",
            "length": 0.038,
            "instruction": "Turn right onto Stanton Street.",
            "end_shape_index": 9,
            "type": 10,
            "time": 27,
            "verbal_post_transition_instruction": "Continue for 40 meters.",
            "street_names": [
              "Stanton Street"
            ],
            "begin_shape_index": 8
          },
          {
            "travel_type": "foot",
            "travel_mode": "pedestrian",
            "begin_shape_index": 9,
            "time": 0,
            "type": 4,
            "end_shape_index": 9,
            "instruction": "You have arrived at your destination.",
            "length": 0.000,
            "verbal_transition_alert_instruction": "You will arrive at your destination.",
            "verbal_pre_transition_instruction": "You have arrived at your destination."
          }
        ]
      }
    ],
    "status_message": "Found route between points",
    "status": 0
  }
}
```
What am I doing wrong?

**Comment by dnesbitt61** [comment]
This is still being developed and has not been integrated into the server fully. You can add the following code to thor/src/route_action.cc in the get_path_algorithm method to test:

    // If the origin has date_time set use timedep_forward method.
    // TODO - what to do if the route is long?
    if (origin.has_date_time()) {
      timedep_forward.set_interrupt(interrupt);
      return &timedep_forward;
    }

    // If the destination has date_time set use timedep_reverse method.
    // TODO - what to do if the route is long?
    if (destination.has_date_time()) {
      timedep_reverse.set_interrupt(interrupt);
      return &timedep_reverse;
    }

We hope to integrate this soon but need to do more testing and performance evaluation before fully deploying this.

**Comment by runetvilum** [comment]
Thanks, I will give a try
Regards
Rune Tvilum
