### ISSUE TITLE
Inaccurate bearing values

### ISSUE THREAD

**Issue by oxidase** [valhalla/valhalla#1320]
Function `tangent_angle` in `src/loki/search.cc` returns an inaccurate heading  for the way   https://www.openstreetmap.org/way/501916297#map=19/38.39898/-122.83941 at the red point of  https://gist.github.com/oxidase/44ce84b189ffd124931b1a73f61e0142. Expected value is about 0°, but the returned value is 341° 

The corresponding test case
```
#include "test.h"

#include <src/loki/search.cc>

void test_tangent_angle()
{
    auto angle_diff = [](float angle1, float angle2) {
        return std::fmod(angle1 - angle2 + 180.f + 360.f, 360.f) - 180.f;
    };

    using PointLL = valhalla::midgard::PointLL;


    PointLL point{-122.839554, 38.3990479};
    std::vector<PointLL> shape{{ -122.839104, 38.3988266 }, { -122.839539, 38.3988342 }, { -122.839546, 38.3990479 }};

    test::assert_bool(std::abs(angle_diff(tangent_angle(1, point, shape, true), 0)) < 10, "incorrect tangent angle for forward=true");
}


int main(void) {

  test::suite suite("Loki internal logic");

  // test successes
  suite.test(TEST_CASE(test_tangent_angle));

  return suite.tear_down();
}
```

It is a minor issue, because accuracy depends on [`HEADING_SAMPLE`](https://github.com/valhalla/valhalla/blob/1688d1f6b6df431080d35dabd00bea1d77a1395a/src/loki/search.cc#L31) value and `tangent_angle` returns correct angles in most cases.

**Comment by kevinkreiser** [comment]
@dnesbitt61 using the classification would be easy to implement and makes intuitive sense. i only chose 30m because it worked in most cases and i didnt go back to revise it later. please feel free to have a go at making it more intellegent.
