### ISSUE TITLE
Using descriptive names for namespaces

### ISSUE THREAD

**Issue by TheMarex** [valhalla/valhalla#1327]
I've talked with @kevinkreiser a bit about this and we both agreed that we should have a real discussion about this, because I think this constitutes a major problem with on-boarding people to Valhalla. I understand that most of these problems will go away if you spend some weeks inside the code base. But most people never will and don't have the time for that.

Having a low barrier of entry for people, that are not part of the core development teams is important, because this technology will be used by so many more people. Making the source code accessible enables a much more asynchronous style of working. If we want to optimize of velocity this is important.

Valhalla derives its module/namespace names from Nordic gods, which is clever and funny, but really does not make it very easy to read the code. I understand that some of this has historic reason from the old way Valhalla was organized into many sub-projects, but right now is the chance to fix this: It will only get worse as other integrations go on.

### Finding the right place to look for specific code is hard

For example if I want to find out where Valhalla serializes its API response, I have basically two options:

1. Grep for `serialization` or `json` and maybe find the file `route_serialize.cc`
2. Scan the readme and maybe interfere from the description that `tyr` could handle serialization.

This might work for one-off lookup but quickly because a problem once you start to read the actual code and try to decipher what the referenced modules do.

### Reading source code requires additional cognitive overhead

If I encounter something from the `baldr::` namespace, my first thought should be "Okay this is related to the cache." Instead I have to remember that this is a name for a module inside Valhalla. Then I need to remember that this module is responsible for caching tiles. There is no preexisting association I can use here. Intuitive naming can help there.

On the other hand encountering something from `tile_cache::` makes it immediately clear in what context the referenced object is used.
 
### This can be done automatically

Change the namespace names is an easy automatic translation. There could be a script for users to update their code if they need to. Given the fact that there are a lot of breaking changes coming to this project (especially on the API side), it does not really matter from the perspective of how easy it is for users to upgrade.
Another option is to have a compatibility header for backwards compatibility. Since this is a one to one mapping that is very easy and enables easy porting of client code.

**Comment by TheMarex** [comment]
@dnesbit61 I understand, change is hard, especially if you are already familiar on this naming scheme, but this is really about making it easier for everyone and having a good base to build on.

I fail to see how more descriptive names would make it harder for people familiar with the code to navigate it. The basic structure stays the same, but as an added bonus you get names that are accessibly to more people. Navigating the code as an IDE would do it is beside the point, an IDE can not tell you what a module is supposed to do.

**Comment by kevinkreiser** [comment]
i would also mention that change isn't always necessary. we've had a heap of contributors over the years nary a one said this PR would have been faster if the namespaces had different names. i think it remains to be seen that renaming the namespaces would have any tangible effects on accessibility of the code. as you mentioned, at most it saves you one `grep` or one look at the `README` or even just one browse of the source files (all their names are descriptive).

i think your point about `valhalla::baldr` brings up another concern. what would the new names be? i think some are easy, like `midgard->math||geometry` and `thor->route||graph_traversal` or something like this. But `baldr` is hard to name. its not the just the tile cache. its also the definition of what a tile is and the subobjects within those tiles. this is why an acronym was used in the first place. what is a succinct way to describe this in an obvious way? Maybe just `tiling`?

**Comment by TheMarex** [comment]
> i think your point about valhalla::baldr brings up another concern. what would the new names be? i think some are easy, like midgard->math||geometry and thor->route||graph_traversal or something like this. But baldr is hard to name. its not the just the tile cache. its also the definition of what a tile is and the subobjects within those tiles. this is why an acronym was used in the first place. what is a succinct way to describe this in an obvious way? Maybe just tiling?

I actually don't want to dive too much into a specific naming discussion here, because it distracts from the actual point I'm trying to make. However, I think you make a great point there. Baldr is hard to name with a reasonable descriptive name. That is a great indication for code smell: If you can't find a good descriptive name for it, maybe it should not be one module?

I ask everyone to challenge their assumptions here and keep an open mind. It is easy to dismiss this if you are already neck deep in the code base, but please approach this from the angle of a new contributor looking at the code base. At best the naming scheme is funny, at worst it is deterring.

**Comment by chaupow** [comment]
I would also welcome descriptive names.

I started this doc https://paper.dropbox.com/doc/Learning-Valhalla-R3f3v35j0Z0bD3pVeF9pu just for myself at the very first day working with valhalla to take down notes and I've had to look at the table often to translate nordic names to modules and what they do 🙈

**Comment by kevinkreiser** [comment]
The code smell one is pretty important. Organization and clarity are admittedly more useful in a project with contributors that are more loosely organized (physically). Though I worry that if we follow that rabbit hole all the way it might atomize all the things. I mean, I wonder if we then end up with just `valhalla::*` and not `valhalla::foo, valhalla::bar, valhalla::baz, ...`

@chaupow I'd be interested to know if today, you are still looking at this list or its in your head now. @TheMarex is right, since we came up with the names as we made new functionality they were always associated with the things they do. I would say its kind of a way to personify the behavior of a certain piece of code much like we do with actual people. For example: Kevin, he works on graph correlation or Greg, he works on graph data creation. Loki, he works on graph correlation and Mjolnir, he works on graph data creation. Basically they are characters in the story that is this code.

**Comment by danpat** [comment]
@kevinkreiser you know you're reading good quality fiction when it comes with an appendix with all the character names and a brief bio.

I too will put in a vote for more semantic namespaces using English words.  While the recent surge in popularity of the Marvel comic movies has brought some old Norse names into the common vernacular, the meanings aren't always obvious, and quite a few of the ones in use here remain obscure to the uninitiated.  It does add some friction when navigating the code-base, even after you've been staring at it for a few weeks.  

Perhaps this story will change over time, but it does seem a bit unnecessary to spend months baking a mapping of norse names -> functional groups into my brain (and having to constantly stop and think while it bakes) when I already have a perfectly good set of words with semantics attached, that I have in common with most other English speakers.

On the other hand, the names currently in use do a really good job of one thing that namespaces are for: avoiding naming collisions.

**Comment by chaupow** [comment]
@kevinkreiser i still haven't really spent lots of time with Valhalla, but yes, regularly looking at the table or wildly clicking and looking at all kinds of different folders 🙈
