### ISSUE TITLE
Cleanup and deprecate navigator

### ISSUE THREAD

**Issue by chaupow** [valhalla/valhalla#1347]
Development of the `navigator` started and was partly merged, but never got completely finished nor released.

We should discuss whether we want to maintain/deprecate/develop `navigator` in the future.

If we will deprecate it, let's clean up the code. 🙌 

cc @dgearhart

**Comment by kevinkreiser** [comment]
i was thinking this and also can we remove OSRM compatibility mode. it was basically the same story. it was developed and partially completed but not finished and so its a lot of code for really no gain. lets :hocho: both of them.

**Comment by dgearhart** [comment]
Split this ticket with remove [osrm compatibility](https://github.com/valhalla/valhalla/issues/1352) ticket
