### ISSUE TITLE
Add is_route_number boolean flag to sign element

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1356]
## Issue
We need to know which sign elements are `route numbers` (refs)
In OpenStreetMap - [exit information](https://wiki.openstreetmap.org/wiki/Exit_Info) is categorized to know which items are route numbers (refs)

## Tasklist
- [ ] Add `is_route_number` boolean flag to sign element
- [ ] During data conversion, set the `is_route_number` attribute to `true` if it is a `route `number` (ref)
- [ ] Assign in trip path builder
- [ ] Test to validate

@dnesbitt61 @gknisely

**Comment by dnesbitt61** [comment]
@dgearhart - I assume the is_route_number flag can only apply to kExitToward, kExitBranch? Would it ever be applied in the general tag parsing cases that look at the exit_to string?

**Comment by dnesbitt61** [comment]
@dgearhart - I assume there are changes to Sign within the TripPath proto (though these don't see obvious to me at first glance).

**Comment by dgearhart** [comment]
@dnesbitt61 correct only branch and toward. 
Not sure how to distinguish with `exit_to` approach

**Comment by dgearhart** [comment]
@dnesbitt61 we had this [issue](https://github.com/valhalla/valhalla/issues/1310) to outline the changes that need to happen after the data was available. Probably will split the issue into two - one for street names and one for signs. Hope to refactor the current TripPathBuilder street name implementation to use a street name object instead of a parallel array
