### ISSUE TITLE
All Request Parsing in One Place (mostly)

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1357]
## Issue
Currently we have a composite object with both `odin::DirectionsOptions` and `rapidjson::Document`. This is because we are half way through a refactor to move everything wrt to input parsing to a single location: `src/worker.cc::from_json`. The plan is that everything gets parsed into pbf at the very beginning of the request/action and we just use pbf after that, no more json strings lying around.

![References to the Rapidjson Object](https://user-images.githubusercontent.com/697548/41293824-5ca1bd40-6e24-11e8-9cd9-99c6c191f77e.png)

Above shows all the things that we reference from the rapidjson object. Most of them are fairly trivial and can be added to and accounted for in DirectionsOptions (we should rename that when this is done). The most difficult thing here is the costing parsing as different costings parse different things.

I would propose that each costing implemented its own costing_options pbf parsing. Of course each will need its own proto definition. these can probably all live in the same file so as not to explode the number of files. Then we can simply have the `from_json` function call the right costings static pbf parsing method as it encounters different `costing_options`.

## Tasklist
- [x] Review past work (#1088 and #1150 )
- [x] Review current flow of information for worker and action
- [x] Start refactoring with options that are simpler
  - [x] isochrone_action: contours, polygons, denoise, generalize, show_locations
  - [x] trace_route_action: shape_match, best_paths, gps_accuracy, search_radius, turn_penalty_factor
  - [x] trace_attributes_action: filters/action, filters/attributes, shape_match, best_paths
- [x] sync with @kevinkreiser prior to starting costing effort
- [x] Costing options will more effort - update after simpler options are complete
  - [x] route_action: costing model and costing options

**Comment by kevinkreiser** [comment]
cc @chaupow

**Comment by kevinkreiser** [comment]
some work for this was done previously:

https://github.com/valhalla/valhalla/pull/1150
https://github.com/valhalla/valhalla/pull/1088

**Comment by dgearhart** [comment]
@kevinkreiser and I discussed this morning about past efforts to combine the json parsing to pbf in one area. @kevinkreiser suggested we complete this effort prior to refactoring for v3. Currently, there is no in flight work - the effort stopped because of re-prioritization.

**Comment by dgearhart** [comment]
Updates will be pushed to the `request_refactor` branch
