### ISSUE TITLE
Cannot build on Amazon Linux

### ISSUE THREAD

**Issue by danmactough** [valhalla/valhalla#1383]
To use Valhalla on Qubole (managed Spark clusters), we need Valhalla to run on Amazon Linux. There is no way to use any other Linux distribution on Qubole.

I have been able (with difficulty) to successfully build Valhalla from source on Amazon Linux. There were several obstacles to overcome.

- [ ] cmake fails to detect the correct installation location for Amazon Linux (will open a PR to resolve this)
- [ ] Amazon Linux ships with an older version of boost (v1.53) (Can we use v1.53?)
- [ ] something (I haven't tracked down if it's part of Valhalla directly or one of its dependencies) has a dependency on `emacs-filesystem`, which is not available at all for Amazon Linux (Need to track this down and find an elegant resolution. Currently, I'm installing a CentOS version of `emacs-filesystem`, which _appears_ to work, but that's not a permanent solution.)

**Comment by oxidase** [comment]
@danmactough i have tried to compile Valhalla in an `amazonlinux:latest` image.
The first fail is related to the Boost.DateTime 1.53 library
```
In file included from /usr/include/boost/date_time/local_time/local_time_types.hpp:18:0,
                 from /usr/include/boost/date_time/local_time/local_time.hpp:13,
                 from /valhalla/valhalla/baldr/datetime.h:10,
                 from /valhalla/src/baldr/datetime.cc:11:
/usr/include/boost/date_time/local_time/custom_time_zone.hpp: In instantiation of 'bool boost::local_time::custom_time_zone_base<CharT>::has_dst() const [with CharT = char]':
/valhalla/src/baldr/datetime.cc:1672:1:   required from here
/usr/include/boost/date_time/local_time/custom_time_zone.hpp:67:30: error: cannot convert 'const boost::shared_ptr<boost::date_time::dst_day_calc_rule<boost::gregorian::date> >' to 'bool' in return
       return (dst_calc_rules_); //if calc_rule is set the tz has dst
```

**Comment by kevinkreiser** [comment]
we haven't used anything older than boost 1.54 to build valhalla... i dont suppose you can get a newer version of boost given that that is kind of against the mantra of centos... im surprised you even have a compiler that supports c++11 :trollface:

**Comment by danmactough** [comment]
> The first fail is related to the Boost.DateTime 1.53 library

That's correct @oxidase 

I'm seeing new failures building from source on the current master. Let me resolve those and then I can  share the process to get a successful build.

**Comment by danmactough** [comment]
> i dont suppose you can get a newer version of boost

Yeah, I'm working on that @kevinkreiser 😄Currently, I am building boost v1.58 from source. (Which I would rather not do.)

**Comment by danpat** [comment]
@danmactough We could consider using https://github.com/mapbox/mason to fetch pre-compiled binary dependencies.  I've used Mason previously to get things running on Amazon Linux boxes.

**Comment by danmactough** [comment]
> It's quite possible that @allierowan might do this anyway as part of #1341, as we'll need to publish static binaries that'll work on multiple platforms there.

mason is probably the way to go for getting the binary onto the Qubole nodes. We do still need to get the build process itself working. (The way I'm doing it now includes building a specific version of boost from source. That would need to be part of the build artifact. Or I guess a separate build artifcate, maybe.)

**Comment by danmactough** [comment]
Also, FWIW - I'm building boost 1.58 from source because that's what ubuntu-xenial uses (which works) even though later versions of boost exist (but didn't work -- got build errors).

**Comment by danpat** [comment]
Over in OSRM-world, we added an off-by-default "build statically with mason deps" flag to CMakeLists.txt:

https://github.com/Project-OSRM/osrm-backend/blob/master/CMakeLists.txt#L37-L54

It would be straightforward enough to port that over here, and use it in environments where system dependencies are messed up.

**Comment by danmactough** [comment]
> an off-by-default "build statically with mason deps" flag to CMakeLists.txt

That's definitely an option. I thought there was a static build flag? (Maybe that was with the autoconf build system?)

**Comment by danmactough** [comment]
@oxidase Here's my build script:

```bash
#!/bin/bash -x
echo "Installing dependencies"

yum -y -q install \
  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
  https://rpmfind.net/linux/centos/7.5.1804/os/x86_64/Packages/emacs-filesystem-24.3-20.el7_4.noarch.rpm

yum-config-manager --enable epel >/dev/null
yum -q groups mark convert
yum -y -q groupinstall "Development Tools"
yum -y -q install \
  cmake3 \
  jq \
  boost-devel \
  libcurl-devel \
  python27-devel \
  python35-devel \
  libcurl-devel \
  lua-devel \
  lz4-devel \
  geos-devel \
  protobuf-devel \
  sqlite-devel \
  libtool \
  protobuf-compiler \
  zlib-devel \
  libspatialite-devel \
  libspatialite \
  bzip2-devel

echo "Building boost"
PYTHON3_BIN=$(which python3)
PYTHON3_ROOT=$(which python3 | sed -e 's#/bin/python.*##')
PYTHON3_VERSION=$(python3 -c "import platform; print('.'.join (platform.python_version_tuple ()[:2]))")
PYTHON3_ABIFLAGS=$(python3-config --abiflags)

curl -sL http://downloads.sourceforge.net/boost/boost_1_58_0.tar.bz2 > /tmp/boost_1_58_0.tar.bz2
tar jxf /tmp/boost_1_58_0.tar.bz2 -C /usr/local
cd /usr/local/boost_1_58_0
./bootstrap.sh \
  --with-toolset=gcc \
  --with-icu \
  --with-python=${PYTHON3_BIN} \
  --with-python-root=${PYTHON3_ROOT} \
  --with-libraries=atomic,chrono,date_time,filesystem,iostreams,regex,system,thread,program_options,python
sed -i "/using python/c\using python : ${PYTHON3_VERSION} : ${PYTHON3_BIN} : ${PYTHON3_ROOT}/include/python${PYTHON3_VERSION}${PYTHON3_ABIFLAGS} ;" project-config.jam
./b2 -q -d0 --layout=tagged install
echo "/usr/local/lib" >> /etc/ld.so.conf.d/libboost_1_58_0.conf
ldconfig

echo "Building valhalla"
cmake3 .. -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_DATA_TOOLS=Off \
  -DENABLE_PYTHON_BINDINGS=On \
  -DENABLE_SERVICES=Off \
  -DPYTHON_EXECUTABLE=$(which python3)
make -j$(nproc)
make install
```

**Comment by PureW** [comment]
Closing this due to age. Please re-open if still an issue.
