### ISSUE TITLE
Map matching: edge speed 

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#1392]
I am working on hooking map matching to map applications via Valhalla working on mobile device and communicating using http://localhost. This would be an extension of routing that works perfectly on mobile. 

While reading through API description (https://github.com/valhalla/valhalla-docs/blob/master/map-matching/api-reference.md#outputs-of-trace_attributes), it seemed to me that its possible to get the speed of the vehicle through `edges.speed`. However, that would require the ability to specify when each location in `shape` input has been measured. Or do I misunderstand meaning of edge.speed?

Hence the question(s): 

* is it possible to get the current speed along the edge using map matching directly from Valhalla?

* if it is, how do I specify the time-moments that correspond to the coordinates using HTTP API?

Obviously, I can just get the last few points in the matched trajectory, figure out distances traveled along edges (combination of corresponding distances and edge lengths) and get the speed via that. Although, if its already done in Valhalla, would be silly not to use it.

**Comment by rinigus** [comment]
I see, that makes sense. Thank you very much for explanation! As for real speed, with the sudden death of the navigator, it maybe out of scope for Valhalla right now. I will continue work on the integration of the map matching and, if all goes well, will try to write the code for speed estimation on the client side. If it will be general enough, I'll paste it later over here as a reference for other interested developers.

Since the issue is resolved and the meaning of the speed is clear, I am closing the issue. Please reopen if you wish to address it more.

**Comment by kevinkreiser** [comment]
Wait wait, this isnt the whole picture! When we did opentraffic we did exactly this and in fact this is part of the python api currently. The trick is it was all based around osmlr and not the graph edges (so really just one layer of indirection deeper). It might take a bit of a refactor but if we just treated each edge as a single osmlr segment we'd have this already. you can see the code here: https://github.com/valhalla/valhalla/blob/master/src/meili/traffic_segment_matcher.cc

it does the matching to get the edges, then it pulls the osmlr segments from the edges and interpolates times along them. from the times it can then calculate the speeds. its not exactly close to what you are asking for but its definitely closely related.
