### ISSUE TITLE
The Great Migration of libvalhalla to One Repository

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#14]
To those of you who are @ mentioned below we'd like to inform you we'll be migrating libvalhalla, which is currently comprised of the midgard, baldr, sif, skadi, meili, mjolnir, loki, thor, odin, tyr and tools repositories into this single repository. We're doing this in an effort to make ourselves more productive but also to make things easier for our contributors. The plan is to have this work completed on the 2nd of February 2017.

We'll be doing this in several steps to make sure the commit history as well as the issues are retained:

- [x] merge the code together (`git merge --allow-unrelated-histories`) and resolve conflicts
- [x] copy issues (not prs?) using github api, some authors will become mentions instead
- [x] mark old repos as deprecated and eventually remove them
- [x] simplify debian packaging
- [x] update the docs by moving each individual readme to its own place, trim overlap and fix links
- [x] simplify chef valhalla source install
- [x] simplify docker valhalla source install
- [x] simplify circle.yml
- [x] test like mad
- [x] :birthday: 

Note that because of the projects' directory structures, if you've got work in progress on libvalhalla you should be able to take your patch and apply it mostly cleanly to a branch from the new single repository. The only likely places for collisions would be in places like `Makefile.am` or `configure.ac` or anything at the top level directory.

If you are mentioned below its because you've made an issue, a pull request or a comment or you are a watcher or a stargazer on one or more of our main library repositories. A huge thank you goes out to everyone who has been helping us to make libvalhalla so great!

**Comment by kevinkreiser** [comment]
thanks to:

@0nko
@adnils
@ahzf
@airgiser
@akavel
@akhilpo
@AlbertJP
@Alex237
@alexmorral
@alixaxel
@almccon
@anatolinicolae
@andersonDadario
@andreipopovici
@andreis
@andrewljohnson
@andrey-str
@andreyz
@angelocky
@angusshire
@antoniomedrano
@araichev
@arnau
@asim
@austntatious
@balazsbela
@baldur
@barbeau
@barrycug
@bcamper
@bedla
@benstadin
@bentley
@bfontaine
@bitner
@blvz
@bmordue
@BobbyBlue42
@bradh
@buma
@burritojustice
@bvbever
@caio
@Checksum
@chkob
@chr33s
@chrisfosterelli
@chrislukic
@cookry
@coolsebz

**Comment by kevinkreiser** [comment]
thanks to:

@cosmicanant
@costales
@costypetrisor
@craigwblake
@curtkim
@cyang-kth
@d1g
@dacresni
@danvk
@darkwizzard
@davidar
@ddiakopoulos
@derekargueta
@descilla
@deutschehandarbeit
@dexterbt1
@dgearhart
@dhodge229
@dmbreaker
@dmeignan
@dnesbitt61
@Drag0s
@drewda
@eamartin
@ecgreb
@eczajk1
@eliotjordan
@ericjohn
@ericrwolfe
@ethervoid
@ezheidtmann
@felixpalmer
@florianf
@flp-gpc
@fnicollet
@folz
@frodrigo
@fsaric
@fuCtor
@gebrits
@gerhardneuhold
@ghosthamlet
@gknisely
@gkze
@glennon
@glw
@gmontalvoriv
@gregwhammond
@guido4000
@gyllen

**Comment by kevinkreiser** [comment]
thanks to:

@h0st1le
@habibutsu
@hallahan
@hanbyul-here
@haoziluo
@hastebrot
@heffergm
@hjanetzek
@HydroLogic
@iarwain
@iCyberon
@iemelyanov
@irees
@iwasrobbed
@jackdoe
@jacquestardie
@JesseCrocker
@jgoldfar
@jiangplus
@jiegec
@jlevente
@jmoe
@johnjameswhitman
@JoshuaKolden
@joto
@jrcii
@jsanders
@kafitz
@kaih1
@karimnaaji
@kavisingh
@kbbaker
@kdiluca
@kelvinabrokwa
@kevinkreiser
@kgryte
@kinnou02
@kirantpatil
@kkowalsky
@KlemenSpruk
@Kopkins
@kristiansaarela
@l3pp4rd
@lamarqua
@LEDominator
@leloyo
@lidonghua
@lipanski
@locationflow
@louh

**Comment by kevinkreiser** [comment]
thanks to:

@lucasdavila86
@luciocorrea
@luiscape
@m12i
@Mafii
@maoabc1818
@mapnerd
@Mappy-team-LBS
@matbeard
@mayorgatellez
@mbektimirov
@mcanthony
@mcoimbra
@meetar
@meisyal
@MichaCo
@MichaelBrowning
@michalbcz
@MikeLockz
@mikolalysenko
@MirrorrorriN
@missinglink
@mjcunningham
@molind
@morganherlocker
@mormegil-cz
@mpuig
@MrXo
@mtehver
@nathanv
@NDuma
@nemobis
@nickplesha
@nisarg09
@nizq
@noblige
@nvkelso
@octanebaby
@orangejulius
@paladin74
@paolobenve
@pavel-citymaps
@pengxu7
@peterneubauer
@pindamonhangaba
@pirxpilot
@pjsier
@pkontschieder
@ptpt
@pwplus

**Comment by kevinkreiser** [comment]
thanks to:

@quilkin
@raethlo
@rafatower
@randymeech
@raylee
@redaready
@re-han
@richpersaud
@RicoElectrico
@rikkit
@rmglennon
@rmsaksida
@robhawkes
@Rob-ot
@rossanag
@rudazhan
@Rudymil
@sahilchinoy
@sandrauddback
@saturation
@schaelle
@sergiocorreia
@shashanktomar
@shawnbot
@shawnmoyer
@skorasaurus
@smWork
@soheilarmin
@souperneon
@SourceInsight
@spartango
@stifoon
@strongwillow
@stuartlynn
@sunwenjun
@Sun-Wukong
@svagionitis
@svenkreiss
@svieira
@talllguy
@tallytalwar
@tdmackey
@TeXitoi
@thatdatabaseguy
@theophoric
@theunreplicated
@thierrymarianne
@ThomasG77
@tidwall
@timelyportfolio

**Comment by kevinkreiser** [comment]
thanks to:

@timothya
@tmcw
@tobyjoe
@todrobbins
@tombh
@tomdean
@tomhughes
@TommasoDb
@tomtaylor
@trefecta
@tumluliu
@tunnuz
@tyrasd
@ucali
@ustroetz
@valipan
@vamsiikrishna
@vincentsarago
@vmx
@w8r
@wafisher
@walkermatt
@xdbr
@xhzhuhit
@xlqian
@Xorlev
@xptr33
@ybkuang
@yipcma
@yoshuawuyts
@yujinlim
@yyinter
@yzadik
@zerebubuth
@zhyueqi
@zikil

**Comment by kirantpatil** [comment]
This is great news. I am using OSRM and thought of using valhalla, but could not since things were scattered.

I expect things to work out of the box like OSRM.

If you are heading in that direction then all is well. :smile:

**Comment by kevinkreiser** [comment]
thanks to everyone bearing with us on this. all of the code and commit history as well as all of the issues have been moved to this repository. feel free to clone it, make issues, make prs and get on with getting things done! Also please try to avoid creating new issues against the old repositories. We'll eventually be shutting those down.

**Comment by kevinkreiser** [comment]
the great migration has been a success. if you see any issues or experience any problems feel free to let us know! thanks again to everyone above!

**Comment by AlbertJP** [comment]
The first post's text (ie the description of the issue) is missing in many (all?) issues copied from the sif repository. #419 is an example of an issue which is still open, which is missing its description.

**Comment by kevinkreiser** [comment]
thats true. halfway through copying issues for @dnesbitt61 we made a change
to the script that did the copying to be robust to issues without a `body`.
this resulted in losing the `body` of the issues copied after that point.
its definitely not all of them but its a decent number. ive been copying
the bodies of the ones ive found still in google cache for the issues that
are still open. i havent done them all but its probably at good 50 or so
issues in total. maybe ill take a morning and go through them all.
apologies for the error!

2017-02-11 11:17 GMT-05:00 Albert Pool <notifications@github.com>:

**Comment by kevinkreiser** [comment]
@AlbertJP im running a job to move the missing bodies (sounds more murder-y than it really is) into the new issues. it was well over the 50 i had originally quoted! ill paste a list of affected issues when done.

**Comment by kevinkreiser** [comment]
full list of issues which have been updated to contain the original bodies are as follows:

475
474
473
469
468
467
466
465
464
463
461
460
459
458
457
453
452
451
450
449
448
447
446
445
444
441
440
439
438
437
436
435
434
433
432
431
430
429
428
427
426
425
424
423
422
421
420
419
418
417
416
415
414
413
412
411
410
409
408
407
406
405
404
403
402
400
399
398
397
396
389
388
387
386
385
384
383
382
381
376
375
374
373
372
371
370
369
368
367
366
365
364
363
360
358
357
356
355
354
352
351
350
349
348
347
346
345
344
343
342
341
339
338
337
336
334
333
330
329
328
327
326
325
324
323
322
321
320
319
318
308
306
302
295
280
278
275
270
269
268
267
262
256
255
254
253
252
251
250
247
245
244
239
237
231
229
227
223
217
216
215
213
212
211
209
208
207
206
204
202
