### ISSUE TITLE
tyr::actor_t: change logging

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#1407]
Currently, `tyr::actor_t` logs information into std stream or file. When integrating with the application, would be great to specify some function that could used to log the messages. If there is such a facility, I must have missed it.

**Comment by kevinkreiser** [comment]
currently we are using `valhalla::midgard::logging` it supports logging to file and stream as you have noted. you are asking for some functionality to the logger to pass logs to some other place. the only difficulty i see there is that it would change the way the logging api is configured and require some means of passing other arguments into it. i'll think about how we can do this. maybe we can just add a method to the logger that will allow you to replace its guts with whatever you want. so you can just configure a `null` logger and then call `logger.imbue(your_log_function)` to inject functionality into it for example.

**Comment by rinigus** [comment]
But that would require somehow to get access to the logger object as well. From the configuration JSON, I had a feeling that there are multiple loggers involved. If its only one object in practice, maybe we could just get an access to it through some static function and, regardless to JSON configuration, have an ability to provide log function - using the same API as you suggested above.

**Comment by kevinkreiser** [comment]
actually i guess we already support what you need! i forgot since i wrote this so so long ago! our logger is a singleton you can get it here:
https://github.com/valhalla/valhalla/blob/master/valhalla/midgard/logging.h#L47

but the logging api lets you make your own logger, register it, and then configure logging to use your custom logger. this should be enough for you to make your own thing without having to inject functionality in any other way. have a read over the code in the source file and let me know if you have other questions on how to do it.

**Comment by rinigus** [comment]
Great! I will try it and let you know how it goes. Thank you.

**Comment by rinigus** [comment]
Redirection of logging worked very well. Had to 

* derive Logger class from `valhalla::midgard::logging::Logger`

* register it (in example, under `server`): 
```C++
  valhalla::midgard::logging::RegisterLogger("server",
                                             [](const valhalla::midgard::logging::LoggingConfig& config) {
      valhalla::midgard::logging::Logger* l = new ValhallaLogger(config);
      return l;
    });
```

* configure static logging to use it:
```C++
  valhalla::midgard::logging::Configure({ {"type", "server"}, {"color", ""} });
```


So, I can mark the corresponding issue resolved and I hope that the other users would find this short howto useful if facing the same problem. Thank you very much!
