### ISSUE TITLE
tyr::actor_t: curl as a requirement

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#1408]
It looks like libcurl is required by Valhalla lib when using `tyr::actor_t` even if it is compiled with 

```
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DENABLE_DATA_TOOLS=OFF -DENABLE_PYTHON_BINDINGS=OFF -DENABLE_SERVICES=OFF
```

Is there any reason for it or is it just remains of HTTP API?

**Comment by kevinkreiser** [comment]
yes its because the `GraphReader` has the ability to get tiles from http via curl. we can add another flag to the build to disable that functionality and not require curl at all in that case

**Comment by rinigus** [comment]
Well, it doesn't bother me, as such. At least its clear that this lib is needed and its not some mistake. I presume that all curl initialization is done by Valhalla, if needed. Or should we be aware of it and call easy init function(s)?

Please feel free to close the issue if you wish.

**Comment by kevinkreiser** [comment]
yes it takes care of the init and deinit of curl automatically without you needing to see here: https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/curler.h

**Comment by rinigus** [comment]
Excellent! Thanks!
