### ISSUE TITLE
Backport node bindings to 2.6

### ISSUE THREAD

**Issue by allierowan** [valhalla/valhalla#1412]
## Background

We are in the process of writing node bindings for Valhalla which expose all of the `tyr::actor` actions (i.e. `route`, `locate`, ...). We currently working toward a 3.0.0 release of Valhalla that will include some breaking changes, and are pushing the node bindings in that same direction. Ultimately, we would like to be able to publish a stable node module to the npm registry. As of last week, the `valhalla` namespace in npm was taken by another small package. The npm team agreed to transfer that package to us to be used by this project!  🎉 They have asked us to publish something to the package ASAP to prove our stake in the project, so we are going to publish an alpha release to get something up there.

## Backporting to 2.6.x

We are going to be [publishing release candidates _of 3.0.0_](https://github.com/valhalla/valhalla/pull/1411) to the npm registry as we have them, since that is the version we are currently sprinting toward. When we publish a 3.0.0 pre release, we will tag it in npm as `next`. That way, you will not download it by default when you run `npm install valhalla`. However, it could be useful to have a 2.6 version published as well, especially since _right now_ the `route` functionality matches 2.6 and does not contain breaking changes. 

We could do this by backporting the node bindings to the 2.6 branch, and tagging the 2.6.x package as `latest` in npm. This way, folks doing npm install valhalla would get 2.6.x. This is not on my immediate roadmap, but I may come back to it eventually. However, if someone else would like to take this on, please do so!

**Comment by danpat** [comment]
@allierowan `npm` has a concept of "tags" on version numbers.  By default, if you `npm publish`, the special tag `latest` is applied to the version you've just uploaded.  When you `npm install`, you will get the version which has the `latest` tag, unless you specify a version.

One thing we could do is backport, then `npm publish` 2.6.x, and assign the `latest` tag with it.  This way, folks doing `npm install valhalla` would get 2.6.x.  When we publish 3.x pre-releases, we can do `npm publish --tag next`, which will put the non-special tag `next` on the version, and avoids moving `latest`.  3.x releases can be installed by explicitly doing `npm install valhalla@3.x`, but they won't be the default if the version number is excluded.

**Comment by allierowan** [comment]
@danpat that makes a lot of sense - I am updating the text of the original ticket to reflect this plan!

**Comment by danpaz** [comment]
Closing, node bindings were removed in #2502 .
