### ISSUE TITLE
Numeric underflow in timezone diff calculator

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#1426]
`clang++` currently complains about a comparison:

```
valhalla/src/baldr/datetime.cc:522:45: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
      if (seconds - abs(td.total_seconds()) < 0) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
1 warning generated.
```

This is caused by https://github.com/valhalla/valhalla/blob/537146b6d978b6e70de12f0542909880fac871ae/src/baldr/datetime.cc#L521-L525

The problem is that `seconds` is `uint64_t`, which causes the whole expression to become unsigned.  It's not possible to have an unsigned value less than zero, so this expression will always be false, regardless of the value of `td.total_seconds()`.

The code notes `// this should never happen`, but the check doesn't actually verify that it doesn't.  Instead, we may get a `seconds` value that underflows (e.g. 0 - 1 == 1.844674407370955e19)

**Comment by dnesbitt61** [comment]
Fixing this as I work with the time dependent algorithms. Changing this method to return the seconds difference between time zones so localtime can be adjusted within the algorithms.
