### ISSUE TITLE
Routing service API: return road speed limit

### ISSUE THREAD

**Issue by KindDragon** [valhalla/valhalla#1433]
It would be useful if the routing service returned a speed limit on the road, like the HERE API (https://developer.here.com/documentation/routing/topics/resource-calculate-route.html)

**Comment by drewda** [comment]
You can do this with Valhalla by:

1. request a route
2. submit the entire route geometry or a portion of it to the `trace_attributes` action: https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md#trace-attributes-action
