### ISSUE TITLE
Node Bindings Segfault when called with undefined

### ISSUE THREAD

**Issue by allierowan** [valhalla/valhalla#1444]
In general, the error handling in the node bindings needs to be improved - we don't get specific error messages in many cases when the input is malformed. That issue is ticketed [here](https://github.com/valhalla/valhalla/issues/1406). 

More urgently however, the node bindings currently throw a seg-fault when undefined input is passed in. We should validate input in the bindings and throw an exception before it gets to that point. I am also wondering if this is a vulnerability in tyr::actor that should be fixed.

**Comment by kevinkreiser** [comment]
If the request is malformed the c++ within the actor will throw an exception. What we need to do is catch that exception in the node bindings and signal it out to javascript through the napi. I'm not sure how to do that second part, but the first part is quite straight forward.

**Comment by kevinkreiser** [comment]
oh i see, it already catches that. must be upstream from the actual actor possibly in the bindings where they parse the request?

**Comment by allierowan** [comment]
yep, those are the two places to look.
