### ISSUE TITLE
nodejs bindings should take advantage of aync worker queue

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#1455]
NodeJS is single-threaded.  However, it has a good event loop implementation.

When someone calls into the node bindings to calculate a route, the route calculation should not block the main event loop like it currently does.

Instead, the route calculation should be farmed off onto a worker thread, and when the response is ready, the callback should be called with the results on the main event loop thread.

This is achieved by using the [`napi_create_async_work`](https://nodejs.org/api/n-api.html#n_api_napi_create_async_work) function.

It might be worth looking at using https://github.com/nodejs/node-addon-api instead of N-API directly - `node-addon-api` has an easy-to-use `AsyncWorker` base class that would greatly simplify the implementation here.

(example of an async worker here: https://github.com/nodejs/node-addon-api/blob/master/test/asyncworker.cc)

/cc @allierowan

**Comment by danpat** [comment]
@kevinkreiser Yes, NodeJS does this under the covers already - we just need to move our instantiation into workers, instead of calling them synchronously like we do currently.

Although the view of the world that NodeJS presents to Javascript code is single-threaded, Node does maintain a pool of worker threads for async native tasks.  Calling `napi_create_async_work` uses workers from this thread pool, and its size can be configured.

What we'll achieve with this change is that the main, single V8/Javascript executor thread isn't blocked while routes are calculated.

**Comment by kevinkreiser** [comment]
@danpat roger that, sounds great!
