### ISSUE TITLE
Filter destination edges based on driving side

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1464]
This would allow a way to filter the edges at the destination (or through locations) so that the lat,lon of the location lies on the same side of street as the driving side. On a 2-way street this is desirable when  pick up a passenger. This assumes that the location lat,lon is sufficiently precise compared to the street geometry so that it allows a side of street computation.

This would be triggered by a new, optional parameter to the input location. 
Logic would be added to loki to filter edges based on driving side of street and computed side of street of the location.

Would this only be done for 2-way streets? If not, what happens for doubly digitized roads with the location lat,lon in between the carriageways?

**Comment by nilsnolde** [comment]
this looks done to me:)
