### ISSUE TITLE
Less Dependencies

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1465]
# Why Reduce Dependencies

Valhalla currently makes use of a lot of dependencies. In some cases these dependencies are pretty light weight (like header only rapidjson). In other cases we need to jump through some hoops to install them on the target platform. Sometimes those hoops are quite easy (`apt-get`) but sometimes they require you to build from source. We want to avoid the cases in which we need to build from source and make valhalla easier to build everywhere.

Dont worry, we aren't porting valhalla to `C` (yet..just kidding)

This issue will serve as a meta issue track all the dependencies we have and which ones we'd like to squash to make building valhalla easier. What follows is a list of dependencies and issues detailing how we plan to go about removing them. We won't end up removing all of them... At some point we'll have to come to a compromise between pain of re-inventing pre-existing but annoying to build code and pain of building said pre-existing code.

## libboost

Quite a lot of these will be found in the `DATA_TOOLS`, `SERVICES`, `TOOLS`, etc portions of the library. Anything that we find that can be avoided as a dependency by simply running a slim (routing functions only) build a la:

    cmake -DENABLE_TOOLS=OFF -DENABLE_DATA_TOOLS=OFF -DENABLE_SERVICES=OFF -DENABLE_PYTHON_BINDINGS=OFF -DENABLE_NODE_BINDINGS=OFF ..`

We can simply avoid removing as its not on a critical path. Here's an exhaustive list of what we currently use from boost. We should mark those which are not part of the slim-routing-functions-only build with `wontfix` and open issues corresponding to the plan for removal or replacement of the rest. Boost publishes a list of what isnt header only here: https://www.boost.org/doc/libs/1_68_0/more/getting_started/unix-variants.html#header-only-libraries.

- [ ] boost::date_time - possibility of doing in two phases by deferring some timezone logic until later (with some assumptions)
- [ ] boost::gregorian - more time stuff need to see where its used if its not just in mjolnir
- [ ] boost::posix_time -  ditto the above two
- [ ] boost::local_time - ditto more time stuff
- [ ] boost::property_tree -  #1474
- [ ] boost::variant - used for json serialization, we should ditch and use rapidjson or switch to header only variant for the time being
- [ ] boost::apply_visitor - this is paired with the above variant
- [ ] boost::static_visitor - more variant
- [ ] boost::optional - use std::optional in c++14
- [ ] boost::none - goes with optional
- [ ] boost::heap - this is needed in map matching so we should see what the performance hit will be for using stl containers
- [ ] boost::shared_ptr - use regular std::shared_ptr
- [ ] boost::make_shared - again use std methods like above shared_ptr
- [ ] boost::filesytem - done for routing stuff may do or not do for mjolnir
- [ ] boost::format - mostly in odin possibly, could use std::regex or do manual string manip
- [ ] boost::algorithm - mostly helper functions we can reimplement pretty quickly
- [ ] boost::replace_all - these are like algorithm
- [ ] boost::is_any_of - these are like algorithm
- [ ] boost::starts_with - more algorithm stuff
- [ ] boost::geometry - probably only in mjolnir
- [ ] boost::hash_combine - probably only in mjolnir
- [ ] boost::lexical_cast -  this is like the stoi functions we can probably just use instead
- [ ] boost::noncopyable - find and use standard modern c++
- [ ] boost::program_options - ignore for a little while
- [ ] boost::python - dont need to worry about its the only way to get bindings with using swig directly
- [ ] boost::adaptors
- [ ] boost::archive
- [ ] boost::char_separator

## libprotobuf

We make a lot of use of this... The main problem here is that to get the right version on the target platform you may need to build it from source which is something we want to avoid. We mainly use pbf for IPC and as a response format (planned work). So we are mostly interested in the schema and versioning and binary protocol features of pbf. We should investigate what it would take to use [protozero](https://github.com/mapbox/protozero) coupled with a proto definition for clients that want to use standard means of reading our responses. At that point then only the tests would need access to protoc to make sure our protozero serialized stuff came out correctly.

This would be a lot of work so it would be fantastic if there were a way to generate protozero like code given a `.proto` file.

## localedef

This is a binary dependency that we make use of to generate posix locale files for use with std::locale. We need to see how this will work on different platforms. Already we know that macos does not easily work with localedef. It might be sufficient for us to just check in the posix locale files generated on a debian based system and call it a day. Its unclear how though to get std::locale to use said files on all target platforms. Linux systems seems to respect the `LOCPATH` environment variable but who knows what other systems expect.

## libcurl

This is widely available and we shouldn't need to avoid it as a dependency.

## zlib

This is widely available and we shouldn't need to avoid it as a dependency.

## libprime_server

its not part of the `slim` build. so we can ignore it as a dependency for now.

## sqlite and spatialite

its not part of the `slim` build. so we can ignore it as a dependency for now.

## napi

its not part of the `slim` build. so we can ignore it as a dependency for now.

## libgeos

its not part of the `slim` build. so we can ignore it as a dependency for now.

## liblua

its not part of the `slim` build. so we can ignore it as a dependency for now.

## libpython

its not part of the `slim` build. so we can ignore it as a dependency for now.

**Comment by kevinkreiser** [comment]
please note that for a lot of the stuff mentioned above there are already some issues written. it would be great if we could cross reference those while we make progress toward this meta-issue here.

**Comment by dnesbitt61** [comment]
@kevinkreiser - would you consider this complete with recent work to remove some boost dependencies outside of data building?
