### ISSUE TITLE
Add date_time and traffic/speed lookup to isochrones

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1486]
Currently only multimodal isochrones have date time support. Should support date time and speed lookup within forward and reverse isochrones. A couple technical questions:
1) Do not do speed lookup based on time for some costing methods (pedestrian, bicycle, motor scooter)?
2) How should time be handled when multiple origin locations are present? Assume the date time would be converted into the timezone at each location?

**Comment by danpat** [comment]
> How should time be handled when multiple origin locations are present?

That's a good thought.  Conceptually, I think "local time at the origin" feels most natural, so yeah, a timezone lookup for each coordinate.

Another option might be to extend the `date_time` parameter to support multiple times, one for each origin (or move `date_time` into the origin descriptor as a new property instead of something that applies to the whole request).

**Comment by dnesbitt61** [comment]
For an isochrone with multiple origin locations there has to be a single time that is used - and probably stipulating that it is local time at the first location makes sense. When multiple locations are presented it is not computing separate isochrones for each location, rather it is a composite isochrone.

**Comment by walkerke** [comment]
@dnesbitt61 this sounds excellent.  Quick question - does your comment above mean that reverse isochrones are already implemented?  I only see it on the wish list in the isochrone documentation.  Or does this mean that reverse isochrones are in development?

**Comment by dnesbitt61** [comment]
Reverse isochrones (e.g. which areas can get to a specific location or locations) implies traversing the network in reverse. There is a test method in isochrones called ComputeReverse, but it is not currently hooked into the interface anywhere. The main reason to not expose this is that multimodal isochrones cannot work with this method due to a limitiation in how we store the transit graph and schedules. Basically transit lines are only stored in the forward direction - there is no way to traverse a transit line backwards. 

One could hook in ComputeReverse for other costing models. However, I also am struggling with how time dependent (traffic) based isochrones would work when the network is traversed in reverse?

**Comment by walkerke** [comment]
I appreciate the response.  Thanks for all you do on this project!
