### ISSUE TITLE
Possible Memory Leaks Exposed by Long Running Servers

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla#1503]
If there is another/better way to do this, that's perfectly fine, but it'd be useful if valhalla supported systemd health checks natively.

I'd be willing to help with this if you could point me in the right direction as to where this should be implemented. I realize there will probably be some specialized knowledge of the architecture required to implement liveness checks.

(I am opening this issue because I've seen servers end up in what appears to be a hung state where they won't respond to requests, but the process is still live, but I don't have any useful debug info to provide, so supporting systemd watchdog would at least help on one front.)

**Comment by danpat** [comment]
I think this probably would end up being part of https://github.com/kevinkreiser/prime_server.

**Comment by ianthetechie** [comment]
That may be the case...

The specific thing I've run into is that when running `valhalla_service`, it will occasionally run itself out of memory. Then the OOM killer ends up killing _something_ that leaves the service technically running (the process is live), but unable to respond to requests. A quick glance through `valhalla_service.cc` and I see a lot of threading going on, but not any process forking, so I'm not sure why this is possible. My initial thought was that liveness checks via the systemd watchdog might be a good way to do it. I've also considered writing a minimal wrapper "service" binary that forks, exec's `valhalla_service` in the child process, and then handles liveness checks and kills the child if it becomes unresponsive. But of course, fixing the issue would be even better ;)

Some more info:

* I'm running the 2.6 branch (with inconsequential modifications).
* I'm running on a server with 16GB of RAM. While the answer may be "just add more RAM," it often runs for weeks on end with reasonable workloads stably. Then it will eventually run itself out of RAM and we're not sure why. Nothing else on the system uses any measurable amount of RAM.

**Comment by kevinkreiser** [comment]
@ianthetechie we should check around for leaks first imho. it would be better to be sure we weren't leaking than spending the time to implement sd_notify handling and still have the leak.

wrt to watchdog, im not sure whether it needs to be on the main thread or other threads but in either case it seems like it could be accomodated with some platform specific ifdefs.

regarding the possibility of a leak, are you using tiles in a `tar` format or `.gph` files in directories? what types of requests are you doing, `route` `sources_to_targets` `isochrones` `trace_*`?

**Comment by ianthetechie** [comment]
@kevinkreiser `.gph` files in directories, doing exclusively `route` requests.

If you've got any ideas regarding checking for memory leaks and are looking for help, I'd be happy to lend a hand. It's been a bit since I did serious C++, but I seem to remember something about using valgrind to check for leaks...

**Comment by kevinkreiser** [comment]
yep valgrid will be the first place we look. i cant do this at the moment but we'll get around to it shortly!

**Comment by dnesbitt61** [comment]
Running valgrind on valhalla_run_route (valgrind --leak-check=full --show-leak-kinds=all ./valhalla_run_route ...) I see some protobuf references. Adding  google::protobuf::ShutdownProtobufLibrary(); cleans up the valgrind run but a couple reachable blocks still show (checking further).

Is this issue related: https://github.com/valhalla/valhalla/issues/1213

**Comment by kevinkreiser** [comment]
yeh pbf is a red herring, id ignore those!

**Comment by dnesbitt61** [comment]
is this still an issue? We fixed one problem with bicycle costing that led to increased memory use but I think that was due to code added after this issue.

**Comment by kevinkreiser** [comment]
I wonder if @danpat 's suggestion is the right one, we've been tracking some strange behavior over here: https://github.com/kevinkreiser/prime_server/issues/62

**Comment by danpat** [comment]
@kevinkreiser My suggestion was more that the systemd health check feature belonged in prime_server, not valhalla core.  But I guess memory leaks could be over there too :-)

**Comment by kevinkreiser** [comment]
well i'm not sure its a leak! but there are definitely important implications depending on how you run it.

**Comment by ianthetechie** [comment]
Hey guys, thanks for looking into this.

First, yes, it is still an issue as of 2.7.0. We had some issue building the TZ database on subsequent 2.7.x releases and haven't really bothered to look into those yet. I'm going to attempt a 3.x build today and I'll give an update on that one way or another after we can get it in production for a week.

As noted, we are (still) running this as a systemd service, and as of 2.7.0, it is possible for the OOM killer to kill the main valhalla process without systemd detecting that the service needs restarting, so it's in sort of zombie mode.

**Comment by ianthetechie** [comment]
Unable to proceed with a full test of the 3.0.1 branch unfortunately due to issue #1698.

**Comment by ianthetechie** [comment]
Hey guys, sorry I forgot to come back and update this ticket. We're running 3.0.1 (with the patch in the PR I sent a few weeks ago) in production and we do still occasionally experience OOM kill issues in which the service is still technically running but won't service requests.

If there's any troubleshooting I could do to help out, let me know. It doesn't happen super often so it's not like a red alert critical issue, but at the same time it's enough of a problem that I'd say a load balancing proxy with fail over + a reasonably alert sysadmin is a requirement for any moderately serious setup ;)

**Comment by kevinkreiser** [comment]
@ianthetechie there has been work on `prime_server` to mitigate the issue where the server becomes unresponsive (though unrelated to any OOM kill scenarios). please have a look at or try out: https://github.com/kevinkreiser/prime_server/pull/75

we should be merging this some time soon

**Comment by ianthetechie** [comment]
Thanks for the update! I might give that a run over the coming week and see how it handles our loads.

**Comment by erdmanncross** [comment]
Hello, how are you guys
Does anyone have a solution for this?
I have a server that keeps locking up constantly.
it is an instance 8 vcpu 32Gb of ram.
I realized that the memory is not being cleaned, so as I am going to send the routes, the memory usage only increases to a level that locks the instance.
I'm using / optimized_route.

**Comment by brad-4k** [comment]
Hello, thank you all for the hard work.  I too am running into an issue were memory is just climbing and not being freed.

Running latest (v1.4, a few months old)
vCPU 8  16GB mem.
Running 500 routes/min.

<img width="1492" alt="Screen Shot 2022-09-16 at 10 08 38 AM" src="https://user-images.githubusercontent.com/78495562/190692412-63f05be6-5189-445f-a40a-51f2640f6ea5.png">

Any ideas why memory doesn't appear to be freed?

**Comment by nilsnolde** [comment]
Which setup are you using (`valhalla_service`, docker..)? If you're still using our gis-ops image, there are [a few open issues](https://github.com/gis-ops/docker-valhalla/issues) regarding memory not being freed. No one really solved that so far (and we're not using docker for prod setups). I had similar issues with other docker containers (Postgres to be exact) in the past.

**Comment by ianthetechie** [comment]
We consider these issues to be essentially solved with our latest iteration. Previously we found it would behave a lot better (not unbounded growth) if we explicitly set Mjonlir max cache size (we used 2GB on some similarly beefy machines) and enabled both LRU mem cache and hard cache control (the latter being important). Our latest iteration seems to essentially solve the issue by using tarballs rather than a directory of routing tiles. This surprised us a bit but the TL;DR (Kevin or Nils can go into more details) is that a lot more RAM can be shared across threads with the tarball extracts. This also gave a modest performance increase.

We recently switched to running containerized via podman (a custom image, but basically the latest code we feel is pretty stable + necessary between releases), but that generally shouldn't have any affect on RAM consumption.

**Comment by brad-4k** [comment]
Ian, thank you for the information.

How recent of a version should I look at that have the memory issues plugged?

Is max cache set in valhalla.json?

**Comment by kevinkreiser** [comment]
Just to be clear it's not too likely that there was a memory leak (though technically still possible). I'll prepare a larger write up of how the library manages access to the graph data which will hopefully be a document we can point to in the future when such questions come up. TLDR; the system tries to use as much memory as you let it because this is a great place to cache the graph. The closer the graph is to the CPU (and ram is closer than disk) the faster the algorithms can run (less CPU stalling from disk latency). Unless you are getting OOM-killed then everything is working as normal, and if you are getting OOM-killed then you probably need to properly configure either your container or valhalla.json settings. Again, I'll write more later but the above should serve as a quick synopsis.

**Comment by ianthetechie** [comment]
Sorry for the late reply @brad-4k, but it was fixed some considerable time ago. I would highly recommend simply trying the tuning above and just running from a tarball rather than files (esp. important if you are running with high concurrency). Additionally, we haven't experienced the original issue in several years at this point. I'm going to close this issue since I opened it ;)

**Comment by brad-4k** [comment]
@ianthetechie thank you and I apologize for not replying to this thread.  After a few weeks of running everything appears to be stable.  I should have jumped back on here to mention that.
Thank you again for your response and considerate help.

**Comment by nilsnolde** [comment]
@brad-4k can you quickly elaborate which setup you were having? And if it's our gis-ops image, whether you did smth in particular for it to be stable?
