### ISSUE TITLE
Offline (and online) routing for mobile devices assistance

### ISSUE THREAD

**Issue by carlos-mg89** [valhalla/valhalla#1530]
I've finally built from source the Valhalla routing engine in my desktop computer. I have generated graphs for a few countries and for the latest Europe PBF extract, to do some testing. And now I have the following doubts that I would need to answer in order to proceed with my project requirements:

- **How do I know which graphs belong to a certain country?** Lets imagine, I have a .POLY file (or a bounding box), and I generate a PBF for the country, extracted from the planet PBF. I'd like to generate all the graphs using the planet PBF, and after that, I'd pack the MBTiles of a country and the routing graphs of that country (so both displaying the map and routing are available offline). But I'd like to allow a routing service between countries as well. How can I discern which graphs are related to a bounding box and/or a POLY file?
- I'm working on a hiking project for mobile devices (at the moment I'm under heavy development of the Android version), and I can see from this doc ( https://github.com/valhalla/valhalla/blob/2.6/docs/api/turn-by-turn/api-reference.md ) that pretty much all that I need is allowed to be done. Like setting a level of allowed difficulty based on the OSM `max_hiking_difficulty`. Perhaps there could be other parameters that would be of use, but it seems this is the most interesting at the moment. **Any other parameters that you think are useful for hiking?**
- Related to the Android app, I believe it's possible to add the Valhalla routing engine, into an Android app, since C++ code is supported through the NDK. In this issue https://github.com/valhalla/valhalla/issues/1514 I've read that the Mapbox staff is working to release an offline sdk for maps and navigation. I understand it will be compatible with iOS and Android. **Do you know if it'll be Open Source, or would it require a Mapbox API key for it to work? Is the beta access a real possibility for anyone who contacts the staff of Mapbox? Otherwise, any information on how to directly include the Valhalla code on an Android project would be very appreciated.**

Thanks in advance, and thanks for developing such a splendid open source project. I'm surprised of the high quality of it.

**Comment by kevinkreiser** [comment]
1. you can read about how our tiles are laid out geographically by looking at this: https://github.com/valhalla/valhalla-docs/blob/master/tiles.md and by looking around in `baldr` for the relevant code. then you do a little bit of maths to compute what tiles are where. we have lots of this code within `baldr` and `midgard`
2. https://github.com/valhalla/valhalla/blob/2.6/docs/api/turn-by-turn/api-reference.md#pedestrian-costing-options has all the pedestrian options that are documented now. in the future we will probably add `use_hills` for example like bikes have.
3. yep its possible exactly as you say, you'll need to build valhalla with the ndk for your targetted architectures. if you're interested in Mapbox's offline routing beta send me an email and I'll get it to the right people. The address is approximately: `kevin DOT kreiser AT mapbox.com`

**Comment by carlos-mg89** [comment]
1. It looks exactly to what I was looking for. As a suggestion, it would be very nice to add a different method than `tiles_for_bounding_box` so it's possible to calculate the tiles related to a POLY file. I'll study the code and see if I could manage to create that method. It'll cut the total size for a country/region, and I'm interested in cutting to the minimum the routing file size.
2. Yes, that's what I checked before contacting you and it seems it is all I need for now. Thanks!
3. Just sent you an email from my personal account.

Thank you for all the assistance. Should we close the issue, or perhaps leave it open for my suggestion of creating a method to calculate the required tiles based on a POLY file (or other kind of files, like GeoJson)?

**Comment by kevinkreiser** [comment]
If you would like to contribute a method to compute tiles within a polygonal region that would be fantastic. Please open a PR and I'll be glad to review it! If you'd just like to suggest that as an idea for a feature please open a separate issue with that specific intent.

Thanks!
