### ISSUE TITLE
A 0 indicates an invalid timezone not -1.

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#1540]
When we created the date_time library, a timezone index of 0 indicates an invalid timezone or a timezone was not found for that node.  Throughout some new time dependent logic, we return a value of -1 for invalid timezones.  Even though sending a value of -1 to the [timezone from_index function is fine](https://github.com/valhalla/valhalla/blob/master/src/baldr/datetime.cc#L42), we need to be consistent about what indicates an invalid timezone.   

We need to update these functions to return 0 instead of -1 for invalid timezones.  The functions should return uint32_t.  
- [ ] [timedep_forward](https://github.com/valhalla/valhalla/blob/master/src/thor/timedep_forward.cc#L36-L46) 
- [ ] [timedep_reverse](https://github.com/valhalla/valhalla/blob/master/src/thor/timedep_reverse.cc#L34-L45)
- [ ] [isochrone](https://github.com/valhalla/valhalla/blob/ad153e26a08ebfd27fa20aac0d7c7acf10bebde4/src/thor/isochrone.cc#L38-L45)   This should be done after merging this [PR](https://github.com/valhalla/valhalla/pull/1528)
- [ ] Double check the code for other timezone inconsistencies.

**Comment by danpat** [comment]
@gknisely Is it worth considering using `std::optional` or `boost::optional` (header only) instead here?  It has clearer semantics that magic "0 is invalid".

**Comment by dnesbitt61** [comment]
This is an index that comes from the GraphTile where perhaps 7 bits are used. I think using optional doesn't fit here - the tile has to store a value in those bits.
