### ISSUE TITLE
Remove transition edges from priority queue in Multimodal methods

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1560]
All other path algorithms (and isochrone methods) have removed code that adds transition edges to the priority queue/adjacency list. This has been done by adding an ExpandForward (or ExpandReverse) method that is called from GetBestPath to expand from a node. Any transition edges encountered are immediately followed and expanded from the end node's hierarchy level.

These changes are required prior to any refactoring to possibly remove transition edges and provide alternative means of transitioning between hierarchy levels at a node. This is desirable since DirectedEdge is a large data structure - and the only information needed for transition edges is the end node of the transition.

**Comment by gknisely** [comment]
- [ ] Discuss current and new logic with @dnesbitt61 
- [ ] Review Multimodal isochrones now use an ExpandForward method [PR](https://github.com/valhalla/valhalla/pull/1572)
- [ ] . . .
