### ISSUE TITLE
Incorrect response returned from this routing request

### ISSUE THREAD

**Issue by oderby** [valhalla/valhalla#1575]
Sending the following api request produces a "success" response, but inspecting the results shows the result is both wrong and invalid.

Request: 
```text
https://api.mapbox.com/valhalla/v1/route?access_token=<token>&json=%7B%22locations%22%3A%5B%7B%22lat%22%3A49.61001%2C%22lon%22%3A6.16752%2C%22type%22%3A%22break%22%7D%2C%7B%22lat%22%3A49.61086%2C%22lon%22%3A6.16943%2C%22type%22%3A%22break%22%2C%22rank_candidates%22%3Afalse%2C%22radius%22%3A13.118258269039911%7D%5D%2C%22directions_options%22%3A%7B%22narrative%22%3Afalse%7D%2C%22costing%22%3A%22bus%22%2C%22output%22%3A%22json%22%7D
```

Response:
```json
{"trip":{"language":"en-US","summary":{"max_lon":6.167518,"max_lat":49.610012,"time":0,"length":0.001,"min_lat":49.610012,"min_lon":6.167517},"locations":[{"original_index":0,"lon":6.167520,"lat":49.610008,"type":"break"},{"original_index":1,"lon":6.169430,"lat":49.610859,"type":"break"}],"units":"kilometers","legs":[{"shape":"wp}r}Ay|lwJ??","summary":{"max_lon":6.167518,"max_lat":49.610012,"time":0,"length":0.001,"min_lat":49.610012,"min_lon":6.167517}}],"status_message":"Found route between points","status":0}}
```

However, the haversine distance between the two requested locations is ~0.167, and so right off we know the result is suspicious (reports length of 0.001). Inspecting the encoded polyline, we see that indeed it's not reporting the expected polyline:
![image](https://user-images.githubusercontent.com/1351158/46714135-d9c56180-cc0e-11e8-9df6-79c57b9c45c4.png)
[source](https://valhalla.github.io/demos/polyline/?unescape=false&polyline6=true#wp%7Dr%7DAy%7ClwJ%3F%3F%0A)

For reference, here's what graphhopper returns for the same 2 points and is the route we'd expect to see:
![image](https://user-images.githubusercontent.com/1351158/46714159-f6fa3000-cc0e-11e8-9092-c4bfc5bf0c65.png) [source](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.61001%2C6.16752%3B49.61086%2C6.16943#map=18/49.61023/6.16861)

OSM Way involved in this request: https://www.openstreetmap.org/edit?way=9207507#map=18/49.61017/6.16833

**Comment by dnesbitt61** [comment]
Thanks for reporting this issue. Walking and cycling routes seem fine - any driving route (auto, bus, etc.) is not. We will investigate shortly.
