### ISSUE TITLE
Edge lookup by id

### ISSUE THREAD

**Issue by YousefED** [valhalla/valhalla#1577]
Is it possible to get more information about the edges returned from trace_attributes?

I'd like to learn more about how edges correlate to OSM ways, and visualise these. OSM ways are easy to look up with a tool like https://www.openstreetmap.org/way/628517871. Can I get similar data for edges?

I noticed the Locate API returns more information (including shape polyline) of edges near a location, but there's no way to query these by id, or include the polyline in the trace_attributes response?

**Comment by YousefED** [comment]
Nevermind, just noticed `begin_shape_index`

**Comment by divya1c** [comment]
is the shape in trace_attributes response not the valhalla edge shape?

**Comment by kevinkreiser** [comment]
@divya1c it's the whole shape of the match and the edges index into it
