### ISSUE TITLE
V3Tiles - Investigate tile size changes 

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1595]
Valhalla currently uses 0.25 (local roads and transit), 1.0 (arterial), and 4.0 degree unprojected lat,lon tiles. 

Analysis of tile size and performance using different tiles sizes should be performed to find a good mix of individual tile size balanced against the total number of tiles. In particular, it may be worth trying a tile size mix of (0.5, 1.0, 2.0) which means that each tile is 1/4 the size (in degrees) of the tile at the next lower level. There will be more highway tiles (with smaller area) and less local tiles (bigger area). Other variants may be worth testing.

At one point, Valhalla had these tile sizes (and even the hierarchy levels) included in the configuration settings. This allowed more flexible tile distributions. To revert back to a totally flexible strategy is beyond this issue but if that is recommended then additional issues to allow that can be generated.

**Comment by drewda** [comment]
Note that transit data has a different distribution than OSM/road data. Many tiles have no coverage. However, a single 0.25 tile can store a significant amount of route and schedule data in places like SF/Oakland and NYC.

**Comment by dnesbitt61** [comment]
I suspect we will keep the 0.25 degree tile size for local tiles and transit. Moving highway level tiles to 2 degrees seems more likely.

**Comment by dnesbitt61** [comment]
Keeping tile sizes the same for V3. Looking at largest tiles in NA they are roughly equa (2-3MB) across the hierarchy levels.
