### ISSUE TITLE
Missing Protobof and Boost as dependency for some modules

### ISSUE THREAD

**Issue by mloskot** [valhalla/valhalla#1604]
CMake configuration seems to generate incomplete target dependencies, so some modules are missing locations for Protobuf and Boost headers, etc.

This issue leaks in environment where Protobuf and Boost are not deployed/not findable in standard locations like `/usr` or `/usr/local`. Namely, Windows, but not only.

**Comment by dnesbitt61** [comment]
@mloskot @kevinkreiser - did recent work make this issue obsolete?

**Comment by mloskot** [comment]
@dnesbitt61 Yes, it is obsolete now.
I should have put `Fixes #1604` in commit of #1605.
Thanks for reminding this.
