### ISSUE TITLE
Bay Area, CA Multimodal Isochrone for time=60min does not contain Isochrone for time=30min

### ISSUE THREAD

**Issue by val-gh** [valhalla/valhalla#1607]
Hello,

I'm seeing a discrepancy in the multimodal isochrones generated for the same location but with different travel times.

For a multimodal isochrone with location in San Francisco, CA, USA:
30min travel time covers only San Francisco city.
60min travel time covers the East Bay (Oakland, Berkeley) but does not include San Francisco at all.

The longer travel time isochrone should include the area covered by the shorted travel time isochrone. 
Valhalla service built from https://github.com/valhalla/valhalla/commit/4b8ef9e90828b45fe104071800137cb2a11313cd. 
Config used is the default generated by `valhalla_build_config`.

----

Isochrone request for `time=30`:
`http://localhost:8002/isochrone?json={"locations":[{"lat":37.792831,"lon":-122.396879}],"costing":"multimodal","contours":[{"time":30}],"date_time":{"type":1,"value":"2018-09-20T08:00"}}`

Isochrone request for `time=60`:
`http://localhost:8002/isochrone?json={"locations":[{"lat":37.792831,"lon":-122.396879}],"costing":"multimodal","contours":[{"time":30}],"date_time":{"type":1,"value":"2018-09-20T08:00"}}`

[30mins.txt](https://github.com/valhalla/valhalla/files/2531181/30mins.txt)
![30mins](https://user-images.githubusercontent.com/43388729/47743267-dfc1c780-dc3b-11e8-9b36-72714598ac6e.png)

[60mins.txt](https://github.com/valhalla/valhalla/files/2531182/60mins.txt)
![60mins](https://user-images.githubusercontent.com/43388729/47743271-e51f1200-dc3b-11e8-9f19-f83bef776644.png)

**Comment by kevinkreiser** [comment]
@val-gh If you run a `depart_at` 8:00 route instead of an isochrone from oakland to san fran, what does the arrival time say? Is it before 9:00? We need to look at the schedule information to be sure that transit exists for the time of day in quesiton and that its properly included in the data that you're using.

**Comment by val-gh** [comment]
Hi @kevinkreiser, thanks for taking a look.

Just to clarify, the 2 isochrone requests in the original item have the same origin location (San Francisco) and the same `depart_at` time. 
The only difference is in the travel time.
I'd expect the isochrone for the shorter travel time to be contained within the isochrone for the longer travel time.
But the isochrone for the 30min travel time is completely disjoint from the 60min travel time.

----

I ran the route request from San Francisco (origin point is the Embarcadero BART station) to Oakland (destination point is the West Oakland BART Station) with 8:00am departure time. 
The arrival time is 08:12am which is accurate since there's only 1 stop.
```
http://localhost:8002/route?json={"locations":[{"lat":37.792831,"lon":-122.396879},{"lat":37.804918384,"lon":-122.29518055}],"costing":"multimodal","directions_options":{"units":"miles"},"date_time":{"type":1,"value":"2018-09-20T08:00"},"costing_options":{"transit":{"use_bus":1,"use_rail":1}}}
```
```
"locations": [{
	"original_index": 0,
	"date_time": "2018-09-20T08:00-03:00",
	"lon": -122.396881,
	"lat": 37.792831,
	"type": "break"
}, {
	"original_index": 1,
	"date_time": "2018-09-20T08:12-03:00",
	"lon": -122.295181,
	"lat": 37.80492,
	"type": "break"
}]
}
```

**Comment by gknisely** [comment]
@val-gh This looks like this may be timezone issue.  Notice that your offset is -03:00 and not -07:00 as it should be.  We have recently update the timezone db and I think you maybe using an old one, in which case the indexes will be off.  Can you try to rebuild you timezone db by running [valhalla_build_timezones](https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_timezones)?  Next, reconvert your data(route and transit data) with that timezone db.  Finally, rerun you test above.  Let us know if this fixes the issue.

**Comment by dnesbitt61** [comment]
this could also be due to denoise operations. See the isochrone doc for and try the denoise parameter. Here is what that says:
A floating point value from 0 to 1 (default of 1) which can be used to remove smaller contours. **A value of 1 will only return the largest contour for a given time value.** A value of 0.5 drops any contours that are less than half the area of the largest contour in the set of contours for that same time value.

**Comment by val-gh** [comment]
Thank you all for the quick responses! 
Setting the `denoise` to 0 returns the contours for both San Francisco and Oakland.
I didn't notice the timezone offset issue - I'll rebuild my data as suggested.
