### ISSUE TITLE
Conversion of float to odin::DirectionsOptions::DateTimeType enum not allowed

### ISSUE THREAD

**Issue by mloskot** [valhalla/valhalla#1626]
The issue discussed in #1169 seems back, at least as reported by MSVC compiler from the very latest VS2017, in the default `/std:c++14` 

```
d:\valhalla\src\worker.cc(593): error C2440: 'static_cast': cannot convert from 'T' to 'valhalla::odin::DirectionsOptions::DateTimeType' 
                   with
                   [
                       T=float
                   ]
           d:\valhalla\src\worker.cc(593): note: Conversions between enumeration and floating point values are no longer allowed
```

If that still has to be float for `hysterical raisins` as per  https://github.com/valhalla/valhalla/pull/1169#issuecomment-376842404, perhaps dumb intermediate `static_cast<int>(*date_time_type)` would do?

```
 if (date_time_type && odin::DirectionsOptions::DateTimeType_IsValid(*date_time_type)) {
    auto const v = static_cast<int>(*date_time_type);
    options.set_date_time_type(static_cast<odin::DirectionsOptions::DateTimeType>(v));
  }
```

**Comment by kevinkreiser** [comment]
imho, `static_cast` is perfectly acceptable here. i presume pre c++14 was doing implicit conversion and they've decided to change that so you'll be more alerted to programming bugs. @mloskot would you mind PRing this?

**Comment by mloskot** [comment]
Sure, I'll prepare PR.

**Comment by mloskot** [comment]
Done
