### ISSUE TITLE
V3Tiles - Allow flexible tile variants

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1639]
Valhalla currently has configurtion parameters for whether hierarchy levels and shortcuts are constructed (useful for lowering the data size for bicycle or pedestrian only routing applications).

Further savings can be obtained by filtering or removing edges that are not needed. This issue proposes a GraphFilter stage of the tile building process that can remove edges (and nodes) based on bicycle, driving, or pedestrian access. It may be more desirable to do this up from when parsing of the PBF data occurs - if we could skip ways based on access. This is problematic at this time due to country based access logic that defers determination of access until the GraphEnhancer stage where admin lookups occur (is more efficient at this stage due to tiling).

A GraphFilter would optionally iterate through all of the Valhalla tiles that pass the GraphEnhancer stage and would remove directed edges whose access doesn't match configuration options that state which access modes to include. Nodes that have all edges filtered would also be removed. Removing nodes requires a second pass to update all endnode IDs of directed edges to the new node IDs.

Running this process along with HierarchyBuilder and ShortcutBuilder options should allow efficient creation of tile variants to support different use cases. The diagram below shows 3 cases: standard case where Valhalla tiles support all modes and options, a driving only case where pedestrian and bicycle only edges are removed, and a bicycle only case where all driving only or pedestrian only edges are removed.

![tilevariants](https://user-images.githubusercontent.com/1838768/48283824-a81d0180-e42b-11e8-9273-e0391ecc1557.png)

**Comment by emiltin** [comment]
If valhalla allows pushing bikes when preferable (I hope it does) then you can't simply remove all pedestrian edges for bicycler routing. But edges that are inaccessible can of be removed.

**Comment by dnesbitt61** [comment]
Valhalla does not allow pushing bicycles at this time. Configuration options control the filtering, so one could set it to allow bicycle and pedestrian, but not roads/paths that allow neither if this option is ever presented.
