### ISSUE TITLE
is edge id unique in map matching

### ISSUE THREAD

**Issue by xdmiodz** [valhalla/valhalla#1652]
I have noticed that in map matching edges with same edge id can have different lengths. So the question is edge id is unique across whole graph?

**Comment by kevinkreiser** [comment]
Which edge in the map match is it. Is it the first or last edge? It may be the case (i have to check the code) that since your first and last locations are partially along the edge in question that it gives back a partial length for those edges. again id have to check the code to be sure.

**Comment by xdmiodz** [comment]
in my case it was the first one

**Comment by xdmiodz** [comment]
what can be used to identify edge uniquely then?

**Comment by xdmiodz** [comment]
and what's the shape of the edge (defined by `{begin,end}_shape_index`)  then? is it a complete shape of the edge or only the touched part of it?

**Comment by xdmiodz** [comment]
ok, with some experiments I found out it myself - edge length includes only the touched part, so the length in the response may vary
