### ISSUE TITLE
V3Tiles - Reserve a bit in NameInfo for "tagged" name flag

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1654]
This bit will indicate the text in the textlist uses the first char (byte) as an identifier of the type of name/text. This will allow future growth for adding features like different language names, or other special interpretations of the text. 

The implementation of tagged text will not be added immediately. This just reserves a bit for future growth so that when an implementation is added the bit is reserved and can be used.

**Comment by dnesbitt61** [comment]
One way to separate this is to create a new tagged_text_list that for text that is flagged as tagged. This seems safe - old code will never access the new text strings. The presence of a tag at the start of a text string will make it non-unique so it is likely that no space savings would occur if the text strings were in the same unique text list.

**Comment by kevinkreiser** [comment]
can't we just have old code skip any that are flagged as tagged not not need a new text_list at all? like the old code just ignores anything that has the tagged bit set. then when we write new code we just make sure to keep all the previously untagged stuff (names et al) with their tagged bit set to `0` and only new additional stuff will have that set to `1` and have the first byte of the string denote what it is etc.

**Comment by dnesbitt61** [comment]
Sounds good. Adding this to EdgeInfo::GetNames and GetNamesAndTypes.
