### ISSUE TITLE
Missing alias_tz.csv

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla#1698]
When running `valhalla_build_timezones` on any release branch newer than 2.7.0, I end up with the following output. Am I missing a step somewhere? I checked the Mjonlir docs (https://github.com/valhalla/valhalla/blob/master/docs/mjolnir/getting_started_guide.md) and am not seeing anything new.

STDOUT
```
downloading timezone polygon file.
Archive:  ./timezones-with-oceans.shapefile.zip
  inflating: dist/combined-shapefile-with-oceans.dbf  
  inflating: dist/combined-shapefile-with-oceans.prj  
  inflating: dist/combined-shapefile-with-oceans.shp  
  inflating: dist/combined-shapefile-with-oceans.shx  
1
```

STDERR
```
SQLite version: 3.22.0
SpatiaLite version: 4.3.0a
Inserted 439 rows into 'tz_world' from './dist/combined-shapefile-with-oceans.shp'
Error: cannot open "alias_tz.csv"
alias table import failed
```

**Comment by dnesbitt61** [comment]
alias_tz.csv is a file within the scripts directory. Are you running valhalla_build_timezones from within that directory?

**Comment by ianthetechie** [comment]
Thanks for the quick response. No, I was not running it from within that directory. I must have missed that detail, as I see it is in the docs after a second look. I did not expect this since I've been running it from elsewhere on the system successfully since before the 2.7.1 release.
