### ISSUE TITLE
Required target protobuf::libprotobuf-lite or protobuf::libprotobuf is not defined

### ISSUE THREAD

**Issue by beneton2003** [valhalla/valhalla#1700]
Hello, i have a troubles while compiling vallhala from sources on Debian 9.7
Here is a console log:

 cmake .. -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is GNU 6.3.0
-- The C compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Performing Test HAS_COLOR_FLAG
-- Performing Test HAS_COLOR_FLAG - Success
-- Configuring in release mode
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.52.1")
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-pthread (found version "3.6.1")
CMake Error at CMakeLists.txt:163 (message):
  Required target protobuf::libprotobuf-lite or protobuf::libprotobuf is not
  defined

-- Configuring incomplete, errors occurred!
See also "/home/valhalla/build/CMakeFiles/CMakeOutput.log".
See also "/home/valhalla/build/CMakeFiles/CMakeError.log".

This is a CMakeError.log

Compiler tell me that libprotobuf-lite or libprotobuf is not installed, but i was install it
libprotobuf-dev:amd64                3.0.0-9 protocol buffers C++ library (development files)
libprotobuf-lite10:amd64             3.0.0-9 protocol buffers C++ library (lite version)
libprotobuf10:amd64                  3.0.0-9 protocol buffers C++ library
libprotoc10:amd64                    3.0.0-9 protocol buffers compiler library

How can i figure it out? can anyone help me to compile?

**Comment by beneton2003** [comment]
root@Debian-95-stretch-64-minimal /home/valhalla/build # protoc --version
libprotoc 3.6.1

**Comment by beneton2003** [comment]
I was spent about 4 days trying to compile this solution and still no result,.
But, i was already figure it out in past, but i am not remember how

**Comment by beneton2003** [comment]
I was try to input dpkg --listfiles libprotobuf-dev, and the result was
root@Debian-95-stretch-64-minimal ~ # dpkg --listfiles libprotobuf-dev

/.
/usr
/usr/include
/usr/include/google
/usr/include/google/protobuf
/usr/include/google/protobuf/any.h
/usr/include/google/protobuf/any.pb.h
/usr/include/google/protobuf/any.proto
/usr/include/google/protobuf/api.pb.h
/usr/include/google/protobuf/api.proto
/usr/include/google/protobuf/arena.h
/usr/include/google/protobuf/arenastring.h
/usr/include/google/protobuf/descriptor.h
/usr/include/google/protobuf/descriptor.pb.h
/usr/include/google/protobuf/descriptor.proto
/usr/include/google/protobuf/descriptor_database.h
/usr/include/google/protobuf/duration.pb.h
/usr/include/google/protobuf/duration.proto
/usr/include/google/protobuf/dynamic_message.h
/usr/include/google/protobuf/empty.pb.h
/usr/include/google/protobuf/empty.proto
/usr/include/google/protobuf/extension_set.h
/usr/include/google/protobuf/field_mask.pb.h
/usr/include/google/protobuf/field_mask.proto
/usr/include/google/protobuf/generated_enum_reflection.h
/usr/include/google/protobuf/generated_enum_util.h
/usr/include/google/protobuf/generated_message_reflection.h
/usr/include/google/protobuf/generated_message_util.h
/usr/include/google/protobuf/io
/usr/include/google/protobuf/io/coded_stream.h
/usr/include/google/protobuf/io/gzip_stream.h
/usr/include/google/protobuf/io/printer.h
/usr/include/google/protobuf/io/strtod.h
/usr/include/google/protobuf/io/tokenizer.h
/usr/include/google/protobuf/io/zero_copy_stream.h
/usr/include/google/protobuf/io/zero_copy_stream_impl.h
/usr/include/google/protobuf/io/zero_copy_stream_impl_lite.h
/usr/include/google/protobuf/map.h
/usr/include/google/protobuf/map_entry.h
/usr/include/google/protobuf/map_entry_lite.h
/usr/include/google/protobuf/map_field.h
/usr/include/google/protobuf/map_field_inl.h
/usr/include/google/protobuf/map_field_lite.h
/usr/include/google/protobuf/map_type_handler.h
/usr/include/google/protobuf/message.h
/usr/include/google/protobuf/message_lite.h
/usr/include/google/protobuf/metadata.h
/usr/include/google/protobuf/reflection.h
/usr/include/google/protobuf/reflection_ops.h
/usr/include/google/protobuf/repeated_field.h
/usr/include/google/protobuf/service.h
/usr/include/google/protobuf/source_context.pb.h
/usr/include/google/protobuf/source_context.proto
/usr/include/google/protobuf/struct.pb.h
/usr/include/google/protobuf/struct.proto
/usr/include/google/protobuf/stubs
/usr/include/google/protobuf/stubs/atomic_sequence_num.h
/usr/include/google/protobuf/stubs/atomicops.h
/usr/include/google/protobuf/stubs/atomicops_internals_arm64_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_arm_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_arm_qnx.h
/usr/include/google/protobuf/stubs/atomicops_internals_atomicword_compat.h
/usr/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_macosx.h
/usr/include/google/protobuf/stubs/atomicops_internals_mips_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_pnacl.h
/usr/include/google/protobuf/stubs/atomicops_internals_power.h
/usr/include/google/protobuf/stubs/atomicops_internals_ppc_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_s390_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_solaris.h
/usr/include/google/protobuf/stubs/atomicops_internals_tsan.h
/usr/include/google/protobuf/stubs/atomicops_internals_x86_gcc.h
/usr/include/google/protobuf/stubs/atomicops_internals_x86_msvc.h
/usr/include/google/protobuf/stubs/bytestream.h
/usr/include/google/protobuf/stubs/callback.h
/usr/include/google/protobuf/stubs/casts.h
/usr/include/google/protobuf/stubs/common.h
/usr/include/google/protobuf/stubs/fastmem.h
/usr/include/google/protobuf/stubs/hash.h
/usr/include/google/protobuf/stubs/logging.h
/usr/include/google/protobuf/stubs/macros.h
/usr/include/google/protobuf/stubs/mutex.h
/usr/include/google/protobuf/stubs/once.h
/usr/include/google/protobuf/stubs/platform_macros.h
/usr/include/google/protobuf/stubs/port.h
/usr/include/google/protobuf/stubs/scoped_ptr.h
/usr/include/google/protobuf/stubs/shared_ptr.h
/usr/include/google/protobuf/stubs/singleton.h
/usr/include/google/protobuf/stubs/status.h
/usr/include/google/protobuf/stubs/stl_util.h
/usr/include/google/protobuf/stubs/stringpiece.h
/usr/include/google/protobuf/stubs/template_util.h
/usr/include/google/protobuf/stubs/type_traits.h
/usr/include/google/protobuf/text_format.h
/usr/include/google/protobuf/timestamp.pb.h
/usr/include/google/protobuf/timestamp.proto
/usr/include/google/protobuf/type.pb.h
/usr/include/google/protobuf/type.proto
/usr/include/google/protobuf/unknown_field_set.h
/usr/include/google/protobuf/util
/usr/include/google/protobuf/util/field_comparator.h
/usr/include/google/protobuf/util/field_mask_util.h
/usr/include/google/protobuf/util/json_util.h
/usr/include/google/protobuf/util/message_differencer.h
/usr/include/google/protobuf/util/time_util.h
/usr/include/google/protobuf/util/type_resolver.h
/usr/include/google/protobuf/util/type_resolver_util.h
/usr/include/google/protobuf/wire_format.h
/usr/include/google/protobuf/wire_format_lite.h
/usr/include/google/protobuf/wire_format_lite_inl.h
/usr/include/google/protobuf/wrappers.pb.h
/usr/include/google/protobuf/wrappers.proto
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.a
/usr/lib/x86_64-linux-gnu/libprotobuf.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/protobuf-lite.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/protobuf.pc
/usr/share
/usr/share/doc
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so
/usr/lib/x86_64-linux-gnu/libprotobuf.so
/usr/share/doc/libprotobuf-dev

I also try to get protoc -- version:
libprotoc 3.6.1

And i was try to find protoc packages  dpkg -l | grep protoc

libprotobuf-dev 3.0.0-9                        amd64        protocol buffers C++ library (development files)
libprotobuf-lite10 3.0.0-9                        amd64        protocol buffers C++ library (lite version)
libprotobuf10 3.0.0-9 

I was compile libprotoc 3.6.1 from source, but libprotobuf-dev 3.0.0 i was get from repositories, I don't know how to install libprotobuf-dev with the same version as libprotoc  3.6.1?
Maybe this is a reason?

**Comment by kevinkreiser** [comment]
Im not sure why that would be a problem but could you try uninstalling your source install of protoc and then apt installing the `protobuf-compiler` package (that one contains protoc).

**Comment by beneton2003** [comment]
The trouble was bcs i made some changes in CMakeLists.txt.
I was compile and install the next packages cmake 3.13, protoc 3.6.1, prime_server 0.6.3
After all this packages was successfuly compiled and installed the trouble was dissapear. Thanks to everybody!
