### ISSUE TITLE
Bounding box download of elevation data

### ISSUE THREAD

**Issue by carlos-mg89** [valhalla/valhalla#1701]
In the Elevation DOC file ( https://github.com/valhalla/valhalla/blob/master/docs/elevation.md ) I can see the `valhalla_build_elevation` line, that if downloads all the elevation data for the world.

However I'd like to download only the information for Europe (I don't have 1.6TB free and I don't need the info for other areas at this moment) but I'm not sure what is each of the parameters supposed to be.

What is each parameter? I know they should be minimum latitude, maximum latitude and minimum longitude, maximum longitude. But on which order are they supposed to be in the call to `valhalla_build_elevation`?

**Comment by dnesbitt61** [comment]
If you run ./valhalla_build_elevation without arguments you get a usage message:

Usage: ./valhalla_build_elevation min_x max_x min_y max_y [target_dir=elevation] [parallelism=4] [decompress=true]

the argument order is minimum longitude, maximum longitude, minimum latitude, maximum latitude

**Comment by carlos-mg89** [comment]
Thanks for the info! Worked like a charm!
