### ISSUE TITLE
valhalla_build_admins

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1708]
Getting an error in valhalla_build_admins with the latest planet:

2019/02/06 16:43:46.486289 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract.
2019/02/06 16:43:46.494641 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract.

@gknisely

**Comment by gknisely** [comment]
This is probably due to invalid polys.  I will look into it.

**Comment by ianthetechie** [comment]
I've noticed this as well for the last 2 weekly planet dumps. During relations parsing, I get the following output:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  unable to read blob from file
```

**Comment by GreGosPhaTos** [comment]
Hi @gknisely any update on this fix ?

**Comment by gknisely** [comment]
@GreGosPhaTos thanks for the bump on this.  I totally forgot about it.  I will try it tonight.

**Comment by GreGosPhaTos** [comment]
Thanks @gknisely !

**Comment by GreGosPhaTos** [comment]
@gknisely did you have any chance to look at it last night ? Thank you

**Comment by gknisely** [comment]
@GreGosPhaTos actually I just started it awhile ago.  I will let you know what I find out.

**Comment by gknisely** [comment]
The only error that I saw was the following:

2019/06/13 22:49:23.596129 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract.
2019/06/13 22:49:23.605383 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract.

@GreGosPhaTos have you tried it lately?

**Comment by GreGosPhaTos** [comment]
Yes I have the same one. And after having this errors my tiles don't seems correct ... 
Is this error ^ related to that ?

**Comment by gknisely** [comment]
This is probably due to a bad relation.  I will see if I can find it.

**Comment by gknisely** [comment]
There was a name change for the country polygons `The United States of America` and `The Netherlands` Real fix will be to use a like clause here; however, for now I am updating the names and adding more logging.
