### ISSUE TITLE
Missing highway cardinal direction

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1720]
## Issue
While testing, discovered a missing highway directional for`Loop 1` in Texas. This is a special case and we need to determine how to handle.
example request:
```
{"locations":[{"lat":30.395716,"lon":-97.732071,"street":"North MoPac Expressway"},{"lat":30.403431,"lon":-97.727058,"street":"Loop 1"}],"costing":"auto","directions_options":{"units":"miles"}}
```

## Need to review and fix highway cardinal directions outside the US

**Comment by dgearhart** [comment]
@gknisely Noting that the PATP is missing the cardinal direction as well.

**Comment by gknisely** [comment]
More directional issues:

https://www.openstreetmap.org/way/42502913
https://www.openstreetmap.org/way/8028082

express vs local issue
![image](https://user-images.githubusercontent.com/2676277/57931461-83945d00-7886-11e9-8189-baeaf5d21532.png)

**Comment by dgearhart** [comment]
Another issue for SR in Ohio:
https://www.openstreetmap.org/way/531487448
Route: {"locations":[{"lat":39.287937,"lon":-84.465652,"street":"East Kemper Road"},{"lat":39.282433,"lon":-84.467476,"street":"Princeton Pike"}],"costing":"auto","units":"miles"}

For maneuver 2, this route should have: Turn left onto Princeton Pike/SR 747 **South**

![image](https://user-images.githubusercontent.com/7515853/60275191-88a5ec80-98c7-11e9-84bb-01dde0475994.png)
