### ISSUE TITLE
OSRM Output 

### ISSUE THREAD

**Issue by mqln** [valhalla/valhalla#1723]
How do we request a route in OSRM Compatibility mode? I've been doc-scouring for a few days now, but can't find any information on how to actually request this format for a route. I've seen the the osrm route serializer is there in `Tyr`, but have also seen PRs out there for removing the OSRM compatibility. So I'm at a loss if this is even truly still a feature.

I've tried,
Directions options format: `..."directions_options":{"format":"osrm"}`
Directions options out format: `..."directions_options":{"out_format":"osrm"}`
Top level format `..."format":"osrm"`
Top level out format `..."out_format":"osrm"`

... and I've also tried replacing `osrm` with `toOsrm` as it's mentioned on the [docs page](https://github.com/valhalla/valhalla/blob/716fd6e99ab6f271b606c20ea64adcd856d83f8b/docs/route_overview.md)?

**Comment by kevinkreiser** [comment]
@dgearhart @dnesbitt61 correct me if I'm wrong but I think that both of your examples using `"format":"osrm"` should work, whether at the top level or within `directions_options`

can you provide us with a full request just in case that might give us an idea as to what is going wrong here?

**Comment by mqln** [comment]
Absolutely, thanks for the fast response time!

I'm testing on Switzerland (as per the docs), and I've got things up and running on a Ubuntu 16.04. Here's my curl

`curl http://localhost:8002/route --data '{"locations":[{"lat":46.9480,"lon":7.4474,"type":"break"},{"la
t":47.3769,"lon":8.5417,"type":"break"}],"costing":"auto","directions_options":{"format":"osrm"}}'`

I saw that `"directions_options":{"format":"gpx"}` returns me a whole bunch of GPX, so I was hoping that swapping out `osrm` would do the same, but the route returns with format as `osrm` is identical to the default output, and definately not OSRM compatible (no `maneuvers`, etc).

Cheers!

**Comment by dnesbitt61** [comment]
try using &format=osrm outside of the JSON.

This is a work in progress (which is why it is undocumented).

**Comment by dgearhart** [comment]
@mqln Could you please add `units` to `directions_options` - for example:
`curl http://localhost:8002/route --data '{"locations":[{"lat":46.9480,"lon":7.4474,"type":"break"},{"lat":47.3769,"lon":8.5417,"type":"break"}],"costing":"auto","directions_options":{"units":"kilometers","format":"osrm"}}'
`
`units` should not be required - I need to figure out what is wrong.
For now - it should work if you add the `units` param
Apologies

**Comment by mqln** [comment]
@dgearhart thanks, but it's still not formatted for OSRM with that sample request. There's no `step` objects, or anything matching [OSRM format](http://project-osrm.org/docs/v5.5.1/api/)

@dnesbitt61 I'm sorry, but `curl` isn't my forte. I've tried adding `&format=osrm` to my data-string like so,

``` 
curl http://localhost:8002/route --data '{"locations":[{"lat":46.9480,"lon":7.4474,"type":"
break"},{"lat":47.3769,"lon":8.5417,"type":"break"}],"costing":"auto","directions_options":{"units":"kilometers","format":"osrm"
}}&format=osrm'
```

But that's giving me a malformed error. Is there something I'm missing here?

**Comment by dgearhart** [comment]
@mqln  When I run the following:
```
curl http://localhost:8002/route --data '{"locations":[{"lat":46.9480,"lon":7.4474,"type":"break"},{"lat":47.3769,"lon":8.5417,"type":"break"}],"costing":"auto","directions_options":{"units":"kilometers","format":"osrm"}}' | jq . > out.json
```
i see OSRM format returned with an array of steps
![image](https://user-images.githubusercontent.com/7515853/53115373-0cb02800-3514-11e9-9377-0de14e47b891.png)

**Comment by mqln** [comment]
What in tarnation.

I don't get any steps when I run your command.

Here's an expert:

```
        "maneuvers": [
          {
            "travel_mode": "drive",
            "begin_shape_index": 0,
            "length": 0.253,
            "time": 70,
            "type": 1,
            "end_shape_index": 21,
            "instruction": "Drive west on Marktgasse.",
            "verbal_pre_transition_instruction": "Drive west on Marktgasse for 300 meters.",
            "travel_type": "car",
            "street_names": [
              "Marktgasse"
            ]
          },
```

I set up Valhalla with the directions on the Github page, via `ppa:valhalla-core/valhalla`.

I did this last week.

Is there a versioning difference here, or could I have set up Valhalla wrong?

**Comment by dgearhart** [comment]
@mqln the osrm format was not in ppa version - you could build from master
cc @kevinkreiser

**Comment by mqln** [comment]
@dgearhart oh ok, I'll give that a shot, thanks!

**Comment by mqln** [comment]
@dgearhart 

Working like a charm, just had to build from source.

Cheers!

**Comment by JFDionne** [comment]
Hi, any ways for having annotations of speed in the Osrm output from Valhalla?

**Comment by kevinkreiser** [comment]
@JFDionne not in the OSRM output but we do supply them in the trace_attributes output.

**Comment by JFDionne** [comment]
@kevinkreiser Thank for fast answer.
Any plan to add annotations on the Osrm output? I was using them and I just switch from Osrm to Valhalla (with Osrm output)

**Comment by kevinkreiser** [comment]
@JFDionne we dont have any plans to add that at the current time. we find the annotations (which are per shape point) to be too verbose to include for an entire route. this is why we designed trace_attributes so that you could, as you need it, get more detailed meta data on the fly. in addition to that, we dont and probably never will store the osm node ids so we cant even offer that annotation.
