### ISSUE TITLE
Prime Server & Source Ubuntu 16.04

### ISSUE THREAD

**Issue by mqln** [valhalla/valhalla#1724]
Heyo,

Since the PPA version of Valhalla doesn't contain it's most recent features (as per my last issues [outlined in this ticket](https://github.com/valhalla/valhalla/issues/1723)), I've been trying to get Valhalla to build from Master.

My error is 
```
valhalla_service: error while loading shared libraries: libprime_server.so: cannot open shared object file: No such file or dire
ctory
```

I tried to follow the Build From Source directions, but the prime server packages weren't able to be installed.

So I followed the tips given in [trying to install for Debian](https://github.com/valhalla/valhalla/issues/708), by excluding the `libprime-server0.6.3-dev ` &  `prime-server0.6.3-bin` from  the`apt-get install` line, and hoped that it would work successfully if I followed the [Prime Server install instructions](https://github.com/kevinkreiser/prime_server#build-and-install).

I guess I'm still missing a Prime Server dependency, right? But I'm at as loss on how to get it installed.

**Comment by mqln** [comment]
Yuk.

I forgot to `sudo add-apt-repository ppa:kevinkreiser/prime-server `

Excuse me...

**Comment by matkoniecz** [comment]
https://github.com/valhalla/valhalla/issues/3158#issuecomment-865659758 suggests `sudo add-apt-repository -y ppa:valhalla-core/valhalla`

**Comment by kevinkreiser** [comment]
@matkoniecz i mirror the packages in both ppas there is no difference between them its just for organizational purposes
