### ISSUE TITLE
TZ database is out of date

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla#1734]
I noticed that the TZ database is a little out of date. I'd love to help make the updates a little less manual, but want to get your feedback on the requirements + understand any potential issues first.

I'm assuming that the reason it's currently pegged to any specific version at all is due to non-canonical names in the shapefile? If so, the primary "problem" to solve would be getting an authoritative source for 1) checking that the TZ names are indeed valid, and 2) mapping from deprecated/alias ones to canonical ones?

I think both of these problems are solvable. Let me know if 1) this is the right track to proceed down, and 2) if you have any restrictions on the tooling you'd like to use to accomplish this (in particular, would Python 3.x be acceptable? I think that'd be easier than trying to work it out in bash).

**Comment by gknisely** [comment]
> I noticed that the TZ database is a little out of date. I'd love to help make the updates a little less manual, but want to get your feedback on the requirements + understand any potential issues first.

@ianthetechie I am not sure that I understand the above statement.  I assume you mean your TZ databases.  If you want to get updates, you should be able to run https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_timezones.  It looks like the last update was 2018d but they are at 2018i, which is not that out of date.  

We usually test the updates locally and then update the bash script.  We only typically do this once or twice a year.  Is there something in particular that you are seeing or worried about?

**Comment by ianthetechie** [comment]
Hey Greg,

I was referring to the database build script was pinned to an old version of the TZ shapefile. I didn't notice anything wrong/broken in particular; just that it wasn't up to date and it looked like a manual process. If you don't think this is an issue, then that's fine, but I happened to notice it and wondered if the update process could be automated so that `valhalla_build_timezones` would always try to build with the latest release if possible.

**Comment by gknisely** [comment]
Since, timezones don't change too much, we run it as a manual process so that we can test it against the planet.  I will probably do this in a few weeks, but feel free to use and test out the new one.  If you do, please let me know if you see any issues.  Thank you for you contributions to valhalla.  We really appreciate it.
