### ISSUE TITLE
Important time difference between valhalla::thor::TimeDistanceMatrix and valhalla::thor::BidirectionalAStar

### ISSUE THREAD

**Issue by xlqian** [valhalla/valhalla#1736]
Hi  Valhalla, 

Greetings from Navitia!

We have encountered some interesting problems when using TimeDistanceMatrix and BA* to calculate the time between two locations. The time obtained from TimeDistanceMatrix and BA* may be very different, ~200s for example, given that we use same configuration when projecting locations(ex: reachability=0, radius=0). 

We tried all combinations like CostMatrix and BA*,  TimeDistanceMatrix and BA*,  CostMatrix and A*,  TimeDistanceMatrix and A*, the differences change a lot depend on the locations and remain still important. 

Do you, if possible, have any ideas how can we do the tuning so that the differences may be minimized?

Thank you

**Comment by dnesbitt61** [comment]
Are these driving routes?

**Comment by xlqian** [comment]
thank you for you response. We have encountered same problems on pedestrian, bike and driving routes.

**Comment by xlqian** [comment]
the differences on pedestrian, bike are much smaller than driving routes.

**Comment by dnesbitt61** [comment]
Driving routes will definitely differ between TimeDistanceMatrix and CostMatrix. CostMatrix "should" closely match BD A* as it will use shortcuts and hierarchies (while TimeDistanceMatrix does not). One difference between CostMatrix and BD A* could be that BD A* will continue the search for a better path for some threshold after the first connection is made - CostMatrix likely uses a different thresholding.

**Comment by xlqian** [comment]
Hi, that was inspiring. We have rebuilt all tiles without hierarchy nor shortcut, the time are actually much closer. 

Thanks
