### ISSUE TITLE
Avoid Locations Issue

### ISSUE THREAD

**Issue by pblack1C** [valhalla/valhalla#1740]
I'm able to create a route that in theory shouldn't be routable: I have utilized Hurricane Sandy flood inundation data to create a set of avoid_locations. For the most part, it works very well. But I've noticed a few cases where Valhalla gives me a route when it probably shouldn't. See the attached map. The intersection of roads and the inundation polygons are marked with red dots. The green dots are my origin points. In this case, there is no viable route without going into an inundated area. So why does Valhalla give me a route (shown in purple)? Thanks so much in advance!
<img width="776" alt="Screen Shot 2019-03-11 at 3 31 11 PM" src="https://user-images.githubusercontent.com/47334022/54162449-bea38b80-4412-11e9-9c67-bb48398414bb.png">

**Comment by dnesbitt61** [comment]
If you send us the route request (with the avoid_locations or at least the one it does not seem to avoid) we could try to take a look. Curious if trying a pedestrian route also has this issue or if only driving routes do? If so that could point to an issue with finding shortcut edges near the avoid locations.

**Comment by pblack1C** [comment]
@dnesbitt61 thanks for the prompt response. We're sending some 13k avoid locations to Valhalla (which I suppose is good to know that it can handle that many), so I won't send you that entire request here. However, I narrowed down the number of avoid locations to see if I could get a reasonable facsimile of the route Valhalla generates for us. This should work below for debugging.

/route --data '{"locations":[{"lat":40.677848,"lon":-74.004868},{"lat":40.712058,"lon":-74.009138}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.677549391886, "lon":-74.0051473161497}, {"lat":40.6775432043007, "lon":-74.0051252864366}, {"lat":40.6775379575975, "lon":-74.0051066065543}, {"lat":40.677476336305, "lon":-74.0048872157396}, {"lat":40.6772386533995, "lon":-74.0040388854987}, {"lat":40.6782650866743, "lon":-74.0050657985247}, {"lat":40.678067922072, "lon":-74.0043409862655}, {"lat":40.67909222945, "lon":  -74.005452264709}, {"lat":40.6790795859625, "lon":-74.0054064073628}, {"lat":40.6797487793151, "lon":-74.0051725248413}, {"lat":40.6797220028928, "lon":-74.0050720477062}, {"lat":40.6797199644347, "lon":  -74.005064398498}, {"lat":40.6796937894038, "lon":-74.004966178053}, {"lat":40.6796870048308, "lon":-74.0049407192947}, {"lat":40.6796827991747, "lon":-74.0049249377886}, {"lat":40.6764195525831, "lon":-74.0031330215683}, {"lat":40.6790406719768, "lon":-74.0055806257554}, {"lat":40.6797070265738, "lon":-74.0052492764681}, {"lat":40.679759317776, "lon":-74.0052233313336}, {"lat":40.6781404764715, "lon":-74.0040854730066}, {"lat":40.6778970664954, "lon":-74.0037128167559}, {"lat":40.6765815760887, "lon":-74.0043051627406}, {"lat":40.6763120195323, "lon":-74.0033411876981}, {"lat":40.6762285081972, "lon":-74.0030316760888}, {"lat":40.6762269534976, "lon":-74.003025740228}, {"lat":40.6762243780995, "lon":-74.0030159073291}, {"lat":40.6805522846038, "lon":-74.0043489960281}, {"lat":40.680572872853, "lon":-74.0043099607525}, {"lat":40.6797747795744, "lon":-74.0052411873249}, {"lat":40.6807835746807, "lon":-74.0053740365362}, {"lat":40.6803476366791, "lon":  -74.004844871913}, {"lat":40.6805118705452, "lon":-74.0045614555585}, {"lat":40.6805438735131, "lon":-74.0044034758979}, {"lat":40.6805324949528, "lon":-74.0046469575035}, {"lat":40.6805216359946, "lon":-74.0046384144629}, {"lat":40.68050804854, "lon":-74.0046277248393}, {"lat":40.680527085854, "lon":-74.0044499300137}, {"lat":40.6805153241837, "lon":-74.0045070509249}, {"lat":40.6804772436266, "lon":-74.0046657029445}, {"lat":40.6804441660745, "lon":-74.0046945758264}, {"lat":40.6804094047992, "lon":-74.0047274297531}, {"lat":40.6803962959082, "lon":-74.0047682539936}, {"lat":40.6803726040147, "lon":-74.0048315147403}]}'

When I tested with pedestrian routing Valhalla took the walker towards the shore to board a ferry :-)

**Comment by dnesbitt61** [comment]
Can you tell me what road that this should avoid? Which lat,lon in the avoid list in particular do you think is not triggering the avoid on the road in question?

I disabled shortcuts when running this test and did not see any changes in the resulting route, so that does not seem to be the immediate issue.

**Comment by pblack1C** [comment]
David, I'd expect this route to fail given that all edges surrounding the origin point seem blocked by flooding inundation. That would be an acceptable result here. So I was perplexed to get a route back from Valhalla at all, and wondering why that may be the case.

**Comment by dnesbitt61** [comment]
That helps! There are no checks to exclude origin or destination edges that are marked as user avoid edges. Adding this code:

    // Disallow any user avoid edges
    GraphId edgeid(edge.graph_id());
    if (costing_->IsUserAvoidEdge(edgeid)) {
      continue;
    }

to bidirectional.cc within the SetOrigin method (line 568) and SetDestination method (line 641 after making the initial change) causes this route to fail immediately. I will think about adding this here and also to other SetOrigin and SetDestination methods, but feel free to make this change locally and see if it helps.

**Comment by pblack1C** [comment]
The other issue is that once the route enters the 'no go' area, it has to exit it to get to the destination. This forces another traversal of an avoid_location on my setup. It seems arbitrary that Valhalla would choose any given exit point. I suppose once we don't allow any traversal of an avoid_location on an origin or destination edge it becomes a moot point, but it definitely struck me as odd...
