### ISSUE TITLE
Implications to increasing max graph id 

### ISSUE THREAD

**Issue by aborovac** [valhalla/valhalla#1743]
Is there any implication to increasing `kMaxGraphId` in `valhalla/baldr/graphconstants.h` ?

I increased `kMaxGraphId` to max uint32_t - 1 and `edge_index_` in `valhalla/baldr/nodeinfo.h` to 32 bits.

Since the change I'm getting `Opposing directed edge not found at LL` when creating shortcuts in valhalla_build_tiles. What could be the causes of this error?

**Comment by dnesbitt61** [comment]
This is tricky. You need to make sure all structures that use these align properly. The unit tests should validate this somewhat as the NodeInfo structure size will likely change if you do not do this properly.

**Comment by aborovac** [comment]
Yes, I remembered to try unit tests. I see at least some changes required in GraphId. Thanks for the hint.
