### ISSUE TITLE
Determine moving direction on edge

### ISSUE THREAD

**Issue by uu3474** [valhalla/valhalla#1751]
Hi! Is exists any way to determine moving direction on osm way(forward or backward) using trace_attributes? I'm use Valhalla as library, not as service.

**Comment by dnesbitt61** [comment]
This is not possible. 
The forward flag indicates whether a DirectedEdge traverses the stored shape of the edge in a forward manner. However, this does not indicate that the DirectedEdge is in the direction of the OSM way. A new flag would have to be added to DirectedEdge to indicate this (and it could easily be populated in mjolnir/graphbuilder), but this is not currently part of the Valhalla data.

**Comment by uu3474** [comment]
thanks!
