### ISSUE TITLE
Meili API Example Not Working

### ISSUE THREAD

**Issue by JeroenSchmidt** [valhalla/valhalla#1759]
Hi there,
I'm trying to run the map matching example from the docker container [instructions](https://valhalla.readthedocs.io/en/latest/meili/run_service_in_docker/) and the API instructions from [here](https://valhalla.readthedocs.io/en/latest/meili/service_api/) with little success.

From curl and postman I try run:
`localhost:8002?search_radius=35&mode=auto`
```
{
  "coordinates": [
    [ 13.288925, 52.438512 ],
    [ 13.288938, 52.438938 ],
    [ 13.288904, 52.439169 ],
    [ 13.288821, 52.439398 ],
    [ 13.288824, 52.439491 ],
    [ 13.288824, 52.439563 ]
  ]
}
```

Output:
```
{
    "error_code": 106,
    "error": "Try any of:'/locate' '/route' '/height' '/sources_to_targets' '/optimized_route' '/isochrone' '/trace_route' '/trace_attributes' '/transit_available' ",
    "status_code": 404,
    "status": "Not Found"
}
```

Some additional notes:

1) The docs in the [docker instructions](https://valhalla.readthedocs.io/en/latest/meili/run_service_in_docker/) point towards an AWS bucket that is no longer accessible. I instead got the Berlin file from [geofabrik](https://download.geofabrik.de/europe/germany/berlin.html)

2) When running the valhalla_service I get the following warnings:
```
[WARN] Tile extract could not be loaded
[WARN] /data/valhalla/elevation/ currently has no elevation tiles
[WARN] /data/valhalla/elevation/ currently has no elevation tiles
```

**Comment by dgearhart** [comment]
@drewda it looks like this map matching example needs to be updated

**Comment by drewda** [comment]
@dgearhart thanks for the pointer. 

I actually wonder if we should just remove that entire doc page. It seems like a hold-over from when Meili ran as its own service. Now users can just follow the same code-compile/tile-build/service-run process at with any other endpoint.

Unless you or @kevinkreiser disagrees, I'll just go ahead and remove that page and make sure any unique instructions about map-matching get moved elsewhere.

**Comment by kevinkreiser** [comment]
@drewda please do remove it, it is as you say, a hold-over!

**Comment by dgearhart** [comment]
@drewda sounds good - thanks

**Comment by JeroenSchmidt** [comment]
thanks for the work guys
