### ISSUE TITLE
segfault on shortcut creation

### ISSUE THREAD

**Issue by slvlirnoff** [valhalla/valhalla#1771]
Hi all,

I'm testing the latest version (going from version 2.6-2.7 to 3.0.2) of valhalla and I experienced a segfault in what seems the 'shortcuts' creation of the tiles building step, after the enhance step.

I'm building tiles for the whole planet with a lots of transit data and I've seen several errors popping-up such as the following that I'm not familiar with.
```
Platform key not equal!
No valid level for this node!
Invalid end node - not found in old_to_new map
Transit Connection does not connect to valid node
```
I've already tried to use another planet osm file and a new transit extract with no success. I've restarted a build using the incremental tile building script to see where it crash exactly.

Any ideas what could be the cause?

**Comment by gknisely** [comment]
Hi @slvlirnoff 
Did you rebuild your transit tiles.  As noted in the changelog:  Tile data is incompatible with Valhalla 2.x builds, and code for 3.x is incompatible with data built for Valahalla 2.x versions.

This sounds like the issue.  I would build a small transit dataset and test it out first before running the planet.  

Let us know how it goes.

**Comment by gknisely** [comment]
https://github.com/valhalla/valhalla/blob/master/CHANGELOG.md#release-date-2018-11-21-valhalla-300

**Comment by slvlirnoff** [comment]
thanks @gknisely it indeed works after reinstalling tools and scripts properly and rebuilding the data.
I guess the first time I did make install there was still some reminding setup / binary of 2.x versions.
