### ISSUE TITLE
Distance Matrix Maximum locations

### ISSUE THREAD

**Issue by angiebs** [valhalla/valhalla#1773]

**Comment by angiebs** [comment]
Hi,

I am testing the DistanceMatrix Api and I realized that there is a limit of sources and targets, that means that the maximum locations for each one is 50.  Is It possible to increase this number?. or Why is the reason of this limitation?

**Comment by kevinkreiser** [comment]
hi @angiebs 50 is a configuration value with you can change. we have a tool to create a configuration file for a server to run with. the tool is called `valhalla_build_config`. if you pass it the argument `--help` you can see all the config items you can change including one called `--service-limits-auto-max-matrix-locations` there are others for different modes of travel like `--service-limits-bicycle-max-matrix-locations`. at any rate,  you can change this number in your config and restart your server to have the number take effect. the reason we have these limits is to prevent requests that could be too expensive.

**Comment by arashmidos** [comment]
Hi, we have around 1k locations per request, In our server with 12 Gb ram, it takes around 10 minutes to solve and response. How we can decrease the response time? Should we buy a new SSD hard or we can handle it non physically? 
I checked an article on GraphHopper which says they can calculate 10k locations in around 5 minutes!

**Comment by nilsnolde** [comment]
You can fix that by using another routing engine;) Valhalla is not speed optimized, rather it’s optimized for high runtime flexibility. With Graphhopper/OSRM/ORS you have huge graphs stored in RAM with **predefined** costings & weights. With Valhalla you can add any costing on the fly without having to rebuild the tiles. I’d recommend using OSRM or ORS, Graphhopper closed their Matrix source code.
