### ISSUE TITLE
location_distance logging

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#1776]
In src/loki/route_action.cc the check_distance method logs the distance between each location pair. With a large number of intermediate locations this creates a large number of log statements. 

// The following is inside the loop so it logs for each location pair.
valhalla::midgard::logging::Log("location_distance::" +
                                        std::to_string(path_distance * kKmPerMeter) + "km",
                                    " [ANALYTICS] ");

Perhaps this is really intended to be outside the loop so it logs the total path distance of the route?

**Comment by kevinkreiser** [comment]
feel free to change it! i personally feel like the analyltics logging could use an overhaul or at least an evaluation!
