### ISSUE TITLE
Tomtom Data

### ISSUE THREAD

**Issue by angiebs** [valhalla/valhalla#1784]
Hi,

Is There any possibility to work with Tomtom data and not only OSM data with Valhalla?.  
I mean, if can we prepare the data as is done with OSM and load this information into Valhalla.

Thank you for your answer

**Comment by TimMcCauley** [comment]
@angiebs this would require a tomtom2osm parser; feel free to pm me at tim@gis-ops.com - I might be able to point you in the right direction.

**Comment by drewda** [comment]
Yes, at @mapzen we supported some clients who converted their own TomTom data into OSM format, for subsequent ingest into the Valhalla routing graph build step. Currently at @interline-io we also support some clients who do the same process to power Valhalla using HERE data.

**Comment by angiebs** [comment]
Thank you for your quick response.

So, that means that directly with Tomtom data is not possible to work in
Valhalla, but we can parse or convert our data into OSM Format?.

We have done something similar but from OSM to Tomtom, for that we used a
tool that we have bought,  Do you have any tool to do this process?.


Thanks in advance

Regards
Angela

**Comment by kevinkreiser** [comment]
@angiebs we do not provide such a tool but you may be able to find something from @TimMcCauley who posted above! good luck!

**Comment by nilsnolde** [comment]
Yes, @gis-ops we developed a utility to use TomTom with FOSS routing engines. It's still in development phase, but we'll be done by the end of May, latest in June. Feel free to contact us.

**Comment by angiebs** [comment]
> FOSS routing engines

Thas sounds great. I am looking forward to test it. I will keep an eye on that :)

**Comment by angiebs** [comment]
> @angiebs this would require a tomtom2osm parser; feel free to pm me at [tim@gis-ops.com](mailto:tim@gis-ops.com) - I might be able to point you in the right direction.

Hi Tim,
I have sent you an Email.  I will really appreciate your help

**Comment by TimMcCauley** [comment]
@angiebs I did reply to your email, maybe it landed in your spam folder?
