### ISSUE TITLE
[3.0.3]  VALHALLA_VERSION_PATCH 2 / version number

### ISSUE THREAD

**Issue by ImreSamu** [valhalla/valhalla#1797]
Thank you for the new release!

as I see in the latest release (`3.0.3`)
the `VALHALLA_VERSION_PATCH` value is strange ..

https://github.com/valhalla/valhalla/blob/3.0.3/valhalla/valhalla.h.in

now:
```
#define VALHALLA_VERSION_MAJOR 3
#define VALHALLA_VERSION_MINOR 0
#define VALHALLA_VERSION_PATCH 2
```

and expecting

```
#define VALHALLA_VERSION_MAJOR 3
#define VALHALLA_VERSION_MINOR 0
#define VALHALLA_VERSION_PATCH 3
```

imho:   the `valhalla_build_tiles -v` version is incorrect now.

**Comment by dgearhart** [comment]
thank you - updated the version and re-tagged
https://github.com/valhalla/valhalla/blob/3.0.3/valhalla/valhalla.h.in
