### ISSUE TITLE
Documentation is missing for Polyline Decoding & Encoding 

### ISSUE THREAD

**Issue by JeroenSchmidt** [valhalla/valhalla#1804]
The documentation points towards a dead [link](https://valhalla.readthedocs.io/decoding.md) when it discusses how to encode and decode the polyline data used within the API.

Examples of Docs with the dead links:
* [Elevation API](https://valhalla.readthedocs.io/en/latest/api/elevation/api-reference/#use-an-encoded-polyline-for-input-locations)
* [Map-Matching](https://valhalla.readthedocs.io/en/latest/api/map-matching/api-reference/)

Is this the [correct document](https://github.com/valhalla/valhalla-docs/blob/master/decoding.md) I should be looking at for the decoding & encoding information?

**Comment by kevinkreiser** [comment]
ive fixed these
