### ISSUE TITLE
Distance Matrix Performance

### ISSUE THREAD

**Issue by Guo-astro** [valhalla/valhalla#1809]
I have done some simple test with the time distance matrix.

 The longest distance in this test is 40km. I chooses the coordinates using random points generated in 20km radius circle.

The environment is as follows:
Valhalla 3.0.3
MacOS Mojave 10.14.4
CPU Intel Core i5  3.1 GHz
1 physic processor 
2 cores
Memory:	16 GB

The time measured using python:
` start_time = datetime.now() 
   response = requests.post('http://localhost:8002/sources_to_targets' , headers=headers, data=data)
   time_elapsed = datetime.now() - start_time `

![PerfWithNumPoints20km 001](https://user-images.githubusercontent.com/15899028/57779106-72513080-7760-11e9-97f4-f0f8aaef54eb.jpeg)
In both figures, the vertical axis is the running time measured in seconds and the horizontal axis is the number of coordinates, i.e., 200 means a matrix with 200*200 elements.
I would like to ask that in figure 2,  the run time seems longer than figure 1. Is that an expected behavior?  In figure 2, does the second parameter for valhalla_service means 2 threads are running and waiting for 2 requests in parallel? (Hope the data is helpful ^^)

**Comment by kevinkreiser** [comment]
@Guo-astro yep the second parameter is the number of threads waiting on requests in parallel. So if your python script to send the requests is single threaded then you wont see any gains in throughput and, as you saw, you might see some overhead for just managing the other idle threads. 

Another very important thing here is how you are loading the data. We have seen the best performance when using a memory mapped tar file of the tile data. So please do use that to achieve the highest performance.

**Comment by Guo-astro** [comment]
Thanks very much!   Are there any doc or refs for the  way of using the memory mapped tar? In this test I saw that Valhalla is already using the tared tiles by default.

**Comment by kevinkreiser** [comment]
as long as your tiles are in a tar, and the valhalla.json config is pointing to this tar you should be good to go! when you start the server, you will get an error message if it was unable to load the tar in the config file and if it was successfull it will tell you how many tiles it found in the tar. shouldnt be much more you need to do than just confirm its working by looking at the log messages when you start the service.

**Comment by Guo-astro** [comment]
Thanks! Got it and this test is based on the memory mapped tar!
