### ISSUE TITLE
Matrix API returns incorrect results

### ISSUE THREAD

**Issue by vitalif** [valhalla/valhalla#1814]
Same points give 896 meter distance in `route` mode and 0 (ZERO) meter distance in `matrix` mode.
Valhalla 3.0.2, https://download.geofabrik.de/russia-latest.osm.pbf

Example PHP script:
```
<?php

$r = [
    'costing' => 'pedestrian',
    'locations' => [
        [ 'lat' => 55.759289, 'lon' => 37.630756 ],
        [ 'lat' => 55.765491, 'lon' => 37.636456 ],
    ],
];

$r = json_decode(file_get_contents("http://192.168.1.204:8202/route?json=".urlencode(json_encode($r))), true);
print json_encode($r, JSON_PRETTY_PRINT)."\n\n";

$r = [
    'costing' => 'pedestrian',
    'sources' => [ [ 'lat' => 55.759289, 'lon' => 37.630756 ] ],
    'targets' => [ [ 'lat' => 55.765491, 'lon' => 37.636456 ] ],
];

$r = json_decode(file_get_contents("http://192.168.1.204:8202/sources_to_targets?json=".urlencode(json_encode($r))), true);
print json_encode($r, JSON_PRETTY_PRINT)."\n\n";
```

The result:

```
{
    "trip": {
        "language": "en-US",
        "status": 0,
        "units": "kilometers",
        "status_message": "Found route between points",
        "legs": [ /* omitted */ ],
        "summary": {
            "max_lon": 37.637047000000003,
            "max_lat": 55.765506999999999,
            "time": 644,
            "length": 0.89600000000000002,
            "min_lat": 55.759391999999998,
            "min_lon": 37.630572999999998
        },
        "locations": [
            {
                "original_index": 0,
                "type": "break",
                "lon": 37.630755999999998,
                "lat": 55.759289000000003,
                "side_of_street": "right"
            },
            {
                "original_index": 1,
                "lon": 37.636456000000003,
                "lat": 55.765490999999997,
                "type": "break"
            }
        ]
    }
}

{
    "targets": [
        [
            {
                "lon": 37.636456000000003,
                "lat": 55.765490999999997
            }
        ]
    ],
    "sources_to_targets": [
        [
            {
                "distance": 0,
                "time": 0,
                "to_index": 0,
                "from_index": 0
            }
        ]
    ],
    "sources": [
        [
            {
                "lon": 37.630755999999998,
                "lat": 55.759289000000003
            }
        ]
    ],
    "units": "kilometers"
}
```

**Comment by vitalif** [comment]
Retested with Valhalla 3.0.3 - same result

**Comment by Guo-astro** [comment]
Hi! How about using 'costing' => 'auto'?

**Comment by vitalif** [comment]
I specifically need pedestrian here, not auto

**Comment by vitalif** [comment]
Retested these points with auto, with auto they're OK

**Comment by dnesbitt61** [comment]
What happens if you update your config file to force the matrix algorithm to use cost matrix rather than choosing the optimal?

"source_to_target_algorithm": "timedistancematrix"

I suspect there might be a bug in timedistancematrix.cc where the edge distance (used to penalize candidate edges farther from the location in cases where there are disconnected regions). aastar.cc has code like this when computing costs at the destination edge:

        if (destination_edge.graph_id() == edgeid) {
          newcost.cost += destination_edge.distance();
        }

Something similar needs to exist within TimeDistanceMatrix::UpdateDestinations. I may have some time to look at this a bit later...

**Comment by dnesbitt61** [comment]
Sorry, what I meant is to switch to costmatrix:
"source_to_target_algorithm": "costmatrix"

I do not see this issue when I run with my local server (full planet set of tiles).

**Comment by vitalif** [comment]
> Sorry, what I meant is to switch to costmatrix:
> "source_to_target_algorithm": "costmatrix"

Where should I put this option? It seems that matrix api ignores it.

> I do not see this issue when I run with my local server (full planet set of tiles).

Can you test it with https://download.geofabrik.de/russia-latest.osm.pbf ?

**Comment by dnesbitt61** [comment]
With the latest Russia data from Geofabrik when I run this URL:
http://localhost:8002/sources_to_targets?json={"sources":[{"lat":55.759289,"lon":37.630756}],"targets":[{"lat":55.765491,"lon":37.636456}],"costing":"pedestrian"}

I get valid matrix values:

{

    "targets": [
        [
            {
                "lon": 37.636456,
                "lat": 55.765491
            }
        ]
    ],
    "sources_to_targets": [
        [
            {
                "distance": 1.007,
                "time": 723,
                "to_index": 0,
                "from_index": 0
            }
        ]
    ],
    "sources": [
        [
            {
                "lon": 37.630756,
                "lat": 55.759289
            }
        ]
    ],
    "units": "kilometers"
}

**Comment by vitalif** [comment]
...OK. I altered lua graph script myself so that was probably my own fault. Without my patch the result is correct. Sorry.
