### ISSUE TITLE
valhalla_build_timezones does not replace timezone zip file

### ISSUE THREAD

**Issue by sinabakh** [valhalla/valhalla#1816]
valhalla_build_timezones downloads the `timezones-with-oceans.shapefile.zip` file using `wget`, but if this file already exists (old version or incomplete downloaded file) the tool will not replace it and will create a zip file with a different name (like `timezones-with-oceans.shapefile.zip.2`) which causes the old file to be processed again.
I believe the right behavior of `valhalla_build_timezones` should be replacing the old file. If that's right I would be happy to create the related pull request to fix it.

**Comment by sinabakh** [comment]
Actually, on line 24 of `valhalla_build_timezones` it tries to delete the zip file but there is a name mismatch.
The filename to remove is `timezones.shapefile.zip` and the downloaded filename is `timezones-with-oceans.shapefile.zip`.

**Comment by kevinkreiser** [comment]
@sinabakh great catch! would you like to contribute that fix back in a pull request?

**Comment by sinabakh** [comment]
@kevinkreiser sure, will submit a pull request soon.
