### ISSUE TITLE
[3.0.4]   version number = 3.0.3

### ISSUE THREAD

**Issue by ImreSamu** [valhalla/valhalla#1836]
Thank you for the new release!  :heart: 

imho - in the [v3.0.4 - release](https://github.com/valhalla/valhalla/releases/tag/3.0.4)   -  the version is still v3.0.3
https://github.com/valhalla/valhalla/blob/3.0.4/valhalla/valhalla.h.in

Now:
```
#define VALHALLA_VERSION_MAJOR 3
#define VALHALLA_VERSION_MINOR 0
#define VALHALLA_VERSION_PATCH 3
```

Expected: 4
```
#define VALHALLA_VERSION_MAJOR 3
#define VALHALLA_VERSION_MINOR 0
#define VALHALLA_VERSION_PATCH 4      <------------
```
( related: https://github.com/valhalla/valhalla/issues/1797 )

**Comment by kevinkreiser** [comment]
good catch sorry about that!

**Comment by kevinkreiser** [comment]
fixed! thanks again

**Comment by ImreSamu** [comment]
@kevinkreiser : 
thank you!

please add this to the  release checklist: https://github.com/valhalla/valhalla/blob/master/docs/releasing.md
