### ISSUE TITLE
When Traffic Influenced Routing will be available in Valhalla?

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#1846]
Hello
I've got a question, When Traffic Influenced Routing will be available in Valhalla? 

Thanks

**Comment by kevinkreiser** [comment]
unfortunately that is not on our roadmap at the current time. we have a section of the tiles devoted to storing compressed historical traffic but at the moment we dont have open data to put there nor do we have a means of adding this data to the tiles. so to the point, im not sure if or when it will be in a usable state.
