### ISSUE TITLE
Cant get directions_type "none" work

### ISSUE THREAD

**Issue by liquidsun** [valhalla/valhalla#1848]
Hello!
I am unable to switch off directions in response.
Request is:
...../route?json={
	"locations": [{
		"lon":26.0177777,"lat":58.7872138
	}, {
		"lon":26.9824944,"lat":58.6455555
	}],
	"costing": "auto",
	"directions_options": {
	"directions_type":"none"
	}
}
What is wrong with request?
Many thanks!

**Comment by kevinkreiser** [comment]
i havent tested this but i think we deprecated the `directions_options` structure before we added `directions_type`. basically dont use `directions_options` and put any option at the top level of the json.

**Comment by liquidsun** [comment]
It's working! Thanks a lot for quick response!

**Comment by ecotner** [comment]
@kevinkreiser sorry to resurrect this, but the workings of `directions_options` was confusing the hell out of me until I found this thread! A lot of the examples in the API docs still use it incorrectly [[1]](https://github.com/valhalla/valhalla/blame/master/docs/api/turn-by-turn/api-reference.md#L14) [[2]](https://github.com/valhalla/valhalla/blame/master/docs/api/turn-by-turn/api-reference.md#L221) [[3]](https://github.com/valhalla/valhalla/blame/master/docs/api/turn-by-turn/api-reference.md#L239) and the [section on the options](https://github.com/valhalla/valhalla/blame/master/docs/api/turn-by-turn/api-reference.md#L242-L249) does not make it clear that options should be top-level. Mind if I make some modifications?

**Comment by kevinkreiser** [comment]
@ecotner sure thing!
