### ISSUE TITLE
global_synchronized_cache missing in valhalla_build_config ?

### ISSUE THREAD

**Issue by AurelienLP** [valhalla/valhalla#1850]
Hello guys!

I was just wondering if global_synchronized_cache was missing in purpose in valhalla_build_config or not.

If not, should I quickly add it?

Thank you very much!

Aurelien

**Comment by kevinkreiser** [comment]
Its a feature we haven't used in any production environment ourselves contributed by someone external. So no, its not on purpose, just lack of need from our side so far. Feel free to add it!

**Comment by AurelienLP** [comment]
Just created the PR, thanks again @kevinkreiser!
