### ISSUE TITLE
build on Window

### ISSUE THREAD

**Issue by angiebs** [valhalla/valhalla#1869]
Hi

I have started building Valhalla on Windows and I really have followed all the instrucctions here and also looking into the other issues referenced in this post (#1606 and #1605). It was a really demanding work since I have not worked with CMake in the past, so now I am learning.

I have faced all the problems with protobuf between others.

The most difficult problem to resolve was the: **conflict macros MIN and MAX from windows.h with std::min, std::max.
In this case I had to include the library algorithm into the file util.h located in \valhalla\valhalla\midgard.

I have commented the line 291 in the CMakeLists.txt => #add_subdirectory(test). Can I do that without affecting the process?

And finally I got a success Build in ALL_BUILD proyect in visual studio.

Then I executed "Build" into the proyect INSTALL, but I get this error

![error](https://user-images.githubusercontent.com/16880640/60708816-37bd7600-9f0f-11e9-9b4c-397f6622f0f9.png)

Any idea why?

**Comment by chazanov** [comment]
Better use a FOSS compiler, it works.
