### ISSUE TITLE
Retrieve WayIDs in route

### ISSUE THREAD

**Issue by DupuyNicolas** [valhalla/valhalla#1874]
Hello,

I'm using routing API on a Valhalla which i run locally. I need to retrieve osm way ids for the shape in the response, so i can later easily match other informations i have previously stored and indexed with way ids.

I've seen this issue which seems quite old and not resolved : #https://github.com/valhalla/valhalla/issues/4

The other issue mentionned thor/trippathbuilder but i can't figure out if there's some kind of configuration i can use, or if i need to fork the project and code my own "extension" ?

**Comment by kevinkreiser** [comment]
we have a service you can access called `trace_attributes` which lets you retrieve metadata along a map matched route. what you can do is first call `/route` and get the route geometry. then call `/trace_attributes` with `shape_walk` and tell it what metadata you want to get. see the documentation here: https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md

**Comment by DupuyNicolas** [comment]
Thanks a lot Kevin, that is exactly what I need !
