### ISSUE TITLE
trace_attributes bad match point at intersection

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1878]
using clang on a mac, we are seeing a request which will return a match point which is a combination of two match candidates' metadata. specifically we see that the route found between two states of the HMM ends at the end of one edge but that the candidate marked as the winner is the beginning of the next edge. because of this, when we serialize the final match point we get an edge that has the right location and right edge id but has the wrong "distance_along". this can really screw up the downstream user in that it can basically say that the match point is at the wrong end of the edge!

working on a test case to make this easily testable but might have to rely on clang/mac to get that going!

**Comment by yuzheyan** [comment]
Is this one the same one with intersection matching. If so, issues can combine

**Comment by yuzheyan** [comment]
@kevinkreiser does intersection matching fix this one?

**Comment by kevinkreiser** [comment]
yep!
