### ISSUE TITLE
Python bindings usage

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [valhalla/valhalla#1883]
Hi, 
I read that there is a python binding. For that reason, I wonder if there is a python script usage to work on ?

Regards,
Bruno

**Comment by kevinkreiser** [comment]
The bindings we have are a python module. We have a test, that exorcises this module: https://github.com/valhalla/valhalla/blob/master/test/bindings/python/utrecht-test.py other than that we have no examples really. If you want you can extend that test to show more APIs, other than that what exactly are you looking to do?

**Comment by BrunoEduardoCSantos** [comment]
Thanks for your feedback.
My goal is converting a list of GPS coordinates to the road network I created. My question would how can I create the road segment edges using a simple txt?
