### ISSUE TITLE
Add Location Indexes 

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#189]
(2016-09-21T17:11:26Z) @dnesbitt61 : originally created valhalla/tyr#127

Request for an identifier of location index that will allow a user to easily correlate input locations with output locations. This was requested for Optimized Route where the location order is changed by the optimizer.

**Comment by kdiluca** [comment]
We have added original_index to locations for the optimized_route response.  This will be in our next release.

**Comment by kdiluca** [comment]
Fix in production.  Example:  
http://matrix.mapzen.com/optimized_route?json={"locations":[{"lat":40.042072,"lon":-76.306572},{"lat":39.992115,"lon":-76.781559},{"lat":39.984519,"lon":-76.6956},{"lat":39.996586,"lon":-76.769028},{"lat":39.984322,"lon":-76.706672}],"costing":"auto","units":"mi"}
