### ISSUE TITLE
Update Links in Documentation

### ISSUE THREAD

**Issue by CharlyUnicorn** [valhalla/valhalla#1894]
Hi,
nice project and good documentation. 

I saw a few disabled links/errors in your documentation: 

- links to api documentation at https://valhalla.readthedocs.io/en/latest/api/
- missing image at https://valhalla.readthedocs.io/en/latest/api/isochrone/api-reference/
- "isocrhone" wrong spelled at https://valhalla.readthedocs.io/en/latest/api/ ->  isochrone

**Comment by kevinkreiser** [comment]
yeah we moved this from a deprecated repository so it was all in one place and in the move some of the links got borked. we'll fix these up when we get a chance, thanks for the heads up
