### ISSUE TITLE
Possible bug found when routing to a state that has no tiles.

### ISSUE THREAD

**Issue by Jkkarr2015** [valhalla/valhalla#1899]
I believe I may have found a bug. I'm running a locally hosted Valhalla Server and I only have the tiles built for Kentucky and Indiana, but I was curious as to what would happen if I routed to the Cincinnati Zoo in Ohio. 

Here is the JSON query I used to get the route. `{"locations":[{"lat":38.2572737,"lon":-85.7142493},{"lat":39.1433304,"lon":-84.5089872}],"costing":"auto","costing_options":{"auto":{"country_crossing_penalty":2000.0,"use_tolls":1.0,"use_highways":1.0,"use_ferry":1.0,"maneuver_penalty":5.0}},"directions_options":{"units":"miles"}}`

Since I don't have the tiles built for Ohio shouldn't I have gotten some sort of no suitable edge error? My "Arrive" Location is 39.113559, -84.479523 which is still in Kentucky and about 6 miles from the Zoo. Is that right?

**Comment by kevinkreiser** [comment]
@Jkkarr2015 there are options to determine the behavior that is right for your application. In this case the default behavior is to give you the nearest location to your input within 35km. This behavior is changable though. We have a search_cutoff parameter on the location object which will, indeed, give back a no suitable edge error if no edges exist within this search_cutoff radius. Please have a look at: https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#locations

**Comment by Jkkarr2015** [comment]
@kevinkreiser  Is the `search_cutoff` parameter in kilometers? So I could say `"search_cutoff":0.065` to cut off if my arrive point is more than 65 meters from the destination?

**Comment by kevinkreiser** [comment]
@Jkkarr2015 it and `radius` are both in meters
