### ISSUE TITLE
How to get start node id

### ISSUE THREAD

**Issue by Guo-astro** [valhalla/valhalla#1901]
HI  I have a question, I can get a  DirectedEdge  use  const DirectedEdge* diredge = tile->directededge(startnodeinfo.edge_index());
 How can I get the start node of diredge?

**Comment by dnesbitt61** [comment]
Use the convenience method ig GraphReader to get the opposing directed edge, the endnode method will give the GraphId of the node.

nodeid = graphreader.GetOpposingEdge(directededge, tile)->endnode();

Be careful though as this can update the value of tile if the edge leaves the current tile. Another way is:

GraphId endnode = directededge->endnode();
GraphTile* endtile = (directededge->leaves_tile() ? graphreader.GetGraphTile(endnode()) : tile;
GraphId opp_edge_id(endnode.tileid(), endnode.level(), endtile->node(endnode)->edge_index() + directededge->opp_index());
GraphId startnode = endtile->directededge(opp_edge_id)->endnode()

**Comment by Guo-astro** [comment]
It works like a charm!! Thanks!!
