### ISSUE TITLE
Optimized Route service results not reasonable

### ISSUE THREAD

**Issue by marthus82** [valhalla/valhalla#1947]
Hi,
is there a maximum number of points that can be handled by the Optimized Route service? 
I have raised the values in the configuration up to 1.000 points. Requests containing 200 or 800 points return results that are neither optimized in order nor reasonable in any way. Requests containing 10 or 20 points work out. 
Following screenshot shows the unreasonable results for 800 points (points are labeled in the order they are returned):
![Screenshot1](https://user-images.githubusercontent.com/55245932/64842216-c5010300-d601-11e9-8595-3fa67115ef1f.JPG)

Is there a way to raise the limits?
Thanks

**Comment by dnesbitt61** [comment]
This has not been tested with such large numbers of locations. I would look at increasing the number of attempts (though it seems to increase based on the location count - perhaps it doesn't increase enough). In thor/optimizer.cc try increasing these:

 attempts_ = 400 * count_;
  successes_ = 40 * count_;

It will take longer to run, but hopefully provide a better answer?

**Comment by marthus82** [comment]
Thanks, that solved the problem

**Comment by jingfei05** [comment]
Hi there
I am seeing the similar problem.  I am wondering if we can make adjustment to get better results?
starting point is missing and resulting route seems to quite confusing.
![image](https://user-images.githubusercontent.com/13552731/77517328-2a4b7180-6e39-11ea-9e14-7cefc1087a78.png)
