### ISSUE TITLE
Valhalla_build_tiles command terminated by signal 11

### ISSUE THREAD

**Issue by Jkkarr2015** [valhalla/valhalla#1949]
Yesterday I tried to run this line

`valhalla_build_tiles -c valhalla.json north-america-latest.osm.pbf  europe-latest.osm.pbf`

It ran for about 13 hours before it terminated by signal 11. Is this a known bug? Should I try just running one at a time? I have successfully built North America tiles before, but this was the first time I've tried Europe. I, unfortunately, don't have the last few lines it output to the screen because I rebooted my server. Has anyone else seen this and hopefully, know how I can fix it?

Edit: I'm using Valhalla version 3.0.7

**Comment by kevinkreiser** [comment]
this sounds like you ran out of memory, though you shouldnt need a crazy amount... i havent recently done the planet on my machine but i used to be able to do it on a machine with 8gb of ram

**Comment by Jkkarr2015** [comment]
I have 8gb of ram on an Ubuntu server.

**Comment by kevinkreiser** [comment]
@gknisely have you run the planet lately?

@Jkkarr2015 the process would have dropped some intermediate `bin` files you can resume the creation of tiles using those if you know what step in the proceedure you made it to. oh right right... there was recently a change in #1852 which i have seen on CI run us out of memory though i havent been able to prove it. i think the code defaults to not buidling that data so unless you configured it to use that it shouldnt be affecting you... at any rate if you have those intermediate files you can start at the building tiles stage for example or at the enhancement stage. see if you can figure out where it left off and restart from there with a build that has symboles attached so you can get a core file for example.

**Comment by Jkkarr2015** [comment]
@kevinkreiser  how would I restart the creation of tiles at a specific point? What would that command look like?

**Comment by gknisely** [comment]
@kevinkreiser no i have not ran the planet on my laptop for some time.  EU was the last huge pbf that I converted.  

@Jkkarr2015 like this `./valhalla_build_tiles -s enhance -e cleanup -c ../../conf/valhalla.conf /data/mapbox/osm_data/spain-latest.osm.pbf` where -s is the start and -e is the end.  You can get the build order via `./valhalla_build_tiles --help` 

Build stage strings (in order)
    parse
    build
    enhance
    filter
    transit
    bss
    hierarchy
    shortcuts
    restrictions
    elevation
    validate
    cleanup

**Comment by Jkkarr2015** [comment]
@gknisely  Thanks for the response. I was able to build just the Europe file by itself and that worked. I'm going to try the NA and EU build again tonight and see what happens.

**Comment by Jkkarr2015** [comment]
It failed again. Same error. The output looks like this:
2019/09/19 19:50:40.962851 [INFO] Start stage = initialize End stage = cleanup
2019/09/19 19:50:42.189504 [INFO] Parsing files: north-america-latest.osm.pbf, europe-latest.osm.pbf
2019/09/19 19:50:42.189561 [INFO] Parsing ways...
2019/09/19 19:53:55.427264 [WARN] Max osmid exceeded bitset, resizing to fit id: 6570550716
2019/09/19 19:53:56.238566 [WARN] Max osmid exceeded bitset, resizing to fit id: 6733378894
2019/09/19 19:53:56.251311 [WARN] Max osmid exceeded bitset, resizing to fit id: 6584833965
2019/09/19 19:53:56.764463 [WARN] Max osmid exceeded bitset, resizing to fit id: 6726943266
2019/09/19 19:53:56.905024 [WARN] Max osmid exceeded bitset, resizing to fit id: 6804527419
2019/09/19 19:53:58.322573 [WARN] Max osmid exceeded bitset, resizing to fit id: 6802243904
2019/09/19 20:42:27.479472 [INFO] invalid_argument thrown for condition (Jun 15-Labor Day)
2019/09/19 20:45:19.247502 [INFO] invalid_argument thrown for condition (Jun 15-Labor Day)
2019/09/19 22:44:22.666506 [INFO] invalid_argument thrown for condition (Jan 01- May 31)
2019/09/19 22:44:22.667555 [INFO] invalid_argument thrown for condition (Jan 01- May 31)
2019/09/19 23:40:03.695527 [INFO] invalid_argument thrown for condition (Jan 01- May 31)
2019/09/20 00:25:20.407829 [INFO] Finished with 88364744 routable ways containing 923122185 nodes
2019/09/20 00:25:20.407887 [INFO] Sorting osm access tags by way id...
2019/09/20 00:25:21.363803 [INFO] Parsing relations...
2019/09/20 00:37:03.232264 [INFO] invalid_argument thrown for condition  Jul 1- Aug 31 off
2019/09/20 01:12:51.751187 [INFO] Finished with 760483 simple restrictions
2019/09/20 01:12:51.751232 [INFO] Finished with 0 lane connections
2019/09/20 01:12:51.807951 [INFO] Sorting complex restrictions by from id...
2019/09/20 01:12:51.853557 [INFO] Sorting complex restrictions by to id...
2019/09/20 01:12:51.898987 [INFO] Sorting osm way node references by node id...
2019/09/20 01:33:31.962573 [INFO] Finished
2019/09/20 01:33:31.965992 [INFO] Parsing nodes...
2019/09/20 04:33:16.278260 [INFO] Finished with 793268492 nodes contained in routable ways
2019/09/20 04:33:16.278969 [INFO] Sorting osm way node references by way index and node shape index...
2019/09/20 04:55:28.951094 [INFO] Finished: max_osm_id 6804068107
2019/09/20 04:55:28.952547 [INFO] Number of nodes with refs (exits) = 81602
2019/09/20 04:55:28.952553 [INFO] Number of nodes with exit_to = 9535
2019/09/20 04:55:28.952557 [INFO] Number of nodes with names = 36327
2019/09/20 04:55:28.952561 [INFO] Number of way refs = 232999
2019/09/20 04:55:28.952564 [INFO] Number of reverse way refs = 20486
2019/09/20 04:55:28.952568 [INFO] Unique Node Strings (names, refs, etc.) = 29706
2019/09/20 04:55:28.952571 [INFO] Unique Strings (names, refs, etc.) = 6215216
2019/09/20 04:55:29.038573 [INFO] Creating graph edges from ways...
2019/09/20 04:56:44.690811 [INFO] Finished with 184595932 graph edges
2019/09/20 04:56:45.089228 [INFO] Sorting graph...
2019/09/20 05:15:13.774814 [INFO] Finished with 143106983 graph nodes
2019/09/20 05:15:14.412373 [INFO] Reclassifying link graph edges...
2019/09/20 05:19:25.884622 [INFO] Class: 0 exit count = 105743
2019/09/20 05:19:25.886992 [INFO] Class: 1 exit count = 126647
2019/09/20 05:19:25.887002 [INFO] Class: 2 exit count = 178604
2019/09/20 05:19:25.887006 [INFO] Class: 3 exit count = 200381
2019/09/20 05:19:25.887009 [INFO] Class: 4 exit count = 128184
2019/09/20 05:19:25.887012 [INFO] Class: 5 exit count = 22013
2019/09/20 05:19:25.887016 [INFO] Class: 6 exit count = 41969
2019/09/20 05:19:25.887019 [INFO] Class: 7 exit count = 0
2019/09/20 05:35:12.370935 [INFO] Finished with 679490 reclassified.  Turn channel count = 347457
2019/09/20 05:35:12.795370 [INFO] Reclassifying ferry connection graph edges...
2019/09/20 05:44:16.240703 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 1967, 66550 edges reclassified.
2019/09/20 05:44:16.840918 [INFO] Building 46814 tiles with 4 threads...
2019/09/20 05:44:16.849241 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 05:44:16.849305 [WARN] Time zone db /home/valservice/valhalla_router/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
2019/09/20 05:44:16.849942 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 05:44:16.849999 [WARN] Time zone db /home/valservice/valhalla_router/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
2019/09/20 05:44:16.850008 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 05:44:16.850122 [WARN] Time zone db /home/valservice/valhalla_router/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
2019/09/20 05:44:16.850642 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 05:44:16.850664 [WARN] Time zone db /home/valservice/valhalla_router/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
2019/09/20 05:45:33.250480 [WARN] Speed = 150 wayId= 706566228
2019/09/20 05:45:33.253880 [WARN] Speed = 150 wayId= 706566227
2019/09/20 05:45:33.698331 [WARN] Speed = 150 wayId= 706566228
2019/09/20 05:45:34.152666 [WARN] Speed = 150 wayId= 706566227
2019/09/20 05:45:34.152740 [WARN] Speed = 150 wayId= 166291289
2019/09/20 05:49:00.679746 [WARN] Speed = 150 wayId= 25469747
2019/09/20 05:49:00.680909 [WARN] Speed = 150 wayId= 25469747
2019/09/20 05:49:00.680926 [WARN] Speed = 150 wayId= 25469744
2019/09/20 05:49:00.680939 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:00.680970 [WARN] Speed = 150 wayId= 25469744
2019/09/20 05:49:00.680984 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:00.681014 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:01.976105 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:01.976818 [WARN] Speed = 150 wayId= 625523473
2019/09/20 05:49:01.977791 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:01.977816 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:01.977926 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:01.977957 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:04.030334 [WARN] Speed = 150 wayId= 625497423
2019/09/20 05:49:04.032433 [WARN] Speed = 150 wayId= 625497422
2019/09/20 05:49:04.032468 [WARN] Speed = 150 wayId= 625523473
2019/09/20 05:49:04.032612 [WARN] Speed = 150 wayId= 625497423
2019/09/20 05:49:05.929781 [WARN] Speed = 150 wayId= 136184117
2019/09/20 05:49:05.929845 [WARN] Speed = 150 wayId= 136184114
2019/09/20 05:49:05.929881 [WARN] Speed = 150 wayId= 136184117
2019/09/20 05:49:05.929907 [WARN] Speed = 150 wayId= 451894612
2019/09/20 05:49:05.929925 [WARN] Speed = 150 wayId= 136184114
2019/09/20 05:49:06.530783 [WARN] Speed = 150 wayId= 625523474
2019/09/20 05:49:06.530862 [WARN] Speed = 150 wayId= 451894612
2019/09/20 05:49:06.895728 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:06.895839 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:06.957816 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:06.957894 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.579730 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.579794 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.580417 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.580437 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.581975 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582010 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582710 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582732 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582760 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582784 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582804 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582813 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582835 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:07.582851 [WARN] Speed = 150 wayId= 43053918
2019/09/20 05:49:10.081811 [WARN] Speed = 150 wayId= 625497422
2019/09/20 05:49:10.081909 [WARN] Speed = 150 wayId= 647627173
2019/09/20 05:49:10.144682 [WARN] Speed = 150 wayId= 647627173
2019/09/20 05:49:10.144766 [WARN] Speed = 150 wayId= 625523474
2019/09/20 05:57:51.964469 [WARN] Exceeding maximum.  Average speed: 164
2019/09/20 05:57:52.024826 [WARN] Exceeding maximum.  Average speed: 164
2019/09/20 06:16:54.002089 [WARN] Too many names for edgeindex: 46920396
2019/09/20 06:25:41.639680 [WARN] Restrictions mask exceeds allowable limit on wayid: 28653224
2019/09/20 06:25:41.641155 [WARN] Restrictions mask exceeds allowable limit: 384
2019/09/20 06:25:41.868836 [WARN] Restrictions mask exceeds allowable limit on wayid: 154988355
2019/09/20 06:25:41.868912 [WARN] Restrictions mask exceeds allowable limit: 510
2019/09/20 06:25:42.201048 [WARN] Restrictions mask exceeds allowable limit on wayid: 548393055
2019/09/20 06:25:42.201143 [WARN] Restrictions mask exceeds allowable limit: 385
2019/09/20 06:25:42.202019 [WARN] Restrictions mask exceeds allowable limit on wayid: 654568890
2019/09/20 06:25:42.202044 [WARN] Restrictions mask exceeds allowable limit: 510
2019/09/20 06:25:42.202130 [WARN] Restrictions mask exceeds allowable limit on wayid: 640540601
2019/09/20 06:25:42.202151 [WARN] Restrictions mask exceeds allowable limit: 386
2019/09/20 06:29:59.363453 [ERROR] Failed tile 2/746780/0: std::bad_alloc
2019/09/20 07:54:40.612774 [WARN] Restrictions mask exceeds allowable limit on wayid: 180572036
2019/09/20 07:54:40.614394 [WARN] Restrictions mask exceeds allowable limit: 1021
2019/09/20 07:54:40.614447 [WARN] Restrictions mask exceeds allowable limit on wayid: 389186706
2019/09/20 07:54:40.614460 [WARN] Restrictions mask exceeds allowable limit: 1022
2019/09/20 07:54:40.614586 [WARN] Restrictions mask exceeds allowable limit on wayid: 389186595
2019/09/20 07:54:40.614602 [WARN] Restrictions mask exceeds allowable limit: 1019
2019/09/20 07:54:40.614662 [WARN] Restrictions mask exceeds allowable limit on wayid: 389186596
2019/09/20 07:54:40.614676 [WARN] Restrictions mask exceeds allowable limit: 1022
2019/09/20 08:15:43.974606 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:43.993214 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:43.994460 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:44.109252 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:44.109299 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:44.287565 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:44.287635 [WARN] Speed = 150 wayId= 166291289
2019/09/20 08:15:53.969153 [INFO] Finished
2019/09/20 08:15:53.988359 [INFO] Node Count = 107436401
2019/09/20 08:15:53.988390 [INFO] Directed Edge Count = 276320329
2019/09/20 08:15:53.988394 [INFO] EdgeInfo Count = 139395830
2019/09/20 08:15:53.995992 [INFO] Enhancing local graph...
2019/09/20 08:15:54.540517 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 08:15:54.540635 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 08:15:54.540618 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 08:15:54.540724 [WARN] Admin db /home/valservice/valhalla_router/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2019/09/20 08:16:42.649539 [WARN] Exceeding maximum.  Average speed: 163
2019/09/20 08:16:42.799631 [WARN] Exceeding maximum.  Average speed: 163
2019/09/20 08:17:18.714367 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:18.789828 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:18.933168 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.135880 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.136087 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.139162 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.161092 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.575404 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.575537 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.576151 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.577083 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.619140 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.619413 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.619569 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.640548 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.640652 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.641104 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:19.641135 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:52.557588 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:17:56.802258 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:21:27.861754 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:21:36.240624 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:22:10.957563 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:22:11.389653 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:26:04.968277 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:26:26.440790 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:26:56.995036 [WARN] Exceeding maximum.  Average speed: 150
2019/09/20 08:26:57.837118 [WARN] Exceeding maximum.  Average speed: 150
2019/09/20 08:30:07.530628 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:30:07.530750 [WARN] Exceeding maximum.  Average speed: 141
2019/09/20 08:35:52.876626 [WARN] Exceeding maximum.  Average speed: 150
2019/09/20 08:35:53.085842 [WARN] Exceeding maximum.  Average speed: 150
Command terminated by signal 11

**Comment by Jkkarr2015** [comment]
@kevinkreiser  I also just looked at [#1852](https://github.com/valhalla/valhalla/pull/1852) which from what I can tell was added in 3.0.8, but I'm using version 3.0.7 and having this issue. What was the last version that someone was able to build the world with?

**Comment by dnesbitt61** [comment]
I have only built the planet with 16 GB RAM, so I cannot say it has worked in a long time with just 8 GB.  I now use a 32 GB laptop but did planet wide conversions 6 months ago with 16GB.

**Comment by Jkkarr2015** [comment]
Which version did you use?

**Comment by dnesbitt61** [comment]
probably 3.0.2 was the last time on a 16GB laptop. On 32GB probably worked with 3.0.6 most recently.

**Comment by kevinkreiser** [comment]
the thing here is that his log doesnt say `bad_alloc` it basically says seg fault. this makes me think it is not running out of memory. @Jkkarr2015 make a debug build and start it at the enhacner phase and see where in the code it is segfaulting. looks like it fails only like a half hour into the build so it shouldnt be too annoying

**Comment by Jkkarr2015** [comment]
Unfortunately, I wiped out all those files so I could get something working. I will run a debug version tonight and I will post the log from it tomorrow morning.

**Comment by Jkkarr2015** [comment]
@kevinkreiser how would I run it as debug?

**Comment by Jkkarr2015** [comment]
@kevinkreiser  I'm not fully done yet with the build but it has failed again with the debug build. I'm not sure if I actually ran it as debug or not though. I basically reinstalled Valhalla and for the CMake I used  

`cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=On -DENABLE_PYTHON_BINDINGS=On -DCPACK_GENERATOR=DEB`

I'm not sure if there was something else you meant when you said debug or not. The failed line does not have any more information than the other way I ran it. Will there be something more in the log files for the build? Where are the logs saved to? Would it be worth it to attempt to run the planet file since it is in one file and not multiple? I was able to build tiles for North America and Europe separately just not together.

**Comment by Jkkarr2015** [comment]
@kevinkreiser  @gknisely  @dnesbitt61 I finally got the stack trace from the sig faults I've been getting. 
[valhalla_sig_fault_stack_trace.txt](https://github.com/valhalla/valhalla/files/3671047/valhalla_sig_fault_stack_trace.txt)

If someone more familiar with the project could help me narrow down what the problem is I would greatly appreciate it. This has been a pain in my side for WAY too long.

**Comment by kevinkreiser** [comment]
@Jkkarr2015 we have a fix for this. that we just haven't pushed up yet. stand by!
