### ISSUE TITLE
Wrong instructions for roundabouts - always "Please take the 2nd exit".

### ISSUE THREAD

**Issue by cranik** [valhalla/valhalla#1950]
the instructions for roundabouts are always wrong. 
There is always the instruction: "Please take the 2nd exit". 
Even if it should be the 1st or the 3rd exit.

**Comment by dgearhart** [comment]
@cranik do you have an example route?

**Comment by Jkkarr2015** [comment]
I've also run into this. I thought it was just off by 1.

**Comment by cranik** [comment]
@dgearhart example route https://shared.gurumaps.app/5d84c73423fd3fc566c52908.html

The correct way is the 1th exit. Valhalla says ’Take the 2nd exit“

**Comment by dgearhart** [comment]
@cranik thanks for reporting - we have seen this when the `driving side of street` is incorrect for a particular country. We will investigate and fix
@Jkkarr2015 if you  have an example in a different country please submit

**Comment by dgearhart** [comment]
@cranik currently - I am seeing this being called out at `Enter the roundabout and take the 1st exit.`

![image](https://user-images.githubusercontent.com/7515853/65329105-cdb78300-db85-11e9-8bce-57b20c22c196.png)

![image](https://user-images.githubusercontent.com/7515853/65329207-0192a880-db86-11e9-9766-e2811bbe8b4b.png)

**Comment by Jkkarr2015** [comment]
I forgot to say which version I was using. I'm on 3.0.7

**Comment by dgearhart** [comment]
@Jkkarr2015 I am seeing `Enter the roundabout and take the 1st exit.` for both roundabouts

![image](https://user-images.githubusercontent.com/7515853/65329832-4965ff80-db87-11e9-992a-b1dc38e701d4.png)

**Comment by gknisely** [comment]
@Jkkarr2015 and @cranik are you converting data with an Admin database?  If not the driving side of street will not be correct.  
/cc @dgearhart

**Comment by Jkkarr2015** [comment]
I don't think I am. How would I go about doing that?
