### ISSUE TITLE
Accurate center position missing in isochrone response

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#1961]
The current isochrone response is missing the snapped isochrone center. It should/could substantially deviate from input coordinate when it snaps to the road network. 

I'd suggest

`features[].properties.center_lon`
`features[].properties.center_lat`

to keep compatibility with all geographic data drivers.

What do you think?

EDIT:
Not-so-important side question: does Valhalla take the closest node as center or the closest point on the closest edge and introduce virtual edges between that virtual node and the neighboring real nodes? And in either case: is that the same snapping behavior for all methods (i.e. directions and matrix)?

**Comment by kevinkreiser** [comment]
@nilsnolde thats a great idea and not too heavy of a lift, would you be interested in contributing it. i think the bulk of the work would just be in https://github.com/valhalla/valhalla/blob/master/src/tyr/isochrone_serializer.cc. if you noticed we have a "show_locations" option to show the original input but not one to show the snapped location.

we snap the location to the closest point on the closest edge that matches the criteria of the requests costing object options. it can snap to a node if the closest thing is a node or its within the node snap tolerance, in which case we seed the isochrone from all the edges leaving the node.

**Comment by nilsnolde** [comment]
I'd love to @kevinkreiser, C++ is on my list for next year though ;)

But @MichaelsJP will have a crack at it I just heard!

**Comment by nilsnolde** [comment]
Oopsie, googling myself I realized this is still open. Fixed a long time ago in #2111
