### ISSUE TITLE
Street Network View with Valhalla

### ISSUE THREAD

**Issue by angiebs** [valhalla/valhalla#1963]
Hi,

I would like to know if there is a way to calculate a Street Network View (see image) by using Valhalla. 

![image](https://user-images.githubusercontent.com/16880640/66384921-e31f1080-e9bf-11e9-9a8f-4011dd09dc2e.png)

Reading the documentation it seems that has not been implemented, but I can see that Valhalla uses many algorithms and maybe it is possible to have also this functionality.

Thank you

**Comment by nilsnolde** [comment]
+1

Related to #1703. I guess Protobuf output format is a general feature being worked on. Would be nice to keep it also in mind for `/isochrone` endpoint.

For inspiration: Graphhopper has [implemented](https://github.com/graphhopper/graphhopper/pull/1577) a CSV endpoint in the latest release to **live-stream** the Dijkstra exploration when building isochrones. Super cool, but not sure what the use cases would be except flashy demos.

**Comment by kevinkreiser** [comment]
@angiebs we implemented this in geojson. where each feature is the edge in the order it was expanded by the algorithm. currently it only works for bidirectional a*. have a look at this pr: #1849

**Comment by angiebs** [comment]
Thank you very much for the info kevin.
