### ISSUE TITLE
begin_shape_index=0, end_shape_index=0

### ISSUE THREAD

**Issue by divya1c** [valhalla/valhalla#1966]
Hi!

I am trying to get all the valhalla edges for a specific region. So, I go through osm roads and use trace_attributes to get valhalla edges for these roads. 
1. I assumed that begin_shape_index and end_shape_index indicate where the edge line starts after decoding the polyline shape. But, I see that both of these indexes are zero for some of the data. What would that mean?

Request shape:
{"shape":[{'lat': '37.4865474598707', 'lon': '-122.181291017096'}, {'lat': '37.4867562530787', 'lon': '-122.181169730957'}, {'lat': '37.4868107354494', 'lon': '-122.181126815613'}, {'lat': '37.4868447659762', 'lon': '-122.181066717367'}, {'lat': '37.4868478672804', 'lon': '-122.181043248039'}],"costing":"auto","shape_match":"edge_walk", "filters":{"attributes":["edge.id","edge.speed","edge.speed_limit"],"action":"include"}}

Response:
{'shape': 'i|~nfArij`hF{KsFqBkA}@yBEm@', 'edges': [{'speed': 50, 'begin_shape_index': 0, 'end_shape_index': 0, 'id': 2712070887049}, {'speed': 50, 'begin_shape_index': 0, 'end_shape_index': 4, 'id': 2712473540233}], 'alternate_paths': []}

Decoded polyline for the shape in response: 
[[-122.18129, 37.486549], [-122.181168, 37.486755], [-122.18113, 37.486812], [-122.181069, 37.486843], [-122.181046, 37.486846]]

2. Is there any other easier way to get valhalla edges?

Thanks!

**Comment by divya1c** [comment]
any help possible here? just giving it a bump :)

**Comment by kevinkreiser** [comment]
@divya1c it looks like there is a zero length edge at the beginning of the match. we could do some work to trim these out of the response i think. especially at the beginning and end of the match when the input shape is close to a node in the route network its hard for the algorithm to decide between two equally likely edges. i would say for now you can just ignore zero length edges at the beginning and ending of the returned match.
