### ISSUE TITLE
Replace use of boost::filesystem::path::c_str() with portable boost::filesystem::path::string()

### ISSUE THREAD

**Issue by mloskot** [valhalla/valhalla#1967]
The use of the `path::c_str()` is not quite portable because the returned `boost::filesystem::path::value_type` is implementation / build-configuration specific:
- `char` on Linux (or any POSIX system, AFAIK)
- `wchar_t` on Windows

Whereas `std::string path::string()` is guaranteed on any system as per Boost.Filesystem implementation:

```cpp
#ifdef BOOST_WINDOWS_API
    const std::string string() const
...
```

So, any call like `rapidjson::read_json(config_file_path.c_str(), pt);` should be patched like so in order to ensure successful compilation on Windows:

```cpp
boost::property_tree::ptree pt;
+ rapidjson::read_json(config_file_path.string(), pt);
- rapidjson::read_json(config_file_path.c_str(), pt);
```

Otherwise, it will fail:

```
error C2664: 'void read_json(const std::string &)': cannot convert argument 1 from 'const boost::filesystem::path::value_type *' to 'const std::string &'
note: Reason: cannot convert from 'const boost::filesystem::path::value_type *' to 'const std::string'
note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

I will try to propose a patch soon, unless objections arrive.

**Comment by kevinkreiser** [comment]
@mloskot we have our own `filesystem` in the project and we havent quite made use of it every where. i would suggest we make use of this https://github.com/valhalla/valhalla/blob/master/valhalla/filesystem.h and delete `boost::filesystem` completely. we have wanted to do this for ever but havent gotten around to removing all of it yet.

**Comment by mloskot** [comment]
@kevinkreiser Aha! Thanks for the pointer (and reminder). I will see what I can do about it.

**Comment by mloskot** [comment]
This has been cleared by PR #2081

Thanks @kevinkreiser
