### ISSUE TITLE
Why return by const value?

### ISSUE THREAD

**Issue by mandeepsandhu** [valhalla/valhalla#1971]
Saw this in a few places in `admin.cc`. Whats the reason for returning `const` objects? 

Eg:
https://github.com/valhalla/valhalla/blob/3176db5363b4a3c678532b8d496274858977776d/src/baldr/admin.cc#L57

Should these be const references instead? I believe returning `const` value for non-builtin types prevents use of rvalue/move semantics of c++11?

**Comment by gknisely** [comment]
Yeah.  Probably should just be `std::string Admin::state_iso() const { `  Thanks for catching

**Comment by mloskot** [comment]
Looks like a perfect first issue to submit PR for :-)

**Comment by mandeepsandhu** [comment]
Ok, so I found a few more instances in the `src` dir:
```
src/baldr/admin.cc:const std::string Admin::country_iso() const {
src/baldr/admin.cc:const std::string Admin::state_iso() const {
src/meili/viterbi_search.cc:const StateId StateLabel::id() const {
src/meili/viterbi_search.cc:const StateId StateLabel::stateid() const {
src/meili/viterbi_search.cc:const StateId StateLabel::predecessor() const {
src/odin/signs.cc:const std::string Signs::GetExitNumberString(uint32_t max_count,
src/odin/signs.cc:const std::string Signs::GetExitBranchString(uint32_t max_count,
src/odin/signs.cc:const std::string Signs::GetExitTowardString(uint32_t max_count,
src/odin/signs.cc:const std::string Signs::GetExitNameString(uint32_t max_count,
src/valhalla_associate_segments.cc:const vs::EdgeFilter DistanceOnlyCost::GetEdgeFilter() const {
src/valhalla_associate_segments.cc:const vs::NodeFilter DistanceOnlyCost::GetNodeFilter() const {
```

Should these be done in a single PR, or separate ones for each of the dirs under `src` ?

**Comment by kevinkreiser** [comment]
@mandeepsandhu single pr is fine!
