### ISSUE TITLE
[Question] Is it possible to turn off some of the messages while valhalla_service is running?

### ISSUE THREAD

**Issue by Jkkarr2015** [valhalla/valhalla#1975]
Hello,

I want to remove a certain line of logging from the valhalla_service output. Particularly the line that looks like this:

`Oct 16 13:53:44 server bash[5235]: 100 2019/10/16 17:53:44.592218 GET /route?{%22locations%22:[{%22lat%22:38.2572581,%22lon%22:-85.714216,%22heading%22:229.08835},{%22lat%22:38.2885818,%22lon%22:-85.5098469}],%22costing%22:%22auto%22,%22costing_options%22:{%22auto%22:{%22country_crossing_penalty%22:2000.0,%22use_tolls%22:1.0,%22use_highways%22:1.0,%22use_ferry%22:1.0,%22maneuver_penalty%22:5.0}},%22directions_options%22:{%22units%22:%22miles%22}} HTTP/1.1`

Where would I edit so that I don't output this information?

**Comment by kevinkreiser** [comment]
@Jkkarr2015 that happens in prime server, its api has a boolean which allows you to turn this off. if you are running this in a multi process setup you can just pass the boolean to `prime_httpd` as a command line argument. if you are running `valhalla_service` you will need to change some code:

**Comment by Jkkarr2015** [comment]
So if I change that does it take out all logging or just the line that I'm talking about?

**Comment by mloskot** [comment]
>  if I change that does it take out all logging 

Yes, all logging, AFAIK.

I imagine, this simple `log` boolean and the checks

https://github.com/kevinkreiser/prime_server/blob/14c7592d604264110eb70e984dc6ccd4d9b04a69/src/prime_server.cpp#L250

could be replaced with levels

https://gist.github.com/kevinkreiser/39f2e39273c625d96790/c5b9b40d1e47cd190d78582993fd07e4478540af#file-logging-hpp-L27

passed to `server_t`, for flexible configurability.

**Comment by mloskot** [comment]
> Other log message information that comes from Valhalla

Yes, correct. I thought by "it take out all logging" you mean all messages by primer server only, not valhalla engine itself. Those are two separate software-s.
