### ISSUE TITLE
Remove symlinks from repository

### ISSUE THREAD

**Issue by mloskot** [valhalla/valhalla#1976]
During discussion about `git clone` command update in the README, in https://github.com/valhalla/valhalla/pull/1973#discussion_r335014371`, @kevinkreiser suggested there is a possibility to remove the symlinks. I think it is a very good idea and I'd like to help make it happen soon :-)

Although I imagine there are not many users building and developing Valhalla on/for Windows, the symlinks are obviously troublesome on Windows. Hence my PR #1973. 

However, they have been troublesome for other scenarios e.g. in release archives #1151 and #1324.

What would be the approach preferred by the dev team?

-----

```
$ find . -type l -ls | grep -o -E '\.\/.+$'
./ChangeLog -> CHANGELOG.md
./docs/changelog.md -> ../CHANGELOG.md
./docs/index.md -> ../README.md
./locales/README -> README.md
./proto/fileformat.proto -> ../third_party/OSM-binary/src/fileformat.proto
./proto/osmformat.proto -> ../third_party/OSM-binary/src/osmformat.proto
./README -> README.md
./run_route_scripts/perf_test/README -> README.md
./run_route_scripts/README -> README.md
./run_route_scripts/requests -> ../test_requests
./run_route_scripts/results/README -> README.md
```

**Comment by kevinkreiser** [comment]
all of the readme links can be deteled
ChangeLog link can be deleted

seems some of the docs use links to get to things outside of the docs directory, we should just update the docs that rely on these links.

@dgearhart can we remove the requests directory link?

for the osm proto definitions we will need to add to cmake a bit that handles generating bindings to these seprately. i think right now the cmake is something like `for protodef in proto/*` we'd need to add another that looks in the thirdparty directory as well

**Comment by dgearhart** [comment]
@kevinkreiser every user would have to manually create a sym link for tools that use the test_requests dir?

**Comment by mloskot** [comment]
The runner already accepts paths, so why not change 

```
./run.sh requests/demo_routes.txt ../../conf/valhalla.json
```

to read

```
./run.sh ../test_requests/demo_routes.txt ../../conf/valhalla.json
```

Why not get all components to explicitly reach to locations they need. 
IMHO, childifying required directories from parent scopes using symlinks is a false convenience, it also obscures structure.

**Comment by dgearhart** [comment]
@mloskot yes, sounds good to remove the `requests` directory link - thanks

**Comment by mloskot** [comment]
@kevinkreiser 
> all of the readme links can be deteled
> ChangeLog link can be deleted

I have done this part in PR #2001

**Comment by themightychris** [comment]
The main page and "Introduction for Developers" link seem to be broken now, related to this change?

https://valhalla.readthedocs.io/en/latest/

**Comment by mloskot** [comment]
@themightychris see https://github.com/valhalla/valhalla/pull/2001#issuecomment-550339973, no related fixes followed yet though

**Comment by mloskot** [comment]
@kevinkreiser in https://github.com/valhalla/valhalla/issues/1976#issuecomment-543778517
> for the osm proto definitions we will need to add to cmake a bit that handles generating bindings to these seprately.
> i think right now the cmake is something like for protodef in proto/*
> we'd need to add another that looks in the thirdparty directory as well

I'd like to resurrect this one and complete the issue.
I believe we can remove the two remaining symlinks now

```
./proto/fileformat.proto -> ../third_party/OSM-binary/src/fileformat.proto
./proto/osmformat.proto -> ../third_party/OSM-binary/src/osmformat.proto
```

Since this change to the `CMakeLists.txt`, those symlinks seem no longer required:

https://github.com/valhalla/valhalla/blob/0200898a773832166aac25512cb560e549d899bc/proto/CMakeLists.txt#L11-L12

Shall I submit a PR?

**Comment by kevinkreiser** [comment]
@mloskot ship it!

**Comment by mloskot** [comment]
Sorry for the noise, I probably had been looking at wrong snapshot of the source tree.

The two OSM's `.proto` files have been removed long ago, as part of #2001 which effectively closes this issue.
