### ISSUE TITLE
Specify libgeos and protobuf version we work with

### ISSUE THREAD

**Issue by vmihaylenko** [valhalla/valhalla#1978]
## Why
So I was building Valhalla and found out it can't be built with libgeos3.8 (which is libspatialite dependency). The maximum version we still support is libgeos3.7. For 3.8 (which is currently presented in brew) we have to modify out code otherwise it doesn't compile.
The same story with protobuf but I'm not sure the maximum version we still support. I can say that's 3.9 version (and 3.10 which is currently in brew) can't be compiled and also 3.6 version works just fine. So IMO it leads us to have a mason file in valhalla with specific libs we need to correct work. But so far we can specify that we work with libgeos3.7 and lower and also with protobuf3.6 (and probably lower versions but need to determine).

## Unknowns
The minimum version of libgeos and min/max version of protobuf.

**Comment by kevinkreiser** [comment]
we've fixed the protobuf part of this. but the geos issue remains. i wonder if some tricky use of auto/decltype can get us around this issue with minimal `ifdef`s.. had a hack on this this morning with @yuzheyan but didnt finish it up yet
