### ISSUE TITLE
Reachability Doesnt Agree With Path Finding

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1983]
At the moment its possible for loki to find candidate edges which it thinks are reachable but which thor thinks are not. This is due to an assumption we made early on which was that loki didnt need to know everything about path finding it just needed to know which edges were generally acceptable and which weren't.

Then, like all things, we a realized it was more complicated. First off the reach check in loki was naive when it came to just traversing the graph (for the sake of performance). We patched that up recently in #1965. Then we realized that the path finding bit was too strict in #1982 so we'll patch that up. But fundamentally we are realizing that we need loki and thor to agree on what parts of the graph are accessable and not.

We've started work on remedying that in #1981 which allows loki full access to the rule set from sif that thor uses to find a path. Our next goal is to change the reach check to stop using just the edge and node filters but to do a proper graph traversal using the allowed methods and of course generating predecessor lables (so that restrictions work properly) and tracking time so that time dependencies work correctly. In the end we might move this general expansion (similar to isochrones i guess) into thor and call it from loki. The idea though is that we dont actually care about the cost or the path itself so we may be able to take quite a bit of short cuts to keep performance reasonable.

**Comment by PureW** [comment]
This was implemented in https://github.com/valhalla/valhalla/pull/2243
