### ISSUE TITLE
Bi-directional route failure for routes

### ISSUE THREAD

**Issue by divya1c** [valhalla/valhalla#1996]
I am trying to get a route between points. I have given a radius of a 1000 meters for the api to correlate the location with the route network. But, I still get no routes. On google maps, I see that there are roads that are closer than a 1000 meters to the location. I am using norcal tiles. 
Eg.
Point1: {"lat": 37.710731, "lon": -122.114628, "radius": 1000}
Point2: {"lat": 37.750466, "lon": -122.39495, "radius": 1000}
No route found via /route api, with logs:
```
2019/10/24 20:23:02.274402 [ERROR] Bi-directional route failure - reverse search exhausted: n = 33261,15
2019/10/24 20:23:02.319847 [ERROR] Bi-directional route failure - reverse search exhausted: n = 88528,47
2019/10/24 20:23:02.319924 [ANALYTICS] 400::No path could be found for input
```
What does the error message mean?

**Comment by dnesbitt61** [comment]
This error means that while it finds a road at the destination, there is no path that leads into where the destination is found. If you look at OSM near the destination, Valhalla could be finding the Yellow Cab Access Road as the destination and there may be some reason that this cannot be reached via the Missisippi Street entrance.  Without looking further and debugging this is just a guess. But basically if one search direction exhausts after some number of iterations it generally means that the location (origin or destination) is a "disconnected" region that does not allow access to outside roads.

**Comment by divya1c** [comment]
Thanks for the reply @dnesbitt61 ! Is there a way to get around this? 
Sometimes, when i get the closest node via /locate and then route, I get a route. I thought that when i call /route, it will associate my point to the closest node automatically.

**Comment by dnesbitt61** [comment]
Perhaps some of the work @kevinkreiser is doing for reachability #1983 will help here. Otherwsie you might need to look into OSM data and see if there needs to be some map edits to make sure a connected path exists (and has correct auto access and oneways) in that region.

**Comment by divya1c** [comment]
thanks @dnesbitt61 !
