### ISSUE TITLE
Default truck attributes

### ISSUE THREAD

**Issue by MichaelsJP** [valhalla/valhalla#1999]
Hi,
currently, the default truck attributes for weight, axle load, height, width and length are kind of concealed in `/src/sif/truckcost.cc`:
```
// Default truck attributes
constexpr float kDefaultTruckWeight = 21.77f;  // Metric Tons (48,000 lbs)
constexpr float kDefaultTruckAxleLoad = 9.07f; // Metric Tons (20,000 lbs)
constexpr float kDefaultTruckHeight = 4.11f;   // Meters (13 feet 6 inches)
constexpr float kDefaultTruckWidth = 2.6f;     // Meters (102.36 inches)
constexpr float kDefaultTruckLength = 21.64f;  // Meters (71 feet)
```
It's quite nontransparent when calculating truck routes with no dimension parameters set.
What do you think of removing them or even better, define them globally somewhere in the config.json?

**Comment by gknisely** [comment]
@MichaelsJP First, thank you for your feedback and using Valhalla.  

For now I think it is fine to have the defaults within the costing.  Maybe in the future we can move these to the config.  As for removing them altogether, that would defeat the purpose of the truck costing.  Basically, we would be performing a auto route if we removed the default values.  

Thank you again!

**Comment by kevinkreiser** [comment]
@MichaelsJP one more thing to mention is that yes the defaults are concealed but they are also all modifyable in the http request. i think it would be fine to simply document the defaults in the api documentation for each parameter with the understanding that if you dont like the default you will override it in your http request json.
