### ISSUE TITLE
Performance improvement for valhalla_fetch_transit.cc

### ISSUE THREAD

**Issue by bryanrideshark** [valhalla/valhalla#2000]
Right now, valhalla_fetch_transit does the phase where it fetches data from Transit.land in a sequential fashion. It's incredibly slow; Would it be possible to do multiple downloads concurrently in this file?

**Comment by blackmad** [comment]
Curious as well about the performance of this - given that it takes forever to process just one city, was it ever used in production? Is it possible to load all of transitland into valhalla
