### ISSUE TITLE
What's the radius that loki uses?

### ISSUE THREAD

**Issue by divya1c** [valhalla/valhalla#2002]
Hi! 

I am using loki to find the closest node for a point in the graph. I read in the documents that if radius is not specified, loki finds the closest point within reasonable reach. 

What does 'reasonable' mean? Is that a parameter in the config? Thanks! :)

**Comment by divya1c** [comment]
bump on this, if someone knows the answer :)

**Comment by kevinkreiser** [comment]
So there is another parameter called search_cutoff which defaults to 35km. you can set that as well. if you want to find the closest "node" as in graph node you can use the node_snap_tolerance to to allow the search to snap to nodes at a higher distance, default is 5m. all of these are request time options mentioned in the docs, no need to change config values.
