### ISSUE TITLE
Can we switch to C++17 (for <filesystem> and others) ?

### ISSUE THREAD

**Issue by mloskot** [valhalla/valhalla#2009]
Currently, Valhalla requires C++14.

Would it be feasible to bump the requirement to **C++17**?

We are cutting down on Boost dependency. The major one is the Boost.Filesystem which is being replaced with the slim version of `filesystem.h`.
I have been looking into completing the port of Valhalla to it and the slim version, well, slim and limited:

- portability bugs and limitations are being discovered (e.g. PR #2007)
- features are missing for portability with Boost libraries that are still in use e.g. `program_options` (see PR #2008)
- it provides `std::string`-based only `path` which is useless in non-ASCII/non-UTF8 environments (see also #1967)
- numerous small functions are missing which are needed to complete the port (e.g. `parent_path` and other `path` manipulators)

The slim filesystem implementation will grow and it will have to be tested and maintained. 

I have no idea about requirements of Valhalla core team and users, but from development point of view I think it would be much more sensible if Valhalla did one of the two:

1. Switch to C++17 and `<filesystem>` library
2. Vendor Boost.Filesystem

------

Alternatives, feasible but with potential of more work required, are:

1. Make the `path` in the slim `filesystem` based on character-parametrized type of string for support of single-byte ASCII, multi-byte UTF-8 and two-byte UTF-16.

2. Allow compile-time define-based selection between the slim `filesystem` and Boost.Filesystem

**Comment by kevinkreiser** [comment]
this is a tougher question than it seems unfortunately. by switching to c++17 (which i agree would make our lives easier in so many ways) we also run the risk of making the code unusable for people who are targetting platforms with older compilers that lack support for it. this is particularly important for embedded systems which have very long update cycles in terms of tool chains.

let me ask around some of the folks i know who are targetting these systems. and hopefully others can chyme in on this issue if it would be a problem from them. i'm hoping we dont hear wide reaching disagreement but we will see.

i also agree the vendoring boost filesystem would work but oh man that would be a sad state of affairs..

**Comment by mloskot** [comment]
@kevinkreiser 
> this is a tougher question than it seems unfortunately (...)

No doubt it is. Still, it's worth to probe and discuss the idea :)

> i also agree the vendoring boost filesystem would work but oh man that would be a sad state of affairs...

Yes.

I have updated the issue description above adding a list of feasible "Alternatives".

**Comment by mskurydin** [comment]
We can still try C++14 first, which requires very small changes in the code (we did this locally https://github.com/valhalla/valhalla/pull/2022), though it will not give us significant feature improvement, some things like std::shared_mutex can be nice to have.

**Comment by mloskot** [comment]
@mskurydin 
> We can still try C++14 first, which requires very small changes in the code

Specifically to this issue, this will not buy us anything. This will not solve the `filesystem.h` vs Boost.Filesystem vs `<filesystem>` issue that is the major motivation of my suggestion in this issue.

Generally, switching from C++98/03 or C++11 in terms of requiring the new compilation mode of `-std:c++14` is a cosmetic change, it's pointless. IMO, a sensible switch is either from C++98/03 to C++11 or from anything to C++17.

**Comment by kevinkreiser** [comment]
I've updated the OP to mention the current situation which is c++14 and wanting to move to c++17.

**Comment by mloskot** [comment]
A bunch of facts about C++ versions support in context of GCC:

- [C++14](https://gcc.gnu.org/projects/cxx-status.html#cxx14): This mode is the default in GCC 6.1 up until GCC 10 (including)
- [C++17](https://gcc.gnu.org/projects/cxx-status.html#cxx17): This mode is the default in GCC 11

and the current landscape of the GCC versions on some Linux distributions:

- RHEL 8: GCC 8 and 9
- Debian 9 (oldstable): GCC 6
- Debian 10 (stable): GCC 8
- Debian 11 (testign): GCC 10
- Ubuntu 16.04: GCC 5
- Ubuntu 18.04: GCC 7
- Ubuntu 20.04: GCC 9

**Comment by danpat** [comment]
One thing that needs to be clear: we're talking about _source code_ versioning here.  One option might be that we allow C++17 constructs in the code, then leave it up to developers to figure out how to cross-compile binary objects for shipping to older systems that don't have newer compilers available.  It's not always necessary to have the build-system compiler available in the target runtime environment.

Is there anyone following this thread that is working in such an environment?  Why not just build binary objects, pay close attention to ABI/library interfaces.

(this is somewhat of a devils advocate question - I'm aware that a typical pattern for some antiquated systems is to do a full source-code build within the old environment - I want to hear the arguments for continuing to support that vs forcing builds of Valhalla with newer compilers producing backward compatible binary modules that get packaged and transferred).

**Comment by mloskot** [comment]
>  It's not always necessary to have the build-system compiler available in the target runtime environment.

Correct.

> If we promised to keep the public interfaces C++14 compatible, we could free up access to C++17 and onward constructs within the implementations.

I'd fear a maintenance hassle, extra requirements (work for reviewers), confused contributors of PRs, etc.

------

A natural scenario is that, when major Linux developers end life of their distributions where default GCC version is older than 8, that is a sign to switch from C++14 to C++17.

A practical scenario is that, when major Linux distributions offer their native packages with GCC 8 or later, that should enable the switch to from C++14 to C++17.

If the practical scenario is not too disruptive for those who build or link-consume Valhalla, it should be feasible now/soon.

**Comment by danpat** [comment]
> I'd fear a maintenance hassle, extra requirements (work for reviewers), confused contributors of PRs, etc.

@mloskot What about something like this built into CI:

```sh
$ cat foo.hpp
class Test {
  int x,y;
  Test() {
    int a[2] = {1,2};
    auto [x,y] = a;
  }
};
$ g++ -std=c++17 -Werror foo.hpp
$ g++ -std=c++14 -Werror foo.hpp
foo.hpp:5:10: error: decomposition declarations are a C++17 extension [-Werror,-Wc++17-extensions]
    auto [x,y] = a;
         ^~~~~
1 error generated.
```

We should be able to define which of our headers in the `valhalla/` directory need to be subject to the compatibility rules, and run a quick check over them similar to above.

**Comment by kevinkreiser** [comment]
> Is there anyone following this thread that is working in such an environment?

the only person maintaining such a system that i'm aware of is @brunoabinader 

there are other more exotic deployments like the one @noblige has (although i think nvidias compilers are pretty up to date) and still other folks who make sure valhalla is building on things like sailfish os and openbsd (though those should be fine).

> I'd fear a maintenance hassle

I agree with this. Having the codebase be halfway c++17 is burdensome even if we can use CI to police our headers to stay c++14.

**Comment by mloskot** [comment]
@danpat Yes, I also think such CI support is a must.

In fact, I think the CI should build for the minimal required C++ version as well as all subsequent versions and, ideally, using GCC **and** clang. For example, see Boost.MP11 [.github/workflows/ci.yml](https://github.com/boostorg/mp11/blob/7694815d7bd98d6d7a373c87e418980c5aa477c9/.github/workflows/ci.yml).

**Comment by molind** [comment]
Hello, everyone.

Today I was looking at what heavy global resources libvalhalla loads at startup. And most of the work turned out to be locales.h, which creates 
const std::unordered_map<std::string, std::string> locales_json
And then creating std::locale for all languages at once.

In C++17 you could use constexpr string_view and not create std::string. And there are many implementations of constexpr map to avoid allocating memory and calling constructors unnecessarily.
With this approach we could choose locales_json implementation depending on compiler version. For C++17 this would reduce memory usage and speed up loading.

**Comment by nilsnolde** [comment]
It's almost 2023 and honestly, I'd personally like Valhalla to move forward a bit (and shed quite some code/dependencies in the process). We're always arguing that some people might build Valhalla in some esoteric environments where C++17 isn't available (or major parts of it aren't). 

Can those people please speak up (e.g. @noblige @brunoabinader) ? Maybe they moved on or their build systems improved significantly?

**Comment by noblige** [comment]
I don’t mind @nilsnolde

**Comment by kevinkreiser** [comment]
if i had to bet, i would say that most folks are likley on forks that are significantly diverged from public master. this means that if they are taking functionality that gets merged into master at all they are porting those changes over to their forks anyway.

with that reasoning in mind im wondering if we shouldnt just go straight to `c++20` it has lots of convenient stuff:

1. howard hinnants date time(zone) stuff (so we can ditch what we have (maybe, we still need consistent numbering))
2. modern string formatting (std::format)
3. shared_ptr atomics (might be able to fix that issue with compile time graphtile pointer semantics)
4. ranges as a first class citizen (rather than keeping track of two iterators yourself)
5. init statements for range based for-each loops, huge quality of life improvement


what about other projects like the one  @dnesbitt61 works on or the one @PhilippVoigt ? would it break your build systems if we upgraded to c++17 or even better c++20? or more directly, are you guys using modern compilers for your target platforms?

**Comment by nilsnolde** [comment]
Hm I think I’d balk a bit with C++20 bcs of pyvalhalla😅 But I’ll research if python bindings wouldn’t get hurt too much. Worst case we’d have to live not being compatible with some old-ish CentOS/other long-lived distros, which could be acceptable.

**Comment by kevinkreiser** [comment]
why would that bother python bindings? i should educate myself on the build system over there i guess? i thought it would be find with pybind

**Comment by molind** [comment]
Nowadays everyone could build Valhalla inside docker and it will work without any overhead on any distro.

**Comment by kevinkreiser** [comment]
there are many embedded systems where that wont be an option. eg, inside car dashboards on special hardware, or on android or on ios. those types of embedded (read: non-server) use-cases still need to be able to compile to their native target platform imho

**Comment by kevinkreiser** [comment]
also merry christmas everyone :smile:

**Comment by molind** [comment]
@kevinkreiser Latest Xcode and Android Studio support all OS version with share more that 1%. (iOS 12+ on Xcode 14.2.0, Android 4.4+ with NDK r25b). Both support C++20. It's a common practice to drop support older mobile OS once it's not supported with latest IDE. :)

p.s. 🎄

**Comment by nilsnolde** [comment]
> why would that bother python bindings?

It needs to be built on a system with the lowest glibc we can find so it has max compat with other distros. Usually it’s some CentOS or older Debian. C++17 is for sure not a problem, C++20 I’ll have a look and report back:)

Enjoy Xmas❤️

**Comment by mloskot** [comment]
Can we do it with baby steps
1. Switch to C++17 and announce the plan to jump to C++20 over next let's say six months
2. Switch to C++20

This will at least give ourselves time to find and fix any problems and people to complain about the switch to C++17 as an indicator before switching to C++20.

**Comment by nilsnolde** [comment]
I think that makes sense. Improvements between both versions wouldn’t overlap too much anyways I suppose. And buys some time for compilers to evolve, eg I just saw that one needs gcc 13.x for std::format to work, that’s not even released yet anywhere. 

I’ll open a new issue for folks to add stuff coming to mind when switching to 17, so it’s a bit cleaner.
