### ISSUE TITLE
Option to avoid ways with custom osm tag

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#2020]
Hello,
Is there any option available for excluding ways with custom OSM attributes? Like the OSRM option to avoid some user defined excludables in runtime.
I know about the avoidEdges and avoidLocations options but they need too many coordinates to avoid for my use case.

**Comment by safe-bug** [comment]
It is possible to create a custom cost class to read edge/node osm tags and if there exists that specific tag on it, set filter it or set its cost so high. But how can I access custom osm tags in my custom cost class?

**Comment by kevinkreiser** [comment]
@safe-bug we dont store all tags we only store those which are useful to routing. yes we support runtime excludes, please see the documentation: https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#automobile-and-bus-costing-options

if you want to make a custom costing you will only have those attributes (tag values) which we normalize into the graphs edges and nodes. please see directededge.h and nodeinfo.h for more info on what is in there!

**Comment by stefanocudini** [comment]
similar issue in #2134
