### ISSUE TITLE
Enable compiler warnings

### ISSUE THREAD

**Issue by PureW** [valhalla/valhalla#2027]
It would be nice if CI ran with compiler warnings (e.g. `-Wall -Wextra -Werror`).

Since satisfying all warnings on all platforms may be more work than it's worth, the suggestion is to use one build as _the one_ and run with warnings as errors only on that build.

Creating a new cmake option, such as `-DENABLE_COMPILER_WARNINGS=On` and using that on the `build-debug` target in CircleCi would accomplish this.

**Comment by kevinkreiser** [comment]
ship it!
