### ISSUE TITLE
Speed up the lint step in CI

### ISSUE THREAD

**Issue by PureW** [valhalla/valhalla#2033]
The lint stage in CI takes a _long_ time. It seems due to `clang-tidy` being quite slow since it by default runs on the full source code. An improvement would be to only run it on changed files as described in https://pspdfkit.com/blog/2018/using-clang-tidy-and-integrating-it-in-jenkins/

**Comment by kevinkreiser** [comment]
it would also be nice to ditch the the whole tidy variant and just make debug be lint/tidy (all builds do lint at the begining as a fast fail so it would just be adding tidy to the debug build and removing the lint build, i think)
