### ISSUE TITLE
Include mySQL in build

### ISSUE THREAD

**Issue by swilinsky** [valhalla/valhalla#2045]
Hi,  
I'm trying to include a call to mysql as part of my costing but when I run make I get :

```
[ 80%] Linking CXX executable valhalla_service
src/libvalhalla.a(pedestriancost.cc.o): In function `valhalla::sif::PedestrianCost::getPolScore(std::vector<valhalla::midgard::PointLL, std::allocator<valhalla::midgard::PointLL> >) const':
pedestriancost.cc:(.text+0x18ef): undefined reference to `sql::mysql::get_driver_instance()'
collect2: error: ld returned 1 exit status
CMakeFiles/valhalla_thor_worker.dir/build.make:107: recipe for target 'valhalla_thor_worker' failed
make[2]: *** [valhalla_thor_worker] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/valhalla_thor_worker.dir/all' failed

```
Is there a simple way to get the make to include the MySQL libraries?

Thanks
Steve

**Comment by PureW** [comment]
Pulling in MySQL libraries for every user of `Valhalla` seems very bloated when the core routing has no such dependency. Could you not simply patch your local copy of Valhalla?

**Comment by swilinsky** [comment]
Hi,

That's what I'm trying to do but I cant get it to compile / link.  I don't have any experience of  CMake and am not sure what I need to do in there to get it to pull in the mysql libraries.

I'm using mysql in SIF in one of the dynamic costing module.

Any advice would be appreciated.

Thanks
Steve

**Comment by PureW** [comment]
Maybe something like this would be helpful? https://stackoverflow.com/a/35069320/1049866
