### ISSUE TITLE
Move docker files to valhalla/valhalla repo

### ISSUE THREAD

**Issue by MichaelsJP** [valhalla/valhalla#2067]
Move the docker setup files from valhalla/docker to valhalla/valhalla and adjust the `.circleci` file with the changed locations.

**Comment by MichaelsJP** [comment]
There are a lot of files in https://github.com/valhalla/docker.
I thought about moving the docker files into the valhalla root and the rest into `./` scripts.
Another way would be to introduce a new folder e.g. `./deploy` and move all that in there.
Any preferences?

**Comment by kevinkreiser** [comment]
@MichaelsJP which files are you talking about. the only important ones for the upgrade would be the various `Dockerfile*` files. i think its only a 4. tbh we've only really been updating the `-build` ones of late. the actual other docker files have probably not been keeping up with the rest of our changes. at any rate the CI relies only on the `-build` ones. i would suggest we update those for now and worry about a larger refactor of this (possibly just move the docker files into the valhalla repo in a directory called docker as you suggested) later.

**Comment by PureW** [comment]
As part of this (or as a potential followup) we could have CircleCI build the image if necessary and publish updated ones.
