### ISSUE TITLE
Possibility for Speeding up PBFGraphParser

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#2095]
Lua parsing will set a large number of tags in the results and many of these will have false or 0 values. Each of these tags must go through a complex set of conditionals (at least for ways) in pbfgraphparser and the result is to set individual values in the OSMWay structure to 0 or false. However, the structure is initialized with all values = 0 (I hope!) so these should be unnecessary.

Is it possible to not add key value pairs to the result map when the value is "false" or "0" within luatagtransform.cc? If so this could yield perhaps a 25% speedup in parsing. A test case for PA showed way parsing went from 57.4 secs to 44.6 secs. Would need to make sure this would not result in any data changes.

**Comment by kevinkreiser** [comment]
we could make a quick test whether it or not it would result in data changes by doing binary comparison of the binary sequence files that we write out while parsing.

**Comment by dnesbitt61** [comment]
Ran a test and the parsed .bin files do not all match. Closing this ticket.
