### ISSUE TITLE
Complex turn-restriction invalidates edge marked as kPermanent

### ISSUE THREAD

**Issue by PureW** [valhalla/valhalla#2103]
![turn-restriction](https://user-images.githubusercontent.com/85910/70356506-8e263c00-1842-11ea-8043-67ec43c6047c.gif)

Here's what happens on Bayfront ave in Singapore. The first expansion in forwards search goes for the shortest path and marks the edges as permanent. But at the last turn, the complex turn-restriction no-uturn kicks in and prevents further expansion.

Then, the astar evaluates going west and correctly coming back from the eastward direction. But now it stops because it finds the edge already marked as permanent.

**Test-case**
```
curl http://localhost:8002/route --data '{"locations":[{"lat":1.282185,"lon":103.859650,"street":"Sheares Link"},{"lat":1.282493,"lon":103.859421,"street":"Sheares Link"}],"costing":"auto","units":"miles", "date_time": {"type": 1, "value": "2019-05-02T15:00"}}'
```
Note: The test-case only exhibits this behaviour in timedependant forward search. Bidirectional manages to avoid this deadlock due to expanding from reverse direction.

**Proposed solution**

We don't mark edges as permanent if they are part of a complex restriction.

**Comment by dnesbitt61** [comment]
Good catch and an interesting case. However, I don't think it will be sufficient to just not mark this as permanently labeled. The case for temporary labels is such that it replaces the predecessor in the priority queue only if the new path to the end of the edge results in a lower cost than the prior path. I think additional special case logic is required (near line 197 in astar.cc). The problem I see is that if you update the predecessor to allow the alternate path that avoids the Uturn, then you would generate bad paths for any route that just goes right onto Bayfront Ave and continues (not a Uturn).

**Comment by PureW** [comment]
>  The problem I see is that if you update the predecessor to allow the alternate path that avoids the Uturn, then you would generate bad paths for any route that just goes right onto Bayfront Ave and continues (not a Uturn).

Some more discussion at https://github.com/valhalla/valhalla/pull/2109#pullrequestreview-329361207

**Comment by PureW** [comment]
## Addendum

In order to find the optimal path in a situation involving complex restrictions, an edge's status as `kPermanent` becomes a function of the future path expanded. It becomes prohibitively expensive to fully evaluate this function to find the optimal path which means we need to find an appropriate approximation.

The complete reset of all edges part of the complex restriction (called _v2_ and implemented in https://github.com/valhalla/valhalla/pull/2109) is a rather aggressive approach. It does ensure _a_ path is found but the path may be sub-optimal.

## 

## Alternative approach - v3

@kevinkreiser and I came up with an alternative approach, called _v3_. _V3_ would only reset edges on the complex restriction _if the edge can be shown to not fork to multiple paths or join from multiple roads_.

We can track whether a predecessor edge forks to multiple paths in the `Expand*` functions, similar to the recently implemented u-turn detection and then set a bit on the predessor.
We can track whether a edge joins from mutiple paths by setting the same bit during the `EdgeLabel.Update(...)` call.

## Path forward

We'll merge the currently implemented aggressive approach, called _v2_ to master to at least produce _a_ path although it may be sub-optimal in some situations.

In a follow-up PR, a two-tiered approach will be implemented: Begin with _v3_ (which should find the optimal path in many situations but _wont find any path_ in some situations). If this approach fails to find a path (and a complex restriction was encountered) fall back to _v2_ which should at least find _a_ path.

**Comment by PureW** [comment]
Tracking implementation of version 3 in https://github.com/valhalla/valhalla/issues/2193
