### ISSUE TITLE
Sqlite error while building valhalla in windows

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2108]
I am following [issue 1645](https://github.com/valhalla/valhalla/issues/1645)
I got following error while building Valhalla in Windows 10. I have provided path of dll as
-DSQLITE3_LIBRARY which I have downloaded from sqlite official site.

`-- Found SQLite3: E:/open_steet_map/libs_and_dependencies/sqlite/lib/sqlite3.dll
CMake Error at cmake/FindSQLite3.cmake:101 (MESSAGE):
Found sqlite, but the sqlite3_enable_load_extension is disabled
Call Stack (most recent call first):
CMakeLists.txt:197 (find_package)
`

**Comment by PureW** [comment]
It sounds like your sqlite was built without extension loading support https://www.sqlite.org/c3ref/enable_load_extension.htmld

**Comment by asheesh1202** [comment]
i may sound naive, but How can i built sqlite with extension loading. While compiling, it asks for dl (dynamic loading) and pthread libraries which I don't know where to find.

**Comment by PureW** [comment]
I haven't used Windows for many years. I'd suggest checking sqlite documentation around how to
 1) Build succesfully
 2) Tweak build-config to allow extension loading

**Comment by MichaelsJP** [comment]
@asheesh1202 It may be worth to build and install sqlite3 with vcpkg for windows.
1. Download here: https://github.com/microsoft/vcpkg
2. Follow the instructions on github. 
3. Run the exe from within the local folder with: `vcpkg.exe install sqlite3 --triplet x64-windows`
4. Run: `vcpkg.exe integrate install` to make the lib available system wide or link it directly.
Hope that helps :+1:

**Comment by asheesh1202** [comment]
Solved: 
Build a static Sqlite lib again in Visual Studio.
