### ISSUE TITLE
Parallel requests to actor route fails

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#2110]
Hello 
I want to get route using actor_t::route method just like the way this comment says (https://github.com/valhalla/valhalla/issues/1693#issuecomment-457038703) but when I send requests to it in parallel, it fails with lots of different error like "munmap_chunk(): invalid pointer" or "double free or corruption".
How can I fix it?

I should add that I initialize just one actor and use it for parallel request, creating an actor for each request will increase the response time.

**Comment by PureW** [comment]
Can you post some minimum example code?

**Comment by safe-bug** [comment]
@PureW I just create and use actor.cc, this is how I use it:

```
MyValhalla::MyValhalla(std::string json): actor(json_to_pt(json), true) {
}

boost::property_tree::ptree MyValhalla::json_to_pt(const std::string& json) {
    std::stringstream ss;
    ss << json;
    boost::property_tree::ptree pt;
    rapidjson::read_json(ss, pt);
    return pt;
}

std::string MyValhalla::route(std::string request) {
        return actor.route(request);
}
```

**Comment by dnesbitt61** [comment]
I think you should create a separate actor per thread, that is how I always use it. Also, you would need to call loki worker first to find routable roads near the supplied locations.

**Comment by safe-bug** [comment]
@dnesbitt61 Thanks for your answer. Isn't the loki worker call inside the actor route function enough for this? (I mean this: https://github.com/valhalla/valhalla/blob/2cd1c8e3ceef68e1fcdd5885fc70a06c179c9ce5/src/tyr/actor.cc#L52)

**Comment by dnesbitt61** [comment]
Sorry, disregard my statement. I was looking at some code I have that uses workers with multiple threads, not actors.

**Comment by safe-bug** [comment]
@dnesbitt61 Thanks, Is it possible for you to share your code with me?

**Comment by dnesbitt61** [comment]
It is within an Android framework so I can't share a working version. It also uses pbf in and pbf out (so there is no JSON interface. The guts is a simple class whose constructor instantiates GraphReader using the global_synchronized_cache (so the reader is shared among threads).  Each individual route call uses shared pointers to construct and call each worker in sequence (loki, thor, odin) followed by a custom pbf serializer at the end.

**Comment by safe-bug** [comment]
@dnesbitt61 I see. Thanks for your help.

**Comment by kevinkreiser** [comment]
None of the `worker` objects, which `actor_t` encapsulates, are thread safe. If you want to call actor functions on separate threads you need to put mutexes around the individual worker calls. You could attempt to make the workers thread safe but that would be pretty rough. Loki worker and odin worker would be quite easy to make thread safe but making the thor_worker_t thread safe will be a significant obstacle.

**Comment by safe-bug** [comment]
@kevinkreiser Thanks for the reply. I think putting mutexes along with using single workers won't solve the problem because it affects the response time. 
I also tried something like the @dnesbitt61 idea, by creating a shared graph reader for actor and use it for all route calls (workers will be instantiated by calls), but the response time is twice as normal.
