### ISSUE TITLE
Isochrones with > 1 origin location overwrite themselves

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2115]
While working on #2111, I found that there's a bug when providing more than 1 origin location for isochrones: it simply overwrites the isochrone result for each location with the result for the last provided location in the `locations` list:

```
curl -XPOST http://localhost:8002/isochrone -d '{"locations":[{"lat":48.207608,"lon":16.356626}, {"lat":48.134934, "lon":16.465759}],"costing":"auto","contours":[{"time":1,"color":"ff0000"}], "show_locations":true}'
```
returns
```
{"features":[{"properties":{"fill":"#ff0000","opacity":0.33,"center_lon":16.356611,"fillOpacity":0.33,"fill-opacity":0.33,"fillColor":"#ff0000","color":"#ff0000","center_lat":48.207546,"contour":1},"geometry":{"coordinates":[[16.463625,48.140018],[16.464258,48.136242],[16.465958,48.135944],[16.466625,48.135098],[16.468021,48.135212],[16.468418,48.138607],[16.468861,48.138840],[16.469389,48.135372],[16.470623,48.135612],[16.472418,48.134613],[16.470625,48.133827],[16.469625,48.134254],[16.468231,48.134007],[16.467926,48.132610],[16.468380,48.131607],[16.466923,48.131310],[16.466627,48.130516],[16.465776,48.130608],[16.466417,48.133610],[16.464626,48.135113],[16.461796,48.132439],[16.459909,48.132324],[16.459625,48.131489],[16.454645,48.131607],[16.458626,48.131798],[16.459471,48.132763],[16.461100,48.133141],[16.462065,48.134174],[16.462370,48.135864],[16.463236,48.136604],[16.463625,48.140018]],"type":"LineString"},"type":"Feature"},{"properties":{},"geometry":{"coordinates":[16.356627,48.207607],"type":"Point"},"type":"Feature"},{"properties":{},"geometry":{"coordinates":[16.465759,48.134933],"type":"Point"},"type":"Feature"}],"type":"FeatureCollection"}
```

I **think** the fix for this wouldn't be too hard and is mostly addressed in `thor/isochrone_action` to create one `grid` per origin and store references to the grids in a container before sending the container off to the `tyr/isochrone_serializer`. 

Please correct me if I'm wrong about the approach. I don't have the best overview yet of Valhalla's code base, but I'd try to tackle the issue.

**Comment by nilsnolde** [comment]
Or alternatively maybe remove the multiple isochrones option from the config and also the code. Though it's a nice feature to have optionally to reduce HTTP load for batch isochrone analysis.

**Comment by dnesbitt61** [comment]
I have not looked at this in a while but the intent with multiple locations is to return a single isochrone that shows where travel from all locations can reach. It was not meant to be a batch isochrone generator.

**Comment by nilsnolde** [comment]
Ah ok, thanks for the clarification. That's pretty cool functionality. Then this might not be an issue after all then. I should've compared the output when I omit the first location: it's indeed different. I'll confirm visually in QGIS.

**Comment by nilsnolde** [comment]
Ok, I implemented it quickly in a QGIS plugin. Looks like both our assumptions are valid @dnesbitt61.

Based on your description I thought Valhalla would then return the isochrone of locations which are reachable by **all** input origins (basically a geometric difference of the individual isochrones around each origin). However, it just unions those isochrones. Also useful, but not quite as much IMO.

That's also not quite as accurate, e.g. this request 
```
{ "costing": "auto", "contours": [ { "time": 13 } ], "polygons": true, "id": 1, "locations": [ { "lon": 16.342851, "lat": 48.187564 }, { "lon": 16.324682, "lat": 48.119688 } ] }
```
aggregates the isochrones of the two locations to this (left two locations at once, right same locations separately):

![valhalla_2](https://user-images.githubusercontent.com/25637358/70626439-8517df00-1c35-11ea-8845-7b1500f98540.png)

They actually barely touch in the middle, yet that middle area is now entirely reachable. That's generally ok though I think.

If the isochrones don't touch though, it actually does only return the isochrone of one single location:

![valhalla_2](https://user-images.githubusercontent.com/25637358/70628125-9adad380-1c38-11ea-8c78-9247578fbc01.png)

Which location that is, seems to be random. I guess, the expected behavior would be to return a MultiPolygon with all isochrones or an error. What do you think?

**Comment by Gianfranco753** [comment]
Hi!

I think the problem could be in the file `src/tyr/isochrone_serializer.cc`, at line 68.
The `features->emplace_back(map({` (line 70-86) should be inside the `for (const auto& contour : feature) {` (starts on line 55) cicle, but it's just after.
This could cause the error where we only see the contours for one location.

I tried to change it myself to test it, but couldn't build the docker image with the change and really don't know any C++ programing.

Could someone test it?

**Comment by kevinkreiser** [comment]
I'm pretty sure this is the result of the `denoise` parameter (which i remember implementing). That parameter deletes outers and inners of a certain contour of the isochrone depending on how large the feature is compared to the biggest feature for that contour. So in @nilsnolde picture above where the middle was filled in, thats probably because the inner was so small it was assumed to be "noise" and could be removed. Similarly for the disjoint isochrones, one of the locations ends up being small enough to be classed as "noise". I would first experiment with setting the `denoise` parameter to something like 0 or a small value close to 0 like .1 or .2. from the docs:

> A floating point value from 0 to 1 (default of 1) which can be used to remove smaller contours. A value of 1 will only return the largest contour for a given time value. A value of 0.5 drops any contours that are less than half the area of the largest contour in the set of contours for that same time value.

**Comment by chrstnbwnkl** [comment]
Just tested @nilsnolde request with denoise=0 and the result looks fine: 

![image](https://github.com/user-attachments/assets/e1f9b0a9-0fd9-4a0c-845e-c4c7fa030bdf)
