### ISSUE TITLE
Error with python bindings

### ISSUE THREAD

**Issue by khamaileon** [valhalla/valhalla#2116]
I managed to run Valhalla on CentOS. The binary files work well but I have a problem with python bindings. Does anyone know where the error might come from or how to debug it?

```bash
>>> import valhalla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib64/libvalhalla.so.3: undefined symbol: _ZN5boost10filesystem6detail11unique_pathERKNS0_4pathEPNS_6system10error_codeE
```

**Comment by PureW** [comment]
The error suggests the valhalla library cannot find boost. Have you installed libboost on the system? The binary files requires some of the source dependencies listed under https://github.com/valhalla/valhalla#building-from-source

**Comment by khamaileon** [comment]
Yes boost 1.58.0 from source.
```bash
bash-4.2# ldconfig -p | grep boost
	libboost_system.so.1.58.0 (libc6,x86-64) => /usr/local/lib/libboost_system.so.1.58.0
	libboost_system.so (libc6,x86-64) => /usr/local/lib/libboost_system.so
	libboost_python3.so.1.58.0 (libc6,x86-64) => /usr/local/lib/libboost_python3.so.1.58.0
	libboost_python3.so (libc6,x86-64) => /usr/local/lib/libboost_python3.so
	libboost_python.so.1.58.0 (libc6,x86-64) => /usr/local/lib/libboost_python.so.1.58.0
	libboost_python.so (libc6,x86-64) => /usr/local/lib/libboost_python.so
	libboost_program_options.so.1.58.0 (libc6,x86-64) => /usr/local/lib/libboost_program_options.so.1.58.0
	libboost_program_options.so (libc6,x86-64) => /usr/local/lib/libboost_program_options.so
	libboost_filesystem.so.1.58.0 (libc6,x86-64) => /usr/local/lib/libboost_filesystem.so.1.58.0
	libboost_filesystem.so (libc6,x86-64) => /usr/local/lib/libboost_filesystem.so
```

**Comment by alichass** [comment]
Hi i seem to get the error:
 `ImportError: /usr/local/lib/python3.6/dist-packages/valhalla.so: undefined symbol: _ZN5boost10filesystem6detail11unique_pathERKNS0_4pathEPNS_6system10error_codeE` 

when I make with with these flags: 
`-DCMAKE_BUILD_TYPE=Release -DENABLE_DATA_TOOLS=Off -DENABLE_SERVICES=Off  -DENABLE_NODE_BINDINGS=OFF -DENABLE_PYTHON_BINDINGS=On -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so`

but not with: `DENABLE_DATA_TOOLS=On` (being the only difference)

**Comment by kevinkreiser** [comment]
It's because we don't link boost file system because we removed it from the project. It seems we forgot to replace an instance of boost file system with the valhalla equivalent. What version of the code are you building. We removed the call to unique path a while back.

**Comment by alichass** [comment]
3.0.9, how should i be building python bindings? i was basing my build off of this issue: https://github.com/valhalla/valhalla/issues/1325

**Comment by kevinkreiser** [comment]
This was probably a bug in 3.0.9 can you please try master

**Comment by alichass** [comment]
yay that fixed it, thanks so much <3

**Comment by kevinkreiser** [comment]
Fixed in master
