### ISSUE TITLE
Transit costing fails to find route

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#2126]
For me, transit costing doesn't find any routes. According to git bisect, it started from d186df780c86a73960a2aec7dc65c7a3f35d6c85 , which isn't very helpful, as its a large commit. Code before that can find transit routes with the same data.

Error that I get is an exception `TransitCost::EdgeCost only supports transit edges`. When testing the command-line tool, I get

```
install/bin/valhalla_run_route -j '{"locations": [{"lat": 59.433, "lon": 24.7323}, {"lat": 59.3980132, "lon": 24.660811715137616}], "costing": "transit", "costing_options": {"transit": {"use_bus": 0.5, "use_rail": 0.5, "use_transfers": 0.5}}, "directions_options": {"language": "en", "units": "kilometers"}}' --config valhalla.json.new
2019/12/21 18:20:23.764077 [ANALYTICS] locations_count::2
2019/12/21 18:20:23.764298 [INFO] routetype: transit
2019/12/21 18:20:23.831628 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
2019/12/21 18:20:23.832260 [INFO] Location Worker construction took 64 ms
2019/12/21 18:20:23.832301 [ANALYTICS] costing_type::transit
2019/12/21 18:20:23.832338 [ANALYTICS] total_location_distance::5.618011km
2019/12/21 18:20:24.017662 [INFO] Location Processing took 185 ms
2019/12/21 18:20:24.022586 [ERROR] trip_path not found
2019/12/21 18:20:24.022619 [INFO] Total time= 255 ms
2019/12/21 18:20:24.022721 [STATISTICS] 59.432999,24.732300,59.398014,24.660812,fail_no_route,0,255,0,0.000000,5.618011,0
```

Please let me know if there are any suspects to check.

**Comment by kevinkreiser** [comment]
the likely suspect will be changes to the costing interfaces i made to disallow use of transit only costing functions for non transit portions of routes and making the base class function for EdgeCost pure virtual. something in the code must be relying on default behavior from that base class function for example.

sorry for the late reply!

**Comment by rinigus** [comment]
Thanks for looking into it! (no wonder it takes longer to get replies at this time of the year). Let me know if there is something to test.
