### ISSUE TITLE
Ignore Trunk and Motorways in pedestrian routing

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#2127]
Hello guys,
Currently valhalla pedestrian costing allows trunk and motorway types, I want to limit these types to when there is not other options available. Is there any option available for it? I can change edgeCost function in pedestriancost to set the cost so high, but I want to know is it configurable with some option? or maybe by highway type.

Thanks

**Comment by dnesbitt61** [comment]
The pedestrian access flags are supposed to be set during the data import process based on country level rules. The pedestrian costing first and foremost looks at the pedestrian access flags in the directed edge to determine if an edge is allowed for a pedestrian route. Do you have examples where this is not as expected? It appears to work properly in US.

**Comment by safe-bug** [comment]
Thanks for the reply @dnesbitt61 . So you mean it should be handled by OSM tags in the data? I think many of the roads in my region don't have these tags (foot, sidewalk) and as you said that must be fixed.

**Comment by dnesbitt61** [comment]
Not exactly, what I mean is that the highway tag has default access per travel mode (rules can differ per country). These per country access rules are followed by setting pedestrian access to true or false during data import and Valhalla tile creation. Then the sif costing Allowed method will exclude any edges (road segments) without appropriate access. Per country access rules for each highway tag are specified here: https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions

**Comment by safe-bug** [comment]
Thanks @dnesbitt61
