### ISSUE TITLE
Running multiple instances of valhalla_service

### ISSUE THREAD

**Issue by lexeric** [valhalla/valhalla#2131]
Dear all,

I'm new to Valhalla. I have 2 set of OSM files and would like to start 2 instances of valhalla service under 2 ports, e.g. 8002 and 8003, I've edited the valhalla.json file to change the port in folder2.

When I run "valhalla_service valhalla.json 1" to start it, it returns "what(): Address already in use".

Please kindly advise if I could do that, thanks for your attention.

Best Regards,
Eric

**Comment by kevinkreiser** [comment]
if you arent married to having separate servers for each data set you can combine them into a single dataset. valhalla_build_tiles can take multiple osm files in a single run. or if the areas arent even close you can just dump all the tiles into the same directory if you created them with separate runs of valhalla_build_tiles.

if you must run two different servers you should check that you dont accidently have another one already running somewhere. have you tried ports other than 8002 and 8003. 8002 is the default so i wonder ifyou have a random server running via docker or something... additionally you need to be aware that the different parts of the system use IPC to send messages to various threads. these threads bind linux domain sockets and they must differ between the two servers. if you look through the config you'll see a lot of `ipc:///` specifiying the file location. they should be unique among the servers.
