### ISSUE TITLE
custom profile or methods costing

### ISSUE THREAD

**Issue by stefanocudini** [valhalla/valhalla#2134]
in reference to this part of the documentation written by @kevinkreiser 
https://valhalla.readthedocs.io/en/latest/sif/dynamic-costing/
and this great article:
https://www.mapzen.com/blog/dynamic-costing-via-sif/ by @dnesbitt61 

how can I extend these methods using the bindings in nodejs or python?

or how can I define my own profile in addition to those already present (pedrestian, auto, bicycle ..)

in the source tests I have not found references to this specific problem

Similar to issue #2020  but I need something more customizable, for example valuate additional openstreetmap tags...

**Comment by stefanocudini** [comment]
@dgearhart may be you know how

**Comment by kevinkreiser** [comment]
we do no allow for any custom costing via the bindings, whether it be node or python. those bindings are simply wrappers of high level apis into the c++ library. the c++ library is where you would need to make changes to support your own costing/custom profile. further we do not support arbitrary osm tags. when we create our tile data we normalize osm into our tile schema. your custom costing will need to make use of the properties we already support in our tile schema or you'll need to add not attribution from osm tags to the tile schema.

you can look at an example PR of how to define your own costing here: https://github.com/valhalla/valhalla/pull/1756/files

that one includes actually changes to the tile schema as well. as you can see its not trivial but its definitely possible to do depending on your use-case.
