### ISSUE TITLE
Get pedestrian specific instructions in OSRM mode

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#2135]
Hi
I'm trying to get walking directions from Valhalla with OSRM parser option, but OSRM instructions doesn't have specific directions (type, highway types) for pedestrian. For example Valhalla says "step into walkway" but OSRM just says "continue". Or for the overpasses OSRM creates "trun lef" and "trun right" instructions for using overpass steps but it should be "Step into overpass".
Do you have any solution for this?

**Comment by dgearhart** [comment]
@safe-bug Valhalla and OSRM-TI have different instruction strings.

**Comment by safe-bug** [comment]
@dgearhart Thanks for the reply, isn't it possible to have both of the instructions at the same request?

**Comment by dgearhart** [comment]
no - not for the same request

**Comment by safe-bug** [comment]
@dgearhart Thanks
