### ISSUE TITLE
Make run_route_scripts/batch.sh macos compatible

### ISSUE THREAD

**Issue by mandeepsandhu** [valhalla/valhalla#2139]
`run_route_scripts/batch.sh` in its current form does not work on macos/Darwin. It has the following issues:
1. Long options are not available in macos/Darwin distributions
2. Need an equivalent of `nproc` on macos/Darwin.
3. Newer bash syntax does not work on Mac's older bash version (`3.x`)
4. One `sed` command (`sed -i -e "s;$;|--config|${CONF};g" -e ...`) fails to run

1 & 2 can be fixed by installing `coreutils` package. 3 can be fixed by updating `bash` from *homebrew*. 4 will need a slight code-change.

Bonus:
This script is setting `set -o errrexit ...` at the beginning. This causes the error message when detecting `parallel` installation to be suppressed. This option should be moved further down after basic checks are done so that the error messages can be displayed to the user.

**Comment by PureW** [comment]
An alternative may be to have osx-users install GnuTools https://formulae.brew.sh/formula/binutils bridging most of the common discrepancies between two platforms. Since we don't test the bash scripts in CI, it's an uphill battle to try to guarantee the script behaviour.

On the bonus point, testing the parallel installation using

```
if [ which parallel2 &> /dev/null ]; then
...
```

works with `-set o errexit` and keeps all error checking in place.

**Comment by mandeepsandhu** [comment]
> An alternative may be to have osx-users install GnuTools https://formulae.brew.sh/formula/binutils bridging most of the common discrepancies between two platforms. Since we don't test the bash scripts in CI, it's an uphill battle to try to guarantee the script behaviour.

I agree, without having a platform to test, it'll be tough to keep scripts working across platforms. But I feel that supporting macOS is still going to be needed as a non-negligble number of Valhalla users are on it. I'll try my best to be a macOS tester :)

BTW, I installed `binutils`, but it doesn't come with gnu variants of `mkdir` & `cp`, 2 of the commands being used with long options.

What was the reason for using long-opts? Was it for readability? I'm thinking, the low hanging fruit here might be to refer to using short opts that work on macOS.
> 
> On the bonus point, testing the parallel installation using
> 
> ```
> if [ which parallel2 &> /dev/null ]; then
> ...
> ```
> 
> works with `-set o errexit` and keeps all error checking in place.

Sounds good!

**Comment by mandeepsandhu** [comment]
> 
> BTW, I installed `binutils`, but it doesn't come with gnu variants of `mkdir` & `cp`, 2 of the commands being used with long options.
> 
Sorry, I also need to install `coreutils` pkg.

**Comment by PureW** [comment]
> What was the reason for using long-opts? Was it for readability? I'm thinking, the low hanging fruit here might be to refer to using short opts that work on macOS.

Aye, readability. But long-opts are not the only difference, some commands simply differ between gnu and bsd versions so simply using short-opts is not going to work in all cases.

**Comment by mandeepsandhu** [comment]
> > What was the reason for using long-opts? Was it for readability? I'm thinking, the low hanging fruit here might be to refer to using short opts that work on macOS.
> 
> Aye, readability. But long-opts are not the only difference, some commands simply differ between gnu and bsd versions so using short-opts is not going to work in all cases.

Right, and I'm only suggesting it for this script. For others we might need a different approach.
