### ISSUE TITLE
Hi, I wanted to know how osm data is processed in Valhalla. Does Baldr, Midgard and Mjolnir reads the tiled/graph data or the osm.pbf data. Can You Please Provide a detailed explanation how valhalla interacts with pbf data and generated graph data from osm

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2142]

**Comment by PureW** [comment]
Take a look in the example on the frontpage: https://github.com/valhalla/valhalla#running

**Comment by asheesh1202** [comment]
My aim is not to use the Valhalla_service over a server but the cpp functions inside baldr and midgard built to extract information inside osm. The link shared does not help me how does midgard and baldr use pfb and graph files.

**Comment by asheesh1202** [comment]
An explanation will help me to achieve  intended functionality.
