### ISSUE TITLE
Does any one know how to build libspatialite in windows using Visual Studio. 

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2144]
I am failing to build Geos and Libspatialite libraries in windows. I could build libspatialite using  MinGW but that results in .a static library but I need static library in .lib format. I found that libspatialite comes with .configure file which generates make files and which can be used to build libspatialite. libspatialite also comes with Makefile.vc. So if I could use these files to build it on Visual Studio or any work around that will help me to generate .lib file will help me to proceed futher.
My windows build is almost near to completion. So soon I am planing to create a documentation for building Valhalla library on windows.

**Comment by PureW** [comment]
I'd suggest perusing Geos/libspatialite documentation and checking the CI setup for windows at https://github.com/valhalla/valhalla/blob/master/.azure-pipelines.yml

**Comment by asheesh1202** [comment]
Can I run this script on Windows??
If yes, Then how??

**Comment by PureW** [comment]
You can't run it directly, but CI goes through and executes the commands inside. You should be able to completely follow along and do what the script describes.

**Comment by asheesh1202** [comment]
It worked for me. Thanks
