### ISSUE TITLE
Hi, I wanted to know how osm data is processed in Valhalla. Does Baldr, Midgard and Mjolnir reads the tiled/graph data or the osm.pbf data. Can You Please Provide a detailed explanation how valhalla interacts with pbf data and generated graph data from osm 

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2145]

**Comment by asheesh1202** [comment]
Duplicate of #2142

**Comment by akuckartz** [comment]
@asheesh1202  Can you please avoid putting the whole content of your issue in the title? Thanks.

**Comment by kevinkreiser** [comment]
@asheesh1202 mjolnir reads osm pbf data and processes it into datastructures which are defined in baldr. this is a one time operation where you create graph (tiles).

after you have the graph tiles you can run a server or some of the test applications that actually do routing functions. the way that works is, baldr is responsible for providing read access to the graph (tile set) to the wider library. the loki part of the library looks in the graph to find edge candidates to start or and a route at or to start and isochrone at, etc. the thor part does the actual route, or isochrone or matrix (meili does map matching and thor wraps that part of the library). finally if you requested a route with narrative and directions odin will annotate the route path with that information.

please have a look inside the docs folder. i know its kind of sparse but it does at least have a little blerb about what each sub project of the library does as its primary function

**Comment by asheesh1202** [comment]
Where does midgard come into picture?

**Comment by kevinkreiser** [comment]
midgard is just a utility library for doing geometric computations.
