### ISSUE TITLE
Ci should publish service images on merge to master

### ISSUE THREAD

**Issue by purew** [valhalla/valhalla#2148]
In https://github.com/valhalla/valhalla/pull/2105 we moved to have CI build and publish updated base images for building Valhalla on merge to master.

Additionally, we would also like to build and publish the service images at this point. And tagged service images when CI builds from a git-tag.

References: https://github.com/valhalla/valhalla/issues/2067

**Comment by nilsnolde** [comment]
Not sure what service image refers to, but I assume it's the `run-` images right? I guess that's solved:) Of course feel free to re-open if that's not what you meant.
