### ISSUE TITLE
getting one way links

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2155]
Hi, 
Baldr is used to read graph tileset. I wanted to know how I can get various attributes of road network like one way form the tile set. I am able to read tile set and get nodes inside a tile at level 2.

**Comment by kevinkreiser** [comment]
please read over the code inside of `valhalla/baldr` specifically look at `graphtile.h` it holds all the data structures of the graph including edges, which have an access mask. using this mask you can find one ways by finding an edge who has auto access but whose opposing edge does not and vice versa. please note we have a directed graph.

**Comment by asheesh1202** [comment]
Which method do i use to get directed edges in the bounding box like for nodes loki comes with method 

 `nodes_in_box(const midgard::AABB2<midgard::PointLL>& bbox, baldr::GraphReader& reader)`

**Comment by asheesh1202** [comment]
found 

```
  /**
   * Get an iterable set of directed edges from a node in this tile
   * WARNING: this only returns edges in this tile, edges at this node on another level
   *          will not be returned by this method, node transitions must be used
   *
   * @param  idx  Index of the node within the current tile
   * @return returns an iterable collection of directed edges
   */
  midgard::iterable_t<const DirectedEdge> GetDirectedEdges(const size_t idx) const;
```

I hope this may work
