### ISSUE TITLE
Valhalla on Android

### ISSUE THREAD

**Issue by rwrx** [valhalla/valhalla#2157]
Hello, is it possible to compile and make Valhalla working on Android system with routing tiles located on device storage?

**Comment by kevinkreiser** [comment]
yes its possible but you'd want to write some code to wrap the c++ library calls in JNI so you can access it from your android application.

**Comment by carlos-mg89** [comment]
@kevinkreiser is there anyone who has published a wrapper for Android that could be used? Or are there instructions anywhere to create that wrapper?

I'm totally null with JNI :S

**Comment by carlos-mg89** [comment]
Thanks for the info @kevinkreiser. Will definitely take a look very soon, I'd love to test Valhalla for my Android app.

**Comment by rwrx** [comment]
@kevinkreiser thank you a lot for the info too.
