### ISSUE TITLE
Nodes in Directed Graph 

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2172]
In a directed graph nodes are start and end of an edge. Also edges in Valhalla Directed graph are the Ways in OSM containing various attributes of that way. 
If I see from OSM perspective, a way is collection of two or more nodes. From Valhalla, Is it possible to check which all intermediate nodes are present in a way while parsing a directed graph.

**Comment by asheesh1202** [comment]
Hi, Can someone please suggest way forwards on this question??

**Comment by dnesbitt61** [comment]
Valhalla does not store OSM nodes except those where OSM ways intersect or begin/end. All intermediate nodes are stored as the lat,lon "shape" with the EdgeInfo structure. However there are no OSM node Ids stored so you cannot refer back to OSM nodes.

**Comment by Sleepingwell** [comment]
See [this comment](https://github.com/valhalla/valhalla/issues/2083#issuecomment-886188371).
