### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by cosmin-mogos** [valhalla/valhalla#2177]
I'm looking into embedding libvalhalla into our service, can you please help me understand which components are thread safe and which are not?

My current understanding is that one graph reader can be shared among several threads but the others loki, thor, etc. are not thread safe, so for concurrency we need a pool of workers.

**Comment by mskurydin** [comment]
@cosmin-mogos , your understanding is correct. For workers like loki, thor, etc you need separate instances for different threads. You can share a single graph reader (but ensure you use global synchronized cache option for sharing in-memory tile cache between different workers).
