### ISSUE TITLE
Valhalla doesn't return alternative routes

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#2186]
Hello
I want to get alternative routes from Valhalla but it just returns 1 route. I set the "max_alternates" param in config to 2 and "alternates" param in request to 2, but result is the same. What should I do?

Thanks

**Comment by danpat** [comment]
You cannot *force* the algorithm to return alternatives - sometimes there are no good ones available.  Setting `max_alternatives` only sets the ceiling on how many *could* be returned, *if* reasonable alternatives can be found.

**Comment by kevinkreiser** [comment]
@safe-bug alternatives are not implemented in valhalla currently. we have the notion of alternatives in the code to support things like map matching where multiple probable matches can occur and specifically for osrm map matching where a break in the match makes a new route. basically, that parameter is a dummy parameter for now alternatives in the traditional sense are not supported
