### ISSUE TITLE
Valhalla Elevation data is not updated?

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#2200]
Hello
I'm using Elevation data according to the documents, but as said in this document (https://github.com/tilezen/joerd/blob/master/docs/data-sources.md) Valhalla Elvation resolution for most of the globe is 90meters (SRTM) but the updated version of SRTM data has 30 meters resolution. Is this data updated and the document is old?
And how can I convert custom elevation data to the format that Valhalla can read it?

Thanks

**Comment by nilsnolde** [comment]
I think you'd have to look at joerd itself. Not being maintained for multiple years doesn't mean it's not still running strong. We tried it recently and it works just fine in Docker (outside of Docker GDAL is a problem as always). I doubt Valhalla changed their elevation tiles.. ever. So, you can fork and extend joerd with an improved [SRTM source](https://github.com/tilezen/joerd/blob/master/joerd/source/srtm.py) to [output tiles](https://github.com/tilezen/joerd/blob/master/joerd/output/skadi.py) Valhalla expects. It's pretty clean code, so it'll be easy.

BTW, can you give a link to updated SRTM data pls? Or even better open this issue in joerd and leave a URL there. We might still decide to fork and maintain a new joerd at some point.

**Comment by dnesbitt61** [comment]
Valhalla elevation data is 30m resolution. Each 1 degree tile is 3601x3601 elevation postings which equals about 30m spacing in latitude.

**Comment by nvkelso** [comment]
The last data build for terrain was around 2 years ago... and switched to using Marble Cutter but the project tracking is still in the Joerd repo for legacy reasons (sorry for the confusion!). Each tile response should have headers saying what source is used.

**Comment by safe-bug** [comment]
Thank you guys!
