### ISSUE TITLE
Penalize Uturns at doubly digitized intersections

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#224]
(2016-01-25T14:12:15Z) @dnesbitt61 : originally created valhalla/thor#304

This approach should work: 1) Identify and mark left turns onto internal intersection edges (right turns in UK)
2) Add a flag to EdgeLabel for such cases.
3) In TransitionCost - add penalty if prior turn was marked as left onto internal and this transition is left from an internal edge.

NOTE: not seeing this happen much. Perhaps wait until we note some good examples.

**Comment by kevinkreiser** [comment]
in #3886 we have found another pathalogical doubly digitized uturn. the basic issue is that we need to know about name consistancy for N labels back. my thought is similar to daves:

1. when we expand onto an internal edge we crack open the edgeinfo of the predecessor edge (that isnt internal) and gets its nameinfo offset
2. we put this nameinfo offset into the edge label
3. while we keep expanding internal edges we simply propogate this nameinfo offset forward
4. as soon as we expand from an internal to a non internal we check if the nameinfo offsets match. if they do its a uturn if they dont its (propbably, caveats below) not a uturn

i know opening up the edgeinfo during path traversal is a sin but im hoping that if we only do it for those expansions transition to and from internal edges it will be so small as to be unnoticable. and by propogating the offset we can also solve the cases where there are multiple internal edges back to back.

anyway this is just an idea. as dave pointed out originally, its unclear as to the prevelence of this issue whther or not its worth it. one could certainly re-digitize the road network in some small number of these places (tag for the router) to avoid these issues but in other cases the router would indeed have to handle it (eg. the standard `H` and `#` style doubly digitized crossings)

**Comment by kevinkreiser** [comment]
closing this in favor of the discussion over in #3886 this issue specifically was fixed by adding code to detect doubly digitized uturns however that code finds some false positives
