### ISSUE TITLE
OSM way Id exceeds 32 bit maximum

### ISSUE THREAD

**Issue by toton6868** [valhalla/valhalla#2260]
I am working with custom pbf file of my road network. When I am trying to build tiles by `valhalla_build_tiles -c conf/valhalla.json roads.pbf` it is returning the following

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  OSM way Id exceeds 32 bit maximum
Aborted (core dumped)
```

What is the problem

**Comment by kevinkreiser** [comment]
@toton6868 at the moment we dont support way ids larger than 2^32 - 1. we'll probably working on a way around this limitation (which was one we introduced in valhalla 3.0) in the near-ish future. in the meantime you can work around this by renumbering your pbf using `osmium renumber`.
