### ISSUE TITLE
413 Client Error: Request Entity Too Large

### ISSUE THREAD

**Issue by JackCaster** [valhalla/valhalla#2265]
I am using Valhalla Map matching service via the GIS-OPS [docker image](https://github.com/gis-ops/docker-valhalla). 

I am using the service `trace_attributes` but I am getting the error `413 Client Error: Request Entity Too Large` for some large requests. I would like to increase the allowed server body size (see [here](https://craftcms.stackexchange.com/a/2330)) but I do not know where to find the Valhalla server settings. Would you be able to help?

**Comment by kevinkreiser** [comment]
If you are running in mulitiprocess mode then you will want to change the 6th argument of prime_httpd. If you are running with valhalla_service you need to change this https://github.com/valhalla/valhalla/blob/master/src/valhalla_service.cc#L77 by adding another argument to the server constructor. It's already there it just defaults to a small number of megabytes. Just add another number there which would be the number in bytes you want to allow

**Comment by JackCaster** [comment]
> If you are running in mulitiprocess mode then you will want to change the 6th argument of prime_httpd. If you are running with valhalla_service you need to change this https://github.com/valhalla/valhalla/blob/master/src/valhalla_service.cc#L77 by adding another argument to the server constructor. It's already there it just defaults to a small number of megabytes. Just add another number there which would be the number in bytes you want to allow

Thank you for the help. Let me check if I understood correctly. First, I need to add an argument at L77 in `valhalla_service.cc`. Then, I should add an argument to `prime_http`. Where I can find this function?

**Comment by kevinkreiser** [comment]
@JackCaster one or the other. if you are running with `valhalla_service`, which i would guess you are, then you just need to add a number of bytes at line 77 there to support a larger request size.
