### ISSUE TITLE
Auto_shorter as an dynamic option

### ISSUE THREAD

**Issue by TimMcCauley** [valhalla/valhalla#2281]
We are thinking about implementing the logic of `auto_shorter` as an option to pass in to Valhalla, basically something like `mode=shortest` vs. `mode=fastest` as other foss routers feature. Is this something you would support are there any pitfalls we should be aware about?

**Comment by kevinkreiser** [comment]
my question would be more are you sure

    "costing": "auto_shorter"

doesnt already fit your needs? i would shy away from expanding an already expansive API if we can avoid it.

**Comment by TimMcCauley** [comment]
Thanks @kevinkreiser - my bad for not thinking a little further - this will probably also work. Would you be ok if we add `hgv_shorter`, as well?

**Comment by kevinkreiser** [comment]
For the second one, i think a more consistant name would be `truck_shorter` unless im misunderstanding what you mean by HGV. For that one we actually have to do some work to make a new costing and apply similar logic as is done for `auto_shorter`. `auto_shorter` should already be supported
