### ISSUE TITLE
Tile Data Freshness - status/query

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#229]
(2016-01-25T17:19:51Z) @dnesbitt61 : originally created valhalla/mjolnir#364

we have the timing information in s3 and we could indeed drop a file in the chef recipe that restarts the service to tell what the freshness is. it could be queried in the api etc.

(2016-01-25T18:52:43Z) @kevinkreiser : Why not just open a tile and read it's header instead of doing something good with chef?

(2016-01-25T18:54:35Z) @kevinkreiser : Or are you looking for the process restate time? This is also available without chef changes

(2016-01-25T18:54:55Z) @kevinkreiser : PS typing on phones is infuriating

**Comment by kevinkreiser** [comment]
Status endpoint exists
