### ISSUE TITLE
Build and test failed in Linux

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2306]
build  and test cases are filing with the error:

`test/CMakeFiles/build_timezones.dir/build.make:60: recipe for target 'test/data/tz.sqlite' failed
make[3]: *** [test/data/tz.sqlite] Error 1
make[3]: *** Deleting file 'test/data/tz.sqlite'
CMakeFiles/Makefile2:4804: recipe for target 'test/CMakeFiles/build_timezones.dir/all' failed
make[2]: *** [test/CMakeFiles/build_timezones.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
`

**Comment by mattrjackson** [comment]
I ran into this yesterday. At least in my case it was because spatialite-tools wasn't installed on the system.

**Comment by kevinkreiser** [comment]
@mattrjackson is correct. you need to install a few things to get that to run, namely:

    curl, unzip, spatialite_tool, spatialite

we'll update the readme
