### ISSUE TITLE
Debug transit routing

### ISSUE THREAD

**Issue by realingo** [valhalla/valhalla#2308]
**Is there some way how to debug transit routing?** I would like to get route between 2 locations in Prague city center and I still get 

`{"error_code":440,"error":"Cannot reach destination - too far from a transit stop","status_code":400,"status":"Bad Request"}`

I imported data from transit.land for whole city and even set radius value in route API to 1500 meters but it returns still error 440. It works fine for pedestrian or auto routing but multimodal is problem.

**Comment by gknisely** [comment]
@realingo did you run `valhalla_convert_transit` and then point your valhalla config `transit_dir` to the transit tiles before running `valhalla_build_tiles`

**Comment by realingo** [comment]
@gknisely I run these commands:

`valhalla_build_transit valhalla.json http://transit.land 1000 transit "13.842,49.656951,14.921692,50.49692" A 4 o-u2fk-dopravnipodnikhlmprahyakciovaspolecnost`

then

`valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json --mjolnir-transit-dir /root/data/transit`

then

`valhalla_build_tiles -c valhalla.json czech-republic-latest.osm.pbf `

then I run valhalla with:

`valhalla_service valhalla.json`

The query I called was:
`{"locations":[{"lat":50.0673725,"lon":14.4016392}, {"lat":50.0444336,"lon":14.4487142}],"costing":"multimodal","radius":1000, "date_time":{"type":0}}`

I got this response to the query:
`{"error_code":440,"error":"Cannot reach destination - too far from a transit stop","status_code":400,"status":"Bad Request"}`

It seems that `valhalla_convert_transit` is part of `valhalla_build_transit` script.

**Comment by gknisely** [comment]
@realingo I am going to try this out at some point, but at first glance your feed id is wrong.  It should be `f-u2f-dpp` I believe.  You have the operator id `o-u2fk-dopravnipodnikhlmprahyakciovaspolecnost` set.

**Comment by realingo** [comment]
Thanks @gknisely - I tried it with suggested `f-u2f-dpp` but no success so far:

`valhalla_build_transit valhalla.json http://transit.land 1000 transit "13.842,49.656951,14.921692,50.49692" A 4 f-u2f-dpp`

Then I run `valhalla_build_tiles -c valhalla.json czech-republic-latest.osm.pbf`. It finished but there were some errors (mostly of this type: `EdgeLength= 0 < connection lengths: 21.570763,10.544075 when connecting to stop Jesenice`). Here is the full output of `valhalla_build_tiles` script
[out.txt](https://github.com/valhalla/valhalla/files/4463725/out.txt).

When I run this query:
`{"locations":[{"lat":50.0673725,"lon":14.4016392}, {"lat":50.0718614,"lon":14.4141111}],"costing":"multimodal"}` - valhalla returns:
`{"error_code":442,"error":"No path could be found for input","status_code":400,"status":"Bad Request"}`

This is what valhalla server outputs on this request:
`1 2020/04/10 23:48:55.856076 GET /route?json=%7B%22locations%22%3A%5B%7B%22lat%22%3A50.0673725%2C%22lon%22%3A14.4016392%7D%2C%20%7B%22lat%22%3A50.0718614%2C%22lon%22%3A14.4141111%7D%5D%2C%22costing%22%3A%22multimodal%22%7D HTTP/1.1
2020/04/10 23:48:55.856238 [INFO] Got Loki Request 1
2020/04/10 23:48:55.856372 [ANALYTICS] locations_count::2
2020/04/10 23:48:55.856401 [ANALYTICS] costing_type::multimodal
2020/04/10 23:48:55.856441 [ANALYTICS] total_location_distance::1.021748km
2020/04/10 23:48:55.863535 [INFO] Got Thor Request 1
2020/04/10 23:48:55.863645 [ANALYTICS] travel_mode::1
2020/04/10 23:48:55.863685 [ANALYTICS] 400::No path could be found for input
1 2020/04/10 23:48:55.863817 400 229
`

Does valhalla have some verbosity level flag for debugging?

**Comment by gknisely** [comment]
Transit routes need a date and time.  Did you build the tiles with a timezone db and did you try entering a date and time?  For example, `-j '{"locations":[{"lat":50.0673725,"lon":14.4016392},{"lat":50.0718614,"lon":14.4141111}],"costing":"multimodal","directions_options":{"units":"miles"},"date_time":{"type":1,"value":"2020-04-15T08:00"}}'`

**Comment by realingo** [comment]
@gknisely Yes, I built the timezone db according to this guide: https://valhalla.readthedocs.io/en/latest/mjolnir/getting_started_guide/

Server shows error when I run your query:
`root@vlad-test:~/data# valhalla_service valhalla.json 4
2020/04/11 08:50:11.098401 [INFO] Tile extract successfully loaded with tile count: 234
2020/04/11 08:50:11.098607 [WARN] (stat): /data/valhalla/traffic.tar No such file or directory
2020/04/11 08:50:11.098625 [WARN] Traffic tile extract could not be loaded
2020/04/11 08:50:11.141013 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
2020/04/11 08:50:11.141765 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
2020/04/11 08:50:11.141922 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
2020/04/11 08:50:11.145513 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
0 2020/04/11 08:50:41.033082 GET /route?json=%7B%22locations%22%3A%5B%7B%22lat%22%3A50.0673725%2C%22lon%22%3A14.4016392%7D%2C%7B%22lat%22%3A50.0718614%2C%22lon%22%3A14.4141111%7D%5D%2C%22costing%22%3A%22multimodal%22%2C%22directions_options%22%3A%7B%22units%22%3A%22miles%22%7D%2C%22date_time%22%3A%7B%22type%22%3A1%2C%22value%22%3A%222020-04-15T08%3A00%22%7D%7D HTTP/1.1
2020/04/11 08:50:41.033322 [INFO] Got Loki Request 0
2020/04/11 08:50:41.033460 [ANALYTICS] locations_count::2
2020/04/11 08:50:41.033490 [ANALYTICS] costing_type::multimodal
2020/04/11 08:50:41.033534 [ANALYTICS] total_location_distance::1.021748km
2020/04/11 08:50:41.041024 [INFO] Got Thor Request 0
2020/04/11 08:50:41.041142 [ANALYTICS] travel_mode::1
2020/04/11 08:50:41.052889 [ERROR] Could not get the timezone at the origin location
2020/04/11 08:50:41.062252 [ERROR] Could not get the timezone at the origin location
2020/04/11 08:50:41.062361 [ANALYTICS] 400::No path could be found for input
0 2020/04/11 08:50:41.062612 400 229`

Isn't it strange that it can't find timezone for the origin location?

But I have timezones.sqlite in valhalla_tiles directory (it has around 96 MB) and I had it there before I run `valhalla_build_tiles`.

This is my valhalla.json config:
[valhalla.json.txt](https://github.com/valhalla/valhalla/files/4464290/valhalla.json.txt)

**Comment by realingo** [comment]
@gknisely I've found the problem. After I built the tiles, I didn't pack them to tar file which is used by valhalla. After I did it, it started to work ;)

Some suggestions:

1/ Could valhalla print that it uses the tar file for data on start? And maybe also creation date of this file. I am beginner with this project and I originally thought that it uses tile directory instead.

2/ When I run query your query, it returns `400::TransitCost::EdgeCost only supports transit edges`. It seems related to  #https://github.com/valhalla/valhalla/issues/2126 . I went back to version 3.0.8 where it works without issues

3/ When I was downloading the transit data, I tried also this command:
`valhalla_build_transit valhalla.json http://transit.land 1000 transit "13.842,49.656951,14.921692,50.49692"` and it seems it ignored the bounding box parameter. The bounding box is for one region in czech republic but it showed it was downloading also some stations from Italy from transit.land.

4/ I couldn't find documentation for `valhalla_build_transit`  import level parameter. I tried number 4 because I saw it in some answers on internet but I am not sure what it is.

Big thanks for helping me to make it working.

**Comment by gknisely** [comment]
@realingo very weird.  tar file is checked first then the tiles directory.  So I have no idea how this would of fixed it. 

Yes all of these issues need to be addressed.  Unfortunately, the transit code needs some love and I have just not had any extra time.

**Comment by YashowardhanTripathi** [comment]
@realingo  I am facing same type of issue but i couldn't not able to find solution please if you have any idea please share.
Thank you

**Comment by realingo** [comment]
@YashowardhanTripathi Unfortunately not

**Comment by nilsnolde** [comment]
not expecting any transit to work atm
