### ISSUE TITLE
valhalla_service segfaults when running multimodal isochrone query

### ISSUE THREAD

**Issue by realingo** [valhalla/valhalla#2315]
`root@vlad-test:~/data# valhalla_service valhalla.json 1
2020/04/11 11:05:39.145666 [INFO] Tile extract successfully loaded with tile count: 256
2020/04/11 11:05:39.145753 [WARN] (stat): /data/valhalla/traffic.tar No such file or directory
2020/04/11 11:05:39.145762 [WARN] Traffic tile extract could not be loaded
2020/04/11 11:05:39.169839 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
0 2020/04/11 11:05:42.860121 GET /isochrone?json=%7B%22locations%22%3A%5B%7B%22lat%22%3A50.0673725%2C%22lon%22%3A14.4016392%7D%5D%2C%22costing%22%3A%22multimodal%22%2C%22contours%22%3A%5B%7B%22time%22%3A5%2C%22color%22%3A%22ff0000%22%7D%5D%2C%22date_time%22%3A%7B%22type%22%3A0%7D%7D HTTP/1.1
2020/04/11 11:05:42.860353 [INFO] Got Loki Request 0
2020/04/11 11:05:42.860501 [ANALYTICS] locations_count::1
2020/04/11 11:05:42.860538 [ANALYTICS] costing_type::multimodal
2020/04/11 11:05:42.860554 [ANALYTICS] max_location_distance::0.000000km
2020/04/11 11:05:42.924749 [INFO] Got Thor Request 0
2020/04/11 11:05:42.924831 [ANALYTICS] travel_mode::1
Segmentation fault (core dumped)
`

I tried to run valgrind to find more (output from Valgrind here 
[valgrind.txt](https://github.com/valhalla/valhalla/files/4464493/valgrind.txt).

Problem is probably here:
`==7698== Invalid read of size 8
==7698==    at 0x3C4454: valhalla::thor::Dijkstras::SetOriginLocationsMultiModal(valhalla::baldr::GraphReader&, google::protobuf::RepeatedPtrField<valhalla::Location>&, std::shared_ptr<valhalla::sif::DynamicCost> const&) (in /usr/local/bin/valhalla_service)` on current master and here on 3.0.8:
`==22036== Invalid read of size 8
==22036==    at 0x3A1BF9: valhalla::thor::Isochrone::SetOriginLocationsMM(valhalla::baldr::GraphReader&, google::protobuf::RepeatedPtrField<valhalla::Location>&, std::shared_ptr<valhalla::sif::DynamicCost> const&)`

Any idea how to fix it?

**Comment by realingo** [comment]
I tried to debug it and problem is in this function:

![image](https://user-images.githubusercontent.com/60293438/79046495-912aa200-7c11-11ea-9511-ca8ac75dad94.png). When I commented it, it runs then without segfault.

**Comment by nilsnolde** [comment]
will pop up again soon or not:)
