### ISSUE TITLE
Usage of valhalla_add_predicted_traffic

### ISSUE THREAD

**Issue by junior-yoda** [valhalla/valhalla#2327]
I couldn't find any related document for `valhalla_add_predicted_traffic`. I think it's still under develop but I'm not sure. as I understood it can modify graph speeds real time. Am I right?    
Please provide a brief explanation and sample for usage of this command.

**Comment by kevinkreiser** [comment]
It's still under development and it's not for real time speeds it's for historical speeds at data building time. The format is only documented in the code and frankly we're looking to use another format. Thinks are still influx there
