### ISSUE TITLE
Exclude some nodes for routing run time

### ISSUE THREAD

**Issue by junior-yoda** [valhalla/valhalla#2332]
How can I avoid routing from some OSM nodes? I found avoid_edges but I barely found documentation about it, I don't know is this what I want or not.

**Comment by dnesbitt61** [comment]
Valhalla does not store OSM Node Ids internally so the only way to avoid routing through a node is to use the `avoid_locations` JSON input which allows a list of Locations to avoid. If you set the lat,lon of the location to be the lat,lon of the node you wish to avoid it should avoid all incoming and outgoing edges from that node. The turn-by-turn API document describes this.

**Comment by junior-yoda** [comment]
Thanks for your help, could you please link the document ?

**Comment by dnesbitt61** [comment]
it is in the docs directory: docs/api/turn-by-turn/api-reference.md
