### ISSUE TITLE
Valhalla alternative routes

### ISSUE THREAD

**Issue by Eugene997** [valhalla/valhalla#2337]
Good day,
I want Valhalla to provide me with alternative routes from e.g point A to point B.

i understand that Valhalla does not provide alternative routes from #2186 . However i would like to inquire if it is possible to create different route requests instead, to emulate the creation of alternative routes. E.g to create 3 different routes from point A to point B.
So far, I tried to vary the options in routes such as maneuver_penalty, use_highways, heading, heading_tolerance...etc. But i had limited success, as sometimes Valhalla either gives error 442 or there is little to no difference in the routes. Any suggestions?

Also if you think that there is any other methods, please let me know. 
Thank you!

**Comment by kevinkreiser** [comment]
@Eugene997 i think you're already on the right track to this type of alternative route. Can you give more detail about the routes you are running and how you are changing the options? Also note that we have a costing type called `auto_shorter` which could give an interesting alternative to regular `auto`

**Comment by Eugene997** [comment]
Hi, thanks for the reply!
Currently, i am using Valhalla via routingpy. 

As you mentioned, i tried using auto_shorter option to see if there is any difference, while keeping all other options as default
e.g #1 (blue):
{"locations":[{"lat":1.4217252644408855,"lon":103.829212188720},{"lat":1.2794575543509612,"lon":103.83504867553711}],"costing":"auto","directions_options":{"units":"miles"}}

#2 (red):
{"locations":[{"lat":1.4217252644408855,"lon":103.829212188720},{"lat":1.2794575543509612,"lon":103.83504867553711}],"costing":"auto_shorter","directions_options":{"units":"miles"}}

![1](https://user-images.githubusercontent.com/64154215/80445835-ce986a80-8947-11ea-83ea-428274fa8f2c.png)
(i used the lines to represent the routes via folium's polyline function)


Next i tried playing with the minimum_reachability, while keeping the rest of the options as default
I kept route No.1 as a constant, and varied its copy's "minimum_reachability" values from default to 100,1000 respectively. But i got no changes to the route.
![2](https://user-images.githubusercontent.com/64154215/80446010-3cdd2d00-8948-11ea-8d71-b86a61705865.png)

Then i tried setting it to 1, upon which Valhalla returned error 442, status code 400.


Similarly, i did the same thing with "heading" and "heading_tolerance". First setting point A's "heading" option to values 0,90,180,270,360. 
For 90,180,270 options, Valhalla returned error 442, status code 400. 0,360, gave no difference too. I repeated all the heading options, with point b, which all got no difference. 

Then i repeated all the above, with the variable being "heading_tolerance". But i only either got error codes or zero difference in the route compiled.

Moving on, to "use_highways"option. I managed to get difference by setting its value to 0 (which means no highway)

![3](https://user-images.githubusercontent.com/64154215/80445968-1e773180-8948-11ea-89f0-a675f85ddb99.png)


If you require the source code, although it is written in python/routingpy, i will be happy to oblige.
Thanks!

**Comment by kevinkreiser** [comment]
closing this as it looks like you've reached the desired result. thanks for the information and good luck with your project!
