### ISSUE TITLE
Find minimum set of waypoints for a given route

### ISSUE THREAD

**Issue by rwrx** [valhalla/valhalla#2354]
Is it possible for a given route and costing option to get minimum set of waypoints which when entered into route finding (by locations json) will return this route? If it is not possible it will be hard and desired to add such kind of functionality? If so, I can try looking at it.

**Comment by kevinkreiser** [comment]
@rwrx the router is deterministic. if you send the same set of waypoints and same costing options you will get the same answer everytime. There are two caveats that can break this rule:

1. you got an updated osm file and made new data which will change the geometry and cost of some paths in the graph
2. you are running with real time traffic conditions and those are changing over time (but this is currently beta code and requires users to bring their own traffic data so is unlikely)

Can you tell me more about your use-case so I can understand what problem you are trying to solve here?

**Comment by rwrx** [comment]
Yes, my use case is an web application I am developing in which user will be able to import a route from gpx file, then it will send this route to valhalla and it will return minimum set of waypoints (if it will be possible for that route) and the user then will be able to move these waypoints around to modify this route. Basically the use case is editing routes that are matching road networks.

**Comment by dnesbitt61** [comment]
I am also interested in this use case. I was going to ask how the route was defined (seems it is a lat,lon path). Seems that the route (polyline) will first need to be map-matched and turned into a set of manuevers/steps. The points where these maneuvers occur could form an initial set of waypoints - but it is possible with costing settings that a route between the endpoints of a maneuver may not match the original path - which would then force insertion of waypoint(s) along the manuever to keep the route on the original path. Anyway, this would make an interesting and useful method I think and I'd be willing to consult / help.

**Comment by kevinkreiser** [comment]
haha cool. i had started previously writing a long reply covering this case but i didnt want to assume. so as @dnesbitt61 says we do have APIs for map matching which would be the first step. you can call `/trace_route` to do this. what this gives you back is a polyline representing the whole of your route as well as a bunch of other information for following the route. from there you could just store the encoded polyline (its compressed already) and call it a day, but this still might be too heavy for your needs.

the only option to reduce it even further is some algorithm for removing shape points that dont meaningfully affect the route returned. i would start by only using points that are on intersections in the road graph (this is like a poor-mans approach to open lr). our current valhalla flavored response does not contain information about which points are intersections in the graph but our osrm format response does (in its intersections object it has an index to the shape point that is at the intersection). taking just the intersections should reduce your number of points by a lot.

you could reduce this further by iteratively adding or removing intersections from your set. this will be expensive-sh. you could do something recursive like, say you had a route with 10 intersections. you could:

run the route using intersections 0 and 9 and if the path differs from the original route then
run the route using intersections 0 4 and 9 and if the path differs from 0 to 4 then
run the sub route from 0 to 2 to 4 and if the path differes from 0 to 2 then you need all points 0 1 and 2
if the path differed from 4 to 9 then
run the sub route from 4 to 7 to 9 and if it differed from 4 to 7 then...

you get the point. recursively add mid points until the route matches. this will leave you with the minimum set (or close to it) of waypoints you need to represent a particular route

**Comment by dnesbitt61** [comment]
a thought I had is to make this an option to trace_route (since presumably map-matching is step 1 in this process). The option would take each route in the match result and add the computed set of Locations needed to reconstruct the route using a route call with the costing options specified for trace_route. This could simplify the input and output serialization (would not need a new action).

**Comment by rwrx** [comment]
Hi, thank you a lot for your answers. I am sorry for this late answer. I think that simple map-matching will be great or this use case when I can extract from it just intersections. But also adding some option to `/trace_route` to just get intersections would be great.

**Comment by kevinkreiser** [comment]
@rwrx please look at the docs: https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md

in particular tell you the index of the lat,lon in the returned shape of the intersections:

    edge.begin_shape_index
    edge.end_shape_index

**Comment by rwrx** [comment]
@kevinkreiser Thank you a lot.

**Comment by systemed** [comment]
I solved this (using OSRM, but I guess the principle works elsewhere) with a matrix query along the lines of this suggestion: https://lists.openstreetmap.org/pipermail/osrm-talk/2016-June/001225.html

**Comment by rwrx** [comment]
@kevinkreiser thank you a lot I have solved it using `/trace_route` and

```
edge.begin_shape_index
edge.end_shape_index
```

as you suggested. I have implemented it in https://trackbook.online where you can create track by clicking on the map with routing mode set to "none" and then convert it to routing track (however this is available only after login in track settings) or by importing gpx file.

I will close this issue.
