### ISSUE TITLE
Failing docker build with new luajit

### ISSUE THREAD

**Issue by matus123** [valhalla/valhalla#2377]
Hello,

With switch from lua to LuaJit i can not build valhalla inside docker.

I tried to change dependencies according to https://github.com/valhalla/valhalla/commit/7298b4e18db7722bc81082fd2bc5f51687cbf851#diff-dfa97c92f281f08badcbf12c272a2529

Tried to leave both dependencies for lua and luajit with no success.

I am getting error with 
```
.
.
.
CMake Error in test/gurka/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


CMake Error in test/gurka/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


CMake Error in bench/meili/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


CMake Error in bench/meili/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


-- Generating done
-- Build files have been written to: /valhalla/build
CMake Warning:
  Manually-specified variables were not used by the project:

    PKG_CONFIG_PATH


The command '/bin/sh -c git clone ${VALHALLA_REPO} && (cd valhalla && git checkout master -b build && git submodule update --init --recursive && mkdir -p build && cd build && cmake .. -DPKG_CONFIG_PATH=/usr/local/lib/pkgconfig -DCMAKE_BUILD_TYPE=Release -DENABLE_NODE_BINDINGS=OFF && make -j2 install) && rm -rf /src' returned a non-zero code: 1
```

Dockerfile Gist:
https://gist.github.com/matus123/cf8e334d83448ef22cb51fbb6091dbce

**Comment by PureW** [comment]
Valhalla CI builds the project succesfully in Docker on every commit, see for example https://circleci.com/gh/valhalla/valhalla/23278?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

My guess is that you have some issue with include folders since it seems you are building under Ubuntu 18.04

**Comment by PureW** [comment]
FYI: You can build the valhalla binaries almost exactly like the CI setup in the official valhalla image and then copy the build binaries over to whichever system you need (as long as the new system has a libc that is not older than Ubuntu 16.04 which valhalla builds with).

That would likely be a much simpler approach than your current where you recreate the build env.

**Comment by matus123** [comment]
@PureW thank you, you are right... i will try the same setup you have in CI

i am closing this... it is just my issue.

Thanks again
