### ISSUE TITLE
How many GIGs of RAM do I need for US data?

### ISSUE THREAD

**Issue by agigao** [valhalla/valhalla#2417]
First of all thanks to all developers for this thrilling product!

I did setup Valhalla on my local machine, did receive a number of warnings/errors:
1 - 
```
valhalla_1  | 2020/06/09 12:52:48.927362 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for United States
```

2 - 
```
valhalla_1  | 2020/06/09 12:55:11.910609 [WARN] Max osmid exceeded bitset, resizing to fit id: 7404254399
```

Q - I wonder if 2nd error is relevant to RAM size, and how much RAM do I need for the US data (~ 7 Gigs of OSM data)?

Cheers,
Giga

**Comment by kevinkreiser** [comment]
The second warning is about how our estimate for the largest nodeid is too small. so yeah this is telling you its going to take more ram to fit bigger ids. the good news is, we are doing away with this approach entirely. please see the updates in #1827

**Comment by agigao** [comment]
@kevinkreiser, thanks for response!

Well, the bottom line of my questions is the following:

> Does it affect my routing results?

I use the service for calculating matrix `one to many`.

Thanks!

**Comment by kevinkreiser** [comment]
@agigao no it wont affect the results. so long as the process completes its fine. the first error is saying you dont have an admin database for the planet. if you want to properly create data you'll want to at least create the admin database using a planet extract to get all the borders.

**Comment by agigao** [comment]
@kevinkreiser Thank you!
