### ISSUE TITLE
Valhalla "leaks" dependence on robin-hood?

### ISSUE THREAD

**Issue by mwoehlke-kitware** [valhalla/valhalla#2445]
AFAICT, the only place RHH is used "publicly" is in [`thor/cost_matrix.h`](https://github.com/valhalla/valhalla/blob/0f160fdfe8c16f7ca5508445bf09fdef8ecaa073/valhalla/thor/costmatrix.h#L161)... and it's not a public member.

This seems to be unnecessarily leaking an implementation detail and making it unnecessarily impossible for external consumers to use Valhalla without also dragging in a dependency on RHH.

Would it be feasible to "hide" this dependency in some manner, possibly by using [PIMPL](https://en.wikipedia.org/wiki/Opaque_pointer) on this class?

**Comment by mwoehlke-kitware** [comment]
In fact, is Valhalla even *usable* by external consumers in its current state? It looks like the RHH headers are never installed, which would prevent any external consumers from being able to include Valhalla's headers.

(Please don't take this as an accusation. This is a "that's odd, did I miss something?" question.)

**Comment by kevinkreiser** [comment]
@mwoehlke-kitware yes we have an in progress pr that was working on handling this but havent gotten anywhere with it recently: #2192

**Comment by kevinkreiser** [comment]
oh and also yes. if you want to make a pr to hide this dep in the implementation please feel free to do so. using a pimpl will also be required in the idtable change that just merged. if you have time to tackle this we would be very grateful

**Comment by mwoehlke-kitware** [comment]
> yes we have an in progress pr that was working on handling this but havent gotten anywhere with it recently: #2192

Ah, interesting... I'm possibly going to run into that. For now I'm working on addressing #2440, so it hasn't "bit me" yet.

> if you want to make a pr to hide this dep in the implementation please feel free to do so. using a pimpl will also be required in the idtable change that just merged.

I'm still waiting on permission to actually publish changes :cry:, hopefully that's going to come through soon. (My previous PR doesn't count; needing permission to remove six characters to apply an obvious fix for a warning is ludicrous :wink:.) But, yeah, hoping I'll be able to PR something. I opened this largely a) because IIRC you like for PRs to have associated Issues, and b) to inquire if the suggested approach is reasonable.

I think `idtable.h` is actually okay; I looked at it, and AFAICT it isn't used externally. (Well, not yet, but for now I'm content to put that in the "burn that bridge when we get to it" list. Especially since a "fix" there is much more problematic, as the whole class is inline.)

**Comment by kevinkreiser** [comment]
@mwoehlke-kitware one solution to the idtable one is to move its implmenetation to pbfadminparser.cc and hide it completely. its the only place its used from.

**Comment by mwoehlke-kitware** [comment]
> one solution to the idtable one is to move its implmenetation to pbfadminparser.cc and hide it completely. its the only place its used from.

```
$ git grep idtable.h
src/mjolnir/pbfadminparser.cc:6:#include "mjolnir/idtable.h"
src/mjolnir/pbfgraphparser.cc:6:#include "mjolnir/idtable.h"
test/idtable.cc:1:#include "mjolnir/idtable.h"
```

...so I don't think that will work. Maybe it can move to `src` so it is a private header? There is also `src/mjolnir/statistics.h`, so I guess there is precedent for doing such a thing?

**Comment by kevinkreiser** [comment]
@mwoehlke-kitware even though its include in pbfgraphparser.cc it is not used. that was something we should have removed but missed in #2422
