### ISSUE TITLE
Boost::python not found

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2447]
Really low priority (for me ;)), but maybe someone has a quick fix off the top of his mind:

Using VS cmake (v3.17.20032601-MSVC_2), boost v1.73 and `ENABLE_PYTHON_BINDINGS=ON` I get a `Boost::python not found`. I tried to dig around a little and only came up with a [milestone for cmake 3.11](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1865), talking about changes in boost v1.67 regarding the naming convention for python libs (I think, it's a pretty confusing conversation)..

So, I wonder if the names in
https://github.com/valhalla/valhalla/blob/0f160fdfe8c16f7ca5508445bf09fdef8ecaa073/src/bindings/python/CMakeLists.txt#L5-L8 are really catching all distros' lib names? 

EDIT: I should also mention that
- python 3.7 is the system python which was successfully found by cmake
- boost-python 1.73 is installed

**Comment by kevinkreiser** [comment]
great question, i think to answer it you should try to figure out what macros come out of the lines above where you linked:

```
find_package(PythonInterp)
find_package(PythonLibs)
```

when im doing something like that i will throw something like this:

```
get_cmake_property(_variableNames VARIABLES)
list (SORT _variableNames)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
```

in right after the `find_package` calls above and then see what cmake prints out. maybe you'll find that it hasnt defined these or that they have different names.

**Comment by nilsnolde** [comment]
Thanks @kevinkreiser , cmake isn't as confusing as I'd have thought. The output doesn't even include a `_Boost_PYTHON*_HEADERS` variable, but several `Boost_PYTHON_*` variables (note the missing `_`):

```
1> [CMake] -- Boost_PYTHON-PY37_LIBRARY_DEBUG=Boost_PYTHON-PY37_LIBRARY_DEBUG-NOTFOUND
1> [CMake] -- Boost_PYTHON-PY37_LIBRARY_RELEASE=Boost_PYTHON-PY37_LIBRARY_RELEASE-NOTFOUND
1> [CMake] -- Boost_PYTHON37_LIBRARY_DEBUG=Boost_PYTHON37_LIBRARY_DEBUG-NOTFOUND
1> [CMake] -- Boost_PYTHON37_LIBRARY_RELEASE=Boost_PYTHON37_LIBRARY_RELEASE-NOTFOUND
1> [CMake] -- Boost_PYTHON3_LIBRARY_DEBUG=Boost_PYTHON3_LIBRARY_DEBUG-NOTFOUND
1> [CMake] -- Boost_PYTHON3_LIBRARY_RELEASE=Boost_PYTHON3_LIBRARY_RELEASE-NOT
```

So, boost didn't find my python? I feel smth is wrong is my boost installation.. I used `vcpkg` to install the needed 1.73. libraries and somehow it all points to `boost-program-options`, e.g. `Boost_LIBRARIES=C:/Users/nilsnolde/Documents/dev/vcpkg/installed/x64-windows/lib/boost_program_options-vc140-mt.lib`.. Shouldn't that point to many more boost libs?

**Comment by nilsnolde** [comment]
actually even cmake is warning me:

```
1> [CMake] CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
1> [CMake]   New Boost version may have incorrect or missing dependencies and imported
1> [CMake]   targets
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
```

I guess I'll try 1.72...

**Comment by nilsnolde** [comment]
Luckily nothing to do with boost. When I installed Python 3.8 and set the right flags for cmake for all Python flags, it worked.
