### ISSUE TITLE
Inputting real time data to Valhalla 

### ISSUE THREAD

**Issue by Eugene997** [valhalla/valhalla#2448]
Good day, i would like to ask if there is any way to input real time data to Valhalla? 

For example, if there is changes to a road's direction, is it possible to reflect it to Valhalla for consideration in its routing?
Or, if there is changes to a road's conditions e.g an accident, is there a way to input the data to Valhalla and subsequently its calculated ETA?

Thanks!

**Comment by kevinkreiser** [comment]
@Eugene997 yes we are still making small changes to its structure but we do support it. the way it works is every edge in the regular graph tiles is given a 64bit value (which is a bit packed struct): https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/traffictile.h

the code expects one big tar file, which we memory map, of these traffic tile structs. the order of the traffictiles in the tar is the same as the graphtiles in graph tar. the order of the edges within the graph and traffictiles is also the same. if you want to close an edge you must modify the appropriate 64bit struct in the tar file accordingly.

the modification of the tar file is something you must do on your own. we will not attempt to standardize this process. instead we leave this up to the developer who will know his/her particular situation/deployment and dependencies. enjoy!

**Comment by Eugene997** [comment]
Alright, thanks for the info!
