### ISSUE TITLE
"make check" fails gurka_instructions_named_roundabout on Ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by dweekly** [valhalla/valhalla#2465]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

$ make check
[  0%] Built target gtest
[  1%] Built target valhalla-midgard
[  4%] Built target valhalla-proto
[ 12%] Built target valhalla-baldr
[ 17%] Built target valhalla-mjolnir
[ 17%] Built target valhalla-skadi
[ 18%] Built target valhalla-sif
[ 21%] Built target valhalla-loki
[ 22%] Built target valhalla-meili
[ 23%] Built target valhalla-odin
[ 26%] Built target valhalla-thor
[ 28%] Built target valhalla-tyr
[ 28%] Built target valhalla
[ 28%] Built target build_timezones
[ 30%] Built target gmock
[ 30%] Built target gtest_main
[ 30%] Linking CXX executable gurka_loops
[ 30%] Built target gurka_loops
[ 30%] Generating gurka_loops.log
[PASS] gurka_loops
[ 30%] Built target run-gurka_loops
[ 30%] Linking CXX executable gurka_use_direction_on_ways
[ 30%] Built target gurka_use_direction_on_ways
[ 31%] Generating gurka_use_direction_on_ways.log
[PASS] gurka_use_direction_on_ways
[ 31%] Built target run-gurka_use_direction_on_ways
[ 31%] Linking CXX executable gurka_traffic
[ 32%] Built target gurka_traffic
[ 32%] Generating gurka_traffic.log
[PASS] gurka_traffic
[ 32%] Built target run-gurka_traffic
[ 32%] Linking CXX executable gurka_simple_restrictions
[ 33%] Built target gurka_simple_restrictions
[ 33%] Generating gurka_simple_restrictions.log
[PASS] gurka_simple_restrictions
[ 33%] Built target run-gurka_simple_restrictions
[ 33%] Linking CXX executable gurka_maxspeed
[ 33%] Built target gurka_maxspeed
[ 33%] Generating gurka_maxspeed.log
[PASS] gurka_maxspeed
[ 33%] Built target run-gurka_maxspeed
[ 33%] Linking CXX executable gurka_time_tracking
[ 33%] Built target gurka_time_tracking
[ 33%] Generating gurka_time_tracking.log
[PASS] gurka_time_tracking
[ 33%] Built target run-gurka_time_tracking
[ 33%] Linking CXX executable gurka_mtb_access
[ 34%] Built target gurka_mtb_access
[ 34%] Generating gurka_mtb_access.log
[PASS] gurka_mtb_access
[ 34%] Built target run-gurka_mtb_access
[ 34%] Linking CXX executable gurka_match
[ 35%] Built target gurka_match
[ 35%] Generating gurka_match.log
[PASS] gurka_match
[ 35%] Built target run-gurka_match
[ 35%] Linking CXX executable gurka_instructions_merge_toward
[ 35%] Built target gurka_instructions_merge_toward
[ 35%] Generating gurka_instructions_merge_toward.log
[PASS] gurka_instructions_merge_toward
[ 35%] Built target run-gurka_instructions_merge_toward
[ 35%] Linking CXX executable gurka_trimming
[ 35%] Built target gurka_trimming
[ 35%] Generating gurka_trimming.log
[PASS] gurka_trimming
[ 35%] Built target run-gurka_trimming
[ 35%] Linking CXX executable gurka_accessibility
[ 35%] Built target gurka_accessibility
[ 36%] Generating gurka_accessibility.log
[PASS] gurka_accessibility
[ 36%] Built target run-gurka_accessibility
[ 36%] Linking CXX executable gurka_search_filter
[ 36%] Built target gurka_search_filter
[ 37%] Generating gurka_search_filter.log
[PASS] gurka_search_filter
[ 37%] Built target run-gurka_search_filter
[ 38%] Linking CXX executable gurka_64bit_wayid
[ 38%] Built target gurka_64bit_wayid
[ 38%] Generating gurka_64bit_wayid.log
[PASS] gurka_64bit_wayid
[ 38%] Built target run-gurka_64bit_wayid
[ 38%] Linking CXX executable gurka_instructions_ferry_toward
[ 38%] Built target gurka_instructions_ferry_toward
[ 38%] Generating gurka_instructions_ferry_toward.log
[PASS] gurka_instructions_ferry_toward
[ 38%] Built target run-gurka_instructions_ferry_toward
[ 38%] Linking CXX executable gurka_guidance_views
[ 40%] Built target gurka_guidance_views
[ 40%] Generating gurka_guidance_views.log
[PASS] gurka_guidance_views
[ 40%] Built target run-gurka_guidance_views
[ 41%] Linking CXX executable gurka_turns
[ 41%] Built target gurka_turns
[ 41%] Generating gurka_turns.log
[PASS] gurka_turns
[ 41%] Built target run-gurka_turns
[ 41%] Linking CXX executable gurka_instructions_turn_toward
[ 42%] Built target gurka_instructions_turn_toward
[ 42%] Generating gurka_instructions_turn_toward.log
[PASS] gurka_instructions_turn_toward
[ 42%] Built target run-gurka_instructions_turn_toward
[ 42%] Linking CXX executable gurka_instructions_named_roundabout
[ 42%] Built target gurka_instructions_named_roundabout
[ 42%] Generating gurka_instructions_named_roundabout.log
[FAIL] gurka_instructions_named_roundabout
Running main() from /home/dew/valhalla/third_party/googletest/googletest/src/gtest_main.cc
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from InstructionsNamedRoundabout
[          ] generating map PBF at test/data/gurka_named_roundabouts/map.pbf
[          ] building tiles in test/data/gurka_named_roundabouts
[ RUN      ] InstructionsNamedRoundabout.RoundaboutEnterOnly
[          ] Routing with mjolnir.tile_dir = test/data/gurka_named_roundabouts with waypoints A -> E with costing auto
[          ] Valhalla request is: {"locations":[{"lon":5.107937335968018,"lat":52.08512496948242},{"lon":5.114225387573242,"lat":52.08512496948242}],"costing":"auto","costing_options":{"auto":{"speed_types":["freeflow","constrained","predicted"]}}}
[       OK ] InstructionsNamedRoundabout.RoundaboutEnterOnly (112 ms)
[ RUN      ] InstructionsNamedRoundabout.RoundaboutOrdinalOnly
[          ] Routing with mjolnir.tile_dir = test/data/gurka_named_roundabouts with waypoints A -> I with costing auto
[          ] Valhalla request is: {"locations":[{"lon":5.107937335968018,"lat":52.08512496948242},{"lon":5.112428665161133,"lat":52.08871841430664}],"costing":"auto","costing_options":{"auto":{"speed_types":["freeflow","constrained","predicted"]}}}
/home/dew/valhalla/test/gurka/gurka.h:895: Failure
Expected equality of these values:
  maneuver.text_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit."
  expected_text_instruction
    Which is: "Enter Dupont Circle and take the 3rd exit."
/home/dew/valhalla/test/gurka/gurka.h:896: Failure
Expected equality of these values:
  maneuver.verbal_transition_alert_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit."
  expected_verbal_transition_alert_instruction
    Which is: "Enter Dupont Circle and take the 3rd exit."
/home/dew/valhalla/test/gurka/gurka.h:898: Failure
Expected equality of these values:
  maneuver.verbal_pre_transition_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit."
  expected_verbal_pre_transition_instruction
    Which is: "Enter Dupont Circle and take the 3rd exit."
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutOrdinalOnly (65 ms)
[ RUN      ] InstructionsNamedRoundabout.RoundaboutOntoStreetName
[          ] Routing with mjolnir.tile_dir = test/data/gurka_named_roundabouts with waypoints A -> D with costing auto
[          ] Valhalla request is: {"locations":[{"lon":5.107937335968018,"lat":52.08512496948242},{"lon":5.112428665161133,"lat":52.0815315246582}],"costing":"auto","costing_options":{"auto":{"speed_types":["freeflow","constrained","predicted"]}}}
/home/dew/valhalla/test/gurka/gurka.h:895: Failure
Expected equality of these values:
  maneuver.text_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit onto Homestead Lane."
  expected_text_instruction
    Which is: "Enter Dupont Circle and take the 1st exit onto Homestead Lane."
/home/dew/valhalla/test/gurka/gurka.h:896: Failure
Expected equality of these values:
  maneuver.verbal_transition_alert_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit onto Homestead Lane."
  expected_verbal_transition_alert_instruction
    Which is: "Enter Dupont Circle and take the 1st exit onto Homestead Lane."
/home/dew/valhalla/test/gurka/gurka.h:898: Failure
Expected equality of these values:
  maneuver.verbal_pre_transition_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit onto Homestead Lane."
  expected_verbal_pre_transition_instruction
    Which is: "Enter Dupont Circle and take the 1st exit onto Homestead Lane."
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutOntoStreetName (66 ms)
[ RUN      ] InstructionsNamedRoundabout.RoundaboutOntoBeginStreetName
[          ] Routing with mjolnir.tile_dir = test/data/gurka_named_roundabouts with waypoints A -> G with costing auto
[          ] Valhalla request is: {"locations":[{"lon":5.107937335968018,"lat":52.08512496948242},{"lon":5.118717193603516,"lat":52.08512496948242}],"costing":"auto","costing_options":{"auto":{"speed_types":["freeflow","constrained","predicted"]}}}
[       OK ] InstructionsNamedRoundabout.RoundaboutOntoBeginStreetName (65 ms)
[ RUN      ] InstructionsNamedRoundabout.RoundaboutToward
[          ] Routing with mjolnir.tile_dir = test/data/gurka_named_roundabouts with waypoints I -> A with costing auto
[          ] Valhalla request is: {"locations":[{"lon":5.112428665161133,"lat":52.08871841430664},{"lon":5.107937335968018,"lat":52.08512496948242}],"costing":"auto","costing_options":{"auto":{"speed_types":["freeflow","constrained","predicted"]}}}
/home/dew/valhalla/test/gurka/gurka.h:895: Failure
Expected equality of these values:
  maneuver.text_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit toward A 95/B 2/M\xC3\xBCnchen/K\xC3\xBCrten."
    As Text: "Enter Dupont Circle and take the 2nd exit toward A 95/B 2/München/Kürten."
  expected_text_instruction
    Which is: "Enter Dupont Circle and take the 1st exit toward A 95/B 2/M\xC3\xBCnchen/K\xC3\xBCrten."
    As Text: "Enter Dupont Circle and take the 1st exit toward A 95/B 2/München/Kürten."
/home/dew/valhalla/test/gurka/gurka.h:896: Failure
Expected equality of these values:
  maneuver.verbal_transition_alert_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit toward A 95."
  expected_verbal_transition_alert_instruction
    Which is: "Enter Dupont Circle and take the 1st exit toward A 95."
/home/dew/valhalla/test/gurka/gurka.h:898: Failure
Expected equality of these values:
  maneuver.verbal_pre_transition_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit toward A 95, M\xC3\xBCnchen."
    As Text: "Enter Dupont Circle and take the 2nd exit toward A 95, München."
  expected_verbal_pre_transition_instruction
    Which is: "Enter Dupont Circle and take the 1st exit toward A 95, M\xC3\xBCnchen."
    As Text: "Enter Dupont Circle and take the 1st exit toward A 95, München."
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutToward (66 ms)
[ RUN      ] InstructionsNamedRoundabout.RoundaboutExitSuppressed
/home/dew/valhalla/test/gurka/gurka.h:895: Failure
Expected equality of these values:
  maneuver.text_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit."
  expected_text_instruction
    Which is: "Enter Dupont Circle and take the 3rd exit."
/home/dew/valhalla/test/gurka/gurka.h:896: Failure
Expected equality of these values:
  maneuver.verbal_transition_alert_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit."
  expected_verbal_transition_alert_instruction
    Which is: "Enter Dupont Circle and take the 3rd exit."
/home/dew/valhalla/test/gurka/gurka.h:898: Failure
Expected equality of these values:
  maneuver.verbal_pre_transition_instruction()
    Which is: "Enter Dupont Circle and take the 2nd exit."
  expected_verbal_pre_transition_instruction
    Which is: "Enter Dupont Circle and take the 3rd exit."
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutExitSuppressed (66 ms)
[----------] 6 tests from InstructionsNamedRoundabout (440 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test suite ran. (663 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutOrdinalOnly
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutOntoStreetName
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutToward
[  FAILED  ] InstructionsNamedRoundabout.RoundaboutExitSuppressed

 4 FAILED TESTS
make[3]: *** [test/gurka/CMakeFiles/run-gurka_instructions_named_roundabout.dir/build.make:61: test/gurka/gurka_instructions_named_roundabout.log] Error 1
make[3]: *** Deleting file 'test/gurka/gurka_instructions_named_roundabout.log'
make[2]: *** [CMakeFiles/Makefile2:10436: test/gurka/CMakeFiles/run-gurka_instructions_named_roundabout.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:5442: test/CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:2188: check] Error 2

**Comment by kevinkreiser** [comment]
@dweekly what `cmake` command did you run. i am also on ubuntu 20.04 and cannot reproduce this without a little more info.

**Comment by dweekly** [comment]
My cmake command was: `cmake .. -DCMAKE_BUILD_TYPE=Release` followed by `make -j6`. Happy to share any further details that might be helpful.
