### ISSUE TITLE
Edges leaving tiles

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2466]
Hello , 
I want to know how edges that leave tiles are stored in valhalla tiles. And how different edge cases are handled for edges leaving tiles. 
E.g. if a edge  leaves a tile then its end node is present in another tile. However what will happen if an edge has start and end node both in the same time but edge crosses (passes through) 2nd tile due to its geometrical shape. How edge will be treated for this specific usecase.

**Comment by kevinkreiser** [comment]
it depends on what scenario you are talking about. as you already mentioned, it will work the same as any other edge. its end node will be wherever it is whether that is the same tile or a different one than its begin node (and its tile). if the geometry crosses other tiles then the spatial index will reflect this and its edge id will be intered into the "bin" of the tiles it intersects.

maybe you can ask a more specific question, particularly around what you mean when you said "will be treated". it seems like you might have something very specific in mind.

**Comment by asheesh1202** [comment]
1) Can we detect, start and end node of the edge is in first tile and part of it is present in 2nd tile due to its geometry? 
2) Will the edge be present n both the tiles or  only on tile?

**Comment by kevinkreiser** [comment]
1. Yes, most easily by doing intersection with the geometry or also by looking at the bins (spatial index) nearby. There is no higher level function to do this for you but there is also no real good reason (yet) to provide this functionality
2. Edges are never duplicated they appear the the tile where they originate(at their begin node)
