### ISSUE TITLE
Japanese translations have unnecessarily spacing between letters

### ISSUE THREAD

**Issue by tsuz** [valhalla/valhalla#2467]
## What

After running Valhalla, there is an unnecessary spacing between characters which makes it hard to read, given that we don't use spacing between the characters in Japanese.

 ![unnamed](https://user-images.githubusercontent.com/6927131/87268433-4f0d4700-c505-11ea-9bb1-fcbcca10716f.png)

After checking Transifex and the [PR diff](https://github.com/valhalla/valhalla/pull/2432/files#diff-ee91550c5d6cf3dac633f2e03c618b37R40), this seems to be the case. 

![Screen Shot 2020-07-13 at 12 22 30](https://user-images.githubusercontent.com/6927131/87268575-b4f9ce80-c505-11ea-9b2c-92a2734128d1.png)

## Action Items

- I will go through and fix as much as I can. 
- I'd also like to understand how it got to this state so that we can prevent this in the future

**Comment by danpaz** [comment]
@tsuz yeah, I've noticed the spacing around tokens in Transifex is too narrow to easily see these whitespaces. Let me know when you've updated in Transifex and we can open a PR. Alternatively you can PR the changes in the [ja-JP.json source file](https://github.com/valhalla/valhalla/blob/master/locales/ja-JP.json) and we can upload that to Transifex.

**Comment by tsuz** [comment]
@danpaz I see. The extra spacing is detrimental for CJK languages at least. I've updated this on Transifex for Japanese.
