### ISSUE TITLE
Windows Builds are Broken

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#2501]
At the moment we cant build windows because we cant install the zlib dependency. This seems to be happening because of: https://github.com/microsoft/vcpkg/issues/12606

It seems that we can tell vcpkg to lock to a specific version to avoid the currently broken dependency. cc @mloskot @mattrjackson @gknisely

**Comment by mloskot** [comment]
@kevinkreiser Yes, some sort of `git reset --hard`  will be needed inside vcpkg cloned repo to restore last known working state. I'm not sure if I'll be able to look into that this week as I'm travelling.
