### ISSUE TITLE
Response time increases so much corresponding to distance increment

### ISSUE THREAD

**Issue by junior-yoda** [valhalla/valhalla#2546]
I launched `valhalla_service`, For routes inside a town response time seems promising but for some long routes response time grows so fast and so much which is not convenient for production service. The response time increment is different for different costings. I found that for `Bike` (like you can see in the logs)  the distance over 1000 km approximately gets a response time over 5 sec. But for `auto` costing you need to test it for a route in planet scale. For example from Asia to Europe and you see a really long response time (tag 3.0.8 is used).
Logs :

```
11 2020/08/19 15:33:12.029415 GET /route?json={%22locations%22:[{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:37.71859032558816,%22lng%22:46.142578125},%22_initHooksCalled%22:true,%22lat%22:37.71859032558816,%22lon%22:46.142578125},{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:26.902476886279832,%22lng%22:60.55664062499999},%22_initHooksCalled%22:true,%22lat%22:26.902476886279832,%22lon%22:60.55664062499999}],%22costing%22:%22**bicycle**%22,%22directions_options%22:{%22language%22:%22en-US%22}}&access_token= HTTP/1.1
2020/08/19 15:33:12.029607 [INFO] Got Loki Request 11
2020/08/19 15:33:12.029849 [ANALYTICS] locations_count::2
2020/08/19 15:33:12.029912 [ANALYTICS] costing_type::bicycle
2020/08/19 15:33:12.029950 [ANALYTICS] total_location_distance::**1809.414185km**
2020/08/19 15:33:12.031551 [INFO] Got Thor Request 11
2020/08/19 15:33:12.031905 [ANALYTICS] travel_mode::2
2020/08/19 15:33:19.261304 [ANALYTICS] admin_state_iso::  
2020/08/19 15:33:19.261333 [ANALYTICS] admin_country_iso::  
2020/08/19 15:33:19.265582 [WARN] thor::route request elapsed time (ms)::**7234.027832**
2020/08/19 15:33:19.265600 [WARN] thor::route request exceeded threshold::11
2020/08/19 15:33:19.265635 [ANALYTICS] valhalla_thor_long_request_route
2020/08/19 15:33:19.267405 [INFO] Got Odin Request 11
2020/08/19 15:33:19.282997 [INFO] trip_path_->node_size()=2912
2020/08/19 15:33:19.413167 [INFO] maneuver_count::743

2020/08/19 15:32:52.643465 [INFO] Got Loki Request 9
2020/08/19 15:32:52.643873 [ANALYTICS] locations_count::2
2020/08/19 15:32:52.643963 [ANALYTICS] costing_type::bicycle
2020/08/19 15:32:52.644032 [ANALYTICS] total_location_distance::1136.381470km
2020/08/19 15:32:52.646230 [INFO] Got Thor Request 9
2020/08/19 15:32:52.646660 [ANALYTICS] travel_mode::2
2020/08/19 15:32:57.338303 [ANALYTICS] admin_state_iso::  
2020/08/19 15:32:57.338348 [ANALYTICS] admin_country_iso::  
2020/08/19 15:32:57.343180 [WARN] thor::route request elapsed time (ms)::4696.954590
2020/08/19 15:32:57.343216 [WARN] thor::route request exceeded threshold::9
2020/08/19 15:32:57.343221 [ANALYTICS] valhalla_thor_long_request_route
2020/08/19 15:32:57.345894 [INFO] Got Odin Request 9
2020/08/19 15:32:57.357782 [INFO] trip_path_->node_size()=4007

2020/08/19 15:31:59.642111 [INFO] Got Loki Request 7
2020/08/19 15:31:59.642389 [ANALYTICS] locations_count::2
2020/08/19 15:31:59.642456 [ANALYTICS] costing_type::bicycle
2020/08/19 15:31:59.642510 [ANALYTICS] total_location_distance::1094.111450km
2020/08/19 15:31:59.643561 [INFO] Got Thor Request 7
2020/08/19 15:31:59.643911 [ANALYTICS] travel_mode::2
2020/08/19 15:32:07.105667 [ANALYTICS] admin_state_iso::  
2020/08/19 15:32:07.105710 [ANALYTICS] admin_country_iso::  
2020/08/19 15:32:07.108673 [WARN] thor::route request elapsed time (ms)::7465.111328
2020/08/19 15:32:07.108706 [WARN] thor::route request exceeded threshold::7
2020/08/19 15:32:07.108711 [ANALYTICS] valhalla_thor_long_request_route
2020/08/19 15:32:07.110375 [INFO] Got Odin Request 7
2020/08/19 15:32:07.117120 [INFO] trip_path_->node_size()=2387
2020/08/19 15:32:07.184927 [INFO] maneuver_count::470
```

**Comment by TimMcCauley** [comment]
What is the use case for routing from Asia to Europe by car? It is absolutely normal that this takes time - https://people.ok.ubc.ca/ylucet/DS/Dijkstra.html - if you get familiar with shortest path algorithms you will understand. 
If you are looking for engines able to compute faster routes you might want to look at Graphhopper or OSRM which use some preprocessing contraction algorithms to speed up the computation but are far less flexible than Valhalla.

**Comment by junior-yoda** [comment]
Well, you are right about the car route but a bike route between two towns is pretty normal and we provide this service for our clients, same request for `auto` costing is served in a normal response time but same route for Bike is really long.   
![Screenshot from 2020-08-19 20-03-41](https://user-images.githubusercontent.com/64004971/90754669-6bb05200-e2ef-11ea-903f-cf2a408e9c4b.png)

These requests are under 2000 km, short response times are for car and longs are for bike route.

**Comment by TimMcCauley** [comment]
To me these response times don't look out of the ordinary, maybe someone else can chip in here. Please also keep in mind that there exist many more possible OSM ways for bikes and pedestrians than cars which ultimately means that it will have to traverse more information.

**Comment by dnesbitt61** [comment]
Bicycle and pedestrian routes do not have any of the performance enhancements that driving routes do: shortcuts, road class filtering. Also as stated above there are many more OSM ways that allow bikes and pedestrians. We (Valhalla developers) chose flexibility over performance, especially for bicycle routes where there are several factors (in addition to shortest time) that need to be considered when choosing the best route for a particular cyclist and what is a good route for one cyclist may not be good for another.

**Comment by junior-yoda** [comment]
Thanks for the explanation. Understood and I respect your mindset and strategy.
