### ISSUE TITLE
Distance to different types of roads from a location

### ISSUE THREAD

**Issue by harshana-pickme** [valhalla/valhalla#2549]
Hi Community,

Is there a way for me to get distance to various types of nearby roads. Eg. when a location is given, is there a way to get distances like: 100m to a unclassified road, 250m to a municipal road, 400m to a district road, etc. with the nearest location on each of the roads.

I need to find the best road within a given radius so I can do an efficient shuttle route by asking the person to move to a location on a near by road.

Thanks,
Harshana

**Comment by harshana-pickme** [comment]
Any update on this please

**Comment by kevinkreiser** [comment]
@harshana-pickme we have a service called `locate`: https://github.com/valhalla/valhalla/blob/master/docs/api/locate/api-reference.md

if you are running a server you can test it out with this little tool: http://valhalla.github.io/demos/locate/

**Comment by harshana-pickme** [comment]
> @harshana-pickme we have a service called `locate`: https://github.com/valhalla/valhalla/blob/master/docs/api/locate/api-reference.md
> 
> if you are running a server you can test it out with this little tool: http://valhalla.github.io/demos/locate/

Thanks @kevinkreiser for the help. Will look at it.

Thank you,
Harshana
