### ISSUE TITLE
Major erroneous doubling back of route produced by trace_route

### ISSUE THREAD

**Issue by austinhess** [valhalla/valhalla#2552]
While trying to use `/trace_route` for a recorded pedestrian GPS track along a section of the John Muir Trail in CA, the output included a large erroneous segment of doubling back that did not reflect any component of the track. The GPS data itself is fairly clean and doesn't reverse its course, and simply heads continuously south along the trail. But in the routed geometry,   at a point near an intersection at 119.478699 W, 37.757385 N, there is a U-turn instruction with directions to head back north for about 7 km, then another instruction to go back 7 km south approximately back to that same point, and then the route continues south in accordance with the actual track geometry.

I attempted to use `turn_penalty_factor` and other `trace_options` parameters as described in the [map matching docs](https://valhalla.readthedocs.io/en/latest/api/map-matching/api-reference/), but not only did they not fix the issue, they didn't change the route output at all. The only thing which seemed to resolve the doubling back was to truncate the track before it reached the intersection mentioned above. While I understand there are issues with doubling back when there is significant jitter due to GPS, this example seems particularly confusing because there is virtually no such variation in the recorded GPS data, the routing output is insensitive to the turn penalty factor, and the doubled-back segments of the route are very long.

Here is a sample curl command to reproduce the issue:
```
curl --location --request POST '<ROUTING SERVER URL>' \
--header 'Content-Type: application/json' \
--data-raw '{"encoded_polyline": "wssdgAx_lwbF?NfC{@bGgEbQ}TxG{KdE}TbBcFxBgDhMsF??rAm@dTjAfm@wC|EvCfCtEfEdE~HzAhHfDtD|J|J|IpB~HlJ`I~HtNx\\zLvNpG|JhCjFl@rFjAjK~HzL|TjAbGrFxLjP~RzG\\bVvObe@zUpQ`GnOvD`Bz@tE^|OtD|TlKvIrF`G_@bQ`HlPjB~WzKnXlJbQxBbeAr[dTfCfJxBv]vDv_BhChHyB`b@LxLm@fYuNjF?~h@yBrKiCfr@\\r[rFfh@jAhWfOtItD??`NbG~HzApLpGbLrFz[lU`LbQfOdOxL~IbLnH|OdE~W|JtO|JtUhMdEtDjF|J`XbQb[dOpRhMnNrF~H~I??xQ|TlKxLxGdPhHhLdEnTnHdEd@tEe@~G~CxCtO?jBfCkBtFoNnS_D`Rd@zKfEdO~HbG~R|JbLdD`b@~h@l_@n]nM\\rLtOzJfE`DrE`LbGfEfNj@`HbBrFd@|J|@hC?`G`BfEdj@j~@dEjBdEl@|OrEhMrGjdAp\\pWvCbLm@nS~Hx[bGnSOz[_I~HNjKhCbjAOlPtEdwAxB??`Xl@dJ`GbV^dOxA`N?yC?zF?pv@fD??bG^zExAfJ^`LjA|JtDvN^hRgD|Y{ApLyB~^}@~Mm@vX{JbG}@nNsFhRiC~HeErPsP|JqGtEyBxQgEb[^nSiC~HO~CgCbGwD`SiC~\\~I`SpH`G~HfOvb@nCbQtE~RpHde@LrE~ClK|JjVxBjUbBfOdEzJvDhC~CNfC_@pHk@pBz@|E|J????xBpGpGhCvXbF|^eO~H}JfEeOhRgNjZ`G`I{@xLhBxLvNjFiC`InS`L`ItPn]`GrPb[hb@zf@lh@rFxMfCvDtP}@dOl@bLnH|TsE??hWuEtm@yBf^bF`SgDrKhCrj@uEvIvCli@xC~RpGhMgDrFfDnNzAxLjVha@tOd[vNxVb[nSvl@hWlrApH~h@be@b`Dl_@j`@~CrQ~M~R??f@|@rKvCnl@dFvw@n]zQsFxL`H|TnIpQOhMhC|JpGbG|J|c@xLdEdEvD{AzE}TbB]bQ|^hH{UfM~]`Nuc@nHtc@rGeOrFpQdJ{KvIz`@pLeP|E~ShHcGz@|@oDhv@jAzJfEpHzt@vc@nShVb[d[~RzK|EdE??pg@pf@tSxa@hCxLhf@p{@zVdE`b@b[ptApfApl@n]x[vCnSaGp\\xApg@tE\\?yGm@zFl@lUm@dh@yBnOoHhu@dd@`SnSbVpf@bQngAkBtlAqGp{@oCzu@e@tc@tInh@fO`]xGtYt^vv@pCvXjd@bdB`SdOjUboA??rApGyBxb@_Inq@lKxv@sGlgBaGfrD`Bfx@hCzj@|TfiC~MnIxp@bxBpH`]????nDdErKxBnIrFlJxMtEOlOyL????yBnRfCrQzGrPzOxMpXz@tIjLv^b[zj@bz@nSz`@zOvNhM`G??vDxBha@fOvDm@~MsQjFcFfc@{AdJjK`IjB~HwDxLzA`SpH~MvX`g@fw@pGha@`SfYrP~{@tJfm@e@fY??Wvb@~Cli@vDp\\|OvYbLvXjPvaA|OhWxLlTbBxLWbQ~ClKvNzKfTfN|Y|TtEnI~Hj_@`GfNbVpS`Xxu@~RlTvNlUrL|Tpa@fm@pBjK}@hMgCvDcBzJ|@tPW~g@gCpQiMjVsFlT?jWaItOgHnRdEjWxB~RpBxL~HlKb[zUlE`H`D`HWbQcLxLcQpGuNvDoDzANdDrFdF\\jA", "costing": "pedestrian", "shape_match": "map_snap", "use_timestamps": false, "trace_options": {"turn_penalty_factor": 500}}'

**Comment by PureW** [comment]
> We're running version 3.1.0

Are you sure about that? Latest release is 3.0.9 https://github.com/valhalla/valhalla/releases
