### ISSUE TITLE
Inconsistent routing between local and hosted demo

### ISSUE THREAD

**Issue by christosnc** [valhalla/valhalla#2577]
## Problem
Hello,

I have built valhalla locally from source and I am running the demos/routing example.

For the most part everything works fine, but I discovered a scenario where I am getting inconsistent routes from local and hosted (api.mapbox) versions. I have elevation, admin, and timezone data loaded.

_Also as a note, it may be related, I also see that the time estimations are totally off as well. (hosted returns about 2x longer ETAs)_

I tried everything I could but I didn't manage to find the cause of the problem. Thanks!

## Reproduce

This is the url I am using:
[http://localhost:5000/demos/routing/index-internal#loc=15,34.925173,33.097730&directionsoptions={%22language%22:%22en-US%22}&directionsoptions={%22language%22:%22en-US%22}&locations=[{%22lat%22:34.929887882670336,%22lon%22:33.07615801692009},{%22lat%22:34.92756568686534,%22lon%22:33.10529753565788}]&costing=%22auto%22](url)

---
Or if you prefer with the route api directly:
##### Local request
[http://localhost:8002/route?json={%22locations%22:[{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:34.929887882670336,%22lng%22:33.07615801692009},%22_initHooksCalled%22:true,%22lat%22:34.929887882670336,%22lon%22:33.07615801692009},{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:34.92756568686534,%22lng%22:33.10529753565788},%22_initHooksCalled%22:true,%22lat%22:34.92756568686534,%22lon%22:33.10529753565788}],%22costing%22:%22auto%22,%22directions_options%22:{%22language%22:%22en-US%22}}](url)

##### Local response
```
{"trip":{"language":"en-US","units":"kilometers","status":0,"summary":{"max_lon":33.104607,"length":5.117,"min_lon":33.076584,"has_time_restrictions":false,"min_lat":34.920532,"max_lat":34.930157,"time":398.324},"status_message":"Found route between points","legs":[{"shape":"w}}raAmuya~@nD_DxG_JtDoIvDcKhBiMnD}J|EiHxF{ArLVfIbA~M`C~CbA~CcAnJiBrK}@vHUxHl@hGdEdEjF~DNhBsAl@kG}@mJ{@}ImEsLqG}JqCsEUkGfCsFpH_IrP{K`HsFlEcGpCgI|DqHfDkFd@mEu@wCeEqBsFqCwIyBeTkA_EcAyByCEkFhB_DhCiC`CkFpAmJzAyGnD}EvCuExBuI^aHu@kGcAaCoDoCeJ_D{FwCyBoDGeExBgI\\{FiC_EgDaBiBcGe@uJGeJe@aHUwDhBsF|DqBrBoCjAqHeAwHqBgDkAgIbAmJnDkGjFmEnDiH|@wCTeE?wI]wNd@kFxB}ErFeEnDkFjAkFUsGsB_CgHoDaHmE_EwIoD}NuDmKu@{E]iCWyGsJ{FyH}EkAqBTaCrA]jBd@nCjAfE?~CsAfCmDjBiHjAaHl@_InCoDnD}@hGVnJT~C{@xAgDs@mFyBkFyBuEcBmEFmD`CmEtDyBhCoDjAyGjBwIrE}EfEiBdT~C|INhCcBrA_DOcGs@sPF{FxBuDfIaCxGiCxG{EpGeKbGqLhMaCbKWzV]`R{AxRVnM\\rG`MnCxBjFpGzKjLnDrFpB|@dAOr@}EjBmDtEOdJzArFtDjGhHxBvNDfNrAnCbBVxBtDbAqLl@wIfDqLpBsFjAkG?eEU{E?cLNcGr@oIxByBbGeE`M_JjA{@t@eE|@yHlDqGpHwCnH}ErBcFpBwD|D_DzFqB|D}J|@{A\\wCsAm@aBFgDjFeJtEmEbAmFvDcFbFcGdEePzFyLrAeJcAoI{AoCcAcB{A]iBF{ArA{KyRgXkFoDsGaCmJ}EyVuD{VkGaWsAkQgIiRuEsFgCgCmEmEcQqCiMiCqMoCuI_DsGgD}DkFoD_DkFcBoIcBwIaCsF{@_De@}DToDt@wCjAoDxBoHjAqHt@_I\\gDbBqC~CyLbBsKOgIaCkLqBoM{AaHoDmFqGaGuD_DwDoIeEkLaC{KsAiHu@sF^mEhBs@xBr@z@xCVlD\\jGrArFjBtDvC|E|DdEnDhCfIzFtEbFlEbG~CxGrF~InCz@fDm@{@oHyMs[sEmKeFqQiCaRaBsLqBeJ_E}Im@kLMaHz@sKzA}OcAkKaCcGaHsFqHsAoHjAwIxBwHjAyH]mEqCuDmEyCiGyB_JqG_c@oDc`@yAoSWaH?}Ou@e_@kAoNuEaLwHcLeJ{F","summary":{"max_lon":33.104607,"length":5.117,"min_lon":33.076584,"has_time_restrictions":false,"min_lat":34.920532,"max_lat":34.930157,"time":398.324},"maneuvers":[{"end_shape_index":100,"time":112.200,"length":1.531,"street_names":["E931"],"verbal_post_transition_instruction":"Continue for 1.5 kilometers.","travel_type":"car","begin_shape_index":0,"verbal_pre_transition_instruction":"Drive southeast on E9 31.","travel_mode":"drive","instruction":"Drive southeast on E931.","type":2},{"travel_mode":"drive","end_shape_index":104,"time":7.104,"verbal_multi_cue":true,"length":0.057,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 60 meters.","begin_shape_index":100,"verbal_pre_transition_instruction":"Turn left to stay on E9 31. Then Turn right to stay on E9 31.","instruction":"Turn left to stay on E931.","type":15,"verbal_transition_alert_instruction":"Turn left to stay on E9 31."},{"end_shape_index":135,"time":34.868,"length":0.394,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 400 meters.","begin_shape_index":104,"verbal_pre_transition_instruction":"Turn right to stay on E9 31.","instruction":"Turn right to stay on E931.","type":10,"verbal_transition_alert_instruction":"Turn right to stay on E9 31.","travel_mode":"drive"},{"end_shape_index":168,"time":49.496,"length":0.618,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 600 meters.","begin_shape_index":135,"verbal_pre_transition_instruction":"Turn left to stay on E9 31.","instruction":"Turn left to stay on E931.","type":15,"verbal_transition_alert_instruction":"Turn left to stay on E9 31.","travel_mode":"drive"},{"end_shape_index":194,"time":30.284,"length":0.372,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 400 meters.","begin_shape_index":168,"verbal_pre_transition_instruction":"Turn left to stay on E9 31.","instruction":"Turn left to stay on E931.","type":15,"verbal_transition_alert_instruction":"Turn left to stay on E9 31.","travel_mode":"drive"},{"end_shape_index":208,"time":18.912,"length":0.221,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 200 meters.","begin_shape_index":194,"verbal_pre_transition_instruction":"Make a sharp left to stay on E9 31.","instruction":"Make a sharp left to stay on E931.","type":14,"verbal_transition_alert_instruction":"Make a sharp left to stay on E9 31.","travel_mode":"drive"},{"travel_mode":"drive","end_shape_index":211,"time":7.088,"verbal_multi_cue":true,"length":0.029,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 30 meters.","begin_shape_index":208,"verbal_pre_transition_instruction":"Turn right to stay on E9 31. Then Turn left to stay on E9 31.","instruction":"Turn right to stay on E931.","type":10,"verbal_transition_alert_instruction":"Turn right to stay on E9 31."},{"end_shape_index":258,"time":70.080,"length":0.890,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 900 meters.","begin_shape_index":211,"verbal_pre_transition_instruction":"Turn left to stay on E9 31.","instruction":"Turn left to stay on E931.","type":15,"verbal_transition_alert_instruction":"Turn left to stay on E9 31.","travel_mode":"drive"},{"end_shape_index":275,"time":20.264,"length":0.212,"street_names":["E931"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 200 meters.","begin_shape_index":258,"verbal_pre_transition_instruction":"Turn right to stay on E9 31.","instruction":"Turn right to stay on E931.","type":10,"verbal_transition_alert_instruction":"Turn right to stay on E9 31.","travel_mode":"drive"},{"end_shape_index":309,"time":48.028,"length":0.793,"street_names":["E903"],"travel_type":"car","verbal_post_transition_instruction":"Continue for 800 meters.","begin_shape_index":275,"verbal_pre_transition_instruction":"Turn left onto E9 03.","instruction":"Turn left onto E903.","type":15,"verbal_transition_alert_instruction":"Turn left onto E9 03.","travel_mode":"drive"},{"length":0.000,"travel_type":"car","begin_shape_index":309,"verbal_pre_transition_instruction":"Your destination is on the right.","end_shape_index":309,"time":0.000,"type":5,"verbal_transition_alert_instruction":"Your destination will be on the right.","travel_mode":"drive","instruction":"Your destination is on the right."}]}],"locations":[{"original_index":0,"lon":33.076157,"side_of_street":"right","lat":34.929890,"type":"break"},{"original_index":1,"lon":33.105297,"side_of_street":"right","lat":34.927567,"type":"break"}]}}
```
## 

##### Hosted request
[https://api.mapbox.com/valhalla/v1/route?json={%22locations%22:[{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:34.929887882670336,%22lng%22:33.07615801692009},%22_initHooksCalled%22:true,%22lat%22:34.929887882670336,%22lon%22:33.07615801692009},{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:34.92756568686534,%22lng%22:33.10529753565788},%22_initHooksCalled%22:true,%22lat%22:34.92756568686534,%22lon%22:33.10529753565788}],%22costing%22:%22auto%22,%22directions_options%22:{%22language%22:%22en-US%22}}&access_token=<YOUR_MAPBOX_ACCESS_TOKEN>](url)

##### Hosted response
```
{"trip":{"status":0,"language":"en-US","status_message":"Found route between points","legs":[{"shape":"w}}raAmuya~@nD_DxG_JtDoIvDcKhBiMnD}J|EiHxF{ArLVfIbA~M`C~CbA~CcAnJqBrKm@vH]xHl@hGdEdEjF~DNhBsAl@kG}@mJ{@}ImEsLkGuJwC{EUkGfCsFpH_IrP{K`HsFlEcGpCgI|DqHfDkFd@mEu@wCeEqBsFqCwIyBeTkA_EcA_CyC?kFhB_DhCiC`CkFpAmJzAyGnD}EvCuExBuI^aHu@kGcAaCoDoCeJ_D{FwCyBoDGmExB_I\\{FiC_EgDaBiBcGe@uJGeJe@aHUwDhBsF|DqBrBoCjAqHkAwHkBgDkAgIbAmJnDkGdFmEtDiH|@wCTeE?wI]wNd@kFxB}ErFeEnDkFjAkF]sGkBgCgHgDaHmE_EwIoD}NuDeKu@cF]iCOyGpCuElEoChHgErKoCpG?lJrAvIz@bF]xH{AfHgItEoIbGaHhGsEhHaClJG~Id@`HVdEu@xGyG`CiCnDiBxBeApBGvCFlJnIxHjK~HfJvHhGpHrGdE`HrAjKl@vMl@hMjAvNhCpHlDzEtEzA|E?rFkAvHoDhH_NdEqG`HqHhMqLpM{LlJiHlJ_IrF_DrFqBjGOjF|@hGnCjGhCtEzArFr@|EcA~BcArGsKz@{Ll@uNzAsLrAqL`CwIl@gILwHm@gJqBaGiBoIWcGd@gI`CcFdFiCjFOhGl@zFd@bG{@|DkB|EaGhHgJtIsFhHqBzKUfIhBjLhHtD|I~CrKpCxMhCdPnCtIfDlFtEhBrF\\bG]lJ]pGxBhHxGvCnD|ElDhGdAdETfEMfDcBrF_DdEeEtDoDbBiHe@}J\\mIpBmErA}@qBsKe@qHbAkK|@qChG{PtUed@lDsFrGaHhGeEbQmO|ZeZ~C}ErA}Dz@uEMcGDgMkA}EgDkFob@yq@qMmOaHkG}JsFmNaG{L_EsPmEmTmJmUiMgScL{KsEaMyB{KGiWhBaNdAgHu@yBhB}E_IcGiHaH{JkFuFkFoCkGOyLrByMpBuILePqBsKaBeJTaIvC{JpHePvNgI|Da\\tJaIt@oHeA{FmDkGoIaHuOkPg^}EkFiGyBcGF_IvCqWnSqGbAoIaCkFwHqHcVePoh@{@iHyMy[sEeKeFyQaCaRiBsLqBeJ_E}Im@kLMaHz@sKzA}OcAkKaCcGaHsFqHsAoHjAwIxBwHjAyH]mEqCuDmEqCiGaCwIqGgc@oDc`@sAoS]aH?}Ou@e_@kAoNuEaLwHcLeJ{F","summary":{"max_lon":33.104607,"min_lat":34.914436,"max_lat":34.930157,"length":6.022,"has_time_restrictions":false,"min_lon":33.076584,"time":693.732},"maneuvers":[{"travel_type":"car","travel_mode":"drive","end_shape_index":100,"begin_shape_index":0,"street_names":["E931"],"time":292.185,"verbal_pre_transition_instruction":"Drive southeast on E9 31.","verbal_post_transition_instruction":"Continue for 1.5 kilometers.","instruction":"Drive southeast on E931.","length":1.532,"type":2},{"travel_type":"car","travel_mode":"drive","end_shape_index":210,"begin_shape_index":100,"time":197.1,"verbal_pre_transition_instruction":"Turn right.","verbal_transition_alert_instruction":"Turn right.","verbal_post_transition_instruction":"Continue for 2 kilometers.","instruction":"Turn right.","length":1.881,"type":10},{"travel_type":"car","travel_mode":"drive","end_shape_index":245,"begin_shape_index":210,"time":74.089,"verbal_pre_transition_instruction":"Turn left onto E9 03.","street_names":["E903"],"verbal_transition_alert_instruction":"Turn left onto E9 03.","verbal_post_transition_instruction":"Continue for 1 kilometer.","instruction":"Turn left onto E903.","length":0.969,"type":15},{"travel_type":"car","travel_mode":"drive","end_shape_index":312,"begin_shape_index":245,"time":130.358,"verbal_pre_transition_instruction":"Turn right to stay on E9 03.","street_names":["E903"],"verbal_transition_alert_instruction":"Turn right to stay on E9 03.","verbal_post_transition_instruction":"Continue for 1.5 kilometers.","instruction":"Turn right to stay on E903.","length":1.641,"type":10},{"travel_type":"car","travel_mode":"drive","end_shape_index":312,"begin_shape_index":312,"time":0,"verbal_pre_transition_instruction":"Your destination is on the right.","verbal_transition_alert_instruction":"Your destination will be on the right.","instruction":"Your destination is on the right.","length":0,"type":5}]}],"units":"kilometers","summary":{"max_lon":33.104607,"min_lat":34.914436,"max_lat":34.930157,"length":6.022,"has_time_restrictions":false,"min_lon":33.076584,"time":693.732},"locations":[{"original_index":0,"lon":33.076157,"side_of_street":"right","lat":34.92989,"type":"break"},{"original_index":1,"lon":33.105297,"side_of_street":"right","lat":34.927567,"type":"break"}]}}
```

**Comment by danpaz** [comment]
@christosnc The most likely reason you'll see discrepancies like this between a local and hosted version is differences in the underlying OSM data. If you map the route geometries you pasted above you'll see they take different paths.

- [local](http://valhalla.github.io/demos/polyline/?unescape=true&polyline6=true#w%7D%7DraAmuya~%40nD_DxG_JtDoIvDcKhBiMnD%7DJ%7CEiHxF%7BArLVfIbA~M%60C~CbA~CcAnJiBrK%7D%40vHUxHl%40hGdEdEjF~DNhBsAl%40kG%7D%40mJ%7B%40%7DImEsLqG%7DJqCsEUkGfCsFpH_IrP%7BK%60HsFlEcGpCgI%7CDqHfDkFd%40mEu%40wCeEqBsFqCwIyBeTkA_EcAyByCEkFhB_DhCiC%60CkFpAmJzAyGnD%7DEvCuExBuI%5EaHu%40kGcAaCoDoCeJ_D%7BFwCyBoDGeExBgI%5C%5C%7BFiC_EgDaBiBcGe%40uJGeJe%40aHUwDhBsF%7CDqBrBoCjAqHeAwHqBgDkAgIbAmJnDkGjFmEnDiH%7C%40wCTeE%3FwI%5DwNd%40kFxB%7DErFeEnDkFjAkFUsGsB_CgHoDaHmE_EwIoD%7DNuDmKu%40%7BE%5DiCWyGsJ%7BFyH%7DEkAqBTaCrA%5DjBd%40nCjAfE%3F~CsAfCmDjBiHjAaHl%40_InCoDnD%7D%40hGVnJT~C%7B%40xAgDs%40mFyBkFyBuEcBmEFmD%60CmEtDyBhCoDjAyGjBwIrE%7DEfEiBdT~C%7CINhCcBrA_DOcGs%40sPF%7BFxBuDfIaCxGiCxG%7BEpGeKbGqLhMaCbKWzV%5D%60R%7BAxRVnM%5C%5CrG%60MnCxBjFpGzKjLnDrFpB%7C%40dAOr%40%7DEjBmDtEOdJzArFtDjGhHxBvNDfNrAnCbBVxBtDbAqLl%40wIfDqLpBsFjAkG%3FeEU%7BE%3FcLNcGr%40oIxByBbGeE%60M_JjA%7B%40t%40eE%7C%40yHlDqGpHwCnH%7DErBcFpBwD%7CD_DzFqB%7CD%7DJ%7C%40%7BA%5C%5CwCsAm%40aBFgDjFeJtEmEbAmFvDcFbFcGdEePzFyLrAeJcAoI%7BAoCcAcB%7BA%5DiBF%7BArA%7BKyRgXkFoDsGaCmJ%7DEyVuD%7BVkGaWsAkQgIiRuEsFgCgCmEmEcQqCiMiCqMoCuI_DsGgD%7DDkFoD_DkFcBoIcBwIaCsF%7B%40_De%40%7DDToDt%40wCjAoDxBoHjAqHt%40_I%5C%5CgDbBqC~CyLbBsKOgIaCkLqBoM%7BAaHoDmFqGaGuD_DwDoIeEkLaC%7BKsAiHu%40sF%5EmEhBs%40xBr%40z%40xCVlD%5C%5CjGrArFjBtDvC%7CE%7CDdEnDhCfIzFtEbFlEbG~CxGrF~InCz%40fDm%40%7B%40oHyMs%5BsEmKeFqQiCaRaBsLqBeJ_E%7DIm%40kLMaHz%40sKzA%7DOcAkKaCcGaHsFqHsAoHjAwIxBwHjAyH%5DmEqCuDmEyCiGyB_JqG_c%40oDc%60%40yAoSWaH%3F%7DOu%40e_%40kAoNuEaLwHcLeJ%7BF)
- [hosted](http://valhalla.github.io/demos/polyline/?unescape=true&polyline6=true#w%7D%7DraAmuya~%40nD_DxG_JtDoIvDcKhBiMnD%7DJ%7CEiHxF%7BArLVfIbA~M%60C~CbA~CcAnJqBrKm%40vH%5DxHl%40hGdEdEjF~DNhBsAl%40kG%7D%40mJ%7B%40%7DImEsLkGuJwC%7BEUkGfCsFpH_IrP%7BK%60HsFlEcGpCgI%7CDqHfDkFd%40mEu%40wCeEqBsFqCwIyBeTkA_EcA_CyC%3FkFhB_DhCiC%60CkFpAmJzAyGnD%7DEvCuExBuI%5EaHu%40kGcAaCoDoCeJ_D%7BFwCyBoDGmExB_I%5C%5C%7BFiC_EgDaBiBcGe%40uJGeJe%40aHUwDhBsF%7CDqBrBoCjAqHkAwHkBgDkAgIbAmJnDkGdFmEtDiH%7C%40wCTeE%3FwI%5DwNd%40kFxB%7DErFeEnDkFjAkF%5DsGkBgCgHgDaHmE_EwIoD%7DNuDeKu%40cF%5DiCOyGpCuElEoChHgErKoCpG%3FlJrAvIz%40bF%5DxH%7BAfHgItEoIbGaHhGsEhHaClJG~Id%40%60HVdEu%40xGyG%60CiCnDiBxBeApBGvCFlJnIxHjK~HfJvHhGpHrGdE%60HrAjKl%40vMl%40hMjAvNhCpHlDzEtEzA%7CE%3FrFkAvHoDhH_NdEqG%60HqHhMqLpM%7BLlJiHlJ_IrF_DrFqBjGOjF%7C%40hGnCjGhCtEzArFr%40%7CEcA~BcArGsKz%40%7BLl%40uNzAsLrAqL%60CwIl%40gILwHm%40gJqBaGiBoIWcGd%40gI%60CcFdFiCjFOhGl%40zFd%40bG%7B%40%7CDkB%7CEaGhHgJtIsFhHqBzKUfIhBjLhHtD%7CI~CrKpCxMhCdPnCtIfDlFtEhBrF%5C%5CbG%5DlJ%5DpGxBhHxGvCnD%7CElDhGdAdETfEMfDcBrF_DdEeEtDoDbBiHe%40%7DJ%5C%5CmIpBmErA%7D%40qBsKe%40qHbAkK%7C%40qChG%7BPtUed%40lDsFrGaHhGeEbQmO%7CZeZ~C%7DErA%7DDz%40uEMcGDgMkA%7DEgDkFob%40yq%40qMmOaHkG%7DJsFmNaG%7BL_EsPmEmTmJmUiMgScL%7BKsEaMyB%7BKGiWhBaNdAgHu%40yBhB%7DE_IcGiHaH%7BJkFuFkFoCkGOyLrByMpBuILePqBsKaBeJTaIvC%7BJpHePvNgI%7CDa%5C%5CtJaIt%40oHeA%7BFmDkGoIaHuOkPg%5E%7DEkFiGyBcGF_IvCqWnSqGbAoIaCkFwHqHcVePoh%40%7B%40iHyMy%5BsEeKeFyQaCaRiBsLqBeJ_E%7DIm%40kLMaHz%40sKzA%7DOcAkKaCcGaHsFqHsAoHjAwIxBwHjAyH%5DmEqCuDmEqCiGaCwIqGgc%40oDc%60%40sAoS%5DaH%3F%7DOu%40e_%40kAoNuEaLwHcLeJ%7BF)

If you're interested in figuring out why the paths are different, I'd look for recent changes in OSM attribution near the point where the paths diverge. It's possible the map you are using is more up to date than the one used in the hosted API.

**Comment by christosnc** [comment]
Thanks for the quick response! Yeah, the two paths are different, that's exactly my point. 😃

Since I know the path in real life, I can say for sure that **the hosted response is better** (although longer in distance, it's the fastest in time). And sure enough, If I set the costing to "auto_shorter", then the hosted returns the same as local (shortest distance, but not fastest).

So overall the hosted performs better. The local version always returns the same (shortest) path.

As you pointed out, I am indeed using the latest OSM data and I also thought that this might be the issue, but this doesn't seem to be the problem. Most OSM ways involved were edited 4+ years ago with the exception of these two:
- [https://www.openstreetmap.org/way/216166616/history](url)
- [https://www.openstreetmap.org/way/152482454/history](url)

Moreover, I tried changing the maneuver_penalty, since the shortest (slow) path has many more maneuvers, but with no difference whatsoever.

I was thinking that maybe there is a different configuration on the hosted demo, or there is more data involved because if you right click on a way in the hosted, you can see some numbers for the free_flow and constrained_flow parameters..
<img width="504" alt="Screen Shot 2020-09-03 at 10 37 07 PM" src="https://user-images.githubusercontent.com/22871955/92176343-2be08300-ee36-11ea-9a2a-5774dedd05d3.png">

This could be anything from a minor issue to a bug.. Can we give a definitive answer to this?

**Comment by nilsnolde** [comment]
too long ago and I don't think mapbox's api is still open like that, let alone it's a very different code base.
