### ISSUE TITLE
Need Alternate Route Support in Valhalla

### ISSUE THREAD

**Issue by YashowardhanTripathi** [valhalla/valhalla#2580]
Valhalla is excellent routing engine and i just started using it is quite good it has detailed features and parameters.
I would like to know is there any option for alternate route as OSRM has, In which it creates separate legs for alternative paths.
[As you can see here](http://map.project-osrm.org/?z=13&center=37.718726%2C-122.432585&loc=37.760537%2C-122.455673&loc=37.703109%2C-122.419453&hl=en&alt=0&srv=1)

**Comment by kevinkreiser** [comment]
@YashowardhanTripathi not at this time. support could be added but we arent focused on doing that at the moment. we can let this issue open and keep it up to date if and when we work on support for it

**Comment by YashowardhanTripathi** [comment]
@kevinkreiser  Thanks for quick reply, Impressive support and I hope this is implemented soon.
