### ISSUE TITLE
(Info) what does k means in prefix of variables

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#2584]
I see a lot of variable is sirf names kDefaultUseFerry, kDefaultUseFerry what does k means
also in lua scrips kv

**Comment by dgearhart** [comment]
@pranavpandey1998official when we started Valhalla - we followed the [Google C++ style guide for constant names](https://google.github.io/styleguide/cppguide.html#Constant_Names) - which started with a `k`

The `kv` in lua scripts is for `key/value`

**Comment by pranavpandey1998official** [comment]
thank you
