### ISSUE TITLE
[Docker] Valhalla not responding

### ISSUE THREAD

**Issue by bboure** [valhalla/valhalla#2585]
Hi,

I am having issues running Valhalla on a planet build.
I have generated the config json file and the tiles on a planet osm file. 
When running the service, the server does not respond. No error is given, the request just never finishes.

- [valhalla.json](https://gist.github.com/bboure/768019d380ae422b20619e3104d43ace)
- My valhalla_tiles.tar is 111G, it also includes admins and timezones
- I am using Docker
- I did not generate elevations
- Hoost Server has 2 CPU and 4GB of RAM, but I also tried it on a much bigger machine (36 CPU and 72 GB of RAM) with the same issue.

He is what I did

```bash
docker run -v $(pwd)/data:/data valhalla/docker bash -c "valhalla_build_config --mjolnir-tile-dir /data/valhalla/valhalla_tiles --mjolnir-tile-extract /data/valhalla/valhalla_tiles.tar --mjolnir-timezone /data/valhalla/valhalla_tiles/timezones.sqlite --mjolnir-admin /data/valhalla/valhalla_tiles/admins.sqlite > /data/valhalla/valhalla.json"
docker run -v $(pwd)/data:/data valhalla/docker bash -c "valhalla_build_admins --config /data/valhalla/valhalla.json /data/osm/planet-latest.osm.pbf"
docker run -v $(pwd)/data:/data valhalla/docker bash -c "valhalla_build_timezones --config /data/valhalla/valhalla.json > /data/valhalla/valhalla_tiles/timezones.sqlite"
docker run -v $(pwd)/data:/data valhalla/docker bash -c "valhalla_build_tiles -c /data/valhalla/valhalla.json /data/osm/planet-latest.osm.pbf"
find data/valhalla/valhalla_tiles | sort -n | tar cf data/valhalla/valhalla_tiles.tar --no-recursion -T -

```

Doing the same thing using a smaller build (City) works just fine. 
I am only having issues with a planet build.

I have tried rebuilding the tiles with the same result.

container's logs:

```bash
0 2020/09/10 11:41:37.010313 GET /route HTTP/1.1
1 2020/09/10 11:48:20.587260 GET /route HTTP/1.1
2 2020/09/10 11:51:14.283400 POST /optimized_route HTTP/1.1
```

I see no error there either but the request do come in.

Docker stats:
```bash
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
6c98f69ecb66        laughing_williams   100.80%             31.71MiB / 3.851GiB   0.80%               2.34kB / 674B       0B / 0B             12
```
CPU remains at around 100%. Memory barely changes either

Any idea on what the issue could be?

Thank you!!!

**Comment by ImreSamu** [comment]
> Any idea on what the issue could be?
> ...
> `docker run -v $(pwd)/data:/data valhalla/docker bash -c " ..." ` 

imho: the current [`valhalla/docker:latest`](https://hub.docker.com/layers/valhalla/docker/latest/images/sha256-2ae7144addb719c002ca311c96c4ed7ee12c59a9e65e8e65c42c8f10adc3b089?context=explore) is 2 years old ..
as I see it is based on **2.4.9**

```
$ docker run -it --rm valhalla/docker valhalla_build_tiles -v
valhalla_build_tiles 2.4.9
```
 
you can verify on your local:   CREATED =  2 years ago 
```
$ docker images | grep valhalla/docker
valhalla/docker                latest              4bb4c09f619c        2 years ago         2.02GB
```

probably you have to create a new Dockerfile with a latest master ...

**Comment by bboure** [comment]
Thank you @ImreSamu for your feedback.

> imho: the current valhalla/docker:latest is 2 years old ..

Good catch on that, that is something I missed.
Although, something I forgot to mention is that this was not my only try.
I have also tried with the community image [interline/valhalla](https://hub.docker.com/r/interline/valhalla) (release-v3.0.9) 
No more luck. Same problem.

**Comment by nilsnolde** [comment]
AFAIK the docker stuff moved into the main repo a long time ago. Also it’s mostly used for CI stuff.

Our docker image is also not tracking master (yet, need to automate that still) but at least you can source 3.0.9:
https://github.com/gis-ops/docker-valhalla

**Comment by bboure** [comment]
Thank you @nilsnolde for your suggestions.
Just tried out your image with a small City and it it working great.
I really like the fact that it's all automated 👏👏👏
Will give it a shot on a planet build.

**Comment by bboure** [comment]
Thank you again @nilsnolde for your suggestions. 
I have tried a planet build using your docker image. 
I am having the exact same issue. Requests come in, but no response.
I waited up to 1 hour with no luck.

```zbah
[ec2-user@ip-x-y-z-123 ec2-user]$ docker run -t --name valhalla_gis-ops -p 8002:8002 -v $PWD/data:/custom_files -e "force_rebuild=False" gisops/valhalla:latest
TEST: /custom_files
2280c2b605130909d9aeb3946265d9df46a7a0edea326c0b410d1500971bae84 e8f1f76aac8a713c7c610b7f0e4a390148113d3aa184329c004e1aa63340f8e0
Found valid hash for /custom_files/valhalla_tiles.tar!
Valid valhalla_tiles.tar found with use_tiles_ignore_pbf: !
Build new valhalla_tiles.tar from available PBF(s).
2280c2b605130909d9aeb3946265d9df46a7a0edea326c0b410d1500971bae84 e8f1f76aac8a713c7c610b7f0e4a390148113d3aa184329c004e1aa63340f8e0
Found valid hash for /custom_files/planet-latest.osm.pbf!
Scanning old hash 2280c2b605130909d9aeb3946265d9df46a7a0edea326c0b410d1500971bae84 e8f1f76aac8a713c7c610b7f0e4a390148113d3aa184329c004e1aa63340f8e0
All files have already been build and valhalla_tiles.tar exists and is valid. Starting without new build!
PBF hashes: 1
PBF file Counter: 1
Found valhalla_tiles.tar!
Found config file. Starting valhalla service!
0 2020/09/12 07:41:02.915860 GET / HTTP/1.1
1 2020/09/12 07:41:06.286934 GET / HTTP/1.1
```

I tried a city build, and it is working as expected. I am not sure what to do.
Are you using AWS? What instance type are you using?

Thanks again

**Comment by nilsnolde** [comment]
Did you build the tiles with the same image? I.e. you just plugged in the planet PBF and let the container do the rest? The valhalla_tiles.tar looks ok (in terms of size..)? Can you share the docker log from the tile build stage?

We never built the planet (native or docker), mostly using it for smaller scenarios. It's really odd though..

**Comment by nilsnolde** [comment]
Also, which image version were you using? I don't recommend using `latest`.

**Comment by bboure** [comment]
Yes, I put the pbf in the custom_files folder and let the container do the rest.
I cannot show you the logs from the build stage cause I destroyed that container since.

Here is the content of custom_files

```bash
362M    admin_data
4.0K    elevation_data
53G     planet-latest.osm.pbf
92M     timezone_data
8.0K    valhalla.json
70G     valhalla_tiles.tar
```

I am using the `latest` tag. I can try with a specific version, but not sure it has anything to do.
I am having the exact same issue with all the docke riamges I have tried ¯\_(ツ)_/¯

I don't think it's a VPC issue either. My security group is well configured, I even tried opening all ports to the world, locally within the instance (with curl); and even from within the container itself. Same result....

Looks like the planet file is too big to handle somehow... It's the only explanation I see

**Comment by nilsnolde** [comment]
I think you're right, version shouldn't matter that much and much more looks like a strange docker effect.

Now I'd like to try a planet build myself. Don't have an appropriate instance at hand though, they're all quite overloaded already.. Let me at least update our image to latest valhalla by tmrw night (needs a few updates in scripts, lots has changed). I'll automate that to update the latest image every night. Maybe you can try again on Monday then. If that doesn't work either, then you should try a local build of valhalla (you can try that of course right now as well.. I'd like to understand though if it's docker related or just code related). Really, all the images out there are quite old (at least around the same age as the last valhalla release) and lots of bugs have been fixed since.

**Comment by bboure** [comment]
> then you should try a local build of valhalla

Sounds good, I will try that over the weekend, just to discard or confirm a docker issue. 

thanks again

**Comment by nilsnolde** [comment]
Well, then you'd need to check out the exact same commit the image used when created, otherwise it could be code, docker or both. Not sure if it's preserved in the container. There might a `valhalla_git` directory still, where you can see the current commit.

**Comment by nilsnolde** [comment]
Did you make it work @bboure ? I just automated a weekly build for our Dockerhub `latest` tag BTW..

**Comment by bboure** [comment]
@nilsnolde Thanks for getting back.
I tried a planet build on a fresh Valhalla (3.0.9) built from source on Ubuntu (no Docker). Same problem :(

I also did several other tests (with Docker):
- a Country-wide build (Spain) works fine
- planet on my laptop: does not work

I want to try bigger regions, like Europe, and see where the "limit" seems to be.

I am unsure if the whole tile graph has to fit into memory. I cannot find any mention of this in the doc ([quite the opposite, actually](https://valhalla.readthedocs.io/en/latest/mjolnir/why_tiles/#onto-the-why)), and the Valhalla does not throw any error about the file being too big or anything. Memory consumption of the docker container also remains very low.

Also, this doesn't even work when I simply call 'http://[HOST]:8002' (that is, without any endpoint or route to calculate). I don't see the typical 404 message about available endpoints.

**Comment by nilsnolde** [comment]
No error logs in the tile building? Just terminates successfully? Does the tile folder look alright (i.e. no artifact files left behind)?

It'd be good to have:
- all relevant logs (tile building, the very first lines after starting `valhalla_service` etc)
- the valhalla.json config

**Comment by bboure** [comment]
Hum, in the last build, I just saw this error:

````
terminate called after throwing an instance of 'std::runtime_error'
  what():  Didn't find OSMWayNode for node id: 2073500103
```

I remember seeing this error before, but not in the last planet build I tried. (I will try again though, just to make sure)

Full Logs and json: https://gist.github.com/bboure/fc2fe55a0ec753530c039e833c3242c7
(Note: I skipped admins and TZ on purpose here. They were generated separately)

For the sake of completeness:

./custom_files
```bash
   130B Sep 18 03:07 .file_hashes.txt
    96B Sep 16 20:09 admin_data
    64B Sep 16 13:20 elevation_data
    53G Sep 16 13:15 planet-latest.osm.pbf
    96B Sep 16 20:47 timezone_data
   5.7K Sep 17 06:51 valhalla.json
    69G Sep 18 03:07 valhalla_tiles.tar
```

valhalla_tiles
```bash
    60M Sep 17 18:30 access.bin
    24M Sep 17 18:30 complex_from_restrictions.bin
    23M Sep 17 18:30 complex_to_restrictions.bin
    55G Sep 18 01:03 way_nodes.bin
    14G Sep 17 18:30 ways.bin
```

One last thing I might try is to use an older planet.pbf.
Could it be that the latest planet has something that makes Valhalla unhappy?

**Comment by nilsnolde** [comment]
yeah, that doesn't look good. it never actually build the tiles and bailed when not finding the node from the error logs.

I just looked on OSM and that node seems to exist. Did you verify the hash sum of your planet pbf against the original server's hash sum? maybe your planet file got corrupted during the download, which is definitely not unheard of. Or try to run `osmium fileinfo -e planet.pbf` which gives you some more info about the internal integrity (but probably not much about allegedly missing nodes..). And yeah, you could try another mirror/earlier date.

**Comment by bboure** [comment]
> I just looked on OSM and that node seems to exist. Did you verify the hash sum of your planet pbf against the original server's hash sum?

Yeah, I did verify it before launching the build. It was correct. 

I'll keep investigating.

Thanks again for your help

**Comment by bboure** [comment]
After several days of different attempts, I am still not able to make this work on a planet build.
My last try was with version 3.0.9, using docker (with https://github.com/gis-ops/docker-valhalla)
This time, it got further though. However, it seemed extremely slow.
Over 2 days to get to then end of the `build` stage (when the doc states the full process should take about 15 hours).
After that, it just stopped in the `enhance` stage without any error. 
I tried restarting the process, with the `-s enhance`, but it complained about not finding `osmdata_unique_strings.bin`. The file is indeed not in the workspace. 
I tried to skip `enhance`, starting from `filter`, it then failed with

````

terminate called after throwing an instance of 'std::runtime_error'
  what():  GetName: offset exceeds size of text list
```

I used a `m5.xlarge` instance on AWS (4 CPU, 16 GB RAM) with 350GB of EBS (gp) storage.

Here are the full logs:
https://gist.github.com/bboure/b9b044c9e15245ffbdd8fc391e43744d

Thanks

**Comment by nilsnolde** [comment]
I'd really not recommend using 3.0.9 anymore (that exact tag), it's really old at this point and tons of bugs have been fixed. Out `latest` image is rebuilt every Saturday morning from valhalla's master.

In terms of speed: no idea really.. maybe try increasing `mjolnir.max_cache_size`, which defaults to 1 GB. It's already using 4 threads for tile building.. also on speed, master should be tons faster than 3.0.9. release.

In the tile building stage you get a few `2020/09/24 08:37:17.667488 [ERROR] Failed tile 2/517741/0: std::bad_alloc`, not sure what the impact of those is, doesn't sound good though.. Maybe someone with extensive building knowledge can chime in, @mookerji maybe?

**Comment by bboure** [comment]
Hi there. Some updates here. I finally made it work!!
I ended up using an older OSM file (from July) just in case and it went through like a charm!!
My guess is that the newer images have some kind of corrupt data or something that valhalla doesn't like 😞. I will open a new issue about that. 

Thanks again @nilsnolde for your great help and awesome docker image.
