### ISSUE TITLE
Max distance as isochrone parameter

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2603]
One more requirement from our side we'd like to implement:

Use distance as cut-off criteria for isochrones. It makes sense regardless, but even more so with `shortest` metric around the corner (#2555).

I think this would be fairly easy to achieve, but there's one question I'm not sure about:

Should it be exclusively `time` **or** `distance`, or should it be possible to include both for a contour in a request and end the expansion when one of them is exceeded?

What do you think about the idea in general?

**Comment by kevinkreiser** [comment]
at the moment we do keep the path distance and time in the edge label as we do the expansion so it should be possible to cut off at both time and distance simultaneously (which ever is tripped first).

i dont think you are asking this but ill say it anyway. if we actually want to build contours of other metrics that arent time, like distance contour, or fuel useage contour, then we need to start tracking those metrics in costing like was done in the awesome work on #2305 and update the isochrone grid to store more than one metric (or be able to choose which metric is stored).

**Comment by nilsnolde** [comment]
Ah ok thanks for the hint @kevinkreiser ! Matt's PR actually also implemented a max speed, nice:) I'll look into this beginning of next week and update with a draft PR.

**Comment by nilsnolde** [comment]
this landed a while ago with https://github.com/valhalla/valhalla/pull/2699
