### ISSUE TITLE
Switch Python bindings to pybind11

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2628]
I had serious trouble compiling boost.python for fedora's mingw64 toolchain, most is documented [on SO](https://stackoverflow.com/questions/64118672/compile-boost-python-1-73-0-for-windows-with-mingw64-on-fedora). In the end, it compiled, but then I couldn't get valhalla's bindings to work on Windows in a cross-compiled python, still complains about missing DLLs even though I pulled all relevant ones next to the python lib.

If you're ok with it I'd like to switch to the **header-only** pybind11 to generate the bindings instead of boost.python. I'd include it in `third-party` as a submodule. Already tried a minimum example in cross-compilation and it worked easily on Windows.

Of course I'll keep the API the same (for now anyways, eventually I'd like to make it more pythonic, more a v4 plan I guess).

**Comment by kevinkreiser** [comment]
header-only python bindings generation it way less intrusive than getting boost python depedencies. honestly this sounds better in all ways. go for it!
