### ISSUE TITLE
Move Demos Repo Contents to Source Repo and Refresh Documentation to Make them Findable

### ISSUE THREAD

**Issue by matkoniecz** [valhalla/valhalla#2637]
As I understand there is no public demo, but maybe adding some image examples to readme would be nice?

Especially demonstration of multimodal capability.

It it would be considered as an improvement I can try adding something like this.

**Comment by nilsnolde** [comment]
There actually is a kinda [public demo](valhalla.github.io/demos/routing/#loc=16,50.721263,7.037194) (requires a Mapbox token though), coming from the [demo repo](https://github.com/valhalla/demos), which you can also easily run against localhost. It's even (fairly well hidden) in the docs :) https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md

The README could actually use a little love IMHO (maybe getting rid of the old v2 warning, re-structuring a little etc) and the demo(s) should probably be in there as well, at least for routing. Would be superb of course, if Mapbox could provide a daily rolling (so it doesn't get abused too much) API key for the public demo like ORS.

**Comment by kevinkreiser** [comment]
yeah @nilsnolde is right. we have demos that can be configured to hit localhost usually by looking at `index-internal.html` in the demos repo. we should probably just move the demos repo into this repo and link there from the readme. plenty of good cleanup could be done there!

**Comment by matkoniecz** [comment]
> maybe getting rid of the old v2 warning

Can be don/rejected by handling #2640 :)

**Comment by nilsnolde** [comment]
we have a demo server & frontend by now
