### ISSUE TITLE
valhalla_run_route: Support loading json query from a file 

### ISSUE THREAD

**Issue by giraldeau** [valhalla/valhalla#2655]
The utility valhalla_run_route accepts only json string on the command line, which is cumbersome and error prone. A more convenient method would be to load the json string from a file.

**Comment by nilsnolde** [comment]
Probably you’re really interested in valhalla_run_route, but are you aware of #2624 and #2648? Those let you run all actions from command line with file input. Didn’t make it to the docs yet:)

**Comment by giraldeau** [comment]
Ho I see, thanks for the info. It seems to do what I was looking for. I think this patch is still valuable, because it targets valhalla_run_route, but it would be nice to standardize the arguments between programs.

One thing to notice is that, because valhalla_service does not use boost options, it assumes it gets a path as a positional argument and the json string hits the file system, which is kind of weird:

```strace
openat(AT_FDCWD, "{\"locations\":[{\"lat\":40.044880,\"lon\":-76.284523,\"street\":\"PA 23 East\"},{\"lat\":40.044506,\"lon\":-76.283646,\"street\":\"Ranck Avenue\"}],\"costing\":\"auto\",\"directions_options\":{\"units\":\"miles\"}}", O_RDONLY) = -1 ENOENT (No such file or directory)
```

This patch uses two options to represent explicitly the intent of the user.

**Comment by kevinkreiser** [comment]
Yeah to be honest `valhalla_run_route` is such a frankenstein it needs to kind of be broken up into separate programs that fulfill a single task each. If you are really after just command line routing, valhalla_service will do the trick. That said, I agree with @giraldeau his PR is still useful to make `valhalla_run_route` more robust for those that need all the insane and very specific things it does.

**Comment by nilsnolde** [comment]
done apparently
