### ISSUE TITLE
How can I get all tags for an edge in Valhalla API response?

### ISSUE THREAD

**Issue by hnaderi268** [valhalla/valhalla#2657]
I'm using [trace attribute api](https://github.com/valhalla/valhalla-docs/blob/master/map-matching/api-reference.md) to do map matching. My problem is that Valhalla does not return all OSM tags (for example [oneway](https://wiki.openstreetmap.org/wiki/Key:oneway)) by default. How can I get these tags and the shape of each edge? To find out two-way edges' geometries is reversed or not?
My other problem is that how I can make Valhalla store non-[default OSM tags](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Valhalla)?

**Comment by kevinkreiser** [comment]
@hnaderi268 if you are looking for "all" tags for an edge im sorry to say that will not be possible. the only reasonable way to store a graph based on osm is to "normalize" the tags into a set of prescribed values which the algorithms can work on.

the problem of finding out whether an edge in a graph is one way and which direction of the edge is with/against the one way is possible to solve with valhalla (we do have that information). if you check out the `locate` api you can see which edges have forward auto access and which edges have reverse auto access. if an edge has both you can drive it in both directions. if it only has forward then you are driving with the one way and if it only has reverse then you are driving against a one way. if it has neither then its an edge that a car cannot drive on.

if you want valhalla to store arbitrary osm tags we have a new bit of code that allows you to store a finite number of those but we likely wont accept any PR that adds to the list unless it is strategic to the project. it would be possible though for you to fork the project and do something like is being done in #2639 but for your particular tags.

**Comment by hnaderi268** [comment]
Thanks, dear Kevin. It helped a lot. I'm going to try `locate` API to find out it's or not. There will be a lot of requests.
As you said oneway cases are obvious. But I was wondering about a two-way case. How I can find out I'm driving with/against the direction on the drawn way in OSM?
Thanks again! I don't think it's strategic, will join it on the client-side.
