### ISSUE TITLE
"400::Path distance exceeds the max distance limit" in a many-to-many call?

### ISSUE THREAD

**Issue by eugen-nw** [valhalla/valhalla#2672]
Hello everybody,

I've checked the docs and for this error it says "You want to travel further than this mode allows".  What does this mean please and more importantly what can I do to fix it?  The call that I'm sending is below my signature.  I try to compute all routes in a 10 x 10 matrix.

Thanks very much,  eugen

```
GET /sources_to_targets?json=%7B%22sources%22:[%7B%22lat%22:29.95688,%22lon%22:-95.26563%7D,%7B%22lat%22:30.21012,%22lon%22:-97.65215%7D,%7B%22lat%22:29.65339,%22lon%22:-95.56049%7D,%7B%22lat%22:29.68854,%22lon%22:-98.47636%7D,%7B%22lat%22:29.19741,%22lon%22:-98.82956%7D,%7B%22lat%22:31.75908,%22lon%22:-106.47312%7D,%7B%22lat%22:29.77225,%22lon%22:-95.22196%7D,%7B%22lat%22:29.29747,%22lon%22:-94.79128%7D,%7B%22lat%22:30.13665,%22lon%22:-95.6545%7D,%7B%22lat%22:32.88261,%22lon%22:-96.88756%7D],%22targets%22:[%7B%22lat%22:29.95688,%22lon%22:-95.26563%7D,%7B%22lat%22:30.21012,%22lon%22:-97.65215%7D,%7B%22lat%22:29.65339,%22lon%22:-95.56049%7D,%7B%22lat%22:29.68854,%22lon%22:-98.47636%7D,%7B%22lat%22:29.19741,%22lon%22:-98.82956%7D,%7B%22lat%22:31.75908,%22lon%22:-106.47312%7D,%7B%22lat%22:29.77225,%22lon%22:-95.22196%7D,%7B%22lat%22:29.29747,%22lon%22:-94.79128%7D,%7B%22lat%22:30.13665,%22lon%22:-95.6545%7D,%7B%22lat%22:32.88261,%22lon%22:-96.88756%7D],%22costing%22:%22truck%22,%22directions_options%22:%7B%22units%22:%22miles%22%7D%7D HTTP/1.1
```

**Comment by kevinkreiser** [comment]
@eugen-nw we have a crows-flys or bee-line or air-line or straight-line check at the beginning of the request that rejects requests that maybe too time consuming for the algorithm. this limit is completely configurable though. have a look inside your json configuration file. you'll find a bunch of places where it says: `max_matrix_distance`. you'll want to edit the one inside the `truck` section (as it looks like you are doing truck routing) to something larger. once you make this large enough (bigger than the distance between your two furthest away sources/targets) then you should be able to get the request through.

let us know if you have another question or if this doesnt resolve your issue!

**Comment by eugen-nw** [comment]
Thanks very much Kevin!  Is there a way to extend the max elements in a matrix calculation beyond 50?  I am interested only in distances and times at this point, so ideally I'd like to be able to compute the entire matrix of routes in one shot.

**Comment by kevinkreiser** [comment]
@eugen-nw yeah please read over our configuration generator it has descriptions of all the configuration options: https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_config#L480

**Comment by eugen-nw** [comment]
Fantastic!  Thanks again!

**Comment by eugen-nw** [comment]
What are distances expressed in please?  For trucks' matrix I see a quite impressive max. distance, yet my call is still failing: "max_matrix_distance": 400000.0

**Comment by kevinkreiser** [comment]
@eugen-nw please read the descriptions in the config file generator the units are listed there: https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_config#L479
