### ISSUE TITLE
Tile Cache

### ISSUE THREAD

**Issue by taraskarpuk** [valhalla/valhalla#2681]
```
2020/11/12 12:37:28.849065 [INFO] valhalla_server 2.4.3 starting on :8002
2020/11/12 12:37:28.970212 [INFO] Map name: EU-2019.21-12489
2020/11/12 12:37:28.970276 [INFO] Override file: /home/tmserver/.Tesla/data/map_override.pbf.gz
2020/11/12 12:37:28.972243 [INFO]    version { data_format_version: "1.0" transform_valhalla_version: "ValhallaUpdateOverrides/skip/update-overrides-0-gcc42cdd" datetime: "UTC 2020-11-02 12:36:56.686320" jobid: "jenkins-MapOverrides-1234" map_name: "EU-2019.21-12489" } prod_signed: false
2020/11/12 12:37:29.220063 [INFO] valhalla_server 2.4.3 ready..
2020/11/12 12:37:34.825207 [INFO] route request(p)
2020/11/12 12:37:34.827988 [ANALYTICS] location_distance::0.900835km
2020/11/12 12:37:35.309234 [INFO] SimpleTileCache::Put: 6711602, new cache_size: 228827
2020/11/12 12:37:35.966647 [INFO] SimpleTileCache::Put: 6723122, new cache_size: 491067
Segmentation fault
```

Hello. I am trying to build custom maps for Tesla, they use valhalla engine for navigation. But some regions is not supported and don't have navigation. 

So, i want try understand tile bin structure and debug why valhalla crash

**Comment by danpat** [comment]
@taraskarpuk it's highly likely that they would be using a fork with a modified tile format - I suspect it's unlikely you'll get the public Valhalla code to generate tiles that are compatible, or use tiles extracted from the firmware with the public Valhalla code.

**Comment by kevinkreiser** [comment]
@taraskarpuk the best place to look about the binary format would be the `baldr` namespace. In there we define several `struct`s which we can memory map directly from tile data on the target device. please have a look at `GraphTile` and the other structs that it encapsulates.

i would warn that it is very easy to make changes to one of these binary structures that breaks compatibility. so its entirely possible that the router that you are working with is expecting a different (in every so slight ways) format of GraphTile

**Comment by taraskarpuk** [comment]
I hope Tesla will publish his fork, but seems it will never be published...

**Comment by kevinkreiser** [comment]
@taraskarpuk you may try older versions of valhalla until you find a version that works. there is still no gaurantee you will find such a version though

**Comment by taraskarpuk** [comment]
![image](https://user-images.githubusercontent.com/54291012/98996735-06f64380-253c-11eb-86ab-12129c30212a.png)
Seems like headers different for tiles, maybe some docs for build params is located ( I've not find that :( )

**Comment by kevinkreiser** [comment]
@taraskarpuk headers will be different for different tiles, they hold information about what is contained in the tile, like counts and things so its no surprize the tile header is different in my opinion

**Comment by treestryder** [comment]
Tesla has an old Valhalla fork here.
https://github.com/teslamotors/valhalla
