### ISSUE TITLE
LocateApi Issue

### ISSUE THREAD

**Issue by arash1892** [valhalla/valhalla#2684]
Hello guys,

In Locate API response, for each point ( which has been mapped match with trace_attribute API), we receive multiple edges in edges list, why is the reason? Also the way_id field for these edges are the same, but it has differences in some fields like "forward".

We expect to get one edge per each point.

**Comment by kevinkreiser** [comment]
@arash1892  our graph is a bidirectional, that means every "edge" in the graph has two directions stored. that is why you see differences in the forward and reverse directions between the two results. both results are the same edge its just you can traverse it in both directions
