### ISSUE TITLE
Correct way of using preferred_side option

### ISSUE THREAD

**Issue by sambestsolutions** [valhalla/valhalla#2686]
Hi
I am trying to figure out how preferred_side option impacts routes in route and optimized_route apis. I expect below locations to return route ignoring road direction but it gives the same route always considering the road direction. Is there anything wrong that I am trying to do here or should I pass any other parameter to get route ignoring the road direction. 

Below are the two locations  and request that I am working with

```
{
  "locations": [
    {
      "lat": 6.845758147943897,
      "lon": 79.94561389094088,
      "preferred_side": "either"
    },
    {
      "lat": 6.846011141099631,
      "lon": 79.94654461746904,
      "preferred_side": "either"
    }
  ],
  "costing": "auto",
  "directions_options": {
    "units": "kilometer"
  },
  "id": "my_work_route"
}
```

**Comment by sambestsolutions** [comment]
can someone help on this

**Comment by kevinkreiser** [comment]
@sambestsolutions please read the documentation, especially this section: https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#locations

**Comment by sambestsolutions** [comment]
@kevinkreiser  Thanks for the reply. I read the documentation before posting and I thought by setting `"preferred_side": "either"` ,  it is possible to get the route no matter what the direction of road. 
So this option will work road should be twoway and need to set `street_side_tolerance` parameter to specify the side from centerline?
