### ISSUE TITLE
Edges Field in Trace Attribute Response

### ISSUE THREAD

**Issue by arash1892** [valhalla/valhalla#2694]
Hi guys

I have a question about Trace Attribute response. For some requests, we have multiple same edges continuously, why is the reason?
As an example, if we request theses points , we will have multiple same answers for "246310839" way id continuously.

[test.txt](https://github.com/valhalla/valhalla/files/5577667/test.txt)

**Comment by kevinkreiser** [comment]
ways are not edges. a way can become multiple edges, where other ways intersect it. every osm node that is referenced more than once, ie included in a way (even the same one), becomes an intersection or node in the graph. an edge is the section of a way between two nodes in the graph.

![image](https://user-images.githubusercontent.com/697548/99878344-aff30d00-2bd2-11eb-8d3f-120e089f8f30.png)

above i have highlighted a way on osm. notice that there are multiple white ways that intersect it. a new pair of edges is created on either side of those intersections. here you can see there will be 5 edges along that single yellow colored way in the final graph. every one of those edges has the same wayid but a different edge id.
