### ISSUE TITLE
Null pointer dereference in case of no available tiles in GraphReader::AreEdgesConnected

### ISSUE THREAD

**Issue by averkhaturau** [valhalla/valhalla#2695]
In case of offline navigation it's possible that not all needed tiles are yet downloaded when AreEdgesConnected is called. This lead to dereference attempt of null pointer, which is undefined behavior in C++. 
In Valhalla GraphReader::AreEdgesConnected is used to choose the routing algorithm, so I assume that returning false in case of unavailable tile is acceptable.

**Comment by danpaz** [comment]
Fixed in https://github.com/valhalla/valhalla/pull/2696
