### ISSUE TITLE
Is there a lightweight "getting started" guide?

### ISSUE THREAD

**Issue by nemosmithasf** [valhalla/valhalla#2704]
I've combed through the docs and its pretty dense and unapproachable.

I was wondering if there is some sort of "getting started" guide that serves as a place for new users to land.

Some examples from Graphhopper and OSRM which I found really helpful:
https://github.com/graphhopper/graphhopper/blob/0.11/docs/web/quickstart.md
https://hub.docker.com/r/osrm/osrm-backend/

**Comment by nilsnolde** [comment]
I kinda agree, it can be fairly overwhelming in the beginning. The [docs](https://github.com/valhalla/valhalla/blob/master/docs) explain the API very well, not so much the setup though. Pretty sure PRs are always welcome to improve that.

#shamelessplug: we started a small series of valhalla tutorials a while back: https://gis-ops.com/tutorials/routing-tutorials/. There's a few deprecated things in there (like building the node bindings).. Good thing is you can PR fixes to the tutorials:)

Another way of low-barrier is docker: https://github.com/gis-ops/docker-valhalla. Might be less intimidating. Also roaming through it's dockerfile and docker-entrypoint script gives you a good idea about the processing steps.
