### ISSUE TITLE
/status endpoint for general info

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2736]
I think it'd be great to have an endpoint for some general info, with a response like

```json
{
  "status": "ready",
  "version": "3.0.9",
  "bbox": [
    -180,
    -90,
    180,
    90
  ],
  "has_admins": true,
  "has_timezones": true,
  "has_xxx": ...
}
```

Esp the bbox (of the graph) and the graph properties, has_admins etc, would be really good. I regularly forget how I set up a certain valhalla instance.. What do you think? 

when's 3.1.0 scheduled btw?;)

**Comment by kevinkreiser** [comment]
I had a similar idea a little while ago in which we would just return the whole valhalla.json config but I like what you suggest where we actually return some useful informationa bout what is loaded in the data.

we could compute the bounding box and cache it by actually looping over the whole dataset. we could also check some tiles to see if they have admins and timezones while we are getting that bbox. we could also check if there are any transit tiles in the tile set and remove that god aweful "transit available" endpoint. 

anyway yeah i think i would cache this data after the first call as its expensive to get. though i could totally see some fields being cheap and somethign we should get on the fly, like a healthcheck

**Comment by kevinkreiser** [comment]
oh also, long long ago we did have a status endpoint but it didnt do anything interesting so we removed it iirc

**Comment by nilsnolde** [comment]
oops, right, that's pretty expensive! how long you figure that'd take approx for the planet?

if it's >> 1 second, should that maybe be part of the warm-up phase? or let some poor person sweat it out on the first `/status` request?

**Comment by kevinkreiser** [comment]
so we have a list of all the endpoints in the config file, i guess if the /status endpoint is in that list then we could cache it. for me it takes about 10-20 seconds to get this info in a brute force way. there is a quicker algorithm that only looks at the tiles on the edges of the tileset. i assume such an implementation would take way less than a second

**Comment by nilsnolde** [comment]
Should we start talking about the contents of a new status endpoint, now the base work has been done (#2907)? I frequently wish for a few details of loaded datasets without hitting the `/locate` endpoint (such as elevation, admin, timezone etc, some of the configurable build options).

My wishlist would be:
- `version` (string)
- `bbox` (float array): the bounding box for the loaded dataset (with the downside of too big bboxes for regional extracts I guess)
- `has_admins` (bool): check one tile if it has admin info
- `has_timezones` (bool)
- `has_predicted_traffic` (bool)
- `has_live_traffic` (bool)
- `endpoints` (array of str)

Lots of more interesting configs (like `service_limits`). Printing the valhalla.json would also work for most things, but it would not tell you if the tileset actually has admins/timezones etc, only the path.

**Comment by kevinkreiser** [comment]
@nilsnolde maybe we could have something like

```json
{
	"version": "foobarbaz",
	"config": {...whole config file here...},
	"data_coverage": []
}
```

It doesnt answer some of the questions about does it actually have admin info built into the dataset because technically you can set the config option but it doesnt have to have been loaded in the data, same for timezones, traffic, etc

**Comment by nilsnolde** [comment]
> but it doesnt have to have been loaded in the data

Thinking about _our_ use cases, that's actually the most important info (next to bbox/data_coverage). I often deploy valhalla with docker (when it's a few users using it, not like a public 1000s of users API), and there I can't really comprehend if the path was _just set_ for admin/timezone etc (they're set by default) or actually _used_. 

I didn't look at how to do it yet with valhalla's API, but I imagine that'd be quite a cheap check?! Or is there another reason why you'd not include that sort of info? I wasn't quite explicit about it, but I'd be happy to contribute the implementation.

**Comment by kevinkreiser** [comment]
most of the ones you are looking for are pretty cheap yes. for some of the traffic ones it could be tricky, historical data could be there in one tile but not another so you'd have to scan all the tiles to be sure which is definitely not feasible. live traffic we can detect via the file being present. as for the bounds of the tileset, this is tricky. there are modes of operation where the tileset bounds change over time. it would be potentially very annoying to update this geometry as part of that but i didnt look into it deeply. for the other modes of tiles where its a static dataset you could do it once and cache the result. so anyway varying degrees of complication depending :smile:

**Comment by nilsnolde** [comment]
Right, at least predicted traffic seems unfeasible.. I'll soon look into the others
