### ISSUE TITLE
geos3.9 changes: geos/opLinemerge.h was deleted

### ISSUE THREAD

**Issue by ImreSamu** [valhalla/valhalla#2739]
Hi,

Testing the brand new [geos3.9](https://github.com/libgeos/geos/releases/tag/3.9.0) + current valhalla master
I see this error message:
`/src/valhalla/src/mjolnir/valhalla_build_admins.cc:35:10: fatal error: geos/opLinemerge.h: No such file or directory`

As I see this file was deleted in Geos3.9 ( exist in geos3.8 )
* ticket: https://trac.osgeo.org/geos/ticket/999#ticket
* https://github.com/libgeos/geos/pull/242 
   * `include/geos/opLinemerge.h` : This file was deleted.

As I see the [ `ubuntu:21.04` ; `debian:bullseye` ] (docker images)  have been updated to geos=3.9 
so a `missing geos/opLinemerge.h` file message expected.

I don't know what is the ideal fix; so I hope somebody can fix.

Thanks in advance

Details:

```bash
[ 87%] Linking CXX executable valhalla_service
In file included from /src/valhalla/src/mjolnir/valhalla_build_admins.cc:25:
/usr/include/geos/geom/Geometry.h:26:3: warning: #warning "The GEOS C++ API is unstable, please use the C API instead" [-Wcpp]
   26 | # warning "The GEOS C++ API is unstable, please use the C API instead"
      |   ^~~~~~~
/usr/include/geos/geom/Geometry.h:27:3: warning: #warning "HINT: #include geos_c.h" [-Wcpp]
   27 | # warning "HINT: #include geos_c.h"
      |   ^~~~~~~
/src/valhalla/src/mjolnir/valhalla_build_admins.cc:35:10: fatal error: geos/opLinemerge.h: No such file or directory
   35 | #include <geos/opLinemerge.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/valhalla_build_admins.dir/build.make:82: CMakeFiles/valhalla_build_admins.dir/src/mjolnir/valhalla_build_admins.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1147: CMakeFiles/valhalla_build_admins.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object CMakeFiles/valhalla_build_statistics.dir/src/mjolnir/statistics.cc.o
```

**Comment by sebastian-meier** [comment]
I also had to find a workaround for this until its officially fixed. I changed only few lines of code and was able to successfully build and use valhalla to generate routing tiles for Germany and use the service afterwards, no problems so far. I have documented the fixes in a commit on my personal fork:

https://github.com/sebastian-meier/valhalla/commit/ab7d72d6de920ec2791bf13cde512812faa2a0a1

**Comment by kevinkreiser** [comment]
@ImreSamu @sebastian-meier we should be able to handle this with `ifdef`s on the geos version define, does anyone care to PR that?

**Comment by ImreSamu** [comment]
@kevinkreiser : 

> does anyone care to PR that?

honestly,  I have  ~minimal knowledge - about `c++` ;  so I am leaving this task for others ..

on the other hand - I can help in the testing part (  adding a "bullseye + geos3.9 based"  -  `Dockerfile-build` test image +  improving  `./docker/install-shared-deps.sh` )

**Comment by sebastian-meier** [comment]
@kevinkreiser 
> @ImreSamu @sebastian-meier we should be able to handle this with `ifdef`s on the geos version define, does anyone care to PR that?

same here @ImreSamu  i am also not a c++ expert, i use the valhalla system for a node.js/javascript based system. I am happy to help if somebody leads the way...

**Comment by kaligrafy** [comment]
on macos, brew upgrade did update geos to 3.9, so I can't compile valhalla in the meantime. It is also very hard to go back to geos3.8 in brew.

**Comment by kevinkreiser** [comment]
@ktatterso is working on the changes to use the preprocesor with the version string to have it build on old as well as new versions. I expect him to push up a PR realatively soon!

**Comment by ImreSamu** [comment]
now it is OK.

I have re-tested with the current valhalla master : 
* debian:bullseye:  with  `libgeos-3.9.0/now 3.9.0-1 amd64 [installed,local]`   :heavy_check_mark: 
* ubuntu:21.04 (Hirsute Hippo) :   with `libgeos-3.9.0/now 3.9.0-1 amd64 [installed,local]`  :heavy_check_mark: 

And thank you for the related fixes: https://github.com/valhalla/valhalla/pull/2783 https://github.com/valhalla/valhalla/pull/2787
