### ISSUE TITLE
Boost.Geometry requires C++14 from 1.75 on (latest)

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2747]
While working on avoid_polygons, I encountered this from [boost.geometry](https://github.com/boostorg/geometry):

`CAUTION: Boost.Geometry in Boost 1.73 deprecates support for the C++03 and will require C++14 from Boost 1.75 onwards (see issue #590).`

Systems with an actual package/dep manager will be affected rather sooner than later I guess.. Is that gonna be a problem for Valhalla? If it's not c++14 ready yet, maybe pull the affected (header) packages to `third_party`?

**Comment by kevinkreiser** [comment]
We're already using c++14: https://github.com/valhalla/valhalla/blob/master/CMakeLists.txt#L19

But we only target boost 1.51. Do you actually need a newer boost for the geometry support? If we do need to update the boost version we'll need to do a pretty rigorous regression testing. Let me know if we need to get onto a newer boost, if so we should open up a separate pr just for that ahead of the polygons work.

**Comment by nilsnolde** [comment]
No, that's fine for me (as of now).. Didn't see the entry in CMakeLists, thx. Was just getting worried Fedora/Arch compilation might break soon;)
