### ISSUE TITLE
Coordinates for each instruction in a journey ?

### ISSUE THREAD

**Issue by BaptisteB-A** [valhalla/valhalla#2749]
Hi,
I'm being part of the Navitia team, and I'm looking for a way to get coordinates, lon & lat, of a location for each instruction in a journey. Is there such a thing ? I've seen there is a `Location` type in trip.proto. Could it be somehow linked with coordinates ?

Thanks in advance

**Comment by dnesbitt61** [comment]
Are you looking for how to get the lat,lng at the start of each maneuver / instruction? If so, then each maneuver within each trip leg has a begin_shape_index which allows you to get the lat,lng at the start of the instruction by indexing into the decoded shape/geometry array of lat,lng coordinates.

**Comment by xlqian** [comment]
Thank you for your answer. I'd like to go a little bit further with that question. We're actually looking for a location(lat,lng) where the maneuvers/instructions will be announced, just imagine that we'd like to build an app for route guidance with Valhalla, the instructions must be announced to the driver in advance. Is that location available somewhere? If it's not the case, we'd love to make some contributions.

**Comment by nilsnolde** [comment]
Isn't that better done on the client side? There you can even take all the fancy device things into consideration, like current speed etc to decide when to give the pre-alerts

**Comment by xlqian** [comment]
that's actually an alternative that we thought... the previous answer was good enough for us so far.
