### ISSUE TITLE
Make Python bindings more useful: build tiles & config from python API

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2753]
I was about to write a blog post on how to use Valhalla with Python without going through the trouble of building it yourself, using our docker image, mapping some volumes etc. I quickly realized what a mess that'll be..

To start making the bindings more useful in a stand-alone manner (and eventually as PyPI wheels?), as a minimum, they should be able to:
- build a config file (sweet it's already a python script..)
- build tiles

Building admins and timezones would be nice too, but limited to mac/linux and a whole lot more dependencies.. Also those are almost static and could actually be downloaded by the python API if there was a central storage somewhere..

I looked into it: a few changes to python.cc and 1 more python module, that's it (hail pybind11!). I'll PR soon..

**Comment by nilsnolde** [comment]
oops, related side issue: somewhere along the way `valhalla_build_config` lost its `tyr`member, which the python bindings use for setting the global logger.. I'll use `mjolnir`s logging settings then for now..

**Comment by kevinkreiser** [comment]
@nilsnolde yes we got rid of the tyr member when we removed the tyr worker from the project and just had odin do the serialization. maybe loki makes more sense since its used in the serivce applications to configure the logger

**Comment by nilsnolde** [comment]
config is built through the bindings. building tiles maybe some day.
