### ISSUE TITLE
Linker issues with libprotobuf (windows build)

### ISSUE THREAD

**Issue by porkedpie** [valhalla/valhalla#2764]
Building on windows, the libprotobuf linker dependenices cause breaking errors during compilations.
I am not a cmake expert but I think it's messing up the use of libprotobuf vs libprotobuf-lite.
Compiles fine via Visual Studio if you add libprotobuf.lib linker dependency for the relevant projects which are:
- valhalla_benchmark_admins
- valhalla_convert_transit
- valhalla_build_tiles
- valhalla_build_statistics
- valhalla_build_admins
- valhalla_validate_transit
- valhalla_fetch_transit

Example reproduce steps:
1. Download the rep:
`cd C:\dev`
`git clone --recurse-submodules https://github.com/valhalla/valhalla.git`
2. Install dependenices using vcpkg. (Mine is in dev/)
`cd valhalla-master`
`C:\dev\vcpkg\vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"`
3. Configure build with CMake
`mkdir build `
`"C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DENABLE_TOOLS=ON -DENABLE_DATA_TOOLS=ON -DENABLE_PYTHON_BINDINGS=ON -DENABLE_HTTP=ON -DENABLE_CCACHE=OFF -DENABLE_SERVICES=OFF -DENABLE_BENCHMARKS=OFF -DENABLE_TESTS=OFF -DLUA_LIBRARIES=C:\dev\vcpkg\installed\x64-windows\lib\lua51.lib -DLUA_INCLUDE_DIR=C:\dev\vcpkg\installed\x64-windows\include\luajit -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -HC:/dev/valhalla-master -BC:/dev/valhalla-master/build -G "Visual Studio 16 2019" -T host=x64 -A x64`
4. Try to compile.
Either 
`cd build`
`cmake --build .`
Or open with VS and Build Solution.

Result - 300ish linker errors for libprotobuf.

Solution which works - right click each affected project (as above) in Solution Explorer -> Properties. Linker -> Input -> Additional Dependencies. Edit and add path to libprotobuf.lib. e.g. for me C:\dev\vcpkg\installed\x64-windows\lib\libprotobuf.lib.

If I know anything about CMake I would suggest how this can be fixed in the build config, but I don't I'm afraid.

**Comment by nilsnolde** [comment]
huh, there might one more glitch in the README.. Generally you can get a good feeling for how a specific system is working looking at its CI jobs. For win you'll see that it checks out a vcpkg commit (which is how it versions stuff..):
https://github.com/valhalla/valhalla/blob/6fa12b16f8babf2079e9591c60f635550824e71c/.azure-pipelines.yml#L49

Sounds like smth might be wrong in the protobuf cmake finder for your current vcpkg version.

Failing that, try to specifically set the protobuf lib (& headers if needed), see [here](https://cmake.org/cmake/help/latest/module/FindProtobuf.html). Also not an expert really, but I think it's enough to use the protobuf-lite version, e.g.:
```
-DProtobuf_INCLUDE_DIRS=C:\dev\vcpkg\installed\x64-windows\include  # headers
-DProtobuf_LITE_LIBRARIES=C:\dev\vcpkg\installed\x64-windows\lib\libprotobuf-lite.lib   # (if that's even included..)
# or even
-DProtobuf_LIBRARIES=C:\dev\vcpkg\installed\x64-windows\lib\libprotobuf.lib
```

**Comment by porkedpie** [comment]
Well to answer your question, libprotobuf-lite.lib is included. (It is present in that directory and it is included as a linker dependency by cmake). But on compiling it's looking for libprotobuf.lib (non-lite) instead and failing to find it.

`-DProtobuf_LIBRARIES=C:\dev\vcpkg\installed\x64-windows\lib\libprotobuf.lib`
Worked fine for me.


Bit strange. Maybe a similar issue to why the DLUA_LIBRARIES config is also needed explicitly.

**Comment by nilsnolde** [comment]
No idea why cmake is finding some perfectly fine, others not at all.. 

You might still want to actually work with the same versions as this repo's CI or you could encounter other nasty issues like https://github.com/valhalla/valhalla/issues/2739.. I'll fix the README soon.

**Comment by nilsnolde** [comment]
closing for housekeeping, feel free to open again if it didn't fix
