### ISSUE TITLE
Use ninja in azure jobs

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2778]
I just tried ninja for the first time on windows and it cut down the compile time from ~20 mins to ~5 mins.. If there's no other serious drawbacks I'm not aware of we could swap compilers on CI.  

Also not sure if/how well etc VS can cache build files, but ninja is pretty good at it from all I saw so far, so we could even cache the build folder, that should get most win builds down to << 5 mins. any concerns @mloskot, @kevinkreiser ?

**Comment by kevinkreiser** [comment]
i have zero concerns about this, ship it. i use ninja from time to time on linux and have no problems with it.

**Comment by mloskot** [comment]
Ninja is a great choice
