### ISSUE TITLE
Avoid CI on unrelated changes

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2793]
Happens quite often that we commit things that are wasting precious CI hours, but def don't deserve to be tested and some part of me starts weeping.. I'd propose to skip CI builds when changing .md and/or other unrelated files. I already had a look into it here: https://github.com/valhalla/valhalla/pull/2763#issuecomment-756804568

I'll do it if you agree.

**Comment by nilsnolde** [comment]
Capture some research:
CircleCI: https://support.circleci.com/hc/en-us/articles/360015562253-Conditionally-end-a-running-job-gracefully
GH Actions: https://stackoverflow.com/questions/62968897/is-it-possible-to-not-run-github-action-for-readme-updates
Extrawurst Azure: https://stackoverflow.com/questions/62044055/is-it-possible-to-cancel-a-azure-devops-pipeline-job-programmatically :roll_eyes:

**Comment by mandeepsandhu** [comment]
+1 from my side (you dont need to go through CI hoops if you've say, changed something in the docs or the README).

Do you have initial list of files dirs that don't require running CI?

**Comment by kevinkreiser** [comment]
:ship:

**Comment by nilsnolde** [comment]
> Do you have initial list of files dirs that don't require running CI
Changelog would be enough already;) Wildcard *.md I think to start with.. Glancing at the rest it's pretty much all used in the builds (with the exception of very few half-dead scripts), whiich is a great sign I think, very little orphans:)

**Comment by mandeepsandhu** [comment]
> > Do you have initial list of files dirs that don't require running CI
> 
> Changelog would be enough already;) Wildcard *.md I think to start with.. Glancing at the rest it's pretty much all used in the builds (with the exception of very few half-dead scripts), whiich is a great sign I think, very little orphans:)

changelog & markdown files seem like a good start! :+1:

**Comment by nilsnolde** [comment]
kinda there with circleci
