### ISSUE TITLE
rapidjson_utils writer_wrapper_t build errors

### ISSUE THREAD

**Issue by jfamiglietti** [valhalla/valhalla#2798]
There are some overloaded call operators (`operator()`) that invoke `writer.String(...)` with incorrect types. The libraries and tools build ok, but does not build when I integrate Valhalla with my own project.

`(error: no matching member function for call to 'String')`

There are a number of them starting at line 331 in rapidjson_utils.h.

I have fixed it locally and will open a pull request shortly.

**Comment by PureW** [comment]
I ran into this as well. Try `-D RAPIDJSON_HAS_STDSTRING=1` in your consuming code so that the internal representation of rapidjson changes to the correct one.

**Comment by jfamiglietti** [comment]
Ok, that did it! Thanks a lot!
