### ISSUE TITLE
"Valhalla-Routing's Project" on maproulette is full of false positives

### ISSUE THREAD

**Issue by matkoniecz** [valhalla/valhalla#2800]
I tried to contact via built-in contact owner but I run into https://github.com/osmlab/maproulette3/issues/1520 and it sems to be operated by you or at least by someone using your name

See for example https://maproulette.org/challenge/983/task/1245787 - it is  a false positive

This challenge is misdesigned and generates large amount of false positives.

Crossing of oneways going in opposite directions is considered as error, even if crossing has two way or other oneway roads

Note https://maproulette.org/browse/challenges/983 - 165 fixed, 436 not an issue - and 20230 tasks sitting since 2016. It should be fixed and regenerated.

**Comment by matkoniecz** [comment]
I will close it as it is not a bug in your software and I contacted this (abandoned probably) account, but you may wish to do something (ask maproulette operators to take it down?) as something really badly designated is operating under your name

**Comment by kevinkreiser** [comment]
we did the maproulette integration many years ago at this point and we no longer maintain it. i think the code still lives in our data processing... but we don't do anything with it. im certain that we did make the account but as you noticed we've abandoned it. sorry for not tidying that up, sometimes things just get away from you.

**Comment by matkoniecz** [comment]
Would you be OK with taking it down? I can try asking maproulette admins to do this if you agree.

At least in my city first impression of maproulette is this set of tasks, all of them not really reporting any real issues.
