### ISSUE TITLE
Valhalla Contry Name 

### ISSUE THREAD

**Issue by taraskarpuk** [valhalla/valhalla#2805]
Hey. I am building maps for Tesla Navigation. I am using http://download.geofabrik.de/ pbf files for creating tiles, it works, but can't get right country name (ex. Country = "???"). How i can rename country everywhere ?

**Comment by taraskarpuk** [comment]
2021-01-26_02:06:06.56272-0800 2021/01/26 02:06:06.562609 [ANALYTICS] admin_state_iso::
2021-01-26_02:06:06.56284-0800 2021/01/26 02:06:06.562707 [ANALYTICS] admin_country_iso::

**Comment by nilsnolde** [comment]
Did you build the admin db? You can check that, it's just an sqlite. Chances are the geofabrik extract doesn't include the full OSM country relation bcs it was cropped (there are issues about that). Generally it's safest to generate the admin db from the planet file (takes around 4-5 h on a small spec server), then you can be sure to include all countries. A more serious issue for not having a proper admin db is that you get false instructions in roundabouts (also here you'll find issues in the repo).

**Comment by taraskarpuk** [comment]
so, i need take planet.pbf file and make valhalla_build_admins, after that run valhalla_build_tiles ?

**Comment by nilsnolde** [comment]
That's what I'd do. Least effort and it will work. The admin db (and timezone) are pretty much static anyways, so you can keep them around for a long time without regenerating them. You'll have to point the config json to the right database, but you'll figure that out from documentation.

I'll close, feel free to open if it didn't solve your issue. Positive feedback also appreciated:)

**Comment by taraskarpuk** [comment]
Well, same situation.. Well is it possible to extract admin.sql from existing tiles? To see what structure is here?

**Comment by nilsnolde** [comment]
No that's not possible. Right, I forgot you're trying to jailbreak your tesla;) In case you're using this repo's code to produce the tiles **and consume** them, that'd be odd. But you're not are you? No idea what Tesla did to the tile schema behind closed doors.

**Comment by taraskarpuk** [comment]
Well, i think i need more research for it. Navigation is works fine... but country name. Tesla is lazy and i don't think, that they changed tile structure. Hmm. Should Tesla post their modification of valhalla to their github repo?

**Comment by nilsnolde** [comment]
If "should" = "they're obliged to", no. But of course that'd make the life of hacky tesla owners a lot smoother:) So, producing tiles with the original valhalla master works for navigation in a tesla? That'd be great already (and very suprising)!

**Comment by taraskarpuk** [comment]
i will use tesla fork from teslamotors github. Building :)

**Comment by taraskarpuk** [comment]
Well, it's not hack i think. Just want to use navigation in my tesla, in Moscow... But they don't support that region :(

**Comment by taraskarpuk** [comment]
```
2021/01/26 18:54:56.735946 [INFO] Parsing files: reunion-latest.osm.pbf
2021/01/26 18:54:56.736028 [INFO] Parsing ways...
Segmentation fault (core dumped)

```

**Comment by taraskarpuk** [comment]
So. Maybe some ideas i could debug in while it builds ? Or hardcode Country ISO for all tiles ?

**Comment by taraskarpuk** [comment]
`{
  "mjolnir": {
    "max_cache_size": 200000000,
    "global_synchronized_cache": true,
    "connectivity_map": false,
    "tile_dir": "/data/valhalla",
    "admin": "/data/valhalla/admin.sqlite",
    "timezone": "/data/valhalla/tz_world.sqlite",
    "transit_dir": "/data/valhalla/transit",
    "logging": {
      "type": "std_out",
      "color": true
    }
  },
  "additional_data": {
    "elevation": "/data/valhalla/elevation/"
  },
  "loki": {
    "actions":["locate","route","one_to_many","many_to_one","many_to_many","sources_to_targets","optimized_route","isochrone","trace_route","trace_attributes","probable_path"],
    "use_connectivity": "false",
    "service_defaults": {
      "radius": 0,
      "minimum_reachability": 50
    },
    "logging": {
      "type": "std_out",
      "color": true,
      "long_request": 86400.0
    },
    "service": {
      "proxy": "ipc:///tmp/loki"
    }
  },
  "skadi": {
    "actions":["height"],
    "logging": {
      "type": "std_out",
      "color": true,
      "long_request": 86400.0
    },
    "service": {
      "proxy": "ipc:///tmp/skadi"
    }
  },
  "thor": {
    "logging": {
      "type": "std_out",
      "color": true,
      "long_request": 86400.0
    },
    "service": {
      "proxy": "ipc:///tmp/thor"
    }
  },
  "odin": {
    "logging": {
      "type": "std_out",
      "color": true
    },
    "service": {
      "proxy": "ipc:///tmp/odin"
    }
  },
  "meili": {
    "mode": "multimodal",
    "customizable": ["mode", "search_radius", "turn_penalty_factor", "gps_accuracy", "sigma_z", "beta", "max_route_distance_factor", "max_route_time_factor"],
    "verbose": false,
    "default": {
      "sigma_z": 4.07,
      "gps_accuracy": 5.0,
      "beta": 3,
      "max_route_distance_factor": 3,
      "max_route_time_factor": 5,
      "max_search_radius": 100,
      "breakage_distance": 2000,
      "interpolation_distance": 10,
      "search_radius": 10,
      "geometry": false,
      "route": true,
      "turn_penalty_factor": 0,
      "altpaths_timeout_secs": 2
    },
    "auto": {
      "turn_penalty_factor": 200,
      "search_radius": 50
    },
    "pedestrian": {
      "turn_penalty_factor": 100,
      "search_radius": 25
    },
    "bicycle": {
      "turn_penalty_factor": 140
    },
    "multimodal": {
      "turn_penalty_factor": 70
    },
    "logging": {
      "type": "std_out",
      "color": true
    },
    "service": {
      "proxy": "ipc:///tmp/meili"
    },
    "grid": {
      "size": 500,
      "cache_size": 10240
    }
  },
  "tyr": {
    "logging": {
      "type": "file",
      "file_name": "/var/log/valhalla.log",
      "reopen_interval": 60,
      "long_request": 86400.0
    },
    "service": {
      "proxy": "ipc:///tmp/tyr"
    }
  },
  "httpd": {
    "service": {
      "listen": "tcp://127.0.0.1:8002",
      "loopback": "ipc:///tmp/loopback",
      "interrupt": "ipc:///tmp/interrupt"
    }
  },
  "service_limits": {
    "auto": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "auto_shorter": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "auto_biased": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "bus": {
      "max_distance": 5000000.0,
      "max_locations": 50,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "hov": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "pedestrian": {
      "max_distance": 250000.0,
      "max_locations": 50,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50,
      "min_transit_walking_distance": 1,
      "max_transit_walking_distance": 10000
    },
    "bicycle": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "multimodal": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "transit": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "truck": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_locations": 50
    },
    "skadi": {
      "max_shape": 750000,
      "min_resample": 10.0
    },
    "isochrone": {
      "max_contours": 4,
      "max_time": 120,
      "max_distance": 25000.0,
      "max_locations": 1
    },
    "trace": {
      "max_distance": 5000000.0,
      "max_gps_accuracy": 100.0,
      "max_search_radius": 100.0,
      "max_shape": 750000,
      "max_best_paths": 4,
      "max_best_paths_shape": 100
    },
    "max_avoid_locations": 50,
    "max_reachability": 100,
    "max_radius": 200
  }
}
`

**Comment by taraskarpuk** [comment]
here config, what i found that tesla use

**Comment by nilsnolde** [comment]
Honestly it's hard to help you here, as we don't know which projects you're running/building with, teslamotor's (super old) fork or this master or.. I can tell you that tesla definitely changed a lot in the repository without disclosing it: half of those actions don't exist here `["locate","route","one_to_many","many_to_one","many_to_many","sources_to_targets","optimized_route","isochrone","trace_route","trace_attributes","probable_path"]`, so they added a lot of matrix stuff. which is a pity, this repo could really benefit from that.

**Comment by kevinkreiser** [comment]
The other matrix actions are depricated aliases to sources to targets which handles all those special cases. Probable path is the only new one that I can tell here. But yeah it's a pitty
