### ISSUE TITLE
Make fails in Ubuntu 16.04

### ISSUE THREAD

**Issue by EdoardoSerri** [valhalla/valhalla#2809]
Hello,

I am trying to install Valhalla on Ubuntu 16.04, but at some point when I run `make -j$(nproc)` it starts giving me errors until it exits completely, giving me error 2. Am I missing something? 
Here the error part until the exit code.

Thanks in advice for the help, hoping is not a bug or something.

[ 47%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/elevationbuilder.cc.o
In file included from /usr/include/c++/5/bits/hashtable.h:35:0,
                 from /usr/include/c++/5/unordered_map:47,
                 from /home/son/valhalla/src/loki/worker.cc:7:
/usr/include/c++/5/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> >’:
/usr/include/c++/5/type_traits:137:12:   required from ‘struct std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > >’
/usr/include/c++/5/type_traits:148:38:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
/usr/include/c++/5/bits/unordered_set.h:95:63:   required from ‘class std::unordered_set<valhalla::Options_Action>’
/home/son/valhalla/valhalla/loki/worker.h:70:39:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<valhalla::Options_Action>) (const valhalla::Options_Action&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                                  ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_function.h:60,
                 from /usr/include/c++/5/functional:49,
                 from /usr/include/boost/property_tree/ptree_fwd.hpp:17,
                 from /usr/include/boost/property_tree/ptree.hpp:15,
                 from /home/son/valhalla/src/loki/worker.cc:1:
/usr/include/c++/5/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’:
/usr/include/c++/5/bits/unordered_set.h:95:63:   required from ‘class std::unordered_set<valhalla::Options_Action>’
/home/son/valhalla/valhalla/loki/worker.h:70:39:   required from here
/usr/include/c++/5/type_traits:148:38: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > >’
     : public integral_constant<bool, !_Pp::value>
                                      ^
In file included from /usr/include/c++/5/unordered_set:48:0,
                 from /home/son/valhalla/src/loki/worker.cc:8:
/usr/include/c++/5/bits/unordered_set.h: In instantiation of ‘class std::unordered_set<valhalla::Options_Action>’:
/home/son/valhalla/valhalla/loki/worker.h:70:39:   required from here
/usr/include/c++/5/bits/unordered_set.h:95:63: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef __uset_hashtable<_Value, _Hash, _Pred, _Alloc>  _Hashtable;
                                                               ^
/usr/include/c++/5/bits/unordered_set.h:102:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::key_type key_type;
                                             ^
/usr/include/c++/5/bits/unordered_set.h:103:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::value_type value_type;
                                               ^
/usr/include/c++/5/bits/unordered_set.h:104:43: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::hasher hasher;
                                           ^
/usr/include/c++/5/bits/unordered_set.h:105:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::key_equal key_equal;
                                              ^
/usr/include/c++/5/bits/unordered_set.h:106:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::allocator_type allocator_type;
                                                   ^
/usr/include/c++/5/bits/unordered_set.h:111:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::pointer  pointer;
                                             ^
/usr/include/c++/5/bits/unordered_set.h:112:50: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::const_pointer const_pointer;
                                                  ^
/usr/include/c++/5/bits/unordered_set.h:113:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::reference  reference;
                                               ^
/usr/include/c++/5/bits/unordered_set.h:114:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::const_reference const_reference;
                                                    ^
/usr/include/c++/5/bits/unordered_set.h:115:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::iterator  iterator;
                                              ^
/usr/include/c++/5/bits/unordered_set.h:116:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::const_iterator const_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_set.h:117:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::local_iterator local_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_set.h:118:57: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::const_local_iterator const_local_iterator;
                                                         ^
/usr/include/c++/5/bits/unordered_set.h:119:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::size_type  size_type;
                                               ^
/usr/include/c++/5/bits/unordered_set.h:120:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       typedef typename _Hashtable::difference_type difference_type;
                                                    ^
/usr/include/c++/5/bits/unordered_set.h:274:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       operator=(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_set.h:368:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
  emplace(_Args&&... __args)
  ^
/usr/include/c++/5/bits/unordered_set.h:412:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       insert(const value_type& __x)
       ^
/usr/include/c++/5/bits/unordered_set.h:416:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       insert(value_type&& __x)
       ^
/usr/include/c++/5/bits/unordered_set.h:471:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       insert(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_set.h:616:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       equal_range(const key_type& __x)
       ^
/usr/include/c++/5/bits/unordered_set.h:620:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<valhalla::Options_Action> >, std::__detail::__is_noexcept_hash<valhalla::Options_Action, std::hash<valhalla::Options_Action> > > >’
       equal_range(const key_type& __x) const
       ^
/home/son/valhalla/src/loki/worker.cc: In constructor ‘valhalla::loki::loki_worker_t::loki_worker_t(const ptree&, const std::shared_ptr<valhalla::baldr::GraphReader>&)’:
/home/son/valhalla/src/loki/worker.cc:162:26: error: no matching function for call to ‘std::unordered_set<valhalla::Options_Action>::insert(valhalla::Options::Action&)’
     actions.insert(action);
                          ^
In file included from /usr/include/c++/5/unordered_set:48:0,
                 from /home/son/valhalla/src/loki/worker.cc:8:
/usr/include/c++/5/bits/unordered_set.h:460:2: note: candidate: template<class _InputIterator> void std::unordered_set<_Value, _Hash, _Pred, _Alloc>::insert(_InputIterator, _InputIterator) [with _InputIterator = _InputIterator; _Value = valhalla::Options_Action; _Hash = std::hash<valhalla::Options_Action>; _Pred = std::equal_to<valhalla::Options_Action>; _Alloc = std::allocator<valhalla::Options_Action>]
  insert(_InputIterator __first, _InputIterator __last)
  ^
/usr/include/c++/5/bits/unordered_set.h:460:2: note:   template argument deduction/substitution failed:
/home/son/valhalla/src/loki/worker.cc:162:26: note:   candidate expects 2 arguments, 1 provided
     actions.insert(action);
                          ^
[ 47%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/ferry_connections.cc.o
/home/son/valhalla/src/loki/worker.cc: In member function ‘virtual prime_server::worker_t::result_t valhalla::loki::loki_worker_t::work(const std::__cxx11::list<zmq::message_t>&, void*, const std::function<void()>&)’:
/home/son/valhalla/src/loki/worker.cc:263:42: error: ‘class std::unordered_set<valhalla::Options_Action>’ has no member named ‘find’
     if (!options.has_action() || actions.find(options.action()) == actions.cend()) {
                                          ^
/home/son/valhalla/src/loki/worker.cc:263:76: error: ‘class std::unordered_set<valhalla::Options_Action>’ has no member named ‘cend’
     if (!options.has_action() || actions.find(options.action()) == actions.cend()) {
                                                                            ^
src/loki/CMakeFiles/valhalla-loki.dir/build.make:94: recipe for target 'src/loki/CMakeFiles/valhalla-loki.dir/worker.cc.o' failed
make[2]: *** [src/loki/CMakeFiles/valhalla-loki.dir/worker.cc.o] Error 1
CMakeFiles/Makefile2:1877: recipe for target 'src/loki/CMakeFiles/valhalla-loki.dir/all' failed
make[1]: *** [src/loki/CMakeFiles/valhalla-loki.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/graphbuilder.cc.o
[ 47%] Building CXX object src/meili/CMakeFiles/valhalla-meili.dir/transition_cost_model.cc.o
[ 47%] Building CXX object src/meili/CMakeFiles/valhalla-meili.dir/map_matcher.cc.o
[ 50%] Building CXX object src/meili/CMakeFiles/valhalla-meili.dir/map_matcher_factory.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/graphenhancer.cc.o
[ 52%] Built target valhalla-odin
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/graphfilter.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/graphvalidator.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/hierarchybuilder.cc.o
[ 52%] Building CXX object src/meili/CMakeFiles/valhalla-meili.dir/match_route.cc.o
[ 52%] Building CXX object src/meili/CMakeFiles/valhalla-meili.dir/config.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/linkclassification.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/luatagtransform.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/node_expander.cc.o
[ 52%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmdata.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmpbfparser.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmaccessrestriction.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmrestriction.cc.o
[ 55%] Built target valhalla-meili
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmway.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/pbfadminparser.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/pbfgraphparser.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/restrictionbuilder.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/servicedays.cc.o
[ 55%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/shortcutbuilder.cc.o
[ 58%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/timeparsing.cc.o
[ 58%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/transitbuilder.cc.o
[ 58%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/util.cc.o
[ 58%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/validatetransit.cc.o
[ 58%] Built target valhalla-mjolnir
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by EdoardoSerri** [comment]
Can it be the gcc compiler version? I have the 5.5.0

**Comment by PureW** [comment]
I believe so. We've moved our base-images away from Ubuntu 16 as the support is ending for that version.

**Comment by mabushey** [comment]
Do a `docker pull valhalla/docker` and copy the exec out, or use the container.

**Comment by PureW** [comment]
> Do a `docker pull valhalla/docker` and copy the exec out, or use the container.

Copying the binaries built in a newer glibc to an older version is not guaranteed to work. Proceed at your own risk.

**Comment by EdoardoSerri** [comment]
I had some problem using the docker but it was on windows, that is another story. For the compatibility with Ubuntu 16.04 the final problem was the gcc compiler version. To manage the cmake at lest the version 6 was needed. After I updated it, it worked fine. 
Thank you for the help.
