### ISSUE TITLE
trace_route crash when 2 locations are provided

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#2814]
Having an issue with a trace_route request where a start and end location are provided in addition to the shape. The crash occurs in loki/trace_route_action.cc inside the conditional where "If locations were provided, backfill the origin and dest lat,lon and update side of street on associated edges."

The issue appears to be with calls to get shape:
auto& shape = tile->edgeinfo(de->edgeinfo_offset()).shape();
After the ClosestPoint call the tuple returned has an invalid idx that causes a crash when trying to access the shape vector with the bad index.

Note that this works if the & is removed (which is how calls to shape seem to be elsewhere such as in thor/route_action.cc):
auto shape = tile->edgeinfo(de->edgeinfo_offset()).shape();

Here is a test URL for a trace in Utrecht area that crashes valhalla_service: 

http://localhost:8002/trace_route?json={"locations":[{"lat":52.073929,"lon":5.087180},{"lat":52.073860,"lon":5.087260}],"shape":[{"lat": 52.073929, "lon": 5.087180},{"lat": 52.074268, "lon": 5.086840},{"lat": 52.074730, "lon": 5.086450},{"lat": 52.074940, "lon": 5.087080},{"lat": 52.075081, "lon": 5.087490},{"lat": 52.075241, "lon": 5.087940},{"lat": 52.075500, "lon": 5.088680},{"lat": 52.075081, "lon": 5.089050},{"lat": 52.074291, "lon": 5.089790},{"lat": 52.074070, "lon": 5.089980},{"lat": 52.073841, "lon": 5.089540},{"lat": 52.073681, "lon": 5.089090},{"lat": 52.073509, "lon": 5.088630},{"lat": 52.073421, "lon": 5.088370},{"lat": 52.073238, "lon": 5.087870},{"lat": 52.073860, "lon": 5.087260}],"shape_match":"map_snap", "costing":"bicycle", "format": "osrm", "shape_format": "polyline5"}

**Comment by kevinkreiser** [comment]
this looks like something from clang-tidy. it often does stupid stuff like this and if you arent careful its hard to notice. would you mind pr'ing the removal of the reference? whats hapening here is we make a temporary edgeinfo, which caches the decoded shape and then we keep a reference to the cached except that as soon as the call is over the temporary is destructed and the reference points to garbage. as you pointed out we need to make a copy here or keep the edgeinfo object in scope while we use the shape
