### ISSUE TITLE
Documentation on command line applications

### ISSUE THREAD

**Issue by Sleepingwell** [valhalla/valhalla#2828]
Forgive me if I'm being daft, but I cannot seem to find documentation on many of the _valhalla\_\*_ command line applications. The applications I am referring to are:

![image](https://user-images.githubusercontent.com/294943/106526466-c8b86100-6539-11eb-8132-e6b3b0f037af.png)

If documentation exists, could someone please point me towards it. If (any of) these are used internally by the service and not intended for direct use, that would be good to know.

The application (I think) I'm most interested in is _valhalla\_run\_map\_match_, which I am having troubles with. I think the problem is that:

- At *./valhalla/src/meili/valhalla_run_map_match.cc:53*, `valhalla::meili::MapMatcherFactory::Create` is passed a `valhalla::Costing`, which is 'added to' (using `valhalla::Options::set_costing`) a default constructed `valhalla::Options`, which is then passed to another overload of `valhalla::meili::MapMatcherFactory::Create`. __Note that at this stage `valhalla::Options::add_costing_options` has never been called on that instance and hence `valhalla::Options::costing_options_size` returns zero (but `valhalla::Options::has_costing` returns `true`)__.

- That overload of `valhalla::meili::MapMatcherFactory::Create` then passes the `valhalla::Options` it receives to `valhalla::sif::CostFactory::Create`, which barfs (at _./valhalla/sif/costfactory.h:77_) because `valhalla::Options::costing_options_size` returns zero.

I note that `valhalla::meili::MapMatcherFactory::MapMatcherFactory` is constructed (at *./valhalla/src/meili/valhalla_run_map_match.cc:52*) with a `boost::property_tree::ptree`, which it saves as a `valhalla::meili::Config` in the instance member `valhalla::meili::MapMatcherFactory::config_`. I think that contains (default) costing options. __Should the `valhalla::Options` instance *options* (or at least a copy of that) be updated with those in `valhalla::meili::MapMatcherFactory::Create` somewhere around *./src/meili/map_matcher_factory.cc:44*? Or perhaps `valhalla::sif::CostFactory::Create` should be receiving a `valhalla::meili::Config`?__

This could be related to #2266 and/or #1945.

I am looking at commit fe2eb603c6de.

**Comment by nilsnolde** [comment]
yeah, some of them (quite a lot actually) are more useful for dev rather than production, i.e. end user. most (if not all) have a command line usage text printing what's it about and the parameters expected. And the `valhalla_run_xxx` are no good for end users I think. AFAIK they're also not tested for the most part so they don't necessarily survive all commits. Look at `valhalla_service`, it can run in server mode or _one shot_ mode: https://github.com/valhalla/valhalla#valhalla_service-aka-one-shot-mode, designed for your use case (I think).
