### ISSUE TITLE
Return more info from DynamicCost::Allowed(edge, pred,...) about the transition

### ISSUE THREAD

**Issue by mandeepsandhu** [valhalla/valhalla#2833]
When running the astar expansion (for bidirectional & unidirectional variants), we check if an edge is allowed to be used by calling into [`DynamicCost::Allowed`](https://github.com/valhalla/valhalla/blob/master/valhalla/sif/dynamiccost.h#L155).

However, we sometimes need to know the reason why an edge was disallowed (whether it was due to a restriction, or live traffic closure etc), so that we can set appropriate properties on the edge label which could be used later during expansion.

Apart from returning a `bool`, we could also set a "reason" which the caller can inspect to the find status of different edge conditions.

cc: @kevinkreiser

**Comment by dnesbitt61** [comment]
If an edge is not allowed by costing then an EdgeLabel will never get added. Basically this shortcuts further computation in the expansion (no transition costs, etc.). Seems like changing this would have large performance impacts.

**Comment by kevinkreiser** [comment]
In this case we actually want this extra information when the edge IS allowed. So right now we get back the index of the restriction if the edge was part of one but the idea here is that instead of just passing in the index by reference to be filled out we send a struct along that lets us hear about both restrictions and closures (and other stuff?) for example:

```c++
struct TransitionInfo{
  uint8_t restriction_index_;
  bool has_closure_;
};

....

// Check if access is allowed on the specified edge.
bool AutoCost::Allowed(const baldr::DirectedEdge* edge,
                       const EdgeLabel& pred,
                       const graph_tile_ptr& tile,
                       const baldr::GraphId& edgeid,
                       const uint64_t current_time,
                       const uint32_t tz_index,
                       TransitionInfo& info) const {
  // Check access, U-turn, and simple turn restriction.
  // Allow U-turns at dead-end nodes in case the origin is inside
  // a not thru region and a heading selected an edge entering the
  // region.
  if (!IsAccessible(edge) || (!pred.deadend() && pred.opp_local_idx() == edge->localedgeidx()) ||
      ((pred.restrictions() & (1 << edge->localedgeidx())) && !ignore_restrictions_) ||
      edge->surface() == Surface::kImpassable || IsUserAvoidEdge(edgeid) ||
      (!allow_destination_only_ && !pred.destonly() && edge->destonly()) ||
      ((info.has_closure_ = IsClosed(edge, tile)) && pred.closure_pruning())) {
    return false;
  }

  return DynamicCost::EvaluateRestrictions(access_mask_, edge, tile, edgeid, current_time, tz_index,
                                           info.restriction_index_);
}
```

In this way we can see whether or not the edge was closed and also if there was a restriction when the closure didnt disallow the path.
