### ISSUE TITLE
Dynamically creating edges in graph

### ISSUE THREAD

**Issue by roadrouting** [valhalla/valhalla#2843]
Hello,

Our use case involves making lots of small changes to the street graph, and then running routing queries to understand the impact. These changes can range from removing roads, adding intersections, or entirely new ways.

We would like to be able to apply these as changes to a running Valhalla server in the same way it is possible to specify dynamic costs. With the goal of avoiding any computationally expensive rebuilding steps for something that is ultimately a short-lived patch.

Thanks!

**Comment by kevinkreiser** [comment]
At the moment the only thing we offer in this regard is removing edges on the fly. This is done via avoid locations which are then mapped to existing edges and then hard avoided in the patching algorithms via costing.

If you have a fixed set of edges that you know a priori then you can add them all to the graph and 'remove' them at query time using this feature.

If you don't know where the edges will be or where the will connect ahead of time than im afraid we cannot support that. It's a cool idea but I'm afraid the amount of work to do to achieve it will be quiet extensive. At the very least you will need to connect new edges to the graph and rebuild the tiles where those appear and either reload the tiles or reload the service that's using them. This could be don't but it won't be terribly fast (I wouldn't expect to do this per query).

Can you elaborate on your needs a bit more?

**Comment by roadrouting** [comment]
Thanks for the fast response!

That's a shame, but makes a lot of sense. Our needs are centred around a citizen-science style interactive application which allows local stakeholders to quickly explore the impact of arbitrary changes such as road closures, bypass creations, bus priority measures.

The desire to use Valhalla over alternatives which may be better suited, like pgRouting, is both the feature completeness from the perspective of a high-level end-user who wants to run fairly standard (yet complex) queries, and the on-balance performance for more involved spatial accessibility questions to be solved on the fly. 

Given the small geographical scale both the changes and analysis would be constrained to, building new specific tiles may be fairly feasible. However, since there may be many proposed scenarios suggested at once, updating the service for all requests wouldn't be ideal. Would something like conditionally enabling tile-variants on a per-request be realistic idea at all?

**Comment by TimMcCauley** [comment]
This would indeed be a very strong feature. Federal road agencies in Germany and probably also other countries do this stuff mostly "by hand" which is terribly time consuming... I know of only one service that is able to do something similar, however it's not open source and I guess it isn't free either. I thought I would leave it here nonetheless.. https://developer.here.com/documentation/custom-routing-extension/dev_guide/topics/what-is.html

**Comment by danpat** [comment]
If you're only interested in relatively local effects, it only takes a few seconds to regenerate tiles for a small area....
