### ISSUE TITLE
Fetching transit with valhalla_build_transit tool.

### ISSUE THREAD

**Issue by mesozoic-drones** [valhalla/valhalla#2860]
Hello!

Could you please help me with some advise or little data extraction? Here is my problem.

I am trying to fetch TransitLand feeds via the `valhalla_build_transit` tool. I have a Free Tier subscription plan for Transitland and I get 429 HTTP errors (Too Many Requests) while running `valhalla_build_transit`. I tried to:
1) Set exponential backoff delays in code in single thread.
2) Specify single feed id. If I set import level to 4, I get  
`[INFO] Finished with 0 transit tiles in 13 feeds`
message and 0 pbf files in target directory. Here is my configuration (I specify feed id as argument for `valhalla_build_transit`):
```
{
	"mjolnir":
	{
	"transit_dir": "transit"
	},
	"api_key": "xxxx",
	"import_level": 4
}
```

If I remove `import_level` parameter the process runs extremely long and ens up with constant 429 HTTP errors so I finish it.

So these approaches didn't help. Maybe you could help me with some advice? Or could you please provide access to resulting pbf files of `valhalla_build_transit`? For example for small region so I could test transit routing of my Valhalla instance. 

I've already read these issues but it didn't help:
https://github.com/transitland/feed-registry/issues/398#issuecomment-381628857
https://github.com/valhalla/valhalla/issues/878

Thank you in advance!

**Comment by pranavpandey1998official** [comment]
here is the tile  fetched after 1 day, https://drive.google.com/drive/folders/1sRlHLRdlW3sV7jldgfTSZpO4i86mn9Zh?usp=sharing

note- 
these are not the resulting tiles you get from `valhalla_build_transit` but tiles you get after you run `valhalla_fetch_transit` so you have to run `valhalla_convert_transit` yourself

these are run with `conf/valhalla.json http://transit.land/ 1000 ./transit_tiles "
                 "-122.469,37.502,-121.78,38.018 transitland-YOUR_KEY_SUFFIX 4 f-9q9-bart`

**Comment by mesozoic-drones** [comment]
Thank you so much for your help!
