### ISSUE TITLE
opp_index in directed edge is confusing

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#2865]
ok , so by the name of it it should be the absolute index of the opposite edge of in the directedEdge array of the tile,

so `tile->directededge(edge->opp_index())` should give me the opposite edge
but the more code I read I come to realize that it is the relative index to the first outbound edge of the end node of the edge,

Am I correct, If yes let me update the doc here
https://github.com/valhalla/valhalla/blob/c634f27f44deebb1aa12223b08bf725dd8c33117/valhalla/baldr/directededge.h#L396

**Comment by kevinkreiser** [comment]
no the are relative to the start edge index on the node. the clue is that the value is only 7 bits wide

**Comment by pranavpandey1998official** [comment]
the `node` is the endnode of the directed edge of which we want to find opposite edge right?

**Comment by kevinkreiser** [comment]
@pranavpandey1998official exactly!

**Comment by pranavpandey1998official** [comment]
I am closing this, in hope that someone would find it if he found similar confusion,
