### ISSUE TITLE
running on kubernetes

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#2881]
has anyone from the community was successful in running Valhalla in Kubernetes,

I am not looking for just replicating the docker image and setting a load balancer in front ,

by looking at the code I can see that we would be needing 4 services inside the cluster , prime_server , loki, thor and odin,

Can someone think of any challenges I will face If I go with this approach

I can see that valhalla/docker repo is doing something similar,

**Comment by kevinkreiser** [comment]
@pranavpandey1998official i have some experience doing it. we've recently made a docker image available which should have all the binaries you need in the container. those latest images can be found on docker hub at: `valhalla/valhalla:run-latest`

the valhalla/docker repo is deprecated and we'll marked it as archived shortly.

as far as running the code goes you're right, the most robust way to do that is to run all the different worker types with prime_server all in different processes at least. the diagram of that looks somethign like this:


```
                                     ==========                   ==========                   ==========
                                     |  loki  |                   |  thor  |                   |  odin  |
                                     |  loki  |                   |  thor  |                   |  odin  |
client <---> server ---> proxy <---> |  ....  | <---> proxy <---> |  ....  | <---> proxy <---> |  ....  |
               ^                     |  loki  |                   |  thor  |                   |  odin  |
               |                     |  loki  |                   |  thor  |                   |  odin  |
               |                     ==========                   ==========                   ==========
               |                         |                            |                            |
                \ _____________________ /___________________________ /___________________________ /
```

In the above the server and the proxies and each worker is its own process. in this way if there is a crash it only affects the individual request that caused it. other requests are unaffected. an important point about the default setup here is that we use supervisord to monitor/run/restart these processes.

with respect to kubernetes its not clear if you'd want to actually want to run these in different containers in the pod. that might be more complication than its worth

**Comment by pranavpandey1998official** [comment]
cool thanx
