### ISSUE TITLE
Compilation error on Ubuntu 18.04

### ISSUE THREAD

**Issue by ismailsunni** [valhalla/valhalla#2883]
I use Ubuntu 18.04 and follow this script to install Valhalla https://github.com/valhalla/valhalla/blob/master/scripts/Ubuntu_Bionic_Install.sh

Unfortunately, I got this compilation error:
```
[ 97%] Built target valhalla_test
Scanning dependencies of target benchmark-mapmatch
In file included from /home/isunni/dev/cpp/valhalla/third_party/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/isunni/dev/cpp/valhalla/third_party/pybind11/include/pybind11/cast.h:13,
                 from /home/isunni/dev/cpp/valhalla/third_party/pybind11/include/pybind11/attr.h:13,
                 from /home/isunni/dev/cpp/valhalla/third_party/pybind11/include/pybind11/pybind11.h:44,
                 from /home/isunni/dev/cpp/valhalla/src/bindings/python/python.cc:1:
/home/isunni/dev/cpp/valhalla/third_party/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
Scanning dependencies of target benchmark-routes
src/bindings/python/CMakeFiles/python_valhalla.dir/build.make:62: recipe for target 'src/bindings/python/CMakeFiles/python_valhalla.dir/python.cc.o' failed
make[2]: *** [src/bindings/python/CMakeFiles/python_valhalla.dir/python.cc.o] Error 1
CMakeFiles/Makefile2:1817: recipe for target 'src/bindings/python/CMakeFiles/python_valhalla.dir/all' failed
make[1]: *** [src/bindings/python/CMakeFiles/python_valhalla.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Any hints to fix this issue?

Thanks :)

**Comment by nilsnolde** [comment]
Doesn’t find your Python installation. You can force it though, look into the azure config, theres the cmake config for setting py stuff. 

But if I’m half right in my assumption of what you need valhalla for, you probably don’t need the bindings anyways, so you can use ENABLE_PYTHON=OFF in the cmake settings..

**Comment by danpat** [comment]
@nilsnolde The problem here is that the CMake step should have already detected the missing python bindings and disabled this target.  `benchmark-mapmatch` is not marked as requiring those bindings.

**Comment by nilsnolde** [comment]
Oh true, weird target to fail on. I tried in a fresh ubuntu container and I can't replicate on master (did you try master @ismailsunni ?).. Building `benchmark-mapmatch` does not build the bindings with the default cmake config, I also can't find any relation between the two in the cmakelists. And of course building all targets will fail in the cmake config step if python is not installed. Looks more like a broken (dev-)python installation to me and maybe some kind of `make` glitch that it relates a broken python to `benchmark-mapmatch` in the log?

To get it built, you can try to:
- repair python (or make sure it's a dev version which has the headers)
- `-DENABLE_PYTHON_BINDINGS=OFF`
- Or if you have a python version in a non-standard place, smth like:
```
-DPYTHON_EXECUTABLE=/usr/x86_64-w64-mingw32/bin/python3
-DPYTHON_LIBRARIES=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpython3.9.dll.a
-DPYTHON_INCLUDE_DIRS=/usr/x86_64-w64-mingw32/sys-root/mingw/include/python3.9
```

**Comment by nilsnolde** [comment]
> that the CMake step should have already detected the missing python bindings
In any case, it's still odd that it came through the cmake config without finding `Python.h`.. We're not checking for any Python installation ourselves, but pybind11 is.. Apparently not for headers though.. Since CMake 3.12 it ships with [FindPython](https://cmake.org/cmake/help/v3.12/module/FindPython.html) apparently, pybind11 is maintaining its own module for that. Maybe generally worth adding `FindPython` in the bindings CMakeLists? Is there a reason (other than more general compatibility) for CMake 3.8 as minimum @kevinkreiser ?

**Comment by ismailsunni** [comment]
hi @nilsnolde, yes, I tried on the master branch. In the end, I disable the binding as you suggested. I got it built now. Thanks!

**Comment by kevinkreiser** [comment]
@nilsnolde there is no reason that i can think of. i suppose its possible there are some older build systems out there that come with older cmake but its pretty easy to get the latest cmake manually on most platforms. if it helps us to move to a newer version im not opposed to it unless someone else has a good reason not to?

**Comment by nilsnolde** [comment]
@ismailsunni 's problem was the first time it was reported so far, and it seems it can only occur when there's a python version not in dev mode, i.e. missing the headers. pybind11 is just not checking for it. With this change, it would be more verbose and skipping the bindings with a warning message:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 69268599c..6fbb082e3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -7,7 +7,7 @@
 # This is secondary build configuration provided for convenient development
 # on Windows and using CMake-enabled IDEs.
 #
-cmake_minimum_required(VERSION 3.8 FATAL_ERROR)
+cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
 project(valhalla LANGUAGES CXX C)
 
 include(FindPkgConfig)
@@ -239,11 +239,15 @@ add_subdirectory(src)
 
 ## Python bindings
 if(ENABLE_PYTHON_BINDINGS)
-  #TODO: need to make sure they actually have python
-  add_subdirectory(src/bindings/python)
-  install(FILES COPYING CHANGELOG.md
-    DESTINATION "${CMAKE_INSTALL_DATAROOTDIR}/doc/python-valhalla"
-    COMPONENT python)
+  find_package(Python3)
+  if (Python3_DEVELOPMENT_Found)
+    add_subdirectory(src/bindings/python)
+    install(FILES COPYING CHANGELOG.md
+      DESTINATION "${CMAKE_INSTALL_DATAROOTDIR}/doc/python-valhalla"
+      COMPONENT python)
+  else()
+    message(WARNING "Skipping Python bindings... Install a development Python version including headers to compile the bindings.")
+  endif()
 endif()
```

I have no strong preference either way. I'll PR if you think it's worth it for a cmake version bump @kevinkreiser
