### ISSUE TITLE
Interrupt bidirectional search as soon as we found all alternates

### ISSUE THREAD

**Issue by genadz** [valhalla/valhalla#2884]
According to the comment https://github.com/valhalla/valhalla/pull/2868#issuecomment-781402924 we could save several percent of iterations if we stopped bidirectional search as soon as all alternates were found. In order to do that, we should refactor the code as proposed here https://github.com/valhalla/valhalla/pull/2868#issuecomment-783018463.
So, this refactoring, for example, could allow us to increase [`cost_extend_rel`](https://github.com/valhalla/valhalla/blob/master/src/thor/bidirectional_astar.cc#L28) coefficient in order to find more alternates.
@kevinkreiser

**Comment by genadz** [comment]
actually, @kevinkreiser @dnesbitt61 do you know why we use `sortcost` instead of `route cost` when set cost threshold in bidirectional astar https://github.com/valhalla/valhalla/blob/master/src/thor/bidirectional_astar.cc#L792 ? is it only about performance ?

I tested it locally (replaced `sortcost` with `route cost`) and got ~20% performance decrease. It's a lot, but, to be honest, I expected much more decrease. The same time, current heuristic can miss optimal routes that lie far from the straight line `Source - Target`.

**Comment by dnesbitt61** [comment]
I haven't followed logic for alternates. However, expansion is based on lowest sort cost, not real cost so I would think that it is proper to use sort cost. As long as the A* heuristic underestimates the true cost from any source to the target then this should be valid.

**Comment by kevinkreiser** [comment]
> current heuristic can miss optimal routes

what do you mean when you say optimal here? i guess you mean the final real cost of a route. as dave said so long as we pick an admissible (underestimates the cost to the goal) heuristic what you are saying shouldnt happen. however there are two details there that can cause this heuristic to OVERestimate the cost to the goal.

1. we use a max speed and b-line distance to estimate the cheapest cost you possible reach the goal at. that max speed is possible to be less than the speeds reported by historical or real time traffic. i forget if we cap the speeds coming out of that in the end so that we dont overestimate the a* heuristic
2. if we have cost factors that have the affect of making parts of the graph cheaper in cost units that the a* heuristic is unaware of then that heuristic may still be overestimating the cost
3. something i didnt think of yet?

If anything with costing or heuristic estimation is happing to make the heuristic overestimate the cost to the goal wrt to the actual cost then what you are seeing could happen.

**Comment by genadz** [comment]
> I haven't followed logic for alternates. However, expansion is based on lowest sort cost, not real cost so I would think that it is proper to use sort cost. As long as the A* heuristic underestimates the true cost from any source to the target then this should be valid.

@kevinkreiser @dnesbitt61 current `sortcost` works perfectly in case of unidirectional search. But for bidirectional such `sortcost` doesn't guarantee that first connection will be the optimal route. In order to guarantee finding the optimal route in bidirectional A* we should:
1) modify `sortcost` to use another potential function;
or
2) use current `sortcost` but stop only after we reach edge with `sortcost > optimal_route_cost`.

There is a simple example: we go from `S` to `T`.
Let's suppose that `time(SA) = time(AT) = 1h1m` and `time(SBC) = time(CDT) = 1h`.
Let's look at sortcosts: `Sortcost(SA) = time(SA) + dist(AT) / maxspeed`, `Sortcost(SBC) = time(SBC) + dist(CT) / maxspeed` -> `Sortcost(SA) - Sortcost(SBC) = 1m - (dist(AT) - dist(CT)) / maxpseed`. It's obvious that `dist(CT) > dist(AT)`, that leads to `Sortcost(SA) = Sortcost(AT) > Sortcost(SBC) = Sortcost(CDT)`. It means, that we will find `SAT` as the first route, but actual optimal route `SBCDT` can be missed.  
```
S----------------------A----------------------T
|                                             |
|                                             |
|                                             |
B----------------------C----------------------D
```

**Comment by kevinkreiser** [comment]
@genadz execllent point! this is the primary reason we extended the search in the first place. my preference is number 2 as it models what that extension that we did in the original implementation was trying to do (but without paying too much performance for it haha). i wonder, in practice, how often master doesnt satisfy number 2 above

**Comment by genadz** [comment]
> @genadz execllent point! this is the primary reason we extended the search in the first place. my preference is number 2 as it models what that extension that we did in the original implementation was trying to do (but without paying too much performance for it haha). i wonder, in practice, how often master doesnt satisfy number 2 above

you mean, how often we miss optimal route because of such heuristic ?

**Comment by kevinkreiser** [comment]
@genadz i was really wondering what it will do to performance. like how often does it happen that we havent already satisfied number 2 will tell us that when we change it how much of a performance drop we will get. if you implemented number 2 already and have measured that performance drop that will be nice to see

**Comment by danpat** [comment]
@kevinkreiser @dnesbitt61 How does the current bidir A* implementation compare to [New Bidirectional A*](https://repub.eur.nl/pub/16100/ei2009-10.pdf), which asserts to solve the need for the balanced heuristic condition?

**Comment by genadz** [comment]
> @genadz i was really wondering what it will do to performance. like how often does it happen that we havent already satisfied number 2 will tell us that when we change it how much of a performance drop we will get. if you implemented number 2 already and have measured that performance drop that will be nice to see

**master**
```
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.011s	0.066s	0.085s	0.115s	0.177s	0.318s	0.484s	1.151s	2.609s
mean = 0.121
```

**branch** (approach 2)
```
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.011s	0.066s	0.083s	0.119s	0.184s	0.377s	0.685s	1.578s	3.173s
mean = 0.149
```

**Comment by kevinkreiser** [comment]
seems worth it to ensure getting a cost optimized path to me :ship:

**Comment by genadz** [comment]
> seems worth it to ensure getting a cost optimized path to me

I can also calculate number of optimal routes that were missed by **master** comparing to the **branch**. Will attach results later

**Comment by genadz** [comment]
I think we shouldn't implement this issue. Working on alternatives for several months I came to the conclusion that we should take into account **different factors** (like number of shared roads or roads importance) when ranking alternatives (not only **cost**). So, admissible alternatives with better costs can be ranked lower than some other routes that, for example, have few number of shared roads.
