### ISSUE TITLE
It's in seconds, so divide by 60 to convert to minutes.

### ISSUE THREAD

**Issue by KamilDwo** [valhalla/valhalla#2895]
> It's in seconds, so divide by 60 to convert to minutes.
 
@nilsnolde 

ok but i got response:

![image](https://user-images.githubusercontent.com/17766738/109283370-00f04e00-781f-11eb-8bd3-e7b7ea7d682e.png)

Why i got 1km and 21 minutes in auto costing ?

_Originally posted by @nilsnolde in https://github.com/valhalla/valhalla/issues/2894#issuecomment-786509689_

**Comment by nilsnolde** [comment]
You can also answer on closed issues, or even better, ask questions in the discussions forum (new feature, next to Pull Requests in the menu).

True, 20 mins is a little long ;) Can you post your exact request? Is it simply an OSM extract or some other data? And please paste text, not a picture!

**Comment by KamilDwo** [comment]
OK thanks for advice, i will remember that :)

Its just variable from summary.time divided by 60.

My request: `{"locations":[{"lat":49.905615,"lon":20.839326},{"lat":49.9068,"lon":20.849}],"costing":"auto","costing_options":{"auto":{"use_tracks":true}}}: `

And response: `{"trip":{"locations":[{"type":"break","lat":49.905615,"lon":20.839326,"original_index":0},{"type":"break","lat":49.9068,"lon":20.849,"city":"left","original_index":1}],"legs":[{"maneuvers":[{"type":1,"instruction":"Drive east.","verbal_pre_transition_instruction":"Drive east.","verbal_post_transition_instruction":"Continue for 700 meters.","time":1278.0,"length":0.71,"cost":996.84,"begin_shape_index":0,"end_shape_index":20,"rough":true,"travel_mode":"drive","travel_type":"car"},{"type":15,"instruction":"Turn left.","verbal_transition_alert_instruction":"Turn left.","verbal_pre_transition_instruction":"Turn left.","verbal_post_transition_instruction":"Continue for 200 meters.","time":25.076,"length":0.224,"cost":20.698,"begin_shape_index":20,"end_shape_index":28,"travel_mode":"drive","travel_type":"car"},{"type":6,"instruction":"Your destination is on the left.","verbal_transition_alert_instruction":"Your destination will be on the left.","verbal_pre_transition_instruction":"Your destination is on the left.","time":0.0,"length":0.0,"cost":0.0,"begin_shape_index":28,"end_shape_index":28,"travel_mode":"drive","travel_type":"car"}],"summary":{"has_time_restrictions":false,"min_lat":49.904847,"min_lon":20.839284,"max_lat":49.906803,"max_lon":20.849256,"time":1303.076,"length":0.934,"cost":1017.538},"shape":"y|~d~Aiv|vf@hCk_@?k[k@qRwEy`@kDm^BqH|AaLlE{VxLaf@tDsZtDco@xBce@rE}s@xBqa@Swb@\\}b@Vun@pBmTjB_Tb@aFkCnA_^w@}GmB_RqNeJqBmKr@qZpGwFX"}],"summary":{"has_time_restrictions":false,"min_lat":49.904847,"min_lon":20.839284,"max_lat":49.906803,"max_lon":20.849256,"time":1303.076,"length":0.934,"cost":1017.538},"status_message":"Found route between points","status":0,"units":"kilometers","language":"en-US"}}`

**Comment by nilsnolde** [comment]
yeah, on the mapbox instance I get the same results (without `use_tracks`, which is btw not a boolean, but a float in [0, 1]). it's indeed a track you're routing on: https://www.openstreetmap.org/way/350366487. slightly surprised valhalla routes on tracks for cars by default, though I can see it's been added very recently: https://github.com/valhalla/valhalla/pull/2769. I guess the default speed is just that slow for tracks with cars, some few KPH. Makes sense to me though..

One way of changing the behavior would be to re-tag the highway tag on that way (if you're sure it's mislabeled!), then valhalla would give you higher speeds. Pretty sure it also modulates the speed for tracks with better `surface` tags (which your way lacks) and assumes a bad surface by default.

**Comment by nilsnolde** [comment]
I'll close, since this is very likely expected behavior, but feel free to keep on commenting.
