### ISSUE TITLE
Json for map matching

### ISSUE THREAD

**Issue by narulakartik** [valhalla/valhalla#2900]
I am looking to map match the following set of coordinates. What would the request to the server look like?

{"lat":37.979516,"lon":23.733512,"time":1537460933},{"lat":37.979512,"lon":23.733515,"time":1537460943},{"lat":37.97952,"lon":23.733508,"time":1537460953},{"lat":37.979525,"lon":23.733505,"time":1537460963},{"lat":37.979529,"lon":23.733502,"time":1537460973},{"lat":37.979533,"lon":23.733498,"time":1537460983},{"lat":37.979538,"lon":23.733495,"time":1537460993},{"lat":37.979542,"lon":23.733492,"time":1537461003},{"lat":37.979546,"lon":23.733488,"time":1537461013},{"lat":37.97955,"lon":23.733485,"time":1537461023},{"lat":37.979554,"lon":23.733481,"time":1537461033},{"lat":37.979557,"lon":23.733478,"time":1537461043},{"lat":37.979561,"lon":23.733475,"time":1537461053},{"lat":37.979564,"lon":23.733472,"time":1537461063},{"lat":37.979568,"lon":23.733469,"time":1537461073},{"lat":37.979571,"lon":23.733466,"time":1537461083}

Thanks

**Comment by kevinkreiser** [comment]
You're already darn close! Have a look at the docs, they have some examples: https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md#example-trace_route-requests

Minimallly, you can take what you have a wrap it like this:

```json
{
  "shape": [YOURE_COORDS_FROM_ABOVE],
  "costing":"auto"
}
```
