### ISSUE TITLE
 prime_server issues after installing

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2917]
When I build valhalla (master) the executables are all fine when run from the build folder.

However, when I install valhalla to /usr/local I can't run `valhalla_service ...` (I know that's new in prime_server, but so is my build):
```
valhalla_service: Symbol `_ZTVN12prime_server13http_entity_tE' has different size in shared object, consider re-linking
valhalla_service: Symbol `_ZTVN12prime_server14http_request_tE' has different size in shared object, consider re-linking
valhalla_service: symbol lookup error: valhalla_service: undefined symbol: _ZN12prime_server7quiesceEjj
```

I purged the relevant /usr/local, built all from scratch again, incl prime_server master, same result. Also I couldn't build prime_server with autotools anymore (undefined macro `m4_esyscmd`), I used CMake & make. Is it somehow related to https://github.com/kevinkreiser/prime_server/pull/93? The version is definitely not right:
```
/usr/local/lib
├── libprime_server.so -> libprime_server.so.0
├── libprime_server.so.0 -> libprime_server.so.0.6.7
├── libprime_server.so.0.6.7
├── libvalhalla.a
├── libvalhalla.so -> libvalhalla.so.3
```

**Comment by kevinkreiser** [comment]
on ubuntu all the packages for prime_server are built with auto tools. at least on 18.04 and 20.04 this seems to work fine. one work around for you is to add the valhalla or prime_server ppas and just install the packages from ppa.

i personally link to self built prime_server in /usr/local as it sounds you are doing. what platform are you on?

**Comment by nilsnolde** [comment]
Argh, I might've a stray prime_server in `/usr/lib` from god knows when.. sorry for the confusion, I'll report back if it worked..

reg autotools: I guess it's a version issue, though I'm on arch with autotools v2.71. Not that tragic for me, just smth I thought I'd mention.

**Comment by nilsnolde** [comment]
yeah, arch had no /usr/local/lib in its linker paths.. :facepalm:
