### ISSUE TITLE
Ferry edges sometimes not connected to high-level road network

### ISSUE THREAD

**Issue by SvetlanaBayarovich** [valhalla/valhalla#2919]
As I was looking at the ferries that router avoids and one it eventually uses, I noticed that ferry routes are high-level edges but sometimes they are not connected to the rest of high-level network. If I understand correctly the purpose of `ReclassifyFerryConnections` it should connect ferry edge to that network , but somehow it does not happen. As a result, by the moment such ferry is reached, the limit for hierarchy transitions (down) is exhausted, which results in either attempts to find a route using "connected" ferries or no route at all. 

@dnesbitt61 Could you comment on intended behavior for ferry connections?

Below are some examples that illustrate ferry connections. 

Legend: **red** denotes L0 edges, **blue** - L1, **orange** - L2

The ferries that are (eventually) used. They are all connected to L0 roads (and later L1 as well)

| West Sicily | Alicante Spain |Palma de Mallorca |
|--|--|--|
|![image](https://user-images.githubusercontent.com/50918075/110137294-bd2eb300-7de1-11eb-9299-58a3a5358154.png)|![image](https://user-images.githubusercontent.com/50918075/110137848-5d84d780-7de2-11eb-9375-2965c685ea04.png)|![image](https://user-images.githubusercontent.com/50918075/110138261-d5530200-7de2-11eb-83c9-da885a002868.png)|

The ferries that are avoided
| Messina, Sicily | Melilla, North of Africa | Denia, Spain |
|-|-|-|
|![image](https://user-images.githubusercontent.com/50918075/110149950-b444de00-7def-11eb-9aea-90107cfa1f23.png)| ![image](https://user-images.githubusercontent.com/50918075/110150553-7300fe00-7df0-11eb-882a-59af35759234.png)|![image](https://user-images.githubusercontent.com/50918075/110150893-d68b2b80-7df0-11eb-8dc8-c957940a4dc1.png)|
||![image](https://user-images.githubusercontent.com/50918075/110150375-4220c900-7df0-11eb-9396-3757a4a8cc11.png)||

**Comment by dnesbitt61** [comment]
In many locations, ferries connect to highway=service ways (which are the lowest road_class). The intent of ReclassifyFerryConnections is to create the shortest path from the terminal node of a ferry to a high class road. It has been quite a while since this code was written and last tested so I cannot verify its current behavior.

**Comment by SvetlanaBayarovich** [comment]
Yeah I wanted to verify that if I see "disconnection" cases it means it's not now it was **meant** to be. So going to dig in

**Comment by SvetlanaBayarovich** [comment]
It turned out there were several reasons for absence of ferry connection. The major one was covered here: https://github.com/valhalla/valhalla/pull/2933. Other cases were related to incorrect tags placed on some of the roads. Currently all the cases described in this issue are resolved. Closing for now.
