### ISSUE TITLE
Broken Python Installation

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#2929]
unfortunately it seems that #2752 broke the python installation. in docker when i test this and do `make install` i get the following:

```
root@e611d5dd51ad:/valhalla/build# find /usr/local/lib/python*
/usr/local/lib/python.
/usr/local/lib/python./dist-packages
/usr/local/lib/python./dist-packages/valhalla
/usr/local/lib/python./dist-packages/valhalla/__init__.py
/usr/local/lib/python./dist-packages/valhalla/python_valhalla.cpython-38-x86_64-linux-gnu.so
/usr/local/lib/python2.7
/usr/local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python3.8
/usr/local/lib/python3.8/dist-packages
```

wtf is `python.` seems like somewhere something is trying to figure out the python major and minor version but doesnt have it? so it becomes `python${major}.{$minor}` where both variables are empty.. this is breaking the docker build at the moment so im going to work around it and we'll need to debug and fix whatever happened here

cc @nilsnolde

**Comment by nilsnolde** [comment]
huh... wtf github.. when I look at the last commit before merging it only failed codecov (obviously), but circle seemed fine. now looking at circle dashboard I can see for that commit it failed actually to build the docker images.. horrible easter egg! so sorry @kevinkreiser , I had no idea this happened! 

I'll dig in!

**Comment by nilsnolde** [comment]
Ah of course, the merge commit only triggered it.. Latest tmrw morning I'll fix it.

**Comment by kevinkreiser** [comment]
no rush really, sorry for the gotcha there, we were just trying to conserve CI by not building everything all the time. docker is kind of like a release thing where `latest==master` and `tagged version==git tag`
