### ISSUE TITLE
Pedestrian crossing should be a separate TripLeg_Use

### ISSUE THREAD

**Issue by abhi2039** [valhalla/valhalla#2942]
Currently, pedestrian crossings are treated as regular walkways in Valhalla. Making them separate so that an edge can be identified if it is a pedestrian crossing can have a few benefits:
1. More detailed navigation instructions for pedestrians. 
2. Potentially we could use this information to adjust cost of pedestrian crossings if needed.

I am happy to implement it if folks think it is a good idea.

**Comment by dnesbitt61** [comment]
I take it that there are already edges created for pedestrian crossings and this would just make them a new Use?

**Comment by abhi2039** [comment]
> I take it that there are already edges created for pedestrian crossings and this would just make them a new Use?

That's correct.

**Comment by dnesbitt61** [comment]
This sounds like a good idea to me. From a costing standpoint I could see some slight penalty to prevent too many crossings so a route would tend to stay on one side of a street. 

From a guidance/navigation standpoint it would be nice if there was a way to determine the name of the street that is crossed. I'm not sure this would be feasible for a crossing that does from a sidewalk to another sidewalk (where sidewalks are separate ways).

**Comment by abhi2039** [comment]
@dnesbitt61 Please review my PR if you get a chance: https://github.com/valhalla/valhalla/pull/2950

**Comment by nilsnolde** [comment]
was fixed in #2950
