### ISSUE TITLE
Times between sets of coordinates is lower than others routing applications

### ISSUE THREAD

**Issue by arielmoraes** [valhalla/valhalla#2954]
When using the Route or Matrix endpoints I could notice a difference in the time response when compared to some other routing engines such as Google Maps and the OSRM. The distance results are very close between each service, but Valhalla is giving a lower time, on a 40 minute route the result is almost 10 minutes lower.

Could that be related to the Administrative Area? Asking that because I didn't extract from the planet.pbf. If not, are there any parameters that should be changed?

**Comment by danpat** [comment]
@arielmoraes You should look at the generated path to get a deeper understanding.  At least compared to OSRM:

  1. Valhalla allows access to a slightly different set of roads (things like driveways, tracks, alleys, etc)
  2. Cost models generate different penalties leading to different path selections
  3. Valhalla generates different speeds from the OSM tags compared to OSRM

For a 40 minute route, there are going to be lots of places for these kinds of disagreements to accumulate.  You would need to look closely at the full route geometry from each to see which is better for your use-case.

It's not really feasible for all routing engines to give exactly the same result - if they did that, then we'd only have one routing engine.  Except for artifically constructed example maps, there is rarely a true "correct" path on routes of any length.

**Comment by arielmoraes** [comment]
Is there a tool to visualize the generated path or to debug the steps? 

That 40 minute path is composed of two coordinates on the same highway (no tools, no roundabouts), almost a straight line.

**Comment by arielmoraes** [comment]
I've created an example using a shorter path, as the distance increases the difference in time increases too, for that example the difference was 1 minute.

**Google Maps**
![image](https://user-images.githubusercontent.com/6741634/111846730-2e905a80-88e6-11eb-9830-82a3041d1a3b.png)

**OSM**
![image](https://user-images.githubusercontent.com/6741634/111846752-3819c280-88e6-11eb-943d-402bf3dac5ed.png)

**Valhalla Shape**
![image](https://user-images.githubusercontent.com/6741634/111846803-4ff14680-88e6-11eb-9c22-d0f14ccbbbdc.png)

```json
"summary": {
    "has_time_restrictions": false,
    "min_lat": -23.365837,
    "min_lon": -47.525779,
    "max_lat": -23.346133,
    "max_lon": -47.471613,
    "time": 179.326,
    "length": 5.974,
    "cost": 167.629
}
```

**Comment by danpat** [comment]
Well, as it's unclear how Google is rounding their numbers, their "4 minutes" might be 3.51 minutes - meaning only a 30 second disagreement.

Google's endpoint also includes traffic data - the free Valhalla service you're using does not.

Unless you actually go out and drive the routes, you're going to be hard-pressed to prove which one is wrong.  Google is definitely not always correct and should've a "source of truth" here.  But they do have traffic data, which does make a difference.

**Comment by arielmoraes** [comment]
I see, but shouldn't the difference in time converge to a exact difference? I mean, we could end up with a difference so big that the results may begin to be very inaccurate. In fact I'm not using Google as source of truth, I'm just comparing two results against Vanhalla.

**Comment by danpat** [comment]
That's 77km/h vs 88km/h - I highly doubt that *either* of those are reasonable average speeds for a long journey like that.

In order to make this ticket concretely actionable, you're going to have to point out something *specific* that you think is wrong.  The fact that Valhalla disagrees with other routing engines is known.  Other routing engines also mostly disagree with each other.

**Comment by arielmoraes** [comment]
Indeed, I agree. Unfortunately I don't have something specific, my inquire was just if Valhalla had configurations that could help align the time results between the engines.

Closing the issue. Thank you for your time.
