### ISSUE TITLE
Map Matching trace_route response change?

### ISSUE THREAD

**Issue by canadaka** [valhalla/valhalla#2955]
I've been developing on a build of Valhalla Master on a local VM from Feb 16th 2021. We're setting up production servers for testing using Valhalla [release 3.1.0](https://github.com/valhalla/valhalla/commit/b4055fda965e0284910bf229c5aba082e4474bf1) and I'm getting very different results using the Map Matching /trace_route feature.

The Feb 16th Valhalla returns "alternates" as an array of ALL objects, each with a UNIQUE leg shape.

![image](https://user-images.githubusercontent.com/108178/111845323-d8a9bb80-88c1-11eb-8fb3-856d90c3c3c8.png)

The latest release 3.1.0 returns "alternates" as an array, but the array items are NOT all objects and the format of the rows that are objects is different. Along with that both the alternative trip legs returned in my test are exactly the same to each other.

![image](https://user-images.githubusercontent.com/108178/111845055-5b7e4680-88c1-11eb-9bfe-3c18f2f932ab.png)

With the Feb 16th server I am able to decode the shape of all the alternates and merge them together one after another to create a single line. I am uploading a messy GPX file and snapping it to our map.

**Comment by kevinkreiser** [comment]
yep the first version of alternates in the serializer was completely borked tbh so it got fixed in #2811. honestly we have a bunch of good fixes since then. i would suggest you just use master or wait for the next release. tbh we are about due for another :smile:

**Comment by kevinkreiser** [comment]
@valhalla/contributors anybody have a problem with cutting another release? i feel like now is as good a time as any.

**Comment by canadaka** [comment]
OK, good to know I'm not crazy! Would be nice to build on a release.

What I'm doing, combining all the alternatives into a single line to get a "map snapped" version of an input line, is that a proper usage?

**Comment by kevinkreiser** [comment]
Well the reason they are broken up is because the algorithm cannot connect all the pieces, either they are too far apart or something about them makes the matching stop working along the way (too far away from actual geometry or they go into a dead end or or or). What you are doing will lead seconds of the polyline being "as the crow flies" where you splice the routes together rather than snapped to the road geometry.

**Comment by canadaka** [comment]
Yah that is what I expected, straight lines connecting the snapped segments, that is fine. Just want to make sure this will be the format going forward I can rely on.

**Comment by kevinkreiser** [comment]
yep it was always supposed to be i just wrote the first version a bit buggy when i switched to rapidjson serialization
