### ISSUE TITLE
valhalla_build_tiles error "Failed to open file"

### ISSUE THREAD

**Issue by canadaka** [valhalla/valhalla#2956]
I have 27 different PBF files for different regions of the world that I merge together into a single PBF for Valhalla to use. But our `valhalla_build_tiles` is failing with the merged PBF. So I decided to convert each source .OSM file to it's own PBF file and try building each region one by one with valhalla_build_tiles to narrow down the issue.

Most of the PBF files build fine with no errors using valhalla_build_tiles. But a few of them have the following error:
`Failed tile 2/860469/0: Failed to open file /mnt/valhalla_tiles/2/000/860/469.gph`
then the console outputs a lot of this before crashing:
```
2021/03/20 06:50:39.096469 [WARN] Local Edge Index exceeds max: 200
2021/03/20 06:50:39.096480 [WARN] Local Edge Index exceeds max: 201
2021/03/20 06:50:39.096489 [WARN] Local Edge Index exceeds max: 202
2021/03/20 06:50:39.096499 [WARN] Local Edge Index exceeds max: 203
2021/03/20 06:50:39.096507 [WARN] Local Edge Index exceeds max: 204
2021/03/20 06:50:39.096518 [WARN] Local Edge Index exceeds max: 205
2021/03/20 06:50:39.096526 [WARN] Local Edge Index exceeds max: 206
2021/03/20 06:50:39.096542 [WARN] Local Edge Index exceeds max: 207
2021/03/20 06:50:39.096553 [ERROR] NodeInfo: edge count exceeds max: 208
Segmentation fault (core dumped)
```

I've been unable to figure out why this is happening. The data in the OSM files and the PBF they are converted into using osmosis looks good. 
`/usr/bin/osmosis --rx europe-uk.osm --write-pbf europe-uk.pbf omitmetadata=true`

I tested our merged world file with Osmium `osmium fileinfo -e world.pbf` and the data looks all good.
```
File:
  Name: world.pbf
  Format: PBF
  Compression: none
  Size: 777771177
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=0.47
    pbf_dense_nodes=true
[======================================================================] 100%
Data:
  Bounding box: (-159.71815,-54.85535,178.10809,70.71892)
  Timestamps:
    First:
    Last: 1970-01-01T00:00:01Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 133875303
  Number of ways: 29835523
  Number of relations: 0
  Smallest changeset ID: 0
  Smallest node ID: 1
  Smallest way ID: 1
  Smallest relation ID: 0
  Largest changeset ID: 0
  Largest node ID: 172781623
  Largest way ID: 29838460
  Largest relation ID: 0
  All objects have following metadata attributes: none
  Some objects have following metadata attributes: none
  Number of buffers: 189398 (avg 864 objects per buffer)
  Sum of buffer sizes: 12110315456 (12.11 GB)
  Sum of buffer capacities: 12412387328 (12.412 GB, 98% full)
```
I've also tested the individual .OSM files that error during build and see no issues with Osmium in them.

I've tried with the latest 3.1.0 release of Valhalla along with the lastest Master code.

I ran some validation tests on a working and a failed OSM source file in JOSM. Both have some similar errors and warnings. Nothing that stands out for the one that failed.
![image](https://user-images.githubusercontent.com/108178/111862897-6fec2e80-8915-11eb-80ca-fa5a23572f7e.png)

This is a PBF of the smallest region that is failing to build.
[asia-india.zip](https://github.com/valhalla/valhalla/files/6175082/asia-india.zip)

**Comment by ImreSamu** [comment]
> edge count exceeds max ..

imho : 
based on https://valhalla.readthedocs.io/en/latest/terminology/    -> _"edge - a line connected between nodes"_
try to remove all duplicated edges ...    

```
$ osmium cat asia-india.pbf -f opl | grep ^w | cut -d" " -f9 | sort | uniq -d |  head -n3
Nn172433233,n172433234,n172433235,n172433236,n172433237,n172433238,n172433239,n172433240,n172433241,n172433242,n172433243,n172433244,n172433245,n172433246,n172433247,n172433248,n172433249,n172433250,n172433251,n172433252,n172433253,n172433254,n172433255,n172433256,n172433257,n172433258,n172433259,n172433260,n172433261,n172433738
Nn172433520,n172433521,n172433522,n172433523,n172433524,n172433525,n172433527
Nn172433527,n172434262

$ osmium cat asia-india.pbf -f opl | grep ^w | grep Nn172433527,n172434262
w29720552 v0 dV c0 t i0 u Tname=Heartbeat,highway=path,bicycle=designated Nn172433527,n172434262
w29720555 v0 dV c0 t i0 u Tname=Heartbeat,highway=path,bicycle=designated Nn172433527,n172434262

$ osmium cat asia-india.pbf -f opl | grep ^w | grep Nn172670637,n172670638,n172670639,n172670645
w29800764 v0 dV c0 t i0 u Tname=Kalka%20%Bypass,highway=trunk Nn172670637,n172670638,n172670639,n172670645
w29800766 v0 dV c0 t i0 u Tname=Kalka%20%Bypass,highway=trunk Nn172670637,n172670638,n172670639,n172670645

```

**Comment by nilsnolde** [comment]
Looking quickly at the code involved, I'd rather think it's duplicate node IDs where the same node ID is on ~100-xxx different nodes connecting to different edges and eventually exceeding the limit. Seems your PBF generation pipeline has some problems. 

You know where to find help if you need it..

**Comment by canadaka** [comment]
Thanks for the tips and grep examples. This helps me focus attention on the source OSM data, rather that some bug or weirdness with the valhalla_build_tiles.

**Comment by canadaka** [comment]
I've cleaned up a lot of the "overlapping ways", "way contains segment twice" and "ways with same position" errors detected by JOSM. But some OSM files still fail however I don't get the "edge count exceeds max" warnings or errors. Just the failed tile error then crash.

```
2021/03/21 01:06:20.504763 [INFO] Finished with 0 reclassified.  Turn channel count = 0
2021/03/21 01:06:20.512257 [INFO] Reclassifying ferry connection graph edges...
2021/03/21 01:06:20.692264 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 0, 0 edges reclassified.
2021/03/21 01:06:20.710807 [INFO] Building 682 tiles with 4 threads...
2021/03/21 01:06:20.713533 [WARN] Admin db  not found.  Not saving admin information.
2021/03/21 01:06:20.713546 [WARN] Time zone db  not found.  Not saving time zone information.
2021/03/21 01:06:20.714175 [WARN] Admin db  not found.  Not saving admin information.
2021/03/21 01:06:20.714189 [WARN] Time zone db  not found.  Not saving time zone information.
2021/03/21 01:06:20.714266 [WARN] Admin db  not found.  Not saving admin information.
2021/03/21 01:06:20.714306 [WARN] Time zone db  not found.  Not saving time zone information.
2021/03/21 01:06:20.715015 [WARN] Admin db  not found.  Not saving admin information.
2021/03/21 01:06:20.715026 [WARN] Time zone db  not found.  Not saving time zone information.
2021/03/21 01:06:20.715422 [ERROR] Failed tile 2/762447/0: Failed to open file /mnt/valhalla_tiles/2/000/762/447.gph
2021/03/21 01:06:20.715772 [ERROR] Failed tile 2/745166/0: Failed to open file /mnt/valhalla_tiles/2/000/745/166.gph
2021/03/21 01:06:22.499573 [INFO] Finished
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted (core dumped)
```

Is there an option for moer verbose logging of the `valhalla_build_tiles`?

**Comment by kevinkreiser** [comment]
there was a known issue where this would happen which was fixed by: https://github.com/valhalla/valhalla/pull/2810

if you're not using master please try with master

**Comment by nilsnolde** [comment]
@canadaka it'd be best if you could run it with gdb, e.g. `gdb --args valhallla_build_tiles -c valhalla.json your.pbf`, then type `run`, wait until it fails and then `where` to post the trace.
