### ISSUE TITLE
costing issue motor_scooter and motorbike

### ISSUE THREAD

**Issue by huggymann** [valhalla/valhalla#2959]
while changing settings in motor_scooter use_primary, i cannot recognize a real change in the routing result. i have two examples of routing ~130 km with use_primary 0 and 5. There is a small change, but the route is more or less the same. I would have expected to see a great difference, but it seems to use the main roads anyway. 

use_primary = 0
![grafik](https://user-images.githubusercontent.com/61777949/111912429-c79bae80-8a69-11eb-9918-2d122f15eac9.png)
use_primary = 5
![grafik](https://user-images.githubusercontent.com/61777949/111912468-fa45a700-8a69-11eb-8372-8a39edc22dc5.png)

would it be possible also to add more street types to use? Like road type 1, type 2 and so on. to really fine tune the routing to get either fast street or small streets far away from any traffic.
an example is here, where each street type can be selected with a weight (the number behind the star, which is 0-5 in valhalla)
![grafik](https://user-images.githubusercontent.com/61777949/111912564-82c44780-8a6a-11eb-9813-6c05c92d3950.png)

**Comment by dnesbitt61** [comment]
use_roads option only applies to bicycles. Did you mean the `use_primary` option?

**Comment by huggymann** [comment]
Oh sorry, yes, of course i was mentioning to use_primary. The other setting is for bikes. Thank you for the hint. 
I was wondering that the road was nearly the same with each setting.

**Comment by huggymann** [comment]
any comments?

**Comment by kevinkreiser** [comment]
@huggymann are you saying that `use_primary` seems to be broken? if that is the case we can easily add a test for that and figure out what is going on there. It was a bit unclear to me wether you had a typo in your comment here or whether you accidently used the wrong option in your request (and therefor didnt see a difference)

**Comment by huggymann** [comment]
@kevinkreiser yes, sorry for confusion, it is all corrected now in the issue description. 
in the two pictures above i chose `use_primary` 0 and 1, the road is nearly the same (really just a very small difference) 

i did another test with a city nearby that has direct primary road connection to my city (i marked as red in the picture). Neither option for `use_primary` does change the routing. I guess my answer to your question is **yes, i am saying `use_primary` is not working**

Another question i had was if it would be possible to add more street types . it is `use_primary` and `use_highways` from cars. i would like to fine tune my routing like (sorry, i am not native english and i am not sure to use correct terms below): 
-MAIN ROAD
-side street
-local street

![image](https://user-images.githubusercontent.com/61777949/112953515-d6572500-913d-11eb-8097-e7347d5573d8.png)
![image](https://user-images.githubusercontent.com/61777949/112953542-de16c980-913d-11eb-8f82-a16ceee2e257.png)

**Comment by huggymann** [comment]
any comments on my questions? sorry, i dont know who to ask  ;-)

**Comment by nilsnolde** [comment]
I actually don't think there's a test covering the use of `use_primary`, though it's hard to be sure. I think that's the best way to know for sure. If you want to dig into it a little, I found the gurka tests here to be very intuitive in setup and execution.. E.g. this is a fairly easy one:
github.com/valhalla/valhalla/blob/master/test/gurka/test_shortest.cc

**Comment by huggymann** [comment]
Hello, 

@kevinkreiser 
still i am trying to figure out why the parameters use_primary (and also use_tracks in motorbike) are not changing the route at all in my app. still, the navigation is always routing through main roads. You mentioned adding a test, would you be able to do that? 

- could someone please test if motor_scooter -> use_primary and motorbike use_trails are chanigng anything in the route? 
- i am running "pure maps" on sailfish/ubuntu touch. do you know any app that uses valhalla where i can test the functionality?
- is there anything i need to set to make these parameters work?

**Comment by huggymann** [comment]
hello, 

today i did a test with valhalla setup in docker with some requests in motor_scooter and motorcycle. 
in motor_scooter, the setting use_primary does nearly change a thing (please see below). My understanding has been that setting "use_primary" to 0.0 will actually (more or less) disable the usage of primary roads.  like with use_highways.
independed from the setting use_primary, the motor_scooter is avoiding high speed roads due to the speed_limit (default is 45 kph). Here you can see a part where it is avoiding a really short part of the road (which i marked in red). Maybe the issue is the definition of "avoiding". it seems to avoid it only if it finds a way with same lenght or so. 
![grafik](https://user-images.githubusercontent.com/61777949/120322984-4d976980-c2e5-11eb-9587-2fc26f05a120.png)


## motor_scooter
#### 
- 1st request top_speed": "50", **"use_primary":"0.0"**, "use_highways":"0.0", "use_hills":"0.0"
`curl http://localhost:8002/route --data '{"locations":[{"lat":51.0637,"lon":13.82},{"lat":50.8961,"lon":14.8315}],"costing":"motor_scooter","costing_options":{"motor_scooter":{"top_speed": "50", "use_primary":"0.0", "use_highways":"0.0", "use_hills":"0.0"}},"directions_options":{"units":"kilometers"}}' | jq '.'
`
   - answer 
   >  "summary": {
      "has_time_restrictions": false,
      "min_lat": 50.896158,
      "min_lon": 13.820001,
      "max_lat": 51.125792,
      "max_lon": 14.831959,
      "time": 7536.732,
      "length": 100.3,
      "cost": 13823.441
    },
    "status_message": "Found route between points",
    "status": 0,
    "units": "kilometers",
    "language": "en-US"
  }




-2nd request top_speed": "50", **"use_primary":"1.0"**, "use_highways":"0.0", "use_hills":"0.0"
`curl http://localhost:8002/route --data '{"locations":[{"lat":51.0637,"lon":13.82},{"lat":50.8961,"lon":14.8315}],"costing":"motor_scooter","costing_options":{"motor_scooter":{"top_speed": "50", "use_primary":"1.0", "use_highways":"0.0", "use_hills":"0.0"}},"directions_options":{"units":"kilometers"}}' | jq '.'
`
    - answer 
   > "summary": {
      "has_time_restrictions": false,
      "min_lat": 50.896158,
      "min_lon": 13.820001,
      "max_lat": 51.125792,
      "max_lon": 14.831959,
      "time": 7697.645,
      "length": 102.528,
      "cost": 11531.607
    },
    "status_message": "Found route between points",
    "status": 0,
    "units": "kilometers",
    "language": "en-US"
  }



## motorcycle 
- 1st request top_speed": "120", "use_highways":"0.0", **"shortest":"1.0"**
`curl http://localhost:8002/route --data '{"locations":[{"lat":51.0637,"lon":13.82},{"lat":50.8961,"lon":14.8315}],"costing":"motorcycle","costing_options":{"motorcycle":{"top_speed": "120", "use_highways":"0.0", "shortest":"1.0"}},"directions_options":{"units":"kilometers"}}' | jq '.'
`
   - answer 
   >    "summary": {
      "has_time_restrictions": false,
      "min_lat": 50.896158,
      "min_lon": 13.820001,
      "max_lat": 51.064912,
      "max_lon": 14.831959,
      "time": 5040.093,
      "length": 85.824,
      "cost": 5097.364
    },
    "status_message": "Found route between points",
    "status": 0,
    "units": "kilometers",
    "language": "en-US"



 - 2nd request top_speed": "120", "use_highways":"0.0", **"shortest":"0.0"**
` curl http://localhost:8002/route --data '{"locations":[{"lat":51.0637,"lon":13.82},{"lat":50.8961,"lon":14.8315}],"costing":"motorcycle","costing_options":{"motorcycle":{"top_speed": "120", "use_highways":"0.0", "shortest":"0.0"}},"directions_options":{"units":"kilometers"}}' | jq '.'`

    - answer 
   > "summary": {
      "has_time_restrictions": false,
      "min_lat": 50.896158,
      "min_lon": 13.820001,
      "max_lat": 51.064912,
      "max_lon": 14.831959,
      "time": 5040.093,
      "length": 85.824,
      "cost": 5097.364
    },
    "status_message": "Found route between points",
    "status": 0,
    "units": "kilometers",
    "language": "en-US"
