### ISSUE TITLE
Incorrect link reclassification

### ISSUE THREAD

**Issue by genadz** [valhalla/valhalla#2976]
There is a particular example. We have sequence of links: https://www.openstreetmap.org/way/699116538 https://www.openstreetmap.org/way/699116539 https://www.openstreetmap.org/way/25845125 . Despite of the fact that these links connect two trunk roads, valhalla downgrades them to the level 1 because of this tertiary road https://www.openstreetmap.org/way/128268520#map=17/59.31748/14.15687 . I think if a sequence of links leads to some major road we shouldn't downgrade all the sequence of links @dnesbitt61 @kevinkreiser

**Comment by genadz** [comment]
moreover, we mark https://www.openstreetmap.org/way/25845125 as a `turn_channel` which is also suspicious

**Comment by genadz** [comment]
> im not 100% sure what you mean by this but i agree about this case. if the links are connecting two pieces of motorway they can stay motorway links. the problem is when you have somethign like this: https://www.openstreetmap.org/way/9060368

my point is: when you have a sequence of connected links: `a -> b -> c` and `c` leads to a major road, we should mark all the sequence `a,b,c` with the highest class even if the link `b` can lead to some tertiary road

**Comment by genadz** [comment]
@kevinkreiser @dnesbitt61 I tried just to **turn off links reclassification** logic and test performance locally. So, what I did:
1. downloaded Pennsylvania region from osm https://download.geofabrik.de/north-america/us/pennsylvania.html ;
2. generated 10000 random route requests in this region (the points in each request are located at a distance of more than 100 km).

I got the same performance results:

**master**
```
all items: 9569
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.021s	0.041s	0.045s	0.049s	0.056s	0.065s	0.076s	0.165s	0.229s
mean = 0.0437
```

**without links reclassification**
```
all items: 9569
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.021s	0.039s	0.043s	0.048s	0.054s	0.064s	0.076s	0.156s	0.220s
mean = 0.0426
```

so, it should be definitely tested on the whole planet but I don't see a reason why results will be different.

**Comment by kevinkreiser** [comment]
@genadz how do the shortcut counts look, did they change?

**Comment by genadz** [comment]
> @genadz how do the shortcut counts look, did they change?

yes, a little:
from **master** logs:
```
2021/04/01 17:04:37.383138 [INFO] Creating shortcuts on level 1
2021/04/01 17:04:38.951480 [INFO] Finished with 63164 shortcuts
2021/04/01 17:04:38.951498 [INFO] Creating shortcuts on level 0
2021/04/01 17:04:39.547108 [INFO] Finished with 25138 shortcuts
```

from branch **without link reclassification:**
```
2021/04/01 16:26:27.838431 [INFO] Creating shortcuts on level 1
2021/04/01 16:26:29.334837 [INFO] Finished with 62324 shortcuts
2021/04/01 16:26:29.334851 [INFO] Creating shortcuts on level 0
2021/04/01 16:26:29.918675 [INFO] Finished with 28314 shortcuts
```

**Comment by mandeepsandhu** [comment]
Does this link reclassification cause us to hit our transition count limit sooner than we'd like? If we mark all the cases similar to what described in https://github.com/valhalla/valhalla/issues/2976#issuecomment-810296683, does that have a meaningful impact on the ETA as well (since the up-classified segments will have greater speed)?

**Comment by genadz** [comment]
> Does this link reclassification cause us to hit our transition count limit sooner than we'd like? If we mark all the cases similar to what described in [#2976 (comment)](https://github.com/valhalla/valhalla/issues/2976#issuecomment-810296683), does that have a meaningful impact on the ETA as well (since the up-classified segments will have greater speed)?

on the data that I mentioned here https://github.com/valhalla/valhalla/issues/2976#issuecomment-812032033 , more than 30% of routes are different (by instructions). Some of them became worse and some better (in terms of ETA).

**Comment by genadz** [comment]
@kevinkreiser @dnesbitt61 I bumped into one more case that causes long detours, issue https://github.com/valhalla/valhalla/issues/2979 . Due to the fact that after link reclassification shortcuts become longer, I've met such problems only on **master** branch.

**Comment by kevinkreiser** [comment]
Well the good news is disabling reclassification is a config parameter so anyone who wants to can opt out. Maybe the result of this work will be to default it to `off` in the config? I do think @dgearhart should take a look into the potential guidance consequences that you mentioned. Is there any thing about turn channels/lanes that this could impact, also someone should certainly do a deeper dive on the RAD diffs.

**Comment by genadz** [comment]
> Well the good news is disabling reclassification is a config parameter so anyone who wants to can opt out. Maybe the result of this work will be to default it to `off` in the config? I do think @dgearhart should take a look into the potential guidance consequences that you mentioned. Is there any thing about turn channels/lanes that this could impact, also someone should certainly do a deeper dive on the RAD diffs.

If I remember correctly, we identify `turn_channels` in `ReclassifyLinks` function.

**Comment by dnesbitt61** [comment]
It has been a very long time since I have looked at link reclassification and its impacts on performance. I seem to recall a modest performance improvement on long routes due to fewer, but longer shortcuts on motorways. A secondary but less important benefit is not expanding unnecessarily on what would have been motorway ramps that connect only to secondary and tertiary roads.  I probably tested Lancaster to San Diego (like I always did back then). I don't use shortcuts and hierarchies with my current work so feel free to default to off if needed. I will say that the reclassify algorithm was probably the most difficult piece of code I wrote for Valhalla.

**Comment by genadz** [comment]
> I will say that the reclassify algorithm was probably the most difficult piece of code I wrote for Valhalla.
totally agree)) it took a while to me to understand all the code

**Comment by dgearhart** [comment]
> > Well the good news is disabling reclassification is a config parameter so anyone who wants to can opt out. Maybe the result of this work will be to default it to `off` in the config? I do think @dgearhart should take a look into the potential guidance consequences that you mentioned. Is there any thing about turn channels/lanes that this could impact, also someone should certainly do a deeper dive on the RAD diffs.
> 
> If I remember correctly, we identify `turn_channels` in `ReclassifyLinks` function.

If we would not mark turn_channels then that would negatively impact guidance

**Comment by genadz** [comment]
> If we would not mark turn_channels then that would negatively impact guidance

@dgearhart Ok, got it! I will refactor the code to use it separately

**Comment by genadz** [comment]
Some brief overview of the work that was done:

### **Turn off links reclassification**
1. If we don't downgrade links -> some turn channels may be lost (we don't mark `motorway_link` or `trun_link` a as turn channel) -> it negatively impacted on guidance. (thank you @dgearhart for help);
2. for some cross-country roads we got ~20% performance decrease.

Taking into account these results I tried to fix links reclassification algorithm.
The main problem that we have right now: for some cases we **downgrade links that shouldn't be downgraded**. An example of such behavior is in the description of the issue. More formal: let's suppose we have two motorways `A` and `B` and the link `c` that lead from `A` to `B`. So, in case we have a road `d` that attaches to the link `c` -> final class of the link will be equal to the class of road `c` instead of class of the road `B` that this link actually leads to.

_One more example from the osm map_: there is a link https://www.openstreetmap.org/way/25269119 that leads from motorway road `M1` to trunk road `M4`. But we also have a secondary road https://www.openstreetmap.org/way/25269113 that attaches to the link. So, final class of the link will be `secondary`.
![Screenshot from 2021-04-14 22-40-06](https://user-images.githubusercontent.com/9436623/114769570-0c69eb00-9d73-11eb-9610-9b741c70b07d.png)


### **New approach for links reclassification**

To fix the problem described above I came up a modification of the current algorithm:
In **master**, in order to detect the actual road a link leads to, we choose the best class of all roads that adjacent to the link. I changed it to the following: we collect **all roads reachable from a link** (in forward direction using other links) and then choose the best one.
So, it fixed cases described above but as turned out this algorithm downgrades too few links (and increase **divebomb** probability). An example (these links will not be downgraded https://www.openstreetmap.org/way/564897701 https://www.openstreetmap.org/way/339617855):
![Screenshot from 2021-04-14 22-54-36](https://user-images.githubusercontent.com/9436623/114771086-d9285b80-9d74-11eb-888e-f141c6b88828.png)

To fix divebombs, I wrote a logic that detects if a link went back to the same road it came from (parse refs,names and compare results). It fixed divebombs (for most cases), but some other cases stayed unfixed.
An example: this link https://www.openstreetmap.org/way/7006913 will not be downgraded but should be, because a destination is this road https://www.openstreetmap.org/way/526274534 . But my algorithm build a chain of links that leads to this motorway https://www.openstreetmap.org/way/7007709 road and decides not to downgrade the link.
 
![Screenshot from 2021-04-14 23-37-30](https://user-images.githubusercontent.com/9436623/114775870-7934b380-9d7a-11eb-84c7-d17752502fef.png)


### **The last chance**
The last idea I wanted to try is the following: leave the algorithm that in `master` right now but for some cases  when we definitely know where the link lead to -> don't downgrade. I think we should parse `ref`,`destination:ref` tags of links for that.

@dnesbitt61 @kevinkreiser do you have any thoughts about this ? probably there is a simple solution that I missed ?

**Comment by kevinkreiser** [comment]
>  leave the algorithm that in master right now but for some cases when we definitely know where the link lead to -> don't downgrade

this is what i was suggesting to you originally. a surgical approach. instead of changing everything make a change that only seeks to modify those problem reclassifications.

tbh i havent thought about alternative solutions to this problem yet, let me think about it a little bit and thank you for the extensive explanation, it really helps to follow what is going on

**Comment by dnesbitt61** [comment]
Not sure if there is a simple solution, but I do remember some cases where the link intersected with a service road on the way to the road it exited onto. I don't quite remember what I did there (perhaps just skipped service roads that connect). One problem I remember is a link that intersects a separated road and continues beyond the first non-link intersected).

**Comment by genadz** [comment]
> Not sure if there is a simple solution, but I do remember some cases where the link intersected with a service road on the way to the road it exited onto. I don't quite remember what I did there (perhaps just skipped service roads that connect). One problem I remember is a link that intersects a separated road and continues beyond the first non-link intersected).

do you think that parsing tags `ref,destination:ref` can help ?

**Comment by kevinkreiser** [comment]
> do you think that parsing tags ref,destination:ref can help ?

I am skeptical of anything that relies on well populated attribution in OSM (in other words you will miss some cases). But its worth looking into. You might be able to look a thttps://taginfo.openstreetmap.org/tags/highway=motorway_link#combinations to figure out what the prevalence of ref and destination:ref are on *_link ways. Seems pretty well populated on motorway_link probably lesser on lower classes of roads!
