### ISSUE TITLE
prime_server.cpp:455 proxy_t: bad_function_call

### ISSUE THREAD

**Issue by bmarcco** [valhalla/valhalla#2985]
When send request to localhost:8002/route?json={"verbose":true,"locations":[{"lat":42.358528,"lon":-83.271400},{"lat":42.996613,"lon":-78.749855}],"costing":"bicycle","costing_options":{"bicycle":{"bicycle_type":"road"}},"directions_options":{"units":"miles"},"id":"12abc3afe23984fe"} 

I get an error "**[ERROR] src/prime_server.cpp:455 proxy_t: bad_function_call**"

**Comment by kevinkreiser** [comment]
i have an inkling of how this could happen but I havent vetted that yet. if im right the bug would be in prime_server though not in valhalla.

**Comment by kevinkreiser** [comment]
this is the line in question: https://github.com/kevinkreiser/prime_server/blob/master/src/prime_server.cpp#L435

im not sure how it could go wrong. im pretty sure that the language allows converting std::function to bool for the semantic of: does this functor have a callable object attached or is it empty.

@bmarcco we should migrate this issue to the prime_server repo. ill do that now

**Comment by chaitu2chowdary** [comment]
hi, @bmarcco Did you solve this issue? 
I get the same error as you got.
is there any workaround?
Thanks in advance.
