### ISSUE TITLE
Map matching GPX file as payload

### ISSUE THREAD

**Issue by bmarcco** [valhalla/valhalla#2993]
Hi, is it possible to use a .gpx file as payloads for POST requests for the http://localhost:8002/trace_route?

**Comment by kevinkreiser** [comment]
its currently not possible though it could be implemented. the transformation from gpx to the json format we support is quite trivial though, you should be able to pretty quickly write some conversion code in any of your favorite scripting languages.

**Comment by marko-bogdanovic** [comment]
Thank you for your prompt response.

**Comment by bmarcco** [comment]
Thank you for your prompt response!

**Comment by canadaka** [comment]
I've been trying to do this for awhile, with not much success. No problem converting the GPX to GeoJSON then converting to encodedPolyline using `polyline.fromGeoJSON` (https://github.com/mapbox/polyline)

```
var routeEncoded = polyline.fromGeoJSON(routeDataGeoJSON, 6);
$.ajax({
	url: valhallaServer+'/trace_route?json=',
	type: 'POST',
	data: JSON.stringify({
		shape_match: "map_snap",
		costing: "pedestrian",
		encoded_polyline: routeEncoded
	}),
	success: function(response) {
		console.log('VALHALLA trace_route', response);
	},
	dataType: 'json'
});
```

It _sometimes_ works but more often fails with a 400 Bad Request response. I can even take an exact trace of a few of the routable segments and it even fails.

I would love to add this as a feature to snap GPX traces to our routing network, but I cannot get it working in a reliable or predictable manor. Any advice would be greatly appreciated!

**Comment by canadaka** [comment]
FYI
After much debugging I've found that _some_ of the /trace_route issues happen if there are ANY duplicate points in the `encoded_polyline` passed to the server. If there is a point with the exact same lat/lng it fails everytime. If I fix that duplicate point, it works.

**Comment by kevinkreiser** [comment]
@canadaka what does it say in the response? there are multiple failures that can happen that result in a 400, but they are usually accompanied with an error message that will help us tell what part of the request its failing on. it could be something with the encoding of the polyline or it could be a failure to map match.

**Comment by canadaka** [comment]
When there is a duplicate points in the encoded_polyine the response is.
```
{"error_code":199,"error":"Unknown:Bad encoded polyline","status_code":400,"status":"Bad Request"}
```

This one is easy enough to check for and fix the data before making the request. Could be useful info for others.

**Comment by Blobonat** [comment]
Maybe this helps someone... I wrote a small python script to convert a GPX file into the Valhalla specific JSON format (not encoded_polyline): [gpx-to-valhalla-json](https://github.com/Blobonat/gpx-to-valhalla-json)
