### ISSUE TITLE
Route optimization for more than one vehicle

### ISSUE THREAD

**Issue by marko-bogdanovic** [valhalla/valhalla#2994]
Hello, I would like to do optimization for more vehicles and more locations that need to be visited. Similar to the picture in the attachment where the green markers represent the vehicles and the blue markers the locations that need to be visited. Do you have any idea how to do this? Thank in advance.
![Capture](https://user-images.githubusercontent.com/82383949/114396015-57320a00-9b9d-11eb-9bb2-4fe5602f9154.PNG)

**Comment by danpat** [comment]
@marko-bogdanovic Valhalla's built-in optimizer is a simple TSP solver.

For multi-vehicle, you're going to want something a bit more sophisticated, like:

  - http://vroom-project.org/
  - https://developers.google.com/optimization/routing/vrp
  - https://jsprit.github.io/
  - https://www.optaplanner.org/learn/useCases/vehicleRoutingProblem.html

**Comment by marko-bogdanovic** [comment]
Thanks I'll try with http://vroom-project.org/.
