### ISSUE TITLE
Set C++17 as default for cmake

### ISSUE THREAD

**Issue by mesozoic-drones** [valhalla/valhalla#3000]
Hello! Are you planning to update CMakeLists to use C++17 standard instead of 14? If there are no obstacles, I could make a PR with this update.

**Comment by nilsnolde** [comment]
That PR would have to be quite a little more extensive I'm afraid, valhalla is not (yet) c++17 ready.. It's been discussed a few times, I think (aside of some implementational details) the main concern is to drop old compilers with that move. 

Without weighing in too much: we (want to) produce python wheels from valhalla (not yet public), and for the millions of linux, wheels packaging c/c++ deps are a HUGE PITA! We basically **have to** use a `manylinux` distro, but even the latest one, running on Debian 9, has only gcc v6.3.0. At least that one doesn't support stuff like `std::optional` and some others (I found that out when also wheeling [VROOM](https://github.com/VROOM-Project/vroom) which is using c++17).

Would like to hear the core team's opinion on this though!

**Comment by kevinkreiser** [comment]
I think there were just a few folks who had some older compilers that werent there yet. @brunoabinader @mskurydin @averkhaturau do you have any target platforms with compilers that dont support c++17 at this point?

**Comment by nilsnolde** [comment]
I'd not like to stand in the way of a significant improvement (and one or the other code redundancy) with our python wheels. So if this would be kinda the only usage standing between valhalla and c++17, I wouldn't be alienated by the move. A few people with old distros would be unlucky to not be able to use valhalla as a python package, but those should be alienated by the distro they're using, not valhalla;)

**Comment by averkhaturau** [comment]
AFAIK we still need to guarantee support of C++14 for one of our customers. So, I have nothing against C++17, but please leave a CI job checking that valhalla compiles with C++14. Unfortunately it means that we cannot use C++17 things, like std::filesystem or std::optional in valhalla.

**Comment by mesozoic-drones** [comment]
> I would personally like to update but if there are significant contributors whose downstream projects are on older build systems I think its best not to rock their boats.

Absolutely agree with you. Before the final decision should we wait some time for objections from contributors?

Tiny benefit from moving to c++17: for many developers open source is about trying something new and experimenting with latest versions. So moving to newer standard may attract some new contributors)

**Comment by brunoabinader** [comment]
@kevinkreiser @averkhaturau one alternative we could have is to move to C++17 but provide polyfills for those who still require C++14 compatibility. Both `std::filesystem` and `std::optional` have open-source polyfill alternatives e.g. https://github.com/gulrak/filesystem/ and https://github.com/mapbox/Optional/.

**Comment by mskurydin** [comment]
If we start to use the new syntax the polyfills for the standard library will not fully help (e.g. structured bindings).

**Comment by kevinkreiser** [comment]
Yeah I was thinking about this earlier and came to the same conclusion as @mskurydin. If some important systems are still targeting c++14 it doesnt make sense to move to c++17. I know that we could still stay backwards compatible if we are careful but that basically means we cant make use of the new bits of the language as well which means there is no real benefit.

**Comment by kevinkreiser** [comment]
I'm going to close this issue in favor of the original issue that asked this same question (almost 1k issues ago!): https://github.com/valhalla/valhalla/issues/2009

There will come a day when we flip the switch and when we do we can close that issue

**Comment by mloskot** [comment]
> I think there were just a few folks who had some older compilers that werent there yet.

w.r.t. the meaning of "old", I've added some notes on the GCC situation https://github.com/valhalla/valhalla/issues/2009#issuecomment-820665802
