### ISSUE TITLE
Could not install valhalla in node

### ISSUE THREAD

**Issue by chaitu2chowdary** [valhalla/valhalla#3004]
When I try to install valhalla in a node project it's giving me errors.
```
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/valhalla/v3.0.0-rc.2/Release/linux-x64-napi-v5.tar.gz
```
probably the link is broken.

How can I run the Valhalla service forever on a server?
BTW I am using ubuntu 20.04.

**Comment by TimMcCauley** [comment]
@chaitu2chowdary it would definitely help if you investigated _a little (!)_ yourself before sending out these kind of ill-considered questions to an open source community of dedicated people who are voluntarily contributing their time and resource to projects like these for free.

**Comment by chaitu2chowdary** [comment]
@TimMcCauley I am sorry if I hurt you.
but coming to the point I am from a javascript background and would like to use Valhalla in my app.
If this disappoints you I can close it.
Thanks

**Comment by TimMcCauley** [comment]
@chaitu2chowdary no offense taken. I just want to encourage a little preliminary research before delving into a new issue... https://github.com/valhalla/valhalla/pull/2502

**Comment by nilsnolde** [comment]
He's just saying that with a little research you'd see that the node bindings were dropped a longer time ago.

You'll want to host and query Valhalla via HTTP, so you'll set it up as a server.

**Comment by chaitu2chowdary** [comment]
@nilsnolde Thanks for the hint.
I have used supervisor to allowing Valhalla service to be available through reboots. it's working as expected.
