### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by psyeon990** [valhalla/valhalla#3006]
Hello, I'm seonyeon.

I've got connection failure error while sending a request to Meili.

I used code below.

```
url = "http://localhost:8002/trace_route"
headers = {'Content-type': 'application/json'}
data = str(meili_request_body)

r = requests.post(url, data=data, headers=headers)
```

It seems the server of Valhalla refused connection for my request.
How can I fix this error?

**Comment by nilsnolde** [comment]
please share how you setup _valhalla_

**Comment by psyeon990** [comment]
Now I'm reinstalling valhalla on Windows. 
I cloned valhalla and install vcpkg in another directory. For installing vcpkg package needed in valhalla, 'vcpkg_deps.txt' file has to be copied to vcpkg folder?

I also have difficulty in building cmake file. Is there a guide for installation valhalla on Windows?

**Comment by kevinkreiser** [comment]
@psyeon990 all the the service stuff is disabled in the windows builds. we basically only build the library there. if your target platform is windows your best bet is to run a python server and use the valhalla python bindings from inside that

**Comment by nilsnolde** [comment]
Actually the instructions in the README are quite new (and work), I added them only a couple of months back. But you always learn learn the most from CI, look at this repo's azure CI yaml.

I wouldn't do that natively on Windows, unless you can live without proper navigation (forget about getting the right navigation instructions in roundabouts) or stuff like avoid borders, in case you also need to build the graph on Win. Either use docker (will be fairly slow) or, as kevin suggests, build the bindings and wrap them in a flask server or so, then build the graph on linux.

**Comment by kevinkreiser** [comment]
@nilsnolde totally but i think the important point is that @psyeon990 was expecting to see a running server when on windows there is no server support (yet)

**Comment by nilsnolde** [comment]
Yep, also no spatialite support unfortunately, so you also don't get all the goodies that come with the admin & timezone dbs (plus some actually wrong roundabout instructions: #2320 ) .. Wanted to look at spatialite on Win in ages, and think I will soon..

So, my point is, aside from the other confusing comments I made: don't build tiles on Win if you're looking for proper navigation.

**Comment by kevinkreiser** [comment]
hahah yeah I feel like we need a small check list in the windows section of the readme that shows what is and isnt supported. you kind of did that for us already with enumerating the cmake options that work and dont work but its hard for newcomers to understand what those translate to in terms of functionality. we'll get there at some point, the fact it works as well as it does on windows is amazing thanks to you and @mloskot

**Comment by mloskot** [comment]
FYI, I regularly, almost daily, build Valhalla on Windows 10 using VS 2019 and apart from the library I also build these, without problems:

```
valhalla_benchmark_adjacency_list.exe
valhalla_benchmark_loki.exe
valhalla_benchmark_skadi.exe
valhalla_expand_bounding_box.exe
valhalla_export_edges.exe
valhalla_path_comparison.exe
valhalla_run_isochrone.exe
valhalla_run_map_match.exe
valhalla_run_matrix.exe
valhalla_run_route.exe
```

**Comment by nilsnolde** [comment]
> a small check list in the windows section of the readme that shows what is and isnt supported

Yeah you're right.. Let me draft it real quick.

jep @mloskot those are fine, true. it also builds many more e.g. all the valhalla_build_*.exe. But when it's trying to access spatialite when building the tiles it bails.. Should be easy-ish to fix I hope.

**Comment by mloskot** [comment]
>  But when it's trying to access spatialite when building the tiles it bails.

@nilsnolde Is this a relatively new issue? I did use `valhalla_build_tiles.exe` to build tiles w/o issues, but may be a while ago.

**Comment by nilsnolde** [comment]
I remember I was tagging you back when I encountered it first (you didn't what the problem was either), but my github query skills are not good enough to actually find the comment again.. You only run into trouble when you build the admin and timezone db. But I actually didn't try in a while, though I doubt anything changed there in the past 8 months or so. I guess you probably built the tiles without those sqlite dbs @mloskot ?

**Comment by nilsnolde** [comment]
Actually we even test the tile building in CI.

**Comment by mloskot** [comment]
> I remember I was tagging you back when I encountered it first 

That rings a bell - my crappy memory, sorry :)

> I guess you probably built the tiles without those sqlite dbs @mloskot ?

Possibly, I will have to confirm that.

**Comment by psyeon990** [comment]
Thank you for all your help. 
I decided not to install on Windows. Instead, I successfully installed it in Ubuntu on Windows. 
But It also has problems running the sample code in READ.ME. 
The error occurs in line 3.
`valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json`
**valhalla_build_config: command not found**
Same command not found error occurs in code below.

**Comment by nilsnolde** [comment]
You should _roughly_ understand what you're doing even if you follow instructions. Please figure this out by yourself, or I fear a bottomless pit of follow-up questions. (hint: is it in your PATH?)
