### ISSUE TITLE
Performance Drop in Long Bicycle Route

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#3007]
Please run performance tests on cycling routes (and likely pedestrian as well) when changing bidirectional_astar.

Within the last month I have noted a somewhat large drop in performance of a long bicycle route that I use as a stress test of Valhalla bicycle routing. The route is:

./valhalla_run_route --config ../../conf/planetv13.json --multi-run 100 -j '{"locations":[{"lat":39.310012,"lon":-77.463554,"type":"break"},{"lat":40.442265,"lon":-80.007329,"type":"break"}],"costing":"bicycle","costing_options":{"bicycle":{"bicycle_type":"Road","use_roads":"0.0","cycling_speed":"25.0","use_hills":"0.5"}}}

This is always run on my Ubuntu system with no other processes running (clean reboot) and I average the 3 runs (making sure they are consistent so they only vary by a few ms between runs. Last 2 months:
3/10/2021 Valhalla master: **993ms**
4/16/2021 Valhalla master: **1128ms**
This is about a **13.5%** performance drop. Data is the same between tests - only code changes have occurred. A diff in CHANGELOG since the March test:

 * FIXED: Fixed "No route found" error in case of multipoint request with locations near low reachability edges [#2914](https://github.com/valhalla/valhalla/pull/2914)
   * FIXED: Python bindings installation [#2751](https://github.com/valhalla/valhalla/issues/2751)
   * FIXED: Skip bindings if there's no Python development version [#2893](https://github.com/valhalla/valhalla/pull/2893)
   * FIXED: Use CMakes built-in Python variables to configure installation [#2931](https://github.com/valhalla/valhalla/pull/2931)
   * FIXED: Sometimes emitting zero-length route geometry when traffic splits edge twice [#2943](https://github.com/valhalla/valhalla/pull/2943)
   * FIXED: Fix map-match segfault when gps-points project very near a node [#2946](https://github.com/valhalla/valhalla/pull/2946)
   * FIXED: Use kServiceRoad edges while searching for ferry connection [#2933](https://github.com/valhalla/valhalla/pull/2933)
   * FIXED: Enhanced logic for IsTurnChannelManeuverCombinable [#2952](https://github.com/valhalla/valhalla/pull/2952)
   * FIXED: Restore compatibility with gcc 6.3.0, libprotobuf 3.0.0, boost v1.62.0 [#2953](https://github.com/valhalla/valhalla/pull/2953)
   * FIXED: Dont abort bidirectional a-star search if only one direction is exhausted [#2936](https://github.com/valhalla/valhalla/pull/2936)
   * FIXED: Fixed missing comma in the scripts/valhalla_build_config [#2963](https://github.com/valhalla/valhalla/pull/2963)
   * FIXED: Reverse and Multimodal Isochrones were returning forward results [#2967](https://github.com/valhalla/valhalla/pull/2967)
   * FIXED: Map-match fix for first gps-point being exactly equal to street shape-point [#2977](https://github.com/valhalla/valhalla/pull/2977)
   * FIXED: Add missing GEOS:GEOS dep to mjolnir target [#2901](https://github.com/valhalla/valhalla/pull/2901)
   * FIXED: Allow expansion into a region when not_thru_pruning_ is false on 2nd pass [#2978](https://github.com/valhalla/valhalla/pull/2978)
   * FIXED: Fix polygon area calculation: use Shoelace formula [#2927](https://github.com/valhalla/valhalla/pull/2927)
   * FIXED: Isochrone: orient segments/rings acoording to the right-hand rule [#2932](https://github.com/valhalla/valhalla/pull/2932)
   * FIXED: Parsenodes fix: check if index is out-of-bound first [#2984](https://github.com/valhalla/valhalla/pull/2984)
   * FIXED: Isochrone: handle origin edges properly [#2990](https://github.com/valhalla/valhalla/pull/2990)
   * FIXED: Annotations fail with returning NaN speed when the same point is duplicated in route geometry [#2992](https://github.com/valhalla/valhalla/pull/2992)
   * ADDED: nit: Links debug build with lld [#2813](https://github.com/valhalla/valhalla/pull/2813)
   * ADDED: Add costing option `use_living_streets` to avoid or favor living streets in route. [#2788](https://github.com/valhalla/valhalla/pull/2788)
   * CHANGED: Do not allocate mapped_cache vector in skadi when no elevation source is provided. [#2841](https://github.com/valhalla/valhalla/pull/2841)
   * ADDED: avoid_polygons logic [#2750](https://github.com/valhalla/valhalla/pull/2750)
   * ADDED: Added sac_scale to trace_attributes output and locate edge output [#2818](https://github.com/valhalla/valhalla/pull/2818)
   *    * ADDED: Add min_level argument to valhalla_ways_to_edges [#2918](https://github.com/valhalla/valhalla/pull/2918)
   * ADDED: Adding ability to store the roundabout_exit_turn_degree to the maneuver [#2941](https://github.com/valhalla/valhalla/pull/2941)
   * ADDED: Penalize pencil point uturns and uturns at short internal edges. Note: `motorcycle` and `motor_scooter` models do not penalize on short internal edges. No new uturn penalty logic has been added to the pedestrian and bicycle costing models. [#2944](https://github.com/valhalla/valhalla/pull/2944)
   * CHANGED: Allow config object to be passed-in to path algorithms [#2949](https://github.com/valhalla/valhalla/pull/2949)
   * CHANGED: Allow disabling Werror
   * ADDED: Add ability to build Valhalla modules as STATIC libraries. [#2957](https://github.com/valhalla/valhalla/pull/2957)
   * NIT: Enables compiler warnings in part of mjolnir module [#2922](https://github.com/valhalla/valhalla/pull/2922)
   * CHANGED: Refactor isochrone/reachability forward/reverse search to reduce code repetition [#2969](https://github.com/valhalla/valhalla/pull/2969)
   * ADDED: Set the roundabout exit shape index when we are collapsing the roundabout maneuvers. [#2975](https://github.com/valhalla/valhalla/pull/2975)
   * CHANGED: Penalized closed edges if using them at start/end locations [#2964](https://github.com/valhalla/valhalla/pull/2964)
   * ADDED: Add shoulder to trace_attributes output. [#2980](https://github.com/valhalla/valhalla/pull/2980)
   * CHANGED: Refactor bidirectional astar forward/reverse search to reduce code repetition [#2970](https://github.com/valhalla/valhalla/pull/2970)
   * CHANGED: Factor for service roads is 1.0 by default. [#2988](https://github.com/valhalla/valhalla/pull/2988)
   * ADDED: Support for conditionally skipping CI runs [#2986](https://github.com/valhalla/valhalla/pull/2986)
   * ADDED: Add instructions for building valhalla on `arm64` macbook [#2997](https://github.com/valhalla/valhalla/pull/2997)

I have seen other performance drops over the last year, but this is the most dramatic. All in all, performance has dropped by **nearly 50%** since last March:
 3-3-2020 Valhalla master: 770 ms
4/16/2021 Valhalla master: 1128ms

(there was a data change since that time - some of that difference is due to a larger data set).

**Comment by PureW** [comment]
I think this highlights that we don't have any documented systematic way of measuring this performance that we can apply on each PR modifying the sensitive code.

**Comment by dnesbitt61** [comment]
I checked out commits over the last month and found that the performance drop occurred with commit:

commit 8de759edc0bbe6469eac37ddbbcd8e0c91ff84ff (HEAD)
Author: Mandeep Sandhu <mandeep.sandhu@mapbox.com>
Date:   Thu Mar 18 13:42:49 2021 -0400

    Allow config object to be passed-in to path algorithms (#2949)
    
    This allows us to pass additional configuration values into path
    algorithm classes without changing the signature of the constructor
    each time.

The prior commit has a benchmark time of 984ms and with this commit I got a benchmark time of 1151ms. Throughout my tests the number of EdgeLabels in bidirectional did not change (logged in FormPath) - they have not changed in the past month meaning that the performance drop is not due to a change in "iterations" of the path expansion.

**Comment by dnesbitt61** [comment]
This is somewhat a false alarm. The issue is that the default number of reserved edge labels was changed (lowered) and the long route I have causes some reallocation. The other problem I noted is that the PR referenced above did not change to pass in the thor config to PathAlgorithm constructors when used in valhalla_run_route. I'll open a quick PR to add that.
