### ISSUE TITLE
Fix spatialite support for Windows

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3010]
Currently it's not possible to build tiles with admin & timezone support because spatialite is not correctly set up for some reason. So tiles built on Windows can't 
- use time-dependent routing
- driving side will be off
- no border-crossing penalties

(maybe not an exhaustive list of disadvantages..)

**Comment by Arkadipta-Chatterjee** [comment]
Can i work on this?

**Comment by nilsnolde** [comment]
oh yes please, that'd be great! unfortunately we can't give you a lot of guidance here, the vast majority of people here never touches windows. but I can guide you at least to where the relevant code bits are:

1. valhalla has the ability to build admin (containing mostly country polygons and some related metadata like right/left handed traffic etc) & timezone sqlite db's, where only the former is built using c++, timezones are built using a bash script. it's not strictly necessary to be able to build admins from windows, but it'd be nice to also solve that:
this is the executable: https://github.com/gis-ops/valhalla/blob/master/src/mjolnir/valhalla_build_admins.cc, which you'd run with `valhalla_build_admins --config <your_valhalla.json> <your_osm_pbf>`, with likely Windows/MSVC not being able to set up this part: https://github.com/gis-ops/valhalla/blob/master/src/mjolnir/adminbuilder.cc#L261
2. once the admin db is built, valhalla will use while building the routing graph to enhance the node information and here it's essential to make it work on windows. this is the approximate flow:
    - `valhalla_build_tiles` is the executable which builds the graph
    - it calls a function which will execute several build stages consecutively: https://github.com/gis-ops/valhalla/blob/master/src/mjolnir/util.cc#L167
    - that function has 2 stages where the sqlite dbs will be opened:
    https://github.com/gis-ops/valhalla/blob/master/src/mjolnir/graphbuilder.cc#L400 (first usage building tiles)
    https://github.com/gis-ops/valhalla/blob/master/src/mjolnir/graphenhancer.cc#L1245 (second usage enhancing already built tiles)

so in the end it's mostly necessary to figure out how to open the spatialite dbs in this function: https://github.com/gis-ops/valhalla/blob/master/src/mjolnir/admin.cc#L14

how to set up your windows environment is in the [readme](https://github.com/valhalla/valhalla#building-from-source---windows) and/or in [CI](https://github.com/valhalla/valhalla/blob/master/.azure-pipelines.yml).

let us know if smth is unclear!
