### ISSUE TITLE
Statistically Improving Default Speed Assignments

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3021]
# Whats the problem?

There are two fairly important considerations when building a routing engine. Path selection and estimated time of arrival for traveling that path. This issue is focused on the latter though in reality they are not independent problems.

If you take Valhalla, build a routing tileset from the OSM planet and run routes on that resulting tileset then you will notice an important deficiency. Currently, routing in certain locales is pretty inaccurate when it comes to the estimated time the route is going to take. I would say that it's especially deficient in urban and heavily trafficked locales. Basically the ETAs we provide out of the box are more akin to driving at night with no one else on the roads. This is unfortunate for 2 reasons.

1. Most people are driving during the day
2. Most people are concentrated in more heavily populated areas

Both of these mean that its statistically more likely that we'll get the kind of routing request that fairs poorly with our current default ETA (which does well at night or in rural areas with less road congestion).

# Why does this happen?

OSM is an amazing dataset without which Valhalla wouldn't exist (let alone countless other companies or divisions of companies). For the purposes of display and basic routing, the dataset has amazing value. But there are some problems. Mainly, we have to make some assumptions about the speed a motorvehicle will travel on a given edge in the graph. We use a few factors to make this assumption:

1. Road class (FRC from the highway tag)
2. Road use (FoW from various tags, roundabout, *_link, turn channel, driveway, track, ...)
2. Road density (urban vs rural)
3. Speed limit (if available)

The general flow of how a default speed gets assigned is:

1. `graph.lua` assigns a default speed to the way via the highway tag (FRC). for some special cases of low class road uses  (driveways and tracks) it sets even lower speeds
2. `mjolnir::PBFGraphParser` checks for other speed tags like speed limit, assumed speed, truck speed etc and stores those on the way as well
3. `mjolnir::GraphBuilder` builds the initial set of tiles and when it does so it sets the initial speed for an edge in the graph. in this case it prefers to use any tagged speed over the default speed we computed in graph.lua
4. `mjolnir::GraphEnhancer` then determines the road density around a given edge and uses this and other derived uses (turn channel etc) to further modify speed assigned to the edge (basically to reduce the speeds of urban edges and turn channels).

# What can we do about it?

## Make it configurable

What most people do about it is they ingest historical or live traffic data with a high enough prevalence that it outweighs the inaccuracies of the default speed assignments. I'd like to propose a different route (pun intended). I'd like to modify the graph enhancer to support 2 modes of operation:

**Normal Mode**: Work exactly as it does today by default. Changes to default speed are significant so its best not to rock anyone's boats by upending those if they don't opt into it.

**Configuration Mode**: Add a configuration option under the mjolnir section (blank by default, ie disabled) that points to another json file with detailed speed information. 

The speed information for configuration mode would take the following form:

```json
{
  "urban": {
    "classes": [
      {
        "ramp/tc": 30,
        "roundabout": 25,
        "none": 40
      }...
    ]
  },
  "rural": {
    "classes": [
      {
        "ramp/tc": 30,
        "roundabout": 25,
        "none": 40
      }...
    ]
  },
  "us": {
    "urban": {
      "classes": [
        {
          "ramp/tc": 30,
          "roundabout": 25,
          "none": 40
        }...
      ]
    },
    "rural": {
      "classes": [
        {
          "ramp/tc": 30,
          "roundabout": 25,
          "none": 40
        }...
      ]
    },
    "pa": {
      "urban": {
        "classes": [
          {
            "ramp/tc": 30,
            "roundabout": 25,
            "none": 40
          }...
        ]
      },
      "rural": {
        "classes": [
          {
            "ramp/tc": 30,
            "roundabout": 25,
            "none": 40
          }...
        ]
      }
    }
  }
}
```

This information is hierarchical but the basic premise is, given the characteristics of an edge that you have, use the closest match to those to set the speed. You'll notice locale information, urban/rural classification, FRC (class), FoW (use) and other attributes. Locale will serve as the basic hierarchical unit. If a local is missing you can pop up to a coarser locale to get the relevant information. We may even use speeds for other attributes where they are missing in our configuration.

## Gather some statistics

Once the configuration mode is fully supported we need to get some speeds from some where. For that we'll need to actually measure real drives to get some mean or median speeds for the given types of roads in the given locales.

The best way to do this is take a large corpus of GPS traces and use map matching to associate them to the graph. We'll want to do some filtering of the traces by time and by locations but also by looking at timestamps and speeds and noisiness so that we don't falsely color our metrics. An important one is doing mode detection (meaning we want to filter bike and walking traces and favor motor vehicle traces) which I think we can do by filtering traces that are continuously traveling at low speeds. We'll need to tweak this a bit for sure to find whats best. Once we have the set of GPS traces that we want to actually use, we can match them to the graph using the trace_attributes endpoint to get metadata information about each edge in the match including the attributes that we will break down our statistics by in the json format above but also, most importantly, the timing (and therefore the speed) on each edge.

So then the question becomes what corpus should we use. I first looked at https://www.openstreetmap.org/traces which is quite large, but the APIs to access those traces are also quite lacking. There were bulk dumps of global traces from about 9 years ago, which would suite our needs but frankly they are too old.

In thinking a bit more I released that another great source would be Mapillary. They have an open API (https://www.mapillary.com/developer/api-documentation/#sequences) that allows you to fetch traces and images for the purposes of improving OSM. The great news is that their API allows date ranges as well as geographic ranges so we can do small tests in different places and then scale up when we are ready to run the whole thing or slowly roll through it to keep the load low etc. In the end its a one time process every so often. Maybe we can even get their support?

The process should be basically a python script that interacts with the Mapillary API as well as our map matching API to map speeds to types of edges in different locales. At the very end of the process, after we've gathered our observations we can take the mean/median of those and create a json config file to be used as described above. Once we've completed a run for the planet the resulting json file can be committed back to this repository and also we can make an osm wiki page with these values (akin to other locale specific tagging suggestions and rules).

@ptpt @gyllen what do you guys think about this idea?

# Conclusion

This process should result in an artifact which we can publish to the OSM wiki and this repository which should allow other projects etc to improve OSM-based motor vehicle routing. I do not expect it to compete with actual traffic products from entrenched vendors since the amount of data coverage they have and the models they use apply at the individual edge level and are thus way more accurate. Here we are just trying to bring up the baseline a little bit so that ETAs and selected routes aren't off by 50%.

**Comment by danpat** [comment]
Some references to previous work along these lines that's helpful context:  https://wiki.openstreetmap.org/wiki/Global_Statistical_Speed_Matrix

https://wiki.openstreetmap.org/wiki/Average_speed_per_way

https://wiki.openstreetmap.org/wiki/Proposed_features/Practical_maxspeed

**Comment by PureW** [comment]
I like it. It sounds like breaking out the current parameters defined in code in various places into a standalone artifact that can be independent of the actual routing engine. This artifact can then more systematically be tested and updated over various geographical regions and roads.

**Comment by kevinkreiser** [comment]
@PureW thats exactly right! Actually your comment brings another idea to my mind. We could actually use this lookup map at runtime instead of changing what is baked into the tiles... There are complications there because some of the attribution needed is on the `NodeInfo`s rather than the `DirectedEdge`s, and that we make shortcuts which need to have some reduction in speed for nodes they pass through (though we could store that elsewhere)... Anyway I'll let this idea for a second revision or future work, but wouldn't it be cool if we could one day refactor default speed to just be speed limit for example or reclaim the bits for default speed entirely and use them for something else?

**Comment by jcoupey** [comment]
Very interesting idea! Please allow me to chime in from an outsider (read not a Valhalla dev or user) perspective.

As previously mentioned, this would be useful for any routing engine so this has the potential to gather contributions outside the Valhalla scope. Furthermore, there are a couple things that may improve the overall efficiency/adoption of such an approach.

1. Allowing for other data sources on top of Mapillary, think specific (non-car) profiles or new collaborative datasets.
2. Making it possible to plugin other map-matching algorithms from other routing engines or dedicated map-matching projects.
3. Further improving the classification by including other data sources that are outside the scope of what a routing engine usually ingests. This may include data from OSM (e.g. building density around an edge) or from other sources (e.g surrounding population density).

Because of these, I feel this may be worth exploring the option of doing this work outside the routing engine itself. What do you think of having the whole process live in a dedicated repo (organization?), define some kind of standard there, and let routing engines adjust internally if they want to ingest the resulting datasets as downstream consumers?

I can only speak for myself, but I think it would not be that easy to contribute to (and use) this process if the implementation is strongly coupled with the Valhalla internals.

**Comment by kevinkreiser** [comment]
@jcoupey something generic and plugin-able sounds good to me. Basically writing adapters for the different data sources and map matching apis. my biggest worry is slowing down momentum. i'd like to get started on this right away, which means id like to start throwing up some python that implements this functionality immediately and has adapters for mapillary and valhalla (since i know those). i dont think thats a problem, so long as i would design it in such a way as to allow others to be swapped in via command line options or configuration.

having a separate github organization doesnt sound like a bad idea to me. do you have a name in mind? i could start one and add interested parties to it? or should i start something here and then promote it to its own org once its off the ground? or maybe the most sensible thing to do would be to ask for a new repository in the openstreetmap github org (@zerebubuth thoughts?). any opinions on these subjects are welcome!

regarding the tight coupling i totally understand that, i think the m ost important thing to do there would be to remove any valhalla specific jargon/derivations from the output format. for example we could just use the osm highway tag to start for differentiation of speeds but i do think having some notion of road density is important when comparing two ways with the same tag but in different regions (urban vs rural).

**Comment by gknisely** [comment]
I have always wanted to implement this, but at a per country level.  Of course fall back to some defaults if we did not have that information.  Take a look at [Implicit maxspeed values](https://wiki.openstreetmap.org/wiki/Key:maxspeed)  So basically was thinking we could implement it like we currently do for the country specific access overrides.

Also, we need to handle defaults for [motorroads](https://wiki.openstreetmap.org/wiki/Key:motorroad) at a per country level.

**Comment by jcoupey** [comment]
@kevinkreiser thanks for considering setting up a dedicated repo, I think it's a good way toward getting more people involved. Having this under the openstreetmap namespace does sound relevant, though I have no strong opinion (and no fancy name in mind for now either). The good part is that it may allow you to get started right away. Onboarding new contributors will probably also be easier after some prototyping work.

**Comment by TimMcCauley** [comment]
There is this pretty impressive logic built by @frodrigo for OSRM which handles speeds by utilizing corine land cover data https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/18/urban-density

**Comment by roadrouting** [comment]
Very much welcome these improvements!

@morganherlocker's approach in https://github.com/sharedstreets/speed-prediction for OSRM has some interesting ideas that may make applying the same technique in geographies with limited traces potentially viable.

**Comment by ImreSamu** [comment]
> The best way to do this is take a large corpus of GPS traces and use map matching to associate them to the graph. 

IMHO: Is it possible to add some extra output?
* _"missing roads, misdirected turn restrictions or misdirected one-way streets"_

related - Lyft research / presentation : 
* https://arxiv.org/abs/1809.09755  _"Map matching when the map is wrong: Efficient vehicle tracking on- and off-road for map learning"_
* https://2019.stateofthemap.us/program/sun/how-map-matching-failures-can-be-used-for-map-making.html ( video )
* https://2018.stateofthemap.us/program/map-matching-when-the-map-is-wrong.html ( video )

Thinking big:
* local transportation companies - can easily install and run with docker
  * continuously processing fresh private GPS traces - with the latest OSM data
  * it can be a high ROI - [Corporate social responsibility (CSR)](https://en.wikipedia.org/wiki/Corporate_social_responsibility) program for them.
* sharing only:
      * the potential OSM road networks problem
      * the calculated "speed assignments" for a vehicle ( bicycle, car, truck/lorry, wheelchair, ...  )
* uploading to   ~  global OSM road aggregation site .. ( mixing multiple company data is adding higher privacy )
* creating daily/weekly collections 
   * road networks problem --> OpenStreetMap community ( JOSM layer / ... )
   * calculated "speed assignments" --> routing engines

**Comment by frodrigo** [comment]
It is interesting. Open traffic data would be a valuable data.
Could see, https://github.com/opentraffic, based on Valhalla.

**Comment by kevinkreiser** [comment]
@frodrigo ironically it was based on valhalla (we wrote the code for it) but the original sponsor is no longer operating the project so far as I know

**Comment by ptpt** [comment]
I like the idea! Just put some comments of using Mapillary APIs here.

- Instead of the documented sequence API `/v3/sequences` you can use `/v3/sequences_without_images` which will be faster because it doesn't return the uneeded `coordinateProperties`.
- The returned sequences doesn't have capture time for each point so you need to call `/v3/images?sequence_keys=key1,key2,key3` that fetches the sequence images which ctontains `captured_at`.
- For correct daily traffic aggregation, you might have to convert the image's `captured_at` (UTC time) to local time by its location.
- Note that by default each API call returns limited features (specified by `per_page`). To fetch more, use the pagination https://www.mapillary.com/developer/api-documentation/#pagination. Check this script https://gist.github.com/ptpt/b106fee8253b4c78c148e7a57192f159

**Comment by kevinkreiser** [comment]
just FYI i started a new org and repo where @rzyc and I will be dropping the first implementation of this. we'll take care to make the input source and the map matching api pluggable so that others can add implementations for their favorite sources.

the repo can be found here: https://github.com/OpenStreetMapSpeeds/conflation

**Comment by rzyc** [comment]
@ptpt Hey! We've started an implementation of this using the Mapillary `/v3/sequences_without_images` API as you suggested. Our intention is to eventually run our script once on the entire planet, i.e. pulling image data on most of the sequences that exist.

I wanted to get your opinion on if / how we should rate limit calls to the Mapillary API. Is there some specific QPS that we should stay under when we do our run, or do you have any tips on how we can optimize these calls to `/v3/sequences_without_images` and `/v3/images`? Feel free to DM me to @kevinkreiser directly as well. Thanks in advance!

**Comment by kevinkreiser** [comment]
just pinging back that we have a schema and some hand tuned values available for a few countries: https://github.com/OpenStreetMapSpeeds/schema/blob/master/default_speeds.json

**Comment by nilsnolde** [comment]
this landed no @kevinkreiser ?

**Comment by kevinkreiser** [comment]
yep it was completed mostly with #3055 and #3621

**Comment by void-rooster** [comment]
I'm working on an issue that requires knowing how valhalla comes up with its travel time estimates. Came across this discussion. Is there a way to get the speeds on the edges that valhalla uses for its travel time estimates? from what I've seen of our `trace_attributes` output, many speeds are missing, which is unexpected because I'm working in data-rich areas.

**Comment by kevinkreiser** [comment]
if you use osrm output and ask for shape attributes you can get per shape segment speed. there is a unit test for this called shape attributes iitc that has sample requests you can have a look at.

**Comment by void-rooster** [comment]
hm we do grab speeds from `trace_attributes`. I'm going to investigate our data quality and maybe get back to you.
