### ISSUE TITLE
Shape not matching route

### ISSUE THREAD

**Issue by kochis** [valhalla/valhalla#3033]
Hi there,

There's a good chance I'm doing something incorrect with the shape polyline -> geojson conversion, but for almost all of the routes I've tested, the shape seems to be wildly off (the directions however, seem correct).

Here's an example route:
```
http://localhost:8002/route?json={"locations": [{ "lat": 40.7043497, "lon": -73.986763}, { "lat": 40.5758196, "lon": -73.9789913 }], "costing": "auto"}
```
Response: https://gist.github.com/kochis/b8c32c3c397c653e4c0fee537cc98fa2

And here's the shape plotted on the map, using the conversion found here: https://blocks.roadtolarissa.com/wboykinm/2eb37319ee5a08741550

![image](https://user-images.githubusercontent.com/814934/115994379-b7b14600-a5a4-11eb-9cb5-5dbdae7fcf20.png)
Shape Data: https://gist.github.com/kochis/75f58a5d9696cd78f474985cc84bc2db

Again, this might be me missing something in the documentation, but a couple of questions are:
* Is the `shape` supposed to be a visual representation of the trip? (ie. is it assumed to be plotted on a map)
* Could this be something getting due to the conversion? 
* The shapes do seem _mostly_ correct, it seems like they usually get thrown off at some point on the route (could my data be bad?)

Happy to provide more details / examples if needed. Thanks!

**Comment by ImreSamu** [comment]
check this code: https://valhalla.readthedocs.io/en/latest/decoding/

**Comment by ImreSamu** [comment]
testing the demo decoder: http://valhalla.github.io/demos/polyline

### with "Unescape '\':"   look OK
![image](https://user-images.githubusercontent.com/2217320/115994888-2e683680-a5d9-11eb-91ba-67e53ed07591.png)

### without "Unescape '\':"  .. the same result - as in your example.
![image](https://user-images.githubusercontent.com/2217320/115994928-4d66c880-a5d9-11eb-9b9a-d5be689f0f08.png)

**Comment by kochis** [comment]
Ahh yeah, that'll do it. Thanks!
