### ISSUE TITLE
Error while building on Mac arm64

### ISSUE THREAD

**Issue by safe-bug** [valhalla/valhalla#3034]
Hello

I'm trying to build valhalla on Mac arm64 according to the instructions in the Readme for arm64, but when I try to make Valhalla it returns this error, although I installed boost-python3 with ibrew. What is the problem?

libboost_program_options-mt.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

**Comment by nilsnolde** [comment]
I realized that boost-python3 somehow requires program_options the other day too, no idea why.. could bee a packaging bug..

You don't need it though, boost-python has been deprecated a longer time ago. Try to install simply `boost`, I think that might be better maintained.

**Comment by kevinkreiser** [comment]
We need program_options anyway though because a lot of our binaries use it. Seems like you've somehow installed the x86 version rather than the arm version. maybe the arm version is in a different path that you need to specify to the linker (LD_LIBRARY_PATH or with some compiler flags?)

**Comment by safe-bug** [comment]
@nilsnolde @kevinkreiser Thanks for your replies. The problem was that it was looking in the arm boost folder instead of x86 boost (that I installed it using ibrew)
