### ISSUE TITLE
Update homebrew to avoid downloads from bintray (which is shutting down)

### ISSUE THREAD

**Issue by mandeepsandhu** [valhalla/valhalla#3036]
[bintray is shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). `homebrew` has already [moved off of it](https://brew.sh/2021/04/12/homebrew-3.1.0/).

However, our osx executor is using an older version, which is causing failures of osx builds.

We should update homebrew before using it and also upgrade to the [newest xcode](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions) version available from circle.

**Comment by kevinkreiser** [comment]
well it looks like i spoke too soon! the other day macos builds started working again so i re-enabled them as mandatory but now they are failing again.

**Comment by mandeepsandhu** [comment]
> well it looks like i spoke too soon! the other day macos builds started working again so i re-enabled them as mandatory but now they are failing again.

IS it failing on building prime_server? Thats the last error I saw (I expected the updated version to fail still, since we haven't really fixed the prime_server build issue yet)

**Comment by kevinkreiser** [comment]
@mandeepsandhu nope now its failing to pull boost, at least that was the last one i saw

**Comment by mandeepsandhu** [comment]
> @mandeepsandhu nope now its failing to pull boost, at least that was the last one i saw

do you have the link to the failed run? wonder if its still pulling from bintray.

**Comment by mandeepsandhu** [comment]
CCI's update on the xcode + homebrew has gone back-n-forth a few times now https://discuss.circleci.com/t/macos-image-users-homebrew-brownout-2021-04-26/39872/3. No wonder we're seeing inconsistent results. But from the last update, it looks like they've finally settled on updating Xcode + homebrew.
