### ISSUE TITLE
Invalid token Mapbox

### ISSUE THREAD

**Issue by raul-parada** [valhalla/valhalla#3049]
Hi,

I'm requesting to mapbox where previously I've create a token. I've tried the public and a personal one. I've also added the URLs:

```
https://api.mapbox.com/valhalla/v1/route/
https://api.mapbox.com/valhalla/v1/trace_attributes
```

This is my URL.

`url="https://api.mapbox.com/valhalla/v1/<route/trace_attributes/..>?access_token=token3"
`
however, I get:

```
{'message': 'Not Authorized - Invalid Token'}
dict_keys(['message'])

```
I'm using Jupyter Notebook.

**Comment by nilsnolde** [comment]
Actually valhalla != mapbox, so this "issue" doesn't really fit here tbh. But anyways, if python doesn't work, I recommend trying other ways before giving up, e.g. this works for me:

```
curl --location --request POST 'https://api.mapbox.com/valhalla/v1/route?access_token=your_token' --header 'Content-Type: application/json' --data-raw '{
    "locations": [
        {
            "lat": 42.546504,
            "lon": 1.591129
        },
        {
            "lat": 42.507667,
            "lon": 1.542721
        }
    ],
    "costing": "auto"
}'
```

Try Postman for requests, helps a lot.
