### ISSUE TITLE
Error while "sudo add-apt-repository -y ppa:valhalla-core/valhalla"

### ISSUE THREAD

**Issue by cjcjcj7777** [valhalla/valhalla#3069]
when I run the command -> sudo add-apt-repository -y ppa:valhalla-core/valhalla
I am using Ubuntu 20.04
it shows the following error-

Err:27 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:28 http://ppa.launchpad.net/kevinkreiser/czmq/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:29 http://ppa.launchpad.net/kevinkreiser/libpgm/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:30 http://ppa.launchpad.net/kevinkreiser/libsodium/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:31 http://ppa.launchpad.net/kevinkreiser/zeromq3/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]

**Comment by ImreSamu** [comment]
what is your system?:
* 32 vs 64 bit?
* ARM or X86?

What is your 
* `uname -i` 
* `dpkg --print-architecture`

```
root@2f98cf8bda4e:/#  uname -i
x86_64
root@2f98cf8bda4e:/# dpkg --print-architecture 
amd64
```

my quick test ( on X86_64 / amd64 )

```
root@2f98cf8bda4e:/# add-apt-repository ppa:valhalla-core/valhalla
 Library, development headers and executables associated with the Valhalla open source routing project: github.com/valhalla
 More info: https://launchpad.net/~valhalla-core/+archive/ubuntu/valhalla
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu focal InRelease [18.1 kB]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease   
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:6 http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu focal/main amd64 Packages [1515 B]
Fetched 19.6 kB in 1s (26.7 kB/s) 
Reading package lists... Done
```
