### ISSUE TITLE
error while running command - "valhalla_service valhalla.json 1"

### ISSUE THREAD

**Issue by cjcjcj7777** [valhalla/valhalla#3070]
I have build the valhalla package and followed all the steps. But when i run the server i.e., 
> valhalla_service valhalla.json 1

there is an error - valhalla_service: command not found
I am using ubuntu 20.04

**Comment by mandeepsandhu** [comment]
If you have run the install step (`make install`) then make sure that your `PATH` environment variable has the path to the install location.

Otherwise you can run `valhalla_service` (assuming you've built it) directly from the build dir:
```shell
./valhalla_service valhalla.json 1
```

**Comment by cjcjcj7777** [comment]
> If you have run the install step (`make install`) then make sure that your `PATH` environment variable has the path to the install location.
> 
> Otherwise you can run `valhalla_service` (assuming you've built it) directly from the build dir:
> 
> ```shell
> ./valhalla_service valhalla.json 1
> ```

when I run 
> sudo make install 
i get the following result 
>[  4%] Built target valhalla-midgard
[ 13%] Built target valhalla-proto
[ 33%] Built target valhalla-baldr
[ 48%] Built target valhalla-mjolnir
[ 49%] Built target valhalla-skadi
[ 54%] Built target valhalla-sif
[ 60%] Built target valhalla-loki
[ 64%] Built target valhalla-meili
[ 69%] Built target valhalla-odin
[ 79%] Built target valhalla-thor
[ 83%] Built target valhalla-tyr
[ 85%] Built target valhalla
[ 86%] Built target valhalla_thor_worker
[ 87%] Built target valhalla_odin_worker
[ 89%] Built target valhalla_build_statistics
[ 90%] Built target valhalla_validate_transit
[ 91%] Built target valhalla_fetch_transit
[ 91%] Built target valhalla_loki_worker
[ 91%] Built target valhalla_build_connectivity
[ 92%] Built target valhalla_benchmark_admins
[ 93%] Built target valhalla_add_predicted_traffic
[ 94%] Built target valhalla_build_tiles
[ 95%] Built target valhalla_build_admins
[ 96%] Built target valhalla_convert_transit
[ 97%] Built target valhalla_query_transit
[ 98%] Built target valhalla_ways_to_edges
[ 99%] Built target valhalla_assign_speeds
[ 99%] Built target libvalhalla.so
[100%] Built target python_valhalla
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/share/doc/python-valhalla/COPYING
-- Up-to-date: /usr/share/doc/python-valhalla/CHANGELOG.md
-- Up-to-date: /usr/bin/valhalla_build_statistics
-- Up-to-date: /usr/bin/valhalla_ways_to_edges
-- Up-to-date: /usr/bin/valhalla_validate_transit
-- Up-to-date: /usr/bin/valhalla_benchmark_admins
-- Up-to-date: /usr/bin/valhalla_build_connectivity
-- Up-to-date: /usr/bin/valhalla_build_tiles
-- Up-to-date: /usr/bin/valhalla_build_admins
-- Up-to-date: /usr/bin/valhalla_convert_transit
-- Up-to-date: /usr/bin/valhalla_fetch_transit
-- Up-to-date: /usr/bin/valhalla_query_transit
-- Up-to-date: /usr/bin/valhalla_add_predicted_traffic
-- Up-to-date: /usr/bin/valhalla_assign_speeds
-- Up-to-date: /usr/bin/valhalla_loki_worker
-- Up-to-date: /usr/bin/valhalla_odin_worker
-- Up-to-date: /usr/bin/valhalla_thor_worker
-- Up-to-date: /usr/bin/valhalla_build_config
-- Up-to-date: /usr/bin/valhalla_build_elevation
-- Up-to-date: /usr/bin/valhalla_build_transit
-- Up-to-date: /usr/bin/valhalla_build_timezones
-- Up-to-date: /usr/share/doc/valhalla/COPYING
-- Up-to-date: /usr/share/doc/valhalla/CHANGELOG.md
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libvalhalla.a
-- Up-to-date: /usr/share/doc/libvalhalla-dev/COPYING
-- Up-to-date: /usr/share/doc/libvalhalla-dev/CHANGELOG.md
-- Up-to-date: /usr/share/doc/libvalhalla-dev/README.md
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libvalhalla.so
-- Up-to-date: /usr/include/valhalla/valhalla.h
-- Up-to-date: /usr/include/valhalla/worker.h
-- Up-to-date: /usr/include/valhalla/filesystem.h
-- Up-to-date: /usr/include/valhalla/proto_conversions.h
-- Up-to-date: /usr/include/valhalla/tile_server.h
-- Up-to-date: /usr/lib/x86_64-linux-gnu/pkgconfig/libvalhalla.pc
-- Up-to-date: /usr/include/valhalla/proto/api.pb.h
-- Up-to-date: /usr/include/valhalla/proto/directions.pb.h
-- Up-to-date: /usr/include/valhalla/proto/info.pb.h
-- Up-to-date: /usr/include/valhalla/proto/options.pb.h
-- Up-to-date: /usr/include/valhalla/proto/tripcommon.pb.h
-- Up-to-date: /usr/include/valhalla/proto/trip.pb.h
-- Up-to-date: /usr/include/valhalla/proto/transit.pb.h
-- Up-to-date: /usr/include/valhalla/proto/transit_fetch.pb.h
-- Up-to-date: /usr/include/valhalla/proto/incidents.pb.h
-- Up-to-date: /usr/include/valhalla/proto/fileformat.pb.h
-- Up-to-date: /usr/include/valhalla/proto/osmformat.pb.h
-- Up-to-date: /usr/include/valhalla/baldr/accessrestriction.h
-- Up-to-date: /usr/include/valhalla/baldr/admin.h
-- Up-to-date: /usr/include/valhalla/baldr/admininfo.h
-- Up-to-date: /usr/include/valhalla/baldr/complexrestriction.h
-- Up-to-date: /usr/include/valhalla/baldr/compression_utils.h
-- Up-to-date: /usr/include/valhalla/baldr/connectivity_map.h
-- Up-to-date: /usr/include/valhalla/baldr/curl_tilegetter.h
-- Up-to-date: /usr/include/valhalla/baldr/curler.h
-- Up-to-date: /usr/include/valhalla/baldr/datetime.h
-- Up-to-date: /usr/include/valhalla/baldr/directededge.h
-- Up-to-date: /usr/include/valhalla/baldr/double_bucket_queue.h
-- Up-to-date: /usr/include/valhalla/baldr/edgeinfo.h
-- Up-to-date: /usr/include/valhalla/baldr/edgetracker.h
-- Up-to-date: /usr/include/valhalla/baldr/graphconstants.h
-- Up-to-date: /usr/include/valhalla/baldr/graphid.h
-- Up-to-date: /usr/include/valhalla/baldr/graphmemory.h
-- Up-to-date: /usr/include/valhalla/baldr/graphreader.h
-- Up-to-date: /usr/include/valhalla/baldr/graphtile.h
-- Up-to-date: /usr/include/valhalla/baldr/graphtileheader.h
-- Up-to-date: /usr/include/valhalla/baldr/graphtileptr.h
-- Up-to-date: /usr/include/valhalla/baldr/json.h
-- Up-to-date: /usr/include/valhalla/baldr/laneconnectivity.h
-- Up-to-date: /usr/include/valhalla/baldr/location.h
-- Up-to-date: /usr/include/valhalla/baldr/merge.h
-- Up-to-date: /usr/include/valhalla/baldr/nodeinfo.h
-- Up-to-date: /usr/include/valhalla/baldr/nodetransition.h
-- Up-to-date: /usr/include/valhalla/baldr/openlr.h
-- Up-to-date: /usr/include/valhalla/baldr/pathlocation.h
-- Up-to-date: /usr/include/valhalla/baldr/predictedspeeds.h
-- Up-to-date: /usr/include/valhalla/baldr/rapidjson_utils.h
-- Up-to-date: /usr/include/valhalla/baldr/sign.h
-- Up-to-date: /usr/include/valhalla/baldr/signinfo.h
-- Up-to-date: /usr/include/valhalla/baldr/streetname.h
-- Up-to-date: /usr/include/valhalla/baldr/streetname_us.h
-- Up-to-date: /usr/include/valhalla/baldr/streetnames.h
-- Up-to-date: /usr/include/valhalla/baldr/streetnames_factory.h
-- Up-to-date: /usr/include/valhalla/baldr/streetnames_us.h
-- Up-to-date: /usr/include/valhalla/baldr/tilegetter.h
-- Up-to-date: /usr/include/valhalla/baldr/tilehierarchy.h
-- Up-to-date: /usr/include/valhalla/baldr/time_info.h
-- Up-to-date: /usr/include/valhalla/baldr/timedomain.h
-- Up-to-date: /usr/include/valhalla/baldr/traffictile.h
-- Up-to-date: /usr/include/valhalla/baldr/transitdeparture.h
-- Up-to-date: /usr/include/valhalla/baldr/transitroute.h
-- Up-to-date: /usr/include/valhalla/baldr/transitschedule.h
-- Up-to-date: /usr/include/valhalla/baldr/transitstop.h
-- Up-to-date: /usr/include/valhalla/baldr/transittransfer.h
-- Up-to-date: /usr/include/valhalla/baldr/turn.h
-- Up-to-date: /usr/include/valhalla/baldr/turnlanes.h
-- Up-to-date: /usr/include/valhalla/baldr/verbal_text_formatter.h
-- Up-to-date: /usr/include/valhalla/baldr/verbal_text_formatter_factory.h
-- Up-to-date: /usr/include/valhalla/baldr/verbal_text_formatter_us.h
-- Up-to-date: /usr/include/valhalla/baldr/verbal_text_formatter_us_co.h
-- Up-to-date: /usr/include/valhalla/baldr/verbal_text_formatter_us_tx.h
-- Up-to-date: /usr/include/valhalla/loki/node_search.h
-- Up-to-date: /usr/include/valhalla/loki/polygon_search.h
-- Up-to-date: /usr/include/valhalla/loki/reach.h
-- Up-to-date: /usr/include/valhalla/loki/search.h
-- Up-to-date: /usr/include/valhalla/loki/worker.h
-- Up-to-date: /usr/include/valhalla/meili/candidate_search.h
-- Up-to-date: /usr/include/valhalla/meili/config.h
-- Up-to-date: /usr/include/valhalla/meili/emission_cost_model.h
-- Up-to-date: /usr/include/valhalla/meili/geometry_helpers.h
-- Up-to-date: /usr/include/valhalla/meili/grid_range_query.h
-- Up-to-date: /usr/include/valhalla/meili/grid_traversal.h
-- Up-to-date: /usr/include/valhalla/meili/map_matcher.h
-- Up-to-date: /usr/include/valhalla/meili/map_matcher_factory.h
-- Up-to-date: /usr/include/valhalla/meili/match_result.h
-- Up-to-date: /usr/include/valhalla/meili/measurement.h
-- Up-to-date: /usr/include/valhalla/meili/priority_queue.h
-- Up-to-date: /usr/include/valhalla/meili/routing.h
-- Up-to-date: /usr/include/valhalla/meili/state.h
-- Up-to-date: /usr/include/valhalla/meili/stateid.h
-- Up-to-date: /usr/include/valhalla/meili/topk_search.h
-- Up-to-date: /usr/include/valhalla/meili/traffic_segment_matcher.h
-- Up-to-date: /usr/include/valhalla/meili/transition_cost_model.h
-- Up-to-date: /usr/include/valhalla/meili/viterbi_search.h
-- Up-to-date: /usr/include/valhalla/midgard/aabb2.h
-- Up-to-date: /usr/include/valhalla/midgard/constants.h
-- Up-to-date: /usr/include/valhalla/midgard/distanceapproximator.h
-- Up-to-date: /usr/include/valhalla/midgard/ellipse.h
-- Up-to-date: /usr/include/valhalla/midgard/encoded.h
-- Up-to-date: /usr/include/valhalla/midgard/gridded_data.h
-- Up-to-date: /usr/include/valhalla/midgard/linesegment2.h
-- Up-to-date: /usr/include/valhalla/midgard/logging.h
-- Up-to-date: /usr/include/valhalla/midgard/obb2.h
-- Up-to-date: /usr/include/valhalla/midgard/point2.h
-- Up-to-date: /usr/include/valhalla/midgard/point_tile_index.h
-- Up-to-date: /usr/include/valhalla/midgard/pointll.h
-- Up-to-date: /usr/include/valhalla/midgard/polyline2.h
-- Up-to-date: /usr/include/valhalla/midgard/sequence.h
-- Up-to-date: /usr/include/valhalla/midgard/tiles.h
-- Up-to-date: /usr/include/valhalla/midgard/util.h
-- Up-to-date: /usr/include/valhalla/midgard/util_core.h
-- Up-to-date: /usr/include/valhalla/midgard/vector2.h
-- Up-to-date: /usr/include/valhalla/odin/directionsbuilder.h
-- Up-to-date: /usr/include/valhalla/odin/enhancedtrippath.h
-- Up-to-date: /usr/include/valhalla/odin/maneuver.h
-- Up-to-date: /usr/include/valhalla/odin/maneuversbuilder.h
-- Up-to-date: /usr/include/valhalla/odin/narrative_builder_factory.h
-- Up-to-date: /usr/include/valhalla/odin/narrative_dictionary.h
-- Up-to-date: /usr/include/valhalla/odin/narrativebuilder.h
-- Up-to-date: /usr/include/valhalla/odin/sign.h
-- Up-to-date: /usr/include/valhalla/odin/signs.h
-- Up-to-date: /usr/include/valhalla/odin/transitrouteinfo.h
-- Up-to-date: /usr/include/valhalla/odin/util.h
-- Up-to-date: /usr/include/valhalla/odin/worker.h
-- Up-to-date: /usr/include/valhalla/sif/autocost.h
-- Up-to-date: /usr/include/valhalla/sif/bicyclecost.h
-- Up-to-date: /usr/include/valhalla/sif/costconstants.h
-- Up-to-date: /usr/include/valhalla/sif/costfactory.h
-- Up-to-date: /usr/include/valhalla/sif/dynamiccost.h
-- Up-to-date: /usr/include/valhalla/sif/edgelabel.h
-- Up-to-date: /usr/include/valhalla/sif/hierarchylimits.h
-- Up-to-date: /usr/include/valhalla/sif/motorcyclecost.h
-- Up-to-date: /usr/include/valhalla/sif/motorscootercost.h
-- Up-to-date: /usr/include/valhalla/sif/nocost.h
-- Up-to-date: /usr/include/valhalla/sif/osrm_car_duration.h
-- Up-to-date: /usr/include/valhalla/sif/pedestriancost.h
-- Up-to-date: /usr/include/valhalla/sif/recost.h
-- Up-to-date: /usr/include/valhalla/sif/transitcost.h
-- Up-to-date: /usr/include/valhalla/sif/truckcost.h
-- Up-to-date: /usr/include/valhalla/skadi/sample.h
-- Up-to-date: /usr/include/valhalla/skadi/util.h
-- Up-to-date: /usr/include/valhalla/thor/alternates.h
-- Up-to-date: /usr/include/valhalla/thor/astar_bss.h
-- Up-to-date: /usr/include/valhalla/thor/astarheuristic.h
-- Up-to-date: /usr/include/valhalla/thor/attributes_controller.h
-- Up-to-date: /usr/include/valhalla/thor/bidirectional_astar.h
-- Up-to-date: /usr/include/valhalla/thor/centroid.h
-- Up-to-date: /usr/include/valhalla/thor/costmatrix.h
-- Up-to-date: /usr/include/valhalla/thor/dijkstras.h
-- Up-to-date: /usr/include/valhalla/thor/edgestatus.h
-- Up-to-date: /usr/include/valhalla/thor/isochrone.h
-- Up-to-date: /usr/include/valhalla/thor/map_matcher.h
-- Up-to-date: /usr/include/valhalla/thor/matrix_common.h
-- Up-to-date: /usr/include/valhalla/thor/multimodal.h
-- Up-to-date: /usr/include/valhalla/thor/optimizer.h
-- Up-to-date: /usr/include/valhalla/thor/pathalgorithm.h
-- Up-to-date: /usr/include/valhalla/thor/pathinfo.h
-- Up-to-date: /usr/include/valhalla/thor/route_matcher.h
-- Up-to-date: /usr/include/valhalla/thor/timedistancebssmatrix.h
-- Up-to-date: /usr/include/valhalla/thor/timedistancematrix.h
-- Up-to-date: /usr/include/valhalla/thor/triplegbuilder.h
-- Up-to-date: /usr/include/valhalla/thor/unidirectional_astar.h
-- Up-to-date: /usr/include/valhalla/thor/worker.h
-- Up-to-date: /usr/include/valhalla/tyr/actor.h
-- Up-to-date: /usr/include/valhalla/tyr/serializer_constants.h
-- Up-to-date: /usr/include/valhalla/tyr/serializers.h
-- Up-to-date: /usr/include/valhalla/mjolnir/admin.h
-- Up-to-date: /usr/include/valhalla/mjolnir/adminbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/adminconstants.h
-- Up-to-date: /usr/include/valhalla/mjolnir/bssbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/complexrestrictionbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/countryaccess.h
-- Up-to-date: /usr/include/valhalla/mjolnir/dataquality.h
-- Up-to-date: /usr/include/valhalla/mjolnir/directededgebuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/edgeinfobuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/elevationbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/ferry_connections.h
-- Up-to-date: /usr/include/valhalla/mjolnir/graphbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/graphenhancer.h
-- Up-to-date: /usr/include/valhalla/mjolnir/graphfilter.h
-- Up-to-date: /usr/include/valhalla/mjolnir/graphtilebuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/graphvalidator.h
-- Up-to-date: /usr/include/valhalla/mjolnir/hierarchybuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/linkclassification.h
-- Up-to-date: /usr/include/valhalla/mjolnir/luatagtransform.h
-- Up-to-date: /usr/include/valhalla/mjolnir/node_expander.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmaccess.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmaccessrestriction.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmadmin.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmadmindata.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmdata.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmnode.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmpbfparser.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmrestriction.h
-- Up-to-date: /usr/include/valhalla/mjolnir/osmway.h
-- Up-to-date: /usr/include/valhalla/mjolnir/pbfadminparser.h
-- Up-to-date: /usr/include/valhalla/mjolnir/pbfgraphparser.h
-- Up-to-date: /usr/include/valhalla/mjolnir/restrictionbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/servicedays.h
-- Up-to-date: /usr/include/valhalla/mjolnir/shortcutbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/timeparsing.h
-- Up-to-date: /usr/include/valhalla/mjolnir/transitbuilder.h
-- Up-to-date: /usr/include/valhalla/mjolnir/transitpbf.h
-- Up-to-date: /usr/include/valhalla/mjolnir/uniquenames.h
-- Up-to-date: /usr/include/valhalla/mjolnir/util.h
-- Up-to-date: /usr/include/valhalla/mjolnir/validatetransit.h
-- Up-to-date: /usr/lib/python3/dist-packages/valhalla
-- Up-to-date: /usr/lib/python3/dist-packages/valhalla/__init__.py

here I cannot find valhalla_service build

**Comment by nilsnolde** [comment]
Looks like you didn't build `TOOLS`. Can you share your exact cmake configure command? `ENABLE_TOOLS`  is `ON` by default, so you probably deactivated it in your cmake config.

**Comment by cjcjcj7777** [comment]
> Looks like you didn't build `TOOLS`. Can you share your exact cmake configure command? `ENABLE_TOOLS` is `ON` by default, so you probably deactivated it in your cmake config.

Yes I changed my cmake configure and I was able to run the command 
thank you nilsnode and mandeepsandhu

**Comment by PIERRE3869** [comment]
Hello,
I can not activate enable tools [on ubuntu] for cmake can you tell me how to do?
Thank you very much for your help
Pierre

**Comment by nilsnolde** [comment]
what's your commands to configure and build?

**Comment by PIERRE3869** [comment]
Hello Nils,
I used these commands:
mkdir build
cd $_
cmake ..
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_INSTALL_PREFIX=/usr
-DENABLE_BENCHMARKS=OFF

**Comment by nilsnolde** [comment]
btw, did you actually build valhalla? you only showed the cmake config command..

**Comment by PIERRE3869** [comment]
here is the result of the command tree -L 1
AUTHORS
├── bench
├── build
├── CHANGELOG.md
├── cmake
├── CMakeLists.txt
├── codecov.yml
├── COPYING
├── date_time
├── docker
├── docs
├── include
├── libvalhalla.pc.in
├── LICENSE.md
├── locales
├── lua
├── mkdocs.yml
├── NEWS
├── proto
├── README.md
├── readthedocs.yml
├── run_route_scripts
├── scripts
├── src
├── taginfo.json
├── test
├── test_requests
├── third_party
└── valhalla

**Comment by nilsnolde** [comment]
> do a tree -L 1 in your build directory

;)

**Comment by PIERRE3869** [comment]
Sorry I am a beginner on ubuntu and valhalla.
the command you gave me for the build folder gives 0 directories, 0 files.

**Comment by nilsnolde** [comment]
no worries: `cd build && tree -L 1` works as well. if not: is there a `valhalla_service.cc` in the build folder?

**Comment by PIERRE3869** [comment]
in the build folder, I have no files.

**Comment by nilsnolde** [comment]
then please follow the documentation, e.g. 

```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j$(nproc) # for macos, use: make -j$(sysctl -n hw.physicalcpu)

sudo make install
```

**Comment by PIERRE3869** [comment]
when I run the commands I get the following error message

he source directory "/home/pierre" does not appear to contain CMakeLists.txt.

**Comment by nilsnolde** [comment]
ok, this goes now way beyond an issue tracker for a project. please make yourself familiar with the basic tools you're using or consider asking a more proficient friend or use stackoverflow. 

last hint I'll give you: you need to be in the valhalla directory before executing those commands.

**Comment by PIERRE3869** [comment]
the request is well executed in the valhalla directory but the commands valhalla [valhalla_build_config] is not found.
Thank you very much for your help

**Comment by nilsnolde** [comment]
maybe it'll be easier for you to use docker: https://github.com/gis-ops/docker-valhalla

**Comment by PIERRE3869** [comment]
thank you very much for the link I managed to install the Valhalla docker but when I run the command curl http://localhost:8002/route --data '{"locations":[{"lat":41.318818,"lon":19.461336},{"lat":41.321001,"lon":19.459598}],"costing":"auto","directions_options":{"units":"miles"}}' | jq '.'
I get the error message "failed to connect to localhost port 8002 : connection denied

**Comment by nilsnolde** [comment]
let's not leave stuff in this issue that's irrelevant for valhalla, instead you can create the first discussion in our docker repo: https://github.com/gis-ops/docker-valhalla/discussions
