### ISSUE TITLE
Unzipped cache in skadi

### ISSUE THREAD

**Issue by molind** [valhalla/valhalla#3071]
I've tried to build tiles using compressed elevation data and found that 
unzipped_cache inside skadi sample used without any locks between different threads.

And because it caches only 1 tile it's terribly slow in `add_elevation` task. But lack of speed is not the worse issue. Pointer from `unzipped_cache` passed to multiple inflate functions at the same time. https://github.com/valhalla/valhalla/blob/master/src/skadi/sample.cc#L151-L156

 https://github.com/valhalla/valhalla/blob/master/src/baldr/compression_utils.cc#L102-L111 there I've added a log function to check what happens.
```
      // several fatal errors to worry about
      code = inflate(&stream, flush);
      switch (code) {
        case Z_STREAM_ERROR:
        case Z_NEED_DICT:
        case Z_DATA_ERROR:
        case Z_MEM_ERROR:
          inflateEnd(&stream);
          LOG_ERROR(std::string("inflate Error: ") + std::to_string(code) + ", " + stream.msg);
          return false;
      }
```
It prints "inflate Error: -3, incorrect data check".

Same issue happens while reading data from "cache" without any sync primitives. After unzipped_cache.first check unzipped_cache.second could be easily changed by other thread.
https://github.com/valhalla/valhalla/blob/master/src/skadi/sample.cc#L139-L142

P.S. I'd suggest to use lz4, instead of gzip. Lz4 provides ~ the same compression ratio while decompression speed is 4-5 times faster.

**Comment by molind** [comment]
When separate buffer is used by each thread it works without errors. I know it doesn't return anything just makes sure it could inflate elevation tiles.

```diff
diff --git a/src/skadi/sample.cc b/src/skadi/sample.cc
index 641c0d8..6350b3f 100644
--- a/src/skadi/sample.cc
+++ b/src/skadi/sample.cc
@@ -147,25 +147,34 @@ const int16_t* sample::source(uint16_t index) const {
     s.avail_in = static_cast<unsigned int>(mapped.second.size());
   };
 
+  std::vector<int16_t> out_buffer;
+  out_buffer.resize(HGT_PIXELS);
+
   // for setting where to write the uncompressed data to
-  auto dst_func = [this](z_stream& s) -> int {
-    unzipped_cache.second.resize(HGT_PIXELS);
-    s.next_out = static_cast<Byte*>(static_cast<void*>(unzipped_cache.second.data()));
+  auto dst_func = [out_buffer](z_stream& s) -> int {
+    //unzipped_cache.second.resize(HGT_PIXELS);
+    s.next_out = (Byte*)out_buffer.data();
     s.avail_out = HGT_BYTES;
     return Z_FINISH; // we know the output will hold all the input
   };
 
+  auto filename = mapped.second.name();
+
   // we have to unzip it
   if (!baldr::inflate(src_func, dst_func)) {
-    LOG_WARN("Corrupt compressed elevation data");
+ //   LOG_WARN("Corrupt compressed elevation data");
+    LOG_WARN((filename + " corrupted").c_str());
+
     unzipped_cache.first = -1;
     return nullptr;
+  } else {
+    LOG_WARN((filename + " ok").c_str());
   }
 
   // update the simple cache
   // TODO: LRU
-  unzipped_cache.first = index;
-  return unzipped_cache.second.data();
+  //unzipped_cache.first = index;
+  return nullptr;
 }
 
 template <class coord_t> double sample::get(const coord_t& coord) const {
```

**Comment by kevinkreiser** [comment]
yeah the problem stems from two use cases without clear differentiation. we added the cache primarily so that we could use it on a multi process deployment of the service. for data building you generally need pretty large disk so we never considered using compressed sources for associating the data at tile building time. 

>  I'd suggest to use lz4

yeah in fact 3 years ago i implemented this with lz4 and in my tests it was still so slow it wasnt really useful for a real time scenario (api service). its probably fine for tile building.

**Comment by molind** [comment]
I have two servers for data building. One with RAID0 SATA drivers - it's terribly slow due to SATA low iops. And second with 2 Tb super fast NWME, but it can't be used, because extracted elevation data takes 1.5Tb. With a good cache of 100-200 tiles. NWME solution should work really fast even on 1Tb drive.
Current cache should be disabled, because it returns dangerously wrong data or crashes on heavy load.

**Comment by lseelenbinder** [comment]
@kevinkreiser sorry to hijack this thread a little bit, but:

> yeah in fact 3 years ago i implemented this with lz4 and in my tests it was still so slow it wasnt really useful for a real time scenario (api service). its probably fine for tile building.

I just discovered this due to a weird series of investigations into performance timing and memory usage. I reimplemented the cache using lz4, and I saw a meaningful improvement for cache misses.

Generally, a cache miss on my local machine went from costing ~120ms per tile (to gunzip and then serve the lookup) to 15~20ms per tile. While 100+ms overhead may cause issues for large requests, 15-20ms is actually reasonable. Would you accept a PR for an lz4 option (it is just based on the file extension, so mixing and matching is fine, too)?

**Comment by kevinkreiser** [comment]
@lseelenbinder yes of course we would accept a pr to bring back lz4 support! i forget how it did it at this point but the important thing is that any thirdparty code we vendor needs to have an MIT compatible license. i think i just used the single header and source file and built them directly into valhalla. looks like they are bsd 2 clause which is perfect. also iirc another important distinction is that there are several flavors of lz4, one that is machine independent (doesnt care about endieness) and one that isnt. i dont remember the details but we'll need to be clear on which one(s) we support. anyway, thanks very much for offering, i look forward to your pr!
