### ISSUE TITLE
install valhalla in editable mode

### ISSUE THREAD

**Issue by pradkrish** [valhalla/valhalla#3076]
Sorry, this is a basic question. I am running ubuntu on my machine, I would like to install valhalla in editable mode so I can play around with the code, test the output and possibly make some code contributions as well. I did check the README but instructions on how to do it is not clear to me, any help is really appreciated. Thanks.

**Comment by nilsnolde** [comment]
After you play around with the code, you'll need to recompile the code. Since re-compiling takes quite a while (at least multiple seconds) I'm not sure if there are IDE magics that auto-recompile whenever you're saving a file (similar to e.g. PyCharm Flask hot-reloading). I'd find that rather disturbing I think..

You best test your output by actually writing unit tests. Other than that you can use your favorite debugger (e.g. inside your IDE) to debug your code e.g. when running `valhalla_service` or other executables. What you need to do exactly depends heavily on your software stack and therefore isn't a good fit for this project's README. There are good tutorials for debugging c++ code.

**Comment by nilsnolde** [comment]
That being said, don't hesitate to ask further.. I've been where you are not too long ago, I know how hard the entry can be in case this is the first time you're exposed to c++. I can assure you it's worth the pain:)

**Comment by pradkrish** [comment]
@nilsnolde Thank you for those encouraging words. I am really looking forward to contributing even in small ways if possible.

So if I look at README.MD, is it enough I follow the instructions in "Building from Source - Linux", "Running" and "Tests"? What is  confusing is "Building from Source - Linux" only covers installing the dependencies but it says nothing about building. Thanks again.

**Comment by PureW** [comment]
> So if I look at README.MD, is it enough I follow the instructions in "Building from Source - Linux", "Running" and "Tests"? What is confusing is "Building from Source - Linux" only covers installing the dependencies but it says nothing about building thinking Thanks again.

Hmm, it seems to be missing a section in there. Look further down below and you'll see

> After getting the dependencies install it with: ...

**Comment by pradkrish** [comment]
Thanks, I suspected so. Should I enable all the build options while building? If not, what are the most common build option to include?

**Comment by PureW** [comment]
Depends a little bit on what functionality you want. You could take a look at what we run in ci at https://github.com/valhalla/valhalla/blob/master/.circleci/config.yml#L66-L69

Also, you may want to disable python bindings for example unless you want those as it adds more things to the build-phase that could fail.

**Comment by nilsnolde** [comment]
To get you started, you'd ideally already have some basics on CMake. It has one of the best documentations IMO, it's fairly easy to learn. 

To learn about all the build options, look at the root CMakeLists.txt. No need to install anything, that only gets confusing, you can run all executables from the build folder. Then it's up to you and cpp:) Some hints: the lua folder contains most of the OSM tag parser instructions and the proto folder the protobuf schemas (which valhalla uses to communicate between the different modules, loki/thor/odin).

Tests are a good resource to learn a new project. Valhalla also has a fun way to build tests with its `gurka` framework: https://github.com/valhalla/valhalla/blob/master/test/gurka/README.md. 

A few PRs which add some features, could be helpful to understand some bits:
https://github.com/valhalla/valhalla/pull/2667
https://github.com/valhalla/valhalla/pull/2555
https://github.com/valhalla/valhalla/pull/2750

**Comment by pradkrish** [comment]
Thanks, I managed to install and play around with some tests. Also thanks for sharing those merged PRs, it was informative to look through the top_speed implementation. I am looking for an issue to work on, I will be happy if someone is interested in mentoring me through my first PR. Feel free to give some suggestions, I am very eager to get started. :)

**Comment by nilsnolde** [comment]
That's usually @kevinkreiser mentoring people through valhalla haha I can give it a shot too as long as you don't blame me if the resulting PR triggers a lot of change requests from others ;) So hit me on my public Github email and we can schedule smth! E.g. #3079 is a low hanging fruit.

**Comment by nilsnolde** [comment]
I'll close this for now. But we might have a new contributor here with @pradkrish :tada: :partying_face:
