### ISSUE TITLE
Out of Bounds Access in Multimodal Routing

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#3086]
Disclaimer->
I am adding another hierarchy and facing the problem , So this can be the issue with transit hierarchy , I still don't fully understand the system but If i am right this should be fixed

https://github.com/valhalla/valhalla/blob/7e67cf9056e7d68ef06d960006a7670fe607fe35/src/thor/multimodal.cc#L516
here code is accessing the basell by `endtile->header()->base_ll()` this endltile could be transit tile as far as i can see

if you look at the implementation of getting basell

https://github.com/valhalla/valhalla/blob/7e67cf9056e7d68ef06d960006a7670fe607fe35/valhalla/baldr/graphtileheader.h#L168 

if the tile is transit this will be a leak

**Comment by kevinkreiser** [comment]
good catch! you can fix it by adding an if and asking the tile hierarchy for the transit level specifically. we do this many other places in the code. ive retitled it because its not a memory lead but rather invalid access

**Comment by pranavpandey1998official** [comment]
fixed in PR
