### ISSUE TITLE
Avoid polygon custom costs

### ISSUE THREAD

**Issue by samvanemelen** [valhalla/valhalla#3087]
I am trying to enforce absolute zone restrictions in my routing. Valhalla is perfect and seems to be, as far as I know, the only open source toolbox that provides this. But with some experimentation I figured that the routes still go through the 'avoid_polygon' when the cost of not doing so is high enough. It seems as if behind the scenes there is a cost associated with going through these polygons. Is there a way to specify this cost to enforce absolute restricting polygons?

**Comment by nilsnolde** [comment]
Hm.. there's actually nothing cost-related in the `avoid_polygons` code. It removes edges from the query graph which intersect with your polygons. That being said, it's a fairly recent (and probably undertested in the field) addition and there's a chance for bugs.

Can you give me a full example request? (I really hope mapbox updated their valhalla instance over the past months..)

> still go through the 'avoid_polygon' when the cost of not doing so is high enough

how did you determine that?

**Comment by samvanemelen** [comment]
It must be the name that got me on the wrong track then. Since it says 'avoid' polygon, I must have interpreted the results that valhalla does not completely restricts it. I am currently working on a local docker instance of valhalla (run-latest) so it should be a reasonably recent version I suppose. The entire OSM dataset of Belgium is used.

After making the avoid polygon bigger, It happened that it did avoid the entire polygon. That's why I thought it was cost related. But I cannot seem to replicate that exact behavior. The polygon seems to remove some edges from the graph but not all.

Route without avoid polygon:
![route1](https://user-images.githubusercontent.com/36103001/119099362-1a1c2b80-ba17-11eb-9bc3-9cf51a38096b.PNG)
Polygon to avoid:
![polygon2](https://user-images.githubusercontent.com/36103001/119099382-1f797600-ba17-11eb-8339-fc1561ee30dc.PNG)
Route with avoid polygon:
![route3](https://user-images.githubusercontent.com/36103001/119099396-22746680-ba17-11eb-8c4f-d10d3cfe0537.PNG)

request made to '/route' with the following json body:
```
{
    "locations": [{"lat":51.209"lon":4.412},{"lat":51.085,"lon":2.611}],
    "costing": "auto", 
    "avoid_polygons": [
          [
            [ 3.823, 50.870 ],
            [ 4.191, 50.870 ],
            [ 4.191, 51.196 ],
            [ 3.823, 51.196 ],
            [ 3.823, 50.870 ]
          ]
        ]}
```

For smaller routes it seems to be working fine:

<img align='left' src="https://user-images.githubusercontent.com/36103001/119101596-71bb9680-ba19-11eb-8e3a-b55668dc0374.PNG" height="200" />

<img align='left' src="https://user-images.githubusercontent.com/36103001/119101605-72ecc380-ba19-11eb-876c-55c04dac6e5e.PNG" height="200" />

<img align='left' src="https://user-images.githubusercontent.com/36103001/119101589-708a6980-ba19-11eb-915b-59eac4cd66a3.PNG" height="200" />

<br clear="left"/>
<br/>
I am no expert on everything that happens behind the scenes, but perhaps an issue with the avoid polygon when it covers multiple tiles?

**Comment by nilsnolde** [comment]
Yeah, crap, I can sorta reproduce this now.. From what I can see it's related to shortcuts, not the size of the polygons.. I had a quick look and don't understand why this happens.. With this query from Vienna to Linz, Austria and a tiny avoid polygon on the highway:

```
https://api.mapbox.com/valhalla/v1/route?access_token=your_token
Parameters:
{ "costing": "auto", "narrative": false, "id": 1, "locations": [ { "lon": 16.428852, "lat": 48.185514 }, { "lon": 14.310785, "lat": 48.305241 } ], "avoid_polygons": [ [ [ 15.589090651484636, 48.186662317143515 ], [ 15.607341371723018, 48.186662317143515 ], [ 15.605151285294411, 48.17059821926258 ], [ 15.587630593865564, 48.173032497043174 ], [ 15.589090651484636, 48.186662317143515 ] ] ] }
```

there are **no** shortcuts passing this check for the above query: 
https://github.com/valhalla/valhalla/blob/7aab546ba769d1997441a27e62616c19283edeb2/src/loki/polygon_search.cc#L105-L108

which doesn't seem right.. We added shortcuts to the spatial bins before the avoid_polygons code, it's even tested. This might take a little while, don't have too much capacity at the minute.. 

Do you have a clue @kevinkreiser ? I tried debugging briefly, but only found that **sometimes** there are no shortcuts included in the bins where I think there should be some..

**Comment by kevinkreiser** [comment]
The avoid edges should get checked by the allowed method on costing. it should be pretty straight forward to see why the edge gets into the queue by setting a conditional breakpoint and watching how the edge is evaluated in the main loop of bidirectional a* for example. this is the block of code in question that decides whether or not to add an edge for expansion:

https://github.com/valhalla/valhalla/blob/ae987bf50a26ac506b3883d1fcaec860072bfd8b/src/thor/bidirectional_astar.cc#L368-L411

then the ExpandInner function checks if its allowed:

https://github.com/valhalla/valhalla/blob/ae987bf50a26ac506b3883d1fcaec860072bfd8b/src/thor/bidirectional_astar.cc#L217-L224

Which is where i believe the costing takes the list of avoid edges and rejects ones on its list

**Comment by pranavpandey1998official** [comment]
hey, just giving my 2 cents, but I cannot see any logic which avoid edges in higher hierarchy level, just looked at it for 2 sec

**Comment by nilsnolde** [comment]
thx both for chiming in. if no one else picks this up in the meantime, I'll look this over in a few days when I have a little more time

**Comment by kevinkreiser** [comment]
@pranavpandey1998official the way it supposed to work is that the polygon gets interesected with the edges in the bins in the level 2 tiles. the level 2 tiles hold lists of all edges on all levels which interesect subsections of the geographic region w hich defines a given level 2 tile. once this intersection happens we take the list of edges which intersected (the boundary only of) the polygon and push that list into the costing. the costing then does a look up on the edge id when we run the routing algorithm.

**Comment by nilsnolde** [comment]
Was of course a problem with the avoid polygons code, see https://github.com/valhalla/valhalla/pull/3090: shortcuts weren't included in the avoid edge set.

**Comment by nilsnolde** [comment]
@ismailsunni this should also be interesting for you guys.

**Comment by nilsnolde** [comment]
FWIW, I think @samvanemelen is right, `avoid_` suggests penalties rather than real exclusion (which it is). Maybe `exclude_polygons` and `exclude_locations` in v4?!

**Comment by kevinkreiser** [comment]
We can alias the parameters today so long as we don't remove support for parsing the improperly worded ones. Then we update the docs and it slowly fads out of existence

**Comment by nilsnolde** [comment]
Yeah I remember the `auto_shortest` drill ;) I'll open an issue about it, maybe someone else wants to pick that up.
