### ISSUE TITLE
Replace `avoid_*` with `exclude_*`

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3092]
The `avoid_polygons/locations` are somewhat confusingly named suggesting penalization at work, while it's really exclusion (see e.g. https://github.com/valhalla/valhalla/issues/3087#issue-897125339)

Would be worthwhile to **alias** those params with `exclude_*` equivalents.

**Comment by RhnSharma** [comment]
I would like to take this one.
