### ISSUE TITLE
Isochrone serialization rounds input threshold value significantly

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#3094]
The Valhalla isochrone API lets you specify contour values like:

  - `{ distance: 10.5 }` - 10.5km
  - `{ time: 1.5 }` - 1.5 minute/90 seconds

However, the serialized response truncates these into the nearest integer:

https://github.com/valhalla/valhalla/blob/master/src/tyr/isochrone_serializer.cc#L78

Example where things get a bit wonky - requested a contour of 1.5 minutes, response _was_ the 1.5 minute contour, but the `contour` property just says 1:

```
$ curl -d '{"locations":[{"lat":38,"lon":-121}],"costing":"auto","date_time":{"type":0},"contours":[{"time":1.5}],"polygons":false,"denoise":1}' http://localhost:8002/isochrone
{"features":[{"properties":{"fill-opacity":0.33,"fill":"#bf4040","fillColor":"#bf4040","color":"#bf4040","fillOpacity":0.33,"opacity":0.33,"contour":1,"metric":"time"},"geometry":{"coordinates":[[-121.004000,38.022013],[-121.004028,38.020972],[-121.003161,38.020839],[-121.003064,38.019936],[-121.002276,38.019724],[-121.001233,38.018000],[-121.001404,38.017404],[-121.002783,38.017000],[-121.001000,38.016774],[-121.000305,38.016000],[-121.000501,37.993000],[-121.001363,37.992000],[-121.000409,37.989000],[-121.001000,37.988342],[-121.006941,37.988000],[-121.000570,37.987430],[-121.000000,37.980183],[-120.999659,37.987000],[-120.998534,37.988000],[-120.999591,37.989000],[-120.999421,38.002000],[-120.999000,38.002528],[-120.995839,38.003000],[-120.996791,38.004209],[-120.999000,38.004496],[-120.999458,38.005000],[-120.999695,38.016000],[-120.999000,38.016894],[-120.997196,38.017000],[-120.999555,38.017445],[-121.000608,38.019000],[-121.001678,38.019322],[-121.001904,38.020096],[-121.002800,38.020200],[-121.002945,38.021055],[-121.003914,38.021086],[-121.004000,38.022013]],"type":"LineString"},"type":"Feature"}],"type":"FeatureCollection"}
```

@kevinkreiser looking back through git history, it looks like this is yours from >5 years ago: https://github.com/valhalla/valhalla/blame/f45badaebfaf8b4c979fa8af3ee308ac8a98f0ad/src/baldr/geojson.cc#L61

Any reason we can't serialize this as a float so it'll match the input?

**Comment by kevinkreiser** [comment]
I think when we were writing it the first time we were going for minutes resolution only but then we stored the value as float since costing stores it that way (as seconds). Looks like an oversight to me. I don't see why we can't support it. Since it's only one property it won't blow up the resulting response much compared to the enormous geom
