### ISSUE TITLE
valhalla_service: command not found

### ISSUE THREAD

**Issue by KaSakee** [valhalla/valhalla#3096]
I used part 1 and part 2 from this
https://gis-ops.com/valhalla-part-2-how-to-run-valhalla-on-ubuntu/

And my ubuntu is 20 LTS

I did everything in the details and check 100 times 
Can anyone help me?

valhalla_service: command not found

Btw everything went well an success i have no idea why is this not there

**Comment by nilsnolde** [comment]
Oops.. I see the mistake.. Here it says to configure with `-DENABLE_TOOLS=OFF`: https://gis-ops.com/valhalla-part-1-how-to-install-on-ubuntu/#3-Build-and-install-Valhalla

That's wrong as it won't build `valhalla_service`.. I'll correct that real quick.

And I'll transfer this issue, our tutorials are also open-source and have their own repo (on top of each article you can see a "Check it out on Github" link).

**Comment by nilsnolde** [comment]
Hmpf can't transfer issues, no rights for that. I opened one and fix it now, online in 10 mins: https://github.com/gis-ops/tutorials/issues/41
