### ISSUE TITLE
Tool valhalla_associate_segments.cc still uses removed AStarPathAlgorithm

### ISSUE THREAD

**Issue by mloskot** [valhalla/valhalla#3098]
This seems to be residue after removed files/classes:

https://github.com/valhalla/valhalla/blob/6c29b716fc2be4934ffe24d1eaacf39122451862/src/valhalla_associate_segments.cc#L8

https://github.com/valhalla/valhalla/blob/6c29b716fc2be4934ffe24d1eaacf39122451862/src/valhalla_associate_segments.cc#L197

Looks like the file is not compiled by any CI, otherwise it would have been caught, no?

**Comment by kevinkreiser** [comment]
Yeah we left this source around from the days when we were working on the open traffic initiative. The idea was to leave it for future reference in case we would ever add such a functionality back to the library. It's basically just an example of an algorithm at this point, definitely not meant to compile as the osmlr project has also been abandoned

**Comment by mloskot** [comment]
Thanks for the clarification.

Perhaps moving to an issue or a WIP PR would serve the archiving purpose.

**Comment by kevinkreiser** [comment]
I dont have a strong opinion on it, does one of them appeal to you more than the other? maybe even moving it to a document (markdown) or something?

**Comment by mloskot** [comment]
I don't have an opinion either and I don't want to interfere w/ the way you guys work.
I just noticed a problem while porting to newer Valhalla and I was searching through the source tree looking for `astar.h` related definitions, and I noticed that residue confusing.
