### ISSUE TITLE
Warnings section in response

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3099]
Would be nice to tell a user when certain things happen while processing, e.g. clamping values to their allowed maximum, enabling `destination_only` roads in 2. pass, deprecating request parameters etc.

IMO it should be a top-level `warnings` array of strings which is empty by default and all modules can add their share during processing: probably implement the most obvious ones first and add others wherever it feels appropriate in the future.

Suggestion:
1.  Include the `warning` field in `proto/api.proto` as `repeated string`. Or do we need extra info to justify a `Warning` message?
2.  Add warnings where sensible in the code and serialize for every action in `tyr/serializers.cc`

Opinions?

**Comment by Arkadipta-Chatterjee** [comment]
Can i work on this?

**Comment by kevinkreiser** [comment]
I think we should take @nilsnolde's suggestions above about which ones to implement, and actually flesh out the details a bit. I think for someone who doesnt know the code it will be hard otherwise to contribute.

Regrading where to keep this information, this was one of the ideas behind the info.proto message. I think we can add repeated strings to the `Info` message type to track warnings that should be user facing, i could also be confivinced that this structure isnt user facing and that we sh ould add it somewhere else to a part of the structure we already serialize out like `Options`

**Comment by nilsnolde** [comment]
that's kind of you to offer @Arkadipta-Chatterjee .. on second thought this might actually not be a `good first issue` for the reasons @kevinkreiser mentioned: it does need a fairly in-depth knowledge of the code/processing to know when to add a "warning" along the processing. the scaffolding around serialization, setting up pbf etc does not need that expertise, but that's also very quickly done.

if you want to contribute, may I suggest the following ones:
https://github.com/valhalla/valhalla/issues/3212 (making isochrone resolution more dynamic so we can get rid of the most glaring artifacts for smaller isochrones)
https://github.com/valhalla/valhalla/issues/3010 (if you have access to a Windows machine, this would be awesome to finally solve, should be fairly mechanical around spatialite integration in the code)

**Comment by nilsnolde** [comment]
but this issue would be nice for our use case as well, so after all those other todo's I'd like to close this as well.

> i could also be confivinced that this structure isnt user facing and that we sh ould add it somewhere else to a part of the structure we already serialize out like Options

"user-facing" you mean "returned in the response" @kevinkreiser ? if so, how would these warnings be beneficial if they're not returned to a user?

**Comment by kevinkreiser** [comment]
Sorry, that was poorly worded. I was saying saying we should decide which protobuf objects get serialized out in the response. Right now we don't do that for the info message type so that would be new. I was kind of thinking it's better to add to something we already serialize

**Comment by nilsnolde** [comment]
just to remind ourselves: #3464 is serializing the info object and @kevinkreiser even added a warnings object (next to an error object, which is already in use in that PR)

**Comment by nilsnolde** [comment]
so this is being worked on currently by @MuluhGodson . a bit more reference:

- `warnings` array: I think for now it's fine to simply have it in info.proto as `repeated string` instead of `CodedDescription` (like `errors`). what do you think @kevinkreiser ? or you want to have a central place eventually, similar to the errors?
- the "infrastructure" to add warnings is not totally clear to me yet. in the end we'd likely have to pass around the info/warnings object to a couple of functions who only look at `options` so far. I'd start simple for now with obvious query parameter deprecations which happen in `src/worker.cc` (where the full `api` object is already):
  - `auto_shorter`: https://github.com/gis-ops/valhalla/blob/master/src/worker.cc#L618
  - `avoid_polygons`: https://github.com/gis-ops/valhalla/blob/6dac5913835663881178537d53e3385cfdf6d695/src/worker.cc#L877-L880
  - maybe there's even others in there I don't see on a quick glance
- each (json) serializer will have to "build" the `warnings` section, so I guess a small function to do that in `tyr/serializers.h/cc` makes sense?

let us know if you feel differently @kevinkreiser .
