### ISSUE TITLE
Refactor costing options to handle common stuff in a one place

### ISSUE THREAD

**Issue by genadz** [valhalla/valhalla#3102]
It's easy to notice that different costing options have a lot of common parameters (for example, look at this section https://github.com/valhalla/valhalla/blob/master/src/sif/autocost.cc#L31-L42). Moreover, most of the common parameters have the same default values. Despite of the fact, we have to:
- parse the same costing option for each costing type;
- declare default value for each costing option even if it's the same.

So, each time when you try to introduce a new parameter you should copy-paste the same code for each costing option. It's not very convenient and should be refactored.

**Comment by kevinkreiser** [comment]
agree, i have been wanting to do this forever and just havent had the time. when i add a new thing, i try to put it just inside of dynamiccost and let the derived class use it from there. im sure there are some gotchas but id love to put all the parsing into the parent class and when we need to somehow have a way for the child class to customize. at the moment we are using some static functions though so we might want to make them non static so that we could get that specialization from the child class if we ever need to. but maybe its a problem we actually dont need to worry about yet, i need to refresh my memory

**Comment by genadz** [comment]
> agree, i have been wanting to do this forever and just havent had the time. when i add a new thing, i try to put it just inside of dynamiccost and let the derived class use it from there. im sure there are some gotchas but id love to put all the parsing into the parent class and when we need to somehow have a way for the child class to customize. at the moment we are using some static functions though so we might want to make them non static so that we could get that specialization from the child class if we ever need to. but maybe its a problem we actually dont need to worry about yet, i need to refresh my memory

As for me it's two different tasks:
1) move costing options parsing to one place;
2) move common parameters from all derived classes to the base one (`DynamicCost`).

This issue is more about the 1st point. Here I want to generalize parsing and setting default values.

**Comment by genadz** [comment]
rough code snippet
```c++
// dynamiccost.h

struct SharedCostingOptions {
  SharedCostingOptions();
  // define shared options
  float opt1;
  float opt2;
  ...
};

const SharedCostingOptions kDefaultSharedOptions{};

void ParseSharedCostOptions(const rapidjson::Value& obj, CostingOptions* pbf_costing_options,
                            const SharedCostingOptions& defaults);

// dynamiccost.cc

SharedCostingOptions::SharedCostingOptions() {
  // set default values
  opt1 = default_opt_1;
  opt2 = default_opt_2;
  ...
}

void ParseSharedCostOptions(const rapidjson::Value& obj, CostingOptions* pbf_costing_options,
                            const SharedCostingOptions& defaults) {
  // parse shared values; use defaults for missing parameters
}

// autocost.cc

SharedCostingOptions GetAutoDefaultSharedOpts() {
  auto defaults = kDefaultSharedOptions; // from dynamiccost.h file
  defaults.opt1 = override_value_1;
  defaults.opt2 = override_value_2;
  ...
  return defaults;
}

void ParseAutoCostOptions(const rapidjson::Document& doc,
                          const std::string& costing_options_key,
                          CostingOptions* pbf_costing_options) {
  auto const & default_shared_opts = GetAutoDefaultSharedOpts();
  ParseSharedCostOptions(json_obj, pbf_costing_options, defaul_shared_opts);
  
  ...
  // parse auto-specific parameters
}

```

**Comment by genadz** [comment]
Here is the [PR](https://github.com/valhalla/valhalla/pull/3125) that implements https://github.com/valhalla/valhalla/issues/3102#issuecomment-848842369
