### ISSUE TITLE
Third Party Library 

### ISSUE THREAD

**Issue by rochadt** [valhalla/valhalla#3136]
I'm experiencing some issues trying to add a third party library (forgive me in advanced, I'm still pretty new to c++). I'm trying to take a similar approach to the `rapidjson` third party library, but I'm not having any luck. 

I'm trying to add a Redis client, so I added the following repository as a submodule in the `third_party` directory:
https://github.com/cpp-redis/cpp_redis

I created a header file in `valhalla/redis/redis.h`
```
#include <cpp_redis/cpp_redis>

namespace valhalla {
namespace redis {

class Client {
public:
  cpp_redis::client client;

  void connect() {
    client.connect();
  };

  void disconnect() {
    client.disconnect();
  };
};
} // namespace redis
} // namespace valhalla
```

Then I created the CMakeLists.txt and redis.cpp file in `src/valhalla/redis`:
```
file(GLOB headers ${VALHALLA_SOURCE_DIR}/valhalla/redis/*.h)

set(includes
        ${VALHALLA_SOURCE_DIR}
        ${VALHALLA_SOURCE_DIR}/valhalla
        ${VALHALLA_SOURCE_DIR}/third_party/cpp_redis/includes
        ${VALHALLA_SOURCE_DIR}/third_party/cpp_redis/tacopie/includes
        ${CMAKE_CURRENT_BINARY_DIR}/src/redis
        )

set(sources
        redis.cc)

valhalla_module(NAME redis
  SOURCES
    ${sources}
  HEADERS
    ${headers}
  INCLUDE_DIRECTORIES
    PUBLIC
      ${includes}
    PRIVATE
      ${CMAKE_CURRENT_BINARY_DIR}
  DEPENDS
    ${valhalla_protobuf_targets}
    Boost::boost)
```
and 
```
#include "redis/redis.h"

namespace valhalla {
namespace redis {
...
```

I also made sure the library is added to the `CMAKE_BINARY_DIR` in `src/CMakeLists.txt`:
```
add_subdirectory(${VALHALLA_SOURCE_DIR}/third_party/cpp_redis ${CMAKE_BINARY_DIR}/third_party/cpp_redis)
```

The issue arises when I try to use `cpp_redis::client client;` in `redis.h` I get the following error:

```
undefined reference to `cpp_redis::client::client()'
```

Is there something obvious I'm missing here? This is set up almost the exact same way as `rapidjson`, but just won't work. Any help is appreciated, thanks!

**Comment by danpat** [comment]
`rapidjson` is a header-only library and doesn't need to be compiled.

It looks like `cpp_redis` needs to be built as a binary module then linked in separately.  This is closer to the `googletest` third-party dependency we have, and is a bit more complicated to setup.

**Comment by rochadt** [comment]
@danpat ahhh yes that would make sense. I see the issue now, and thank you for the quick response! I will look further into the `googletest` dependency, or try to find a header only library. Thanks!
