### ISSUE TITLE
Valhalla  installation

### ISSUE THREAD

**Issue by saraefaf1** [valhalla/valhalla#3139]
Sorry, this is a basic question.
i use windows10 and want to install valllaha for my map matching project . but idont know ,how do that. I did check the github but instructions on how to do it is not clear to me, any help is really appreciated. Thanks.

**Comment by nilsnolde** [comment]
It would help if you could outline what exactly is not clear to you from this description: https://github.com/valhalla/valhalla#building-from-source---windows

you only need to clone vcpkg, install CMake and follow the instructions line by line. that should work out-of-the-box.

**Comment by nilsnolde** [comment]
also with the latest windows 10 updates you can run valhalla with docker, I've done that before. it does require you to enable some things (like WSL2 & hyperv virtualization) to be able to load ubuntu images on windows, but if you know docker a little that'd be the least-friction way. or, if you already have wsl2 and a recent ubuntu to go with it, you can do the linux installation, also easier.
