### ISSUE TITLE
ENABLE_SINGLE_FILES_WERROR = OFF by default?

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3157]
Just built valhalla with default settings and it complained in two locations with `-Werror` from third-party lib code (benchmark and gtest). Not so much a problem (for us), but can be really off-putting for newcomers. 

Should we default `ENABLE_SINGLE_FILES_WERROR = OFF`?

**Comment by kevinkreiser** [comment]
by complain do you mean compilation failed?

**Comment by nilsnolde** [comment]
yep

**Comment by nilsnolde** [comment]
Should I reproduce and paste the stack?

**Comment by nilsnolde** [comment]
gcc 10.2.0 and on arch linux

**Comment by nilsnolde** [comment]
hm, still, even setting `ENABLE_SINGLE_FILES_WERROR=OFF`:

```
build] FAILED: googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o 
[build] ccache /usr/bin/g++ -DBOOST_NO_CXX11_SCOPED_ENUMS -DDATA_TOOLS -I../third_party/googletest/googletest/include -I../third_party/googletest/googletest -fdiagnostics-color=auto  -g -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -pthread -std=c++11 -MD -MT googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -MF googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o.d -o googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -c ../third_party/googletest/googletest/src/gtest-all.cc
[build] In file included from ../third_party/googletest/googletest/src/gtest-all.cc:42:
[build] ../third_party/googletest/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
[build] ../third_party/googletest/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
[build]  1301 |   StackLowerThanAddress(&dummy, &result);
[build]       |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
[build] ../third_party/googletest/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
[build]  1290 | static void StackLowerThanAddress(const void* ptr, bool* result) {
[build]       |             ^~~~~~~~~~~~~~~~~~~~~
[build] ../third_party/googletest/googletest/src/gtest-death-test.cc:1299:7: note: ‘dummy’ declared here
[build]  1299 |   int dummy;
[build]       |       ^~~~~
[build] cc1plus: all warnings being treated as errors
```

**Comment by nilsnolde** [comment]
Is it set in googletest itself? Any idea how to get rid of it? Was about to quickly update the exclude_* PR to get that shipped

**Comment by kevinkreiser** [comment]
cc @PureW who is also on arch

i thought that we were only enabling -Wall and -Werror on our own sources but it seems somehow it leaks with that configuration. perhaps we shoudl roll back some recent changes on that

**Comment by kevinkreiser** [comment]
> Is it set in googletest itself?

maybe since we recently updated that right?

**Comment by nilsnolde** [comment]
oh sorry, was relying on the version info from VS Code.. gcc actually was updated to 11.1.0 recently, also the cause for this:

was fixed in googletest: https://github.com/google/googletest/commit/a0cbbba131dd0db65fad238bfe38692075bfcad3. updated the dependency to that commit which worked. really frustrating option `-Werror` for a library, damn.. how can you ever make sure it won't break at some point with some compiler who introduced some new warning.. anyways..

we're on a almost 1 year older version. what you think you'd like to do here?

**Comment by kevinkreiser** [comment]
gbench was updated recently with another thirdparty lib: https://github.com/valhalla/valhalla/pull/3151

i suppose we should just update unless its breaking

**Comment by nilsnolde** [comment]
I'll give it a shot to update gtest in another PR

**Comment by nilsnolde** [comment]
or not: https://github.com/valhalla/valhalla/pull/3112#issuecomment-849731857 :face_with_head_bandage:

**Comment by PureW** [comment]
> cc @PureW who is also on arch
> 
> i thought that we were only enabling -Wall and -Werror on our own sources but it seems somehow it leaks with that configuration. perhaps we shoudl roll back some recent changes on that

Yes, I just tested with `gcc` and I see this issue as well when using gcc 11.1.0. Lately I've been running clang locally though due to better error messages (subjectively) and there it works fine. 

Hmm what a jigzaw puzzle trying to fit all everything together.

**Comment by nilsnolde** [comment]
I’m personally ok with having a dirty gtest for now.. also doubt there’ll be production systems on gcc 11 anytime soon. Considering the potential effort we’d have to put in to update the submodule (apparently linker issues in most test files for clang) I guess we should at least warn in the readme for those arch/fedora people. I’ll close this issue and open a new one for a todo. 

Or is there anything other you’d like to do as of now?
