### ISSUE TITLE
broken Ubuntu install for 20.04, missing libprime-server-dev package

### ISSUE THREAD

**Issue by matkoniecz** [valhalla/valhalla#3158]
```
mateusz@grima:~$ sudo apt-get install -y cmake make libtool pkg-config g++ gcc curl unzip jq lcov protobuf-compiler vim-common locales libboost-all-dev libcurl4-openssl-dev zlib1g-dev liblz4-dev libprime-server-dev libprotobuf-dev prime-server-bin
[sudo] password for mateusz: 
Sorry, try again.
[sudo] password for mateusz: 
Sorry, try again.
[sudo] password for mateusz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libprime-server-dev
E: Unable to locate package prime-server-bin
```

#1724 suggests `sudo add-apt-repository ppa:kevinkreiser/prime-server` - is it the proper solution?

related to #2904

**Comment by nilsnolde** [comment]
actually both ppa's ([valhalla](https://launchpad.net/~valhalla-core/+archive/ubuntu/valhalla) &  [kevin's personal one](https://launchpad.net/~kevinkreiser/+archive/ubuntu/prime-server) have the same stuff for prime_server, so it shouldn't matter which one you use, but really one should be enough. you sure you followed https://github.com/valhalla/valhalla/blob/master/docker/install-shared-deps.sh?

**Comment by matkoniecz** [comment]
hm, it is possible that I missed it

I will reopen if I will reproduce it
