### ISSUE TITLE
"Then, build prime_server." in install is unclear

### ISSUE THREAD

**Issue by matkoniecz** [valhalla/valhalla#3165]
refers to https://github.com/valhalla/valhalla#installing-dependencies docs

"build `prime_server`." suggests that it was obtained by the previous step (`--recurse-submodules`) but as far as I see it needs to obtained independently.

If it is a submodule: I would add `cd path/prime_server` step/.

If it needs to obtained independently: I would change to "optain and build `prime_server` by following instructions in its repository."

Also, is it even needed on Linux? In such case `prime-server-bin` is installed. (this part of confusion is related to #3163 - not sure what is MacOS specific, what is applying also to Linux)

**Comment by matkoniecz** [comment]
Sorry for issue spam - but I tried to setup based on existing README and the first attempt failed.

**Comment by nilsnolde** [comment]
Hm, I do agree that we could do a better job of breaking down all steps involved into more comprehensible, less confusing parts. Would be a good job for someone going through all of it the first time and realizing the pitfalls:) 

But in this case the section you’re linking to, actually links to the build and installation section of prime_server. Just have to click on it.

**Comment by matkoniecz** [comment]
Would you accept PR with minor rephrasing it to "obtain and build prime_server by following instructions in its repository.", that would keep the current link?

When I encountered it I thought that I screwed something up (or something changed) as I expected it to be pulled as one of submodules and ready to be build.

**Comment by nilsnolde** [comment]
would be fine I think, yes
