### ISSUE TITLE
trip into graph 

### ISSUE THREAD

**Issue by Laura0106** [valhalla/valhalla#3176]
Hello dear developers ! I am sorry for distracting. Thanks for your work! I am writing master thesis "Location prediction of vehicles based on geo-tracking.  I would like to ask you: is it possible to put a whole trip on the graph (for ex osmnx) without using «shortest_path» , which is the method of networkx library. I will be glad for any help! Thank you in advance !!!!!

![image](https://user-images.githubusercontent.com/86328190/123342660-79a6b300-d550-11eb-9553-30d969a2ce53.png)

**Comment by kevinkreiser** [comment]
hi @Laura0106 can please describe what your trying to do a bit more? maybe describe the process you want to accomplish step by step. i cant tell if you are looking for map matching or if you are trying to actually add edges into the graph from a gps trace or something completely different. the also please explain what you mean by "without using shortest path". thanks!

**Comment by Laura0106** [comment]
To be more precise : for each GPS point there should be closest edge (of the graph) to this point  , from that I can plot whole trip with the help of these edges. This is what I am looking for
Thnaks!

**Comment by mandeepsandhu** [comment]
> To be more precise : for each GPS point of one track there should be closest edge (of the graph) to this point , from that I can plot whole trip with the help of these edges. This is what I am looking for
> Thnaks!

I think you'd want to use valhalla's [map-match API](https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md) which is built for this purpose - you give it a set of coordinates and it returns the the most probable path for it,

**Comment by kevinkreiser** [comment]
What exactly do you need as a final output? The output of that api is the edges in the graph. yes it returns way ids which can be made of more than one edge in the graph. Osm has no concept of edges only graphs do which is a post processing step. If you want to localize an edge from a graph you need to know about the osm nodes at the begining and end of the edge and the wayid it belongs to. if you just want the actual full paths geometry that is also returned in the map match as `shape`

**Comment by Laura0106** [comment]
I would like to build a track as in this image,which is build based on GPS points (see below), but with the help of edges.
![image](https://user-images.githubusercontent.com/86328190/123460675-44e63a80-d5e8-11eb-8757-5966a63392f9.png)

**Comment by nilsnolde** [comment]
simple map-matching use case
