### ISSUE TITLE
Unable to update live speed with add_predicted_traffic

### ISSUE THREAD

**Issue by kitindir** [valhalla/valhalla#3180]
Hi everyone, 
I went through a number of documentations, trying to update live speed with no luck. 

I ran the command `valhalla_ways_to_edges --config valhalla.json` to get a mapping between OSM way and Valhalla edge.
I then put some sample data in a csv file inside the `speeds` folder as follows:
<pre>
194313962073,1,1
63820776025,1,1
</pre>

In order to update live speed, I ran `valhalla_add_predicted_traffic -c valhalla.json -t speeds/` 
and below is the output I'm getting: 
<pre>
2021/06/27 20:17:27.653644 [INFO] Adding predicted traffic with 4 threads
2021/06/27 20:17:27.653689 [INFO] Parsing speeds from 0 tiles.
2021/06/27 20:17:27.653889 [INFO] Parsed 0 constrained traffic speeds.
2021/06/27 20:17:27.653905 [INFO] Parsed 0 free flow traffic speeds.
2021/06/27 20:17:27.653920 [INFO] Parsed 0 compressed records.
2021/06/27 20:17:27.653928 [INFO] Updated 0 directed edges.
2021/06/27 20:17:27.653933 [INFO] Duplicate count 0.
2021/06/27 20:17:27.653937 [INFO] Finished
</pre> 

How come live speeds are not updating? What am I missing? 
In the config I have the following:
<pre> 
    "tile_dir": "/root/valhalla/tiles/valhalla_tiles",
    "tile_extract": "/root/valhalla/tiles/valhalla_tiles.tar",
    "timezone": "/root/valhalla/tiles/valhalla_tiles/timezones.sqlite",
    "traffic_extract": "/data/valhalla/traffic.tar",
    "transit_dir": "/data/valhalla/transit",
</pre> 

I read in one of the existing issues that one needs to unset `tile_extract` so I tried both leaving it blank and removing it altogether with no luck. I'm really stuck and don't know what else to do.
Can anybody help please? 

I look forward to your assistance. 
Thanks

**Comment by nilsnolde** [comment]
There's 2 modes of traffic Valhalla supports: live & historical traffic data. You were actually going for the workflow of the latter (predicted as in "what will traffic be in 2 days from now", you can only achieve that with fixed patterns like historical data).

I recently went through the process of creating predicted traffic tiles for TomTom data, so let me know if you need support on that.

But more likely you'll want live traffic, which is a bit more involved. Never did it myself, but AFAIU you'd basically have another process (in your favorite language) updating live traffic tiles with updated speeds every now and then, you write those tiles to the `traffic_extract` tar file and valhalla picks up the updates automatically. So the challenge is to write those (binary) traffic tiles in the format valhalla expects, for that see its [header](https://github.com/valhalla/valhalla/blob/0d2187fc63cc9910d2a77b437a944629ebe7e6ac/valhalla/baldr/traffictile.h). That should be enough to get you going if you really want it.

**Comment by nilsnolde** [comment]
It’s a bit confusing: there’s live speed and there’s historical traffic patterns. The workflow you went through is for the latter. I recently went through the entire thing myself for TomTom traffic. Let me know if you want support on that.

for live traffic, it’s unfortunately not that easy: you’d have to have a look at the binary layout of the expected traffic tiles and generate them yourself from the data you have. The good thing at Valhalla is they also follow the tiling scheme, so you can fairly easily get meaningful update cycles for large regions, eg

**Comment by kitindir** [comment]
@nilsnolde Thank you very much for your comment.

You're right, what I want is live traffic and not predicted speed.
It's just that, in the issue [#2006](https://github.com/valhalla/valhalla/issues/2006) it was confirmed that it worked; so I wasn't sure what was going wrong with my workflow.

What I would like to achieve is to get a different route from A to Z after updating slow speeds along the first route that was calculated by Valhalla. I've never had a chance to look at [the header of traffictile](https://github.com/valhalla/valhalla/blob/0d2187fc63cc9910d2a77b437a944629ebe7e6ac/valhalla/baldr/traffictile.h).
Is that file the only resource that we have on live traffic? Is there any documentation on how to use this?

**Comment by kitindir** [comment]
Just to add on this. If it worked as confirmed in the issue #2006 so why traffic speeds are not updating for me?
Maybe if traffic speeds were updating for me, I would be able to know for certain whether or not this would do for now for what I'm looking for.

**Comment by nilsnolde** [comment]
Oh I guess it works, it's live on Mapbox infrastructure I bet. That issue is quite old, a LOT changed since then on the traffic front..

I feat that's the only "documentation" out there, partly bcs it's really not that old, I think the plan was to do a more proper documentation at some point, after the dev dust settled. That might actually already be the case, it's a chore topic though to update that kind of documentation, so priority is very low. In any case, you'd still have to write your own tile update process. 

For now (and if you're c++ savvy enough) you can try to follow the comments in the header file and sorta derive how it's used from the surrounding logic using the traffic tiles, e.g. the layout here: https://github.com/valhalla/valhalla/blob/0d2187fc63cc9910d2a77b437a944629ebe7e6ac/valhalla/baldr/traffictile.h#L204-L209

**Comment by kitindir** [comment]
@nilsnolde Thank you, I'll have a look at your suggestion.

**Comment by kitindir** [comment]
@nilsnolde Thank you, I'll definitely have a look at your suggestion.

I'm still wondering why predicted speeds are not updating for me, if somebody could assist please.
Now I understand that it's a complete different issue from live traffic, which I'm looking for, but for now I cannot comment much on live traffic as I haven't even had a go at it.

**Comment by nilsnolde** [comment]
You actually did the right thing already, just with the wrong input.

What you need:
- historic traffic data with 5 mins speed bins for every day of the week

The sequence is:
- build the routing tiles
- valhalla_ways_to_edges.cc gives you the osm -> edge id map
- loop through all the traffic edges you have, the above map will tell you which valhalla tile the edge goes to (edge ids have information about tile level & tile id)
- create one csv per routing tile in the same structure, you can see one example csv in the tests: https://github.com/valhalla/valhalla/blob/master/test/data/traffic_tiles/0/003/196.csv (columns: edge_id, freeflow (night), constrained (average day speed), a DCT-II encoded base64 string of all 2016 speed bins (every 5 mins in 7 days)
- then run valhalla_add_predicted_traffic to bake the historical data in the graph itself (the routing tiles)

Main challenge here: creating the [DCT-II](https://en.wikipedia.org/wiki/Discrete_cosine_transform#DCT-II) encoded speeds. You could port this repo's implementation (I did it that way): https://github.com/valhalla/valhalla/blob/89db5fc1500ed00ef0be4f04980e38776d3366ec/src/baldr/predictedspeeds.cc#L54

There's probably a whole other host of challenges you'll face if you're not too familiar with valhalla, I think you'll have to dive in yourself a little more and learn some about the structures it uses, like what the GraphId represents.

Do note though you won't have dynamic updates on speeds (i.e. not live!); this is a one-time operation and baked into the graph.

**Comment by nilsnolde** [comment]
BTW, if you don't have historical data with granularity (i.e. temporally differing speeds), then this exercise is pretty pointless anyways. In the case where you simply want to alter the speed an edge is assigned the by far simplest is to change the base data you're working with (OSM I assume) and then build the graph from it. Traffic patterns are really meant to be used for `arrive by/depart at` kind of situations, where speeds change according to time of day.

**Comment by nilsnolde** [comment]
I'll close for now, as the problem is not with the repo (other than better documentation). Feel free to continue to ask questions here though

**Comment by alinmindroc** [comment]
Hi,

I have created a docker image with instructions on how to add traffic to Valhalla: https://github.com/alinmindroc/valhalla_traffic_poc
Currently only shows how to add traffic as predicted speeds, hopefully live traffic coming too at some point.

The repository contains instructions on how to add traffic based on how it traffic support is implemented at the moment in Valhalla. 
I understand this might change and that's one of the reasons there are no official docs for it. But the lack of step-by-step instructions almost made me abandon the project, so hopefully this will help someone else.



Thanks @nilsnolde for describing how predicted speeds work: https://github.com/valhalla/valhalla/issues/3180#issuecomment-869502204
