### ISSUE TITLE
Avoid polygons

### ISSUE THREAD

**Issue by EVOX-TECHNOLOGIES** [valhalla/valhalla#3182]
The algorithm can't calculate a path, however when I take a polygon it can calculate the path here, everything normal if this polygon affected the path, I leave the example images here: 

Image with Polygons:
![notwork](https://user-images.githubusercontent.com/60399171/123781994-c1b93300-d8cc-11eb-93c8-e1085a31f9c4.png)

Image without Polygons:
![work](https://user-images.githubusercontent.com/60399171/123782068-d1d11280-d8cc-11eb-8a17-3e5e2d4ab040.png)

And my request:

{
	"directions_type": "maneuvers",
	"avoid_polygons": [
		[
			[-8.899850490212819, 39.13892207569951],
			[-8.899855854630864, 39.13892415606849],
			[-8.899920227647314, 39.13891167385339],
			[-8.900242092729133, 39.14053226293175],
			[-8.900164308667662, 39.14054474485951],
			[-8.900000693917733, 39.139745897023865],
			[-8.899829032540767, 39.138930397175216],
			[-8.899850490212819, 39.13892207569951]
		],
		[
			[-8.90089085203469, 39.13890553686528],
			[-8.900890852034703, 39.138823362220464],
			[-8.901337439835736, 39.138843125751414],
			[-8.901637847245356, 39.13839480429094],
			[-8.90171026688879, 39.13841248755808],
			[-8.901405836165658, 39.13892113963512],
			[-8.900937790692456, 39.1389044966805],
			[-8.90089085203469, 39.13890553686528]
		]
	],
	"costing": "auto",
	"locations": [{
		"name": "startPlace",
		"lon": -9.1485128705079,
		"type": "break_through",
		"lat": 39.188744520260286
	}, {
		"min_road_class": "residential",
		"name": "firstStopPoint",
		"lon": -8.90767222222222,
		"type": "break",
		"lat": 39.1243722222222,
		"preferred_side": "opposite"
	}, {
		"name": "enPlace",
		"lon": -9.1485128705079,
		"type": "break_through",
		"lat": 39.188744520260286
	}],
	"language": "pt-PT",
	"costing_options": {
		"auto": {
			"service_penalty": 0,
			"use_highways": 1,
			"use_tolls": 1,
			"top_speed": 120,
			"use_tracks": 0,
			"use_living_streets": 0,
			"shortest": true
		}
	}
}

Is there any way to overcome this?
Thanks

**Comment by nilsnolde** [comment]
yeah, I can reproduce with mapbox's api.. seems weird. your route is a roundtrip, but off the top of my head nothing comes to mind that would cause this.

a fair warning: I'm super busy right now, so unless you want to financially sponsor the bug fix (or no one else jumps at this issue), this will take a while to get sorted.

**Comment by nilsnolde** [comment]
btw, did you build valhalla yourself or are you using someone else's? which commit did you build? there's been some fixes to avoid_polygons recently (2-3 weeks ago)..

**Comment by EVOX-TECHNOLOGIES** [comment]
yes it was built by me and the version I am using is 3.1.2. thanks

**Comment by nilsnolde** [comment]
sadly that fix made it into 3.1.2

**Comment by nilsnolde** [comment]
@EVOX-TECHNOLOGIES feel free to try #3194 , that should fix it.
