### ISSUE TITLE
googletest not actually updated

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3186]
PR #3166 should've updated googletest from commit [d166e09483845b9b6a658dccc3d3dbb293676b62](https://github.com/google/googletest/commit/d166e09483845b9b6a658dccc3d3dbb293676b62) to 
[e2239ee6043f73722e7aa812a459f54a28552929](https://github.com/google/googletest/commit/e2239ee6043f73722e7aa812a459f54a28552929), but seems it didn't: in https://github.com/valhalla/valhalla/tree/master/third_party there's still the old commit referenced.

cc @PureW

**Comment by PureW** [comment]
It was updated, but then was downgraded again in https://github.com/valhalla/valhalla/pull/3168 it seems.
