### ISSUE TITLE
clang 12.0 fails one avoids test

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3195]
One of the avoid_* tests seems to fail on clang 12.0, ref https://github.com/valhalla/valhalla/pull/2750#issuecomment-871672316

**Comment by nilsnolde** [comment]
@PureW just wanted to reproduced this on arch with the same toolchain you used, but for me this works fine, no failing test. maybe try a fresh build? no idea what else could cause this..

**Comment by PureW** [comment]
Yup, blew away the build folder and built 22d32a963 from scratch. Still see the failure. @ktatterso is also experiencing it on his macbook I believe.

**Comment by nilsnolde** [comment]
Hm.. I just had a fresh clang install. Veery strange..

**Comment by PureW** [comment]
Fixed for me in https://github.com/valhalla/valhalla/pull/3301
