### ISSUE TITLE
Tile Cache as a Memory Map

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#32]
(2015-10-16T18:00:17Z) @kevinkreiser : originally created valhalla/baldr#203

Currently we load tiles on demand into a memory cache from disk. It turns out that we often max out disk iops well before the CPU. Basically we aren't able to feed the CPU route network data fast enough.

A while back we spent a bunch of R&D trying to figure out how to make a shared (amongst processes) cache for tiles. It turns out that really all approaches were slower than just reading the tile off the disk into memory and keeping it there for as long as you can. So that is what we do. Today.

So why were the previous approaches not good? Well, fundamentally our data is lots of little pieces (tiles) of a larger route network. Only 2% of all the tiles are larger than 1mb. The median tile is likely in the 100k range. That is pretty small. So most of the approaches would take these small items, pump them into an off the shelf cache (think memcached or kyotocabinet) and then retrieve them from it when needed. Hard problems like, consistency, eviction and synchronization are handled by the cache of choice. This is really nice because it means you dont have to tackle hard problems, but... It's really slow... By and order of magnitude in the best case...

So we did more experiments, this time with memory maps. Memory maps are amazing. We use them for lots of stuff because they provide all the things we need: shared, opportunistic, in-memory caching controlled by someone else (namely the OS). The thing about memory maps though is that they are only really useful for reasonably large files. The tiles just dont fit the bill and again they are basically just marginally slower than the current approach of just reading them from disk.

So we are screwed, we have a crap ton of little tiles, and lets face it, little tiles are the coolest thing about Valhalla. They allow for arbitrary extracts, they should allow for arbitrary updates, they make searching the data easier because you dont have to keep an index (they are the index), they may make associating other data easier as well. So yeah, there is nothing to do. Not exactly.

What if we just cram all the tiles into one file. They are still tiles, so you can still reference them individually but instead of referencing them by file name, you can reference them by a byte offset from the beginning of the file. Sure, we'd need to keep an index of what tiles are where within the file but we can scan through 35gb of planet data, in what, a minute on modern hard drives. We could even arrange the tiles within the file so that tiles close to each other in space are close to each other in the file. The good news is, we still have tiles. Which means we can still serve up individual tiles (either from the one large one) or as singular items on the disk/s3. But the even better news is that we can memory map the massive file and let the os handle which bits (tiles) are actually in memory at any one time. And because its shared amongst processes we can keep more in memory at any one time without wasting the overlap.

The best bit about all of this is that we wouldnt need to change much of the code. `GraphTileReader` would simply still return `const GraphTile*`. We would need two things:
- a little program that could:
  - write an index header followed by all the tiles into one big fat file
  - break the big fat file back into files on disk
- add to `GraphTileReader` to detect the big fat file and change its mode of operation accordingly

(2016-02-02T14:17:52Z) @dnesbitt61 : Might consider breaking into separate files based on hierarchy level.

(2016-02-02T15:24:47Z) @kevinkreiser : Yep totally!

**Comment by maestroIgor** [comment]
@kevinkreiser Could you please leave some comments why this issue was closed.

**Comment by kevinkreiser** [comment]
@maestroIgor because we completed this task! the code supports mmap'ing a tar of tiles. if you read the readme we in fact suggest that you run the service this way: https://github.com/valhalla/valhalla/#running
