### ISSUE TITLE
Fast Fail Impossible Routes Seems Broken

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3202]
Recently I tried to do this:
![image](https://user-images.githubusercontent.com/697548/124982388-a2c14c00-e004-11eb-9d5f-6f7aa865cf51.png)

This should result in an immediate 400 and a message about how the locations are in disconnected regions however i saw this:
![image](https://user-images.githubusercontent.com/697548/124982458-b8cf0c80-e004-11eb-8bad-e238523a6aca.png)

This request should never make it to thor so long as loki is using the connectivity map so i checked my config and:
![image](https://user-images.githubusercontent.com/697548/124982561-d56b4480-e004-11eb-8c3e-75520be8a550.png)

It looks like it should be!

**Comment by kevinkreiser** [comment]
Debugging this a bit more it looks like the code actually does think both europe and the US are the same color in the connectivity map... Which makes me suspect data which makes me wonder how long its been this way...

**Comment by kevinkreiser** [comment]
ah yeah that is borked...
![image](https://user-images.githubusercontent.com/697548/124983762-60007380-e006-11eb-883e-caba802608e4.png)

everything is connected except a few lucky places like cuba madagasgar svalbard and a few places in polynesia

**Comment by PureW** [comment]
Seems like something we need to add a unittest for

**Comment by kevinkreiser** [comment]
newer data shows this problem while older data does not. the leading candidates are something changing either with the shape itself or with the binning of the shape. i might write small program to re-bin a tile set and have it log when the number of tiles touched by the shape is larger than some number

**Comment by kevinkreiser** [comment]
i modified `valhalla_export_edges` adding this to the top of the inner for loop:

```c++
      auto inf = tile->edgeinfo(tile->directededge(i));
      const auto& shp = inf.shape();
      const auto& l2 = TileHierarchy::levels().back().tiles;
      auto intersected = l2.Intersect(shp);
      if (intersected.size() > 20) {
        LOG_ERROR(encode(shp));
      }
```

and commenting out the other printing at the bottom of the loop and it printed out some very interesting findings (which ill turn into unit tests, FYI we have unit tests for this but its hard to test every permutation when you are talking about numerical precision):

```
2021/07/09 14:50:12.516705 [INFO] Enumerating edges...
2021/07/09 14:50:32.544482 [INFO] Exporting 711196788 edges
2021/07/09 14:50:32.545076 [INFO] 0%
2021/07/09 14:50:38.223657 [INFO] 1%
2021/07/09 14:50:42.220460 [INFO] 2%
2021/07/09 14:50:46.404522 [INFO] 3%
2021/07/09 14:50:50.169194 [INFO] 4%
2021/07/09 14:50:53.252195 [INFO] 5%
2021/07/09 14:50:56.790646 [INFO] 6%
2021/07/09 14:50:58.861963 [ERROR] {wvueB{knms@GdU
2021/07/09 14:51:00.423221 [INFO] 7%
2021/07/09 14:51:01.734418 [ERROR] }~etdBcnwfk@dE}YnS_oA|OwaAjAwIGudBEuD_Ey^wHwk@]mVxFss@eTu}G_Iuk@}@mZt@mW\sNcLueAN{PvXseBrFq\
2021/07/09 14:51:03.647848 [INFO] 8%
2021/07/09 14:51:07.071192 [INFO] 9%
2021/07/09 14:51:10.150014 [INFO] 10%
2021/07/09 14:51:10.619466 [ERROR] {d{gbBwdpsZ]s~AG}bAFqhAd@goA\_pAUq`B
2021/07/09 14:51:13.109038 [INFO] 11%
2021/07/09 14:51:16.111172 [INFO] 12%
2021/07/09 14:51:17.417675 [ERROR] eibz`Bc_ysVFse@
2021/07/09 14:51:19.068295 [INFO] 13%
2021/07/09 14:51:19.142529 [ERROR] uhbz`BziwcnEUgyl@
2021/07/09 14:51:20.436774 [ERROR] m{~s`B_qbfOu@rDiBxDqCbK]tH?dOd@v\t@x`@l@tZe@dU?bc@Lxh@NrTt@h[\nWN`WmAbTiB`V]vOyClTuDzT
2021/07/09 14:51:22.301245 [INFO] 14%
2021/07/09 14:51:22.842044 [ERROR] _qwg`Bkf}qQgN}g@kAkLiCs`@gCm_@_@wHEcHr@qKbBwK`CqM
2021/07/09 14:51:25.393081 [INFO] 15%
2021/07/09 14:51:28.683880 [INFO] 16%
2021/07/09 14:51:31.587902 [ERROR] cqsa~Aym}kSbBqH|c@ikBd@oH?aEm@eDaC}FwCiG}D}FkGeIyWeVwCgCcAqB}@uD{@gMe@wT_@_UN{I
2021/07/09 14:51:31.865648 [INFO] 17%
2021/07/09 14:51:35.368050 [INFO] 18%
2021/07/09 14:51:38.897027 [INFO] 19%
2021/07/09 14:51:42.062385 [INFO] 20%
2021/07/09 14:51:45.834290 [INFO] 21%
2021/07/09 14:51:49.293962 [INFO] 22%
2021/07/09 14:51:50.489606 [ERROR] swk{yAm{vp\fIiKtJ}[bU}_AbW{{AdEyXl@cNGagAqBut@wD_t@{F}{@wCmy@aCca@mEyYcFyQ
2021/07/09 14:51:51.813468 [ERROR] o_}tyAfwu_iC{FqaDkQgaBiCgaBlEed@rLiWhu@cp@pHk`@t@ce@kLumAav@skDkQ?{P|_@eTlgAaShXuThBipA_s@ag@mJw\aRyRia@uEoSOkqDcKi_Bz_@y_AeE}Tst@qq@kFaSm@mJnNia@L}i@{Jsd@{Vyk@cj@_J_JwNk[wfEyV{k@afAijAcL_^iC_Tf@ce@dYaaEqB}_@
2021/07/09 14:51:53.208868 [INFO] 23%
2021/07/09 14:51:56.824627 [ERROR] wqkdxA_cbeeAG|E
2021/07/09 14:51:56.877365 [INFO] 24%
2021/07/09 14:51:56.951873 [ERROR] q_lgxAkorvq@ud@|}@}@lEEfCLpCd@`CdKnNrPhW|~@|tAv\zg@
2021/07/09 14:52:01.241573 [INFO] 25%
2021/07/09 14:52:05.674697 [INFO] 26%
2021/07/09 14:52:09.482395 [INFO] 27%
2021/07/09 14:52:13.353483 [INFO] 28%
2021/07/09 14:52:17.812729 [INFO] 29%
2021/07/09 14:52:22.010991 [INFO] 30%
2021/07/09 14:52:26.050377 [INFO] 31%
2021/07/09 14:52:29.522488 [ERROR] qbjvpAjpjlcDwDcG{AuEUuEFwMGya@O{~@e@orA]mT
2021/07/09 14:52:30.087014 [INFO] 32%
2021/07/09 14:52:33.981525 [INFO] 33%
2021/07/09 14:52:38.267821 [INFO] 34%
2021/07/09 14:52:42.347034 [INFO] 35%
2021/07/09 14:52:46.080940 [INFO] 36%
2021/07/09 14:52:49.897311 [INFO] 37%
2021/07/09 14:52:52.437690 [ERROR] ehtwkAznrdgELxhB^|@z@z@~eBkAnDm@`CM
2021/07/09 14:52:53.872265 [INFO] 38%
2021/07/09 14:52:57.414984 [INFO] 39%
2021/07/09 14:52:58.579972 [ERROR] uvwijArilewCiCaHmEqGsLl@yLz@}IiBiMOaSfDsPbFkFjBmEtEkB~HFxzE
2021/07/09 14:53:01.321809 [INFO] 40%
2021/07/09 14:53:05.153980 [INFO] 41%
2021/07/09 14:53:09.098028 [INFO] 42%
2021/07/09 14:53:13.101198 [INFO] 43%
2021/07/09 14:53:16.869287 [ERROR] c}kweA~|lpNNnAu@`GgDfG{AdEe@fC{@dAkAZsAA}@cAqBeEwHkQuEmHyBsDe@mD
2021/07/09 14:53:17.242358 [INFO] 44%
2021/07/09 14:53:21.358480 [INFO] 45%
2021/07/09 14:53:23.087918 [ERROR] u`sidA`nzecF]m@W{AMkBF_S
2021/07/09 14:53:25.074407 [INFO] 46%
2021/07/09 14:53:28.329311 [INFO] 47%
2021/07/09 14:53:32.011968 [INFO] 48%
2021/07/09 14:53:35.655795 [INFO] 49%
2021/07/09 14:53:39.503417 [INFO] 50%
2021/07/09 14:53:43.024460 [ERROR] {{at_Ajmkj`F]o|@O{_@?O?aRNekCz@eFbBiBbFkAly@}@jL??g`BlJen@r@m@d~@cz@
```

Those are the encoded polylines, and as you may have guessed are pretty simplistic little shapes. When you plot them a pattern emerges:

![image](https://user-images.githubusercontent.com/697548/125097555-40b82380-e0a4-11eb-9153-9568d6b6111f.png)
![image](https://user-images.githubusercontent.com/697548/125097576-46156e00-e0a4-11eb-8bea-a51e254847d4.png)
![image](https://user-images.githubusercontent.com/697548/125097598-4b72b880-e0a4-11eb-9255-f9ef86a40edb.png)


They all have a section that is perfectly horizontal (at least by eye). Anyway ill keep working on this.

**Comment by dnesbitt61** [comment]
For the first shape ({wvueB{knms@GdU) I see this when adding some logging to the Bresenham computation in tiles.cc:

2021/07/09 17:46:46.580390 [INFO] x0= 4150.004760y0= 2876.999960x1= 4149.997660y1= 2877.000040
2021/07/09 17:46:46.580395 [INFO] x= 4150 y= 2877 tile_row= 575 tile_column= 830
2021/07/09 17:46:46.580400 [INFO] sx = -1.000000 sy= -1.000000
2021/07/09 17:46:46.580404 [INFO] dx = -0.007324 **dy= 0.000000**
2021/07/09 17:46:46.580409 [INFO] x = 4150.500000 y= 2877.500000

It computes dy as 0, so the y pixel value never changes and it never triggers the end pixel. Changing the bresenham code to use double precision seems to fix this one case. Why was so much logic changed to use double precision? This all seemed to work before that.

**Comment by kevinkreiser** [comment]
I started a new section in the intersect unit test for the cases that I logged. I'll try the chnage to double and also see if I can't numerically protect against it once I relearn my code from years ago haha
