### ISSUE TITLE
Map Matching ignores most of the route

### ISSUE THREAD

**Issue by tima0900** [valhalla/valhalla#3210]
I send a trace_attributes request to the http server and it ignores most of the waypoints I supply and creates a really short route.
![image](https://user-images.githubusercontent.com/5970376/125625365-c4235c92-19e9-49b1-b552-ad47364ce58c.png)
Thre red line are the source waypoints and the blue line is the result I get from the server. Is there something wrong with my setup/config/request or is this a bug? I used the docker image from https://hub.docker.com/r/gisops/valhalla for testing.
Relevant part of the Valhalla config:
```
"meili": {
    "auto": {
      "search_radius": 50,
      "turn_penalty_factor": 200
    },
    "bicycle": {
      "turn_penalty_factor": 140
    },
    "customizable": [
      "mode",
      "search_radius",
      "turn_penalty_factor",
      "gps_accuracy",
      "interpolation_distance",
      "sigma_z",
      "beta",
      "max_route_distance_factor",
      "max_route_time_factor"
    ],
    "default": {
      "beta": 3,
      "breakage_distance": 2000,
      "geometry": false,
      "gps_accuracy": 5.0,
      "interpolation_distance": 10,
      "max_route_distance_factor": 5,
      "max_route_time_factor": 5,
      "max_search_radius": 100,
      "route": true,
      "search_radius": 50,
      "sigma_z": 4.07,
      "turn_penalty_factor": 0
    },
    "grid": {
      "cache_size": 100240,
      "size": 500
    },
    "logging": {
      "color": true,
      "file_name": "path_to_some_file.log",
      "type": "std_out"
    },
    "mode": "auto",
    "multimodal": {
      "turn_penalty_factor": 70
    },
    "pedestrian": {
      "search_radius": 50,
      "turn_penalty_factor": 100
    },
    "service": {
      "proxy": "ipc:///tmp/meili"
    },
    "verbose": false
  }
```
And the request:
[request.txt](https://github.com/valhalla/valhalla/files/6816145/request.txt)

**Comment by kevinkreiser** [comment]
it looks like a bug to me but i have to try it myself to confirm. can you try removing the location types and times and see if just lat lons in each location does any better?

**Comment by tima0900** [comment]
Removing the location types and times(also tried only with types and only with times in addition to lat/lon) doesn't change the result.

**Comment by kevinkreiser** [comment]
Do the ways in OSM there have bike access?

**Comment by kevinkreiser** [comment]
We should reformat your request on geojson so we can look at it on geojson.io

It looks like there are a lot of paths around we'd have to check for bike access or whther or not they are close enough to your original input

**Comment by tima0900** [comment]
I created a [geojson.txt](https://github.com/valhalla/valhalla/files/6816997/geojson.txt) of the input.
But I don't know what to do at the mentioned website.

I am not 100% sure if every way in OSM has bike access but they should have. Is there an"easy" way to check that? I am sure that the ways directly after where Valhalla is turning around are bike accessible.

**Comment by mandeepsandhu** [comment]
> I created a [geojson.txt](https://github.com/valhalla/valhalla/files/6816997/geojson.txt) of the input.
> But I don't know what to do at the mentioned website.
> 

Copy the contents of your file above into the left-pane on geojson.io. By default the left-pane shows:
```json
{
  "type": "FeatureCollection",
  "features": []
}
```

**Comment by tima0900** [comment]
So I did some more test and it seems when I remove some locations at the start of the trace Valhalla suddenly is able to create a proper match. So for me it seems like there is an issue if the start of the route and the end of the route are close together. I'll try to apply some filters for my input data which will remove groupings of locations at the start of the route(happens when you start tracking before moving) and see if this solves the problem or if not if there must be a specific distance between the first and last location for it to work(e.g. I'll remove more and more points at the start of the input until it works).

This is the start of the route after I deleted a bunch of points at the start:
![image](https://user-images.githubusercontent.com/5970376/125766348-f3b59bc7-e52d-4d35-9815-81b503f3d95d.png)

And this was the start of the route before:
![image](https://user-images.githubusercontent.com/5970376/125766503-a51626f8-ca94-4764-ad92-1a1da1d19925.png)

So I am pretty sure it can't be because of any bike access issues in the OSM data as the turn around in the original route happens after the start of the working trace.

**Comment by tima0900** [comment]
So reducing the grouping at the start and end of the trace doesn't help. Which seems logically as the `interpolation_distance` should take care of that as well. What helps is if the start and end of the trace are not on the same OSM way( https://www.openstreetmap.org/way/727115954#map=18/49.97234/11.55223 ).

**Comment by kevinkreiser** [comment]
@tima0900 i agree that that seems like the cause, starting and ending in the same place but knowing the algorithm i cant see how that could be the case! its time for some debugging :smile:

**Comment by tima0900** [comment]
Some more information:
If I set `shape_match = map_snap` it also works, so it seems that the `edge_walk` algorithm is returning a match which doesn't really fit the input data and prevents the  `map_snap` algorithm to find a better route with the option `walk_or_snap`.
I'll call Valhalla with `map_snap` from now on as the speed penalty isn't really relevant to me.

**Comment by kevinkreiser** [comment]
Oh I completely missed that detail. The shape walking algorithm only works with exact shape matches meaning your input shape must exactly match the road geometry that the server has. The docs should explain this if they don't we should update them
