### ISSUE TITLE
Remove "bg::correct" again

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3217]
ref https://github.com/valhalla/valhalla/pull/3194#discussion_r665346192

now I know why I initially removed the `bg::correct`: it's not available on older boost versions. I use debian 9 (i.e. boost 1.62) to build the python bindings, which fails right now..

guess we'll have to revert that change and make it more explicit in the docs that clockwise winding is needed for `exclude_polygons` to work..

**Comment by kevinkreiser** [comment]
i believe we already have the winding check in the isochrones code for when we generate polygons. we should just make that code re-usable and use it here as well. (i didnt go check the code but im pretty sure)

**Comment by kevinkreiser** [comment]
https://github.com/valhalla/valhalla/pull/2932

**Comment by kevinkreiser** [comment]
https://github.com/boostorg/geometry/blob/815de96b84751e9df12a202d4847f71b8b682288/include/boost/geometry/algorithms/correct.hpp#L127-L155

check if the ring is closed having the first and last point duplicated and then check the sign of the area, and if its the wrong sign, reverse the order of the points.

**Comment by nilsnolde** [comment]
jup, I'll see that I can quickly implement that.

**Comment by nilsnolde** [comment]
@kevinkreiser bg::area is also not available :roll_eyes: : https://github.com/valhalla/valhalla/pull/2750#issuecomment-751244718

Is it ok for now if I leave a TODO? I did write a sentence about it in the docs for now.

**Comment by kevinkreiser** [comment]
i think we can just use the shoelace formula, if you want to set it up and leave a TODO in there i can help you implement it. we could even merge the PR with the TODO in it and just update the docs if this is blocking you at the moment

**Comment by nilsnolde** [comment]
it is indeed a little blocking atm with little time to spare.. ah never mind, just found the implementation from #2927 :) should work out-of-the-box, let me quickly check

**Comment by kevinkreiser** [comment]
ah y eah that was the one i was trying to remember, i knew someone recently reimplemented that
