### ISSUE TITLE
Map match with wrong turn direction and Uturn

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#3230]
Found an issue with map matching where an incorrect turn type is generated followed by an immediate Uturn. Rather than turning right, the instructions say to turn left then make a Uturn to stay on the road. The distance of the turn left step/maneuver is 1 meter. A route request correctly calls out a right turn.

Request:
http://localhost:8002/trace_route?json={"shape":[{"lat": 39.906110, "lon": -76.014600},{"lat": 39.906020, "lon": -76.014340},{"lat": 39.905970, "lon": -76.014160},{"lat": 39.905830, "lon": -76.012840},{"lat": 39.905820, "lon": -76.012580},{"lat": 39.905780, "lon": -76.012130},{"lat": 39.905730, "lon": -76.011440},{"lat": 39.905720, "lon": -76.011290},{"lat": 39.905680, "lon": -76.010740},{"lat": 39.905660, "lon": -76.010540},{"lat": 39.905360, "lon": -76.010720},{"lat": 39.904880, "lon": -76.010970}],"shape_match":"map_snap", "costing":"bicycle"}

Result (with a dataset from July 2021) includes these maneuvers/steps:
{
    "type": 15,
    "instruction": "Turn left onto Mount Pleasant Road.",
    "verbal_transition_alert_instruction": "Turn left onto Mount Pleasant Road.",
    "verbal_pre_transition_instruction": "Turn left onto Mount Pleasant Road. Then Make a left U-turn to stay on Mount Pleasant Road.",
    "verbal_post_transition_instruction": "Continue for less than 10 meters.",
    "street_names": [
        "Mount Pleasant Road"
    ],
    "time": 4.0,
    "length": 0.001,
    "cost": 22.75,
    "begin_shape_index": 11,
    "end_shape_index": 12,
    "verbal_multi_cue": true,
    "travel_mode": "bicycle",
    "travel_type": "hybrid"
},
{
    "type": 13,
    "instruction": "Make a left U-turn to stay on Mount Pleasant Road.",
    "verbal_transition_alert_instruction": "Make a left U-turn to stay on Mount Pleasant Road.",
    "verbal_pre_transition_instruction": "Make a left U-turn to stay on Mount Pleasant Road.",
    "verbal_post_transition_instruction": "Continue for 100 meters.",
    "street_names": [
        "Mount Pleasant Road"
    ],
    "time": 33.449,
    "length": 0.095,
    "cost": 144.828,
    "begin_shape_index": 13,
    "end_shape_index": 17,
    "travel_mode": "bicycle",
    "travel_type": "hybrid"
},

**Comment by kevinkreiser** [comment]
there was a unit test like this already that is commented out that exposed this. id have to see if i can find it but there is a test that just goes back and fourth with a multipoint route and changes the location t ypes to get different narrative and i remember seeing this bug there too with the uturns.

**Comment by dnesbitt61** [comment]
This is before TripLegBuilder. In FormPath (thor/map_matcher.cc) I printed out some info on the edge_segments. I see these:

```
2022/07/08 11:11:30.886542 [INFO] DWN - add edge_id 3202 length= 412.000000 de length 412 transition cost= 0.686250
2022/07/08 11:11:30.886547 [INFO] DWN - add edge_id 2565 length= 0.164100 de length 42 transition cost= 27.875000
2022/07/08 11:11:30.886551 [INFO] DWN - add edge_id 41138 length= 0.164100 de length 42 transition cost= 136.875000
2022/07/08 11:11:30.886555 [INFO] DWN - add edge_id 2563 length= 47.000000 de length 47 transition cost= 51.478127
```
The middle 2 in this list show the short Uturn edges. If I remove the shape location at the intersection ({"lat":40.105040,"lon":-76.236550}) from the request then the result is correct. Perhaps there is an issue finding candidate edges when at a node?

**Comment by kevinkreiser** [comment]
yep or maybe a problem in how it decides to use those candidates. i wonder whether this is a recent issue or a longer term one. it seems like we would have noticed this in earlier implementations. makes me want to run git bisect to see if a particular change caused it. at any rate, its a bug or a regression
