### ISSUE TITLE
Bug: Bus is not being routed down a road with access=no and bus=designated

### ISSUE THREAD

**Issue by grutts** [valhalla/valhalla#3231]
We discovered an issue where Valhalla is not routing a bus down a road, and is instead taking a detour around it. Happens on Valhalla 3.1.2

The road is marked as `access=no` and `bus=designated` (https://www.openstreetmap.org/way/240829576#map=17/55.94858/-3.21144)

For a minimal example, you can try to route from [55.947865, -3.213393] to [55.948947, -3.211037].
A slightly larger example would be routing from [55.947053, -3.215223] to [55.950133, -3.208083]

I would expect the bus to be routed straight down the road, but it is not.

According to taginfo.json Valhalla should be processing "bus=designated" roads, in my understanding. https://github.com/valhalla/valhalla/blob/42ed61c7c1e081765f8b00f69917f5e9ae7ee224/taginfo.json#L844

I also checked to be sure that "bus=designated" was a commonly used tag. Confirmed by the following queyr
http://overpass-turbo.eu/s/19Eb

**Comment by kevinkreiser** [comment]
we probably just dont handle that combo properly in lua?

https://github.com/valhalla/valhalla/blob/master/lua/graph.lua#L1768-L1785

looking at the code it seems like it should work though! it pulls out designated and then looks up the value for that in a map up above and should get the proper mask:

https://github.com/valhalla/valhalla/blob/master/lua/graph.lua#L575

i didnt check to see if 64 is the proper mask though on the other side in the c++ code..

**Comment by gknisely** [comment]
@kevinkreiser @grutts this issue has nothing to do with the lua.  It seems that all motor vehicle access was shut off for https://www.openstreetmap.org/way/234820637 and only taxis can get through.  @grutts I assume you are more familiar with this area.  What should the access be on this way?  

![Screenshot from 2021-08-02 17-39-19](https://user-images.githubusercontent.com/2676277/127927217-bc8a96a0-f853-4051-9766-15af1f53df17.png)

**Comment by grutts** [comment]
Thanks @gknisely and apologies for the false alarm. I've added a `bus=designated` tag to the way
