### ISSUE TITLE
Optimized Route service results not reasonable for more than 250 coordinates

### ISSUE THREAD

**Issue by mickael-bdias** [valhalla/valhalla#3242]
Hi!

When I use the 'Optimized Route' service for less than 200 coordinates, I do not found any problem with the solution.

The issues happen after I introduce more than 250 coordinates. 
The solution is not reasonable.

In September, 2019, someone had the same problem: [Issue_1947](1947).

Is it possible to configure the number of attempts and success of the thor/optimizer.cc onto valhalla.json for a next version?

I was trying to open a shell in the running container (but I do not known where the file is located) and changed with nano (if installed).

Anyone knows a workaround for that kind of situation?

Thank you!

**Comment by kevinkreiser** [comment]
@mickael-bdias it is not currently possible, but it wouldnt be too difficult to add this. ive summarized this here: https://github.com/valhalla/valhalla/issues/2287#issuecomment-891186427

where we can continue to track this issue.
