### ISSUE TITLE
Using Valhalla as a tile provider?

### ISSUE THREAD

**Issue by vinnytwice** [valhalla/valhalla#3252]
I'm looking at the the docs but I can't find out how to serve tiles to use for my app's map. Is it even possible?
Many thanks. 
Vincenzo

**Comment by kevinkreiser** [comment]
@vinnytwice we dont ship a tile server with the project at the moment. honestly though you can run one with very minimal effort. go to the directory where your tiles are written and then run `python3 -m http.server 8000`. this will run an http server that will give your application access to the tiles on port `8000`. so you can get a tile with eg.: `http://localhost:8000/1/051/336.gph` (assuming that tile is in the tile set you built). then all you need to do is configure your application to hit that tile server by adding your to  config this bit: https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_config#L294

which is terribly documented frankly, and should show an example format: `http://localhost:8000/{tilePath}`

**Comment by kevinkreiser** [comment]
rereading your question, it kind of sounds like you mean the visual map, valhalla does not (yet) support that.

**Comment by vinnytwice** [comment]
@kevinkreiser many thanks for answering. Indeed I need to serve mapas tiles ( vector ) for map visualization.  I will serve them from my node server app, which uses valhalla for routing. So it look like serving tiles is on the roadmap right?

**Comment by kevinkreiser** [comment]
> it look like serving tiles is on the roadmap right

in short yes but its a long way off from now most likely. i would really love to work on this in my free time and started to do so some 2 years ago but didnt end up pushing up anything interesting. the place we can track this work will be over in issue #1703
