### ISSUE TITLE
Question: How to call Loki's function from Thor

### ISSUE THREAD

**Issue by ismailsunni** [valhalla/valhalla#3255]
In my implementation of the Chinese Postman solver, I need to find the shortest route between several pairs of starting and destination locations. The shortest route's result should be in the list of edge graph id so that I can merge it with the other computed parts.

Unfortunately, calling the `route` function from this new function (CP) is not easy (as far as I know). First, I need to call `pimpl->loki_worker.route(request);` as I saw in `actor.cc`. How can I do it? Is it possible to call Loki's function as in here from Thor? 

I tried to see how other Thor works, like `optimized_route`. It doesn't call the Loki from Thor but calls it in `actor.cc`. The problem is, in my case, the list of starting and destinations location is not yet known until I ran some algorithm in CP.

Sorry, if I didn't explain it properly. I am open to discussion/questions to make it clear.

**Comment by kevinkreiser** [comment]
Yeah I feel like I've not quite understood your problem yet. If the question is, I have a bunch of edge ids and i want to find routes between them then the answer is you dont have to call loki at all, all you need to do is use those ids to create the same t ype of results that loki does before you call thor to find the path.

thors basic algorithms take a valhalla::Options object as their input. If you are this far you should already have such an object (hit has the costing model etc) but it probably doesnt have the locations just yet (this is what loki produces). if i were you i would just create the locations as loki does  directly from the edge ids. There are some examples of this but basically look at baldr/location and baldr/pathlocation. you can construct these from edge ids once you've done that you can then call pathlocation::toPBF to add it to the options object. we can screenshare so i can show you in more detail if you like, let me know if you'd like to set something up, cc @nilsnolde

**Comment by nilsnolde** [comment]
Thanks @kevinkreiser I pinged you on rocket. Tmrw I’ll have to go through a similar issue, I’ll see if I can come up with smth reg this issue as well.

**Comment by nilsnolde** [comment]
I think we mostly got the idea of providing the right objects to the algos. @ismailsunni will prepare a little flow chart of the high-level implementation for chinese postman as it currently is, which could still be good to discuss if you're up for it.

**Comment by kevinkreiser** [comment]
we synced externally, and can close this i  believe
