### ISSUE TITLE
fix doc for costing models

### ISSUE THREAD

**Issue by JackCaster** [valhalla/valhalla#3259]
The doc at https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md#costing-models-and-other-options are dead points to two dead links:
> Refer to the route costing models and costing options documentation for more on how to specify this input.

I believe they should point to https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#costing-models and https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#costing-options

**Comment by nilsnolde** [comment]
thx, link rot often goes unnoticed until someone points it out:)

feel free to PR yourself, no changelog or anything else necessary.
