### ISSUE TITLE
"avoid_polygons" not always working

### ISSUE THREAD

**Issue by jacobmolin** [valhalla/valhalla#3266]
Hi! Not sure if this is the proper spot to ask for help, but I'll give it a try. 

I'm having issues with Valhalla not always behaving as expected when "avoid_polygons" is set in the request.

The first issue is that Valhalla isn't avoiding/excluding all the polygons set in "avoid_polygons". In the first image the orange line is the first Valhalla route between two coordinates, without "avoid_polygons" key in request. The red (dashed) line is the new route between the same coordinates, with "avoid_polygons" key set to all 5 polygons (blue) in the request. 

![avoid_polygons1_crop](https://user-images.githubusercontent.com/34372356/129329522-1de86031-5dda-4c3f-8a42-872a752f8b59.png)
**Valhalla request 1**: http://localhost:8002/route?json={"locations":[{"lat":58.41006774460547,"lon":15.606112899975813},{"lat":58.386271522638594,"lon":15.648684062845575}],"costing":"auto","avoid_polygons":[[[15.609060512441545,58.4052012110549],[15.611825439467083,58.405455359464156],[15.610944720626236,58.403878003820836],[15.609060512441545,58.4052012110549]],[[15.623030000404242,58.40838796551],[15.62424405492564,58.40970541197214],[15.625337876047467,58.40730715533152],[15.623030000404242,58.40838796551]],[[15.614563342513492,58.405088062855384],[15.619145222733778,58.405789342811005],[15.61780831337316,58.40256404666442],[15.614563342513492,58.405088062855384]],[[15.608390927229692,58.40811391706427],[15.611347350933158,58.40836943999963],[15.608761167240743,58.406515441705494],[15.608390927229692,58.40811391706427]],[[15.63373610288258,58.422240553046265],[15.638368923273816,58.424742199990305],[15.640570492017616,58.42192028644277],[15.63373610288258,58.422240553046265]],[[15.637767074120859,58.3966541896728],[15.641443387225848,58.39931179797901],[15.640108496360597,58.393686676241344],[15.637767074120859,58.3966541896728]]]}

The second issue is that Valhalla avoids a polygon when it's not obstructing the original route.

![avoid_polygons2_crop](https://user-images.githubusercontent.com/34372356/129329549-1fc3f655-decc-4a92-94da-93be21def210.png)
**Valhalla request 2:** http://localhost:8002/route?json={"locations":[{"lat":58.4038066756371,"lon":15.621524547558693},{"lat":58.382176513187915,"lon":15.659753004894355}],"costing":"auto","avoid_polygons":[[[15.62084663661571,58.39357099094781],[15.62676149266764,58.39424287898075],[15.626496442964054,58.39173287177684],[15.62084663661571,58.39357099094781]]]}

The third issue is that Valhalla is giving me "Error: No path could be found for input" even though the polygon isn't obstructing the original route. Here the polygon is in orange.

![avoid_polygons3_crop](https://user-images.githubusercontent.com/34372356/129329567-4829c5ce-4018-456e-bbf9-696176c1cef2.png)
**Valhalla request 3:** http://localhost:8002/route?json={"locations":[{"lat":58.40435298766556,"lon":15.626638942354106},{"lat":58.3838372884089,"lon":15.655106734065384}],"costing":"auto","avoid_polygons":[[[15.65496274498716,58.39215710223414],[15.663665718828156,58.39299491524716],[15.658155035526306,58.388763411827966],[15.65496274498716,58.39215710223414]]]}

I've tried this for both the "auto" and "bus" costing profiles. I've also tried using "exclude_polygon" instead of "avoid_polygons", but that response never takes the polygons into consideration. 

I'm using:
- [gisops/valhalla:latest Docker image](https://hub.docker.com/layers/gisops/valhalla/latest/images/sha256-dfc49eab8775ccf5a328e56703aa0298041b6d3e7d060e20f77e7cb63159652d?context=explore) (I think it's v3.1.4, but I can't really tell) running locally.
- [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js)
- [Mapbox GL Draw](https://github.com/mapbox/mapbox-gl-draw)
- OSM data for Sweden from [Geofabrik](https://download.geofabrik.de/europe/sweden.html)

**Comment by nilsnolde** [comment]
oh boy.. really sorry @all in here that it's so buggy.. @jacobmolin I'll investigate soon-ish, latest end of next week.

shouldn't be a version problem unless you pulled the image weeks ago. is it a recent `latest`? if not, can you pull a fresh one and try again?

**Comment by nilsnolde** [comment]
some practical advice: you can trim the coords to 6 places, less data being posted

**Comment by jacobmolin** [comment]
Thanks! 

Yes, I pulled it today, 13 August 2021.

**Comment by kevinkreiser** [comment]
1. we need to look into how that is possible. hopefully a bug scrub and a unit test will fix this up
2. i suspect that is because removing edges from the graph changes the order of evaluation in the path finding, if you set alternates=1 does it give the other route back that you would expect? the other option is that the polygon intersection is selecting edges it shouldn't
3. looks similar to 1, there must be some edges selected which shouldnt have been


reading over all 3 it makes me think that we just have a bug in our polygon intersection logic. i think the best way for us to debug this would be a simlar tact as we've done before. add some debug code that converts the input polygons to geojson and also gets the shape of the supposedly intersected edges and turns those into geojson, then print this whole geojson blob out on the command line and throw it into geojson.io. once we do that we will be abel to visually tell what the hell is going on with the intersection

**Comment by nilsnolde** [comment]
yeah, at least we already have that to_geojson ifndef'd for trace logging. which I used the last time (also extended the unit tests), so I really wonder what's going again.. will look into it as soon as I have time
