### ISSUE TITLE
tunnels and bridges unit tests

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3267]
over in https://github.com/valhalla/valhalla/pull/3264 we finally added tests for tagged values support but unfortunately it was done in the old style. when doing data tests it is highly encouraged to use the gurka style. we should convert this test to gurka and when doing the new phoneme and layer tag support we should do the same. cc @SiarheiFedartsou

**Comment by SiarheiFedartsou** [comment]
So, we should simply generate pbf from gurka's ascii map and test over it in the same way?

BTW does gurka support multi-level roads in some way? I'm working on adding Z-level support to Loki at the moment and it is not clear how to produce such pbf(i.e. it should be edges with 100% the same geometry, but with different Z-levels) using gurka.

**Comment by kevinkreiser** [comment]
you should be able to do it by specifying the same geometry twice, ie when you create a "way" use the same "nodes" but change the attributes ie "layer" tag

**Comment by danpat** [comment]
Hmm, there's currently not a way to specify two disconnected nodes at the same location without constructing the node map manually.  If you ASCII-draw `A` and `B` and create two ways that connect `A` and `B`, then both ways will connect to `A` and `B`, which is probably not you want.  E.g. this:

```
A----B

  const gurka::ways ways = {
      {"AB", {{"highway", "residential"},{"name","AB1"}},
      {"AB", {{"highway", "residential"},{"name","AB2"}}
  };
```

I wonder if we should add a capability to gurka to support multiple versions of a node at the same location, maybe using a `'`, like `A'`:

```
  const gurka::ways ways = {
      {"AB", {{"highway", "residential"},{"name","AB1"}},
      {"A'B'", {{"highway", "residential"},{"name","AB2"}}
  };
```

This would mean `A'` is at the same location as `A`, but is a completely separate node, so wouldn't create accidental connections.

Of course, you could just slightly offset overlapping geometries like this:

```
AC-------BD

  const gurka::ways ways = {
      {"AB", {{"highway", "residential"},{"name","AB"}},
      {"CD'", {{"highway", "residential"},{"name","CD"}}
  };
```

and these wouldn't be connected either.

**Comment by SiarheiFedartsou** [comment]
> Of course, you could just slightly offset overlapping geometries like this:
> 
> ```
> AC-------BD
> 
>   const gurka::ways ways = {
>       {"AB", {{"highway", "residential"},{"name","AB"}}},
>       {"CD'", {{"highway", "residential"},{"name","CD"}}}
>   };
> ```
> 
> and these wouldn't be connected either. You need to be careful about angles when trying to overlap like this though - the math to calculate lon/lat from the ASCII grid doesn't use spherical geometry, so diagonal lines may not be possible to create perfectly overlapping.

@danpat thanks for the idea!

I tried it [here](https://github.com/valhalla/valhalla/pull/3270/files#diff-53e01cd9cf34b58a9384ecd2180a77281790da8cfa39b48d1b533d6857ab5d30R106) and for some reason it does not work. Loki chooses candidates from lower level always. I'm quite confident in logic related to Z-level in Loki, because I tested it before with "old-school" way(using OSM extract) and it was working. Maybe you have ideas what can be wrong in my Gurka tests there?

**Comment by kevinkreiser** [comment]
Loki only ever chooses one result unless you specify a radius. That's what I was trying to say before. A radius of 0,the default means give me the closest thing. If both things are equally close then it just luck which one loki sees in the data first

**Comment by SiarheiFedartsou** [comment]
> Loki only ever chooses one result unless you specify a radius. That's what I was trying to say before. A radius of 0,the default means give me the closest thing. If both things are equally close then it just luck which one loki sees in the data first

hm, I'm quite confident that it used to work with "old-school" test 🤔 Will re-check - thanks.

**Comment by SiarheiFedartsou** [comment]
Well, just tried to pass `radius` argument and it worked.

**Comment by kevinkreiser** [comment]
yeah its luck of the draw, whichever one it sees first becomes the one it gets (so if there are equal results the tie breaker is which one it sees first). we could change the code to keep multiple results if the results are truely equal, but i think in real world situations there will be floating point noise and it wont matter
