### ISSUE TITLE
Question: Difference result for runing route algorithm inside chinese postman

### ISSUE THREAD

**Issue by ismailsunni** [valhalla/valhalla#3272]
Dear @kevinkreiser @nilsnolde 
From our last discussion (related to #3255), I managed to call the function to calculate the route and get a path from it. Unfortunately, the result is not correct.

Here is the function that I use to call the routing functionality: https://github.com/ismailsunni/valhalla/blob/develop/src/thor/chinese_postman_action.cc#L248

These are what I have done:
- Refactoring my code so that it's easy to do the following steps.
- I have done the setup as @kevinkreiser explained.
- I have checked the input location for the `GetBestPath` is the same as in the normal route function.
- I also use `get_path_algorithm` to get the same path algorithm for the same case.
- I have created unit tests to compare the variables between [normal routing ](https://github.com/ismailsunni/valhalla/blob/develop/test/gurka/test_chinese_postman.cc#L439)and [calling routing functions from CP](https://github.com/ismailsunni/valhalla/blob/develop/test/gurka/test_chinese_postman.cc#L429)

Based on what I found, I don't understand why `edgelabels_` in [unidirectional_astars](https://github.com/ismailsunni/valhalla/blob/develop/src/thor/unidirectional_astar.cc#L466) is different for both unit tests. I am trying to understand when it starts to differ, but I can't find where is it. Since the first time I saw `edgelabels_` is when I call `GetBestPath` from the CP.

Any idea where does this comes from? Or any hint where the problem might occur?

Thanks!

**Comment by kevinkreiser** [comment]
can you maybe show an example result and the expected result so that we could tell what is not correct about it? with any luck we just forgot to set something in the input to the algorithm.

**Comment by ismailsunni** [comment]
Here is the example (copied from the unit test):
```
            p----------------x----------q
            |    B--------A--|------F   |
            |     \       | \|     /|   |
            |      \      |  |\   / |   |
            |       \     |  | \ /  |   |
            |        \    |  |  E   |   |
            |         \   |  |   \  |   |
            |          \  |  |    \ |   |
            |           \ |  |     \|   |
            |             C--|------D   |
            r----------------y----------s
```
with the direction of the road as below
```
    // B----<---A--->----F
    //  \       | \     /|
    //   \      |  ^   v |
    //    \     v   \ /  |
    //     v    |    E   v
    //      \   |     \  |
    //       \  |      ^ |
    //        \ |       \|
    //          C---->---D
```

For the normal routing, the input is point E as the start and D as the destination. The result is correct: EA->AC->CD.

For the CP, the input is F as the start and E as the destination. The Chinese polygon is `xqsy`. The expected result would be: `FE -> EA -> AC -> CD -> DE` but the result that I got is `FE -> FE -> FD -> DE -> DE`. 
The first edge (FE) and the last edge (DE) are computed from the CP algorithm. The 3 edges in the middle are computed by calling the Valhalla routing. So, it gives me `FE -> FD -> DE` not `EA->AC->CD` (like the normal routing algorithm.)

It seems the algorithm either doesn't follow the direction of the road or arriving at the wrong destination.

Those two cases/tests can be run in this unit test: https://github.com/ismailsunni/valhalla/blob/develop/test/gurka/test_chinese_postman.cc#L429

**Comment by kevinkreiser** [comment]
@ismailsunni im sorry but im failing to understand. You want the regular routing algorithm to find a path from F to E. To me it looks like it should just return `F -> E`. let me ask ask some clarifying questions/statements:

1. are you trying to route from node to node using any edges that leave the node? or are you trying to route from edge to edge, starting and ending on the specific edges that you specify?
2. when you get back the names of edges in gurka, they are named in the order of the geometry, not in the order of the traversal between nodes. so if you have the graph `A------B` and you make an osm way by specifying the nodes `AB` then the way will get the name `AB`. We make two edges out of this in the graph though, and you can travel along them in either direction but both of them still have the name `AB` regardless of the direction you are traveling.
3. are you making these ways as oneway roads? given the example you set it seemed to me that  you must be but i didnt check the test file to see.

**Comment by ismailsunni** [comment]
Hi @kevinkreiser 
No, it should also visit DE and FD since both edges are also inside the polygon `xqsy`.

1. From node to node using any edges that leave the node.
2. Yes, I understand that. That's why it's strange for me to get `FE -> FD -> DE` since the edge FE is ended at node E, and FD is started at node F. I set the edge's name for all edges with the same order as the edge's direction (e.g. FE because it starts on F and end on E, see the code on point 3)
3. Yes, I specify the order and make it one way. Here is the excerpt of the Gurka map setup:
    ```
    const gurka::ways complex_ways =
        {{"AB", {{"highway", "residential"}, {"name", "AB"}, {"oneway", "yes"}}},
         {"AC", {{"highway", "residential"}, {"name", "AC"}, {"oneway", "yes"}}},
         {"AF", {{"highway", "residential"}, {"name", "AF"}, {"oneway", "yes"}}},

         {"BC", {{"highway", "residential"}, {"name", "BC"}, {"oneway", "yes"}}},

         {"CD", {{"highway", "residential"}, {"name", "CD"}, {"oneway", "yes"}}},

         {"DE", {{"highway", "residential"}, {"name", "DE"}, {"oneway", "yes"}}},

         {"EA", {{"highway", "residential"}, {"name", "EA"}, {"oneway", "yes"}}},

         {"FD", {{"highway", "residential"}, {"name", "FD"}, {"oneway", "yes"}}},
         {"FE", {{"highway", "residential"}, {"name", "FE"}, {"oneway", "yes"}}}};
    ```

**Comment by nilsnolde** [comment]
I think we singled out the issue @kevinkreiser but honestly it's really hard to debug/see what the problem is. maybe you can shed some light on this..

the following code basically takes an origin and destination node, and wants to route in between those (the case where there are edges outside of the CP-internal graph), where I think the main problem is how origin and destination edges are treated:

```c++
  google::protobuf::RepeatedPtrField<Location> locations_;
  std::vector<baldr::GraphId> node_ids{GraphId(cpvertex_start.graph_id),
                                       GraphId(cpvertex_end.graph_id)};
  for (const auto& node_id : node_ids) {
    auto* loc = locations_.Add();
    auto tile = reader->GetGraphTile(node_id);
    const auto* node = tile->node(node_id);
    auto ll = node->latlng(tile->header()->base_ll());
    loc->mutable_ll()->set_lng(ll.first);
    loc->mutable_ll()->set_lat(ll.second);

    auto edge_id = tile->id();
    edge_id.set_id(node->edge_index());
    for (const auto& edge : tile->GetDirectedEdges(node_id)) {   // <- add outbound edges even for origin?
      auto ei = tile->edgeinfo(&edge);
      std::cout << ei.GetNames()[0] << std::endl;
      auto* path_edge = loc->add_path_edges();
      path_edge->set_distance(0);
      path_edge->set_begin_node(true);  // <- my brain broke a little when trying to figure out if these are correct for bidir a*
      path_edge->set_end_node(true);  // <- my brain broke a little when trying to figure out if these are correct for bidir a*
      path_edge->set_graph_id(edge_id);
      path_edge->mutable_ll()->set_lng(ll.first);
      path_edge->mutable_ll()->set_lat(ll.second);
      ++edge_id;
    }
  }
```

the full code is here: https://github.com/ismailsunni/valhalla/blob/develop/src/thor/chinese_postman_action.cc#L248-L296

cc @ismailsunni

**Comment by ismailsunni** [comment]
Hi, I managed to make it work and keeping the `set_end_node(false)`.
I added this code after the setup above:
```
  try {
    auto locations = PathLocation::fromPBF(locations_, true);
    const auto projections = loki::Search(locations, *reader, this->mode_costing[Costing::auto_]);
    for (size_t i = 0; i < locations.size(); ++i) {
      const auto& correlated = projections.at(locations[i]);
      PathLocation::toPBF(correlated, locations_.Mutable(i), *reader);
    }
  } catch (const std::exception&) { throw valhalla_exception_t{171}; }
```

It works fine for my unit test. But I still have other issues when testing on the real data though. But at least, I think we can close this.

Thanks!
