### ISSUE TITLE
Elevation downloader in python?

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3298]
we're just having a use case where we want to load elevation based on arbitrary polygon geometries instead of bbox, so we'd like to implement a small python script instead of the existing bash script. the geometries we want to have elevation for are pretty concave, so bboxes is a disk waste. additionally, we'd accept an [osmium-tool config file](https://docs.osmcode.org/osmium/latest/osmium-extract.html#config-file) as input to extract polygon geometries from the same input one might create OSM extracts with.

would that be interesting for upstream? realistically that'd need a spatial library though, e.g. `shapely` to ease intersection stuff. so a user would need to install that. we could automate that as well as part of the cmake config or so, but IMO it's fair to print a sane message saying `shapely` needs to be manually installed.

cc @chrstnbwnkl

**Comment by nilsnolde** [comment]
just did an extract for half US + 11 canadian cities and saved more than 35% of disk space:
```
2021-09-01 14:23:35,628 DEBUG: Bbox extraction would've yielded 1103 tiles.
2021-09-01 14:23:35,628 INFO: Successfully saved 698 tiles to /custom_files/elevation_data!
```

**Comment by kevinkreiser** [comment]
@nilsnolde what i have advocated for a while (but i cant figure out where) was to just download each srtm tile as the tile builder needs it (ie lazily). in this case we will only ever download exactly the tiles we need and only when we need them (though we should cache them to disk). i did a prototype of this some 3 years ago but the code is lost to time. i think in the meantime a python script is just fine. actually we could replace the existing scripts if you can add the same functionality that exists in them (ie extract them and do it all in parallel).

**Comment by nilsnolde** [comment]
Sure, c++ would be deluxe. Would be nice if we can save that for another day. We’ll polish the script a little then and PR.

**Comment by nilsnolde** [comment]
the only downside is that hyperthreading is not really supported in python. `multiprocessing` can only use physical cores (for me that's 4 instead of 8), and `threading` is not an option anyways with python's GIL.. hope that's not a dealbreaker..

**Comment by nilsnolde** [comment]
in fact, I'd advocate to eventually have all relevant helper scripts written in python (or ported to c++), some of the bash ones don't even run on mac (e.g. `nproc` is linux-only), much less win (still chasing the dream that I can use full valhalla eventually on all major platforms:) tests might be a pipe dream though..). I think the only relevant script left (after this PR) is `valhalla_build_timezones`. that won't be possible without some more third-party packages though for spatialite access. worth though IMHO.. what do you think?

**Comment by kevinkreiser** [comment]
> is that hyperthreading is not really supported in python

are you sure about that? i'm pretty sure ive done it. here's a snippet:

```python
from multiprocessing.dummy import Pool as ThreadPool
pool = ThreadPool(multiprocessing.cpu_count()) #this is the number even with hyperthreading (double the cores on most non-crappy cpus)
results = pool.imap_unordered(work_function, job_yielding_function())
pool.close()
```

**Comment by nilsnolde** [comment]
Not entirely sure, no. But: that value says 8 for me too, but that’s not how it’s being processed on your computer: only 4 processes are spawning IIRC. We’ll see when we implement it, then I’ll update here

**Comment by kevinkreiser** [comment]
@nilsnolde that snippet uses threads instead of processes and for my computers, one with 8 cores and 16 threads and one with 12 cores and 24 threads, it works as you would expect with hyperthreading/SMT. but yeah let me know if that doesnt actually work. when i run this with a lot of work and i look at `top` i see that its at 24 on my big machine, as it should be

**Comment by nilsnolde** [comment]
ah, but doesn't threading in python actually not work like in c++ though, due to the global interpreter lock, where only one thread can do work at the same time while the others are sleeping, e.g. https://opensource.com/article/17/4/grok-gil. hence the need for multiprocessing where actual processes are started instead of threads. would be awesome if there was a way around that. AFAIK threading in python is mostly useful for background listeners who do work here and there, I/O bound stuff etc.

**Comment by kevinkreiser** [comment]
i mean isnt this exactly that? its just downloading (network io) not using the cpu.

also in practice i recently wrote a script that uses this snippet pretty much exactly and it completes something that used to take hours in only 5 minutes. now some of that process calls into c++ or makes system calls but it certainly works to some degree. i dont understand why threading would exist in python if it doesnt work at all but i have heard this argument before so there must be some merrit to it, i just haven't been burnt by it yet i guess :smile:

**Comment by nilsnolde** [comment]
yeah, never really tried it I guess, I always used processes exactly because of articles like that (and bcs I usually actually do cpu processing more often than not). wouldn't say "work at all", just limited in usage in different ways than using processes. we'll try and report:)

**Comment by kevinkreiser** [comment]
fwiw multiprocess is fine with me! do whatever you are comfortable with!
