### ISSUE TITLE
Uanble to load Great Britain data from OSM

### ISSUE THREAD

**Issue by boothrob** [valhalla/valhalla#3315]
Hi

Apologies if this isn't the right place to raise questions like this.  I've just started playing with Valhalla, and have run into an issue generating the tiles for Great Britain.

I've successfully generated tiles for other European countries and successfully queried routes, but when I generate for GB I get consistent Error 400 messages on my routing requests - error code 171 - 'No suitable edges near location'.

This is the output form the command I use to create the tiles - 

ubuntu@ubuntu2004:~/valhalla$ valhalla_build_tiles -c valhalla.json great-britain-latest.osm.pbf 
2021/09/10 15:27:49.058661 [INFO] Start stage = initialize End stage = cleanup
2021/09/10 15:27:49.059536 [WARN] Non-empty /home/ubuntu/valhalla/valhalla_tiles/0 will be purged of tiles
2021/09/10 15:27:49.061866 [WARN] Non-empty /home/ubuntu/valhalla/valhalla_tiles/1 will be purged of tiles
2021/09/10 15:27:49.064770 [WARN] Non-empty /home/ubuntu/valhalla/valhalla_tiles/2 will be purged of tiles
2021/09/10 15:27:49.089597 [INFO] Parsing files for ways: great-britain-latest.osm.pbf
2021/09/10 15:27:49.089822 [INFO] Parsing ways...
2021/09/10 15:31:16.746759 [WARN] Error during parsing of `layer` tag on the way 804841043: stoi
2021/09/10 15:31:19.017271 [INFO] invalid_argument thrown for condition (Dec 26-easter -2 days)
2021/09/10 15:31:19.272220 [WARN] Error during parsing of `layer` tag on the way 820150245: stoi
2021/09/10 15:31:23.196658 [WARN] Error during parsing of `layer` tag on the way 839095616: stoi
2021/09/10 15:32:09.419912 [INFO] Added 9067 culdesac roundabouts from 14727 candidates.
2021/09/10 15:32:09.419948 [INFO] Finished with 5770453 routable ways containing 43401587 nodes
2021/09/10 15:32:09.462327 [INFO] Sorting osm access tags by way id...
2021/09/10 15:32:09.507079 [INFO] Finished
2021/09/10 15:32:09.569546 [INFO] Parsing files for relations: great-britain-latest.osm.pbf
2021/09/10 15:32:09.574644 [INFO] Parsing relations...
2021/09/10 15:33:15.179335 [INFO] Finished with 22575 simple restrictions
2021/09/10 15:33:15.179371 [INFO] Finished with 0 lane connections
2021/09/10 15:33:15.180096 [INFO] Sorting complex restrictions by from id...
2021/09/10 15:33:15.182621 [INFO] Sorting complex restrictions by to id...
2021/09/10 15:33:15.184045 [INFO] Finished
2021/09/10 15:33:15.185331 [INFO] Parsing files for nodes: great-britain-latest.osm.pbf
2021/09/10 15:33:15.185365 [INFO] Sorting osm way node references by node id...
2021/09/10 15:33:49.813217 [INFO] Parsing nodes...
2021/09/10 15:36:16.120464 [INFO] Finished with 35568552 nodes contained in routable ways
2021/09/10 15:36:16.120508 [INFO] Sorting osm way node references by way index and node shape index...
2021/09/10 15:36:49.584925 [INFO] Finished: max_osm_id 9077772163
2021/09/10 15:36:49.585151 [INFO] Number of nodes with refs (exits) = 1730
2021/09/10 15:36:49.585161 [INFO] Number of nodes with exit_to = 305
2021/09/10 15:36:49.585184 [INFO] Number of nodes with names = 2940
2021/09/10 15:36:49.585192 [INFO] Number of way refs = 0
2021/09/10 15:36:49.585198 [INFO] Number of reverse way refs = 0
2021/09/10 15:36:49.585203 [INFO] Unique Node Strings (names, refs, etc.) = 2209
2021/09/10 15:36:49.585334 [INFO] Unique Strings (names, refs, etc.) = 403210
2021/09/10 15:36:49.588409 [INFO] Creating graph edges from ways...
2021/09/10 15:36:58.975944 [INFO] Finished with 11458057 graph edges
2021/09/10 15:36:59.049120 [INFO] Sorting graph...
2021/09/10 15:37:17.451471 [INFO] Nodes processed. Sorting begin and end nodes by edge.
2021/09/10 15:37:20.910752 [INFO] Sorting begin and end nodes done. Populating edges...
2021/09/10 15:37:22.196016 [INFO] Finished with 9395476 graph nodes
2021/09/10 15:37:22.237685 [INFO] Writing tile manifest to /home/ubuntu/valhalla/valhalla_tiles/tile_manifest.json
2021/09/10 15:37:22.238241 [INFO] Reclassifying_V2 link graph edges...
2021/09/10 15:37:23.708330 [INFO] Class: 0 exit count = 1445
2021/09/10 15:37:23.708367 [INFO] Class: 1 exit count = 7573
2021/09/10 15:37:23.708371 [INFO] Class: 2 exit count = 5208
2021/09/10 15:37:23.708373 [INFO] Class: 3 exit count = 1715
2021/09/10 15:37:23.708375 [INFO] Class: 4 exit count = 2606
2021/09/10 15:37:23.708377 [INFO] Class: 5 exit count = 712
2021/09/10 15:37:23.708379 [INFO] Class: 6 exit count = 380
2021/09/10 15:37:23.708382 [INFO] Class: 7 exit count = 0
2021/09/10 15:37:28.268710 [INFO] Finished with 16610 reclassified.  Turn channel count = 9432
2021/09/10 15:37:28.351580 [INFO] Reclassifying ferry connection graph edges...
2021/09/10 15:37:32.228033 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 153, 3813 edges reclassified.
2021/09/10 15:37:32.306747 [INFO] Building 727 tiles with 2 threads...
2021/09/10 15:37:32.679826 [INFO] SpatiaLite loaded as an extension
2021/09/10 15:37:32.679871 [INFO] SpatiaLite loaded as an extension
2021/09/10 15:37:32.680320 [WARN] Time zone db /home/ubuntu/valhalla/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
2021/09/10 15:37:32.680433 [WARN] Time zone db /home/ubuntu/valhalla/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
2021/09/10 15:40:42.989553 [INFO] Finished
2021/09/10 15:40:43.006397 [INFO] Node Count = 9395476
2021/09/10 15:40:43.006556 [INFO] Directed Edge Count = 22916114
2021/09/10 15:40:43.006600 [INFO] EdgeInfo Count = 11514897
2021/09/10 15:40:43.006615 [INFO] Enhancing local graph...
2021/09/10 15:40:43.068550 [INFO] SpatiaLite loaded as an extension
2021/09/10 15:40:43.068716 [INFO] SpatiaLite loaded as an extension
2021/09/10 15:40:43.072428 [INFO] Disabled default speeds assignment from config
2021/09/10 15:40:43.079188 [INFO] Disabled default speeds assignment from config
2021/09/10 15:40:48.144974 [WARN] Exceeding maximum.  Average speed: 141
 <SNIPPED FOR EASE OF READING BUT LOTS MORE DUPLICATES OF THIS MESSAGE>
2021/09/10 15:46:24.662952 [WARN] Exceeding maximum.  Average speed: 141
2021/09/10 15:46:24.663315 [WARN] Exceeding maximum.  Average speed: 141
Killed

ubuntu@ubuntu2004:~/valhalla$ find valhalla_tiles | sort -n | tar -cf valhalla_tiles.tar --no-recursion -T -

ubuntu@ubuntu2004:~/valhalla$ valhalla_service valhalla.json 1

2021/09/10 15:48:33.820522 [INFO] Tile extract successfully loaded with tile count: 727
2021/09/10 15:48:33.820670 [WARN] (stat): /data/valhalla/traffic.tar No such file or directory
2021/09/10 15:48:33.820705 [WARN] Traffic tile extract could not be loaded
2021/09/10 15:48:33.828138 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
0 2021/09/10 15:49:23.882716 GET /route?json={%22locations%22:[{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:52.3688917060255,%22lng%22:0.6684494018554688},%22_initHooksCalled%22:true,%22lat%22:52.3688917060255,%22lon%22:0.6684494018554688},{%22options%22:{%22allowUTurn%22:false},%22latLng%22:{%22lat%22:52.14697334064471,%22lng%22:0.10814666748046874},%22_initHooksCalled%22:true,%22lat%22:52.14697334064471,%22lon%22:0.10814666748046874}],%22costing%22:%22auto%22,%22directions_options%22:{%22language%22:%22en-US%22}}&access_token= HTTP/1.1
2021/09/10 15:49:23.883088 [INFO] Got Loki Request 0
2021/09/10 15:49:23.994445 [WARN] 400::No suitable edges near location request_id=0
0 2021/09/10 15:49:23.994578 400 228

From a different set of install instructions, I've also tried using the valhalla_build_admins command which suggests thaht there may be a problem in the naming of the Great Britain data (as opposed to UK data)

ubuntu@ubuntu2004:~/valhalla$ valhalla_build_admins --config valhalla.json united-kingdom-latest.osm.pbf 
2021/09/10 15:19:05.620236 [INFO] Parsing files: united-kingdom-latest.osm.pbf
2021/09/10 15:19:05.620305 [INFO] Parsing relations...
2021/09/10 15:19:36.996400 [INFO] Finished with 7 admin polygons comprised of 4083 ways
2021/09/10 15:19:36.996593 [INFO] Parsing ways...
2021/09/10 15:20:10.536101 [INFO] Finished with 489 ways comprised of 54492 nodes
2021/09/10 15:20:10.536149 [INFO] Parsing nodes...
2021/09/10 15:20:43.145403 [INFO] Finished with 54000 nodes
2021/09/10 15:20:43.166860 [INFO] SpatiaLite loaded as an extension
2021/09/10 15:20:43.220281 [INFO] Created admin access table.
2021/09/10 15:20:43.229628 [INFO] Created admin table.
2021/09/10 15:20:44.213149 [INFO] Inserted 4 admin areas
2021/09/10 15:20:44.229987 [INFO] Created spatial index
2021/09/10 15:20:44.231066 [INFO] Created Level index
2021/09/10 15:20:44.232135 [INFO] Created Drive On Right index
2021/09/10 15:20:44.233459 [INFO] Created allow intersection names index
2021/09/10 15:20:44.236792 [INFO] Done updating drive on right column.
2021/09/10 15:20:44.236911 [INFO] Done updating allow intersection names column.
2021/09/10 15:20:44.686977 [INFO] Done updating Parent admin
2021/09/10 15:20:44.687108 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for United States
2021/09/10 15:20:44.687133 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for United Kingdom
2021/09/10 15:20:44.687140 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Switzerland
2021/09/10 15:20:44.687146 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Russia
2021/09/10 15:20:44.687151 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Romania
2021/09/10 15:20:44.687155 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Poland
2021/09/10 15:20:44.687160 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Norway
2021/09/10 15:20:44.687165 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Spain
2021/09/10 15:20:44.687170 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Netherlands
2021/09/10 15:20:44.687175 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Hungary
2021/09/10 15:20:44.687180 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Slovakia
2021/09/10 15:20:44.687184 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for France
2021/09/10 15:20:44.687189 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Finland
2021/09/10 15:20:44.687194 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Denmark
2021/09/10 15:20:44.687199 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Brazil
2021/09/10 15:20:44.687204 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Turkey
2021/09/10 15:20:44.687209 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Belgium
2021/09/10 15:20:44.687214 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Belarus
2021/09/10 15:20:44.687219 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Austria
2021/09/10 15:20:44.687238 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Australia
2021/09/10 15:20:44.687831 [INFO] Finished.

Any idea what I am missing or what I need to try and fix?

**Comment by nilsnolde** [comment]
Your tiles never got built, you’re actually missing the big, fat „Killed“ right „after“ the tile build;) My guess is your machine is too low spec on RAM. How much you got? What other countries did you build successfully before? GB is one of the biggest extracts in Europe.. 

The admin builder tells you those errors are fine: „ignore of not using a planet extract“

**Comment by nilsnolde** [comment]
correction, you do have an archived graph, but a broken one. it did build tiles, but got (OOM?) killed in the enhancement stage. not sure what the consequences are exactly, but's still 99% the cause of the issue.

**Comment by boothrob** [comment]
OOM was indeed the answer!  Many thanks.
