### ISSUE TITLE
Build Problems on Newer GCC: static_assert(is_destructible

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3316]
Disccussion is here: https://github.com/valhalla/valhalla/pull/3120#discussion_r706329653

**Comment by kevinkreiser** [comment]
so i took a quick look at this and it seems the presence of a destructor in `tile_data` causes `is_destructable` to be `false`. this is highly unintuitive but :man_shrugging: anyway seems like we can fix this if we can figure out a way to not have a user defined constructor.. i think i have an idea for that but its kind of hacky. ill draft a pr and see what you all think

**Comment by molind** [comment]
gcc with libstdc++ 11.1.0 throws this error if `tile_data` forward declared before cache_t
https://godbolt.org/z/8sYhf8Wqb
and only in 11+ versions. gcc < 11 compiles it without errors.

while clang 12.0.1 with libc++ works fine. -stdlib=libc++
https://godbolt.org/z/vPYTdb3aW

I'll send bug report to libstd++ and try to reorder declarations to fix this bug.

**Comment by nilsnolde** [comment]
Fixed in #3317 :)
