### ISSUE TITLE
Coordinates in encoded polyline are wrong order of magnitude

### ISSUE THREAD

**Issue by chfritz** [valhalla/valhalla#3319]
I'm running the latest valhalla/docker container on OSM data from Santa Monica, CA (USA). I get a route, but all the coordinates in the encoded polyline in the `shape` field seem to be multiplied by a factor of ten:

```
> curl http://172.17.0.2:8002/route --data '{"locations":[{"lat":34.01983626526626, "lon": -118.49357665402121, "type":"break"},{"lat":34.01972733171817, "lon": -118.50239843948418}], "costing":"auto","directions_options":{"units":"miles"}}' | jq '.'

{
  "trip": {
    "language": "en-US",
    "summary": {
      "max_lon": -118.493607,
      "max_lat": 34.021423,
      "time": 157,
      "length": 0.727,
      "min_lat": 34.017582,
      "min_lon": -118.502533
    },
    "locations": [
      {
        "original_index": 0,
        "lon": -118.493576,
        "lat": 34.019836,
        "type": "break"
      },
      {
        "original_index": 1,
        "type": "break",
        "lon": -118.502396,
        "lat": 34.019726,
        "side_of_street": "right"
      }
    ],
    "units": "miles",
    "legs": [
      {
        "shape": "a}k{_Alyg_aFyMdPmd@jj@kZ|^sAzAqH|IaHnIrP|T|@jAvCfExCtD`RjVhQlUnDrEtErGbQzUtO~RbFrGxCdEpQjVlPlT|DbF`SjWfCdD`CfDxRzVpW~\\wm@zu@ig@fm@{EvC}UdZmIjK",
   ...
```
This `shape` value decodes to:
```
[
  [ 340.19809, -1184.93607 ],
  [ 340.20046, -1184.93882 ],
  [ 340.20645, -1184.94576 ],
  [ 340.21083, -1184.95087 ],
 ...
  [ 340.19451, -1185.02335 ],
  [ 340.19618, -1185.02533 ]
]
```
The route itself is correct. When I manually translate these coordinates to divide each lat and lon by 10 then I can visualize it and it is correct.

**Comment by ImreSamu** [comment]
my result :
 http://valhalla.github.io/demos/polyline/?unescape=true&polyline6=true#a%7Dk%7B_Alyg_aFyMdPmd%40jj%40kZ%7C%5EsAzAqH%7CIaHnIrP%7CT%7C%40jAvCfExCtD%60RjVhQlUnDrEtErGbQzUtO~RbFrGxCdEpQjVlPlT%7CDbF%60SjWfCdD%60CfDxRzVpW~%5C%5Cwm%40zu%40ig%40fm%40%7BEvC%7DUdZmIjK

![image](https://user-images.githubusercontent.com/2217320/133170772-980390e4-cac1-436e-9d96-6aa899b83410.png)

**Comment by ImreSamu** [comment]
doc "Decode a route shape":  https://valhalla.readthedocs.io/en/latest/decoding/

**Comment by chfritz** [comment]
ah, I see. Seems to be a matter of the polyline version. Sorry, didn't know about polyline6. I tested with both [Google polyline utility](https://developers.google.com/maps/documentation/utilities/polylineutility) as well as the [mapbox's npm package](https://github.com/mapbox/polyline), and they both showed the results you get when you toggle the Polyline6 checkbox in the tool you linked to.

**Comment by nilsnolde** [comment]
> It might be good to point out that that Google tool the documentation links to (indirectly) will not work!

I think it's fairly clear from the docs:

```
Note: Valhalla APIs use six digits of decimal precision.

It is very important that you use six digits, rather than five as referenced in the Google algorithms documentation. With fewer than six digits, your locations are incorrectly placed (commonly, in the middle of an ocean), and you may receive errors with your API requests.
``` 

valhalla is being a little exotic here, but on the good side of exotic I find:)
