### ISSUE TITLE
Error 400::Path distance exceeds the max distance limit 

### ISSUE THREAD

**Issue by saraefaf1** [valhalla/valhalla#3345]
Hey guys,
i try to sending the Json file to Mapmaching,I got this error, and I tried to give the "max_matrix_distancea" value to fix this error , but I still get this error 400,does anyone have an Idea?
Thanks,
sara

> 

meili_coordinates = df_sampel.to_json(orient='records')
meili_head = '{"shape":'
meili_tail = ""","search_radius": 150, "shape_match":"map_snap", "costing":"auto", "max_distance":9000000.0,
            "max_matrix_distance":900000.0,
            "max_matrix_locations":250, "format":"osrm"}"""
meili_request_body = meili_head + meili_coordinates + meili_tail

**Comment by saraefaf1** [comment]
meili_coordinates = df_sampel.to_json(orient='records')

meili_head = '{"shape":'
meili_tail = ""","search_radius": 150, "shape_match":"map_snap", "costing":"auto",
,"format":"osrm","service_limits":{
"auto":{
"max_distance":9000000.0,
"max_matrix_distance":900000.0,
"max_matrix_locations":250},
},}"""
meili_request_body = meili_head + meili_coordinates + meili_tail

**Comment by kevinkreiser** [comment]
ok so for map matching you need to modify the `trace` config sections `max_distance`: https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_config#L243

**Comment by kevinkreiser** [comment]
can you paste the final json request `meili_request_body` that you send to the library? if i were you i would use the python module called `json` and then create a dict that will be the request and turn that into a string before you send it to valhalla via `json.dumps(request_dict)`

**Comment by saraefaf1** [comment]
i can send you  meili_request_body via Eemil.

**Comment by saraefaf1** [comment]
my jsondata is now correct, but are there still the errors, is it possible, the number should be larger? i have also tried up to 900000000.

**Comment by ikespand** [comment]
Hi. How can we avoid this error for map matching when distance is large. What would be the configuration parameter in the tail. My request works perfectly fine when distance is upto ~200 KM, however after that it always returns:
`{'error_code': 154, 'error': 'Path distance exceeds the max distance limit', 'status_code': 400, 'status': 'Bad Request'}
`
I already play around with following parameters:
`{"search_radius": 150, "shape_match":"map_snap", "max_distance":900000,"max_matrix_locations":250, "max_matrix_distance":900000, "costing":"auto"}
`
Any suggestions?

**Comment by nilsnolde** [comment]
@ikespand was mixing service config options with request parameters. Have a look a the config json generator to see which values you have to adjust: https://github.com/valhalla/valhalla/blob/3da6471dc37765806022d3055cb2d12b56c47f17/scripts/valhalla_build_config#L250

If you’re requesting against a remote (foreign) API, e.g. https://valhalla1.openstreetmap.de, then there’s nothing you can do other than running your own Valhalla service.

**Comment by brad-4k** [comment]
I'm having the same problem.  Trying a LONG route from Alaska, US to Mexico City, MX which is an "aggressive" test we do inhouse.  I've changed valhalla_build_config (max_distance from 200000, to 2000000):

` 'trace': {
      'max_distance': 2000000.0,
      'max_gps_accuracy': 100.0,
      'max_search_radius': 100.0,
      'max_shape': 160000,
      'max_alternates': `

I restarted but I still get the "Path distance exceeds the max distance limit" error.

Is this file read on each start or is it read during the building of the database?

My URL:

`http://localhost:8002/route?json={%22locations%22:[{%22lat%22:61.211689,%22lon%22:-149.74348569806048},{%22lat%22:19.36341,%22lon%22:-99.051203}],%22costing%22:%22truck%22,%22directions_options%22:{%22units%22:%22miles%22}}`

**Comment by dnesbitt61** [comment]
did you change the configuration for trace route rather than route? You would need to change the max_distance under service_limits truck if you are looking to do a truck route as your requests shows.

**Comment by brad-4k** [comment]
> did you change the configuration for trace route rather than route? You would need to change the max_distance under service_limits truck if you are looking to do a truck route as your requests shows.

I originally had updated 'service_limits': { 'trace': max_distance and I've now changed 'service_limits': {
`    'truck': {
      'max_distance': 50000000.0,
      'max_locations': 20,
      'max_matrix_distance': 4000000.0,
      'max_matrix_locations': 50
    },`

I went so far as to make the max_distance for truck 50,000,000 (50000000).

I restarted valhalla but I have the same issue.

**Comment by brad-4k** [comment]
The file is "valhalla_build_config", so based on the same, does that mean I have to rebuild valhalla when I make a change?

**Comment by dnesbitt61** [comment]
your request worked for me with config for truck as follows:
    "truck": {
      "max_distance": 50000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_location_pairs": 50
    }
This is with a mostly current Valhalla build. You do not need to rebuild Valhalla when changing the config file. You have to restart your server to read in the new config file.

**Comment by brad-4k** [comment]
> your request worked for me with config for truck as follows: "truck": { "max_distance": 50000000.0, "max_locations": 20, "max_matrix_distance": 400000.0, "max_matrix_location_pairs": 50 } This is with a mostly current Valhalla build. You do not need to rebuild Valhalla when changing the config file. You have to restart your server to read in the new config file.

Ok, that's promising.  The image I'm using is 6 months old, so I wonder if that is the issue.  I'm going to pull a more recent one and try that.  Thank you again for your responses.

**Comment by nilsnolde** [comment]
If it’s still our image you’re using, that may well be, there’s been a couple of weird bugs depending on the exact setup.

**Comment by brad-4k** [comment]
> If it’s still our image you’re using, that may well be, there’s been a couple of weird bugs depending on the exact setup.

I'm using  docker.pkg.github.com/gis-ops/docker-valhalla/valhalla:latest (until 3.1.5 lands).  I'm guessing this is managed separately?

**Comment by brad-4k** [comment]
> > your request worked for me with config for truck as follows: "truck": { "max_distance": 50000000.0, "max_locations": 20, "max_matrix_distance": 400000.0, "max_matrix_location_pairs": 50 } This is with a mostly current Valhalla build. You do not need to rebuild Valhalla when changing the config file. You have to restart your server to read in the new config file.
> 
> Ok, that's promising. The image I'm using is 6 months old, so I wonder if that is the issue. I'm going to pull a more recent one and try that. Thank you again for your responses.

Still not working for me using the latest image from _docker.pkg.github.com/gis-ops/docker-valhalla_ .  I set all of the _**max_distance**_ values to 20x of their defaults and my test route from Anchorage, AK, US to Mexico City, MX (~4900 miles) returns  `[WARN] 400::Path distance exceeds the max distance limit request_id=0`.

Any ideas?  Is there a way to know if my configuration changes are actually being read?

**Comment by kevinkreiser** [comment]
it seems very unlikely to me that the code is broken in this trivial way. i think the best way you could help us help you would be to post all of your steps and file contents. that way we can ask questions about specific items rather than continue to take stabs in the dark haha.

**Comment by nilsnolde** [comment]
in fact we're testing for that (almost) exact config change in the docker repo and the tests just passed a few hours ago: https://github.com/gis-ops/docker-valhalla/blob/a503d556a75661a644c25b16fa82eafa89b3f963/tests/test.sh#L80-L87

best way to help is for you to post:
- exact docker/docker-compose command (if compose, also the yml)
- the directory lists for the volume you mount into the `custom_files` directory of the container

**Comment by brad-4k** [comment]
> in fact we're testing for that (almost) exact config change in the docker repo and the tests just passed a few hours ago: https://github.com/gis-ops/docker-valhalla/blob/a503d556a75661a644c25b16fa82eafa89b3f963/tests/test.sh#L80-L87
> 
> best way to help is for you to post:
> 
> * exact docker/docker-compose command (if compose, also the yml)
> * the directory lists for the volume you mount into the `custom_files` directory of the container

Nils, thank you for your reply and the hard work.

I'm rebuilding my databases now (just added one more PBF) so I'm not sure if the custom_files directory will be complete but I'll show what I have so far:

Compose:  I'm just pulling a pre-built from _docker.pkg.github.com/gis-ops/docker-valhalla/valhalla:latest_ and running with: `docker run -v $PWD/custom_files:/custom_files -p 8002:8002 --name valhalla_latest docker.pkg.github.com/gis-ops/docker-valhalla/valhalla:latest`

Looking at the files in the `custom_files` directory, I just saw `valhalla.json` and I see that it has max_distance files in there.  Is that the file that the executable is reading?  I read above that I need to change it in `valhalla_build_config`, which I did, but those values are not reflected in `valhalla.json`.  I'm guessing I've been changing them in the wrong place?

**Comment by nilsnolde** [comment]
Jep that’s it then. Our docker image provides a lot of magic dust, you shouldn’t ever have to go into the container itself and change anything in there. It should all be controlled via environment variables and/or container restarts. 

If you change smth in the exposed valhalla.json, then restart the container and it’ll take effect. We won’t let you change any of the data paths though as they’re all relative to the container internals.

Nit: try to not quote entire comments in your comment, that adds quite of cognitive overhead (at least for me).

**Comment by brad-4k** [comment]
Nils, great, thank you.  Once my rebuild is complete I'll try that.  Thank you.

**Comment by brad-4k** [comment]
Nils, I was able to try it on another instance that I have running and it works great.  Thanks again
![Screen Shot 2022-07-14 at 3 47 58 PM](https://user-images.githubusercontent.com/78495562/179101017-b3b73f40-3eef-482a-98d5-16032901ea16.png)
!

**Comment by picazzo72** [comment]
If you wish to create a Docker image with the expanded trace-max-distance, you can edit the scripts/configure_valhalla.sh file from https://github.com/gis-ops/docker-valhalla where the config file is created by valhalla_build_config with an extra option eg. --service-limits-trace-max-distance 600000.
