### ISSUE TITLE
Hot traffic tiles update is not visible until restart (possibly k8s + NFS problem)

### ISSUE THREAD

**Issue by alexey-gl** [valhalla/valhalla#3347]
Hello
I'm trying traffic tiles feature of Valhalla and doing hot update of traffic tiles tar.
Locally everything works fine. But server deployment failed from time to time.
Server infrastructure: k8s and shared NFS storage with graph and traffic tars.
Valhalla and separate traffic tiles update service are two different pods in k8s cluster.
From time to time traffic tiles updates is not visible by Valhalla until restart.

I suppose it is NFS problem, but do not have proofs.
Could you recommend please how to debug this and how to properly use infrastructure with Valhalla traffic feature.

**Comment by danpat** [comment]
If you're writing to the traffic.tar file on one box on an NFS volume, and expecting the written pages to appear on other boxes with the same NFS volume mount appeared, then it's entirely up to NFS and the kernel to propagate those disk pages to other boxes.

This approach should in theory work, but it feels a bit fragile - delays in flushing pages on the writer, lost network packets, how the readers invalidate locally cached pages in response to remote NFS writes - these all feel like points the flow could break down.

**Comment by alexey-gl** [comment]
@danpat Thank you for comments! I feel it is necessary to think about another storage and services cluster architecture.
