### ISSUE TITLE
Running with more than 2 threads

### ISSUE THREAD

**Issue by iddqd2d** [valhalla/valhalla#3358]
The app for North America (download pbf from: https://download.geofabrik.de/north-america.html) runs perfectly with one or 2 threads, unfortunately, when I try to run with more than 2 threads the app crashes and I have different errors every time. Screenshot with errors is attached. My VDS has 24 CPU cores, 100 Gb RAM.
 I have tried to run on my own server which has 6 CPU cores and 24Gb RAM and I had still the same errors.

![image](https://user-images.githubusercontent.com/40464324/137309133-f855ed56-2688-43f5-91cd-e3afd4d8f560.png)

**Comment by kevinkreiser** [comment]
are you running inside of docker using one of our docker images or did you build the code from source, what is the state of the code that you are running?

**Comment by kevinkreiser** [comment]
@iddqd2d it looks like mmap cant map the elevation tiles. we semi-recently merged #3120 which did touch a lot of that code. i would suggest you try the commit before that merge and build that.  you should be able to just do `git checkout 48408b1de22d8c647cc456180008aae16d8d7552` to do that. let me know if that allows you to start up with elevation. if not we'll have to figure out what is going on with mmap on your system (could be ulimit you need to change)

**Comment by iddqd2d** [comment]
....
denis@testvm2:~$ git clone https://github.com/valhalla/valhalla
Cloning into 'valhalla'...
remote: Enumerating objects: 94553, done.
remote: Counting objects: 100% (4348/4348), done.
remote: Compressing objects: 100% (1419/1419), done.
remote: Total 94553 (delta 3278), reused 3829 (delta 2917), pack-reused 90205
Receiving objects: 100% (94553/94553), 117.92 MiB | 45.12 MiB/s, done.
Resolving deltas: 100% (66233/66233), done.
denis@testvm2:~$ cd valhalla
denis@testvm2:~/valhalla$ git checkout 48408b1de22d8c647cc456180008aae16d8d7552
Note: switching to '48408b1de22d8c647cc456180008aae16d8d7552'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 48408b1de update base docker image before building (#3233)

denis@testvm2:~/valhalla$ git submodule sync
denis@testvm2:~/valhalla$ git submodule update --init --recursive
Submodule 'OSM-binary' (https://github.com/scrosby/OSM-binary.git) registered for path 'third_party/OSM-binary'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Submodule 'third_party/cpp-statsd-client' (https://github.com/vthiery/cpp-statsd-client) registered for path 'third_party/cpp-statsd-client'
Submodule 'third_party/date' (https://github.com/HowardHinnant/date.git) registered for path 'third_party/date'
Submodule 'third_party/dirent' (https://github.com/tronkko/dirent) registered for path 'third_party/dirent'
Submodule 'third_party/fastcov' (https://github.com/RPGillespie6/fastcov.git) registered for path 'third_party/fastcov'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/libosmium' (https://github.com/osmcode/libosmium.git) registered for path 'third_party/libosmium'
Submodule 'third_party/microtar' (https://github.com/rxi/microtar.git) registered for path 'third_party/microtar'
Submodule 'third_party/protozero' (https://github.com/mapbox/protozero.git) registered for path 'third_party/protozero'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/pybind11'
Submodule 'rapidjson' (https://github.com/miloyip/rapidjson) registered for path 'third_party/rapidjson'
Submodule 'third_party/robin-hood-hashing' (https://github.com/martinus/robin-hood-hashing.git) registered for path 'third_party/robin-hood-hashing'
Cloning into '/home/denis/valhalla/third_party/OSM-binary'...
Cloning into '/home/denis/valhalla/third_party/benchmark'...
Cloning into '/home/denis/valhalla/third_party/cpp-statsd-client'...
Cloning into '/home/denis/valhalla/third_party/date'...
Cloning into '/home/denis/valhalla/third_party/dirent'...
Cloning into '/home/denis/valhalla/third_party/fastcov'...
Cloning into '/home/denis/valhalla/third_party/googletest'...
Cloning into '/home/denis/valhalla/third_party/libosmium'...
Cloning into '/home/denis/valhalla/third_party/microtar'...
Cloning into '/home/denis/valhalla/third_party/protozero'...
Cloning into '/home/denis/valhalla/third_party/pybind11'...
Cloning into '/home/denis/valhalla/third_party/rapidjson'...
Cloning into '/home/denis/valhalla/third_party/robin-hood-hashing'...
Submodule path 'third_party/OSM-binary': checked out '4e32fa236e919be5bb8dbb323437f026f24e5853'
Submodule path 'third_party/benchmark': checked out 'e991355c02b93fe17713efe04cbc2e278e00fdbd'
Submodule path 'third_party/cpp-statsd-client': checked out '8cc00d0bba3f53c1966fe4e199d032c9c183048d'
Submodule path 'third_party/date': checked out 'a2fdba1adcb076bf9a8343c07524afdf09aa8dcc'
Submodule path 'third_party/dirent': checked out '287ba928bfe9d20796bf0428d449abc8d6f29d79'
Submodule path 'third_party/fastcov': checked out '1128b0f82898df32381a7f7e47a54023a0711e5b'
Submodule path 'third_party/googletest': checked out 'e2239ee6043f73722e7aa812a459f54a28552929'
Submodule path 'third_party/libosmium': checked out '336001aba7f29d65f24a53799895b9c7f16ee8a2'
Submodule 'test/data-tests/osm-testdata' (https://github.com/osmcode/osm-testdata) registered for path 'third_party/libosmium/test/data-tests/osm-testdata'
Cloning into '/home/denis/valhalla/third_party/libosmium/test/data-tests/osm-testdata'...
Submodule path 'third_party/libosmium/test/data-tests/osm-testdata': checked out '3917f6847037af862018aa0af449e19794746ead'
Submodule path 'third_party/microtar': checked out '27076e1b9290e9c7842bb7890a54fcf172406c84'
Submodule path 'third_party/protozero': checked out '7487f8109acc8637b48e3cb291784cd58f943a1c'
Submodule path 'third_party/pybind11': checked out '8de7772cc72daca8e947b79b83fea46214931604'
Submodule path 'third_party/rapidjson': checked out '73063f5002612c6bf64fe24f851cd5cc0d83eef9'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'third_party/rapidjson/thirdparty/gtest'
Cloning into '/home/denis/valhalla/third_party/rapidjson/thirdparty/gtest'...
Submodule path 'third_party/rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
Submodule path 'third_party/robin-hood-hashing': checked out 'f2cae2e6b8231c46fe9c324e31b0a1f64e0de8c6'
....
----------------------------------------
Did I use it correctly? The result has not changed

**Comment by Rishikeshsynosys** [comment]
did you figure it out ?

**Comment by hb0** [comment]
[Here](https://github.com/valhalla/valhalla/issues/4770#issuecomment-2482592325) someone suggested that running valhalla with too many threads might cause the issue. I'm running this on my dev notebook with 22 threads. I don't seem to have the issue on the server VMs with 8 threads. Haven't found a solution yet.
