### ISSUE TITLE
Restriction relations without foot type applied for pedestrian routing

### ISSUE THREAD

**Issue by szymone** [valhalla/valhalla#3403]
Hi,
It seems that restrictions without foot type specified are also applied tor pedestrian routing. However according to https://wiki.openstreetmap.org/w/index.php?title=Relation:restriction, point "Turn restrictions do not apply to pedestrian unless the type or key is restriction:foot", this shouldn't be done. Any comments on this? Is this a bug or feature?

I assume this is related to OSM tags processing in Lua, https://github.com/valhalla/valhalla/blob/8921a1d22368e3198dd157a9587447cacfefcd00/lua/graph.lua#L2129.

**Comment by nilsnolde** [comment]
can you leave an example here to reproduce? I doubt we do _any_ turn restrictions for pedestrian, never heard of such a thing :sweat_smile: usually road segments are or aren't accessible to the public pedestrian, let's see the example

**Comment by szymone** [comment]
Route query: {"locations":[{"lat":49.8178193,"lon":19.2173556},{"lat":49.8181684,"lon":19.2170585}],"costing":"pedestrian"} Restriction: https://www.openstreetmap.org/relation/8349076#map=17/49.81725/19.21688
Result: 

![image](https://user-images.githubusercontent.com/10035692/141799838-f30429cb-c1fa-480e-b5a8-81f5d37c7e2e.png)

Both roads are accessible for pedestrians, however they shouldn't be forced to make a loop to be able to turn right. 

Another example is in this place: https://www.openstreetmap.org/#map=18/49.72233/18.81876. When you route backward, the result is ok.

![image](https://user-images.githubusercontent.com/10035692/141800998-91908fc9-67b7-459d-9fcf-0959416af150.png)

What I've meant in this issue is that relations with restriction key shouldn't be appleid for pedestrian routing and only these ones with restriction:foot key should be.

**Comment by kevinkreiser** [comment]
in my opinion there are two possibilities:

1. we have a bug where we are accidentally applying restrictions to modes where they shouldn't apply. this would either happen at data creation time (seems unlikely) or in dynamiccost.h/cc where we check restrictions (seems more likely)
2. there's something wrong with the routing algorithm that causes it to not expand that sharp right (seems unlikely given the second example which is a very slight right)

@gknisely can you take a look? this seems pretty serious

**Comment by dnesbitt61** [comment]
this commit https://github.com/valhalla/valhalla/commit/c3978097620f3b12593091749a8cacabe42f3f59 added the line:
 ((pred.restrictions() & (1 << edge->localedgeidx())) && !ignore_restrictions_) ||

Prior to that pedestrian costing never checked simple restrictions (which do not have any mode specific identification - meaning they would apply to all simple restrictions. This line should be removed. Pedestrian costing should only check "complex" restrictions - those involving multiple edges or those that apply only to specific travel modes.

**Comment by gknisely** [comment]
Yes not good.  I will create a PR

**Comment by szymone** [comment]
@gknisely Have you already started working on this PR?

**Comment by gknisely** [comment]
@szymone no, but feel free to remove, test it out, and PR it if you have a minute.
