### ISSUE TITLE
Release Builds Failing Filtering Tests

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3445]
https://app.circleci.com/pipelines/github/valhalla/valhalla/8467/workflows/ad690f8b-2ff6-4221-9655-510f729fd1a0/jobs/50188

```
[----------] Global test environment tear-down
[==========] 68 tests from 4 test suites ran. (19072 ms total)
[  PASSED  ] 61 tests.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] SearchFilter.Heading
[  FAILED  ] SearchFilter.PreferredSide
[  FAILED  ] SearchFilter.MaxRoadClass
[  FAILED  ] SearchFilter.MinRoadClass
[  FAILED  ] SearchFilter.ExcludeTunnel
[  FAILED  ] SearchFilter.ExcludeBridge
[  FAILED  ] SearchFilter.ExcludeRamp
```

```
[ RUN      ] SearchFilter.MinRoadClass
[          ] Valhalla request is: {"locations":[{"lat":-0.002695,"lon":0.000898},{"lat":-0.000898,"lon":0.003593,"search_filter":{"min_road_class":"motorway"}}],"costing":"auto"}
unknown file: Failure
C++ exception with description "No suitable edges near location" thrown in the test body.
[  FAILED  ] SearchFilter.MinRoadClass (26 ms)
```

Some how there are no tiles there for the tests to run against?

**Comment by mandeepsandhu** [comment]
@kevinkreiser this is caused by another [unrelated test](https://github.com/valhalla/valhalla/blob/master/test/gurka/test_route.cc#L835)  creating the same map file (since tests are run in parallel, they can trample over each other). Whenever tiles go missing, its almost always more than 1 tests sharing the same map tile dir.

**Comment by mandeepsandhu** [comment]
putting a fix in https://github.com/valhalla/valhalla/pull/3446 as I was seeing repeated search_filter test failures.

**Comment by kevinkreiser** [comment]
Ah yep that will do it thanks!
