### ISSUE TITLE
Getting error while run of Valhalla library .so file load in android studio

### ISSUE THREAD

**Issue by singhisking11** [valhalla/valhalla#3448]
<div class="_rp_T5 ms-bg-color-themeLight" style="background-color: rgb(199, 224, 244); padding: 10px 10px 10px 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="_rp_L5 ms-font-weight-regular ms-font-color-neutralPrimary" style="font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; color: rgb(51, 51, 51); font-size: 14px; overflow-wrap: break-word;">(No subject)</span></div><div class="_rp_U5" style="padding: 12px 16px 49px 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div><div class="_rp_P5" style="min-height: 70px; min-width: 200px; width: 329px; padding-bottom: 21px; display: block;"><div class="_rp_J2" style="min-width: 200px; width: 329px; display: block;"><div class="_rp_O2" style="float: left; width: 329px;"><div></div><div><div class="_rp_N2" style="margin-top: 14px; white-space: nowrap; overflow: hidden;"><span class="ms-font-xl owa-color-neutral-orange" style="color: rgb(216, 35, 0); font-family: wf_segoe-ui_light, &quot;Segoe UI Light&quot;, &quot;Segoe WP Light&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; font-size: 21px; font-weight: normal;">[Draft]</span><span class="_rp_M2 ms-font-s" style="color: rgb(51, 51, 51); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; font-size: 12px; font-weight: normal; display: block;">This message hasn't been sent.</span></div><div class="_rp_L2 ms-font-s owa-color-neutral-orange" style="color: rgb(216, 35, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; font-size: 12px; font-weight: normal; padding: 5px 0px 8px;"><span>Saved on:</span><span> </span><span>Tue 07/12/2021 10:32</span></div></div><div class="_rp_Q2" style="text-align: right; display: block; float: right; width: auto; margin-top: 5px;"><button autoid="_rp_h" type="button" class="_rp_R2 o365button" aria-label="Delete" style="background: transparent; border-width: 0px; padding: 0px 0px 0px 17px; font-size: 15px; cursor: pointer !important; float: right; z-index: 2;"><span class="owaimg ms-Icon--trash ms-icon-font-size-32-circle ms-fcl-ns-b ms-bcl-ns-b ms-bg-transparent ms-icon-font-circle" style="display: inline-block; line-height: 1; background: transparent;"></span></button><button autoid="_rp_i" type="button" class="_rp_R2 o365button" aria-label="Continue editing" style="background: transparent; border-width: 0px; padding: 0px 0px 0px 17px; font-size: 15px; cursor: pointer !important; float: right; z-index: 2;"><span class="owaimg ms-Icon--pencil ms-bcl-ns-b ms-bg-transparent ms-icon-font-circle ms-fcl-ns-b ms-icon-font-size-32-circle" style="display: inline-block; line-height: 1; background: transparent;"></span></button></div><div class="_rp_X2" style="margin-top: 15px; margin-bottom: 15px; float: left; width: 329px;"></div></div></div><div class="_rp_T2" style="position: relative; clear: both; padding-top: 0px; top: -1px;"><div><div class="attachmentWell"><div autoid="_ay_0" class="_ay_a" style="position: relative; user-select: none;"><div role="group" tabindex="0" aria-label="1 attachments (300 KB)"><div class="_ay_a2"><div>

 
--

</div></div></div></div><div class="buttonBar"><div class="_ay_e" style="display: inline-block; vertical-align: bottom; white-space: nowrap;"></div></div><div></div></div></div></div></div><div><div autoid="_rp_M" class="_rp_Q5" style="overflow-wrap: break-word; clear: both;"><div class="_rp_Q5 rpHighlightAllClass rpHighlightBodyClass" id="Item.MessageNormalizedBody" style="overflow-wrap: break-word; clear: both; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif, serif, EmojiFont;"><div class="rps_81cc"><div><div dir="ltr"><div id="x_divtagdefaultwrapper" dir="ltr" style="font-size: 12pt; color: rgb(0, 0, 0); font-family: Calibri, Helvetica, sans-serif, serif, EmojiFont;"><p style="margin-top: 0px; margin-bottom: 0px;"></p><div>   VM has multidex support, MultiDex support library is disabled.<br>E/Start: &gt;&gt;&gt;&gt;Lib Init<br><b><span style="color: rgb(255, 0, 0);">E/art: dlopen("/data/app/com.baeldung.jni-2/lib/x86_64/libvalhalla-odin.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "/data/app/com.baeldung.jni-2/lib/x86_64/libvalhalla-odin.so" (built with --hash-style=gnu?)</span></b></div><div><b><br><span style="color: rgb(255, 0, 0);">E/Error: &gt;&gt;&gt;&gt;dlopen failed: empty/missing DT_HASH in "/data/app/com.baeldung.jni-2/lib/x86_64/libvalhalla-odin.so" (built with --hash-style=gnu?)</span></b><br>W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable<br>I/art: Rejecting re-init on previously-failed class java.lang.Class&lt;android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper&gt;<br>    Rejecting re-init on previously-failed class java.lang.Class&lt;android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper&gt;<br><b><span style="color: rgb(255, 0, 0);">E/art: No implementation found for void com.baeldung.jni.MainActivity.sayHello__() (tried Java_com_baeldung_jni_MainActivity_sayHello_1_1 and Java_com_baeldung_jni_MainActivity_sayHello_1_1__)</span><br><span style="color: rgb(255, 0, 0);">D/Error: &gt;&gt;&gt;&gt;No implementation found for void com.baeldung.jni.MainActivity.sayHello__() (tried<span> </span></span></b>Java_com_baeldung_jni_MainActivity_sayHello_1_1 and Java_com_baeldung_jni_MainActivity_sayHello_1_1__)<br>D/OpenGLRenderer: Render dirty regions requested: true</div></div></div></div></div></div></div></div></div></div>

**Comment by kevinkreiser** [comment]
im sorry but this just is not an actionable issue. i understand you want to try to call c++ from java in android. i suggest that maybe you start with a smaller c++ project and make sure you can call that properly first. then when you are ready to try valhalla, i would suggest that you disable building most things,  you can check the readme to see all the stuff you can disable. then all you should need to do is call add_subdirectory in cmake and that should be able to add valhalla to your jni cmake project. good luck
