### ISSUE TITLE
planet build fails to reclassify links

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3473]
just had a failed planet build on the fossgis instance with 
```
2021/12/25 08:24:57.459352 [INFO] Reclassifying_V2 link graph edges...
2021/12/25 08:25:50.588545 [INFO] Class: 0 exit count = 181800
2021/12/25 08:25:50.588564 [INFO] Class: 1 exit count = 318539
2021/12/25 08:25:50.588566 [INFO] Class: 2 exit count = 398318
2021/12/25 08:25:50.588568 [INFO] Class: 3 exit count = 421592
2021/12/25 08:25:50.588569 [INFO] Class: 4 exit count = 327793
2021/12/25 08:25:50.588570 [INFO] Class: 5 exit count = 57751
2021/12/25 08:25:50.588572 [INFO] Class: 6 exit count = 106547
2021/12/25 08:25:50.588573 [INFO] Class: 7 exit count = 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exceeding kMaxLinkEdges in ReclassifyLinks
```

looking it up: one node having more than 16 outgoing link edges sounds weird.. does someone have an opinion what's wrong, how to avoid? maybe I should print the osm id and see which one it is..

must've been introduced to osm in the past 1.5 days since the last planet build. I didn't update valhalla code in the past 6 weeks.

**Comment by kevinkreiser** [comment]
Getting information about where it is will help for reproducing it for sure. Re-reviewing the code will also help for me too

**Comment by nilsnolde** [comment]
hahah jeeez, got the bastard: https://www.openstreetmap.org/way/1014945636#map=19/32.54232/-117.02897

it's the border lanes between US-Mexico, edited 3 days ago.. overambitious mapping IMO but looks fair.. huge changeset, so many deleted ways. 

I'll have a look soon what's the best solution here for us, in the meantime I'll switch off link reclassification..

**Comment by nilsnolde** [comment]
Or rather have a more than superficial look if that’s not a osm issue.. link might not be the best classification here..
