### ISSUE TITLE
ClosestPoint() - lat and long of 'point' variable

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3477]
I'm working on converting the ClosestPoint() function to JavaScript for a turn-by-turn routing application with guidance from Kevin.

My team and I wanted to double check the intended lat and long values of the variable 'point' that's set in this if/else sequence: https://github.com/valhalla/valhalla/blob/8921a1d22368e3198dd157a9587447cacfefcd00/src/midgard/pointll.cc#L179

Depending on the if/else case, point can be set to {u.lng(), u.lat()}, {v.lng(), v.lat()}, or {u.lng() + bx * scale, u.lat() + by * scale}. As you can see, all of these start with the first element being a longitude value. 

However, I was under the impression that the first value of a GeoPoint (which point is, given that it is later passed into approx.DistanceSquared()) is always the latitude. Is that not correct? Or is it that for the case of point, the first element, which is something .lng() with some variation, is the latitude value we are looking for?

Thanks!

**Comment by nilsnolde** [comment]
I'm not entirely sure if I understand the confusion, but sounds like the old lon/lat conundrum.. never gets old ;)

valhalla's PointLL is short for PointLonLat, we (thankfully) use the modern lon/lat. see here for the "proof": 
https://github.com/valhalla/valhalla/blob/ba50b993cc02be4e610f0231a71a40b3153b936c/valhalla/midgard/pointll.h#L55-L57

not generally arguing against cooking your own algos, but why not use turfjs or so (I think they're pretty modular by now, so you can choose & pick)?

**Comment by kungfu303** [comment]
Ah, gotcha makes sense. Yes, it is the old lon/lat conundrum. We'll consider using turfjs, thanks!
