### ISSUE TITLE
Changing log configuration requires full tile rebuild

### ISSUE THREAD

**Issue by PepijnK** [valhalla/valhalla#3479]
Currently it is not possible to simply switch on/off color encoding of log-level without thrashing the tiles. Ideally the log color attribute is read from the JSON-config file every time valhalla starts up.

**Comment by nilsnolde** [comment]
I’m probably misunderstanding smth, but what doesn’t work for you with setting color encoding in the config, eg https://github.com/valhalla/valhalla/blob/ba50b993cc02be4e610f0231a71a40b3153b936c/scripts/valhalla_build_config#L59?

Even if you wanna change the log level, you don’t have to rebuild the _tiles_, but the _code_, since it’s compile-time config (unfortunately).

**Comment by PepijnK** [comment]
So that means there is no runtime config for color coding? I'm a bit confused as I see `color=true` in the logging section of most `valhalla.json` files listed in the repo (https://github.com/valhalla/valhalla/search?l=JSON&q=color).

When I try to search for terms like `logging` of `configuration` in https://valhalla.readthedocs.io/en/latest, I get TODO's or broken links.

**Comment by kevinkreiser** [comment]
Log level is a build time decision.
Log configuration is a runtime decision but can be only configured once per invokation, IE you have to restart the program if you want to change the log config

**Comment by PepijnK** [comment]
Yeah, I'm talking about log configuration. Somehow the color seems to be applied even after restart
I've tried:
```
"logging": {
    "color": false    
}
```

```
"logging": {
    "color": "False"
}
```
And restarted the container but still, the log output is color-coded.

**Comment by nilsnolde** [comment]
What program are you running? There’s some 3-4 logging configs for the different modules and depends what program you’re running which one applies. If you don’t want to dig in, just change them all..

**Comment by PepijnK** [comment]
We're using a slightly modified version of https://github.com/valhalla/valhalla/blob/7e80a71c5034037746b02864e62899d1a4ce6292/test/win/valhalla.json

**Comment by nilsnolde** [comment]
You edited your responses quite a bit, now it’s a little clearer what you’re doing. 

Just had a 2 secs look: so the image is simply using valhalla_service, and there’s a tiny bug there. You’d need to provide a config option that doesn’t exist anymore: tyr.logging. Just copy one of the others in the config JSON: add the top level tyr member, add the full logging config to it and you should be fine. 

Still needs to be cleaned up eventually.

**Comment by PepijnK** [comment]
Perfect!
I've added the following section to my `valhalla.json` config file:
```
  "tyr.logging": {
    "color": false,
    "type": "std_out"
  }
```
And I have no color coding anymore! Thanks, now my logs are also readable in the remote logging system :)

**Comment by PepijnK** [comment]
Same as 
```
"tyr": {
    "logging": {
      "color": true,
      "type": "std_out"
    }
  }
  ```

**Comment by nilsnolde** [comment]
meh, I'll let the merge close it..
