### ISSUE TITLE
Reg:Cross-compilation

### ISSUE THREAD

**Issue by anantha-vidhya** [valhalla/valhalla#3480]
DId any one cross-compiled this to arm board using tisdk based linux-devkit?
if so please let me know the steps in detail.
Thanks & Regards
A.N.V.Lavanya

**Comment by kevinkreiser** [comment]
TI as in Texas instruments? Can we get valhalla running on a calculator? Seriously though have you tried it? We link only a handful of libs like protobuf curl and zlib. I think we have we should have cmake options to disable almost everything but protobuf. So you'll probably need to vendor or prebuild protobuf with that compiler

**Comment by anantha-vidhya** [comment]
Yeah i am trying to cross-compile this to am437x sbc .
- Cloned this source code .
- I created one build folder in side the cloned source code folder.
- Then given this command
 **cmake -B /home/futura/Downloads/valhalla-master/build -DCMAKE_BUILD_TYPE=Release.**
Got this error as below.
 
**C Make Error: The source directory "/home/futura/Downloads/Valhalla-master/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the C Make GUI.**
-Then i stopped for compiling to desktop itself.
So i didn't went to arm 
for arm i will do like as below:
- I will export variables by sourcing  tisdk folder linux-devit/environment-setup
- Later i will also exported 3 more variables manually like export PATH,CROSS_COMPILER,ARCH variables with devkit /sysroot/..toolchain path
- Then i will use **cmake -B /home/futura/Downloads/valhalla-master/build -DCMAKE_BUILD_TYPE=Release.**
- If it went well i need to do 
    **make -C build -j$(nproc)
    sudo make -C build install**
as shown in github notes you mentioned.


please let me know what is reason for above error did i am missing any thing else for desktop?
Also let me know the procedure i am preferring to cross-compile valhalla is correct or not.

Thanks & Regards
A.N.V.Lavanya

**Comment by kevinkreiser** [comment]
Your cmake invokations look wrong. You should go learn a bit about how to tell cmake where to look for build resources as well as where to output its results. To me it looks like you are messing the former and only have the latter. You need both

**Comment by nilsnolde** [comment]
some cleanup;)
