### ISSUE TITLE
calling /route as reroute in JS/React delay with fetch()

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3488]
We have a mobile application that involves bike routing.

When a user goes off course from the route (which comes from Valhalla's /route endpoint's bike directions), we call the /route endpoint with the user's new GPS location. 

However, we're noticing that the API call in our mobile application (using React Native/JS's fetch() function) takes much longer to attain the API's response than say by calling the /route endpoint from Postman or the browser. 

Any ideas why? According to my debugging, its just hanging on the fetch() call and no other pre-processing or post-processing step...

**Comment by TimMcCauley** [comment]
[This may help you](https://github.com/facebook/react-native/issues/28283), I do think this is a client side issue and has nothing to do with Valhalla.

**Comment by nilsnolde** [comment]
Don’t think so either. Good luck @kungfu303 !
