### ISSUE TITLE
europe and north-america fail building

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3498]
we had this issue reported downstream in the docker repo: https://github.com/gis-ops/docker-valhalla/issues/53

europe and NA build fine separately, but fail to verify the sequence when built together here:
https://github.com/valhalla/valhalla/blob/3558c952b4dfc7051d912f3bc50a9b9d49aae936/valhalla/midgard/sequence.h#L285-L290

how can that even happen that it fails there? some objects have been written to that file that don't belong there for some reason?

**Comment by kevinkreiser** [comment]
it could happen if you run out of diskspace. basically this error says, i see your file is 1234567 bytes long, but the type of object you have in this sequence is 12 bytes long. 1234567 is not a multiple of 12, therefor your sequence file is broken.

**Comment by nilsnolde** [comment]
jep, that was correct, thanks @kevinkreiser
