### ISSUE TITLE
Tiles build stuck at enhancement stage

### ISSUE THREAD

**Issue by AlexTheKing** [valhalla/valhalla#3499]
Hi!

I'm trying to build valhalla tiles for Europe and Asia, using
`valhalla_build_tiles -c /custom_files/valhalla.json -s enhance /custom_file/asia-latest.osm.pbf /custom_file/europe-latest.osm.pbf`

but enhancement phase stucks somewhere after this logs:

> 2022/01/05 01:39:22.533713 [INFO] Adding Restrictions at level 2
2022/01/05 02:43:27.083921 [INFO] --Forward restrictions added: 12144
2022/01/05 02:43:27.083958 [INFO] --Reverse restrictions added: 12113
2022/01/05 02:43:27.496111 [INFO] Adding Restrictions at level 1
2022/01/05 02:43:48.350447 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376455 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376545 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376643 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376715 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376794 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376852 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.376948 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377010 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377069 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377151 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377298 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377360 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377436 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377498 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.377560 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.447208 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.447478 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267
2022/01/05 02:43:48.447544 [WARN] Tried to exceed max vias per restriction(reverse).  Way: 0/3377/153267

I've tried to wait for a couple of days for valhalla to accomplish this task, but have had no luck.
Unfortunately full tiles rebuild also did not help.

I'm using `gisops/valhalla:latest` image with the digest `sha256:17c101c48ae1b5fbfc4d1633e6b34ff99bf95e88ad2b24207830b974c526b671`.

Hashes of the corresponding PBF files:
1) Europe
MD5: 1a2ab05df8ac47fcdd712f2f813517d3
SHA1: 8ca0bcd94d554f529d5a78b43b99357ec1c79615
SHA256: c1072322ae304d20b79ec52cf2d78158e9574dc4f1c06e75f7251a4a51a7e5b4
 2) Asia
MD5: 59b14109aa5f29e65fd9ce20b7282479
SHA1: c7bfb151653040e0bc2fb3f0e7cc1b181066ccc6
SHA256: f4bf3d0da4a3e0131630f26b8ea4d08928df593b53898eedd26c4363d4734c30

Currently, I'm trying to accomplish the enhancement stage using `gisops/valhalla:3.1.4` and will give you an update after.

Could you please share some insights of the possible root cause here and/or possible fixes/workarounds?

I would really appreciate any help!
Thank you in advance!

Best Regards,
Alex

**Comment by nilsnolde** [comment]
hm, weird, we just had a similar issue in #3498 with multiple pbfs (and the `3.1.4` tag) but at a totally different stage.. our docker image tests work on two pbfs as well, but that's only andorra & luxemburg. wanna say, it's not inherently multiple pbfs causing weird behavior.

did you try the files separately @AlexTheKing ?

**Comment by AlexTheKing** [comment]
Yeah, Europe-only configuration works awesome, but I need Asia as well.

I already had a look at #3498, but that seems not to be my case as I have no errors in the logs, it looks like it just stucks.

**Comment by AlexTheKing** [comment]
Oh, forgot to mention: `htop` shows that one core is almost always 100% busy with the valhalla task, but I suppose the enhancement for the two PBFs of ~35 GB in total cannot take so much time (around 4 days).

Server configuration is the following:
CentOS 7.9.2009
32 GB RAM
4 cores
340 GB SSD

**Comment by kevinkreiser** [comment]
yeah the enhancer does a bunch of graph traversal, and it should do so with cutoffs but i guess its possible there is some infinite loop (at least that is what comes to mine given the description about one core sticking to 100%). if you still have the intermediate files, i would start the build at the enhance stage with those using gdb and then when that scenario happens, i would stop the execution and see where it is when this is happening.

another thing to try would be an older version of asia if you can get it. this is most certainly a data driven phenomenon so trying a different version of the data may work around it and at least give us a clue that its something particular about the data

**Comment by AlexTheKing** [comment]
@kevinkreiser the truth is somewhere near.

I've got now the following error during the enhancement stage, so it seems you are right:
> 2022/01/06 17:20:17.479384 [INFO] Adding Restrictions at level 2
terminate called after throwing an instance of ‘std::runtime_error’
 what(): GraphTile NodeTransition index out of bounds: 752492,2,0 transitioncount= 0
Aborted (core dumped)

I'll try to build with 3.1.4 and new versions of PBFs and will let you know if the problem is fixed.

Thank you!

**Comment by kevinkreiser** [comment]
that error there means the data is somehow corrupted. somehow the tile data, at least one of the tiles, or some other part of the code, thinks that there are hierarchies in the tiles which cannot be the case at this point because hierarchies are only added after the enhancer. either that or some other part of the code thinks that a node has transitions when it doesnt. to be sure you need to run this with gdb and then we can look at the call stack when it throws by running the gdb command `where`

**Comment by nilsnolde** [comment]
other than the unlikely case of an extraction failure by geofabrik (presumably?) or a corruption during download (seems like you checked that though @AlexTheKing ) it's likely not a data error, our planet keeps building fine with daily updated osm data.

**Comment by AlexTheKing** [comment]
Unfortunately, it has also stucked at the same place with the new versions of PBFs as well. I'm not so experienced with `gdb`, so I suppose that would be the latest thing for me to check out.

As @nilsnolde said that the whole planet keeps building fine, I'll give it a try then. Hopefully this helps.

I'll keep you updated. Thank you!

**Comment by AlexTheKing** [comment]
Hello everyone!

I'm still at the building stage (I'm building the whole planet) and look forward to see the results (hopefully successful :)

Could you please share any ideas/working examples of the following: how can I track the progress except the provided logs?
E.g. the logs are showing, there are 171k tiles to build. If I count the number of .gph files - I can see the progress like 70k tiles from 171k are already built.
Or am I mistaken?

How do you do this?

I really appreciate your help! Thank you so much!

**Comment by nilsnolde** [comment]
There’s no really good way I’m aware of.. You’ll usually get more or less constant logs from tile building if you’re using default logging (sometimes a few hours nothing is logged). A planet build on 16 threads takes around 1.5 days max, but it’s not a linear relationship, some parts are not multithreaded.

**Comment by nilsnolde** [comment]
did the planet work for you @AlexTheKing ?

**Comment by AlexTheKing** [comment]
Excuse me for the delay. Yes, yesterday I was finally able to start the Valhalla service. The planet tiles were built successfully.
So it seems the problem is solved for me.

Thank you!

**Comment by nilsnolde** [comment]
ok great! then let's assume there really was smth borked with the data :crossed_fingers: ;)
