### ISSUE TITLE
Isochrone calculations: use fixed vehicle speed?

### ISSUE THREAD

**Issue by sfairgrieve** [valhalla/valhalla#3504]
Is there an easy way via costing options or other request options or some underlying service configuration to use the pedestrian/bicycle/vehicle's current known speed as the speed used in calculations rather than whatever gets derived from each OSM road segment?  I'm basically looking for a simple/more naive approach that assumes the vehicle is traveling at whatever speed it's currently traveling at independent of speed limits/assumptions about the road segments in question. The goal is to provide a near real-time measure of where a vehicle might be in the next few minutes if it continues to travel at its current rate.

**Comment by kevinkreiser** [comment]
with bicycle and pedestrian you can set the cycling and walking speeds repsectively. this should kind of do what you want though we do use other factors to perturb that speed (hilliness for example or roughness/difficulty of terrain). with automobiles we dont yet provide any such ability.

**Comment by sfairgrieve** [comment]
Thanks @kevinkreiser for the quick response!  If I was feeling adventurous, is this something that could be implemented using a custom cost model similar to the changes here:  https://github.com/valhalla/valhalla/pull/1756/files, or is it more complex than that?

**Comment by kevinkreiser** [comment]
it could be done by using a custom costing model or you could just add it as a new option to costing which would be less work:

1. add a new CostingOption called `fixed_speed` or something to the protobuf
2. add the parsing in dynamiccost.cc parsebasecostingoptions
3. go to each costing that you care about and modify its edgecost function with an `if` that says, if fixed_speed is set then use only that
4. add a unit test, i can elaborate if you decide to go this route

thats about it :smile:
