### ISSUE TITLE
demo server api is down

### ISSUE THREAD

**Issue by brandart** [valhalla/valhalla#3505]
the API of the demo server is currently unavailable. 

For every request I make at `https://valhalla1.openstreetmap.de/` I receive an `502 Bad Gateway` Response

**Comment by nilsnolde** [comment]
correct, see https://github.com/valhalla/valhalla/discussions/3373#discussioncomment-1924473

reminds me we'll have to somehow make it more visible that this is not the right repo for the public server (no worries @brandart ), in the absence of an actual repo, it's better to post here: https://github.com/gis-ops/valhalla-app/discussions. 

also it's flagged on https://valhalla.openstreetmap.de.

the server is toast, hetzner dedicated servers apparently have lots of problems recovering from system failures, rescue mode didn't help really. looks like we'll have to nuke the whole thing and set it up from scratch. now it bites me that I postponed the ansible setup, so now it's a big time investment which I'll try to do today, but no guarantees.

**Comment by nilsnolde** [comment]
well, actually this repo is fine maybe for notifying outages of the public server by pinning this issue whenever it's down (which shouldn't happen so much, this was a dumb and rare mistake). most people will probably naturally come to this repo to find out, no matter if we had an own repo or not. what do you think @kevinkreiser ?

**Comment by kevinkreiser** [comment]
I'm cool with it, it does seem like a logical place to look. :+1:

**Comment by nilsnolde** [comment]
up again
