### ISSUE TITLE
Override default lua transformation functions

### ISSUE THREAD

**Issue by azarz** [valhalla/valhalla#3513]
Hi!

I'm currently trying to migrate from OSRM to Valhalla. With OSRM, I'm using custom-made `osm` files with custom tags, and I'm able to process them with custom `lua` profiles. Reading through the documentation of `Mjolir`, I found [this section](https://github.com/valhalla/valhalla/blob/master/docs/mjolnir/tag_parsing.md#lua-tag-processing), which states 

> Valhalla comes with default `lua` transformation functions which can be found [here](https://github.com/valhalla/valhalla/tree/master/lua). If you'd like to override these you may do so by changing arguments in the `valhalla.json` configuration used with `valhalla_build_tiles`.

However I have not found the aforementioned `valhalla.json` arguments, and after reading through the repo issues (e.g. #2134, #800, #2020), it seems that overriding the `lua` is in fact not possible.

The direction I think I'm going to take is to make my custom tags match standard OSM ones, but first I'd like to be certain that overriding the `lua` functions is not possible.

Thank you for reading!

**Comment by nilsnolde** [comment]
I don't think you can change the lua simply with `valhalla.json`. maybe that was possible at some point. of course it can still be done, but I think you'd need to change some stuff in mjolnir's CMakeLists.txt (or edit the existing graph.lua). if you only add tags it shouldn't be a huge deal (as long as tags don't clash with existing tags of graph.lua). still: if you can I'd personally definitely go the way of converting the data into the OSM format, for many reasons. most importantly though if you do that you can use the PBF with the whole awesome software universe built around OSM reliably, that's a huge plus. 

plug: we do offer commercial services to convert arbitrary datasets to OSM format, you can PM me in case of interest.

**Comment by kevinkreiser** [comment]
Actually you can still change the lua by pointing at a different lua file on disk from your config file: https://github.com/valhalla/valhalla/blob/master/src/mjolnir/pbfgraphparser.cc#L1391-L1402

You need to put the file path in the `mjolnir` second of your config. But if the file you provided either wasnt found or cant be opened it will fall back to our built in lua.

I think this uncovers an issue that we may have never added that feature to the config generation tool. I also think that back when @noblige added it so many years ago, we didnt even have the config generation tool. Good news is, its easy to add back as an optional.

**Comment by nilsnolde** [comment]
Ah missed that one..

**Comment by kevinkreiser** [comment]
I should probably mention that over time we've been parsing more and more stuff directly in c++ and also it's quite hard to match all of the stuff we are doing in Lua with your own Lua without any documentation from us. I wouldn't be surprised if you got it mostly working but some stuff ended up missing or didn't work quite right for example. It's a non trivial amount of work and you'll probably still need to make changes to your source data or the c++ parsing unfortunately

**Comment by azarz** [comment]
Okay, thanks for all the info! I'll try to see if I manage to make a matching lua, and if I don't I'll change the scripts that generate the .osm files.

Thanks a lot for the quick reponses!
