### ISSUE TITLE
pedestrian costing options

### ISSUE THREAD

**Issue by sdigenis** [valhalla/valhalla#3514]
I have installed valhalla and i am running on my local machine and I'm trying to find a route between two locations with several costing options but the output is the same as if i had no costing options. (i have looked and the shortest option is false)

**Comment by nilsnolde** [comment]
we'll need the JSON of both requests to help.

**Comment by sdigenis** [comment]
im sending you the executable files

curl http://localhost:8002/route --data '{
    "locations":[
        {"lon":22.950968,"lat":39.368049},
        {"lat":39.365614,"lon":22.934920}
    ],
    "costing":"pedestrian", 
    "costing_options.pedestrian":[
       {"exclude_polygons":[
           [[22.936406135559086,39.36745800855762],[22.93706059455872,39.36778148934154],[22.937189340591434,39.36767366258005]],
           [[22.935730218887333,39.36720088173738],[22.935934066772464,39.366968637344094],[22.936041355133057,39.36705158185893]]],
           "use_ferry":1,
           "service_penalty":15,
           "service_factor":1,
           "shortest":false,
           "use_hills":0.5,
           "walking_speed":5.1,
           "walkway_factor":35,
           "sidewalk_factor":40,
           "alley_factor":2,
           "driveway_factor":5,
           "step_penalty":0,
           "max_hiking_difficulty":1}
        ],
    "language": "el",
    "units":"kilometers"
    }' | jq '.'

curl http://localhost:8002/route --data '{
    "locations":[
        {"lon":22.950968,"lat":39.368049},
        {"lat":39.365614,"lon":22.934920}
    ],
    "costing":"pedestrian", 
    "units":"kilometers"
    }' | jq '.'

The output for both of them is the same like the costing options are being ommited

**Comment by kevinkreiser** [comment]
The way you are specifying costing options in the first one is incorrect. It should be `"costing_options":{"pedestrian":{... ` notice the nesting, we don't have dots in our api fields

**Comment by sdigenis** [comment]
thank you. I have been struggling with it for so much time. In the documentation in the section 
Docs » Turn-by-Turn Route API » Public APIs » API Reference
there is this field saying that you indicate the costing options with a dot. 

"Costing methods can have several options that can be adjusted to develop the route path, as well as for estimating time along the path. Specify costing model options in your request using the format of costing_options.type, such as costing_options.auto."

Thank again a lot.

**Comment by kevinkreiser** [comment]
@sdigenis yeah its kind of hard to talk about nesting json without having to show the whole json. in this case the `foo.bar` is kind of like if you had the json object in javascript you would access it that way with the dot notation. apologies for the confusion.
