### ISSUE TITLE
trim expansion response for intervals less than 10 mins/kms

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3517]
now we finally wanted to make use of the dijkstra `/expansion` tracking and I realized it's really weird that we return huge geometries even though the request just asks for 1 minute isochrone. reason is that we add some buffer to user-specified max_mins/kms of 10 mins/kms, so dijkstra finds edges with higher cost.

just had a quick look but didn't see an elegant obvious way.. I'll leave it here for now, if anyone has an idea off the to of their head, I'd appreciate it

**Comment by kevinkreiser** [comment]
i think we could just call the callbacks if its outside of the original bounds. that way the algorithm proceeds in the same way but you dont actually see the extra edges. its hard to tell what the use-case is exactly though because maybe you want to know when things are visited similar to the original action i made for debugging (where order of operations is important)

**Comment by nilsnolde** [comment]
the use case is really the same as for isochrones: give me the road segments I can reach within a given time/distance interval. I'd claim that's the majority of intentions when calling expansion for isochrones, though semantically the name "expansion" is a little off for that. we could wrap that with a request option though I'd like to avoid introducing yet another one for that. `verbose` could be an existing candidate which kinda relates?

**Comment by nilsnolde** [comment]
> i think we could just call the callbacks if its outside of the original bounds

yeah I was thinking too complex.. solved it calling the callback only if `time < (max_seconds_ - 10 mins` (similar for distance). I'd PR soon when I have time again.

**Comment by kevinkreiser** [comment]
Sorry that's what I was trying to say just NOT call them if it's in the original bounds
