### ISSUE TITLE
https with valhalla endpoints not working

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3518]
We have a mobile application that uses an http endpoint currently to call the /route endpoint via a valhalla docker image running on an EC2 instance. I followed Nils's super helpful guide here to set that docker image up and run it on EC2 (https://gis-ops.com/valhalla-how-to-run-with-docker-on-ubuntu/)

As the guide details as the final step, there's a curl call to the ubuntu machine (in our case, an EC2 instance) which involves an http request on port 8002. 

Currently, Google Play is rejecting our app because we must use https instead of http. However, when I try to switch the request to https, I get the following message: 

> Error: write EPROTO 140718886653256:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Does anyone have any ideas on how to call my request with https? (the request more specifically is http://pointz-router-usa.hopto.org:8002/route, with an appropriate json body that the /route service takes in)

**Comment by TimMcCauley** [comment]
I would suggest to set up Apache or Nginx and stick it in front of Valhalla. Add certbot which will help you create Lets Encrypt SSL certificates and proxy the request to Valhalla on port 8002. Some helpful links:

- https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
- https://gist.github.com/unixcharles/949271

**Comment by kevinkreiser** [comment]
@kungfu303 what @TimMcCauley is saying is exactly correct. the http server that valhalla uses does not implement ssl. typical installations put a proxy in front of the service to do things like request authentication, rate limiting, and indeed ssl.

**Comment by kungfu303** [comment]
Great. Thanks @TimMcCauely and @kevinkreiser, I will go ahead and set up an Ngnix proxy in front of my ubuntu instance. 

Just to confirm @TimMcCauley, in the second link with the nginx.conf, the line with "proxy pass" is where I would want to write "http://localhost:8002" to direct it to my ubuntu instance's valhalla endpoint right?

**Comment by TimMcCauley** [comment]
> Great. Thanks @TimMcCauely and @kevinkreiser, I will go ahead and set up an Ngnix proxy in front of my ubuntu instance.
> 
> Just to confirm @TimMcCauley, in the second link with the nginx.conf, the line with "proxy pass" is where I would want to write "http://localhost:8002" to direct it to my ubuntu instance's valhalla endpoint right?

Yes, that is basically correct. You shouldn't need much more. The SSL bits of the config you can ignore, certbot will add them automatically. I think this issue can be closed.
