### ISSUE TITLE
Build issue in macos 12.1

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#3520]
```
Undefined symbols for architecture x86_64:
  "geos::geom::Coordinate::Coordinate()", referenced from:
      valhalla::mjolnir::BuildAdminFromPBF(boost::property_tree::basic_ptree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in libvalhalla.a(adminbuilder.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kevinkreiser** [comment]
these are the dependencies we install for macos: https://github.com/valhalla/valhalla/blob/master/.circleci/config.yml#L13

we've had trouble with geos versions on macos before though so this isnt surprising. its possible you are on a newere or older version than we are targetting. we have several macros in the code that detect which geos version you have and make the code changes to deal with it. its possible you are on an unsupported version. we'll need more information to determine if that is the case

**Comment by pranavpandey1998official** [comment]
protobuf 3.19.3
 cmake 3.22.1
 libtool 2.4.6_4
 libspatialite 5.0.1_1
 pkg-config 0.29.2_3
 luajit 2.0.5
 curl 7.81.0
 wget 1.21.2
 czmq 4.2.1
 lz4 1.9.3
 spatialite-tools 5.0.1_2
 unzip 6.0_7
 
 macos version is 12.1
 what else info do you need

**Comment by nilsnolde** [comment]
Ehm, how about the _geos_ version? 😂

**Comment by pranavpandey1998official** [comment]
geos version is 3.10.1 😊

**Comment by nilsnolde** [comment]
https://github.com/valhalla/valhalla/issues/3388 will work
