### ISSUE TITLE
Based on location, get road edges that this point lies on

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3525]
We would like to have a way for someone, based on a location point, get the entire set of edges for the road (or roads if they are at an intersection) that the person lies on (their location point). 

What's the best way to achieve this with the different services?

**Comment by kevinkreiser** [comment]
@kungfu303 if i were you i would take a look at the `locate` api. it lets you get edges/nodes near an input location. use the `verbose` to get extended metadata about the edges: https://github.com/valhalla/valhalla/blob/master/docs/api/locate/api-reference.md

**Comment by kungfu303** [comment]
Thanks @kevinkreiser. A follow-up:

The intended usage for what I described above is really for when a user is dragging their finger along a map. They are highlighting and drawing a road or route with their finger (the curve that they draw may not be one road and might not be the same route that /route would produce).

Would using /trace_route or /trace_attributes help in this case to output the edges that the user highlighted with their finger?  Or would a calls to /locate on each of the coordinates they highlighted get what I'd want (a set of edges that make up the roads on the line that the user drew)?

**Comment by kevinkreiser** [comment]
ok yeah that is more of a map matching use-case for sure. the problem there is that, depending on how zoomed out the map is, it might be very far off of the path they want to take which becomes very expensive to compute a map matching for. specifically you'll want to vary the size of the locations radii depending on the zoom level the person is viewing the map at (and latitude for that matter, smaller radii closer to the poles as your finger covers less physical space) at any rate you can experiment with it by, yes, passing that sequence of locations to either of the map matching endpoints that you listed.

one thing im not quite sure of is what you mean when you say "edges", like do you want metadata about the edges or do you want a route to follow? you could use locate to do the  same thing

**Comment by kungfu303** [comment]
Gotcha. Maybe I'll keep the zoom level in mind (perhaps this drag feature is only available at a close-up zoom level so that a finger swipe doesn't cover as much space). 

Right, so by 'edges' what I'm hoping to get are the edge segments that cover the roads dragged on. These would consist of a start and a dest coordinate and would be a straight line. So kind of like the individual steps that are outputted in a route, but I don't really want to generate a route from the drag/swipe motion. Instead I'd like to just identify what roads the user actually dragged/swiped on so they can be highlighted as polylines/drawn in our front-end

**Comment by kevinkreiser** [comment]
ok so you just want the geometry of the underlying edges then. in that case yes trace_attributes will work for you. simply use the attribute filter to include `shape` and that should be it

**Comment by kungfu303** [comment]
Great. Yes, we will include the `shape` to draw out the matched polyline. Additionally, if we want to go through each edge that was matched, we can access the coordinates of each edge by indexing into shape with `begin_shape_index` and `end_shape_index` right?

**Comment by kevinkreiser** [comment]
I'm not quite sure what you mean by

> if we want to go through each edge that was matched

Do you mean highlight individual edges' geometries? if that is the case then yep you can just ask for the begin and end indices as well in the filter

**Comment by kungfu303** [comment]
Yes, exactly!
