### ISSUE TITLE
libprime server not found when building on Ubuntu 20.04

### ISSUE THREAD

**Issue by JanStern** [valhalla/valhalla#3530]
When trying to build Valhalla I get the following error.
```console
foo@bar:~$ cmake -B build -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /home/linuxbrew/.linuxbrew/bin/pkg-config (found version "0.29.2") 
-- Performing Test HAS_COLOR_FLAG
-- Performing Test HAS_COLOR_FLAG - Success
-- Configuring in release mode
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.71")  
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread (found version "3.6.1") 
-- Using pbf headers from /usr/include
-- Using pbf libs from /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Using pbf release libs from 
-- Using pbf debug libs from /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Using pbf-lite
-- Checking for module 'libprime_server>=0.6.3'
--   No package 'libprime_server' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  CMakeLists.txt:233 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```
This problem seems similar to the one mentioned in https://www.giters.com/kevinkreiser/prime_server/issues/106
However, the mentioned **autotools install** did not make any difference for me. PPA also worked fine

**Comment by nilsnolde** [comment]
Can you outline the exact steps you took to install prime_server? Is its install location in your PATH?

**Comment by JanStern** [comment]
That is probably the source of my problem. I never properly installed the prime server.

Folowing the build and install from https://github.com/kevinkreiser/prime_server
I am stuck on the same problem. If I try to build prime server I get:
```console 
--   No package 'libcurl' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  CMakeLists.txt:43 (pkg_check_modules)

```
After messing with the CMakeList.txt include_irectories order I even realized that it fails for all other dependencies (libcurl, libzmq, libczmq). Seems like I am having a more fundamental problem

**Comment by kevinkreiser** [comment]
Just to be clear you followed these instructions https://github.com/kevinkreiser/prime_server#grab-some-deps ?

**Comment by JanStern** [comment]
When grabbing the dependencies the if statement runs without any actions. I assumed that I would be fine in this case. That is my mistake. However, after I manually added all PPA repositories they all failed with a 404 response. The release file seems to be non-existing for every one of them.
"E: The repository 'http://ppa.launchpad.net/kevinkreiser/libpgm/ubuntu focal Release' does not have a Release file."
That can't be right?

**Comment by kevinkreiser** [comment]
Yeah those ppas are backports you don't need them on 20.04 if you installed curl and libzmq you should be good. Is the output still that prime server can't find curl?

**Comment by JanStern** [comment]
After a new clean try, I got everything figured out. Thank you guys so much for your amazing work and help. 
Bedeutet mir wirklich viel! Danke das ihr etwas von eurem Samstag Abend für mich geopfert habt

**Comment by kevinkreiser** [comment]
Überhaupt kein Problem gewesen, viel spass dabei!
