### ISSUE TITLE
cycle_lane values for an edge

### ISSUE THREAD

**Issue by collins2023** [valhalla/valhalla#3536]

**Comment by collins2023** [comment]
Hello,
For a given edge, I was wondering what are the possible values for the field? Through playing around with the locate service, I was able to find possible values of 'shared’, ‘separated’,  ‘dedicated’, ‘and none’ but was not sure if there were more and could not tell necessarily from the documentation. Thank you!

**Comment by ImreSamu** [comment]
> I was able to find possible values of 'shared’, ‘separated’, ‘dedicated’, ‘and none’ but was not sure if there were more 

in the `trip.proto` only these values exists:

```proto
  enum CycleLane {
    kNoCycleLane = 0;
    kShared = 1;    // Shared use lane (could be shared with pedestrians)
    kDedicated = 2; // Dedicated cycle lane
    kSeparated = 3; // A separate cycle lane (physical separation from the main carriageway
  }
```
https://github.com/valhalla/valhalla/blob/1555d0fd419952eb0827abd970d250baa857c83e/proto/trip.proto#L81_L86

**Comment by nilsnolde** [comment]
guess that answers the question:) feel free to re-open @collins2023 if it didn't
