### ISSUE TITLE
Transit build failing due to transitland api error

### ISSUE THREAD

**Issue by timwis** [valhalla/valhalla#3537]
Hi! I've been trying to get transitland running and have run into an issue using `valhalla_build_transit`, which I believe is due to a bug in the TransitLand v1 api.

```
valhalla_build_transit valhalla.json https://transit.land 1000 ./transit -0.489,51.28,0.236,51.686 MY_API_KEY 4 f-gcpv-transportforlondon
```

Throws this error:

```
[WARN] 500'd retrying https://transit.land/api/v1/feeds.geojson?per_page=false&api_key=MY_API_KEY&bbox=-0.489,51.28,0.236,51.686&active_feed_version_import_level=4
```

I copied the URL into my browser and saw a more descriptive error message:

```
{"message": "[NoMethodError] undefined method `onestop_id' for nil:NilClass"}
```

The TransitLand v1 API [documentation page](https://www.transit.land/documentation/datastore/api-endpoints) has a similar request listed as an example:

```
/api/v1/feeds?bbox=-122.4183,37.7758,-122.4120,37.7858
```

This suggests valhalla _is_ making an appropriate query, and the issue is on the transitland side (albeit on an old and probably deprecated version of their API). I tried a few other variations of the URL to try and narrow down the issue, but they all yielded the same error message, so I [posted an issue](https://github.com/transitland/transitland-datastore/issues/1314) on the transitland-datastore repo.

I just wanted to make you aware because (a) it means that `valhalla_build_transit` doesn't work with the `https://transit.land` endpoint in the meantime, so other users may be searching for the error in this repo, and because (b) another solution would be to update [valhalla_fetch_transit.cc](https://github.com/valhalla/valhalla/blob/7a546791d0db9b5906be90af64638ca29e1a2fe1/src/mjolnir/valhalla_fetch_transit.cc) to use the latest TransitLand API (v2), which they may come back and recommend.

**Comment by kevinkreiser** [comment]
I am unaware of changes on their end but its fully within their rights to update their APIs. What I can say is that we currently don't have the bandwidth to modify existing executable to work with this new API unless we get a volunteer to work on it. That team did make support for generating pbf tiles that integrate directly into our ingestion (where as `valhalla_build_transit` generates these pbf tiles from their http apis). So if they give access to these tiles directly that would be a much more streamlined approach.

Long term the Valhalla project would like to support GTFS directly. There is a PR and some issues talking about that but its gone pretty stagnant. @nilsnolde has entered this project (GTFS support in Valhalla) as a Google Summer of Code opportunity so if you have anyone who would like to try it out please let them know. In the mean time I will write up the issues containing the information about how to achieve support.

Apologies for the inconvenience, bear with us while we transition.

**Comment by timwis** [comment]
Thanks for the context, Kevin, and for writing up the gtfs proposal. Just wanted to let you know that Drew over at transit land was kind enough to [fix the bug](https://github.com/transitland/transitland-datastore/pull/1315) yesterday, and I've just verified it's working in `valhalla_build_transit` now. He did mention the v1 API is rather difficult to troubleshoot, and all their resource is going toward the v2 API, though, so GTFS support still sounds like a worthwhile pursuit!
