### ISSUE TITLE
GTFS Support

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3539]
# Backstory

Back in #699 @dnesbitt61 first suggested that we should add direct support for GTFS and outlined some of the steps to get there. Over the years a few different people have asked for such a feature and we even had a contributor who drafted #2835 but sadly was not able to get to the end.

# Current Status

At the moment we have what is quickly becoming vestigial transit routing support in valhalla. The code is not exorcised in CI, the core team does not administer any deployments that serve transit routes. At best we hope the code is still working but I suspect there are at least a few bugs to be squashed before we get it running again. Just today we had someone report in #3537 that our data tooling no longer works with the transitland APIs. This is the perfect opportunity to revive transit support in valhalla via directly ingesting GTFS feeds. Lets talk about our options.

# Proposal - Match the Existing Specs

The previous proposals for this support centered around transcoding transit data into a set of protobuf tiles (that match the geographic extents of our native transit tiles) as is done when interfacing with the transitland APIs. This approach has the benefit of using existing code paths and really becoming a project of simply converting from one format to another (though its not completely trivial). The concrete task list is as follows:

* gain access to GTFS data via bespoke or existing means (`just_gtfs` or `cgtfs`)
* support multiple feeds in an additive fashion
* avoid doing deduplication where feeds overlap geographies in the first pass we can save that for future work
* find a reasonable way to do association to the graph (finding the edges/nodes where to attach a stop/station)
* copy all of the required and optional data out of the feed according to the PBF spec
* data hacking where needed to extend schedules
* grab some utrecht transit to build with in CI so we can write tests on it (gurka support is unfortunately difficult at the moment)
* write some actual unit tests proving the algorithms still work with the data

# Specification

What follows is, based on looking at our proto specs and existing code a list of the various GTFS feed metadata and marking which we require, and which would be nice to have. Anything that is currently not used is not included in the list.

## agency.txt
| Field | Status |
| - | - |
|agency_id | required|
|agency_name |optional |
|agency_url | optional|

## stops.txt
| Field | Status |
| - | - |
|stop_id |required |
|stop_lat |required |
|stop_lon |required |
| location_type|required (generic nodes and boarding areas are not supported) |
| parent_station|required (for stops/platforms/ingress/egress located within stations) |
|stop_name |optional |
| stop_timezone|optional |
|wheelchair_boarding | optional|

## routes.txt
| Field | Status |
| - | - |
|route_id ||route_type |required | |
|route_type |required |
|route_short_name | optional (preferred)|
|route_long_name |optional (used only if no short name provided) |
|route_desc |optional |
|route_color |optional |
|route_text_color | optional|

## trips.txt
| Field | Status |
| - | - |
|route_id |required |
|service_id |required |
|trip_id |required |
|trip_headsign | optional|
|block_id |optional |
| shape_id|optional |
|wheelchair_accessible |optional |
|bikes_allowed |optional |

## stop_times.txt
| Field | Status |
| - | - |
|trip_id |required |
|arrival_time |required |
|departure_time |required |
|stop_id |required |
|stop_sequence | required|
|stop_headsign |optional |
|shape_dist_traveled |optional |
|timepoint |optional |

## calendar.txt (optional)
| Field | Status |
| - | - |
| ALL FIELDS | required (if applicable) |

## calendar_dates.txt (optional)
| Field | Status |
| - | - |
| ALL FIELDS | required (if applicable) |

## shapes.txt (optional)
| Field | Status |
| - | - |
|shape_id |required |
|shape_pt_lat |required |
|shape_pt_lon |required |
|shape_pt_sequence |optional (assumed sequential) |

## frequencies.txt (optional)
| Field | Status |
| - | - |
|trip_id |required |
|start_time |required |
|end_time | required|
|headway_secs |required |
|exact_times |optional (assumed 0 or empty) |

**Comment by pranavpandey1998official** [comment]
hi, I am also a past GSoC contributor, and happy to see that you guys are talking about proposing this in GSoC, I would have. loved to apply for this under GSoC, but unfortunately, I passed out this year,

I know @nilsnolde is going to be mentor for this, but count me in as an unofficial mentor, let me know If I can help you guys in anything

**Comment by nilsnolde** [comment]
thanks a bunch @kevinkreiser , I added it to the GSoC description: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2022/Project_ideas

**Comment by mr-loop-1** [comment]
Hello, I am interested in the GSoC project related to this issue. My previous 2 projects have majorly been making and coding path algorithm in MySQL & MongoDb. 
I am currently studying about GTFS, and also trying to understand the '/proto' folder contents and also https://github.com/valhalla/valhalla/pull/2835.
I would appreciate any help or suggestions on these and about the project in general.

**Comment by mesozoic-drones** [comment]
@nilsnolde Hello! Yes, c++14 branch is completely up-to-date with master:
https://github.com/mapsme/just_gtfs/tree/cpp14

`boost::program_options` is specially added to the c++14 branch to replace the c++17 `std::optional`.  It is used in many methods like 
[inline boost::optional<Agency> get_agency(const Id & agency_id) const;](https://github.com/mapsme/just_gtfs/blob/a3638306ef7277f2a4bf6a0b42b8a39c1ad07557/include/just_gtfs/just_gtfs.h#L1187)

If `boost::program_options` is a problem we can think about changing methods signature to something like this:

**Comment by nilsnolde** [comment]
> Yes, c++14 branch is completely up-to-date with master:

great :)

> to replace the c++17 std::optional

ah ok, I think you can actually safely remove it then. seems you just need `boost::optional` which is header-only. `program_options` parses command line options.

then it's not a problem for us, as we'd just include just_gtfs as submodule and won't attempt any cmake "build" for it.

**Comment by kevinkreiser** [comment]
>  I think you can actually safely remove it then.

i was going to say the same thing

**Comment by smalcakmak** [comment]
Hello, I am İsmail, a freshman CS student from Sabancı university, istanbul, Turkey. I have some prior python and c++ knowledge and recently started to dive into more to C++ and DSA.

I have not contributed to open source before, but I am willing to do so, especially in this summer. 

I want to say that I am interested in the Valhalla GTFS integration project and I want it to be the project where I will improve my programming skills while working on it. So i'm thinking of applying to gsoc for this project.

**Comment by nilsnolde** [comment]
sorry ismail, we already have many candidates and it's a little too late for us now to take on another one (since there's quite some preparation which is expected of the candidates, putting strain on me/us as well). feel free to discover the other osm related projects though: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2022/Project_ideas

don't be too irritated, I'll delete your post (and mine too). good luck!

**Comment by vinayakkulkarni** [comment]
This is really interesting for making valhalla a truly multimodal trip planner backend! 

Thanks for such awesome work @kevinkreiser & co. 

I really hope to contribute more in this, time to learn C++ :)
