### ISSUE TITLE
Finding intersections between directions and isochrones

### ISSUE THREAD

**Issue by msiric** [valhalla/valhalla#3548]
Is there an easy way to find the coordinates of intersections between a path from point A to point B and an isochrone for point A?
Example:
<img width="694" alt="Screenshot 2022-02-22 at 23 44 07" src="https://user-images.githubusercontent.com/26199969/155232504-43412984-cbe3-46ac-96b6-8e6d13ab48c8.png">
I am looking for coordinates of the point of intersection that the blue arrow is pointing to:
<img width="694" alt="Screenshot 2022-02-22 at 23 44 07" src="https://user-images.githubusercontent.com/26199969/155232784-741098bf-ce90-4f28-ba3b-bdbb46d6f43b.png">
I queried the engine for directions from point A to point B and then requested an isochrone for point A. Looking for point/s where these two meet. I understand that, in theory, the drawn isochrone's polygon can have a side completely parallel to the path of a direction so no intersections would technically occur (they'd extend over each other). But I am just looking for points wherever these two are overlapping regardless of their positions.
If there is no easy way to do this, what would be a feasible solution?

**Comment by kevinkreiser** [comment]
@msiric there are two things to consider here. first, is it the case that you absolutely must have the intersection fall on isocrone exactly? the isochrone has a decent level of approximation to it, and is a lower resolution of the information you can get out of the route itself.

assuming you want the geometric intersection to be visibly matching between the two geometries you'll want to use a 3rd partly library to get this done. so then the next issue is it depends totally on where you are going to implement this. for javascript like in the browser you can probably use turf.js, if you are doing it in python  you can probably use shapely, if you are doing it in c++ you can use geos or boost. maybe you are doing it in yet another language?

assuming you dont care if the intersection lies perfectly on the isochrone you can actually use the osrm format route response with the shapeattributes time annotation to get back detailed time information along the routes geometry (basically a number of elapsed seconds for each shape point in the route). from there you could simply find the two shape points on either side of your desired elapsed time and find the point along that segment that would map to your time exactly. this point would not be gauranteed to lie directly on the isochrones geometry but it should be near by.

let us know which one you are looking to do so we can give you more advice

**Comment by msiric** [comment]
@kevinkreiser I appreciate the prompt reply.

I'm using JavaScript so Turf.js is probably the best choice for handling the first scenario.
If the point returned by the second scenario is not too far off, I'm perfectly fine with it.
How do you suggest I approach this? I'm not sure what OSRM format route response and shapeattributes time annotation are. Could you elaborate a bit?

**Comment by kevinkreiser** [comment]
yeah so the second scenario is basically change your route request to have at least:

```json
{
        ... PUT YOUR REGULAR OPTIONS HERE ...
	"format": "osrm",
	"filters": {
		"attributes": ["shape_attributes.time"],
		"action": "include"
	}
}
```

This should return an `annotations.durations` sections in the response where you'll have the time spent between every 2 adjacent shape points in the response. y ou can accumulate these to figure out which two shape points would be on either side of your target elapsed time. from there you simply need to linearly interpolate an intersection point between those two shape points to find the spot on your route where that amount of elapsed time occurs. this will be the most accurate positioning you can get out of valhalla and will definitely differ from the output of the isochrone (which is lower resolution)

**Comment by msiric** [comment]
I managed to get the `annotations.durations` sections, but I'm not sure what to map these values to?

Here's what the full response looks like:
https://jsoneditoronline.org/#left=cloud.2eb19f94ccda438b87ab1fcb29953cb8

How do I get the two shape points from these durations in order to find the spot where the amount of elapsed time occurs on the route?

**Comment by kevinkreiser** [comment]
there is one duration between every pair of shape point representing the time it took you to travel between those two points. you can get the shape by just decoding the `geometry` attached to the route

**Comment by msiric** [comment]
Ah now it makes sense.
I got it to work.

Thanks so much for the help 👍
