### ISSUE TITLE
Sub-optimal routing when using multiple locations

### ISSUE THREAD

**Issue by grutts** [valhalla/valhalla#3554]
Hello,

We have come across a case of sub-optimal routing which might be indicative of a bug.

The route from the origin to the next location appears sensible

`{"locations": [{"lat": 55.843564619077654, "lon": -4.255260357864107, '
 '"type": "through"}, {"lat": 55.85217034562079, "lon": -4.259261380403026, '
 '"type": "through"}], "costing": "auto"}`
                
               
However, when a subsequent destination is added the resulting route is very sub-optimal. Instead of approaching the middle location from the south, Valhalla chooses an approach from the north. Approaching from the north means the vehicle needs to do an awkward turn through side streets in order to continue northbound to the final location.

`{"locations": [{"lat": 55.843564619077654, "lon": -4.255260357864107, '
 '"type": "through"}, {"lat": 55.85217034562079, "lon": -4.259261380403026, '
 '"type": "through"}, {"lat": 55.858524911433314, "lon": -4.258434644873094, '
 '"type": "through"}], "costing": "auto"}`

We can demonstrate the sub-optimality by adding a "waypoint" location (second in the array) to force Valhalla to take a more sensible route. It can arrive at the "via" location from the south, and just continue northbound from there without awkward turns.

`{"locations": [{"lat": 55.843564619077654, "lon": -4.255260357864107, '
 '"type": "through"}, {"lat": 55.84894662128379, "lon": -4.260322916369417, '
 '"type": "through"}, {"lat": 55.85217034562079, "lon": -4.259261380403026, '
 '"type": "through"}, {"lat": 55.858524911433314, "lon": -4.258434644873094, '
 '"type": "through"}], "costing": "auto"}`
                
I have attached a ZIP of GPX files showing the routes we're getting with and without the waypoint to force the route [gpx_files.zip](https://github.com/valhalla/valhalla/files/8141179/gpx_files.zip)

It seems to us like Valhalla is optimising each leg of the journey individually, whereas it would arrive at a much better routing if it took into account the routing across all stops at the same time. Apologies if we can correct this behaviour by just changing a setting or parameter - we've had a look at the documentation but not found anything.

This is using Valhalla 3.1.4

**Comment by kevinkreiser** [comment]
@grutts thats correct, in the standard path finding algorithm we do each leg of the route in order independently

>  it would arrive at a much better routing if it took into account the routing across all stops at the same time

Map matching (`trace_route`) does this though there are limits on how far apart the locations can be from one another. If they are close enough or if you configure your service limits correctly this should get you the result you want though it is computationally much more expensive because, as you said, you have to track all edge candidate pairs' paths.

It would be interesting to allow a user to opt into this mode of operation i guess but with out the one bit of the map matching the cares about distance of your input point to the graph but only about cost of the routes.

**Comment by grutts** [comment]
Thanks for clarifying @kevinkreiser 

It would indeed be handy if this was an option! 

I just tried using `trace_route` for this. A lot of our intermediate points are quite far apart, so I tried setting quite a high breakage_distance. However, the map matching actually excludes the final point I was experimenting with from the resulting trace. Presumably, the algorithm concludes that there is low probability that the true trace passed through a point so far away and excludes it as an outlier.

It seems like a combination of elements from map matching and from routing would be ideal - the ability to search across multiple legs (from map matching), but also treating each supplied location as a fixed point which must be routed to/through (from routing)

**Comment by grutts** [comment]
For now we've solved the issue by adding a heading to the location, which incentives the routing to approach the location from a certain direction. Of course, it would be easier if we didn't need to use headings to force the direction, but it's a manageable solution. I'll close this issue
