### ISSUE TITLE
config max matrix locations as total locations of all sources and targets

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3566]
we just had a case where we wanted to calculate an asymmetric matrix (i.e. N != M) but the way we have to limit `max_matrix_locations` is not very convenient right now. e.g. setting 50 (the value we have currently on the FOSSGIS servers), we can get to a total number of 50x50 but not to e.g. 1 x 2500 and the way our matrix is implemented (I think at least) that's more or less the same thing, right? (not counting the time it takes to locate all inputs in the graph)

so I'd like to change that to a "total locations" maximum if you agree? if so, is changing the meaning of an existing config ok-ish? I tend to say yes in this case as the worst thing that can happen is matrix requests bouncing if operators don't check the config before upgrading (which I'm sure is a lesson everyone has learned by now who's actually running production servers;))

**Comment by kevinkreiser** [comment]
i think the best way to do this is to yes change it but not re-use the same name in the config. this way, the binary will complain when it starts up that its missing `max_matrix_pairs` and the person will not just have to pay attention to when requests start coming back but rather they will not be able to start the service without reading the new config value and seeing that it deprecated the old one. this way you get what you want and people who are currently running a service dont get completely screwed in a tricky way (silently going from 2500 pairs down to 50 pairs would be pretty rotton to do to people).
