### ISSUE TITLE
Are alternative routes available via the HTTP API?

### ISSUE THREAD

**Issue by mraaroncruz** [valhalla/valhalla#3567]
I was just looking at this PR
https://github.com/valhalla/valhalla/pull/2626
It looks like the ability to calculate alternative routes exists now.

Has this API been included in the HTTP API? It's not in the docs but if I understand the proto files, it seems like it should be available.
https://github.com/valhalla/valhalla/blob/master/proto/trip.proto#L289-L291

But I can't really figure out how the HTTP API works in this project and don't see any rpc services in the proto files so you must be implementing it in another way.

Anyway, is this available (via tyr?) and if not, where would I find where to implement it myself?

Thank you!

**Comment by kevinkreiser** [comment]
huh you're right, i forgot to put documentation in for that! its pretty straight forward, just add the parameter `"alternates": 1` to ask for up to 1 additional alternate. ill update the docs
