### ISSUE TITLE
Finding intersections between two isochrones

### ISSUE THREAD

**Issue by msiric** [valhalla/valhalla#3568]
Is there an easy way to find an intersection between two (or more) isochrones?
Example: 
<img width="754" alt="Screenshot 2022-03-10 at 13 39 37" src="https://user-images.githubusercontent.com/26199969/157663948-656eed18-5bfb-4928-9b8d-53f90d4f2570.png">
I'm looking for coordinates of the intersecting points that would form the following polygon:
<img width="296" alt="Screenshot 2022-03-09 at 14 22 16" src="https://user-images.githubusercontent.com/26199969/157695738-25af4611-a36d-4155-ab3d-a7a418fffa9a.png">
What is the best way to do this?

**Comment by nilsnolde** [comment]
it's called "geometric difference" and you'd do that on the client side, e.g. https://turfjs.org/docs/#difference. what valhalla can do for you is to union the polygons when you provide multiple locations in a single request, but it doesn't give you the difference.

**Comment by msiric** [comment]
@kevinkreiser Found a solution using Turf, thanks for the suggestion 👍
