### ISSUE TITLE
pedestrian route time unrealistic and inconsistent

### ISSUE THREAD

**Issue by georg-d** [valhalla/valhalla#3573]
The walking route https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=9.884691238403322%2C47.599319584622%2C9.872074127197267%2C47.602632914527724 is 1.3km but shown to need 1h 15min 
![grafik](https://user-images.githubusercontent.com/45993293/157907654-eaa12537-da71-4031-8d3d-a812accd5bce.png)
That seems quite a lot over-estimated. I assume the settings are default (did not find "reset to default", see https://github.com/valhalla/valhalla/issues/3574)

Moreover, [Valhalla itself ](https://valhalla.openstreetmap.de/isochrones?profile=pedestrian&range=15&interval=4) shows start & destination to be within 15min isochrone, so both computations are inconsistent.
![grafik](https://user-images.githubusercontent.com/45993293/157907677-44fd556a-c344-4648-8fa0-87341d70a2bb.png)

**Comment by nilsnolde** [comment]
the repo for the app is over at https://github.com/gis-ops/valhalla-app. though in this case it's actually really valhalla giving the 956 secs response. very strange. thanks though, very easily reproduced. the isochrone is right of course, the routing has some hiccup.

**Comment by nilsnolde** [comment]
uff.. 936 secs = 15 mins. all ok on valhalla side. the app has the problem, it somehow adds an hour.. I'll add an issue to the app repo and tag you

**Comment by TimMcCauley** [comment]
This was a nasty bug adding +1 hour for CEST... sorry about this @georg-d  - it is fixed and deployed now

<img width="871" alt="Screenshot 2022-03-11 at 21 04 51" src="https://user-images.githubusercontent.com/10322094/157951115-6922a7d5-0ce0-4e55-912f-fe5813674d8f.png">

**Comment by georg-d** [comment]
Tested and fine now 🙂 No worries and thank you for the prompt fix! Have a nice week end.
