### ISSUE TITLE
Unidirectional A* variants have issues with multiple destination edges

### ISSUE THREAD

**Issue by derolf** [valhalla/valhalla#3582]
In SetOrigin and ExpandInternal, the Uni A* checks if a new edge E is a destination edge.

Let’s consider the case where E is a destination edge.

Then the cost of E is adjusted (minus percentage, plus lateral distance) and inserted into the queue. If the lateral distance is high, the adjusted cost of E might be much bigger than the vanilla cost of E.

However, it could be that the actual shortest path travels along E to another destination edge F with a much smaller lateral distance and hence much smaller total cost.

Because of the adjusted cost of E, it is impossible for any such shortest path to travel along E towards F (costs are distorted). So any such path will not be found, resulting in strange detours around the destination: They will avoid E and try to reach F via a detour.

NOTE: We have a workaround in our codebase that fixes the issue: We always inserts a vanilla edge label into the queue first. If the edge is also a destination edge, we compute the adjusted cost and add another edge label to the queue and mark it as a destination edge label. When pulling from the queue, we check if it’s a destination edge label and terminate the search.

**Comment by derolf** [comment]
Pretty sure that this is the root cause for https://github.com/valhalla/valhalla/issues/1952

**Comment by kevinkreiser** [comment]
@derolf excellent suggestion! this issue has been plaguing us for years, how to penalize candidate start/end edges appropriately. the suggestion sounds straight forward and requires only one bit on the edge label. we should write a unit test and give this a try!

cc @dnesbitt61

**Comment by derolf** [comment]
Thanks @kevinkreiser !

Right now our “flag” is to ride on the fact that destination edge labels have dist = 0.0. However that feels a bit like a hack and I only did it to keep the changes local since edge label is used at many places. What do you think?

**Comment by kevinkreiser** [comment]
@derolf i dont have strong feelings that that would be "hacky" having path distance to destination being 0 on the destination edge is kind of intuitive, but also we have a lot of spare bits in edgelabel at the moment and we could easily just taking one of those and make an explicitly named flag with a nice comment explaining what it means.

i'd say if you are already working on this then throw up a pr and we can have a few folks make comments on it and get it merged, thanks again for bringing this up!

**Comment by derolf** [comment]
Guten Abend @kevinkreiser !

So, I added some tests in: https://github.com/derolf/valhalla/commit/0429fabdb08c2e995f08eb3e179da63c1cef8cc6

They pass with `radius=0`, but fail as soon as I raise the `radius` and hence generate multiple origin, destination candidates.

I also added a `destination` flag to EdgeLabel. Tomorrow, I am going to port the fix.

**Comment by kevinkreiser** [comment]
geil, ich freu mich drauf!

**Comment by derolf** [comment]
Interestingly, my test caught a potential bug in the `time_dependent_reverse_a*`. Even with radius=0, I get

```
Expected equality of these values:
  actual_names
    Which is: { "AB", "BC", "CD", "CD", "BC", "AB" }
  expected_names
    Which is: { "AB" }
```

and

```
Expected equality of these values:
  actual_names
    Which is: { "CD", "BC", "AB", "AB", "BC", "CD" }
  expected_names
    Which is: { "CD" }
````

**Comment by kevinkreiser** [comment]
feel free to comment that test out for now and we can get it in a subsequent pr? or if you'd like to look into it now that would also be great. its totally up to you, we really appreciate you looking into it either way!

**Comment by derolf** [comment]
Fixed (including the bug in https://github.com/valhalla/valhalla/issues/3582#issuecomment-1078800283)

**Comment by xuruiray** [comment]
I also found this problem, is there any good solution so far

**Comment by nilsnolde** [comment]
as you can see there's a pr solving the bug. as you can see further in the pr comments, there's some problem in test routes. should be done in the next weeks latest.

**Comment by nilsnolde** [comment]
this is done in #3585
