### ISSUE TITLE
How to get gps points (lat and lon) between origin and destination?

### ISSUE THREAD

**Issue by bachephysicdun** [valhalla/valhalla#3598]
Hi, 

Is it possible to get all the gps points (lat and lon) every 5 min between origin and destination? 
For example, I would like to find the optimized route for the following location and have all the information for that route?
'{"costing":"auto","directions_options":{"units":"kilometers"},"locations":[{"city":"Hamm","lat":51.6803258,"lon":7.8208923},{"city":"Bonn","lat":50.7333333,"lon":7.0999999}]}'

Thank you in advance!

**Comment by nilsnolde** [comment]
You get the full line geometry from /route, but it’ll be hard to correlate that to durations, though very easy to break it up in distances, eg every 5 km. You can also send the /route response/geometry on to /trace_attributes which is really verbose, responding with every edge information. But there’s enough info in that response to approximate well enough what you’re after.

**Comment by bachephysicdun** [comment]
Thank you!
