### ISSUE TITLE
MapMatching api on private trails

### ISSUE THREAD

**Issue by amjith** [valhalla/valhalla#3600]
Is it possible to match segments of my ride against private trails in a map? 

I am using valhalla's meilie for matching trails from my bike rides. I get pretty good results. But sometime I notice that sections of my ride don't come back with a match even though the map has the appropriate trail names. This is because the trails are marked private and I presume meilie won't matching against private trails by default. 

I've tried using the different costing options such as `pedestrian` and `bicycle`. I'm wondering if there is way to enable matching against the private trails.

**Comment by kevinkreiser** [comment]
There are costing options which allow you to ignore the access restrictions of ways in osm. Specifically we have ignore_access which you can set to true in costing_options. I can't remember if it's documented though.. if not we should add it

**Comment by kevinkreiser** [comment]
or i should have documented them when i implemented the feature...

**Comment by amjith** [comment]
I tried the `ignore_access` in `costing_options` and it works beautifully. Thank you!
