### ISSUE TITLE
Learning more about the technical details behind isochrone calculation

### ISSUE THREAD

**Issue by msiric** [valhalla/valhalla#3601]
As the title says, I am trying to find more information on how exactly isochrones are being calculated and manipulated until they are finally returned as a list of coordinates.

I only managed to find this page: https://valhalla.readthedocs.io/en/latest/thor/isochrones/, which includes a section with "Technical details", but it is quite short and not very extensive.

Is there another place where I could learn more?

**Comment by nilsnolde** [comment]
Sorry to say but the most uptodate info is in the code. 

There’s also some more info in this issue, where isochrones are fairly well explained IIRC: https://github.com/valhalla/valhalla/issues/3212

Other than that you’re best bet is to dive into the code.
