### ISSUE TITLE
Weird routing on highway A7 germany (due to detour tag on osm?)

### ISSUE THREAD

**Issue by SamuelBrucksch** [valhalla/valhalla#3604]
Hi,

i just tried valhalla a bit and found a route, that takes a detour, that is a bit strange:
![image](https://user-images.githubusercontent.com/8776268/165045385-e3c6afea-4c6f-4482-98b6-c336df6b592e.png)

Start: 49.097330 (lat),10.211430 (lon)
Destination: 48.943566,10.191557

I checked OSM for that highway part but could not find anything obvious. However there is a `detour` tag exactly at those on/offramps:
https://www.openstreetmap.org/relation/6491122

Other detours do not seem to affect the route planning though, so not sure if that is really the reason. If i swap the directions, the same happens.

Any idea what could be the reason here?

**Comment by SamuelBrucksch** [comment]
One thing to add:
![image](https://user-images.githubusercontent.com/8776268/165047501-a979e8e9-f2bd-45a6-88f1-0e9a7dc42c9f.png)
It seems to be related to the on ramp on the destination point. If i move the destination to shortly before the ramp (1) it works, but if i move to behind the ramp (2), it takes the detour.

**Comment by SamuelBrucksch** [comment]
https://valhalla.openstreetmap.de/directions?profile=car&wps=10.212137%2C49.0985841%2C10.1907157%2C48.9457193

Like this? I found out that it takes the correct route, if i enable "shortest route", however it is actually always the shortest and best route so it should be used per default. There seems to be something that causes high cost which forces the other route to be taken.

**Comment by nilsnolde** [comment]
you must've found a pretty annoying edge case there.. had a quick glance and we don't parse `detour` from OSM, it's not heavily used and seems to be fairly instable on how it's tagged, however, A7 is the most common value (followed by other german highways..). 

the fact that shortest gives the right result is very strange.. that limits the code area quite well though, basically it has to be smth with costing, not e.g. hierarchies. anyone got a good guess as to why this might happen? doubt I'll have the time anytime soon to take a closer look tbh.

**Comment by SamuelBrucksch** [comment]
Found something on the OSRM debug map:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/8776268/165374542-6f799d39-0fce-46e9-acb2-2a39113aed2f.png">
Magenta / pink seems to indicate that there is a not properly connected road segment. Any idea, what could cause this?

**Comment by SamuelBrucksch** [comment]
There was a barrier modeled on the highway. So we just tried to model it slightly differently. Let's see if this fixes the issue.

Before:
![image](https://user-images.githubusercontent.com/8776268/165470857-70e6e480-ed06-44ff-92ca-727738d3f1e3.png)
After:
![image](https://user-images.githubusercontent.com/8776268/165470879-05e59bc8-7065-4623-b4b2-1934ac1b28e8.png)

**Comment by nilsnolde** [comment]
did osrm have similar issues routing along that stretch?

what you can do to test those things a bit quicker: load the area into josm, do your edits, then export the PBF (extra josm plugin), build the tiles with valhalla and route. 

an osm change now won't be picked up by the fossgis instance before friday or so (takes 1.5 days to build the tiles and the change must've been in a daily changeset already)

**Comment by kevinkreiser** [comment]
its a bit late but i was going to suggest running the route with shortest but also specifying a recosting of not shortest. this will then output the costing information along the whole route (if you use osrm format). from there you can fidn where a huge cost gets added (at what intersection (ie node in the graph) along the route). from there we will probably see the gate crossing penalty as you have found. in the mean time you can probably test this theory by disabling the gate penalties but it looks to me like you found it already.

**Comment by nilsnolde** [comment]
TIL more efficient costing debugging :clap: thanks!

**Comment by SamuelBrucksch** [comment]
Looks like those barriers for the service roads connecting both side of the highway were the problem. A route can now be calculated. Thanks for your inputs.
