### ISSUE TITLE
Incorrect value for cost_threshold in costmatrix 

### ISSUE THREAD

**Issue by monteirodom** [valhalla/valhalla#3605]
In costmatrix, the searches (forward and backward) are stopped when a cost.duration is higher than a computed threshold.
That threshold is computed as (auto mode): `cost_threshold = max_matrix_distance / kCostThresholdAutoDivisor;`
As the check is based on a duration, that divisor is equivalent to a speed (56 km/h in auto mode).
> In accordance with the much more explicit computation in timedistancematrix

But that speed is in km/h and the cost.duration is in seconds. But the computation of the threshold lacks the conversion of the units (_again that conversion is explicit in timedistancematrix_).
In consequence, the many to many searches stop far too early, unless we set max_matrix_distance with a huge value.

The issue was already raised in #1554, but the fix in #1555 didn't address the problem correctly.
> It used a `2.0` coefficient, but the right conversion from km/h to m/s should be `3.6`

That issue arises much particularly for routes with ferries, as usually the ferry edge is very long and has a very low speed.

By the way, why convert a distance into a time for the check? Yo **do need** a hipothesis of  an average speed. The check can be done with a distance, by replacing :
`if (pred.cost().secs > current_cost_threshold_)`
with 
`if (pred.path_distance() > max_matrix_distance)`
Which is much more meaningful with the parameter in the setup.

**Comment by monteirodom** [comment]
I'm also concerned by that one ... wich mixes duration with cost
```
-        float s = std::abs(pred.cost().secs + opp_el.cost().secs - opp_el.transition_cost());
+        // TODO: shouldnt this use seconds? why is this using cost!?
+        float s = std::abs(pred.cost().secs + opp_el.cost().secs - opp_el.transition_cost().cost);
```
The TODO was added by @kevinkreiser at #2425, but left as is since then.

**Comment by kevinkreiser** [comment]
yeah i noticed that while doing another refactor. instead of changing the behavior i decided to adapt to just the refactor and let the TODO for later. does look like we should take another bug scrub over the code

**Comment by monteirodom** [comment]
Is there anyone working on this issue?
I can come with a PR with the fix described on the issue. But I'm not very easy about the consequences on this part of code that uses the threshold for bucket allocation:
```
    // Allocate the adjacency list and hierarchy limits for target location.
    // Use the cost threshold to size the adjacency list.
    target_adjacency_.emplace_back(DoubleBucketQueue<BDEdgeLabel>(0, current_cost_threshold_,
                                                                  costing_->UnitSize(),
                                                                  &target_edgelabel_[index]));
```

**Comment by nilsnolde** [comment]
> I'm also concerned by that one ... wich mixes duration with cost
> 
> ```
> -        float s = std::abs(pred.cost().secs + opp_el.cost().secs - opp_el.transition_cost());
> +        // TODO: shouldnt this use seconds? why is this using cost!?
> +        float s = std::abs(pred.cost().secs + opp_el.cost().secs - opp_el.transition_cost().cost);
> ```
> 
> The TODO was added by @kevinkreiser at #2425, but left as is since then.

fwiw, this was totally fine. `opp_el.transition_cost().cost` is actually secs in that context, albeit it is pretty confusing..

**Comment by nilsnolde** [comment]
but I'll look at the OP again these days, sounds fishy..

**Comment by nilsnolde** [comment]
I'll pin it, so I'll remember:)

**Comment by nilsnolde** [comment]
I looked a bit at it.

I also think currently it's somewhat aborting too early based on the `max_matrix_distance`, at least for some costings, it's saying e.g. 
```c++
constexpr float kCostThresholdPedestrianDivisor =
    28.0f; // 200 km distance threshold will result in a cost threshold of ~7200 (2 hours)
```

that gets multiplied with 2 and is relevant for each half-expansion (it's bidirectional). so really we'd abort after 4 hours in each direction, totalling ~ 8 hours. that's sporty for 200 km haha as @monteirodom says, currently we're using that value also to set the amount of buckets in the doublebucket queues, so it's pretty bad for memory to set that to an insane value.

I think we should actually compare this threshold to the path distance as @monteirodom suggests, it says _**_distance**_  anyways and we don't need to do conversions to durations. it'd be more intuitive IMO.

scaling bucket count for the adjacency queues with allowed distance does make sense. I'd experiment a bit here to see if we can't reach a better heuristic to scale the bucket count. an actual 200 km pedestrian route would result in a huge overflow bucket if the max distance is set to the same. needs to be in balance with memory requirements though.. 200 km pedestrian results in a bucket count of 144000 (40 hours of walking in seconds) for each source and targets and the vast majority of requests wouldn't need even remotely that many.

maybe it'd make sense to scale the bucket count with a scaled-up max distance between the locations of each request, so it's not dependent on the configured max distance? e.g. use the estimated cost range of x times the max crow-distance between locations, and max would be the cost conversion of the configured max distance limit?
