### ISSUE TITLE
proper pre-commit script

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3613]
before I go ahead with it: what you think about adding a proper pre-commit script to valhalla? mostly to try and prevent all these format.sh commits.. it can also be used in CI of course.

I was thinking a bash script which installs python's `pre-commit` library. `pre-commit` needs a small simple config file in this repo but is battle-tested and very flexible. with that we could add the existing scripts as target, but also do some python linting/formatting with appropriate tools (I feel we have enough python in this repo to be a bit more mindful about it;)). in total it'd be 2 new files (one script, one config).

so a dev would only run `install_pre-commit.sh` or so and that installs the `pre-commit` library to their python env which will then run all targets on each commit. we could also add the tidy script on pre-push events (though that's much less likely to cause failures and often takes a long time to run).

thoughts?

**Comment by kevinkreiser** [comment]
I have done exactly this on other repos and I agree that it's pretty uninhabited. The only problem with it is it's opt in so if a person doesn't do it they will be afforded none of the benefits. Anyway, im not opposed to it, I think it could be somewhat helpful

**Comment by vinayakkulkarni** [comment]
Maybe we can use Husky which provides easy access to `git hooks`

e.g.: https://github.com/geospoc/v-mapbox/tree/main/.husky

I can setup the hooks if you want @kevinkreiser
