### ISSUE TITLE
ignore access=destination on ferry-connecting edges

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3614]
had a client who couldn't route over a shorter ferry and was always sent over the longer ferry:
https://valhalla.openstreetmap.de/directions?profile=car&wps=-5.011911392211915%2C54.96160781245034%2C-5.79681694507599%2C54.848578936001466
![image](https://user-images.githubusercontent.com/25637358/166741050-f653234d-1eaa-4cbe-9d78-c6cee6960ee1.png)

when we moved the destination onto the ferry ramp, it worked:
https://valhalla.openstreetmap.de/directions?profile=car&wps=-5.0129950046539316%2C54.961204350394524%2C-5.79630732536316%2C54.849137951748666
![image](https://user-images.githubusercontent.com/25637358/166741036-251255f3-80ff-46e0-a1b5-0729f5c1c035.png)

for the 2. example, you'll need to decrease the `use_ferry` to less than 1, its own bug apparently..

anyways, the problem is that the ferry ramp at the destination has `access=destination` which I disagree with, so I already removed it: https://www.openstreetmap.org/way/417929556

anyways, the client ran an analysis on his pg osm dump and came up with tons of those ferry examples in the planet. also osrm & graphhopper seem to handle that case. I think we should do too, given how pervasive that occurs apparently.

I guess that should be handled in the graph building phase. I imagined smth like "if one of a node's incoming edges is a ferry edge, then remove a possible `destination` flag on all outgoing edges". I don't see why edges connecting to ferries should ever have a `destination` tag, so that seems safe to me.. 

other suggestions?

**Comment by kevinkreiser** [comment]
I swear we saw and tried to fix this already but perhaps it's slightly different: https://github.com/valhalla/valhalla/pull/1905

**Comment by nilsnolde** [comment]
huh.. weird.. will have probably have a look soon

**Comment by nilsnolde** [comment]
if not solved, at the very least superseded by #3942
