### ISSUE TITLE
Question: Is it possible to ignore locations/routes when calculating isochrones?

### ISSUE THREAD

**Issue by msiric** [valhalla/valhalla#3618]
Is there a parameter that can be used to specify areas that should be ignored when calculating isochrones?
Something like `avoid_locations` that is available for route calculation?

**Comment by dnesbitt61** [comment]
avoid_locations should work with isochrones. I remember doing a test a few years ago where I put an avoid_location on a bridge, and the isochrone changed to not use the bridge.

**Comment by nilsnolde** [comment]
so does `exclude_polygons`.. btw, `avoid_` is deprecated, rather use `exclude_` (not we'll ever really deprecate it I guess;))

**Comment by msiric** [comment]
Just gave it another go and it does indeed exclude locations I specified.
I could've sworn I tried it yesterday and noticed no difference. 

Thanks for the tip to use `exclude_locations` instead of `avoid_locations`!

P.S. Maybe the `exclude_locations` parameter could be added to the Isochrone API's "Other request parameters" section for future reference 😉
