### ISSUE TITLE
Linux build errors

### ISSUE THREAD

**Issue by nitin9291** [valhalla/valhalla#3624]
I'm having trouble building from source on linux (ubuntu). The error message looks like this when I ran the make command with VERBOSE=1 :

Are there any workarounds I can try?

[ 92%] Linking CXX executable valhalla_build_admins
/usr/bin/cmake -E cmake_link_script CMakeFiles/valhalla_build_admins.dir/link.txt --verbose=1
/usr/bin/c++  -fdiagnostics-color=auto  -O3 -DNDEBUG CMakeFiles/valhalla_build_admins.dir/src/mjolnir/valhalla_build_admins.cc.o -o valhalla_build_admins  src/libvalhalla.a /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/libprime_server.so /usr/lib/x86_64-linux-gnu/libspatialite.so /usr/lib/x86_64-linux-gnu/libsqlite3.so /usr/lib/x86_64-linux-gnu/libluajit-5.1.so -lm /usr/lib/x86_64-linux-gnu/libgeos.so /usr/lib/x86_64-linux-gnu/libgeos_c.so
/usr/bin/ld: src/libvalhalla.a(adminbuilder.cc.o): in function `valhalla::mjolnir::BuildAdminFromPBF(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
adminbuilder.cc:(.text+0x3eee): undefined reference to `geos::geom::Coordinate::Coordinate()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/valhalla_build_admins.dir/build.make:108: valhalla_build_admins] Error 1
make[2]: Leaving directory '/mnt/sdb/gisops_docker/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:1469: CMakeFiles/valhalla_build_admins.dir/all] Error 2
make[1]: Leaving directory '/mnt/sdb/gisops_docker/valhalla/build'
make: *** [Makefile:156: all] Error 2

**Comment by nilsnolde** [comment]
does that help? https://github.com/valhalla/valhalla/issues/3617

**Comment by nitin9291** [comment]
Nope, I did check issue #3617, but I did not miss installing the libraries 


sudo apt-get install -y libgeos-dev libgeos++-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libgeos++-dev is already the newest version (3.10.2-1).
libgeos-dev is already the newest version (3.10.2-1).
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.

**Comment by nilsnolde** [comment]
ah I see 22.04 landed apparently (correct me if I'm wrong, I'm on arch myself, which has very outdated 3.9.1).. then you're hitting the same as #3388 and the solution should be the same as well.

**Comment by nilsnolde** [comment]
Did you nuke the whole build folder before trying again? Cmake and cache is sorta a mystery to me. 

You can also dig a little in the issue I pointed to, it references a geos issue and PR (which should fix that exact behavior hopefully in 3.11). 

Other than that, going with 3.9.1 is for sure gonna work. 

I wanted to get rid of geos for a while now, but ended up being more work than I anticipated, so it’ll have to wait a while.

**Comment by nitin9291** [comment]
As you suggested I started fresh by creating a new build folder, but I ran into the following error :

[ 32%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o
cd /mnt/sdb/gisops_docker/valhalla/build/src/mjolnir && /usr/bin/c++ -DAUTO_DOWNLOAD=0 -DBOOST_ALL_NO_LIB -DBOOST_NO_CXX11_SCOPED_ENUMS -DDATA_TOOLS -DHAS_REMOTE_API=0 -I/mnt/sdb/gisops_docker/valhalla -I/mnt/sdb/gisops_docker/valhalla/valhalla -I/mnt/sdb/gisops_docker/valhalla/third_party/date/include -I/mnt/sdb/gisops_docker/valhalla/third_party/rapidjson/include -I/mnt/sdb/gisops_docker/valhalla/build/src/mjolnir -I/mnt/sdb/gisops_docker/valhalla/build/src/mjolnir/valhalla -I/mnt/sdb/gisops_docker/valhalla/build/src -I/mnt/sdb/gisops_docker/valhalla/build/src/valhalla -I/usr/include/luajit-2.1 -I/mnt/sdb/gisops_docker/valhalla/third_party/robin-hood-hashing/src/include -DGEOS_INLINE -fdiagnostics-color=auto  -O3 -DNDEBUG -fPIC -mfpmath=sse -msse2 -std=gnu++14 -Werror -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -MD -MT src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o -MF CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o.d -o CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o -c /mnt/sdb/gisops_docker/valhalla/src/mjolnir/adminbuilder.cc
In file included from /usr/include/geos/geom/CoordinateSequence.h:21,
                 from /usr/include/geos/geom/CoordinateArraySequence.h:21,
                 from /mnt/sdb/gisops_docker/valhalla/src/mjolnir/adminbuilder.cc:20:
/usr/include/geos/geom/Coordinate.h:164:11: fatal error: geos/geom/Coordinate.inl: No such file or directory
  164 | # include "geos/geom/Coordinate.inl"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/build.make:84: src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o] Error 1
make[2]: Leaving directory '/mnt/sdb/gisops_docker/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:2061: src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/all] Error 2
make[1]: Leaving directory '/mnt/sdb/gisops_docker/valhalla/build'
make: *** [Makefile:156: all] Error 2

**Comment by nitin9291** [comment]
I have completed the installation using Geos 3.9.1., many thanks for the help.

$ valhalla_build_tiles --help
valhalla_build_tiles 3.1.4

valhalla_build_tiles is a program that creates the route graph
from one or multiple osm.pbf extract(s)

Usage:
  valhalla_build_tiles [OPTION...] OSM PBF file(s)

  -h, --help               Print this help message.
  -v, --version            Print the version of this software.
  -c, --config arg         Path to the configuration file
  -i, --inline-config arg  Inline JSON config
  -s, --start arg          Starting stage of the build pipeline (default:
                           initialize)
  -e, --end arg            End stage of the build pipeline (default: cleanup)

**Comment by kevinkreiser** [comment]
the latest LTS release of ubuntu is using 3.10.2 which even others have reported is broken (missing the actual guts of the library we are linking against): https://answers.launchpad.net/ubuntu/+source/geos/+question/701657
