### ISSUE TITLE
GTFS Support: Re-enable Transit Routing

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3631]
Alright, if we made it this far we are almost there. We have the data loading, in the tiles and also connected to the rest of the graph all we need to do now is check that we can route on it. The problem is we havent been routing on transit for quite some time so there is bound to be some broken code. Numerous refactors have happened since we last regularly exorcised these algorithms and so its unlikely that they still work as they originally did. This task is complete when:

1. we have a gurka test that shows you can compute a transit route. use the mocked gtfs feed with a gurka map to build a scenario to route on
2. check that the timing of the routing algorithm works properly that the information coming back in the response uses the right schedule information and that other metadata appears correctly (as output from the serializers)

There will be a lot of clean up and debugging in this step, its impossible in advance to write up all the issues we'll find and its likely some will slip through the cracks but we'll do our best effort to conform to the original response spec.

**Comment by nilsnolde** [comment]
this is done I'd say
