### ISSUE TITLE
Log `color` options not working

### ISSUE THREAD

**Issue by JaimeHolland** [valhalla/valhalla#3666]
When building a config file like

```
    valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles \
                          --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar \
                          --mjolnir-timezone ${PWD}/timezones.sqlite \
                          --mjolnir-admin ${PWD}/admins.sqlite \
                          --mjolnir-logging-color false \
                          --loki-logging-color false \
                          --thor-logging-color false \
                          --odin-logging-color false \
                          --mjolnir-concurrency 7 \
                          --meili-logging-color false  > valhalla.json
```

the output of `valhalla_build_tiles` in not colour - which is what I want.  However, when starting valhalla with `valhalla_service valhalla.json 1`, the stdout logs _are_ in colour, which is an issue for me as the service i send my logs to can't parse them as easily.

Any suggestions?  I'm using the docker image valhalla/valhalla:run-3.1.4

**Comment by kevinkreiser** [comment]
have you tried the `run-latest` tag instead? we havent done a release in a little while but that tag will have the most recent master. looking at the code `valhalla_service` uses the `loki` logging config: https://github.com/valhalla/valhalla/blob/master/src/valhalla_service.cc#L169 so it should adhere to what you have set

**Comment by JaimeHolland** [comment]
Hi, thanks for the pointer.  Yes, this does now work - the logs are not in colour.  

Also, it resolved something else that confused me: the /status endpoint seems to be returning data now ( `{"version":"3.1.4"...}` ), whereas with the 3.1.4 tagged image it only ever returned `{}`  

I still can't get the verbose setting working for the /status endpoint though, despite having turned `allow_verbose` on in the config, when trying `curl http://localhost:8002/status?verbose=true` - maybe my understanding of how to invoke a verbose status is wrong?

More importantly, is it possible to tag the image which is currently `run-latest` to some static tag?  I don't want to have to use a `latest` style tag in production in case the underlying image changes....

**Comment by nilsnolde** [comment]
> I still can't get the verbose setting working for the /status endpoint though

you'll need to request with a json payload, valhalla doesn't parse/accept query params other than `json`, e.g. `'http://localhost:8002/status?json=%7B%22verbose%22%3A%20true%7D'` (url encoded) or with POST and this payload:
```
{
    "verbose": true
}
```

> More importantly, is it possible to tag the image which is currently run-latest to some static tag

docker has a similar concept to commits: digests. just pin your `docker pull` to the digest you're interested in, e.g.
![image](https://user-images.githubusercontent.com/25637358/175328484-bd9433e9-626d-451e-a9e1-7ea783acf259.png)

as far as I'm aware there's no way to get a list of digests for a particular image if it's not locally available already. only workaround is to look at the circleci logs of a particular (git) commit you want, e.g. this is the circleci log of a particular commit and this should be the short form of the encoded digest string:

![Screenshot from 2022-06-23 17-04-54](https://user-images.githubusercontent.com/25637358/175331908-5f5ca63b-d7a5-4823-a4ee-b1649841fdaa.png)
