### ISSUE TITLE
Linear References missing cost attributes

### ISSUE THREAD

**Issue by PaulH97** [valhalla/valhalla#3671]
I have noticed that in the linear references (list of LineLocationReference) of a calculated route with the Valhalla routing service API there is no information about the cost attributes. 
Is there a way to get the cost attributes (length, time) explicitly per linear reference segment and not per maneuver?

**Comment by kevinkreiser** [comment]
Yes but only in the osrm output where every edge of the graph is returned. There are some units tests that show how to do this. Let me know if you need a pointer

**Comment by PaulH97** [comment]
Now it works properly as we need it, thanks for the help!

**Comment by kevinkreiser** [comment]
Yep the valhalla interface is maneuver based so it's not really possible without extending it to add such info

**Comment by PaulH97** [comment]
I have still one small question: Is there a way to divide the osrm output into smaller steps or ? Some steps in the route are very rudimentary (contain many points) while others are very small consisting of a few supporting points. 
Thank you so much for your help!

**Comment by PaulH97** [comment]
![Route from osrm](https://user-images.githubusercontent.com/63372566/176883043-39350dc2-070a-40dc-9582-95552e9a854e.png)
Perhaps this screenshot of the route will help you understand it
