### ISSUE TITLE
Does valhalla support other linux distributions like Centos

### ISSUE THREAD

**Issue by Sam-damn** [valhalla/valhalla#3682]
Iam trying to build Valhalla from source but i can't find equivalent packages in Yum, is it not possible to build it on  distributions other than ubuntu?

**Comment by nilsnolde** [comment]
Sure, centos is also linux and valhalla builds just fine, as well as OS X and windows. 

Which centos version are you on? From centos 7 you shouldn’t have problems with dependency versions. 

What’s happening if you build?

**Comment by Sam-damn** [comment]
when i try to do 
`yum install prime-server-bin`

and i get the following:  `No package prime-server-bin available.`
so this means there are some packages on ubuntu which have no equivalent on other distributions

**Comment by nilsnolde** [comment]
Right, you need to build that yourself, the apt-get instructions are only for Ubuntu/Debian. It’s pretty quick & easy: https://github.com/kevinkreiser/prime_server#build-and-install

**Comment by Sam-damn** [comment]
oh i see thanks a lot , are there any other dependencies that also need to be built manually too?

**Comment by nilsnolde** [comment]
You’ll see when you attempt to build Valhalla;) in case of an ancient centos yes, if modern no.
