### ISSUE TITLE
Allow to ignore `oneway` tags (bicycle costing)

### ISSUE THREAD

**Issue by qwerty287** [valhalla/valhalla#3686]
Hello,
first of all thank you for this application! It works (almost) perfectly for me. The only issue I had is a one-way street I'd like to ignore and take as a regular street.
Context: I have some GPS data from a ride with my bike and tried to use Valhalla's map matching. Unfortunately, I used a oneway in the wrong direction (I get off the bike and walked) and thus, Valhalla can't parse the track correctly. What I need is a costing option that allows me to ignore *every* `oneway` tag and just use it as a "regular" street. Thank you!

**Comment by nilsnolde** [comment]
there is an undocumented api parameter which lets you ignore oneways: e.g. `{ "costing": "bicycle", "narrative": false, "id": 1, "locations": [ { "lon": 13.475466, "lat": 52.505688 }, { "lon": 13.474954, "lat": 52.505059 } ], "costing_options": { "bicycle": { "ignore_oneways": true } } }` for this `oneway:bicycle` path: https://www.openstreetmap.org/way/1014084319

there's also a few more: `ignore_restrictions` (turn restrictions), `ignore_access` and `ignore_closures` (only relevant if you have live traffic). I'll PR a docs fix soon, it's about time :smile:
