### ISSUE TITLE
Exceeded max locations:20

### ISSUE THREAD

**Issue by saman-oz** [valhalla/valhalla#3698]
Hey guys... hope you are good
I run the Valhalla with docker image and get the below error:
```
{
    "error_code": 150,
    "error": "Exceeded max locations:20",
    "status_code": 400,
    "status": "Bad Request"
}
```
If you can debug it please let me know...

**Comment by nilsnolde** [comment]
generally it's always a good idea to include the exact request that raises an error. in this case it should be pretty straight forward: you need to patch your valhalla.json config file. `service_limits.<auto/pedestrian/truck/...>.max_locations` needs to be raised if you plan to have more waypoints than the default.

our docker image is quite a bit easier to use, you might wanna check it out: https://github.com/gis-ops/docker-valhalla.
