### ISSUE TITLE
Footway for bikes in Belarus

### ISSUE THREAD

**Issue by molind** [valhalla/valhalla#3705]
I checked state of the [wiki](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions) and [valhalla code](https://github.com/valhalla/valhalla/blob/master/valhalla/mjolnir/adminconstants.h#L43-L46) related to footway permissions in Belarus, it should allow to use footways for bikes instead of the driveways. But it doesn't. In Minsk users explicitly added bicycle=yes on multiple footways (e.g. https://www.openstreetmap.org/way/110906819). But it should be redundant as I understand.

Example: https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=30.3162905%2C53.8753305%2C30.3331368%2C53.8853113

**Comment by dnesbitt61** [comment]
I believe the country specific overrides for Belarus footways are correct. See valhalla/mjolnir/adminconstants.h.
I am able to generate bicycle routes on footways in the area you show - but these have bicycle=yes. Do you have an example where the OSM way is highway=footway without a bicycle=yes tag?

**Comment by molind** [comment]
@dnesbitt61 Yes I've seen and mentioned [valhalla code](https://github.com/valhalla/valhalla/blob/master/valhalla/mjolnir/adminconstants.h#L43-L46) related to footway permissions in Belarus. And example was already in my initial message.

> Example: https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=30.3162905%2C53.8753305%2C30.3331368%2C53.8853113

@kevinkreiser It's more like an issue, not just a question. Because it should allow to drive on footways, but it doesn't allow to do so in Mogilev (which is in Belarus).

**Comment by kevinkreiser** [comment]
@molind i think im not understanding what you are asking for. i had understood you are saying that bikes are NOT using highway=footway when they SHOULD use it. is that what you were saying? when i check the route that you linked i see it taking this way: https://www.openstreetmap.org/way/427635271#map=18/53.87579/30.31477 which is marked as highway=footway. sorry if im misunderstanding.

**Comment by molind** [comment]
@kevinkreiser Sorry if I wasn't clear enough. You got me right. I draw an expected result in blue. Footway should be preferred over highway for bikes in Belarus.
<img width="1192" alt="Screenshot 2022-08-15 at 21 34 55" src="https://user-images.githubusercontent.com/102496/184705326-6689b0a1-210b-4e0b-b489-25ac95da77c7.png">

**Comment by kevinkreiser** [comment]
yep so it seems the bug isnt with highway=footway specifically but maybe another tag or something generally wrong with costing to cause it to do that strange route that is suboptimal

**Comment by molind** [comment]
Yes, it could be something like that.

**Comment by molind** [comment]
Simplified example would be: https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=30.31588196754456%2C53.875508824077905%2C30.316520333290104%2C53.87587884055905

**Comment by kevinkreiser** [comment]
looking at the tagging im suspicious that its marked as footway=sidewalk. in other words, i would check if we arent blocking it because its marked as a sidewalk. @dnesbitt61 or @gknisely do you know off the top of your head if country overrides would work to open up bike access even if something is marked as a sidewalk?

**Comment by gknisely** [comment]
@kevinkreiser I will take a look as soon as I can do so

**Comment by dnesbitt61** [comment]
that is what I was wondering. given how I feel about bicycles on sidewalks it is possible that when set to Use = kSidewalk we disable bicycle access. I haven't found code yet that does this but with locate I see Use=sidewalk and bicycle access = false.

**Comment by kevinkreiser** [comment]
> given how I feel about bicycles on sidewalks

i was thinking it but im glad you said it :smile:

**Comment by gknisely** [comment]
So looking at this [way](https://www.openstreetmap.org/way/678502698#map=18/53.86854/30.31942), it is actually the `highway=footway` tag that is turning off access.  You can see it [here](https://github.com/valhalla/valhalla/blob/master/lua/graph.lua#L25) in the LUA.  Scroll to the right and you will see `["bike_forward"] = "false"}`.  This will be propagated to `bike_backward` too.  

As @dnesbitt61 noted, there is an override for the [defaults](https://github.com/valhalla/valhalla/blob/master/valhalla/mjolnir/adminconstants.h#L44) for Belarus.  Basically, we allow routing on footway, pedestrian, and, cycleway by default.  The logic is based on this [chart](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Belarus).   

So I ran a quick conversion here and I can not run a route here.  This looks like a bug to me as the use is `Use::kSidewalk` and we don't look for it in the [override logic](https://github.com/valhalla/valhalla/blob/master/src/mjolnir/graphenhancer.cc#L1526-L1528).  Fix should be a simple as checking for (`Use::kSidewalk` || `Use::kFootway`) for edges that are footways and pedestrians.  Also, may have to add logic [here](https://github.com/valhalla/valhalla/blob/master/src/mjolnir/countryaccess.cc) too.  @molind thank you for flagging this....I should have a fix this week unless you want to try to fix it.    cc @kevinkreiser

**Comment by kungfu303** [comment]
Hi @gknisely, did you add a fix to the above? No worries if not - just wanted to check as we're looking for a similar use case

**Comment by kevinkreiser** [comment]
Greg fixed it yes but we wanted to add a test for it before merging. If I have a second I can do so tonight

**Comment by gknisely** [comment]
@kevinkreiser going to see if i can do tests for the above and https://github.com/valhalla/valhalla/issues/3135#issuecomment-1243823807 now.

**Comment by kevinkreiser** [comment]
@gknisely many thanks, the examples in the existing admin builder tests should be pretty easy to extend similar to what im doing in the admin builder pr #3683

**Comment by molind** [comment]
Thanks a lot. I've build last commit of master on server, navigation data is build by valhalla@3.1.4. I'm not sure should I generate it from scratch as well? Then I've checked bike routes in Mogilev and it works almost as expected. :)

There is two road crossing. First is crossing=zebra (https://www.openstreetmap.org/way/631261674), second is crossing=marked (https://www.openstreetmap.org/way/608144621). And first one is used for bike route (https://route.getyourmap.com/demos/routing/#loc=18,53.872798,30.320018&directionsoptions=%7B%22language%22:%22en-US%22%7D&costing=%22bicycle%22&directionsoptions={%22language%22:%22en-US%22}), while second one isn't (https://route.getyourmap.com/demos/routing/#loc=16,53.886801,30.335655&directionsoptions=%7B%22language%22:%22en-US%22%7D&costing=%22bicycle%22&directionsoptions={%22language%22:%22en-US%22}).

**Comment by gknisely** [comment]
@molind you need to use the latest valhalla and you must rebuild the tiles

**Comment by molind** [comment]
@gknisely Checked it with the updated data, on the new valhalla. Same results.
<img width="482" alt="Screenshot 2022-09-14 at 12 50 15" src="https://user-images.githubusercontent.com/102496/190135011-eadbdd87-7cea-4dd5-a4ea-0eb91a23304a.png">

**Comment by molind** [comment]
Same results on valhalla.openstreetmap.de. I'm not sure however if it's related to the original issue. May be crossing=zebra and crossing=marked are processed in a different way.

https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=30.332651138305668%2C53.884498981560455%2C30.33385276794434%2C53.884815167173784

**Comment by gknisely** [comment]
@molind `Use::kPedestrianCrossing` probably needs to be added just like what I did for `Use::kSidewalk`  Should be an easy update and you should be able to follow what I did in the PR.  If you don't have time, I will update it as soon as possible.
