### ISSUE TITLE
ferry for hgv not respected

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3709]
we found that ferries are (basically) disabled for hgv, `use_ferry` is not parsed and hence the transition cost is 6 hours by default. however, there are lots of [ferries with hgv access](https://overpass-turbo.eu/s/1l3K) and I wonder if there was a specific reason for the current behavior or just an unintended oversight? it seems it's very intended, it's the only use of `BaseCostingOptionsConfig.disable_ferry_`.

it should be a quick addition if wanted.

**Comment by nilsnolde** [comment]
also the docs are misleading then

**Comment by kevinkreiser** [comment]
I don't see why we shouldn't allow it. We want the router to mirror the real world and if a ferry is the right choice in some scenarios, likely rare, it should be possible.
