### ISSUE TITLE
"No such file or directory" error should mention which file it is referring to

### ISSUE THREAD

**Issue by markstos** [valhalla/valhalla#3716]
I'm running a build from 6 days ago. When I start it up, I get some errors about "No such file or directory" which are hard to track down because there's no mention of what file Valhalla was trying to access at the time.

It would be appreciated if the locations are reviewed where files are attempted to be read, and error handling added that  updates the diagnostic message to mention /which/ file is not found. Thanks.

```
[INFO] Tile extract successfully loaded with tile count: 1121
[WARN] (stat):  No such file or directory
[WARN] Traffic tile extract could not be loaded
```

**Comment by kevinkreiser** [comment]
It's referring to the traffic extract, ie the next warning tells you that. Unless you have real time traffic data you can safely ignore this warning. If you don't want to see the warning then remove the traffic extract from your json configuration file.

**Comment by markstos** [comment]
Thanks. In `valhalla.json`, I have:

```
    "traffic_extract": "",
```

Shouldn't that be enough to signal that I don't have a traffic extract?

I'd like to leave the key in the config file to document that it exists.

**Comment by kevinkreiser** [comment]
the library isnt that pedantic, if you have the key in the config it will try to use whatever is in the value even if its an empty string. you have the option of ignoring the warning or removing it knowing its documented in the config builders (`valhalla_build_config`) help flag

**Comment by chrstnbwnkl** [comment]
If your container shuts down immediately after the service is fired up, the missing traffic extract is certainly not the root cause. Feel free to open an issue in the docker image repository, preferably with container logs.
