### ISSUE TITLE
Show distance limit in error message

### ISSUE THREAD

**Issue by not-my-profile** [valhalla/valhalla#3722]
When I attempt to plan a longer route at https://valhalla.openstreetmap.de/ I get the error message:

> OSM: Path distance exceeds the max distance limit for bicycle.

It would be nice if the error message said what the distance limit is.

**Comment by kevinkreiser** [comment]
indeed, others have mentioned this, the problem with putting the limit in there is that it makes the error message change depending on your config. we have added error ids to encourage people not to hardcode string checks in their client side code but we cant guarantee people dont do that. by this point though its probably mostly harmless if we made this change

**Comment by Luc35b** [comment]
Hello I’m new to to open source projects could someone assist me on how to begin and where this issue is located.

**Comment by Luc35b** [comment]
Could someone help me get started on fixing this issue as I this is my first open source contribution

**Comment by reillywynn** [comment]
Hi, I attempted to add the line of code to add the max distance to the error message. I submitted a pull request, let me know how it is. Thanks.
