### ISSUE TITLE
Build from source errors

### ISSUE THREAD

**Issue by rwrx** [valhalla/valhalla#3728]
I have tried to build Valhalla from source on Ubuntu 18.04, but I got warning treated as error stating that minor is a keyword in C language as backward compatibility. When I patched it locally - renaming minor() function to get_minor() I got another error in benchmarks. I am sorry, but I do not have actual error messages at machine from which I am creating this issue.

How could I patch these errors properly? Are build instructions in this repository for Linux correct?

I have tried to build master and also version 3.1.4, but the outcome was the same. I think that 2 years ago, I had no problem building version 3.1.0 from source.

**Comment by kevinkreiser** [comment]
@rwrx are you stuck on 18.04? thats a pretty old distribution. we build in CI on 20.04 so for sure the code will build there. there is always a possibility we need an update of the docs but if you can i would move to 20.04 and try there. let me know how it goes!

**Comment by rwrx** [comment]
@kevinkreiser thank you a lot for your response. I have tried to compile it on Ubuntu 20.04 and was compiled, I just needed some time to start generating tiles, so now I can confirm that it seems it works. Thank you.
