### ISSUE TITLE
Localserver request issue 

### ISSUE THREAD

**Issue by 0xcro3dile** [valhalla/valhalla#3730]
when I run curl command I recive 
```
{
  "error_code": 171,
  "error": "No suitable edges near location",
  "status_code": 400,
  "status": "Bad Request"
}
```

**Comment by kevinkreiser** [comment]
this usually means you dont have any data loaded for the location you were trying to use. just showing the error is not enough information for anyone to help you debug further. things to check:

1. did you build tiled routing data (valhalla_build_tiles)?
2. is valhalla configured to and can it actually load the tiles you've built?  this should be in your json config under mjolnirl.tile_dir
3. is the request location in a part of the world that is covered by your tileset?

**Comment by nilsnolde** [comment]
closing due to lack of feedback. feel free to re-open again if you couldn't make it work @0xcro3dile
