### ISSUE TITLE
Truck - weird ferry issue

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3731]
There's been an issue with truck routing where it takes the ferry or not depending on whether a waypoint is placed before or after a certain graph node. What's hard to understand here is that this node connect two pretty identical edges (in terms of FRC & name), so there's nothing hierarchy related going on.

takes ferry: https://valhalla.openstreetmap.de/directions?profile=truck&wps=12.199952602386476%2C54.12032571468474%2C11.806182861328127%2C55.45160500981926
![image](https://user-images.githubusercontent.com/25637358/188108221-a15044a0-4d8c-443c-9aec-b91ba2a998aa.png)

doesn't take ferry: https://valhalla.openstreetmap.de/directions?profile=truck&wps=12.200242280960083%2C54.12061181812585%2C11.806182861328127%2C55.45160500981926
![image](https://user-images.githubusercontent.com/25637358/188108324-5a243777-c6d8-4475-8363-0bf38e6e3696.png)

Any clues what might happen here? Note, with `auto` it works fine in both cases.

EDIT: in fact it takes a ferry in all cases, but in the latter case it takes an unreasonable detour.

**Comment by nilsnolde** [comment]
I had another go at this particular one. As it's only reproducible on this very long route I didn't want to debug, so I scoured the code for some differences between truck & car costing but couldn't come up with anything useful. It had to do smth with the algorithm and the only reasonable place to look at were the hierarchy limits. I raised them to 10x what they are by default and indeed it allows the truck to use the ferry even when further away.

What I don't understand: car and truck have the same hierarchy limits and if anything I'd expect truck to expand on _less_ transitions than car (i.e. truck restrictions), not the other way around. Nothing changes if I basically make the truck a car by setting all costing options to 0. Anyone got a clue why the hell truck exhausts the limit faster than car and doesn't want to transition down to the closer ferry anymore?

**Comment by nilsnolde** [comment]
Note so self: Maybe I should try the bidir astar expansion action on this to see what the differences are between car & truck expansion.

**Comment by nilsnolde** [comment]
Alright, another update.. I plotted the A* expansion to see what's happening. Not much compared to car, the picture looks overall pretty similar. Around the pier of the ferry the truck should take though, it's just not seeing the ferry line..

red is the route a car takes, blue the truck expansion:
![image](https://user-images.githubusercontent.com/25637358/205367237-69b31186-547a-43dc-ad21-99174d1f115a.png)

That's kinda explainable: the road the car takes after the first roundabout is not open for `hgv`: https://www.openstreetmap.org/way/324027905.

Even more interesting is what happens for the request where it takes the right ferry. Actually stuff happens there that shouldn't happen, yet I'm really not sure why this is working when setting the origin just a few hundred meters further..

again, the route truck takes when taking the right ferry and in blue the expansion result of truck when it's **not** taking the right ferry:
![image](https://user-images.githubusercontent.com/25637358/205369320-7f6d4a12-aead-4c86-a3b8-30ac6fa55c69.png)

The route it's taking is sketchy at best.. It's all `service` roads (hello service cost), and right where the expansion stops is a building where the road becomes a `tunnel=building_passage` (see [TODO](https://github.com/valhalla/valhalla/blob/8d33f031e71fec6ca69981670c846d02fef7e5a5/lua/graph.lua#L392) to fix that in the graph.lua). So arguably, it's a poor route even when it pretends to do the right thing.

What I don't understand here, is why truck is not taking [the perfectly fine tertiary road](https://www.openstreetmap.org/way/65354552#map=18/54.14330/12.10107) to get to the terminal instead of this horrible service road.

**Comment by nilsnolde** [comment]
after talking to @kevinkreiser, our theory currently is that it's likely some kind of combination of early exhausted hierarchies and a search that's aborted too soon, so I'll try:

- increase hierarchy limits again. was it really a > factor increase necessary? does it take tertiary or service? how about alternates?
- increase the threshold for expansion extension: https://github.com/valhalla/valhalla/blob/master/src/thor/bidirectional_astar.cc#L24. should at least find _a_ route. see if it'd find the service or tertiary road
- try with an alternate, which routes does it find then

ultimately I just want this to make more sense so that I can at least have a consistent explanation for all these observations, so the more tests from more different perspectives the more likely the interpretation is accurate. and also examine in more detail (if it's true), why truck costing exhausts its hierarchies so much quicker when the expansion actually seems quite similar to car (only thing that's a bit different is some access tags & some cost).

**Comment by nilsnolde** [comment]
maybe there's even an option to rethink the hierarchy limits? e.g. have them a bit more dynamic so we can increase them when we know the origin/destination are in a dense area? it looks feasible, the hierarchy limits are defined in the `DynamicCost` constructor and thor constructs its own cost factory. so we could also look at the density and factor that in when deciding on the hierarchy limits. the idea being that in dense areas we allow more expansion on the local/arterial level as it doesn't cover much ground before the default limits are exhausted compared to a sparse network.

would that be worth investigating @kevinkreiser ? doesn't seem like a huge code change, but I have little feeling for the impact on performance. I'm also not sure how to best approach the trade-off performance & quality. would we need cases like the above (pending final evaluation, not sure yet what's really wrong), which can serve as a reference (you mentioned more cases like this, maybe we can dig some up?)? i.e. by tweaking the possible density-weighted hierarchy limits logic to find the more reasonable route and then discussing if the performance impact of relaxed hierarchy limits is worth the benefit?

**Comment by gknisely** [comment]
@nilsnolde you probably already checked into this, but are we hitting any restrictions with the truck routing that could be causing differences in the expansion?  Just a thought.

**Comment by nilsnolde** [comment]
Yeah, I tried disabling basically all restrictions by making truck more or less a car and even including the `ignore_*` options, so there couldn't possibly be any left. Same same.. That also has the effect to exhaust the allowed cycles and hierarchy limits faster, but car could find the same route as without those options, just truck not. Just got set up to investigate with more time, will update later today.

**Comment by kevinkreiser** [comment]
I have a theory which I've not yet vetted by looking at code...

Because ferry connector roads are low class we up class them with reclassify ferries logic. Otherwise hierarchy pruning would fail routes that require ferry use. I bet the reclassify ferry logic looks for auto access though I didn't confirm this. If the roads that we upclassed did not have truck access but there are other truck accessible paths that stay low class then technically the trucks can use the ferry but they miss it based on transition counting and the positioning of thier origin and destination locations

**Comment by nilsnolde** [comment]
Yeah that makes a whole lot of sense, esp. in this case with the OSM data involved around the ferry pier: there's an obvious connection which is `hgv: false` and alternative connections which are all `hgv: true; motorcar: false`. 

I'll naively try to include hgv access at that point, thanks for the pointer @gknisely . Super annoying, since the graph is fairly big, but whatever.. smth like this might work then no?

```diff
index c8ef8d01f..c046862c0 100644
--- a/valhalla/mjolnir/node_expander.h
+++ b/valhalla/mjolnir/node_expander.h
@@ -97,12 +97,12 @@ struct Edge {
       e.attributes.driveableforward = false;
       e.attributes.driveablereverse = false;
     } else {
-      e.attributes.driveableforward = way.auto_forward();
-      e.attributes.driveablereverse = way.auto_backward();
+      e.attributes.driveableforward = way.auto_forward() || way.truck_forward();
+      e.attributes.driveablereverse = way.auto_backward() || way.truck_backward();
     }
     e.attributes.link = way.link();
     e.attributes.driveable_ferry =
-        (way.ferry() || way.rail()) && (way.auto_forward() || way.auto_backward());
+        (way.ferry() || way.rail()) && (way.auto_forward() || way.auto_backward() || way.truck_forward() || way.truck_backward());
     e.attributes.reclass_link = false;
     e.attributes.reclass_ferry = false;
     e.attributes.has_names =
 ```

**Comment by nilsnolde** [comment]
Yep, that worked :partying_face: great stuff @kevinkreiser @gknisely ! So at least we know now what the problem is. I'll PR this one and hope that the tests work. Or maybe you have some more concerns?

If all is good, I think it'd be fine to not care about motorbike-only edges or others. Truck & car have the most potential for mutually exclusive access.

**Comment by nilsnolde** [comment]
> maybe there's even an option to rethink the hierarchy limits? e.g. have them a bit more dynamic so we can increase them when we know the origin/destination are in a dense area?

I'd still like to discuss this though, even if it wasn't a problem here.
