### ISSUE TITLE
How to ovewrite Valhalla tiles?

### ISSUE THREAD

**Issue by crekIron** [valhalla/valhalla#3732]
I have build tiles for the original data successfully and they are stored in their respective locations according to my config file. Now, I want to add new map data. Whenever I give another osm data for same config file, it removes the previous tiles made.
I want to update the new map data upon the previous tiles only. I checked `valhalla_build_tiles -h` option, there I got to know about stating starting stage and ending stage. 
So, I started run the command `valhalla_build_tiles -c valhalla.json -s parseways map.osm.pbf` but then this command gives a segmentation fault later. The map data is not corrupted. Tiles are built perfectly fine if `-s`option is not given.

Is there a way to update existing tiles? Or we need to build them from scratch everytime.

**Comment by nilsnolde** [comment]
Jep from scratch every time currently. There’s a few issues about this already. While we’d love to be able to only rebuild tiles where data actually changed (I guess this was one of the goals when deciding to tile the graph), there’s quite a few obstacles along the way and it’s a big project in fact.
