### ISSUE TITLE
Pedestrian isodistance includes area not reachable within distance parameter

### ISSUE THREAD

**Issue by akadouri** [valhalla/valhalla#3741]
Trying out the pedestrian isochrone/isodistance API with the following query (using the QGIS plugin and the docker image `gisops/valhalla:latest` with data from an OSM extract of Brooklyn, NY, USA):
```
2022-09-11T12:43:49     INFO    url: http://localhost:8002/isochrone?access_token=
             Parameters: {
              "costing": "pedestrian",
              "show_locations": false,
              "contours": [
              {
              "distance": 1.1
              }
              ],
              "polygons": true,
              "id": 1,
              "costing_options": {
              "pedestrian": {
              "max_hiking_difficulty": "1",
              "walking_speed": 0,
              "walkway_factor": 0.0,
              "alley_factor": 0.0,
              "driveway_factor": 0.0,
              "use_ferry": 0.0,
              "step_penalty": 0,
              "shortest": true
              }
              },
              "locations": [
              {
              "lon": -73.992891,
              "lat": 40.665374
              }
              ]
             }
```
This includes a region in a nearby cemetery that isn't reachable within the 1.1km distance, shown in the image below the shortest path to that region is around 1.79km.

Is this an artifact of the implementation (which according to the [doc](https://valhalla.readthedocs.io/en/latest/thor/isochrones/) uses grids)? Is there a way to get the grid output?

![Screen Shot 2022-09-11 at 12 48 34 PM](https://user-images.githubusercontent.com/3322573/189539562-01b72a69-3b49-4f34-bc07-e0df7b4f3d11.png)

**Comment by kevinkreiser** [comment]
yes it uses grids, and you can probably walk to the intersection of 7th ave and 20th street which is right next to it in less than 1.1km right? the isochrone isnt exact, if it were it would just be a skeleton of the of the shapes of the edges in the graph. for smaller isochrones though we could make the resolution of the grid finer and get the desired effect. it might be useful to either find a better heuristic for grid size (based on estimated maximum area covered) or allow tweaking it to some degree in the request itself.

**Comment by kevinkreiser** [comment]
oh and no we dont return the grid itself at this time. ive considered it before but its not implemented yet. one option could be to avoid doing the contour algorithm entirely and just making contours as the parimeter of the contiguous grid area. it would look kind of blocky but could be smoothed in another way (lots of algorithms exist)

**Comment by nilsnolde** [comment]
There's some discussion around that in this thread: https://github.com/valhalla/valhalla/issues/3212#issuecomment-901884900. Since this issue is an artifact which would very likely be solved by following the discussion over there, let's close here (feel free to re-open if that doesn't cover it). Would be nice to have more granular pedestrian isochrones soonish:)

**Comment by akadouri** [comment]
Thanks for the responses, I appreciate it. Yeah you can get pretty close to that spot, there is a fence but it's not mapped (I don't think that would matter testing in a couple other spots). It is the same issue, might have to start digging into the code...

ps @kevinkreiser I just noticed the [doc page](https://valhalla.readthedocs.io/en/latest/thor/isochrones/) says "KEVIN -please write a paragraph or 2 to describe how the contours are formed and output!" 😉
