### ISSUE TITLE
Building europe fails with `way_nodes.bin has an incorrect size for type`

### ISSUE THREAD

**Issue by markstos** [valhalla/valhalla#3749]
Today I attempted to build the OSM europe extract from Geofabrik on a maching with 60 GB of RAM and 8 cores. 

It failed with the following error. From the monitoring I have, it neither appears CPU, Memory nor disk were exhausted at the time. 

```
Sep 13 17:59:24 Parsing files for nodes: /custom_files/europe-latest.osm.pbf
Sep 13 17:59:24 Sorting osm way node references by node id...
Sep 13 18:22:45 terminate called after throwing an instance of 'std::runtime_error'
Sep 13 18:22:45 what():  sequence: /custom_files/valhalla_tiles/way_nodes.bin has an incorrect size for type
```
The referenced `way_nodes.bin` is 53 GB.

The one thing I can see in the logs posted above is that there's a gap in the timestamps of about 20 minutes from when the sorting step started to when the crash happens.

The gisops container I'm building is fairly recent:

> docker.io/gisops/valhalla@sha256:584a3e2a75fbe6e95824168e34091b1763fab9d13861886cd8d2ee9c5b53f88c

I will try another build from scratch and see if the error is triggered again.

**Comment by kevinkreiser** [comment]
Is it possible you ran out of disk? We generally need like 2 or 3x the disk space for whatever size the extract is. For ram you probably only need like 8 gb but more ram can make some parts of the processing go faster

**Comment by markstos** [comment]
I didn't see a disk space problem in our monitoring, but I added 50 GB of disk space, and it succeeded. Since I can't reproduce the issue, I'll close this. Thanks for the feedback!

**Comment by ianthetechie** [comment]
Sorry for the necro post, but I've been getting the same issue on occasion and it turns out we were just under the rule of thumb Kevin noted. It'd be nice if this failed in a slightly more graceful way, as it's not apparent what happened. Strangely, the disk is not full at all (had over 100GB free at the time of the last failure), so I presume there's a spot where it's trying to do a very large write and just fails in a non-obvious way.

**Comment by nilsnolde** [comment]
Yeah when parsing it quickly accumulates >> 100 GB in temp files (for the planet). I agree, if possible, it’d be nicer to have a more sensible error thrown.
