### ISSUE TITLE
OSX Build Broken For Uk Admin Overrides

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3756]
Sadly we have a broken lint build which we've been ingoring for a few merges and because of that it seems we missed an actual failure on a recent pull request: https://github.com/valhalla/valhalla/pull/3746

@gknisely would you be able to look into the OSX build failure there?

**Comment by gknisely** [comment]
@kevinkreiser yes.  Looks like we are expecting a name but it was not added.
