### ISSUE TITLE
'error': 'No suitable edges near location'

### ISSUE THREAD

**Issue by Katja-M** [valhalla/valhalla#3762]
Hello,

I would like to use valhalla for getting driving distance data.
I have installed valhalla through the docker image.

Here is my input dictionary:

`data = {"sources":[{"lat":33.791318,"lon":-84.396295}],"targets":[{"lat":33.781849,"lon":-84.399267}],
        "costing":"auto", "directions_options":{"units":"miles"}}`

My code (in Python)

`url = "http://localhost:8002/sources_to_targets"

r = requests.post(url, json=data)

response_text = json.loads(r.text)`

My output:

{'error_code': 171,
 'error': 'No suitable edges near location',
 'status_code': 400,
 'status': 'Bad Request'}

My valhalla container is running. I have downloaded the maps of north america.
Please let me know if you need further information.

Thanks for any help in advance

**Comment by nilsnolde** [comment]
Can you show us the full docker commands you did and the docker logs of the container?

**Comment by Katja-M** [comment]
I have installed valhalla in 

C/Users/MyUsername/valhalla

I am on Windows 11 Professional

In Powershell, cd into the folder, I am running the command
 `docker-compose up --build`

It took me a while to figure out that it needs about 20 minutes until you can send a request, but anyway here is the log
The request in my initial question is request id 11 but I was facing the same response with all other requests (if it wasn't a json
file parsing problem). I have posted request id 11 here because it is my test dataset)
`
INFO: Running container with user valhalla UID 59999 and GID 59999.

WARNING: Hash not found for: /custom_files/north-america-latest.osm.pbf!
INFO: Found routing tiles with 'use_tiles_ignore_pbf' True.
INFO: Jumping directly to the tile loading!
WARNING: User valhalla is running with sudo privileges. Try building the image with a host user's UID & GID.
INFO: Found config file. Starting valhalla service!
2022/09/26 14:38:34.329011 [INFO] Tile extract successfully loaded with tile count: 26589
2022-09-26 14:37:41,277  INFO: Finished tarring 26589 tiles to /custom_files/valhalla_tiles.tar
2022/09/26 14:38:34.329129 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.337736 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.337749 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.337803 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.337821 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.347438 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.347518 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.347527 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.348602 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.348661 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.348692 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.348724 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.349110 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.349140 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.353231 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.353373 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.353405 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.358539 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.358539 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.358624 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.358632 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.358633 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.358643 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.359890 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.359923 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.359927 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.366460 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.366543 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.366552 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.368186 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.368245 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.368251 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.378881 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.378899 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.378981 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.378981 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.378988 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.378990 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.392544 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.392615 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.392623 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.402805 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.402905 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.402914 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.414019 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.414081 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.414088 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.414615 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.414666 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.414673 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.422323 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.422438 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.422448 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.425517 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.425591 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.425598 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.426642 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.426690 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.426696 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.440113 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.440183 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.440189 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.469829 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.469899 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.469906 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.511065 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.511136 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.511142 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:34.517626 [INFO] Tile extract successfully loaded with tile count: 26589
2022/09/26 14:38:34.517672 [WARN] (stat):  No such file or directory
2022/09/26 14:38:34.517676 [WARN] Traffic tile extract could not be loaded
2022/09/26 14:38:35.570695 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.570692 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.570794 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.570875 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.570965 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.571085 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.571169 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.571711 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.575306 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.590385 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.651682 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.651742 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.651810 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.651873 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.651912 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.651978 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.652050 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.652112 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.652213 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.652519 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.664312 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.709990 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:35.749048 [WARN] Corrupt elevation data: /custom_files/elevation_data/N29/N29W086.hgt
2022/09/26 14:38:35.797905 [WARN] Corrupt elevation data: /custom_files/elevation_data/N31/N31W099.hgt
2022/09/26 14:38:36.213667 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.213731 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.213796 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.213863 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.213962 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.214016 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.214077 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.214098 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.214301 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.214322 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.214652 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.217055 [WARN] Corrupt elevation data: /custom_files/elevation_data/N40/N40W084.hgt
2022/09/26 14:38:36.691369 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691425 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691488 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691547 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691606 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691671 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691738 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691812 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691852 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.691923 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.692063 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.692909 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W055.hgt
2022/09/26 14:38:36.736209 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736312 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736376 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736443 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736542 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736611 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736641 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736742 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736773 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.736870 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.737003 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.737280 [WARN] Corrupt elevation data: /custom_files/elevation_data/N46/N46W099.hgt
2022/09/26 14:38:36.821202 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821256 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821322 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821424 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821492 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821567 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821649 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821740 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821905 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821945 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.821946 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.822397 [WARN] Corrupt elevation data: /custom_files/elevation_data/N47/N47W089.hgt
2022/09/26 14:38:36.897172 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897230 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897293 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897377 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897424 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897489 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897644 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897693 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897651 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897842 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.897915 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.898097 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W065.hgt
2022/09/26 14:38:36.917682 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.917740 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.917804 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.917859 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.917923 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.917974 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.918035 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.918129 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.918286 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.918331 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.918425 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.920030 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W092.hgt
2022/09/26 14:38:36.945702 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.945775 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.945846 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.945908 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.945978 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.946092 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.946113 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.946274 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.946318 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.946444 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.946728 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:36.947614 [WARN] Corrupt elevation data: /custom_files/elevation_data/N48/N48W117.hgt
2022/09/26 14:38:37.051579 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.051636 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.051695 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.051757 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.051908 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.051925 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.051988 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.052093 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.052151 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.052189 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.052414 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.053159 [WARN] Corrupt elevation data: /custom_files/elevation_data/N50/N50W057.hgt
2022/09/26 14:38:37.540896 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.540952 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541012 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541078 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541125 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541208 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541366 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541400 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541464 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541529 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.541652 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.544555 [WARN] Corrupt elevation data: /custom_files/elevation_data/N56/N56W092.hgt
2022/09/26 14:38:37.806664 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.806718 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.806783 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.806866 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.806962 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807027 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807096 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807172 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807261 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807332 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807400 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
2022/09/26 14:38:37.807835 [WARN] Corrupt elevation data: /custom_files/elevation_data/N60/N60W114.hgt
0 2022/09/26 14:40:35.487502 GET /sources_to_targets?json=%7B'costing':%20'auto',%20'directions_options':%20%7B'units':%20'miles'%7D,%20'sources':%20%5B%7B'ID':%20'C0',%20'lat':%2042.788494,%20'lon':%20-73.941979%7D,%20%7B'ID':%20'C1',%20'lat':%2042.902282,%20'lon':%20-74.439683%7D,%20%7B'ID':%20'C2',%20'lat':%2043.443544,%20'lon':%20-73.648811%7D,%20%7B'ID':%20'C3',%20'lat':%2043.113847,%20'lon':%20-74.422175%7D,%20%7B'ID':%20'C4',%20'lat':%2042.25007,%20'lon':%20-73.631871%7D%5D,%20'targets':%20%5B%7B'ID':%20'C0',%20'lat':%2042.788494,%20'lon':%20-73.941979%7D,%20%7B'ID':%20'C1',%20'lat':%2042.902282,%20'lon':%20-74.439683%7D,%20%7B'ID':%20'C2',%20'lat':%2043.443544,%20'lon':%20-73.648811%7D,%20%7B'ID':%20'C3',%20'lat':%2043.113847,%20'lon':%20-74.422175%7D,%20%7B'ID':%20'C4',%20'lat':%2042.25007,%20'lon':%20-73.631871%7D%5D%7D HTTP/1.1
2022/09/26 14:40:35.487908 [INFO] Got Loki Request 0
2022/09/26 14:40:35.490212 [WARN] 400::Failed to parse json request request_id=0
0 2022/09/26 14:40:35.490632 400 224
1 2022/09/26 14:41:06.556547 POST /sources_to_targets HTTP/1.1
2022/09/26 14:41:06.556923 [INFO] Got Loki Request 1
2022/09/26 14:41:06.848502 [WARN] 400::No suitable edges near location request_id=1
1 2022/09/26 14:41:06.848811 400 228
2 2022/09/26 14:41:38.133353 GET / HTTP/1.1
2022/09/26 14:41:38.133720 [INFO] Got Loki Request 2
2022/09/26 14:41:38.134045 [WARN] 400::Try any of:'/locate' '/route' '/height' '/sources_to_targets' '/optimized_route' '/isochrone' '/trace_route' '/trace_attributes' '/transit_available' '/expansion' '/centroid' '/status'  request_id=2
2 2022/09/26 14:41:38.134441 404 390
3 2022/09/26 14:41:38.521069 GET /favicon.ico HTTP/1.1
2022/09/26 14:41:38.521563 [INFO] Got Loki Request 3
2022/09/26 14:41:38.521926 [WARN] 400::Try any of:'/locate' '/route' '/height' '/sources_to_targets' '/optimized_route' '/isochrone' '/trace_route' '/trace_attributes' '/transit_available' '/expansion' '/centroid' '/status'  request_id=3
3 2022/09/26 14:41:38.522180 404 390
4 2022/09/26 14:42:12.566876 GET /sources_to_targets HTTP/1.1
2022/09/26 14:42:12.567176 [INFO] Got Loki Request 4
2022/09/26 14:42:12.567505 [WARN] 400::Insufficiently specified required parameter 'locations' or 'sources & targets' request_id=4
4 2022/09/26 14:42:12.567785 400 275
5 2022/09/26 14:43:12.966280 GET /sources_to_targets?json={%27costing%27:%20%27auto%27,%20%27directions_options%27:%20{%27units%27:%20%27miles%27},%20%27sources%27:%20[{%27ID%27:%20%27C0%27,%20%27lat%27:%2042.788494,%20%27lon%27:%20-73.941979},%20{%27ID%27:%20%27C1%27,%20%27lat%27:%2042.902282,%20%27lon%27:%20-74.439683},%20{%27ID%27:%20%27C2%27,%20%27lat%27:%2043.443544,%20%27lon%27:%20-73.648811},%20{%27ID%27:%20%27C3%27,%20%27lat%27:%2043.113847,%20%27lon%27:%20-74.422175},%20{%27ID%27:%20%27C4%27,%20%27lat%27:%2042.25007,%20%27lon%27:%20-73.631871}],%20%27targets%27:%20[{%27ID%27:%20%27C0%27,%20%27lat%27:%2042.788494,%20%27lon%27:%20-73.941979},%20{%27ID%27:%20%27C1%27,%20%27lat%27:%2042.902282,%20%27lon%27:%20-74.439683},%20{%27ID%27:%20%27C2%27,%20%27lat%27:%2043.443544,%20%27lon%27:%20-73.648811},%20{%27ID%27:%20%27C3%27,%20%27lat%27:%2043.113847,%20%27lon%27:%20-74.422175},%20{%27ID%27:%20%27C4%27,%20%27lat%27:%2042.25007,%20%27lon%27:%20-73.631871}]} HTTP/1.1
2022/09/26 14:43:12.966469 [INFO] Got Loki Request 5
2022/09/26 14:43:12.966639 [WARN] 400::Failed to parse json request request_id=5
5 2022/09/26 14:43:12.966863 400 224
6 2022/09/26 14:49:30.318888 POST /sources_to_targets HTTP/1.1
2022/09/26 14:49:30.319288 [INFO] Got Loki Request 6
2022/09/26 14:49:30.322554 [WARN] 400::No suitable edges near location request_id=6
6 2022/09/26 14:49:30.323018 400 228
7 2022/09/26 14:52:34.866151 POST /sources_to_targets HTTP/1.1
2022/09/26 14:52:34.866481 [INFO] Got Loki Request 7
2022/09/26 14:52:34.869184 [WARN] 400::No suitable edges near location request_id=7
7 2022/09/26 14:52:34.869712 400 228
8 2022/09/26 14:54:23.658203 POST /sources_to_targets HTTP/1.1
2022/09/26 14:54:23.658498 [INFO] Got Loki Request 8
2022/09/26 14:54:23.661213 [WARN] 400::No suitable edges near location request_id=8
8 2022/09/26 14:54:23.661624 400 228
9 2022/09/26 15:04:14.024693 POST /sources_to_targets HTTP/1.1
2022/09/26 15:04:14.025036 [INFO] Got Loki Request 9
2022/09/26 15:04:14.124763 [WARN] 400::No suitable edges near location request_id=9
9 2022/09/26 15:04:14.125067 400 228
10 2022/09/26 15:10:44.517055 POST /sources_to_targets HTTP/1.1
2022/09/26 15:10:44.517387 [INFO] Got Loki Request 10
2022/09/26 15:10:44.519371 [WARN] 400::No suitable edges near location request_id=10
10 2022/09/26 15:10:44.519773 400 228
11 2022/09/26 15:11:28.891936 POST /sources_to_targets HTTP/1.1
2022/09/26 15:11:28.892366 [INFO] Got Loki Request 11
2022/09/26 15:11:28.894098 [WARN] 400::No suitable edges near location request_id=11
11 2022/09/26 15:11:28.894407 400 228
12 2022/09/26 15:18:46.231114 GET /sources_to_targets?json=%7B'sources':%20%5B%7B'lat':%2033.791318,%20'lon':%20-84.396295%7D%5D,%20'targets':%20%5B%7B'lat':%2033.781849,%20'lon':%20-84.399267%7D%5D,%20'costing':%20'auto',%20'directions_options':%20%7B'units':%20'miles'%7D%7D HTTP/1.1
2022/09/26 15:18:46.231567 [INFO] Got Loki Request 12
2022/09/26 15:18:46.231878 [WARN] 400::Failed to parse json request request_id=12
12 2022/09/26 15:18:46.232163 400 224
`
Thanks

**Comment by nilsnolde** [comment]
This would be the right repo: https://github.com/gis-ops/docker-valhalla/issues.

This gives a clue (though not necessarily a proof..):

```
WARNING: Hash not found for: /custom_files/north-america-latest.osm.pbf!
INFO: Found routing tiles with 'use_tiles_ignore_pbf' True.
```

Do you have a tileset flying around from another build than `/custom_files/north-america-latest.osm.pbf`? You can enable `"service_limits.status.allow_verbose": true` and hit the `/status` endpoint with `{"verbose": true}`. You'll get a GeoJSON that shows you the current tile extent. If it's pointing somewhere else on the globe, you'll have to force build.
