### ISSUE TITLE
Templatize forward/reverse Dijkstra in TimeDistance matrix

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3764]
While looking a bit more into the matrix code, I wondered if we couldn't get rid of the whole reverse traversal code in timedistance matrix. I think it's a bit superfluous and would reduce the code to more or less half of what it is now. 

If we have more targets than sources, we can switch them and do forward expansion instead of doing a reverse traversal from the targets (and switch them back before returning them). (or the more elaborate way of templating the traversal functions similar to what was done semi-recently on the uni-directional astar)

Cc @dnesbitt61

**Comment by nilsnolde** [comment]
Right, my suggestion is that we could transpose a many:one to a one:many. We’re putting the problem in a ManyToOne when there’s more sources than targets, instead we could switch sources and targets in that case, to ditch the reverse algo. It’s just a lot of duplication. Templating being another alternative, but more laborious (for me at least). Does that make sense?

**Comment by dnesbitt61** [comment]
if you had 50 to 1, by transposing it would run 50 sequential calls rather than a single call.

**Comment by nilsnolde** [comment]
Hm, maybe I’m being daft but 50:1 with many:1 is the same as 1:50 with 1:many? What I mean is, we could always do a 1:many (ie forward expansion), by just switching source locations & target locations in case there’s more sources than targets.

**Comment by dnesbitt61** [comment]
They are not the same due to the presence of oneway roads and divided highways/ramps. I assume the times and distances would usually be close but would not be the same. The same way that a route from A->B is not always the same time/distance as the route from B-->A.

**Comment by nilsnolde** [comment]
I think I'm really not explaining myself clearly, sorry for that!

Considering `sources: [A,B]` and `targets: [C]`, so more sources than targets.

Right now: We do a many:1 with reverse traversal, so C -> A and C -> B.

My thought: If more sources than targets, swap them, so that `sources: [C]` and `targets: [A, B]`, then do 1:many, i.e. also C -> A and C -> B.

Then reverse traversal and many:1 would be redundant, we'd always do a 1:many and save quite a bit of code/logic. I can't see the logical flaw, but that doesn't mean anything :sweat_smile:

**Comment by dnesbitt61** [comment]
I have to admit that I was wrong and missed the point. So (just to expand for myself)
Start with more sources than targets: sources A,B,C,D,E and target Z. 
We currently do 1 pass expanding from Z in reverse until A,B,C,D,E are found.
Swapping would be: source Z, targets A, B, C, D, E
Then it is one pass expanding forward from Z giving Z->A, Z->B , etc.
This is what is desired! Very nice!

**Comment by nilsnolde** [comment]
Jep exactly:) so you’re on board with the idea of refactoring it @dnesbitt61 ?

**Comment by kevinkreiser** [comment]
yeah exactly @dnesbitt61 swapping will not work. i had to read it a few times but i'm pretty sure they are not equivalent. let me try a succinct summary:

when Z is the target its a destination. expanding in reverse from Z back to A keeps Z as a destination and A as an origin whereas expanding forward from Z to A turns Z into an origin and A into a destination.

for me, using the terms origin and destination makes the reasoning clear. hopefully it helps other people but anyway we could still do the other thing @nilsnolde suggested where we templatize the expansion direction to reduce the size of the code

**Comment by nilsnolde** [comment]
Of course.. it’s reverse from Z‘s perspective, uff.. Indeed, thinking about it in terms of origin/destination makes it clearer.. Sorry for the time waste.. As compensation, I’ll see if I can templatize it😊

**Comment by dnesbitt61** [comment]
No problem. This stuff is never easy (hence my flip-flopping!)
