### ISSUE TITLE
Increase Distance and Maximum Locations for Distance Matrix in Valhalla

### ISSUE THREAD

**Issue by Doctor-N0** [valhalla/valhalla#3777]
I would like to create a distance matrix of several hundred locations. I am aware that the computation time will be correspondingly high, but this should not be a problem.

Please forgive me, if this is a basic Question, but how do I increase the Distance ([Error 154: Path distance exceeds the max distance limit](https://valhalla.readthedocs.io/en/latest/api/turn-by-turn/api-reference/)) and the Maximum Locations ([Error 150: Increase Max Locations and Path Distance](https://valhalla.readthedocs.io/en/latest/api/turn-by-turn/api-reference/))?

Thank you so much for your comments!

**Comment by dnesbitt61** [comment]
For whichever costing method you need, adjust the service_limits in the configuration JSON: e.g. max_matrix_distance and max_matrix_locations.

**Comment by Doctor-N0** [comment]
Thank you so much! That was it!

I changed in the `custom_files/valhalla.json` the lines `max_matrix_distance` and `max_matrix_locations`, and now it seems to work.

**Comment by nilsnolde** [comment]
you guys must be using a pretty old valhalla :smile: `max_matrix_locations` was deprecated for `max_matrix_location_pairs` a while ago: https://github.com/valhalla/valhalla/pull/3569
