### ISSUE TITLE
Unsigned integer underflow in graphtile.cc

### ISSUE THREAD

**Issue by PhilippVoigt** [valhalla/valhalla#3780]
We observed a bug involving an underflow of the size_t variable *ind*:
https://github.com/valhalla/valhalla/blob/d83be12170bb536a8c0c4f839d967c2748c1e63c/src/baldr/graphtile.cc#L471

It seems that *ind* can end up being 0 at the time the separator is assigned and is then reduced by 1. Afterwards we try to iterate up to *ind* which is now way larger than the length of the string:
https://github.com/valhalla/valhalla/blob/d83be12170bb536a8c0c4f839d967c2748c1e63c/src/baldr/graphtile.cc#L475

Philipp Voigt (<philipp.voigt@mercedes-benz.com>) on behalf of Mercedes-Benz Tech Innovation GmbH.
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by nilsnolde** [comment]
To make it easier to reproduce and reason over it, can you gdb into it and let us know the graphid of the tile that is causing the underflow?

**Comment by nilsnolde** [comment]
And to be verify: you’re using master with normal OSM data and no transit right?

**Comment by PhilippVoigt** [comment]
We observed this issue with the graphid 809057, which should be encoded in the path "/1/101/132.gph".

I should add that we were experimenting with different tile sizes in tilehierarchy.cc when this issue occurred:
> highway: 2.8125
> arterial: 0.703125
> local: 0.17578125

Otherwise we were using normal OSM data.

By avoiding the underflow, the tiles were otherwise successfully created and valid for routing. I'm not sure if this issue would ever occur with the default tile configuration.

**Comment by nilsnolde** [comment]
Ah ok, tbh that’s a non-issue for me. Any modification of source code and especially those sensitive constants is outside of the project’s “responsibility”. However if you come up with a more robust way we’d be happy to merge I think.

**Comment by nilsnolde** [comment]
Actually it might not be that sensitive. However, those divisors cant be divided cleanly through 180 or 90 (only tried highway). That might not be an issue though, I’m not sure.

**Comment by PhilippVoigt** [comment]
They should separate the world cleanly since they simply derived from
> 180 / 64 = 2.8125
> 180 / 256 = 0.703125
> ...

It's sure possible that this causes issues elsewhere in the project, but I believe that the bug I described exists independently, as soon as the top-level directory in the folder structure does not start with a leading '0'.

I agree that it might not be an issue as such and I'm happy to contribute a local fix to the underflow as a Pull-Request. I would just like to be sure that the function `GraphTile::FileSuffix` is the only place where file paths are assembled.

**Comment by nilsnolde** [comment]
> They should separate the world cleanly

Yeah, had a typo :man_facepalming: 

> as soon as the top-level directory in the folder structure does not start with a leading '0'.

I definitely didn't review the code as well as you did, that might very well be as that never happens with the original code.

> I would just like to be sure that the function GraphTile::FileSuffix is the only place where file paths are assembled.

I'm reasonably sure that's the only place (other than some python scripts maybe, which no one really uses). Would be very strange if not.
