### ISSUE TITLE
Building Valhalla as a submodule

### ISSUE THREAD

**Issue by yzsolt** [valhalla/valhalla#3781]
When Valhalla is built as a CMake submodule, there are some build errors:
- Boost isn't found after installed with Conan because of incorrectly set CMake module/prefix paths
- OSM PBF protoc compilation fails with a "not found correct include path" error

The first can be trivially fixed, but for the second one I haven't found the root cause (maybe related to the "`protobuf_generate_cpp` supports protos only in the same folder" limitation). I have a workaround which skips these protos if not building Mjolnir, which is enough for my use case at the moment.

**Comment by nilsnolde** [comment]
solved in the linked PR
