### ISSUE TITLE
Support Real-time traffic 

### ISSUE THREAD

**Issue by A0x01** [valhalla/valhalla#3784]
Hi valhalla Team ,
Thank you for your great work on this project , i would suggest to add an api for making real-time traffic data .Like if i have  a lot of devices that uses my "valhalla instance " will consider this devices as live traffic data 
also if you can add an intergration for other services that provide real-time traffic data for example GOOGLE .
Thank you so much

**Comment by kevinkreiser** [comment]
@A0x01 we already support real-time traffic. its not well (or at all) documented but the code is there to handle it. based on what you've written though it seems like you are asking if we are going to write the code to generate the realtime traffic from peoples gps traces. that is a huge project. we did a smaller version of it over here: https://github.com/OpenStreetMapSpeeds to do the first step of getting speed data for an edge given a trace but to do this in real time and provide the infrastructure to move the data to the router is a hell of an ask. roughly you need to:

1. have a system for collecting trace data client side and push that into an api
2. turn the basic idea from the openstreetmapspeeds repo into a running service which takes traces in real time in pushes those observations to some queriable intermediate storage
3. design a cron based processing engine that determines whether you have enough observations on a given edge in a given timespan to emit a real time speed for that edge
4. write the tiling infra that will turn those observations into real time traffic speed tiles
5. create a pubsub that pushes those tiles to your running valhalla instances
6. reconfigure your valhalla instances to listen to the pubsub and update their real time traffic tar as they get tiles over the pubsub

This is a huge amount of work, like it takes a team of people to accomplish it. if you are interested in working on it i would suggest reading up on the code and formulating a plan around each of those bullet points.

Regarding adding support for specific traffic providers, that is likely never something we are going to do here. Assuming you had done all of the bullets above then i would say that valhalla provides a data api, and if you want to integrate googles traffic feed into our apis you can write an adapter that converts their traffic data into our traffic tiles and push those to the router. This type of thing is likely always going to be out of scope for the project.
