### ISSUE TITLE
No path could be found for input!

### ISSUE THREAD

**Issue by bachephysicdun** [valhalla/valhalla#3798]
I tried to generate route given few gps locations for a bus.
Gps location that are available is crossing Italy and Switzerland  borders as shown here:

![image](https://user-images.githubusercontent.com/41142560/196895479-b5917c91-c65b-4458-a8ba-ad05934756f6.png)

Here is the json file I created to generate route:
`{"locations": [{"lat": 46.023482, "lon": 9.239947, "type": "break"}, {"lat": 46.020058, "lon": 9.235828, "type": "through"}, {"lat": 46.018871, "lon": 9.225398, "type": "through"}, {"lat": 46.036621, "lon": 9.183592, "type": "through"}, {"lat": 46.041275, "lon": 9.148016, "type": "through"}, {"lat": 46.035726, "lon": 9.117857, "type": "through"}, {"lat": 46.024533, "lon": 9.073738, "type": "through"}, {"lat": 46.018482, "lon": 9.024777, "type": "through"}, {"lat": 46.005143, "lon": 8.996332, "type": "through"}, {"lat": 45.986748, "lon": 8.937355, "type": "through"}, {"lat": 45.94347, "lon": 8.965736, "type": "through"}, {"lat": 45.878561, "lon": 8.980093, "type": "through"}, {"lat": 45.839102, "lon": 9.024399, "type": "through"}, {"lat": 45.82235, "lon": 9.050741, "type": "through"}, {"lat": 45.783676, "lon": 9.059254, "type": "through"}, {"lat": 45.78673, "lon": 9.069156, "type": "through"}, {"lat": 45.798604, "lon": 9.087033, "type": "through"}, {"lat": 45.807758, "lon": 9.088253, "type": "through"}, {"lat": 45.813237, "lon": 9.079466, "type": "through"}, {"lat": 45.809089, "lon": 9.073233, "type": "through"}, {"lat": 45.809054, "lon": 9.073272, "type": "break"}], "costing": "bus", "costing_option": {"bus": {"country_crossing_cost": 0.5, "toll_booth_penalty": 0.5}, "transit": {"use_bus": 1}}}`

I tried to add "country_crossing_cost" as well as "toll_booth_penalty" to allow the algorithm find the cross bordering routes.
However, I got error that the file was not found with error code of 442 ({'error_code': 442, 'error': 'No path could be found for input', 'status_code': 400, 'status': 'Bad Request'}).

Any idea why is this happening? Is it the bug or I badly chose costing options?

**Comment by bachephysicdun** [comment]
yes! you are right! I had to load the right graphs. Thanks!

**Comment by nilsnolde** [comment]
No worries, I think we could show a better error message that’s more comprehensible for people. You’re by far not the first to be slightly confused about it.

**Comment by kevinkreiser** [comment]
"no path could be found for input" is not the error that you get when you loaded the wrong graph unless the one you loaded was two disjoint graphs in which the origin and destination were both in separate disjoint regions but they were close enough to still be in the same tiles, a very rare case. the error that most people get when they load a wrong (or often no) graph is the one about "No suitable edges near location" or "Locations are in unconnected regions. Go check/edit the map at osm.org". We could add extra text to the messages for these common cases but then again these common cases could be red herrings in other scenarios.
