### ISSUE TITLE
Valhalla Kubernetes operator

### ISSUE THREAD

**Issue by itayankri** [valhalla/valhalla#3801]
Hi guys,

I wanted to share with the community a new tool I developed called valhalla-operator.
https://github.com/itayankri/valhalla-operator

I think that I am not the only one that struggling with deploying valhalla on Kubernetes at scale, so I developed a Kubernetes operator that automates the process. It will help you scale up your Valhalla deployments, or even migrate them to Kubernetes if you like.

I also wrote a medium article that demonstrates how to use it.
https://medium.com/@itay.ankri/deploying-valhalla-routing-engine-on-kubernetes-using-valhalla-operator-2426e79ac746

Feel free to approach me with any feedback or suggestions you have.

Enjoy!

**Comment by nilsnolde** [comment]
Sounds great, thanks for sharing! Not a Kubernetes user myself (lack of real prod env I guess), but things like these can only help the project itself.

I think the "Discussions" section ("Show & tell") is more suited for announcements like these. Also, would you mind adding your project to #3797. Not sure yet what the others think about adding a "Related projects" section, but once you're out of alpha stage I think it'd be great to reference there.

**Comment by itayankri** [comment]
@nilsnolde Fine by me. Feel free to add my project to your issue.

**Comment by pfamili081** [comment]
> Hi guys,
> 
> I wanted to share with the community a new tool I developed called valhalla-operator. https://github.com/itayankri/valhalla-operator
> 
> I think that I am not the only one that struggling with deploying valhalla on Kubernetes at scale, so I developed a Kubernetes operator that automates the process. It will help you scale up your Valhalla deployments, or even migrate them to Kubernetes if you like.
> 
> I also wrote a medium article that demonstrates how to use it. https://medium.com/@itay.ankri/deploying-valhalla-routing-engine-on-kubernetes-using-valhalla-operator-2426e79ac746
> 
> Feel free to approach me with any feedback or suggestions you have.
> 
> Enjoy!

Thank you for sharing, I am kinda new to this. If you happened to use Vertex AI to run your notebook sending request to the GKE and use it for example to do map matching, Could you share your experience? Thank you.
