### ISSUE TITLE
edge->weighted_grade of 6 after valhalla_build_config with elevation

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3805]
For all `DirectedEdge`s, I'm getting a weighted_grade of 6, even after running valhalla_build_config taking elevation_tiles into account. I ensured that I have the correct path to my local elevation_tiles directory. Any ideas?

**Comment by kungfu303** [comment]
I'm also certain that I have correct data in the elevation_tiles dir because the /height endpoint is working correctly (giving appropriate elevation gain and loss values).

**Comment by nilsnolde** [comment]
Did you rebuild the graph with elevation? /height works off the hgt tiles directly, that’s different.

**Comment by kungfu303** [comment]
I don't think I rebuilt the graph with a specific elevation tag, no. Would that just be a modification to this command?

`valhalla_build_tiles -c valhalla.json us-latest.osm.pbf`

**Comment by nilsnolde** [comment]
At the time you issued that command, did the `valhalla.json` contain the `elevation_path` pointing to downloaded elevation tiles that cover the full graph?

What we do usually is first build the tiles until the `build` stage, then run `valhalla_build_elevation -t -c valhalla.json`, then start the tile build again at the `enhance` stage, so that we can only download the elevation tiles the planet graph actually covers (saves a good chunk of mostly unneeded tiles, I'm 99% sure bathymetry isn't covered yet by the Map/TileZen tileset).

**Comment by kevinkreiser** [comment]
Bathymetry is definitely covered but it's useless for the edges in the graph of course. It is nice for visualizations of polylines that cross bodies of water though

**Comment by nilsnolde** [comment]
Oh right the ETOPO dataset, I forgot. Should've spent that 1 min to look it up.

**Comment by kungfu303** [comment]
Cool, thanks for the info @nilsnolde and @kevinkreiser!

Re: did our `valhalla.json` point to the `elevation_tiles` dir, yes it did. Those tiles were pulled before any of the stages (according to the article [here](https://gis-ops.com/valhalla-part-3-how-to-build-with-elevation-support-on-ubuntu/#2-build-the-elevation-tiles))

So you're referencing the stages of `valhalla_build_tiles` [in terms of these stages](https://github.com/valhalla/valhalla/issues/1949#issuecomment-533212539), right? Seeing the example in that post, I'm assuming that you can just run one of those phases (til build), then run the `valhalla_build_elevation` command, then start back up at enhance onwards. Giving that a try.

**Comment by nilsnolde** [comment]
> (according to the article [here](https://gis-ops.com/valhalla-part-3-how-to-build-with-elevation-support-on-ubuntu/#2-build-the-elevation-tiles))

That's a pretty old article. I wrote that when I didn't really know Valhalla too well. I'll need to update those public posts, e.g. `valhalla_build_elevation` changed from being a bash script to python and the instructions are somewhat stale.

> So you're referencing the stages of valhalla_build_tiles

`valhalla_build_tiles -h` gives all the options.

If you had the elevation tiles downloaded before, then something else went wrong. If you use our docker image, you'll get a care-free package, just set the right env vars in `docker-compose.yml`: https://github.com/gis-ops/docker-valhalla/

**Comment by kungfu303** [comment]
Ok, thank you that helps a lot. We got it to work on a small example, and just finishing up the command that starts at the `enhance` stage for the whole US. It definitely seems to be taking 18 hours on that `enhance` stage command (still running), but perhaps that's expected

**Comment by kungfu303** [comment]
Specifically, this is what it is hanging on:

`2022/10/25 20:47:13.065834 ^[[32;1m[INFO]^[[0m Adding elevation to 16367 tiles with 8 threads...`

Any thoughts on this?

**Comment by nilsnolde** [comment]
> It definitely seems to be taking 18 hours

Very little threads or HDD or both?

> Specifically, this is what it is hanging on:

What do you mean with "hanging"? That's not part of the enhance stage. No idea what your timezone (or your server's) is, but that's actually one of the fastest stages. Here for the whole world, more than 10x your data size:

```
2022/10/25 20:11:28.426691 [INFO] Adding elevation to 184546 tiles with 16 threads...
2022/10/25 20:21:09.969305 [INFO] Finished
``` 

Though that's with uncompressed elevation tiles. Are yours gz/lz4 compressed?

**Comment by kungfu303** [comment]
Right, so we have like 8 or so threads. Going to increase those since you mentioned Valhalla likes threads :)

Yeah, so by hanging what I meant is that the 'Finished' log was not printing and still has not been after many hours. I realized that it's probably because of a lack of threads and potentially RAM on my machine, especially given that this only took ~10 min on the whole world from your setup. 

And our tiles are zipped up. I'll try uncompressing them. Appreciate the help!

**Comment by kungfu303** [comment]
One other thing I meant to add - is there a param for increasing thread count? Right now my machine's using whatever nproc is by default and I'm sure that can be changed

**Comment by kevinkreiser** [comment]
@kungfu303 going beyond what your system has in terms of the output of `nproc` will not help you. if you want more parallelism you have to get more cpu cores (ie a bigger machine). and yeah you definitely want to have that data uncompressed otherwise the code will spend the bulk of the time uncompressing it, ditching it from ram cache, uncompressing it again, ditching it from ram cache again, over and over. uncompressing it upfront on disk lets the comptuer memory map the files and multiple threads can make use of the same (os-provided) ram cache over the course of the run.

**Comment by nilsnolde** [comment]
8 threads for North America is completely fine. What I was showing you was on 16 for the planet. Once you uncompress you’ll see how snappy that stage is.
