### ISSUE TITLE
GTFS support after GSoC ?

### ISSUE THREAD

**Issue by paro-** [valhalla/valhalla#3806]
Hi, according to [this](https://github.com/valhalla/valhalla/issues/3539) there was a GSoC on supporting GTFS in Valhalla, I'd like to know what came out of it, and if we can hope for the feature soon?
Thanks, best regards,
Paul

**Comment by ImreSamu** [comment]
>  I'd like to know what came out of it,

see: https://www.openstreetmap.org/user/ChrisPark/diary/399918

* https://github.com/valhalla/valhalla/pull/3665 - Merged
* https://github.com/valhalla/valhalla/pull/3669 - Merged
* https://github.com/valhalla/valhalla/pull/3700 - ....

**Comment by nilsnolde** [comment]
> if we can hope for the feature soon?

There's still a way to go. Chris with Kevin's help almost finished the ingestion and building GTFS into the graph part of the process. Also there's still a few key things needed to be solved. Then it'll be onto fixing the routing part, which is very likely quite far behind as it hasn't been touched in ages. 

I'd love to carry this over the finish line, but so far no client wanted to commit to fund the whole feature. Now that we're closer to having it done, that might change any day :crossed_fingers:

**Comment by nilsnolde** [comment]
It'll require full re-build. And likely _always_ will if it's affecting the topology (e.g. route change). Eventually (_not_ after finishing up GSoC) we want to support some features of real-time GTFS, where we'll need some support for incremental attribute changes like timetables. But then you'd need to provide/mock up an actual real-time GTFS provider.

**Comment by nilsnolde** [comment]
Yeah that's true! Transit will need a full re-build, but not the base graph, so it's quick-ish. I meant the pipeline from point 2. on and was thinking about very fast updates in the order of real-time.

**Comment by nilsnolde** [comment]
I mean it might be fast enough, but depends on what you're building it for. Use cases of our clients are more around scenario testing in a fairly limited extent, like a city or metropolitan area. But then maybe lots of transit, so rebuilding all of that could be quite expensive. But we'll see, it's not so crazy what we need to do with gtfs to add to the graph and if work a bit on the performance potentially, it might quick enough.

**Comment by kevinkreiser** [comment]
Oh and I should mention to make this faster addition of transit to the graph possible we need to pull out the `TransitBuilder::Build` step into its own phase not inside of the regular tileset build. similar to what we did for elevation and others (like historical traffic). actually i guess we could make all the steps into one binary if we really wanted but separate ones is fine as well.
