### ISSUE TITLE
Route prediction

### ISSUE THREAD

**Issue by 333bkz** [valhalla/valhalla#3813]
Can Valhalla find future route with current route and directions?

**Comment by nilsnolde** [comment]
Yes, with the right data it can. You can read more here: https://gis-ops.com/traffic-in-valhalla/ or in various issues (less concise than the article)

**Comment by kevinkreiser** [comment]
I took a different meaning from this question. I had understood it to mean does valhalla support what is called "electronic horizon". Ignore this response if I took the wrong meaning but in case I did take the right one, this feature can be described as:

Given a users current position, and whether or not there is a route loaded that they are following, what is the most likely next N kilometers of graph that they are likely to traverse.

The response to this query might be a simple N km route, but it is more likely a small "tree" data structure where the root is their current position and each branch of the tree has a probability of being taken by the driver with usually decreesing degrees of confidence the further along in time/distance you are along the tree.

Valhalla does not support an API to do this out of the box but others have built such functionality with libvalhalla. It would be cool to support this feature directly but there are a number of concerns with the design centered around the frequency at which one would call it and real-time navigation which we haven't built as top level considerations into the core library just yet. We did start doing that some 4 or 5 years ago but eventually removed it from the library when we didnt have time to fully build it.

I would like to build such support directly into the library in the future but there is no timeline for this unless someone else is  really excited about it and has time to do direct contributions with some guidance from core members.

**Comment by liuyindong** [comment]
@kevinkreiser Can you tell me the way to achieve it, I'll refer to it

**Comment by 333bkz** [comment]
sorry for the late reply,  you understand what I'm talking about, thank you for your answer

**Comment by 333bkz** [comment]
@kevinkreiser Hi, I want to get polyline by 'way_id'.
i got the 'way_id' and 'shape' by 'locate' api. but I need a full line not a line from one node to the next
What should I do？

**Comment by kevinkreiser** [comment]
We don't support that usecase but you can achieve it by using the end shape of the first response to get the next edges at the next intersection. Then you have to check those edges for matching way id and do it over and over again until you don't find that way id anymore. You'll also need to go in both directions along the way id. This could end up being a lot of requests but the strategy will work and you can do both directions in parallel for a slight boost in time to completion.

**Comment by 333bkz** [comment]
I'll try it. Thanks again
