### ISSUE TITLE
Highway, ferry and tracks tags missing in the response to route

### ISSUE THREAD

**Issue by monteirodom** [valhalla/valhalla#3815]
When requesting a route, one can ask to (_try to_) avoid **ferry**, **highways**, **tolls**.
It's a good behavior to have some information in the response, allowing to know if such segments have actually been used or not.
A tag `toll=true` is actually added to a segment on the response as [documented](https://valhalla.readthedocs.io/en/latest/api/turn-by-turn/api-reference/#trip-legs-and-maneuvers)
But contrary to the docs, `ferry=true` should also be added to a ferry segment in the response, but it is actually missing.

**Comment by nilsnolde** [comment]
Just noticing, this was solved in #3816.
