### ISSUE TITLE
about elevation

### ISSUE THREAD

**Issue by 333bkz** [valhalla/valhalla#3821]
I see that titles have elevation information, how does route return elevation information synchronously？

**Comment by 333bkz** [comment]
![8881667813373_ pic](https://user-images.githubusercontent.com/38521620/200278142-d01e432d-af4f-4aeb-b577-dfe95a1b2702.jpg)

**Comment by kevinkreiser** [comment]
`route` does not return elevation the `height` endpoint does. You have to make a second api call after you get the route to get the elevations along it. That endpoint can actually take any geometry not just a route

**Comment by 333bkz** [comment]
@kevinkreiser The ’elevation_data‘ is very large，how to compress it？
A .hgt file is about 25MB

**Comment by kevinkreiser** [comment]
It comes compressed but serving from it in this way is slow. You'll throw out all the ocean data if you can't manage the space otherwise

**Comment by 333bkz** [comment]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/38521620/200308241-625079e8-807c-41c3-b784-787bba7416f4.png">
This is China's elevation data and exclude ocean data.

**Comment by kevinkreiser** [comment]
there really arent any other options at this time, you can either keep it compressed and serve from it that way (this is much slower) or you can serve from it uncompressed but use a lot of disk. these are the two options. we have a pretty straight forward path to build the data into the graph directly but i havent started that work.

**Comment by 333bkz** [comment]
:anguished:  thank you for your answer
