### ISSUE TITLE
Reach::exact() useless maybe？

### ISSUE THREAD

**Issue by sunwei1216444523** [valhalla/valhalla#3831]
https://github.com/valhalla/valhalla/blob/5f59706b8a172f8e664835f79f1928c2de8fb837/src/loki/reach.cc#L192

Hi, 
     I am scretching my head when i see this part code. I think we need update exact reach.outbound/inbound if outbound/inbound < max_reach. But how this line work for update `done_` by run `Dijkstras.compute`. I think function `exact()` do nothing for achieving more exacter reach. 
     Hoping any voice for answer, thank!

**Comment by kevinkreiser** [comment]
The way it works is like this:

1. `reach::operator()` computes a conservative worst-case reach (it is pessamistic assuming that all turn restrictions apply), but importantly its way faster to run than the more complex and actually correct dijkstras algorithm, anyway this simple algorithm gives us a **lower bound** for reach
2. if we see the lower bound from this pessamistic but cheaper to run algorithm is less than the desired reach we run the `reach::exact` algorithm
3. this algorithm calls out to `dijkstras::compute` but  before doing so it calls `clear` on itself to reset `done_`
4. the `reach` class derives from `dijkstras` and implements the `ExpandingNode` method, this is what is called while `dijkstras` traverses the graph and how `done_` is updated to have the exact reach value (including the time and all mode restrictions etc)

**Comment by sunwei1216444523** [comment]
Thank you for answer! I got your mind.

**Comment by kevinkreiser** [comment]
:brain: indeed! :smile:
