### ISSUE TITLE
Skip circleci on draft PRs

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3834]
I'm a bit obsessed with avoiding all these unnecessary CI runs. Most of my repos (using github actions though) now are run only when it's not a draft PR anymore and some even only once approved.

Since we're a public repo, we can easily determine whether a PR is draft or not in the `needs_ci_run` script and skip executing it. I'm not sure though if it'll automatically send another request when it's only changing status from draft to non-draft (which would definitely be handy).

What'ya think?

**Comment by kevinkreiser** [comment]
I highly doubt that CI will be triggered when the pr status changes from draft to to not in which case we will need the person to push an empty commit or whatever else to trigger it. Not ideal in my opinion but not the worst.

The other bit about running only once approved seems too far to me. Seeing CI show green is like part of what gives a reviewer confidence in his approval so I would suggest against doing that. Or maybe you mean ci approval like actions has not code review/merge approval?

I am wondering what problem you're looking to solve, is it wasted cpu hours primarily? If that's the case one option is to have primary contributors opt out of ci for drafts they are making with the comment in the commit. We could also change the repo to not build fork prs until we manually allow it.

Anyway I don't feel strongly about the solutions or the problem tbh.

**Comment by nilsnolde** [comment]
> is it wasted cpu hours primarily

100% that jep.

> opt out of ci for drafts they are making with the comment in the commit

You mean the `skip ci` stuf? Sure, that exists since ages, but no one uses it and I doubt I could discipline myself (let alone others) to use it. Arranging it with drafts would be really the best option IMO. But not possible with circleci.

> We could also change the repo to not build fork prs until we manually allow it.

I'd feel a bit better with that tbh, if you don't mind. Until we're some day paying Github instead of circleci (or self-host), I'll try to remember the `skip ci` stuff instead of drafts.

**Comment by nilsnolde** [comment]
FWIW, in case anyone is interested, I created myself a git alias:

```
echo " [skip ci] " > /home/nilsnolde/dev/git_skipci_msg.txt
git config --global alias.draft 'commit -t /home/nilsnolde/dev/git_skipci_msg.txt'
```

Spins up the editor with ` [skip ci]` pre-filled. Comes with autocomplete and the commit will fail if the message wasn't edited with more info, works for me.
