### ISSUE TITLE
Current status on Transitland integration?

### ISSUE THREAD

**Issue by adamzki99** [valhalla/valhalla#3844]
Hello,

I am working on a project where we are trying to use train-transit data. From reading the documentation it should be as easy as using the `valhalla_build_transit` command in the official docker container. But the result that I am getting from running the command is as follows:

`[WARN] 500'd retrying http://transit.land/api/v1/feeds.geojson?per_page=false&api_key=MY_KEY&bbox=9.667969,55.128649,24.345703,69.549877&active_feed_version_import_level=4`

And this is even when using the provided example you get from running `valhalla_build_transit -h`.

Before trying to dig deeper into this issue I want to ask what the current status is with the Transitland integration.

I understand that there hasn't been any focus on implementing the new version of the Transitland API, but is the support for the v1 API broken? 

What is the current state of handling GTFS directly? Is there any way that Valhalla can make static data to build transit tiles?

**Comment by nilsnolde** [comment]
@adamzki99 transitland seems unsupported these days, multiple other people reported that too. There’s no plan at this point from our side to integrate again, it’s highly inconvenient to be dependent on (now) third party services. That’s why we started the GSoC project, there’s info on the status when you go through the issues. We can and will do it at some point. With funding that point could be moved closer to now.
