### ISSUE TITLE
Make shortest-ish actual shortest

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3851]
When we introduced the `shortest` option in #2555 , we took a bit of a shortcut. Using `shortest` still uses the default hierarchy limits which won't find the _actual_ shortest path for longer distances.

I only quickly reasoned over it, but I think it's not much more than simply disabling the hierarchy limits when `shortest: true`, right? That could be quite a performance drainer, so I'd add another config option for `max_distance_shortest` (or smth saying "no hierarchies", but hard to come up with a good word..). Also, only makes sense for motorized vehicles, but doesn't matter if set for bike/ped either.

Thoughts?

**Comment by kevinkreiser** [comment]
Yes. If you look at the pr description you'll see I explicitly called out that we didn't disable hierarchy pruning and yes the reason was it kills performance. We could consider making this an option but it should be an explicit separate option and one that can be disabled via server config

**Comment by nilsnolde** [comment]
Why a new option and not change current `shortest`? It's not that nasty I find. Its name is currently a bit misleading, even though we also specifically mention the limitations in the docs. Responses will be different for longer routes, but rather more like most users probably expect (without reading the docs). People running a service will notice the new config option if we make it required and will hopefully read up in the help, changelog or docs. 

I'd personally go with changing its current logic with a config option, but not too strong feelings around it. What could be a new option's name though?

**Comment by nilsnolde** [comment]
Had a chat about this and @kevinkreiser had a good idea about it:
- keep `shortest` the way it is right now and live with the sub-optimal name
- add `disable_shortcuts` as a request option, so it's a bit more universal and if turned on with `shortest` it'll return true shortest
- add config option `max_distance_no_shortcuts` (open for ideas on names) to protect the instance. Value will be similar to regular bike/ped max distance, as it's basically the same. Maybe a bit more for motorized vehicles, generally less network to cover than bike/ped.

**Comment by dnesbitt61** [comment]
note - bicycle and pedestrian already disable shortcuts.

**Comment by nilsnolde** [comment]
jep I know:) so there shortest was already shortest you're saying.. didn't think about that, true..

**Comment by kevinkreiser** [comment]
It's not just shortcuts it's hierarchy transition counting and pruning as well

**Comment by veenits123** [comment]
Hi @nilsnolde, I would like to work on this issue.
I am mind-mapping, and putting together things and will come up with a PR.

**Comment by kevinkreiser** [comment]
@veenits123 if you look right above your comment you'll see there is an issue about implementing this with someone already working on it with an open PR
