### ISSUE TITLE
Routing issue matches to wrong side with Trace attributes 

### ISSUE THREAD

**Issue by malibu** [valhalla/valhalla#3854]
Routing issue with valhalla. Please see attached image and request json

```json
{
	"shape": [{
			"lon": 54.37525,
			"lat": 24.44709
		},
		{
			"lon": 54.37475,
			"lat": 24.44793
		}
	],
	"shape_match": "map_snap",
	"costing": "auto",
	"use_timestamps": true,
	"trace_options": {
		"search_radius": 100.0,
		"breakage_distance": 20000
	},
	"filters": {
		"attributes": ["edge.id", "edge.length", "edge.way_id", "edge.end_shape_index", "shape"],
		"action": "include"
	}
}
```

![issue](https://user-images.githubusercontent.com/999234/204848070-9ec0c6a2-19ed-4056-83e7-c6aa20314168.jpg)

I have a GCC PBF. Tried with docker image and custom build. The issue persists. Openstreetmap routing has no issues. I wonder if the roundabout is the cause. The route should go around the roundabout instead of the straight line which matches the source location to the other side of the road network.

Any clues?

**Comment by malibu** [comment]
GCC is the acronym for Gulf corporation council. I meant to say the PBF has network of countries in the the middle-east. 
I doubt it's relevant though. You can also see the issue in https://valhalla1.openstreetmap.de/trace_attributes

**Comment by nilsnolde** [comment]
Ah ok thx. Jep, shouldn’t matter. Will have a quick look tmrw, may be a case for the bug scrub project for map matching..

**Comment by kevinkreiser** [comment]
i think map matching is working as designed in this case. the input shape you provided is traveling north west, that is the second point in your input is up and to the left of your first input point. the fact the first point is on the other side of a dual carriage way road makes no difference unless you tell the map matching algorithm that your input point has extremely good accuracy and that it shouldn't look at other near by edges. see by default the map matching api assumes that the input points you give it have an accuracy of 50m, which means both sides of the road are candidate matches for both points. what this means is that the accuracy of each point and telling the algorithm what that should be is very important depending on your use case.

long story short if you wanted it to go around the roundabout you could tell the map matching api that actually your points are super accurate:

```json
{
	"shape": [{
		"lon": 54.37525,
		"lat": 24.44709,
		"radius": 10
	}, {
		"lon": 54.37475,
		"lat": 24.44793
	}],
	"shape_match": "map_snap",
	"costing": "auto",
	"use_timestamps": true,
	"trace_options": {
		"search_radius": 100,
		"breakage_distance": 20000
	},
	"filters": {
		"attributes": ["edge.id", "edge.length", "edge.way_id", "edge.end_shape_index", "shape"],
		"action": "include"
	}
}
```

notice the inclusion of a very tight 10m radius on the first point there. that tells the algorithm i should only look for potential edges within a 10 meter radius. the request above returns, what i assume, is the result you were expecting:

![image](https://user-images.githubusercontent.com/697548/204931244-fc9bdd44-da66-49f7-93ed-c2e61fcb3edd.png)

**Comment by malibu** [comment]
Thanks @kevinkreiser. This is exactly what was missing. That fixes it.
For the record, is there an issue with the doc. It says 'The number of meters about this input location within which edges (roads between intersections) will be considered as candidates for said location. When correlating this location to the route network, try to only return results within this distance (meters) from this location. If there are no candidates within this distance it will return the closest candidate within reason. If this value is larger than the configured service limit it will be clamped to that limit. The default is 0 meters.'

From your response, it appears that the default is 50 m.

**Comment by kevinkreiser** [comment]
@malibu yeah improved docs could definitely help on this. the document you are refering to is for the regular route service, for the map matching services (trace_route and trace_attributes) we have other docs, and a section which kind of talks about this issue: https://github.com/valhalla/valhalla/blob/master/docs/api/map-matching/api-reference.md#get-better-results

the existing docs really only mention the top level accuracy options you can pass in (this makes sense for the polyline encoded request types). however once you switch to the array of location objects you get an actual usable way to specify accuracy at a per-point granularity.

essentially its "historical reasons". when we first made the api we only allowed polyline encoded shape (as its way more efficient to send to the service) but we overlooked that it totally knee-caps ones ability to set proper radius/accuracy thresholds  on each point. so we started allowing arrays of locations which to fix that but never updated the docs.

what i think needs to be updated in the docs is that we should encourage users to use the array of locations as input and to set the proper accuracy on each point. we should also deprecate accuracy and just use radius and explain that the behavior for map matching regarding defaults is different than that for the regular routing api.
