### ISSUE TITLE
Truck-Routing with hazardous material

### ISSUE THREAD

**Issue by Trietes** [valhalla/valhalla#3861]
I'm having some issues with truck routing. Here is an example case:

Route start: 6-8, Rombacher Hütte, Weitmar, Bochum-Mitte, Bochum, Nordrhein-Westfalen, 44795, Deutschland
Route end: Kohlenstraße, Weitmar, Bochum-Mitte, Bochum, Nordrhein-Westfalen, 44795, Deutschland

When using Valhalla and truck routing, there is no possible route found:
![grafik](https://user-images.githubusercontent.com/33934221/206509440-325f05d9-e667-4e30-bf4b-a46140f9de77.png)

After enabling hazardous materials, a route can be found:
![grafik](https://user-images.githubusercontent.com/33934221/206509718-221b3128-a37b-44f5-b7ae-2d124eca6beb.png)

The destination of my route has the tag `hazmat=destination`. I think Valhalla is not dealing properly with the hazmat tag. 

I've already checked the code in the truckcost.cc file and found this:
```
bool TruckCost::ModeSpecificAllowed(const baldr::AccessRestriction& restriction) const {
  switch (restriction.type()) {
    case AccessType::kHazmat:
      if (hazmat_ != restriction.value()) {
        return false;
      }
      break;
...
```
I guess this part of the function should only return false, if there is hazardous material on the vehicle **and** the street has an hazmat tag. If `hazmat_` is false it should never return false.

I neither know if my assumptions are correct nor how to properly fix this. Would be great if somebody could look into it.

**Comment by nilsnolde** [comment]
Huh, seems like a bug, agreed. So the road has a hazmat tag and it won't let you route on it unless you specify `hazmat: true` for your truck haha that's certainly not properly handled. Fix seems easy though. You wanna give it a go with a quick test?

**Comment by nilsnolde** [comment]
Ah no sorry, those exact lines are actually fine. It's only getting called when there actually is a hazmat restriction on an edge and then the logic checks out. Must be smth else. Can you please share the full demo URL of the route?

**Comment by Trietes** [comment]
Here is a link to my route: https://valhalla.openstreetmap.de/directions?profile=truck&wps=7.1925653%2C51.4641951%2C7.196795%2C51.4629054
You can see that a route is only found whenever 'Hazardous materials' is enabled.

I would say if `hazmat: false` is specified for the truck, it shouldn't matter if the route has any hazmat tag or not. The hazmat tag of the route should only be considered if the truck is actually carrying hazardous materials. But I'm not that deep into that code that I could really judge if it is correct or not.

**Comment by nilsnolde** [comment]
Argh, you're right after all (why am I so confused about this simple stuff..). Sure, if there's hazmat on the way and it's false in the request (default), it won't allow it. I'll quickly do it, repentance on my own stupidity;)

**Comment by Trietes** [comment]
Thanks a lot for looking into it! I really appreciate that you could check it that quick and that you are going to fix it.
