### ISSUE TITLE
slim down matrix response

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3866]
The matrix response is quite verbose and there's no option right now to slim it down. Curiously, we get a lot of matrix requests lately and got some feedback. I think the following would be good:
- remove (at least optionally) the `sources` & `targets` arrays, as they're literally just copies of the input
- quite drastic but also possible optionally: make `durations` & `distances` arrays of floats/integers instead of full objects. `to_index` & `from_index` are pretty pointless IMO, it's implicit by the position of the element in the nested array.

Big requests are suffering quite a bit, even if it could argued that the computation is so much more expensive than output JSON. I don't see the point of all this verbosity and would like to have the option to slim it down.

**Comment by kevinkreiser** [comment]
sounds good to me. my suggestion would be to use the existing top level `verbose` flag. then, when not specified and when a person does a matrix request, we can default it to `true` and the output is unchanged. however, when the person specifies it and they specify it as false, we can do as much trimming as possible to make the response smaller. the only problem with this is it means we have to keep the `verbose` flag as a `oneof` so that we can tell the difference between not provided and set to `false` explicitly. but thats a small price to pay since its already setup like that. we should just note it in the proto that it must stay a `oneof`.

**Comment by nilsnolde** [comment]
> we should just note it in the proto that it must stay a oneof.

Good point!

**Comment by veenits123** [comment]
Hi @nilsnolde, I would like to work on this issue.
I am exploring the codebase rn, parallelly I can work on this and get aware of files and directories.
It would be a good start to learn and explore as I am new to Valhalla.
Can you please assign it?
Thanks!

**Comment by nilsnolde** [comment]
Jep please go ahead. Let us know if you have issues in the PR that you’re raising.

**Comment by veenits123** [comment]
@nilsnolde, how can I recreate this Matrix response? Where can I find the data to do so?

**Comment by nilsnolde** [comment]
Not sure I understand. You're asking me to copy/paste sections of the README here for you? It's all right there. You'll need to spend a few hours trying to understand what it is you're dealing with here, i.e. the Valhalla project. We're happy to help, but we can't start at the big bang, that's not feasible for us.

**Comment by veenits123** [comment]
Is there any workshop or conference related to Valhalla, from which we can refer and understand the flow?

**Comment by veenits123** [comment]
@kevinkreiser @nilsnolde 
Need clarifications.

vee_nits123@Veenits-Air conf % **valhalla_service valhalla.json sources_to_targets '{"sources":[{"lat":41.318818,"lon":19.461336}],"targets":[{"lat":41.318818,"lon":19.461336},{"lat":41.321001,"lon":19.459598}],"costing":"pedestrian"}'**
``` 
2023/02/15 22:31:45.23358 [INFO] Tile extract successfully loaded with tile count: 235
2023/02/15 22:31:45.23425 [WARN] (stat): /data/valhalla/traffic.tar No such file or directory
2023/02/15 22:31:45.23425 [WARN] Traffic tile extract could not be loaded
2023/02/15 22:31:45.24041 [INFO] matrix::TimeDistanceMatrix

{"sources":[[{"lon":19.461336,"lat":41.318818}]],"warnings":[{"text":"path distance exceeds the max distance limit for time-dependent matrix, ignoring date_time","code":200}],"units":"kilometers","targets":[[{"lon":19.461336,"lat":41.318818},{"lon":19.459598,"lat":41.321001}]],"sources_to_targets":[[{"distance":0.000,"time":0,"to_index":0,"from_index":0},{"distance":0.286,"time":202,"to_index":1,"from_index":0}]]}
vee_nits123@Veenits-Air conf % 

```
So, our current output is coming like this:

```
{
  "sources": [
    [
      {
        "lon": 19.461336,
        "lat": 41.318818
      }
    ]
  ],
  "warnings": [
    {
      "text": "path distance exceeds the max distance limit for time-dependent matrix, ignoring date_time",
      "code": 200
    }
  ],
  "units": "kilometers",
  "targets": [
    [
      {
        "lon": 19.461336,
        "lat": 41.318818
      },
      {
        "lon": 19.459598,
        "lat": 41.321001
      }
    ]
  ],
  "sources_to_targets": [
    [
      {
        "distance": 0,
        "time": 0,
        "to_index": 0,
        "from_index": 0
      },
      {
        "distance": 0.286,
        "time": 202,
        "to_index": 1,
        "from_index": 0
      }
    ]
  ]
}
```

Do we need to slim it down to this??

```
{
  "warnings": [
    {
      "text": "path distance exceeds the max distance limit for time-dependent matrix, ignoring date_time",
      "code": 200
    }
  ],
  "units": "kilometers",
  "sources_to_targets": [
    [
      [
        0,
        0
      ],
      [
        0.286,
        202
      ]
    ]
  ]
}
```

**Comment by kevinkreiser** [comment]
this looks good to me however, i feel like it should be `time, distance` in terms of ordering the outputs. mainly because people are usually most interested in the time first and the distance secondarily (if at all?). basically most important thing first imho

**Comment by kevinkreiser** [comment]
@nilsnolde yep that is definitely a better solution. removing the need to RTFM is always important to keep in mind i agree

**Comment by veenits123** [comment]
@kevinkreiser @nilsnolde 
Need help!

vee_nits123@Veenits-MacBook-Air conf % **valhalla_service valhalla.json sources_to_targets '{"sources":[{"lat":41.318818,"lon":19.461336}],"targets":[{"lat":41.318818,"lon":19.461336},{"lat":41.321001,"lon":19.459598}],"costing":"pedestrian"}'**
```
2023/02/21 17:09:31.87496 [INFO] Tile extract successfully loaded with tile count: 235
2023/02/21 17:09:31.87550 [WARN] (stat): /data/valhalla/traffic.tar No such file or directory
2023/02/21 17:09:31.87550 [WARN] Traffic tile extract could not be loaded
2023/02/21 17:09:31.88796 [INFO] matrix::TimeDistanceMatrix

{"warnings":[{"text":"path distance exceeds the max distance limit for time-dependent matrix, ignoring date_time","code":200}],"units":"kilometers","sources_to_targets":[[{"distance":0.000,"time":0},{"distance":0.286,"time":202}]]}
vee_nits123@Veenits-MacBook-Air conf % 
```

Have trimmed down something at least :)

```json
{
    "warnings": [
        {
            "text": "path distance exceeds the max distance limit for time-dependent matrix, ignoring date_time",
            "code": 200
        }
    ],
    "units": "kilometers",
    "sources_to_targets": [
        [
            {
                "distance": 0,
                "time": 0
            },
            {
                "distance": 0.286,
                "time": 202
            }
        ]
    ]
}
```

I am unable to parse the data and collect it in "durations" and "distances" as you told i.e., 
```json
   "sources_to_targets":{
      "durations":[
         [
            0,
            202
         ]
      ],
      "distances":[
         [
            0,
            0.286
         ]
      ]
   }
```
https://github.com/valhalla/valhalla/blob/master/src/tyr/matrix_serializer.cc#L121

https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/json.h

I need to grasp these codes, as I haven't worked with `shared_ptr` before. 
Can you please help me with what should I need to learn, so that I can understand these? Any references, tutorials, or docs?
Thanks!

**Comment by nilsnolde** [comment]
I'll give you a hint: there's already pretty much the implementation we're looking for in the matrix serializer file, if you follow the code for osrm format. Not sure if it's ok to use osrm namespaced functions inside the valhalla namespace though, might want to break it out.

**Comment by veenits123** [comment]
Desired output is coming.
Can't we define the same functions again in `valhalla_serializers`? But it will be same thing twice :/

```json
{
    "warnings": [
        {
            "text": "path distance exceeds the max distance limit for time-dependent matrix, ignoring date_time",
            "code": 200
        }
    ],
    "units": "kilometers",
    "sources_to_targets": {
        "durations": [
            [
                0,
                202
            ]
        ],
        "distances": [
            [
                0,
                0.286
            ]
        ]
    }
}
```

**Comment by nilsnolde** [comment]
I'd say break those functions out into an anonymous namespace. No one else needs them other than the code in that file.

After that you'd need to make this configurable in the request via the `verbose` option, as @kevinkreiser pointed out here: https://github.com/valhalla/valhalla/issues/3866#issuecomment-1346362590.

Go into the proto definition of the `verbose` flag, change it to `oneof`, then evaluate it while serializing the response JSON and decide whether to trim down the response or not.

Then the last step is to write a quick unit test.

**Comment by nilsnolde** [comment]
Ideally you raise a PR as it make it easier to reason over the changes and give tips. It also allows to follow your progress.

**Comment by veenits123** [comment]
Thank you @nilsnolde @kevinkreiser for the assistance in making this issue reach its destination 🚀
Thanks to me :) for my first contribution in [Valhalla](https://github.com/valhalla)
I learned a lot of new things and got to know Valhalla more.
On the way to a new issue!!
