### ISSUE TITLE
Matrix output in PBF

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3867]
Also a way to "slim down" a matrix request as proposed in #3866 . But also generally good to have for protobuf consumers.

Side question: few others are missing as well in protobuf output. What else would make sense? I don't know off the top of my head which endpoints' output is included. IMO isochrones would also make sense, mostly only for general protobuf consumers, as the usual use case probably is displaying it via GeoJSON anyways.

**Comment by kevinkreiser** [comment]
my thought sicne i implemented it was that it would eventually be all of them. i want to make it possible to interact completely with the service via protobuf if a client prefers this. additionally id like it that some day we support grpc as well but we'll probably only tackle that once we are finished adding support for pbf output to all the endpoints
