### ISSUE TITLE
Expansion returning out-of-range edges

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3869]
I never really used the endpoint so far, just been testing a bit since I want to include it in a new QGIS plugin.

Seems it's including tons of completely out-of-range edges for isochrones, sprinkled all over the place:
![image](https://user-images.githubusercontent.com/25637358/207564137-a7149611-c9bc-471f-8f64-0b7459bbaac3.png)

That's even far outside the 10 mins/km buffer we have for the isotile. Will look at it when I have more time.

**Comment by nilsnolde** [comment]
> That's even far outside the 10 mins/km buffer we have for the isotile

No that can't be.. anyways, clearly a bug

**Comment by kevinkreiser** [comment]
yeah this image is blowing my mind. when i first saw you posted it i couldnt even guess what it could be. is it possible that its not the same every time? either uninitialized memory or uncleared memory?

**Comment by coderon98** [comment]
Okay, got it. There is another bug but I will create another "issue".

**Comment by nilsnolde** [comment]
You might be the first one really using this @coderon98 :) I added it with the intention to use it in another software, but didn't have the chance to release that.
