### ISSUE TITLE
`valhalla_ways_to_edges` OOM

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3871]
Tried to process TomTom Europe with historical traffic, but seems it's now sufficiently big to get OOM killed on 32 GB RAM. Previous times it's been close already, I was just dragging my feet (as so often until it's too late :sweat_smile: ). But it's easy to fix, we can just flush to disk more often than once.

**Comment by kevinkreiser** [comment]
It looks like the program is just missing a call to graphreader::clear when ::overcomitted is true

**Comment by kevinkreiser** [comment]
Unless you are running this with a tar. If that is the case then it would have to be the unordered map?

**Comment by nilsnolde** [comment]
Ah i didn’t even consider the tile dir cache. True, that should do it too. I figured it’s the map, but the tiles are definitely huge when it loads them all..
