### ISSUE TITLE
Update Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [valhalla/valhalla#3891]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Update your project on the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

Please make sure
- the list of data used is up-to-date
- the 'last updated' date is updated, as it has not been since 2016.

**Comment by nilsnolde** [comment]
@danieldegroot2 can you please provide concrete steps we'd have to take? We try to update the taginfo.json as we add stuff to our PBF parser, but of course, likely quite a few slipped through the cracks over the years, but the last edit was a few months ago in this repo, not in 2016.

That sounds to me like smth is wrong on the taginfo side? I can see an [error popping up](https://taginfo.openstreetmap.org/taginfo/projects/valhalla/error_log) when fetching our JSON in the status table, but in [Valhalla's column] it says "Ok", so I assume that error wouldn't result in taginfo discarding the entire JSON, right? I'd assume it'd just leave that erroneous entry.. Also that's a very recent addition, nothing that goes back to 2016.

Cc @gknisely

**Comment by kevinkreiser** [comment]
oh i see, we have a typo. ill cowboy fix this..

**Comment by kevinkreiser** [comment]
https://github.com/valhalla/valhalla/commit/a8a6eb679c700677a43039dc22a3b58aeb22339f

**Comment by kevinkreiser** [comment]
> the 'last updated' date is updated, as it has not been since 2016.

i think this is a red herring, i think its the last time we prd to the taginfo repo to update the place from which to pull our taginfo. we do keep it mostly up to date. otherwise there is no issue i think. @danieldegroot2 if there is somethign else you see wrong let us know!

**Comment by danieldegroot2** [comment]
https://wiki.openstreetmap.org/wiki/Taginfo/Projects

As I understand, `data_updated` is for the last time data inside the file was changed. I.e. [JOSM](https://taginfo.openstreetmap.org/projects/josm_main_presets) has it specified and updates it anytime it makes changes to the file.

`data_updated` is optional. If not specified, the HTTP header of the project file itself will be used. Therefore you could also choose to remove it. I.e. [MapComplete](https://taginfo.openstreetmap.org/projects/mapcomplete_cyclofix) doesn't have it specified.

**Comment by kevinkreiser** [comment]
:cowboy_hat_face:
