### ISSUE TITLE
To steep makes section flat?

### ISSUE THREAD

**Issue by hungerburg** [valhalla/valhalla#3897]
As I noticed in Issue #3882, very steep sections get [shown as flat](https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=11.40584707260132%2C47.24694530635573%2C11.40782117843628%2C47.24685790834034) in the altitude chart.

That may reflect in the routes chosen and durations calculated? 6:22 minutes is very sportive! There are ~90m altitude to climb.

If you care about hiking: Please overestimate timings! Too sportive clocking is one of the main annoyances with most pedestrian routers. People might miss the last bus for home, get into darkness, and so on…

Nice weather did invite a [walk today](https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=11.367378830909729%2C47.172845638207754%2C11.349788904190065%2C47.17059194697666%2C11.343619823455812%2C47.17406361275208%2C11.33588969707489%2C47.17650677088075%2C11.331737637519838%2C47.184542874116005%2C11.337112784385681%2C47.18303346293106%2C11.346178650856018%2C47.183704317645%2C11.357438564300537%2C47.18557829078686%2C11.363360881805422%2C47.1771704153164%2C11.359766721725466%2C47.16506671679181) - It took me a little bit more than 3:33h :) This one needs sac_scale 2 to render correctly (setting does not carry over the deep link.) I'd say, 5 hours pure walking time at least, not including breaks will match a lot more fitness levels.

**Comment by nilsnolde** [comment]
> very steep sections get [shown as flat](https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=11.40584707260132%2C47.24694530635573%2C11.40782117843628%2C47.24685790834034) in the altitude chart.

That looks indeed not quite right. However, do note that it's not a problem with Valhalla, likely a problem with the [Valhalla web app](https://github.com/gis-ops/valhalla-app/) (another project), which uses the [elevation profile builder](https://github.com/GIScience/Leaflet.Heightgraph), but maybe it doesn't use it correctly. Best to transfer this issue to the Valhalla web app's one.

> If you care about hiking

I'm not sure what's all needed to get a better hiking route experience tbh. Also, this is an open-source project of course, anyone can suggest/implement/PR, and I think if there's someone really wanting this, they can put in the time to make concrete suggestions. We could also expose more control over a user's preferences, e.g. we currently penalize sac_scale/grade always the same and don't take into account a user's estimate of own hiking prowess (beginner/intermediate/advanced could be a selection). Basically, the pedestrian profile is kinda lacking a good backer who has the desire to make it as good as possible, similar to the bike profile with @dnesbitt61, either through funding or own development.

And it's really not that difficult to understand what is currently going on, you might want to have a look at the function that mostly decides on ETA/costing: https://github.com/valhalla/valhalla/blob/6db32cfffe521e1080fdb9218000c3ffc3f83366/src/sif/pedestriancost.cc#L682-L729. 

If you want to put in the time to make concrete (and concise) suggestions how we can improve pedestrian to make it more useful for hiking, we'd have a base for discussion. It doesn't have to be concrete code suggestions, more logical ones: which options to expose for example (e.g. `hiking_level=beginner/intermediate/advanced`) or how much to raise ETA for certain elevation differences/grades. Once we have that, I'm sure at some point someone (likely me) will put in the time to turn that into actual code.

**Comment by nilsnolde** [comment]
I'll close here, since it's nothing with this repo.
