### ISSUE TITLE
conditional restriction does not work

### ISSUE THREAD

**Issue by xuruiray** [valhalla/valhalla#3899]
conditional restriction does not work when tag like restriction:conditional no_right_turn @ (16:30-07:00)
but use hour_on and hour_off it is work

maybe because of relation_callback func not parse restriction when tag is restriction:conditional

https://github.com/valhalla/valhalla/blob/be8d17835a2eb3effbfa8be4f9725f29e3ce504d/src/mjolnir/pbfgraphparser.cc#L2268-L2273

**Comment by gknisely** [comment]
@xuruiray These should be processed correctly via [this](https://github.com/valhalla/valhalla/blob/be8d17835a2eb3effbfa8be4f9725f29e3ce504d/src/mjolnir/pbfgraphparser.cc#L2244) and subsequent code.  Can you provided the example or link that is not working from OSM?

**Comment by xuruiray** [comment]
@gknisely oh very sorry man, I took a wrong test
so embarrassing •﹏•

**Comment by gknisely** [comment]
@xuruiray no problem...it happens.  ;-)
