### ISSUE TITLE
Fix Azure Win build

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3914]
Once this is merged, hopefully soon, we can either wait for a new release or point to the tip of master: https://github.com/microsoft/vcpkg/pull/28919

EDIT: And we should update Azure config to also run on `master` pushes.

I'm really not sure what releases mean with `vcpkg` tbh.. @mloskot isn't `vcpkg` always usable in `master`, or it's not really best practice? I could imagine that they only release for the changelog or release-obsessed downstream devs..

**Comment by mloskot** [comment]
@nilsnolde My apologies, I've been swamped. Thank you for your efforts!

>  isn't vcpkg always usable in master, or it's not really best practice?

Yes, that was the case since I started using vcpkg long time ago, but I haven't monitored vcpkg lately, so perhaps they have changed the practice.
