### ISSUE TITLE
Visualize matrix expansion & paths

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3920]
It'd be great to visualize the matrix expansion. Obviously it could be a crazy payload, but I wouldn't expect to ever debug more than 2-3 locations, everything after that is only a conceptual repetition I think. So in worst case, it's like 3 times the isochrone's expansion output for the one:many algo.

We could also hide a debug function in a trace block or so, which can trace back the chosen path (so it's not dependent on a `/expansion`  request). I'd find that invaluable to validate and compare with our other algos, which I'd love to do at some point.

**Comment by kevinkreiser** [comment]
i always wanted the expansion stuff to be available from all relevant algorithms just didnt have time to do it. as you say it can be very useful for low level debugging without stepping through the debugger
