### ISSUE TITLE
trace_attributes API does not return instructions

### ISSUE THREAD

**Issue by SamuelBrucksch** [valhalla/valhalla#3924]
Hi,

according to Map Matching API, it should be possible, to get instructions for a polyline that describes a route:
https://valhalla.github.io/valhalla/api/map-matching/api-reference/

```
You can also set directions_options to specify output units, language, and whether or not to return directions in a narrative form. Refer to the [route options](https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/#directions-options) documentation for examples.
```

So i added params, that i want to get directions in narrative form.

This is the request i send:
POST https://valhalla1.openstreetmap.de/trace_attributes
```
 {
        "encoded_polyline": "mih{|AmxjmO~IpDdVrP`DvAhD\nE_@jD_BhDqC|B}@~F}@vAY`@`Hr@rGEvF~@vLh@dLqElJaGzMwCbHiItSyDdLuDjLyFpReG~SkFjTsEnRwGxZoL~o@isA|lHqClOk^roB_GvY_N|q@uMjv@}Nhz@oY|}AcBpJiCzNw@IwBHwAl@yA|A}AdE]nDDlDpAvFtBtCtAz@jBLhB]fBhCtBbEdH~Qzb@h`BpAtKd@fEPlDWlGk@~CqAjDiBlCeDrByD~AyCb@kGzFwgBpLcG`@gObAiaAbHcl@dEsd@|CshApHmRpAcaA~GmtGjc@sa@bC_q@pDevAdK}x@`GmgEl[eIn@{Hd@qM|@_OdAmUbBiG`@iHf@iw@`FiTrA}`@rC{VhBqbAfHk@D_Mn@}ZbBca@bA_OJ}OByIM{g@}@sU}@m]sBe{@cKiPwBif@qJye@aMs~@eYsYeL{]eOe[kOiVsMyo@q`@e[gU{l@oc@q|@kq@yd@y^mMwJwWoSgNyKm@g@c{@wp@qg@ga@_XqSsrB}}AgG{Eem@{d@qHgGqZqUeJoH{rAseAe}BsgBqI_Hsy@yo@e\gVubBmoAmi@g_@aB_AqO}IiY{Q}k@y^im@i^cQ_KoTeMot@s`@aq@y\cuAuo@iZcMyh@kToLyEmSqHgy@gZkt@uVieAe[m}@sVsx@uRi`@{IssAcXkp@sKgoAgRidAqOoTgD{}@eNgq@yJgo@kJs\cFu_AqNsn@_Jy_AiN{v@gLwDm@}IsAglAiQu[yEydAuOcKmFmDqBiEaCeDgBgCcCsAiBmAuCw@cCc@aC]cEKaD@iJTeUdA}`AjA_FfA}Ex@uCr@gBjA_BjBmArGkDnCM|Ba@bB]dFaCpG{CnEwCpD}BfEiBfBq@nDs@~AQ`EDrCb@hC`@nCx@fAf@t@d@vB|AnC`CdApAjDnBpBXrCZtDeN|DiNlAiExJs[~EqOfF{MzQ{d@dE_KxC{GdC_G~@{BbEqJjLgWtIaRfIkQxKgXtJeUtCwG|BmFrBwEpEwK|Nk^hJiWvBaGbNua@|Koa@bFyTlDyO`CoLbB_K~AmKlCkSfEg`@nB{Vn@mKj@wKf@oN^qL\oRFkVGaW_@e]gAm\qAiWgCsb@oCoa@kCo`@aB}ZyAu\u@_Yk@qWtCeJx@}BhAsAzBeAxE{AdLxF`F~EtGvJ`Wjc@~Sz]vEtGv@n@v@n@jDv@tEhI^n@`P`XtElH`AhBrGxIlDrFn@jA|@fBdQdZfJgPhAyBrRq]rBmDz@sAp@oAvC}E",
        "shape_match": "edge_walk",
        "costing": "auto",
        "directions_options": {"units": "km",  "directions_type": "instructions"},
        "directions_type": "instructions"
}
```

I tried both setting `"directions_type": "instructions"` inside `directions_options` and outside, but i did not get any instructions in the response. Is there anything I'm doing wrongly?

**Comment by SamuelBrucksch** [comment]
Ok looks like `trace_route` returns instructions. This was not very clear from the documentation.

**Comment by nilsnolde** [comment]
> when i want to get instructions AND speed limits and other properties from the route, that i have to call trace_route and then trace_attributes?

Jep correct. It is a bit confusing in the docs, agreed. Please feel free to PR any improvements you might have.

And another fail in the docs (or code?) is that `directions_type` is not nested inside `directions_options` in the code, it has to be top-level while the docs suggest it should be nested. Not sure what was intended here, I think nested makes more sense. I didn't realize that `narrative` was deprecated!

Docs for such a huge (and in many places shared) HTTP API are really a lot of work and hard to do completely correct in the first place and maintain over time.

**Comment by SamuelBrucksch** [comment]
Thanks for your feedback!
