### ISSUE TITLE
Routing through partially closed military training area

### ISSUE THREAD

**Issue by chrstnbwnkl** [valhalla/valhalla#3939]
Just stumbled across this behavior accidentally: when trying to find a route from one side of a military training area to the other, Valhalla suggests to ride through it directly: https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=51.8214%2C8.7176%3B51.7834%2C8.8150#map=13/51.8032/8.7659

The road it suggests to take is tagged as `bicycle:conditional=no @ military schedule`: https://www.openstreetmap.org/way/65157849

**Comment by gknisely** [comment]
Hi @chrstnbwnkl At this time valhalla only supports conditionals that utilize date/time, height, weight, etc restrictions.  We do not process User or group restrictions yet.  Ref https://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Comment by nilsnolde** [comment]
Hm, can you elaborate a bit @gknisely ? Not sure I understand "group restrictions". This specific one seems like an easy case (unless we'd have a `military` costing option), as it's just a hard `no`, right?

**Comment by gknisely** [comment]
@nilsnolde we would have to support the following:  _**User group**: The restriction relates to a specific user group, e.g. doctor, disabled, emergency, female._  So no we don't support this at all.

**Comment by nilsnolde** [comment]
Huh, would `military` use fall under that `User group` category? Anyways, this particular case seems very edge, 44 ways globally. Sorry @chrstnbwnkl ;) Maybe the OSM data should change to smth less rare and still applicable?

**Comment by kevinkreiser** [comment]
if it's `no` with some weirdo exception, should we assume `no` even if we don't understand the exception? it would be interesting to see taginfo for what all exceptions exist. would be hilarious if it did what the wiki said and had exceptions like female or senior citizen. only old bike riders can ride through this area haha super edge casey
