### ISSUE TITLE
Handle destonly ways/edges around ferry terminals

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3942]
ref https://github.com/valhalla/valhalla/issues/3941#issuecomment-1407713742.

Even though it's more of a mapping error, it seems it's quite pervasively done when mapping access to/from ferries terminals. Our client did a quick analysis, and around 400 ferry terminals world-wide have `access=customers/private/destination` tagged on the land-side connection edge, so they'd not really be considered by the bidir A* on the first pass, leading to horrendously long detours.

Maybe we could think about handling this case better in whatever way? I know it's a slippery slope to start handling mapping errors, but in this case IMO it could make sense.

There's a few approaches that come to my mind, but only viable one I think. Ideally it's done on the data, not the request, level, e.g. when reclassifying ferry edges we could "untag" `access` for all the path edges we find whenever the ferry connection edge is `dest_only`, and we'd stop untagging as soon as the next expanded edge is not `dest_only` anymore (similar stuff to what we're doing with `not_thru` when enhancing the graph). That way we could make sure to not open up legit `dest_only` along the way to the next `primary` road. 

That still leaves all the ferry terminals kinda "unsupported" where the connection edge is not treated as `dest_only` but only the edge further "inward". We wouldn't catch that, but gotta stop at some point supporting non-sense;)

We can discuss briefly tmrw..

**Comment by kevinkreiser** [comment]
this was the same thought I had. we already remove destonly when reclassifying (Kristen and I did that a while ago). to me we are doing this reclassification exactly to make sure the ferry stays connected so it doesn't make sense to waste that work by keeping it closed unless the tagging isn't likely

**Comment by kevinkreiser** [comment]
(sorry about the close and reopen, accidently tapped the wrong button)

**Comment by nilsnolde** [comment]
ok cool. should we then not care if the connection is dest_only or not and simply remove dest_only from all edges which are part of the final upclassed paths for all modes? 

on the one hand there could be legit dest_only which we don't want to touch but on the other hand we'd miss out on some cases where only the connection edge is not weirdly tagged but all others in the area are.

**Comment by kevinkreiser** [comment]
@nilsnolde i really thought we did that already in #1905

**Comment by nilsnolde** [comment]
Some of it. We also have to unset the dest_only in the edge data itself, not only include them in the reclassification expansion. Otherwise the bidir A* will still see the destonly property on those edges and not include them in the first pass. Also there's still a penalty of 5 mins for those edge, so in the end it'll upclass often shitty service ways instead of the normal ferry access ways.

So, in summary, I think we should do:
- remove the destonly property from the ways if they were the ones chosen to be upclassed (accepting to also remove valid destonly properties, not these irrelevant ones)
- inherently remove the extra penalty for destonly edges when reclassifying which was introduced with #1905

I guess that PR was more focussing on even getting _any_ connection while still avoiding destonly ways. What I'm proposing you mentioned in the issue #1889 but the PR didn't really do what you suggested IMO.

**Comment by nilsnolde** [comment]
> should we then not care if the connection is dest_only or not, and simply remove dest_only from all edges which are part of the final upclassed paths for all modes?

That's still a valid question then. FWIW, I'd still favor the latter option.

**Comment by nilsnolde** [comment]
Actually I guess #1889 was a case where the connection way didn't have destonly but some (or all) of the others in the area. Then the PR trying to solve that worked out. But the example I gave has that: the connection way is destonly. That's why it fails I think.

**Comment by kevinkreiser** [comment]
yeah it was a long time ago I totally misremebered it. we might want to do the fallback thing though only remove dest only when we can't find another way? whatever we do it might be a good idea to qa the results, ie spit out the geoms of the ferry reclassification in geojson so we can visually review some otherwise we could get some strange stuff potentially? anyway just a thought to avoid potential craziness

**Comment by nilsnolde** [comment]
Yeah, it'd be good to optionally see the path(s) it upclasses for ferries. I'll include that, pretty sure I'll get to this in the next weeks.

**Comment by nilsnolde** [comment]
> we might want to do the fallback thing though only remove dest only when we can't find another way?

Hm, then we'd pretty sure get those shitty service roads upclassed as well as they can be cheaper when they're not destonly. I should've waited with updating OSM on the example.. Anyways, will do a gurka test with what I mean, also quickly done, discussed and decided I think.

**Comment by nilsnolde** [comment]
Agreed offline to do it the way of only removing/disregarding destonly of edges _if_ the connection edge also is destonly.

**Comment by andrewharvey** [comment]
Sorry to comment on an old thread but it looks like we've encountered this at https://community.openstreetmap.org/t/queenscliff-sorrento-ferry/145618/6 however the fix from #4118 may not be working here since the `access=customers` way doesn't directly touch the ferry route way, there is a short way without access allowing existing the ferry... Do we think valhalla should address this?

**Comment by chrstnbwnkl** [comment]
I think this is a mapping error. Logically, if all edges that lead to the connection edge are customers only, then by extension, the connection edge has to be as well, or am I misunderstanding something?

**Comment by andrewharvey** [comment]
> I think this is a mapping error. Logically, if all edges that lead to the connection edge are customers only, then by extension, the connection edge has to be as well, or am I misunderstanding something?

Right so you're saying that this one should also be `access=customers`, since the queue up lanes 1-8 are `access=customers` so to reach that way you either need to travel via the queue up lanes (hence be a customer) or be exiting the ferry, in which case you were a customer of the ferry.

<img width="905" height="664" alt="Image" src="https://github.com/user-attachments/assets/17f7621d-31be-464e-89d5-f31eef0bf8dd" />

**Comment by chrstnbwnkl** [comment]
Yes, exactly.
