### ISSUE TITLE
memory leak, valhalla_servic killed automaticaly 

### ISSUE THREAD

**Issue by sagarjsr** [valhalla/valhalla#3946]
I have set up the Valhalla server with a source build on a virtual instance of `8 core and 16 Gb Ram` for Planet.osm.pbf
I used use get killed automatically after 1000*1000 cost matrics.
need to know the reason why it is getting killed automatically

![image](https://user-images.githubusercontent.com/36634354/216317025-005244c9-4ea2-4400-9588-aba054552946.png)

I really appreciate any help you can provide.

**Comment by nilsnolde** [comment]
1000x1000 matrix is the reason why it gets killed, it's OOM'ing. Valhalla's matrix code is fairly memory hungry, at least the CostMatrix (and that's the only one you can use for this really..). There's no good rule of thumb how much memory this would require, it all depends on the underlying road network. It can go pretty crazy, like dozens of GB RAM if the locations are far enough apart in dense networks.

Memory leak is surely not the right buzz word here.

**Comment by nilsnolde** [comment]
But actually good to hear the planet still builds easily on 16 GB RAM. May I ask how long it took to build the whole graph?

**Comment by sagarjsr** [comment]
@nilsnolde it 48hr to build Planet osrm valhalla from source code build, `8 core  16 Gb RAM and  220 Gb or storage`
