### ISSUE TITLE
docker image fails building for arm64

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#3950]
Was raised on the osm dev list (and is more a hunch as of now, but makes sense I think):

It might be not be possible to build our image on e.g. Apple Silicon. The error is caused by the name of the python bindings when we try to `strip` it:

https://github.com/valhalla/valhalla/blob/3fac9705794f902dceb9b031d04c2f4fa9ada109/Dockerfile#L45

I'd guess it builds actually `python_valhalla.cpython-310-darwin.so` or so.

**Comment by ImreSamu** [comment]
> I'd guess it builds actually python_valhalla.cpython-310-darwin.so or so.

as I see : 
* `valhalla/python_valhalla.cpython-310-aarch64-linux-gnu.so`
* `valhalla/python_valhalla.cpython-310-x86_64-linux-gnu.so`

-----------------

side note:  

in my (intel) machine the "qemu + Buildx" has been crashed : 
command:  `docker buildx build --pull --progress=plain --platform linux/arm64 -t valhalla-arm64 .  ` 

error:
```
....
#16 10269.6 make[2]: *** [test/CMakeFiles/utrecht_tiles.dir/build.make:77: test/data/utrecht_tiles/traffic.tar] Segmentation fault (core dumped)
#16 10269.6 make[1]: *** [CMakeFiles/Makefile2:6126: test/CMakeFiles/utrecht_tiles.dir/all] Error 2
#16 10269.6 make[1]: *** Waiting for unfinished jobs....
#16 10375.5 [ 93%] Linking CXX shared module valhalla/python_valhalla.cpython-310-aarch64-linux-gnu.so
#16 10390.9 [ 93%] Built target python_valhalla
#16 10831.5 [ 96%] Linking CXX static library libvalhalla_test.a
#16 10835.1 [ 96%] Built target valhalla_test
#16 10835.2 make: *** [Makefile:156: all] Error 2

```

**Comment by nilsnolde** [comment]
Yeah ok, then we can’t cross-compile with the bindings enabled, guess that’s one level too deep for QEMU. Thanks for trying!

**Comment by nilsnolde** [comment]
Ah no, it’s the traffic tiles? Huh.. That sounds more serious actually. Then we can’t cross compile with tests enabled;)

**Comment by iwpnd** [comment]
Any chance you found a way to create an arm64 image for valhalla @nilsnolde?

**Comment by nilsnolde** [comment]
I don't have much interest in a ARM image tbh.. IMHO it should come from the community.

**Comment by iwpnd** [comment]
fair enough. 🙏

**Comment by homtec** [comment]
Wouldn't it make sense to fix line 45 with
`RUN strip /usr/lib/python3/dist-packages/valhalla/python_valhalla.cpython-310-*-linux-gnu.so
`
Works for me building the image locally on Apple Silicon.

**Comment by nilsnolde** [comment]
Probably without „linux“ in there, but yeah, feel free to PR:)
