### ISSUE TITLE
Update url for just_gtfs submodule

### ISSUE THREAD

**Issue by mesozoic-drones** [valhalla/valhalla#3994]
Hello! I am the maintainer of just_gtfs library for reading & writing of GTFS feeds. This library is used as a submodule in Valhalla.

@nilsnolde recently opened 2 issues in mapsme/just_gtfs repo:
https://github.com/mapsme/just_gtfs/issues/17
https://github.com/mapsme/just_gtfs/issues/19

The problem is that just_gtfs is the part of the MAPS.ME project which is not supported anymore. I can't push to master of mapsme/just_gtfs (and nobody of the original MAPS.ME team can).

But I want to improve and develop just_gtfs library so I propose to use my personal (and historically original) version:
https://github.com/mesozoic-drones/just_gtfs

**Let's update url for just_gtfs in Valhalla's submodules!**

P.S.
I've fixed the first bug found by @nilsnolde and this fix is already in master covered by test.

**Comment by nilsnolde** [comment]
Great thanks. I accepted your invitation to the repo, thanks. I can try to help a bit here and there.

I'm kinda confused about the whole maps.me history :sweat_smile: 

Maybe you want to remove that fork and set up a real repository for that? If maps.me abandoned the project, IMHO a fresh start could be better? Also makes it more obvious for other people who want to use it.

**Comment by kevinkreiser** [comment]
another option i would offer would be to even move the project into the valhalla organization as its own repo and then add @mesozoic-drones to the valhalla organization if that is something she would be interested in (for higher visibility maybe)?

but yeah in your own user organization as its own un-forked repo is great as well if that is more comfortable!

**Comment by nilsnolde** [comment]
> I created a request to github team via [chat bot](https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks) and now "fork" relation is completely removed.

Great! Didn't know that was a thing:)

Issues are disabled by default, just as a reminder:)

**Comment by mesozoic-drones** [comment]
Thanks, I enabled issues & discussions.
