### ISSUE TITLE
Get OSM Way IDs via routing API

### ISSUE THREAD

**Issue by danvk** [valhalla/valhalla#4]
Valhalla provides the shape of the path that it routes you along:

    curl 'https://valhalla.mapzen.com/route?json=%7B%22locations%22%3A%5B%7B%22lat%22%3A42.358528%2C%22lon%22%3A-83.271400%7D%2C%7B%22lat%22%3A42.996613%2C%22lon%22%3A-78.749855%7D%5D%2C%22costing%22%3A%22auto%22%7D&api_key=valhalla-...'

    {
      "trip": {
       ...
      "units": "kilometers",
      "legs": [
        {
          "shape": "_ojxoApmny}CnaB{AWik@]}_@U{j@Wy`@e@mi@G{`@Ma]Wik@?mU?sFUoSOwXGsFMcGqCupGe@mU{@sPu@kLiBaRm@sFsBqQiBuOkAmKu@yLe@sP?_JFoI\\gMt@{LhCiWnC{UrAuO\\oINoIFoI?cPWkj@qB_kG?_JOo]aBiqD?{A?{A]mhAGqGe@iaAGcFe@ceA?..."
        }
      ]
    }

But what I'd really like is the IDs for the OSM ways that comprise this shape. Is there a way to get these out? If not, consider this a feature request.

(I wasn't sure which repo to file this on—feel free to close and suggest one.)

**Comment by dnesbitt61** [comment]
We do not expose these currently. One concern is that the path may not follow an entire wayid - it can turn onto a way or off of a way without traversing the entire way. We will consider an optional return of a list of way Ids. Would you also need to know indexes into the list of way Ids for each maneuver?

**Comment by danvk** [comment]
That's a good point. Having the index into where the route starts/stops in each way would be nice, but by no means necessary. Just the list of way IDs would be great.

**Comment by dnesbitt61** [comment]
Actually, we cannot return wayIds in many cases. We aggregate/combine ways to create shortcut edges and do not retain way Ids for these cases. What is your use case?

**Comment by danvk** [comment]
I'm synthesizing traffic data and would like to get vehicle counts along sections of road. Ways seem like a natural segmenting of the major highways.

So I have a collection of (Origin, Destination) pairs. I run each through the Valhalla API to get a plausible route. I currently intersect the resulting shape with a collection of ways I'm interested in, but this also produces artifacts at intersections:

![screen shot 2016-03-29 at 10 25 24 am](https://cloud.githubusercontent.com/assets/98301/14111397/91657bf4-f598-11e5-8b54-65d0cfae7940.png)

Clearly the route goes south, but it intersects multiple ways at this intersection. I assume that at some point internally, Valhalla knows which ways are being used. My analysis would be simpler if I could get those out directly, rather than by trying to reconstruct them from the shape.

**Comment by dnesbitt61** [comment]
Are you running Valhalla locally or via Mapzen Turn-by-Turn API? If running locally you should be able to generate way Ids if you restrict the route to stay on the local hierarchy level and instrument thor/trippathbuilder to capture way Ids on the path and output them to your application. You can send an email to valhalla@mapzen.com or to me: dave@mapzen.com for more info. I hesitate to add this to the API at this time - since restricting to local hierarchy impacts performance if someone sends in long routes.

**Comment by danvk** [comment]
I was using the `https://valhalla.mapzen.com/route` endpoint, but I'm open to trying to run it locally. I'll follow up with you directly if I go down that path and run into issues (or get it working!).

We work next door, btw. Say hi to Dave Riordan for me! :)

**Comment by dnesbitt61** [comment]
The Valhalla team is actually in Lancaster, PA though we do visit the Mapzen NYC office a bit.

**Comment by danvk** [comment]
Would it be simpler to get node IDs for the route, rather than the IDs of the ways? That would also be entirely sufficient for us.

**Comment by dnesbitt61** [comment]
We do not store OSM node Ids at all within Valhalla data. One could modify a local instance of Valhalla to return wayIds along a route, but you would also have to restrict/prevent the use of shortcut edges which do not retain any way Id association (a shortcut edge may span multipl wayIds). We do not have plans at this time to expose this via the Mapzen route API.
