### ISSUE TITLE
Tile building takes forever with elevations

### ISSUE THREAD

**Issue by xlqian** [valhalla/valhalla#4013]
Hi, 

I have been desperately trying to build tiles for France **with elevations** without being able to finalise the building. The building always hung at the elevation stage and it never ended. 

However when building with a smaller OSM like Switzerland, everything worked like a charm. 

I tried  with `valhalla/valhalla:run-3.3.0`, `valhalla/valhalla:run-3.2.1`, `valhalla/valhalla:run-latest`, they all have the same behavior.

Before I dive into the codes, I just want to make sure whether this issue has been known, and do you guys have any idea what the cause could be? 

Regards

**Comment by nilsnolde** [comment]
Hm, that shouldn't be the case, but not 100% sure where that's coming from.. Upfront: the public instance is built with elevation tiles, globally it takes 10 mins for the builder to add elevation.

So you already have the tiles downloaded locally I guess? What's your valhalla.json and what did you run exactly?

**Comment by nilsnolde** [comment]
Also you'll need to raise the container's ulimits, since it opens tons of files. There's command line flags for docker for that (or configs in docker-compose.yml).

**Comment by xlqian** [comment]
yep.. it seems quite weird to me too... I have been using the default config by using `valhalla_build_config` without changing a single letter... and the elevations are downloaded by `valhalla_build_elevation` and a geojson... I'm gonna try with another large OSM, maybe the problem lies in the osm...

**Comment by xlqian** [comment]
> Also you'll need to raise the container's ulimits, since it opens tons of files. There's command line flags for docker for that (or configs in docker-compose.yml). 

YES! that's a good point!!! thank you!!

**Comment by nilsnolde** [comment]
What are the logs of the container? Just stopping at the elevation stage and not continuing?

**Comment by xlqian** [comment]
hmmm, I think there IS something weird... I tried to build the tiles without docker, but it still hung at the elevation stage... I'm gonna dive into the code to see if I can find anything fishy

**Comment by xlqian** [comment]
(It came to my mind that I built whole europe with `valhalla/valhalla:run-3.1.4` successfully... so probably it's not docker :shrug:  )

**Comment by nilsnolde** [comment]
Well one thing: do you have NVMe disks or HDD or? This really works best with super fast disks, not sure if HDD would pretty much result in this.

**Comment by nilsnolde** [comment]
Lastly I'd also check the output of the elevation downloader, i.e. the tiles. They should all have 25 MB IIRC. Not sure anyone ever really exercised the `--geojson` option and it's only loosely covered by tests;)

> with 3.1.4 but not with 3.2.1

with elevation you mean, or without? What's your machine specs?

**Comment by nilsnolde** [comment]
Oh, and can you see the processor spinning? And did you decompress the gzipped tiles? Sorry for the unstructured questions.. Lots of moving parts:)

**Comment by xlqian** [comment]
> They should all have 25 MB IIRC

Hmm, seems not at all :grin: 
```
9849678 8.1M -rw-r--r--  1 x x 8.1M Mar  7 04:49 N03W052.hgt.gz
9849651  11M -rw-r--r--  1 x x  11M Mar  7 04:48 N03W053.hgt.gz
9849659  11M -rw-r--r--  1 x x  11M Mar  7 04:49 N03W054.hgt.gz
9849697  11M -rw-r--r--  1 x x  11M Mar  7 04:49 N03W055.hgt.gz
```

> with elevation you mean, or without?

Yes, we built our tiles always with elevation.

> What's your machine specs?

My laptop: Dell XPS 15 
Ubuntu 22.04
SSD
Intel Core i7

>  can you see the processor spinning or it's really just hanging there?

~12% all the time during 10 hours, :sob: 

>  did you decompress the gzipped tiles?

Do you mean the elevation tiles? if so, no...

> Sorry for the unstructured questions..

I appreciate your patience a lot:)

**Comment by kevinkreiser** [comment]
the compressed ones arent really useful for any reasonable use case (either tile building or running the service). the reason i compressed them is so that downloading them takes less time. uncompressed they are something like 1.6TB but compressed they are something like 300GB which is much better in terms of download. for all practical purposes decompress them before use.

**Comment by nilsnolde** [comment]
Thanks good to know/remember. 

It does read them though right? Maybe we should remove support for reading gzipped tiles? Or at least warn? This tripped me a few times when debugging issues for others.

**Comment by kevinkreiser** [comment]
yeah it definitely works. i would rather not remove support, but instead add a warning that we need to decompress (when we see gzipped tiles in there).

**Comment by xlqian** [comment]
here we go!  I decompressed them and that works! good to know!
