### ISSUE TITLE
Update OSMPBF repo

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4021]
We could (try to) update our OSM proto sub repo. Of course there hasn't been much going on since you included it, but one thing has been added (7 years ago :smile: ): `syntax=proto2`.

**Comment by kevinkreiser** [comment]
well that will at least remove a warning during build

**Comment by nilsnolde** [comment]
Hm, nuked the `build` folder, just to be sure, but still fails when linking with e.g.

```
[build] [220/220 100% :: 15.604] Linking CXX executable valhalla_build_tiles
[build] FAILED: valhalla_build_tiles 
[build] : && ccache /usr/bin/g++ -fdiagnostics-color=auto  -g  CMakeFiles/valhalla_build_tiles.dir/src/mjolnir/valhalla_build_tiles.cc.o -o valhalla_build_tiles  -Wl,-rpath,/usr/local/lib:  src/libvalhalla.a  /usr/lib/libprotobuf-lite.so  /usr/lib/libcurl.so  /usr/lib/libz.so  /usr/local/lib/libprime_server.so  /usr/lib/libspatialite.so  /usr/lib/libsqlite3.so  /usr/lib/libluajit-5.1.so  -lm && :
[build] /usr/bin/ld: src/libvalhalla.a(fileformat.pb.cc.o): in function `OSMPBF::Blob::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
[build] /home/nilsnolde/dev/cpp/valhalla/build/src/valhalla/proto/fileformat.pb.cc:353: undefined reference to `google::protobuf::internal::UnknownFieldParse(unsigned long, google::protobuf::UnknownFieldSet*, char const*, google::protobuf::internal::ParseContext*)'
[build] /usr/bin/ld: src/libvalhalla.a(fileformat.pb.cc.o): in function `OSMPBF::Blob::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const':
```

How can protoc generate stuff the same protobuf library doesn't have?

**Comment by kevinkreiser** [comment]
its possible you use one protoc but link to a different libprotobuf since protoc will be in  your PATH somewhere and libprotobuf will be in your LD_LIBRARY_PATH (or found via other means pkg-config) in cmake. have to look into what the build system is finding and using to be sure

**Comment by nilsnolde** [comment]
Sorry, should've said that it's both v3.21.12. Of course it worked before, it just broke when I upgrade OSMPBF and not sure how that can be. Let's see what CI says.
