### ISSUE TITLE
preferred_side parameter for locations

### ISSUE THREAD

**Issue by Trietes** [valhalla/valhalla#4028]
I'm having some issues when using the preferred_side paramter for locations. It seems like it is doing exactly the opposite of what I would expect. The documentation says: "In Germany (driving on the right side of the road), passing a value of same will only allow you to leave from or arrive at a location such that the location will be on your right."

I came up with following minimal example. When not speicifing any prefered side it behaves as expected:

`localhost:8002/route?json={"locations":[{"lat":51.55044428412877,"lon":7.513110819661061},{"lat":51.55571992309335,"lon":7.5120135619991135}],"costing":"auto","units":"meter","directions_type":"none"}
`

results in 

`{"trip":{"locations":[{"type":"break","lat":51.550444,"lon":7.51311,"side_of_street":"right","original_index":0},{"type":"break","lat":51.555719,"lon":7.512013,"side_of_street":"right","original_index":1}],"legs":[{"summary":{"has_time_restrictions":false,"has_toll":false,"has_highway":false,"has_ferry":false,"min_lat":51.550561,"min_lon":7.511867,"max_lat":51.55567,"max_lon":7.513797,"time":70.902,"length":0.608,"cost":96.513},"shape":"aukiaBuwpiMy@{BgCoGaDyG{D}FkF{EiJcFuJuDkGkAqCIU?iBEqF\\uFfAoNlCcP~CaZzFoKlB_KlDcH~C{NpJ{J|F{MjE{NzD}SbH_Bp@kBr@kFfCuFlC{D|BsJ~FyLzH}HzFiCxB"}],"summary":{"has_time_restrictions":false,"has_toll":false,"has_highway":false,"has_ferry":false,"min_lat":51.550561,"min_lon":7.511867,"max_lat":51.55567,"max_lon":7.513797,"time":70.902,"length":0.608,"cost":96.513},"status_message":"Found route between points","status":0,"units":"kilometers","language":"en-US"}}`

It can be seen that both locations are approached from the right side. In the next example I'm now specifying a prefered side for the second location: 

`localhost:8002/route?json={"locations":[{"lat":51.55044428412877,"lon":7.513110819661061},{"lat":51.55571992309335,"lon":7.5120135619991135, "preferred_side":"same"}],"costing":"auto","units":"meter","directions_type":"none"}`

The Valhalla answer is:
`
{"trip":{"locations":[{"type":"break","lat":51.550444,"lon":7.51311,"side_of_street":"right","original_index":0},{"type":"break","lat":51.555719,"lon":7.512013,"side_of_street":"left","original_index":1}],"legs":[{"summary":{"has_time_restrictions":false,"has_toll":false,"has_highway":false,"has_ferry":false,"min_lat":51.550561,"min_lon":7.510794,"max_lat":51.556923,"max_lon":7.513797,"time":101.313,"length":0.935,"cost":161.104},"shape":"aukiaBuwpiMy@{BgCoGaDyG{D}FkF{EiJcFuJuDkGkAqCIU?iBEqF\\uFfAoNlCcP~CaZzFoKlB_KlDcH~C{NpJ{J|F{MjE{NzD}SbH_Bp@kBr@kFfCuFlC{D|BsJ~FyLzH}HzFuL`Ke\\fYaFhEmGzFqBfBcCReAX_AR}@HwBBuEDFhA\\dIxEyBzBqAlDcCjBuCpBgBlG{F`FiEd\\gYjHgG"}],"summary":{"has_time_restrictions":false,"has_toll":false,"has_highway":false,"has_ferry":false,"min_lat":51.550561,"min_lon":7.510794,"max_lat":51.556923,"max_lon":7.513797,"time":101.313,"length":0.935,"cost":161.104},"status_message":"Found route between points","status":0,"units":"kilometers","language":"en-US"}}`

It can be seen that after specifing the second location with `prefered_side : same` the route will approach the waypoint from the left side. According to the documentation I would've expect it to approach from the right side.

I've used the latest gis-ops Docker Image for the routing.

**Comment by Trietes** [comment]
I've not set any environment variables of the docker image except tile_urls. According to the gisops docker there shouldn't been any adim database build:

- build_admins: True builds the admin db needed for things like border-crossing penalties and detailed routing responses. Force will do the same, but first delete the existing db. Default False.

**Comment by kevinkreiser** [comment]
iirc (i could be wrong) if you dont have admins we default to left hand driving, if that is the case it might explain what you are seeing. imho we should fix that since most places (by land mass) are right hand driving anyway. if we go by population though japan and india tip the scales back a little bit toward left hand driving.. hard to pick a good default here..

**Comment by nilsnolde** [comment]
> True builds the admin db needed for things like border-crossing penalties and detailed routing responses

Yeah we should change that description probably. Although I don't consider comments in docker-compose.yml authoritative documentation;) 

There's quite a few problems when not using an admin DB, apart from what Kevin mentioned, there's also the problem that it'll navigate poorly in roundabouts. I didn't even know we're defaulting to left-side driving until today :)

Regardless, it'd be nice if we'd have a S3 bucket or so for the tz & admin DBs. Should be hosted with AWS open data and pushed to from our master CI builds:)

**Comment by Trietes** [comment]
Its working for me now. Just in case somebody else faces the same issue: Just building for a region of a country like north rhine westphalia in Germany won't work. It has to be build for the complete country.

**Comment by nilsnolde** [comment]
Yeah right, at least one country so we get all the ways that are referred to by the country relation.

**Comment by nilsnolde** [comment]
I'll close, feel free to re-open if anything is still not working/unclear.
