### ISSUE TITLE
Make Valhalla's latest docker image public

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4039]
Currently no one can use the new Docker registry image, it's private apparently (just wanted to base our image on the new one, but couldn't). That's Github's default and we'd need to change the visibility manually. I don't have permissions for that, can someone do with full admin do it?

Might as well remove the `test_tag` image.

**Comment by kevinkreiser** [comment]
i think i did this. the UI is very unintuitive! also i cannot figure out how to delete the test_tag..

**Comment by nilsnolde** [comment]
Jep, that worked. We can delete it in the next session, it it pretty unintuitive..
