### ISSUE TITLE
skip CI runs is broken

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4061]
```
Traceback (most recent call last):
  File "/Users/distiller/project/./scripts/needs_ci_run", line 95, in <module>
    status, last_pr_gitsha = last_build_successful()
  File "/Users/distiller/project/./scripts/needs_ci_run", line 51, in last_build_successful
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://circleci.com/api/v1.1/project/github/valhalla/valhalla/tree/nn-gtfs-multi-feed-tests?circle-token=****************************************&shallow=true&limit=6
```

Don't see how that can be unauthorized.. It's all coming from within CircleCI right? Or is the `CIRCLE_API_TOKEN` smth you put in some circleci settings?

https://github.com/valhalla/valhalla/blob/435631bb0a2f2901d4f86dfc61b856ae6e506b1d/scripts/needs_ci_run#L28-L48

**Comment by kevinkreiser** [comment]
it is something we put in settings in circle and it is also something that is currently set. maybe circle rotated the tokens. i can check that

**Comment by kevinkreiser** [comment]
ive regenerated it. lets see if it still works

**Comment by nilsnolde** [comment]
also working now, pushed a changelog-only commit in #4062
