### ISSUE TITLE
Codecov broken too?

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4063]
codecov didn't run on #4055, instead it printed `{'detail': ErrorDetail(string='Commit sha does not match Circle build. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`:
https://app.circleci.com/pipelines/github/valhalla/valhalla/10502/workflows/3b41bd14-60a8-4a9e-b565-fc24585261a0/jobs/57495/parallel-runs/0/steps/0-120

**Comment by kevinkreiser** [comment]
the codecov token was not there in the circleci settings at all. i've added it, so we can see if its resolved now

**Comment by nilsnolde** [comment]
jep that has worked in #4062
