### ISSUE TITLE
Documentation on building from source on debian should not pull in binary packages from untrusted source

### ISSUE THREAD

**Issue by 5balls** [valhalla/valhalla#4074]
The build instructions for valhalla on debian reads:

To install on a Debian or Ubuntu system you need to install its dependencies with:

    ./scripts/install-linux-deps.sh

Now you can build and install Valhalla, e.g.

    # will build to ./build
    cmake -B build -DCMAKE_BUILD_TYPE=Release
    make -C build -j$(nproc)
    sudo make -C build install

The install-linux-deps.sh for the release 3.3.0 contains the following:

    # Adds the primeserver ppa
    apt-get update --assume-yes
    apt-get install --assume-yes software-properties-common
    add-apt-repository ppa:valhalla-core/valhalla

IMO it should be clearly communicated that this script adds another (from my point of view untrusted) repository to the debian system or IMO better it should be mentioned as source dependency to build prime_server first. If I'm going to build it from source I'm already not looking for the easy path necessarily.

**Comment by nilsnolde** [comment]
That’s long “fixed” in master, albeit not for the reason you’re mentioning (the PPA was part of the project, it’s as untrusted as the entire codebase here). It’s just not maintained anymore.

**Comment by 5balls** [comment]
It is changed on master but is still in the latest source release 3.3.0. If the ppa is unmaintained your instructions wont even work properly for your latest source release!

**Comment by nilsnolde** [comment]
It never worked for 22.04 anyways (or any other distro). Happy to accept some maintenance around that as a PR!

**Comment by kevinkreiser** [comment]
it was a documentation vestige and a simply overlooked aspect of the release. the best option is just use the current instructions to build that old release and move on with your life.

in my opinion it's not worth patching the tag and re releasing. the code still works fine just install prime_server from source like ci was doing at that time

**Comment by kevinkreiser** [comment]
also the next release is coming in a couple days

**Comment by 5balls** [comment]
Thanks for looking into it @nilsnolde  and @kevinkreiser. Can confirm that installing prime_server from source works fine. But while you are at it you may also want to look at the source tarball packaging of prime_server. I think the last release does not package the git submodules so logger.cpp or something like that is missing (also there are some ppa's in the prime_server instructions for the last source release - removed in master as well). So this is looking good for the future releases. IMO - and YMMV - ppa's should be avoided and either it should be properly maintained debian upstream packages or more reasonable compiling instructions should just work self contained (even if dependencies involve compiling other libraries).

**Comment by 5balls** [comment]
PPA's are fine for binary installs IMO, but for source compile instructions I don't expect them - but as said YMMV, thanks for your work!

**Comment by nilsnolde** [comment]
YMMV=your mileage may vary? :laughing: that's a new one to me!

**Comment by kevinkreiser** [comment]
the missing submodules is a know issue which we have no control over. it's a function of the github releases feature itself unfortunately

**Comment by kevinkreiser** [comment]
long term I think we will aubmodule prime server and let cmake do all the work. I'd love to get back into making proper packages for all this but I'd have to reduce myself on the tooling
