### ISSUE TITLE
Include Country/State Crossing Geometry Index in Response

### ISSUE THREAD

**Issue by davislasis** [valhalla/valhalla#4076]
Hi, 
We need a country returned in leg maneuvers data array.
Ideal to add a new variable if this leg is country border crossing point or not.

How fast can you develop this enhancement?

Thanks

**Comment by kevinkreiser** [comment]
how fast can *you* develop it!? :smile:

when we construct the route we do attach admin (country/state) information to all the nodes in the route: https://github.com/valhalla/valhalla/blob/6e0db89cefc4e8d1b43f9a3ccb5874a99c166ee3/src/thor/triplegbuilder.cc#L1553-L1557

the directions object however does not copy over this information. so if you want it on the standard valhalla flavored json output you'll need to add it there and then serialize it.

if you dont care which format you use though, we already output it on the OSRM flavored json format: https://github.com/valhalla/valhalla/blob/6e0db89cefc4e8d1b43f9a3ccb5874a99c166ee3/src/tyr/route_serializer_osrm.cc#L464-L466

you get this by just using `"format":"osrm"` in the request json

**Comment by davislasis** [comment]
Hi Kevin,
Thanks for reply.

I am PHP developer, not familiar with Valhalla code, but i do understand somewhat of that.
I am just looking for a solution for my problem here.

I did test your suggestion with OSRM format, but it does not work for me. Maybe i have outdated version on our server.
Response i have, does not include any data about country (most urgent variable we need) or country border crossing.

There are few new variables though, like "admin_index", "geometry_index", "out" - i have no idea what those are.

`      "weight_name": "auto",
      "weight": 4251.111,
      "duration": 3878.642,
      "distance": 85826.906,
      "legs": [
        {
          "via_waypoints": [],
          "admins": [
            {}
          ],
          "weight": 4251.111,
          "duration": 3878.642,
          "steps": [
            {
              "intersections": [
                {
                  "classes": [
                    "restricted"
                  ],
                  "bearings": [
                    185
                  ],
                  "entry": [
                    true
                  ],
                  "admin_index": 0,
                  "out": 0,
                  "geometry_index": 0,
                  "location": [
                    23.738529,
                    56.645731
                  ]
                }
              ],
              "maneuver": {
                "type": "depart",
                "instruction": "Drive south.",
                "bearing_after": 185,
                "bearing_before": 0,
                "location": [
                  23.738529,
                  56.645731
                ]
              },
              "name": "",
              "duration": 5.124,
              "distance": 35.582,
              "driving_side": "left",
              "weight": 5.124,
              "mode": "driving",
              "geometry": "eek`kBai{gl@nHn@tGhA|@H"
            },
`

Am i missing anything here?

Thanks

**Comment by kevinkreiser** [comment]
@davislasis if its not already on, we should be able to turn it on with a request option. i noticed that its triggered by node index attributes being included, maybe we just need to add:

`"filters":{"attributes":["node.admin_index"],"action":"include"}` to your osrm format request?

at the end of the day though we dont split geometry (ways) at country/state borders, so the actual index in the geometry may not be exactly at the border

**Comment by davislasis** [comment]
I will test this tomorrow morning.

The feature i must achieve here is - route can go through multiple countries, i need to figure out how many km are in each country. In general (in most cases), i know start and end point, but in the route can be multiple stop-points as well.

I thought if every leg would have country writen, i could loop through legs and calculate that.
Or maby there is a way how this could be achieved through summary data?

Thanks again

**Comment by davislasis** [comment]
Hi @kevinkreiser,

We have older docker image on our server, v3.1.4 - that's the main issue i couldn't replicate your tests.
We are looking forward to update to newest version.

Meanwhile i did some test requests to test server and it works with your request param additions.

Test route:
https://valhalla1.openstreetmap.de/route?json={"costing":"auto","format":"osrm","filters":{"attributes":["node.admin_index"],"action":"include"},"locations":[{"lat":56.645762,"lon":23.7378725},{"lat":55.9362946,"lon":23.3315101}]}

It does return leg admins (countries) and does include that in each leg intersection. So i can loop all legs and intersections to calculate distance within country.

To avoid leg looping from response, brilliant would be:
- get those data from default JSON format
- get summary like 

routes.0.legs.0.admins

`
[
    {
        "iso_3166_1_alpha3": "LVA",
        "iso_3166_1": "LV",
        "distance": 85830.898,
        "duration": 3876.065
    },
    {
        "iso_3166_1_alpha3": "LTU",
        "iso_3166_1": "LT",
        "distance": 20000.898,
        "duration": 676.065
    }
]
`

Many thanks for you effort and help here so far!

**Comment by kevinkreiser** [comment]
I think what you need is very specific to your use case. we could add what you suggested to the summaries but when you can get that info with a simple for loop, it doesn't make sense for us to add extra size to our response payload

**Comment by davislasis** [comment]
Actually i overlooked data, i think. I messed up distance against duration.
It is not possible with simple loop.

Reason:
- each leg has admins (countries involved) - OK
- leg has overall distance, but this can be in both countries
- each legs each step has distance, but again - at this stage, i still don't know in which country this is
- if we go deeper - each step each intersection has admin index, finally i know country, but it has no data about distance, because it's a point


I understand what you are saying, but adding few summary details should not increase payload a ton, in my opinion.

Thanks

**Comment by kevinkreiser** [comment]
i still believe that your use-case is very specific to you. i also believe that you can get what you want from the existing response. let me explain:

in the osrm response each intersection has an `admin_index`. the intersections are nodes in the graph. this is the highest resolution of this information we can return. the interesctions each have a `duration` property on them which you can accumulate to get the time spent in each country. unfortunately they do not have a `distance` property (maybe we should add that?) however they do come with a `geometry_index` which tells which shape point in the geometry the intersection belongs to. using this you can simply accumulate the distances between points to get your distance up to any point in the route. the code to find the distance between any two lat lon points is trivial, you can either use the law of cosines or the haversine distance. for examples you can see our code: https://github.com/valhalla/valhalla/blob/6e0db89cefc4e8d1b43f9a3ccb5874a99c166ee3/src/midgard/pointll.cc#L50

if you dont want to do any of that work yourself with accumulating either time or distance, you can turn on the time and distance annotations, which will give you accumulated time and distance per shape point in the route. you can then use the geometry_index on the intersection to look up the accumulated time/distance at any point. to do that you can simply add to your request some parameters:

`"filters":{"attributes":["node.admin_index","shape_attributes.length","shape_attributes.time"],"action":"include"}`

**Comment by davislasis** [comment]
Well, on my side, best approach is less calculations possible, of course. I have used haversine distance calculations before, but in this case it would make a little bit of a hasle for first and last intersection points.

Just to confirm i understood correctly using "shape_attributes.length" filter: 
legs.0.annotation.distance.0 = 73.7
legs.0.steps.0.intersections.0.geometry_index = 0

Does this means that first intersection is 73.7m in distance?
geometry_index value is annotation.distance key?

"maybe we should add that?" 
If you ask me - definately yes, i would be more then happy to see a distance variable in each intersection.

Thanks

**Comment by kevinkreiser** [comment]
the annotations array measures the distance/time **between** each point in the geometry, so it will be one less in size than the number of points in the geometry. the first intersection is of course assumed to be 0 time/distance along the route. so you need to subtract 1 from the geometry index to get the right one.

it looks like you will still have to accumulate all of the times/distances in between where the intersections lie on the route. if i were implementing it i would simply loop over the intersections noting which ranges of geometry_index belonged to which countries. then i would do loop over the time and distance annotations in parallel accumulating them in the specific country based on which geometry_index range i was currently in. let me know if that made sense!

**Comment by davislasis** [comment]
Not exactly.
Missleading: "number of points in the geometry" and "which ranges of geometry_index belonged to which countries"

I did subtract 1 from geometry_index and summed annotation distance values, i still get ~50% of km per country.

geometry_index = 98
so i add to specific country annotation.distance.97

Not sure if it is a bug, or i am not fully understanding geometry indexes.

in my response geometry_indexes are not in following order, for example
intersection.14.geometry_index = 99
intersection.15.geometry_index = 102

Where did 3 geometry data go?

2. example i tried to capture all geometry_indexes per country - OK
but looping through country indexes, i could not match many of annotation.distance indexes
Maybe this leads to result, that a lot of annotation.distance indexes does not exist and therefore cannot be summed.

And thanks again for your help

**Comment by kevinkreiser** [comment]
ill write some pseudo code later on, i dont have time at the moment

**Comment by davislasis** [comment]
Hi @kevinkreiser, 
I managed to create a valid PHP code calculations based on your extensive explanation.
There could be around 1% total km error per country around borders, but that's good enough for my needs.

I had to use extensive looping and data re-mapping in-between, though...

To make life easier for me (and potentionally other your clients or users), easiest approach would be if your could enhance code at your end.

As i understood, your main concern is to make response payload bigger. That's a valid point.
I only can assume that filter attribute `node.admin_index` is not so commonly used accross your users. If so, then if country summary data could be included in a response only when this filter is used, it should not affect majority of your client's response payloads.

Summary data could be included under `leg`.`admins` for each country - therefore making for end user simple option to sum  those up and done.

As i have tested almost 10 of other map APIs, none of them provide such an option or data. Your are the only one and first i know so far, with whos code this is possible.
I am not demanding, just giving you a valid point of a potential code enhancement. Final decision i leave to you to decide if you are willing to go that route.

Again,
Many many thanks for your time, effort and patience.
I appreciate that a lot.

Cheers, 
Davis

**Comment by davislasis** [comment]
Hi @kevinkreiser 
I know this issue is closed and that's fine. 
Simply i couldn't find any other way how to ask last question.

My server guy did update to newest version 3.3.0, but response does not send back `admins` data. 
Do we need to re-build all route data as well? Or it should be OK with simple update?

Thanks again

**Comment by kevinkreiser** [comment]
before building the data you need to run valhalla_build_admins to create an admin database. then you need to point your valhalla.json at that whe. you are building the tiles so it can take admin information and add it to the graph. honestly the documentation is not discoverable enough. I feel like this is a gotcha since so many things depend on the admin db
