### ISSUE TITLE
Choosing the correct start and end transit station with multimodal routing

### ISSUE THREAD

**Issue by danceb** [valhalla/valhalla#4077]
Hello,

How is the public transport station searched for, where the routing starts end ends? Because it seems like that always the closest station is taken.
In a specific case here the routing is made in the way, that you have to walk first to the nearest station (1). Then you should take the train south, change to another train there (2), which then goes north again (on a different route) and passes station (3). In this time, however, one would have walked faster to the other station (3), which is indeed further away from the starting position, but you would have a shorter travel time for the whole route.

![grafik](https://user-images.githubusercontent.com/30999402/233306910-c78b23e4-3f35-48c9-b07c-63b44fa1e88c.png)

The walking distance from the starting position here to the other station (3) is around 700 m, so it is below the standard value of 2145 m from the `transit_start_end_max_distance` option.

With the relation between the last public transport station and the end position it is the same. It seems like that it always routes the way, that the last station is the one which is nearest to ending position and not the one where you would have the shortest travel time.

**Comment by nilsnolde** [comment]
We do have an extra penalty of factor 1.5 (IIRC) for pedestrian mode on multimodal, which effectively makes it > 1 km, ie more than 12 mins. I can’t remember what drives the speed of the transit here. Looking at the pic, it _could_ be faster to take the train south (although I agree, looks very odd and shouldn’t be like that). How long is the journey from 1 to 2 and 2 to 3? 

Did you try a faster walking speed and/or other departure times? If walking & transit resulted in the same departure at station 3, we might have a problem there and (wrongly) decide to take transit instead of walking.

**Comment by danceb** [comment]
Thanks for your thoughts about this!

Traveling from 1 to 2 takes around 19 minutes already with waiting at the platform.  Including waiting at 3 and than traveling to 2 takes another 35 minutes, which is around 1 hour in sum.

Just walking from 1 to 3 takes 11 minutes.

I know that there is a train from 3 to the example destination, which starts at 8:38 am. So If you start at 8:15 from 1, there is enough time to walk there and get the train. But the routing is like in the image above.

**Comment by nilsnolde** [comment]
Yeah strange.. Can't see how that's happening, unless the GTFS data isn't right (or it's not correctly parsed by us).

If you move much closer to the station 3, is it taking the train from there? Or it's always trying to take transit to get to 3 and can never walk there?

**Comment by danceb** [comment]
Ok, I now have tested many different combinations of start time and starting position. It seems like with the routing everything works fine!! (puhh :smile:). 
The behaviour here is related to the gtfs data, which is just incomplete, the train at 7:38, 8.38, ... is missing. I have to check, but I think this information would come from another gtfs data set, which is not implemented in my system. So it will calculate this strange route, because it IS faster to get the train to 2 than waiting for the train at 3.

So I am very sorry for the noise here. Closing this now.

**Comment by nilsnolde** [comment]
No worries @danceb. We still have to do quite a few more tests to be confident about our data pipeline (the algorithm is quite a lot easier to judge:)). 

It’s also really hard to debug on a user's end. You're lucky enough to have access to the raw GTFS data. We should at least give an endpoint to verify departures I think.

**Comment by nilsnolde** [comment]
> perhaps we parse the time in the request as normal and then we simply show the next departure

Yeah that’s what I was thinking as well. Good idea to let locate handle it, makes sense. That could also generally be used to query next departure(s) for a station, eg in navigation apps.
