### ISSUE TITLE
Parasitic linestrings in "/expansion" results

### ISSUE THREAD

**Issue by coderon98** [valhalla/valhalla#4083]
Hello,
I am currently working on a project where I have chosen valhalla as the routing engine. 
While testing the beta version of expansion on metropolitan France, I noticed that the result obtained with the isochronous action contains a lot of small portions of routes which are not relevant for the result.

**workaround**
A temporary solution I found was to calculate "/expansion" and then "/isochrone" on the same point (lat-lng) under the same conditions and removed everything that is not inside the isochrone curve.
Unfortunately, this approach is expensive and detrimental to the final performance. Indeed, it requires two API calls and geometry processing for one result. I think the bug can be solved easily if it is addressed natively in the valhalla project.

**request**
#### Here is the request if you want to check it locally
```
curl --location --globoff --request GET "http://localhost:8002/expansion?json={"costing":"auto","locations":[{"lon":-4.487131,"lat":48.381908}],"contours":[{"color":"ff0000","time":10}], "polygons": true, "action": "isochrone", "skip_opposites": false}"
```
#### Here is the result with the outliers
![outliers](https://user-images.githubusercontent.com/47818458/234247693-74b994ce-9aaf-4769-a29b-91bf3c14a5bd.png)

#### Here is the result without the outliers
![myresult](https://user-images.githubusercontent.com/47818458/234250906-1fe19545-cd84-4b97-837a-e3c1239c8b38.png)

### Is there a way to solve the problem more easily?

**Comment by nilsnolde** [comment]
haha parasitic :laughing: you're right, but it's a dup of #3869 

Didn't have the time yet to resolve this. It can be sped up when funding the effort, feel free to contact me on my public Github email.
