### ISSUE TITLE
mac os arm build isochrones incorrect

### ISSUE THREAD

**Issue by baileyheading** [valhalla/valhalla#4108]
A bit of a continuation of the mac os arm issue.

Routing for the build appears to work normally, but the isochrones being produced are very bizarre for mac os arm.

**mac os arm build**

<img width="478" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/12a7f4e9-58c4-40cf-8562-147dc8029778">

**mac os intel build**

<img width="475" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/27bd171b-5d14-475d-954b-b43ed5b64521">

I'll make a simpler example below

**Comment by kevinkreiser** [comment]
I suspect something with hashing. the algorithm I wrote for making the contours relies heavily on unordered containers. we should be able to post some code for turning the bitmap thing before the contours into some output and then comparing that so we know where to further debug. there is this data structure called a grid. we can write a printing function for it, turn it on and check the differences

**Comment by baileyheading** [comment]
The two examples are for the exact same lat/lon bounded region for time=5,10,15,20 with same colours


mac os arm:

<img width="497" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/83d5cd52-3fc5-4abc-8999-b6425392887d">

mac os intel:

<img width="492" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/b44370a8-a873-4041-bb9e-818f3b24c26c">

**Comment by kevinkreiser** [comment]
if you overlay them do they overlap? if you turn off denoising do more contours appear?

**Comment by baileyheading** [comment]
mac os arm

data={
        "locations": [
            {
                "lat":-34.92855772711225, "lon":138.5998605588323
            },
        ],
        "costing": "auto",
        "denoise": 0,
        "contours": [{'time': 5.0}, {'time': 10.0}, {'time': 15.0}, {'time': 20.0}]
    }

<img width="498" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/f16e2124-9e92-4126-a5f2-99217a83d52b">

**Comment by baileyheading** [comment]
I haven't overlapped them here yet, but it looks like they will overlap

**Comment by kevinkreiser** [comment]
your coloring is very confusing! each geometry comes with the time, are they colored by that?

**Comment by baileyheading** [comment]
they are coloured by line feature. I'll change it to colour them by time

**Comment by baileyheading** [comment]
t=5,10,15,20 : pink,green,blue,red

<img width="493" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/576784de-626f-4d9f-9a82-610def10f789">

**Comment by kevinkreiser** [comment]
well that's still a bit unexpected. I would have guessed they would be the same just that the linesegments would be disconnected in the one so it seems like a bit more is wrong, probably floating point math in the conrec. someone di actually refactor that a couple years ago might be worth reverting and seeing

**Comment by nilsnolde** [comment]
> I would have guessed they would be the same just that the linesegments would be disconnected

that's exactly what it looks like to me.. many line segments missing, but can't see anything actually _different_, can you?

**Comment by baileyheading** [comment]
I tried setting "generalize" : 0

**Mac os arm**

<img width="489" alt="image" src="https://github.com/valhalla/valhalla/assets/69223649/07f02348-42eb-410e-89d8-b472462f58e4">

Is this expected?

**Comment by kevinkreiser** [comment]
I think it's still missing g contours pieces. the algorithm works by making  a piece of the contour per cell of the grid that a contour passes. I guess some floating point thing misses some

**Comment by baileyheading** [comment]
> well that's still a bit unexpected. I would have guessed they would be the same just that the linesegments would be disconnected in the one so it seems like a bit more is wrong, probably floating point math in the conrec. someone di actually refactor that a couple years ago might be worth reverting and seeing

was the refactor to thor/isochrone.cc? I don't know too well how valhalla works, but it looks like where most of the isochrone work is going on to me

**Comment by kevinkreiser** [comment]
nah its in the gridded data class iirc. I'm not at a computer most of they day but can check at night and post back

**Comment by baileyheading** [comment]
> nah its in the gridded data class iirc. I'm not at a computer most of the day but can check at night and post back

I'm having a look at "gridded_data.h" now. It's not making enough contours is your hypothesis right? (due to some difference with how m1 mac handles floating point math?) or do you have some other ideas?

I don't really know how this part of the overall "valhalla system" works so the best I can do is inspect the lines relating to contour generation closely looking for anything sus.

**Comment by baileyheading** [comment]
@nilsnolde I've noticed in the PRs that you've been playing with the Mac ARM builds? Did you test out isochrones by any chance?

**Comment by nilsnolde** [comment]
No sorry, didn't do that. I was just interested to get the build itself working as I'm forced on M1 lately. @kevinkreiser is playing around with it more actually: https://github.com/valhalla/valhalla/pull/4213. 

I forgot: did you build the dependencies with rosetta or natively?

**Comment by baileyheading** [comment]
> No sorry, didn't do that. I was just interested to get the build itself working as I'm forced on M1 lately. @kevinkreiser is playing around with it more actually (though linux arm64): #4213.
> 
> I forgot: did you build the dependencies with rosetta or natively?

I did it all natively for mac ARM in this case

**Comment by nilsnolde** [comment]
Ok, then it might be an easy workaround to build them with rosetta, that should work I think. Eventually someone will find out what the problem is I'm sure:)

**Comment by baileyheading** [comment]
> Ok, then it might be an easy workaround to build them with rosetta, that should work I think. Eventually someone will find out what the problem is I'm sure:)

The point was to get valhalla running in arm though. I've been able to run it in rosetta x86 for sometime

**Comment by nilsnolde** [comment]
Ah ok, then never mind:) let's see what the arm64 experiments will surface

**Comment by nilsnolde** [comment]
Should also be fine now after https://github.com/valhalla/valhalla/pull/4213. Let us know if there’s still problems with m1 builds.
