### ISSUE TITLE
arrival times json request

### ISSUE THREAD

**Issue by javea7171** [valhalla/valhalla#4116]
Hello thanks for creating this great software

Is it possible to order or optimize a route taking into account arrival times for each location? e.g. a truck driver has to arrive at a location at a specified time.

Example:

Start: London 10:00

Manchester 12:00
Essex 14:00

End: London 17:00

I'd expect to get back based on time:

London 10:00
Manchester 12:00
Essex 14:00
London 17:00

Have read the documentation but it's not completely clear to me if this is possible and if so how to represent the arrival times in a json API request to optimized_route or matrix endpoints

**Comment by nilsnolde** [comment]
Nope that’s not possible with vanilla Valhalla. Have a look at vroom: https://github.com/vroom-project/vroom. There you can specify “service time windows” which will pretty much model what you’re after.
