### ISSUE TITLE
[Question] Valhalla as Traffic Management Engine for Semi-Autonomous Vehicle

### ISSUE THREAD

**Issue by fmg-lydonchandra** [valhalla/valhalla#4120]
Hi, has anyone used or extended Valhalla as Traffic Management Engine ?

eg. given 10 vehicles currently on road , TrafficManagementEngine will give best route to get to given destination, 
while restricting / allowing other vehicles to enter paths in best routes above to minimise collision risk.

**Comment by nilsnolde** [comment]
You mind sharing the use case? Gotta be autonomous driving in a strange environment? Or simulation stuff? 

Valhalla doesn’t support that as of now. You can hack it though with the live traffic infrastructure. Keeping the state of all vehicles paths and the associated edge ids would be in some database, then you can just update the traffic edges with what you feel like (if you know the current vehicles‘ position, you can also revert the impact of edges which are already traversed by the vehicles). 

I (ab)used the live traffic in similar ways before. Let me know via email if you want commercial support for this.

**Comment by fmg-lydonchandra** [comment]
Thanks @nilsnolde , another question: has anyone done routing and parking "rear end in" ?

Regular parking scenario:
![image](https://github.com/valhalla/valhalla/assets/104476360/d08b65fa-8142-48d3-bd96-7aa6bdc7f134)

Our parking scenario:
* Route to `Cusp` point, and then Route to final destination by reversing, eventually stopping "rear end in"

![image](https://github.com/valhalla/valhalla/assets/104476360/063389b5-0555-4c31-9972-a39e6804f619)

**Comment by nilsnolde** [comment]
I feel like this should be more the vehicles responsibility with all sensors etc, a routing engine isn’t well setup for this scenario, it depends a LOT on the local environment which we don’t really know about.

I’ll close here as it seems your main question has at least been partly answered. Feel free to re-open if there’s more to it.
