### ISSUE TITLE
Problem of overestimation in large agglomerations

### ISSUE THREAD

**Issue by coderon98** [valhalla/valhalla#4123]
By analysing the isochrones obtained in the big cities, we can see that they are too optimistic compared to reality. 
To solve the problem, I tried to create a custom pbf where I decrease the "maxspeed" values of the "way osm" according to the type of road defined in the "highway" tag (based on an article of the highway code on speed limits, openstreetmap and wikipedia data).
When generating an instance with this data, valhalla becomes four times slower without me being able to explain it. 

Can you please explain why this approach is not performing well and give me a solution for the overestimation problem?

PS: I should point out that the new pbf I get is not much bigger than the old one (barely + 5%).

**Comment by nilsnolde** [comment]
hard to tell what's going wrong. we should have country-dependent maxspeed defaults to implement the OSM wiki page which most other routers implemented as well. not much is stopping us, other than finding the time to extend the logic for the admin db a bit.

other than that, you can have a look here: https://github.com/OpenStreetMapSpeeds/. it's a side project which valhalla has full support for. you can extend the JSON provided there with your own defaults and then specify the JSON path in the valhalla config so it can pick it up.

**Comment by nilsnolde** [comment]
another, more costly, way to go is to buy historical speed patterns from e.g. tomtom, which can be plugged into Valhalla after a bit of processing. that'll provide you with the best estimate you can get.
