### ISSUE TITLE
Update documentation for Mjolnir: Getting started guide

### ISSUE THREAD

**Issue by mariogiampieri** [valhalla/valhalla#4127]
Hi, 

First off, thanks for this amazing project and in particular the recent focus on better support for transit and raw GTFS usage. I'm trying to build tiles for Washington, DC using the GTSF feed available [here](https://www.transit.land/feeds/f-dqc-wmata~bus) and the OSM pbf file from Geofabrik [here](https://www.transit.land/feeds/f-dqc-wmata~bus). The Mjolnir getting started guide references `valhalla_build_transit` but it seems this function has been depricated; from what I can tell, this function invoked `valhalla_ingest_transit -c valhalla.json` and then `valhalla_convert_transit -c valhalla.json` so that calling `valhalla_build_tiles -c valhalla.json path/to/osm.pbf` would include support for transit (assuming that `valhalla.json` correctly references the transit directory).

I can see from the activity preceding `3.4.0` that there was a fair amount of activity regarding transit, so I'm wondering whether the documentation needs to be updated to reflect these updates.

I've encountered a few issues following the above steps, having built 3.4.0 from source on an Intel-based macbook pro. 
- For my DC test case, during `valhalla_convert_transit`, I get a warning that >5m stop pairs had invalid service dates. My sense is this is due to the `calendar.txt` including an incomplete record of the network's service
- Upon running `valhalla_build_tiles`, I receive a `Segmentation fault: 11` after a `[WARN] Could not find connection point for in/egress near: 38.869526, -77.067955`. 
- I am able to build and query the graph using the same OSM file without support for transit without issue.

I was following the thread in #4003 demonstrating an example case using a GTFS feed to demonstrate transit support- I am able to build the graph using the GTFS feed referenced there(https://transitfeeds.com/p/swhn-stadtwerke-heilbronn/1239/latest) without issue but receive an error that edges are not within range (after confirming?? that my lat/long pairs are in the correct order). I worry that I'm missing a step somewhere in the building process.

**Comment by kevinkreiser** [comment]
keeping documentation up to date is hard :(

honestly the best place to look for how its supposed to be run is the [test](https://github.com/valhalla/valhalla/blob/master/test/gurka/test_gtfs.cc). the general layout is:

1. create a gtfs feed (you have that already)
2. turn the feed into protobuf via `valhalla_ingest_transit`
3. turn the protobuf into graph tiles via `valhalla_convert_transit`
4. make the road graph with transit support via `valhalla_build_tiles`
5. hope that it all worked

it is 100% likely that we havent ferreted out all the problem cases with different gtfs feeds. so if the WMTA feed has some things that throw our code for a loop it would be great to find those, add them to the test and make sure they are handled. at the moment we are in a beta phase where we need to try a bunch of feeds and shake the bugs out, so please bear with us as the maintainers dont have tons of time. if you on the other hand, do have time, please let us know and we can point you to the place where you can do a bit of work to help the project continue!

**Comment by mariogiampieri** [comment]
Thanks Kevin for your speedy response- I'll take a look at the test and will report back with any insights that I find.

**Comment by gottagoplaces** [comment]
@mariogiampieri not sure if you already resolved this on your own, but I ran into the same error when I was trying to build a graph for the Atlanta region - it seems, for me at least, the issue was that my PBF file didn't completely cover the extent of the GTFS network, and so I was able to get everything built by expanding the region of the PBF (I used BBBike.org to get a custom extract).

**Comment by nilsnolde** [comment]
Oops, didn’t know it was segfaulting there.. it’s still on our todo to avoid that and still build the graph.

**Comment by nilsnolde** [comment]
Closing here too in favor of the more specific issue about the segfaulting
