### ISSUE TITLE
Error when building a merged pbf

### ISSUE THREAD

**Issue by coderon98** [valhalla/valhalla#4129]
I tried to launch a valhalla instance with a pbf obtained by merging several pbf downloaded from Geofabrik OSM. 
This is the first time an error of this type has occurred and I think it's important that I report it. 
```
what():  Detected unsorted input data
valhalla    | /valhalla/scripts/configure_valhalla.sh: line 210:    79 Aborted                 (core dumped) valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```
It's not blocking for me, I downloaded a larger pbf than I need but it will do. 

### For fusion, I used osmium-tool:
```
sudo apt-get install osmium-tool
osmium cat france-latest.osm.pbf germany-latest.osm.pbf -o dual.osm.pbf
```
Is it not possible to use a merged file?  What does the input data sorting step in the error message correspond to ?

**Comment by kevinkreiser** [comment]
the error is in the message above, the pbf was not sorted. you can use osmium to also sort the input and then it should work fine. good luck!
