### ISSUE TITLE
Issue Loading GTFS Feed to Enable Multimodal Routing

### ISSUE THREAD

**Issue by moss-xyz** [valhalla/valhalla#4132]
Caveats:
- I think I see that the GTFS support is relatively new and might be considered "Beta", so maybe what I'm trying to do just isn't supported yet, I'm open to alternatives
- I also recognize I am relatively new at this and could be making mistakes

#### Background

I'm trying to do an accessibility analysis of Atlanta and wanted to use valhalla to calculate travel times between origin/destination pairs using a variety of travel modes: driving, walking, biking, and transit.

#### What has worked

I got valhalla working for non-transit modes after some tinkering around, using a cropped PBF file acquired from BBBike.org (I tried using an extract from Geofabrik originally, but it was giving me errors). This is the code I ran to get it working:
```
docker run -dt --name valhalla_atlanta -p 8002:8002 -v $PWD/data/pbf_atlanta:/custom_files ghcr.io/gis-ops/docker-valhalla/valhalla:latest
```

#### The issue

Now, I want to add transit to this file. I thought that valhalla might grab this from transit.land automatically when I added the `build_elevation=True`  environment variable, but it seems that wasn't the case. Instead, I downloaded GTFS file myself and created a folder tree like so:
project ($PWD)
L data
  L pbf_atlanta <- contains the PBF file for atlanta
  L gtfs_feeds <- contains a .zip named marta_20230420.gtfs.zip

Based off the instructions I saw, I was under the impression that I would have to change my docker run command to be the following: 
```
docker run -dt --name valhalla_atlanta -p 8002:8002 **-v $PWD/data/gtfs_feeds:/gtfs_feeds** -v $PWD/data/pbf_atlanta:/custom_files -e **build_transit=True** ghcr.io/gis-ops/docker-valhalla/valhalla:latest
```

However, it doesn't work, instead generating this output:
```
= Building transit tiles =

2023/05/28 01:59:03.234754 [INFO] Tiling GTFS Feeds
2023/05/28 01:59:03.247547 [INFO] Writing 0 transit pbf tiles with 8 threads...
2023/05/28 01:59:03.248866 [INFO] Finished
2023/05/28 01:59:03.249244 [INFO] Stitching 0 transit tiles with 8 threads...
2023/05/28 01:59:03.249663 [INFO] Finished
2023/05/28 01:59:03.305969 [INFO] Building transit network.
2023/05/28 01:59:03.307060 [INFO] Building transit network.
2023/05/28 01:59:03.307085 [INFO] No transit tiles found. Transit will not be added.
2023/05/28 01:59:03.307142 [INFO] Validating transit network.
2023/05/28 01:59:03.307599 [INFO] Transit directory not found. Transit will not be added.
```

I've also tried running the following code from within the docker terminal, as I saw it referenced in another help thread:
```
valhalla_ingest_transit -c valhalla.json pwd/data/gtfs_feeds
```

But this just gets me a shorter version of the above^ output:
```
2023/05/28 02:13:37.361506 [INFO] Tiling GTFS Feeds
2023/05/28 02:13:37.390563 [INFO] Writing 0 transit pbf tiles with 8 threads...
2023/05/28 02:13:37.394507 [INFO] Finished
2023/05/28 02:13:37.395403 [INFO] Stitching 0 transit tiles with 8 threads...
2023/05/28 02:13:37.396564 [INFO] Finished
```

### What now?

I'm a bit at a loss understanding if the issue is with what I am doing or not. I've tried placing the gtfs_feeds folder in various locations to understand if the valhalla_ingest_transit command is just having issues _finding_ it or what, but nothing seems to work. Am I barking up the wrong tree?

**Comment by nilsnolde** [comment]
Unzip and put the whole unzipped folder under gtfs_feeds. That’s it.

**Comment by gottagoplaces** [comment]
Nevermind! That was actually a problem with my environment, it seems that the nested subfolder set-up worked :) 

Thank you for the quick response on a Sunday! Will try the rest of the build, hopefully no more issues 🤞
