### ISSUE TITLE
Landmark Routing 3: Tile Storage of Associated Landmarks

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#4135]
- decide how we will store landmarks associated to nodes/edges/otherwise
- make the changes to the datastructures, both builders and the regular "read only" ones
- write the tests hard to do without the association code but\
- maybe we can use the setters directly on the builder objects in the unit tests and then use the getters to check that the stuff is properly associated in the tiles

**Comment by kevinkreiser** [comment]
so we want to make use of edgeinfo after discussing the original design document some loose steps to do this. the first thing we need is a new executable `valhalla_add_landmarks` all it takes is the config from there it gets the sqlite db and the location of the tiles to which it will add the landmarks. so gets the config loaded then calls `landmark_builder::add_landmarks(ptree)`. so then add_landmarks all it does is:



```python
for t in tiles:
  landmarks = db.query(t.bbox())
  tb = tile_builder(t)
  for l in landmarks:
    edges = t.get_edges_near(l, 10) # 10 meter radius?
    for e in edges:
      tb.add_tag_value(e, to_tag(l), to_value(l))
  tb.store_graph_tile()
```

this is way way simplified but the basic idea is there. the bulk of the work will be in changing tile_builder to add the "add_tag_value" method to it and to modify the tag value stuff to be aware of the landmarks. we can get into more detail once implementation starts.

i should also note that we dont want to actually loop over the tiles instead we want to make a thread pool and have them work on the tile list in parallel. to start we can skip threading if that helps

**Comment by kevinkreiser** [comment]
first question we need to answer here is if we are going by tile and we need to associate a given landmark to edges across tile hierarchy levels then we will be searching for edges for the same landmarks multiple times. so we have a few options:

1. do the naive way above where we end up finding edges for the same landmarks over and over but filtering out the ones that dont match the current tile we are updating. its main benefit is its simplicity but it will waste a lot of time searching for and finding the same edges for the same landmarks
2. we could instead only use level 0 (largest area tiles) as jobs. then when we get edges on levels 1 and 0 we keep these in their respective lists and update those child tiles. this is still a pretty simple setup but the book keeping is kind of annoying. first in the worst case we will have 21 tiles to update from one job. the area is large which means each thread may need quite a decent amount of storage while its looking up edges for that whole patch.
3. pick whatever spatial granularity we like, say 1 degree, those become the jobs, if we want to make sure we dont have large ones at the end of the job list we can still use tile size to sort them. anyway for each job we get the landmarks in the box from the db, search each one of those with loki to get the nearby edge ids, then we write a pair of edgeid,landmark_pkey to a sequence file. then when we join the threads each will have returned the location of a sequence file. we merge sort the sequence file. we enumerate the tiles in the sequence and those become our tile jobs. then we fire up the thread pool again and each thread can get a range of tiles from the sequence like we do in other data processing workloads. for this to work we need to add a column to the db to have a primary key. the pros of this approach is we dont run out of ram, we dont do any wasted searching and we logically separate the tasks of finding candidate edges for a landmark from updating the tile to add the landmarks.

its probably clear i like the last option best

**Comment by vesperlou** [comment]
got a few questions to ask:

1. should I add kLandmark following kBridge not kLevelRef, that is  `kLandmark = static_cast<uint8_t>('3'), `?
2. do you mean a `uint_32t` by `edge id` and how to lookup the `Edgeinfo` by `uint32_t edge id` only? I find something like this https://github.com/valhalla/valhalla/commit/eb5fe912b96109d5763cf92c6f113518be4a3fca#diff-8189d3cf78ffc8f6d7ee3ee746acf277aea5615c4a6da4d43f31f126472ef573R523-R524 but it constructs an edge tuple.
3. do we add latitude and longitude data in `tagged_value_blob`?

**Comment by vesperlou** [comment]
@kevinkreiser @nilsnolde hey, do either of you have time to take a look at my issue here https://github.com/valhalla/valhalla/pull/4233#issuecomment-1666868942

update:
compared with real tile size in memory, `header.end_offset()` is always smaller (for a fixed size). e.g. one landmark added for each direction of an edge comes to 8; for two edges comes to 16. the difference is not relevant to the size of added landmark itself.
One more day's digging still couldn't solve it completely. I feel I missed something in the code and need your help to point it out :)
