### ISSUE TITLE
Building from Source - Windows [third_party issue]

### ISSUE THREAD

**Issue by sdsjb** [valhalla/valhalla#4139]
Win 8.1.
1. Installed vcpkg (c:\dev\vcpkg).
2. Cloned valhalla proj (c:\temp\valhalla_s\valhalla).
3. Added to the project the vcpkg.json with pakages listed in .vcpkg_deps.txt (to be able to use local installation of vcpkg packages);
4. Run  

> c:\temp\valhalla_s\valhalla>"C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DENABLE_TOOLS=ON -DENABLE_DATA_TOOLS=ON -DENABLE_PYTHON_BINDINGS=ON -DENABLE_HTTP=ON -DENABLE_CCACHE=OFF -DENABLE_SERVICES=OFF -DENABLE_BENCHMARKS=OFF -DENABLE_TESTS=OFF -DVCPKG_TARGET_TRIPLET=x64-windows DCMAKE_TOOLCHAIN_FILE="c:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -H"c:/temp/valhalla_s/valhalla" -B"c:/temp/valhalla_s/valhalla/build" -G "Visual Studio 16 2019" -T host=x64 -A x64 

Got:

> CMake Error at src/CMakeLists.txt:164 (add_subdirectory):
  The source directory

>  C:/temp/valhalla_s/valhalla/third_party/robin-hood-hashing

>  does not contain a CMakeLists.txt file.

> CMake Error at src/CMakeLists.txt:166 (add_subdirectory):
> The source directory

>    C:/temp/valhalla_s/valhalla/third_party/cpp-statsd-client

>  does not contain a CMakeLists.txt file.

>-- Performing Test LIBCXX_SUPPORTS_MFPMATH_EQ_SSE_FLAG
-- Performing Test LIBCXX_SUPPORTS_MFPMATH_EQ_SSE_FLAG - Failed
-- Performing Test LIBCXX_SUPPORTS_MSSE2_FLAG
-- Performing Test LIBCXX_SUPPORTS_MSSE2_FLAG - Failed
-- Found Python: C:/Users/sds/AppData/Local/Programs/Python/Python39/python.exe (found version "3.9.6") found components
: Development Interpreter Development.Module Development.Embed
CMake Error at src/bindings/python/CMakeLists.txt:1 (add_subdirectory):
  The source directory

>    C:/temp/valhalla_s/valhalla/third_party/pybind11
>
> does not contain a CMakeLists.txt file.

>CMake Error at src/bindings/python/CMakeLists.txt:3 (pybind11_add_module):
 > Unknown CMake command "pybind11_add_module".

>-- Configuring incomplete, errors occurred!

Indeed, the C:/temp/valhalla_s/valhalla/third_party/ subfolders are empty. Why? What did I wrong?

**Comment by sdsjb** [comment]
Thank you. Just in case in the documentation (in the window related section)  there is no such instruction.

But now I have another error:

 >CMake Error in CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

 > "CURL_INCLUDE_DIR-NOTFOUND"

**Comment by nilsnolde** [comment]
And you sure you built `vcpkg` correctly? The documentation is 100% stale for which commit it references for `vcpkg`. Best to look at https://github.com/valhalla/valhalla/blob/master/.azure-pipelines.yml (or just do `master`, likely that's safest).

You should have a curl folder at `c:/dev/vcpkg/packages/x64/include` (this is from memory, real path will differ)

**Comment by sdsjb** [comment]
Thank you, but I am a novice in vcpkging and all this big project "building machinery" (I've never worked with azure poipelines), so it's a little difficult to me to understand my proper steps without explicit documentation...

I followed vpckg installing instructions, i.e. something like

C:\dev> git clone https://github.com/microsoft/vcpkg
C:\dev> .\vcpkg\bootstrap-vcpkg.bat 

And, after all the steps mentioned earlier, now I have "c:\dev\vcpkg\installed\x64-windows\include\".
Should I include it in some way in the configuring command in the documentation: 

>"C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DENABLE_TOOLS=ON -DENABLE_DATA_TOOLS=ON -DENABLE_PYTHON_BINDINGS=ON -DENABLE_HTTP=ON -DENABLE_CCACHE=OFF -DENABLE_SERVICES=OFF -DENABLE_BENCHMARKS=OFF -DENABLE_TESTS=OFF -DVCPKG_TARGET_TRIPLET=x64-windows DCMAKE_TOOLCHAIN_FILE="c:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -H"c:/temp/valhalla_s/valhalla" -B"c:/temp/valhalla_s/valhalla/build" -G "Visual Studio 16 2019" -T host=x64 -A x64 

?

**Comment by nilsnolde** [comment]
Na, the CMake command looks fine by itself. 

Did you do this bit?

```
# Basic packages
git -C C:\path\to\vcpkg checkout f4bd6423
cd C:\path\to\project
C:\path\to\vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"
```

**Comment by nilsnolde** [comment]
You'll need to actually install the packages, which will download the sources and build them locally on your machine.

What folders are in here? `c:\dev\vcpkg\installed\x64-windows\include`

**Comment by sdsjb** [comment]
I didn't do
>git -C C:\path\to\vcpkg checkout f4bd6423

because the official vcpkg installation instruction didn't mention this step (in addition, f4bd6423 could have obsoleted).

As I mentioned earlier I added vcpkg.json to the project, so it seems it's the same. To be sure I launched the  command 
>c:\temp\valhalla_s\valhalla>C:\dev\vcpkg\vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"

right now and got: 

>The following packages are already installed:
    curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.0.1
    geos[core]:x64-windows -> 3.11.2
    libspatialite[core,freexl,geocallbacks]:x64-windows -> 5.0.1#12
    luajit[core]:x64-windows -> 2023-01-04#1
    proj4[core,net,tiff]:x64-windows -> 8.9.9#1
    protobuf[core]:x64-windows -> 3.21.12
    sqlite3[core,rtree,tool]:x64-windows -> 3.40.1#3
    zlib[core]:x64-windows -> 1.2.13
curl:x64-windows is already installed
geos:x64-windows is already installed
libspatialite:x64-windows is already installed
luajit:x64-windows is already installed
proj4:x64-windows is already installed
protobuf:x64-windows is already installed
sqlite3:x64-windows is already installed
zlib:x64-windows is already installed
Restored 0 package(s) from C:\Users\sds\AppData\Local\vcpkg\archives in 531 us. Use --debug to see more details.

The folder c:\dev\vcpkg\installed\x64-windows\include contains libs subfolders like "curl", "geos", etc. and also some header files like "geos.h", "zlib.h" etc.

**Comment by nilsnolde** [comment]
Then I guess you work on Visual Studio.. i only know VS Code. Anyways, it’s definitely a problem with your environment, as it seems it installed curl etc just fine. 

Since a while windows got excellent support for Linux via WSL2. I’d recommend you try that, along with VS Code, which has built in support for WSL2 & C++. Just install the Microsoft and CMake plugins for C++. It’s a bit of an effort, but IMO more future-proof (windows will be another Linux distro soon😄).

**Comment by sdsjb** [comment]
Thank you, but I'd prefer to figure out what is the reason of my error without changing my current building tools.
Maybe you could tell, where (in general) CMake is supposed to get "NTERFACE_INCLUDE_DIRECTORIES" value from? From env variables?

**Comment by kevinkreiser** [comment]
no, not from environment variables. the different functions that go off to discover the locations of the dependencies we have to fill those out.

honestly though, i think learning about the way cmake works is beyond the scope of this repository. you might try reading up on that a bit elsewhere. maybe you could even write a little program that depends on curl and see if you can get cmake to find it on your system in your favorite IDE.
