### ISSUE TITLE
isochrone seems to have a hardcoded limit of 100 minutes

### ISSUE THREAD

**Issue by stevegt** [valhalla/valhalla#4143]
Does anyone know why valhalla would limit isochrone generation to 100 minutes maximum?

In a local instance using the valhalla docker image, I have max_time_contour in valhalla.json set to 300.  But I'm unable to create isochrones of more than 100 minutes: 100 works, 101 and higher doesn't.   I'm using the QGIS valhalla plugin as a client, and I receive a 400 "Bad Request" response. 

I haven't yet figured out how to debug or trace what is going on here.  I've tried altering other likely-looking config items, and have grepped the source code for variations of "100", but haven't yet been able to spot where this limit might be being enforced.

**Comment by ImreSamu** [comment]
imho: Try changing the configuration value in your config file.

```json
     'isochrone': {
            'max_contours': 4,
            'max_time_contour': 120,
            'max_distance': 25000.0,
            'max_locations': 1,
            'max_distance_contour': 200,
        },
```
https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_config#L243

**Comment by stevegt** [comment]
> imho: Try changing the configuration value in your config file.

I already have that set to 300.  From my previous message:
> I have max_time_contour in valhalla.json set to 300. 

Here's that complete section of the config file as I currently have it set:

```
    "isochrone": {
      "max_contours": 4,   
      "max_distance": 25000,
      "max_distance_contour": 320,
      "max_locations": 1,
      "max_time_contour": 300
    },                    
```

I've tried temporarily altering several other settings in the config file that the docker image defaults to "100", with no change in behavior.  (Yes, I've restarted the docker container after each change.)

Something that's not helping with debugging this:  `src/loki/isochrone_action.cc` is supposed to throw a `valhalla_exception_t` type 151 if `contour.time() > max_contour_min`:  https://github.com/valhalla/valhalla/blob/efb4d74af3158ec9633970b249cd95a9ca97b033/src/loki/isochrone_action.cc#L53

Tracing up the call stack, I see that those exceptions are supposed to be serialized on stdout: https://github.com/valhalla/valhalla/blob/efb4d74af3158ec9633970b249cd95a9ca97b033/src/valhalla_service.cc#L126

But I'm never seeing those messages on stdout in the container.  It could be that I'm misreading the code and that those messages are supposed to be going to the client.  I don't now recall if I was seeing that '151' exception type for a contour time exception in the log box in the qgis valhalla plugin.  (And can't check right now because I'm in the middle of a tile rebuild to turn on elevations.)

Still looking.

**Comment by nilsnolde** [comment]
The Valhalla QGIS plugin is pretty much deprecated, though it should still work. It does give a „Debug Log“ in the main window with the full request. Can you paste that here? 

I’m 99.99% sure you’re **not** requesting against your local Valhalla, but FOSSGIS one, where the limit is 100.

**Comment by nilsnolde** [comment]
Also, the 151 error should be returned as a response, but the plugin doesn’t show you that. It’s only going to stdout if you’re using valhalla_service in one-shot mode.

**Comment by stevegt** [comment]
> I’m 99.99% sure you’re **not** requesting against your local Valhalla, but FOSSGIS one, where the limit is 100.

@nilsnolde You nailed it!  Even though I had localhost selected as the provider in the plugin's 'Web' dialog box, the queries were still going to FOSSGIS.  I've created https://github.com/gis-ops/valhalla-qgis-plugin/issues/10 to help any future travelers who might run across this.

> The Valhalla QGIS plugin is pretty much deprecated, though it should still work. 

Oh!  What are you using yourself for a mapping and routing client then?  I'm just now getting an environment set up, and am not wedded to QGIS.   (My first use case is cross-country RV routes that avoid steep road grades, and am hoping valhalla with 'use_hills' set low will do that job.)

**Comment by nilsnolde** [comment]
I still use the QGIS plugin as well, but I just don’t want to be publicly responsible for it, i.e. fix small bugs etc.
