### ISSUE TITLE
Turn-by-Turn Route API Query - missing coordinates?

### ISSUE THREAD

**Issue by kk2491** [valhalla/valhalla#4144]
Hi All,  

Good day.  
I have recently started using Valhalla Turn-by-Turn Route API to plot the route (waypoints) to be followed given the locations. 

`costing` method used is `auto`.   
`type` used is default (`break`). 

This is one of the example where I noticed an issue.  

Location1 - 15.7474452, 80.2231475
Location2 - 15.747110145966033, 80.222190232136
Location3 - 15.75103405310018, 80.22261938555603

In google map, this the route I get. 

![image](https://github.com/valhalla/valhalla/assets/38481564/ff637c55-8e39-4f6e-a94a-11eaf3de63c5)

Using Valhalla it gives 2 legs, and the first leg contains 2 coordinates and the second leg contains 4 coordinates.  
Looks like it skips the original locations given as input while generating the route. 

![image](https://github.com/valhalla/valhalla/assets/38481564/9dee4cf1-5f57-4aa3-ae92-e1bfdd844c0c)

Could you please help me in understand the reason for the incomplete route?  
And is there a way we can pad the original given locations to the coordinates from each leg? 

Thank you,  
KK

**Comment by nilsnolde** [comment]
Can you show the example with a request? Ideally a link to https://valhalla.openstreetmap.de.

**Comment by kk2491** [comment]
Thanks for your response. And here is the example.  

Request Type : POST  
API URL : https://valhalla1.openstreetmap.de/route 
Request Body :    

```
{
    "locations": [
        {
            "lat": 15.7474452,
            "lon": 80.2231475
        },
        {
            "lat": 15.747110145966033,
            "lon": 80.222190232136
        },
        {
            "lat": 15.75103405310018,
            "lon": 80.22261938555603
        }
    ],
    "costing": "auto",
    "units": "kilometers"
}
```

Thank you,  
KK

**Comment by nilsnolde** [comment]
I meant on here: https://valhalla.openstreetmap.de/. Re-create the route you're visualizing on GM, instead in the FOSS client. You'll see that there is no issue with Valhalla missing coordinates. Very likely you have a problem decoding the encoded polyline from the response. Showing that code would probably be most helpful. In case you weren't aware: we have 6 digit precision, as opposed to the standard 5 of Google (and many others..).

**Comment by nilsnolde** [comment]
Note there's also a demo app which lets you visualize the polyline: https://valhalla.github.io/demos/polyline

**Comment by kk2491** [comment]
I cross verified the decoded coordinates, the one from here https://valhalla.github.io/demos/polyline is matching with the results I got using the above function.  

Thank you,  
KK

**Comment by kk2491** [comment]
This is the result I got in https://valhalla.openstreetmap.de/. 

![image](https://github.com/valhalla/valhalla/assets/38481564/0704a3d2-8b89-4577-895f-603706174071)

**Comment by nilsnolde** [comment]
Hm.. that looks awkward.. Can you please post the _full_ link, including everything after the `?`?

**Comment by kk2491** [comment]
Sorry for the delay in response, here is the full link https://valhalla.openstreetmap.de/directions?profile=car&wps=80.2223667%2C15.7496449%2C80.2225653%2C15.751039

**Comment by CeallachKN** [comment]
Sorry to chip in, but the roads you are trying to use have just been added by yourself less then 24h ago https://www.openstreetmap.org/way/1179756444. Last Data Update: 2023-06-05 12:23 on https://valhalla.openstreetmap.de. therefore the roads aren't part of the routing graph.

Route with the decoded coordinates 
https://valhalla.openstreetmap.de/directions?profile=car&wps=80.234466%2C15.752562%2C80.234427%2C15.752642%2C80.233978%2C15.753563%2C80.233235%2C15.754945%2C80.232756%2C15.755875

1, 2 and 5 are the coordinates for the given locations mapped to the graph without geocoding 
3 and 4 are the points of the polyline https://www.openstreetmap.org/way/586767883
Thats's why leg2 has 4 coordinates. 
The given locations are not part of the encoded shape for the route.

The Screenshot shows the given locations used WITH Geocoding. The weird issue is that with geocoding enabled, the markers for the trip locations are not shown correctly. But thats not art of the original issue reported.

**Comment by nilsnolde** [comment]
Thanks @CeallachKN for the quick analysis. It'd would've been VERY worth mentioning that you _just_ mapped that. Next time then:)

**Comment by kk2491** [comment]
@nilsnolde I am sorry for the confusion. I missed to mention that. How long does it take to reflect the OSM updates in Valhalla route API?   

@CeallachKN Thanks for the explanation. 

> 1, 2 and 5 are the coordinates for the given locations mapped to the graph without geocoding

My input locations are different from 1, 2 and 5. Does each map to the nearest road's node ? 


> Thats's why leg2 has 4 coordinates.

I am sorry I could not clearly understand why the leg2 has 4 coordinates, could you please elaborate a little further ? 

Thank you,  
KK

**Comment by kk2491** [comment]
@nilsnolde Sure, thank you. That's what I thought. It did seem like perpendicular projection on the nearest road.  
And moreover most of the roads from India are missing in OSM, I will take some time to update few of them at least.  

Thank you,   
KK

**Comment by kk2491** [comment]
I could see that the road I updated are not visible in the Valhalla route.  

https://valhalla.openstreetmap.de/directions?profile=car&wps=80.2223667%2C15.7496449%2C80.2225653%2C15.751039  

![image](https://github.com/valhalla/valhalla/assets/38481564/1851259c-5e5d-4e97-a040-71d2679771b8)

However it does not seem like the Planet PBF is not updated yet. 

Thank you,  
KK
