### ISSUE TITLE
Build problem on large pbfs files.

### ISSUE THREAD

**Issue by coderon98** [valhalla/valhalla#4145]
Hi, I'm a bit discouraged by the weekend I've just had. I acquired a new machine with more resources than the old one in order to be able to do a build on planetary pbf data (about 68 GB of pbf data). Unfortunately, after a day and a half of build, I had an abrupt interruption of the process with the following error message:
```
/valhalla/scripts/configure_valhalla.sh: line 210: 117 Killed valhalla_build_tiles -c ${CONFIG_FILE} -s enhance ${files}
```
Please note that this happens during the "Enhancing the initial graph" phase.

I used the european pbf which is much smaller (about 27 GB). But after 8 hours of processing, I got the same result.
Can you tell me the source of the problem?

The machine I'm using has :
```
1 TB SSD ROM (95% free)
16 GB RAM
16 CPUs
intel i7
```
I feel like I've wasted several days for nothing.

Thank you so much.

**Comment by nilsnolde** [comment]
What’s the log before it’s killed?

**Comment by ImreSamu** [comment]
> 16 CPUs

Are you referring to a setup with 16 cores and 32 threads? High levels of parallel processing might be causing your RAM to be used up and lead to a system crash. You could try reducing the number of cores used, and/or consider adding more swap memory as a buffer.   
 *  https://github.com/valhalla/valhalla/issues/2384

**Comment by coderon98** [comment]
lhalla    | ===============================
valhalla    | = Enhancing the initial graph =
valhalla    | ===============================
valhalla    | 2023/06/04 21:09:12.338264 [INFO] Start stage = enhance End stage = cleanup
valhalla    | 2023/06/04 21:09:12.338481 [INFO] Read OSMData unique_names from temp file
valhalla    | 2023/06/04 21:09:14.163412 [INFO] Done
valhalla    | 2023/06/04 21:09:14.163429 [INFO] Enhancing local graph...
valhalla    | 2023/06/04 21:09:14.318255 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.318249 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.318613 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.319979 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.320893 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.320945 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.321583 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.321656 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.321703 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.321805 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.321865 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.322019 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.322495 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.322957 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.323070 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:14.323075 [INFO] Enabled default speeds assignment from config: /custom_files/default_speeds.json
valhalla    | 2023/06/04 21:09:21.884461 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:21.884609 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622258 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622321 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622344 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622626 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622693 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622709 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622737 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622808 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622843 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622877 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622894 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622908 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622936 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622954 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622967 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.622987 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623000 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623011 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623035 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623053 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623065 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623087 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623099 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623111 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623132 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623149 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.623161 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626120 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626234 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626255 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626267 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626278 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626289 [WARN] Local index 13 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626307 [WARN] Local index 14 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626336 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626349 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626361 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626372 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626383 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626399 [WARN] Local index 13 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:50.626414 [WARN] Local index 14 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:52.013393 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:54.184659 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:09:54.184733 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203615 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203677 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203733 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203737 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203746 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203749 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203757 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203760 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203768 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203775 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203783 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203789 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203796 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203801 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203808 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203813 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203818 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203825 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203829 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:13.203832 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:17.734447 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:17.734610 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:17.734675 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:17.734715 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:17.734758 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:10:17.734796 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:13:06.741710 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:13:06.748021 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:13:06.748088 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.810319 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.811988 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812027 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812030 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812051 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812054 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812066 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812068 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812080 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812082 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812093 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812095 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812104 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812106 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812112 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812114 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812119 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:08.812122 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.878864 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881037 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881067 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881082 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881106 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881124 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881141 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881154 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:14:19.881165 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:15:05.035391 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
valhalla    | 2023/06/04 21:15:05.046462 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
valhalla    | /valhalla/scripts/configure_valhalla.sh: line 210:   117 Killed                  valhalla_build_tiles -c ${CONFIG_FILE} -s enhance ${files}

**Comment by nilsnolde** [comment]
Oh yeah, @ImreSamu is right, overlooked that bit. It's a _very_ low cpu/ram ratio. Not sure what's really pulling that much RAM while enhancing, but try with a `server_threads` of 8 or even 4.

**Comment by kevinkreiser** [comment]
enhancer uses the `graphreader` interface to reach into other tiles. the reader has an in memory tile cache. the configuration for that cache is found in your valhalla.json config and is defaulted to 1gb. if you only have 16gb of ram but you are running 16 ways parallel, each thread can have up to 1gb of cache which will run you out of ram. you can set that configuration parameter to something like 500mb and hopefully stay within the limits of your machine.

https://github.com/valhalla/valhalla/blob/efb4d74af3158ec9633970b249cd95a9ca97b033/scripts/valhalla_build_config#L283

**Comment by iwpnd** [comment]
where you able to make it work this way @coderon98?

**Comment by coderon98** [comment]
Yes, I can confirm that. I readjusted my configuration by reducing the number of "server_threads" to 8 and it worked.

**Comment by iwpnd** [comment]
Aight, can confirm. Was able to make it work for europe with 4 threads on a m5.2xlarge instance.
