### ISSUE TITLE
Enabling route finding on roads under construction

### ISSUE THREAD

**Issue by aez99** [valhalla/valhalla#4148]
I'm trying to plan a route within a part of the highway which seems to be labeled as road under construction in the map ([https://www.openstreetmap.org/#map=16/41.2321/28.8358](https://www.openstreetmap.org/#map=16/41.2321/28.8358))

The default options seem to completely disregard that part of the road when finding a route as shown in [https://route.getyourmap.com/demos/routing/#loc=17,41.229895,28.844582&locations=[{%22lat%22:41.22846687919765,%22lon%22:28.842911180108786},{%22lat%22:41.23120222113064,%22lon%22:28.843683656305075}]&costing=%22auto%22](https://route.getyourmap.com/demos/routing/#loc=17,41.229895,28.844582&locations=[{%22lat%22:41.22846687919765,%22lon%22:28.842911180108786},{%22lat%22:41.23120222113064,%22lon%22:28.843683656305075}]&costing=%22auto%22)

So I tried to turn off the flags related to closed roads when constructing a request:
{"locations":[{"lat":41.226734,"lon":28.842563,"search_filter":{"exclude_closures":false}},{"lat":41.231201,"lon":28.843670,"search_filter":{"exclude_closures":false}}],"costing":"auto","costing_options":{"auto":{"closure_factor":1.0}},"directions_options":{"units":"miles"}}

However, it didn't make any difference and it still avoids the road labelled as under construction. Is there way to force Valhalla to find a route through roads under construction?

**Comment by nilsnolde** [comment]
Nope, not via a request. That's only possible if you're running Valhalla yourself, see https://github.com/gis-ops/valhalla/blob/731923446bfb32f6edfa4d24e1c428d1ef0067f3/scripts/valhalla_build_config#L50. 

`exclude_closures` is only relevant for live traffic.

**Comment by aez99** [comment]
@nilsnolde Thank you for your response. This link doesn't exist, can you please re-send it? Also, yeah I'm running Valhalla myself using this image gisops/valhalla:latest

**Comment by nilsnolde** [comment]
Oh sorry, that's our private fork. but you get the gist, it's the same location and the same line in this repository

**Comment by aez99** [comment]
Found it thanks! One last thing, to re-build the graph, is it enough to restart the container? Tried that and it seems that the changes didn't take effect

**Comment by eikes** [comment]
As far as I can tell, you currently cannot create routes on ways with a construction tag. You _can_ build the routing graph with the construction ways included but they always get excluded in the costing process.
