### ISSUE TITLE
Multiple sources to sources_to_targets only returns valid result for first source.

### ISSUE THREAD

**Issue by wieringen** [valhalla/valhalla#4153]
Something strange is happening to /sources_to_targets when giving multiple sources in combination with the bicycle profile. The first source is accurately compared to all the targets. However, the second source (even when giving the same source again) is (incorrectly) compared to only the first and second targets. The rest of the targets always return a distance and time of zero. 

Different sources
`curl -d '{"targets":[{"lon":5.1976415000000005,"lat":52.1787269},{"lon":5.2328787000000005,"lat":52.188281800000006},{"lon":5.2535733,"lat":52.201553000000004},{"lon":5.24305,"lat":52.214337},{"lon":5.2225318000000005,"lat":52.220196400000006}],"sources":[{"lon":5.0827256,"lat":52.2065365},{"lon":5.094541,"lat":52.231289}],"costing":"bicycle"}' https://valhalla1.openstreetmap.de/sources_to_targets | jq .`

The same source twice
`curl -d '{"targets":[{"lon":5.1976415000000005,"lat":52.1787269},{"lon":5.2328787000000005,"lat":52.188281800000006},{"lon":5.2535733,"lat":52.201553000000004},{"lon":5.24305,"lat":52.214337},{"lon":5.2225318000000005,"lat":52.220196400000006}],"sources":[{"lon":5.0827256,"lat":52.2065365},{"lon":5.0827256,"lat":52.2065365}],"costing":"bicycle"}' https://valhalla1.openstreetmap.de/sources_to_targets | jq .`

When I use the car profile the output seems to be correct and in line with what I expect to see.
`curl -d '{"targets":[{"lon":5.1976415000000005,"lat":52.1787269},{"lon":5.2328787000000005,"lat":52.188281800000006},{"lon":5.2535733,"lat":52.201553000000004},{"lon":5.24305,"lat":52.214337},{"lon":5.2225318000000005,"lat":52.220196400000006}],"sources":[{"lon":5.0827256,"lat":52.2065365},{"lon":5.0827256,"lat":52.2065365}],"costing":"auto"}' https://valhalla1.openstreetmap.de/sources_to_targets | jq .`

**Comment by nilsnolde** [comment]
So a problem in TDMatrix it seems; I added it to the list.

**Comment by nilsnolde** [comment]
I could reproduce it on the FOSSGIS instance and on master. Not sure what it was in the end, but #4121 fixes it.
