### ISSUE TITLE
valhalla_build_tiles: segmentation fault

### ISSUE THREAD

**Issue by khamaileon** [valhalla/valhalla#4155]
Hi guys,

This is a follow-up to this discussion: https://github.com/valhalla/valhalla/discussions/4146

I retested with another version of the GTFS file. valhalla_ingest_transit and valhalla_ingest_transit made it to the end, minus a few errors, probably due to the input data (I'll investigate this later). 

Unfortunately, the valhalla_build_tiles command always ends with a Segmentation fault (core dumped). And always at the same step: 

```
2023/06/08 14:37:16.661619 [INFO] internal intersection = 26412
2023/06/08 14:37:16.661803 [INFO] GraphFilter - nothing to filter. Skipping...
2023/06/08 14:37:17.008279 [INFO] Adding 37 transit tiles to the local graph...
2023/06/08 14:37:17.221383 [WARN] Could not find connection point for in/egress near: 48.867417,1.472441
Segmentation fault (core dumped)
```

Any idea where this might be coming from and how to debug it?

**Comment by kevinkreiser** [comment]
make a debug build of the executable. take the command you are running and prepend to it `gdb --args`. once you are in gdb type `run` and hit enter. wait for it to segfault. when it does ty pe `where` and hit enter. that will show a stacktrace whjich will tell us where its segfaulting. its possible its during multithreaded stuff in which case you m ight need to use the `thread` command to switch to the right thread.

**Comment by nilsnolde** [comment]
I think it's the same as here: https://github.com/valhalla/valhalla/issues/4127#issuecomment-1566193383

i.e. your OSM data isn't covering the whole extent of the GTFS data, which somewhere causes a segfault. That's still a limitation we'd like to get rid of. I thought there was an issue already, but can't find it.. likely a bullet point in a bigger issue..

**Comment by khamaileon** [comment]
I've got this:

```
2023/06/08 15:27:38.587854 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
[Thread 0x7ff97d9cf640 (LWP 9378) exited]
[Thread 0x7ff97e1d0640 (LWP 9379) exited]
[Thread 0x7ff97d1c0640 (LWP 9377) exited]
2023/06/08 15:36:11.559357 [INFO] Finished with max_density 24.469158
2023/06/08 15:36:11.559385 [INFO] internal intersection = 26412
[Thread 0x7ff97c995640 (LWP 9376) exited]
2023/06/08 15:36:11.559479 [INFO] GraphFilter - nothing to filter. Skipping...
2023/06/08 15:36:11.782639 [INFO] Adding 37 transit tiles to the local graph...
[New Thread 0x7ff97e1d0640 (LWP 9380)]
[New Thread 0x7ff97d9cf640 (LWP 9381)]
[New Thread 0x7ff97d1c0640 (LWP 9382)]
[New Thread 0x7ff97c995640 (LWP 9383)]
2023/06/08 15:36:11.823237 [WARN] Could not find connection point for in/egress near: 49.095376,2.753825

Thread 11 "valhalla_build_" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ff97d9cf640 (LWP 9381)]
0x000055b3873cdd48 in (anonymous namespace)::build(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::mutex&, std::__detail::_Node_const_iterator<valhalla::baldr::GraphId, true, true>, std::__detail::_Node_const_iterator<valhalla::baldr::GraphId, true, true>, std::promise<(anonymous namespace)::builder_stats>&) ()
(gdb) thread
[Current thread is 11 (Thread 0x7ff97d9cf640 (LWP 9381))]
(gdb) where
#0  0x000055b3873cdd48 in (anonymous namespace)::build(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::mutex&, std::__detail::_Node_const_iterator<valhalla::baldr::GraphId, true, true>, std::__detail::_Node_const_iterator<valhalla::baldr::GraphId, true, true>, std::promise<(anonymous namespace)::builder_stats>&) ()
#1  0x00007ff981f872b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ff981c10b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#3  0x00007ff981ca1bb4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
(gdb) 
```

**Comment by khamaileon** [comment]
> i.e. your OSM data isn't covering the whole extent of the GTFS data, which somewhere causes a segfault.

That's probably the case here.

**Comment by khamaileon** [comment]
I'm testing it with a larger pbf to be sure.

**Comment by khamaileon** [comment]
Are the files generated (tiles, admin zones, etc.) the same in DEBUG as in RELEASE?

**Comment by nilsnolde** [comment]
Jep, they're equivalent

**Comment by nilsnolde** [comment]
Let me close here, we have the other issue which supersedes this one.

**Comment by khamaileon** [comment]
Ok thanks @nilsnolde . I've restricted my GTFS to the area covered by the OSM file. Tiles are still being generated but no errors so far, so that's probably the problem. By the way, do you know if tile generation in DEBUG version is slower than in RELEASE version?

**Comment by nilsnolde** [comment]
Should be somewhat slower yeah, it’ll do all the asserts etc. I don’t think you’d feel it much though on that particular stuff. Others can probably answer more competently😅

**Comment by kevinkreiser** [comment]
it will be significantly slower because it disables compiler optimizations
