### ISSUE TITLE
Remove Pedestrian, Bicycle, Buse routes

### ISSUE THREAD

**Issue by NerMerss** [valhalla/valhalla#4186]
I'm trying to build a navigation for a car and I'm limited in size. Task: to make navigation throughout Europe and fit it into 7GB. I am using zstd to compress files. The problem is that valhalla uses a lot of unnecessary tags for me and I still can't figure out how to exclude them from the build. Can someone help me with this?
when I looked at the navigation tags used, there was even hiking, which became funny to me when I try to make it simple for the car

**Comment by ImreSamu** [comment]
> Task: to make navigation throughout Europe and fit it into 7GB. 

- What is the current size? In other words, how much data needs to be removed?
- What exactly do you mean by 'Europe'? Should the European parts of Russia and Turkey be included?

> when I looked at the navigation tags used, there was even hiking, 
> which became funny to me when I try to make it simple for the car

Even though I am more familiar with OpenStreetMap tags than the average user, I would exercise particular caution with 'hiking' information. A 'sac_scale = hiking' tag often appears in combination with 'highway=track', which can be traversable by car, especially if ['tracktype=grade1'](https://wiki.openstreetmap.org/wiki/Key:tracktype) is also included in the OSM way information. 
for example https://www.openstreetmap.org/way/311651095#map=19/43.81020/11.32717

Thus, it is essential to understand OpenStreetMap tagging at a basic level for any customization.

**Comment by nilsnolde** [comment]
I think currently Europe OSM graph has around 30ish gigs, it's usually fairly close to its PBF size. So in short: no, you won't get  to 7 GB. Most of the storage (in terms of size) is fixed-size so not including any particular tag is meaningless mostly. There's a few notable exceptions like names of roads, which probably would shave off quite a bit (very likely other variable-sized attributes as well), but it's not even near to what you'd need. So, removing tags by any extent is not helping much.

The only which could get you there is to remove road types from the network entirely. @ImreSamu is right, for that you need to know OSM tagging conventions pretty intimately or live with the fact that you'd miss out on car-relevant road segments. Reducing things by 75% or more is not leaving you with a very connected network though. That's pretty sure enough for all level 0 & 1 road classes and a chunk of level 2, but definitely not for stuff like `residential` or `service`: https://taginfo.openstreetmap.org/keys/highway#values. 

All in all, that won't be possible while remotely maintaining quality for car navigation, unless it's a very special use case..

**Comment by nilsnolde** [comment]
Or wait, actually I think you _could_ read compressed graph tiles as well, though currently there's only gzip compression implemented IIRC. That'd make the raw graph size of 30 gigs around 10 gigs I guess, but I'm still skeptical that you'd be able to remove 30% of the network without causing major trouble for car navigation. Also, reading gzipped tiles should be pretty bad for performance, especially with little RAM to cache.

**Comment by NerMerss** [comment]
> > Task: to make navigation throughout Europe and fit it into 7GB.
> 
> * What is the current size? In other words, how much data needs to be removed?
> * What exactly do you mean by 'Europe'? Should the European parts of Russia and Turkey be included?
> 
> > when I looked at the navigation tags used, there was even hiking,
> > which became funny to me when I try to make it simple for the car
> 
> Even though I am more familiar with OpenStreetMap tags than the average user, I would exercise particular caution with 'hiking' information. A 'sac_scale = hiking' tag often appears in combination with 'highway=track', which can be traversable by car, especially if ['tracktype=grade1'](https://wiki.openstreetmap.org/wiki/Key:tracktype) is also included in the OSM way information. for example https://www.openstreetmap.org/way/311651095#map=19/43.81020/11.32717
> 
> Thus, it is essential to understand OpenStreetMap tagging at a basic level for any customization.



I want to make valhalla tiles of Europe without United Kingdom
I've made squashfs image with tiles and they weigh 8.5GB
I want to remove pedestrian, bike and other useless routes

**Comment by ImreSamu** [comment]
@NerMerss :

> I want to remove pedestrian, bike and other useless routes

imho: you can remove the  ways with highway=[safe to remove list for your use case ] 
check the full list: https://taginfo.openstreetmap.org/keys/highway#values

my quick proposal just removing special "higway=*" tags; so the Valhalla builder not interpreting it as a topology.
* [footway](https://taginfo.openstreetmap.org/tags/highway=footway)
* [cycleway](https://taginfo.openstreetmap.org/tags/highway=cycleway)
* [steps](https://taginfo.openstreetmap.org/tags/highway=steps)
* [pedestrian](https://taginfo.openstreetmap.org/tags/highway=pedestrian)
* [platform](https://taginfo.openstreetmap.org/tags/highway=platform)
* [bridleway](https://taginfo.openstreetmap.org/tags/highway=bridleway)  ( maybe ???? )
* [raceway](https://taginfo.openstreetmap.org/tags/highway=raceway)
* [elevator](https://taginfo.openstreetmap.org/tags/highway=elevator)
* ...

in theory, you can use:
* `osmium tags-filter`   ( with "-t, --remove-tags"  ...  )
  * https://docs.osmcode.org/osmium/latest/osmium-tags-filter.html
  * Please install the latest master or latest release ..  
* or https://wiki.openstreetmap.org/wiki/Osmfilter   
* or https://github.com/osmcode/pyosmium  ( if you want to implement more complex filtering.  ( ~ expert level ) )
* ....

> I want to make valhalla tiles of Europe without United Kingdom

You can use https://docs.osmcode.org/osmium/latest/osmium-extract.html for removing unwanted areas 
( UK, Ireland and Northern Ireland, Isle of Man, [Spitsbergen](https://en.wikipedia.org/wiki/Spitsbergen), ... )

Warning:  Please do not append the osm extracts! 
* https://github.com/valhalla/valhalla/issues/3925#issuecomment-1398390637
* and keep the ferry info!
