### ISSUE TITLE
Cycling time estimates in Berlin

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#419]
(2016-07-26T13:33:30Z) @missinglink : originally created valhalla/sif#124

I find the time estimates for cycling in Berlin are far too optimistic and are usually very different from personal experience and estimated travel time provided by other apps on my phone.

eg: A west->east trip across [Tiergarten](https://en.wikipedia.org/wiki/Tiergarten_%28park%29) from [Zoologischer Garten](https://en.wikipedia.org/wiki/Berlin_Zoologischer_Garten_railway_station) train station to the [Sony Centre](https://en.wikipedia.org/wiki/Sony_Center) in Mitte.

Valhalla estimates the travel time at 9 minutes for 3.7km (6.9 meters/sec):

![screenshot_20160726-144716](https://cloud.githubusercontent.com/assets/738069/17138668/ababad6a-5341-11e6-8763-793ea932e341.png)

Compared to another app on my phone which estimates 17 mins for 3.6km (3.5 meters/sec):

![screenshot_20160726-144723](https://cloud.githubusercontent.com/assets/738069/17138796/44220aa8-5342-11e6-85a7-b98125780fec.png)

The second image shows a route which is a much nicer cycle as it takes http://www.openstreetmap.org/way/35383224 right through the park almost directly to the door (this shortcut is well known by locals) rather than taking the busy http://www.openstreetmap.org/way/24912850 between traffic lights at [Siegessäule](https://en.wikipedia.org/wiki/Berlin_Victory_Column) and then crossing another busy road on to http://www.openstreetmap.org/way/153376937.

In general I find that I need to _double the time_ in order to get accurate estimates, the average speed of 25km/hr is not realistic for a city, especially when stopping at traffic lights along the way!

Here's another example from the north of the city to Mitte:

![screenshot_20160726-144909](https://cloud.githubusercontent.com/assets/738069/17139362/67d7b7c0-5344-11e6-88e0-0b8428ecd0e0.png)

![screenshot_20160726-144924](https://cloud.githubusercontent.com/assets/738069/17139366/6df2dab8-5344-11e6-9061-f1ff0865cdfe.png)

The final example is a short route across the center of the CBD, the issue seems to be exaggerated at shorter distances:

![screenshot_20160726-152259](https://cloud.githubusercontent.com/assets/738069/17139730/f25cf8aa-5345-11e6-8cbb-1953509ed772.png)

![screenshot_20160726-152308](https://cloud.githubusercontent.com/assets/738069/17139822/36a8bd28-5346-11e6-9b49-d22dcf02a7e0.png)

(2016-07-26T13:46:44Z) @dnesbitt61 : Valhalla has an input option for cycling speed - the speed with which a cyclist can generally travel on flat roads for an extended period of time. Cyclists vary dramatically in fitness and ability so a single speed will not suit all.

(2016-07-26T13:49:49Z) @missinglink : hey @dnesbitt61 I edited to add a comment above:

> In general I find that I need to double the time in order to get accurate estimates, the average speed of 25km/hr is not realistic for a city, especially when stopping at traffic lights along the way!

Totally agree regarding differing levels of fitness, the default speeds used in erasermap would not generally be considered safe in a city like Berlin, even if it is very cycle friendly.

I would be :+1: for tuning the setting for an 'average' person, at the moment it seems tuned to an athlete.

(2016-07-26T13:53:40Z) @dnesbitt61 : There is also a setting for bicycle type - road bikes have higher speeds. City bikes and cross bikes are lower. Yes, the times for road bikes are probably tuned to a "former athlete" - I used to average 18MPH now am closer to 15MPH (25km/hr)

(2016-07-26T14:03:30Z) @missinglink : I had a glance at the wiki about [cycle performance](https://en.wikipedia.org/wiki/Bicycle_performance):

> Typical speeds
> 
> In utility cycling there is a large variation; an elderly person on an upright roadster might do less than 10 km/h (6.2 mph) while a fitter or younger person could easily do twice that on the same bicycle. For cyclists in Copenhagen, the average cycling speed is 15.5 km/h (9.6 mph).

It says the 'average cycling speed' in Copenhagen is 15.5 km/h, which I think is closer to what an average person can reasonably sustain for an 'extended period of time'.

Once the traffic lights and other stops are calculated in I think that would get the user experience closer to that of other apps.

(2016-10-11T20:20:35Z) @AlbertJP : You are probably right, multiplying travel times by 25/15 gets me realistic travel times for Utrecht as well, so a default setting on osm.org with 15 would work in cities. I don't know about cycling in rural places though.

**Comment by dnesbitt61** [comment]
We have updated the default bicycle type to "hybrid" (city bike) which has a lower default speed. This brings speeds more inline with other services. One can still override the speed in the request if they want time estimates that more accurately represent their riding style and capabilities.
