### ISSUE TITLE
Availability of graphreader in costing options

### ISSUE THREAD

**Issue by ADMUKHE** [valhalla/valhalla#4194]
I was trying to figure out a clean approach to link countries with soft avoids. [https://github.com/valhalla/valhalla/issues/4161](https://github.com/valhalla/valhalla/issues/4161)
I think to acheive anything like this, the costing should either have the config or reader available. EdgeCost calculation should depend on the country code option and we need the reader to figure out the country for the start and end node of an edge.  What do you think is a good approach to have this? Passing reader all along seems messy.

**Comment by kevinkreiser** [comment]
im going to close this and give a solution to your problem on the original issue, i agree the reader being passed along is messy and also not needed i think
