### ISSUE TITLE
Get osm way & node ids

### ISSUE THREAD

**Issue by slong8254** [valhalla/valhalla#4198]
Hello, I'm trying to get osm way & node id from map matching result (match_result).

I would like to obtain the Node ID and Way ID of OSM from the results obtained through Valhalla Map matching. How can I obtain the corresponding OSM Way ID and adjacent OSM Node ID from the match result?

**Comment by kevinkreiser** [comment]
node ids we don't have but there is a branch of a fork where it's added here: https://github.com/valhalla/valhalla/pull/3245

way ids are already supported please check the documentation
