### ISSUE TITLE
Add support for motor_vehicle:forward = no

### ISSUE THREAD

**Issue by eisams** [valhalla/valhalla#4203]
Valhalla will happily route through motor_vehicle:forward and motor_vehicle:backward restrictions

See this routing segment for an example, and compare to OSRM and GraphHopper that does it right

https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=59.91829%2C10.76063%3B59.91870%2C10.75938#map=18/59.91854/10.76084

https://www.openstreetmap.org/way/38850700

**Comment by kevinkreiser** [comment]
yep it's just hard to catch every single tagging convention. good news is this one seems very easy.

**Comment by eisams** [comment]
Cool!

Researching a bit more, it's in principle a generic modifier of all the access tags, so that's quite a few :)

I had a look at taginfo and at least bicycle and vehicle seem to be as prevalent as motor_vehicle that I encountered in my city

https://taginfo.openstreetmap.org/keys/bicycle%3Aforward#overview
https://taginfo.openstreetmap.org/keys/vehicle%3Aforward#overview

**Comment by kevinkreiser** [comment]
in the pr above I did it for all modes we support

**Comment by eisams** [comment]
I'm sure people would appreciate that, `vehicle` seems to have some use in Germany, Belgium and Netherlands
