### ISSUE TITLE
max speed and street name in route response

### ISSUE THREAD

**Issue by mkandulavm** [valhalla/valhalla#4211]
Hi All

In comparison to graphhopper , valhalla does not return max speed and street name in the route response.

Can I get some pointers, on what can be done to achieve this ?

I can try the suggestion(s), and if it works , submit the code for your review for inclusion in Valhalla. Kindly help.

**Comment by kevinkreiser** [comment]
you can use the osrm format response for this information. it has street and ref names and also has annotations for speed limit among other things. to get annotations add this to the request json:

`"filters":{"attributes":["shape_attributes.speed_limit"],"action":"include"}`
