### ISSUE TITLE
Strange or wrong Isochrone response

### ISSUE THREAD

**Issue by hn0017** [valhalla/valhalla#4222]
I am using Valhalla Demo and noticed a wrong isochrone plotted.
Not able to figure out why it is happening.

https://valhalla.openstreetmap.de/isochrones?profile=pedestrian&wps=73.54132175445558%2C18.72759177831964&range=10&interval=10

![Screenshot from 2023-07-27 18-23-34](https://github.com/valhalla/valhalla/assets/140719886/431e982b-3b40-4d77-b4bc-861045a24719)

**Comment by nilsnolde** [comment]
You can't start on an expressway with pedestrian. See here 15 mins ago: https://github.com/valhalla/valhalla/issues/4221#issuecomment-1653567494
