### ISSUE TITLE
Weird isochrone behavior from specific location

### ISSUE THREAD

**Issue by dave42424242** [valhalla/valhalla#4232]
We're seeing some odd behavior from the isochrone endpoint. When running the isochrone endpoint using this one specific location, we see this:

![image](https://github.com/valhalla/valhalla/assets/131161642/7df29f66-0254-4250-8867-b1f1f275d9c9)

I'm guessing that's the "priming" polygon that's created before any search results are actually found. This is an older version of Valhalla, but I wanted to check with the team to better understand what is happening here and hopefully find out how we can correct this. My guess is we need to regenerate the tiles, Any insight here would be greatly appreciated! Thank you!

**Comment by nilsnolde** [comment]
First I'd reproduce this with the current master of Valhalla. Even I doubt it'll make a difference, it's still important IMO.

You're using public OSM data without any modifications to the data?

**Comment by dave42424242** [comment]
We're on an older version (when transitland was still supported), so I won't be able to do that. I was just hoping someone here would recognize what was happening and point us in the right direction. I can close this issue if necessary.

**Comment by nilsnolde** [comment]
Hui, v2 then, that's really ancient :smile: We did do the work to work off of raw GTFS data if that's of any help..

Do you see the same here for isochrones: https://valhalla.openstreetmap.de/? (assuming you can model the same parameters, seems like you're running some kind of abstraction..)

**Comment by dave42424242** [comment]
Yeah, I did try to reproduce it on the demo server to no avail. We're in the process of upgrading to the latest version now that GTFS is supported, but this is something our support team was asking about. Thanks for the help.

**Comment by nilsnolde** [comment]
If it's not reproducible with recent Valhalla & data, I'll close here. Feel free to re-open should it pop up again.
