### ISSUE TITLE
 Could NOT find Protobuf

### ISSUE THREAD

**Issue by keepClamDown** [valhalla/valhalla#4234]
~/valhalla   master ±  cmake -B build -DCMAKE_BUILD_TYPE=Release
-- Configuring in release mode
CMake Error at /opt/homebrew/Cellar/cmake/3.24.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.24.3/share/cmake/Modules/FindProtobuf.cmake:650 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:183 (find_package)
  anyone can help me?

**Comment by keepClamDown** [comment]
I have install protoc （version libprotoc 3.21.9） but cmake file can't find protoc~

**Comment by nilsnolde** [comment]
What did you exactly install? Show us the command. I guess you could install protoc without protobuf libraries.. I'd say (re-)installing protobuf should solve that, ideally not manually but with homebrew.
