### ISSUE TITLE
make compile problem ： has no member named

### ISSUE THREAD

**Issue by sanleshusheng** [valhalla/valhalla#4237]
<img width="1430" alt="image" src="https://github.com/valhalla/valhalla/assets/33344109/631086f7-641f-4156-8c9f-923d3c821b8f">

**Comment by sanleshusheng** [comment]
root@21d2e6f7b686:/home/data/valhalla# git -C third_party/just_gtfs status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by sanleshusheng** [comment]
> please no screenshots of code 🙏 it's text, copy/paste pls.
> 
> what's the output of `git -C third_party/just_gtfs remote -v` and `git -C third_party/just_gtfs status`?

root@21d2e6f7b686:/home/data/valhalla# git -C third_party/just_gtfs status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by sanleshusheng** [comment]
> please no screenshots of code 🙏 it's text, copy/paste pls.
> 
> what's the output of `git -C third_party/just_gtfs remote -v` and `git -C third_party/just_gtfs status`?

root@21d2e6f7b686:/home/data/valhalla# git -C third_party/just_gtfs remote -v
origin	https://github.com/valhalla/just_gtfs.git (fetch)
origin	https://github.com/valhalla/just_gtfs.git (push)

**Comment by nilsnolde** [comment]
No idea how, but you're on the wrong commit:

`git -C third_party/just_gtfs checkout 375be1c`
