### ISSUE TITLE
Seeking Help: Adjusting Default Speed in Valhalla Docker Image (3.4.0)

### ISSUE THREAD

**Issue by ishibook** [valhalla/valhalla#4247]
Hello everyone. 
I apologize for the sudden question. I have two questions.

(1) Is there a way to change the default speed using the image published on Docker Hub version 3.4.0? I followed the steps in this issue to modify the config, but the changes didn't take effect.
Here's the link to the issue: https://github.com/valhalla/valhalla/pull/3055

(2) When I switched from version 3.0.7 to 3.4.0, the computation speed slowed down significantly, and memory consumption also increased drastically. Could this be due to the addition of some other processing?
(the previous 30 minute batch process took over 2 hours.)

I hope you're all doing well. 
Thanks.

**Comment by nilsnolde** [comment]
> I followed the steps in this issue to modify the config, but the changes didn't take effect.

Without all the commands, valhalla.json etc it'll be hard to give any support..

> (the previous 30 minute batch process took over 2 hours.)

3.0.7 is really old and we know there's been a lot of performance degradation over the years by adding more and more conditions to the expansion, but 4 times increase sounds very unlikely (hopefully!). Again, without knowing exactly what you're doing, we can't comment too much.

**Comment by nilsnolde** [comment]
> Does increasing these parameters slow down the calculation speed?

Not the parameters itself, but of course it takes a LOT longer if you actually send a matrix request with almost 1000 times more (!!!) location pairs!

Speed assignment is a bigger topic. The PR you found should give you an idea how to use https://github.com/OpenStreetMapSpeeds/schema to define default speeds _at graph build time_. There's also live traffic infrastructure which doesn't need a graph re-build, but is significantly more complex to implement.

**Comment by nilsnolde** [comment]
Closing for now
