### ISSUE TITLE
Passing timestamps to trace_attributes

### ISSUE THREAD

**Issue by stemillington-flock** [valhalla/valhalla#4248]
Apologies if this is the wrong place for this question.

I am trying to use the trace_attributes via pyvalhalla, and want to pass in a route containing gps locations and timestamps and I am hoping to get map matched outputs with speed estimates on the edges. Is this possible? It's not clear how to pass the time stamps into the function, i've tried adding a "time" (or "timestamp") attribute along with "lat", "lon" in the input but it appears to have no effect.

**Comment by kevinkreiser** [comment]
time in epoch seconds along with the lat lon should make it work properly. we even have an example of this in python.

https://github.com/OpenStreetMapSpeeds/conflation/blob/master/conflation/map_matching/valhalla.py

this calls the json api instead of using the python bindings but the idea is the same.

**Comment by nilsnolde** [comment]
Closing as answered

**Comment by JacoBezuidenhout** [comment]
Good morning @kevinkreiser , 

I tried the code in your example, but I still get the same elapsed_time if I include the time values on the Lat/Lon Pairs and use_timestamp options, and when I do not include them... Does the trace_attributes really support the use of timestamps?

In the docs they state use_timestamp in trace_route but should it also work in trace_attributes?:

> trace_route has additional options that allow more flexibility in specifying timestamps (when using encoded polyline input for the trace) and for using timestamps when computing elapsed time along the matched path. These options are:...

My code:
```
def map_match_shape_attributes(s, maximum_speed=130):
    data = {
        "shape": [{
            "lat": _s['input']['lat'],
            "lon": _s['input']['lon'],
            "time": int(_s['input']['time']),
        } for _s in s],
        "costing": "auto",
        "shape_match": "map_snap",
        "use_timestamps": "true",
    }
    # headers = {
    #     'Content-Type': "application/json",
    # }
    url = "https://<valhalla_url>/trace_attributes"
    res = requests.post(url, data=json.dumps(data))
    json_res = res.json()
    json_res['shape'] = decode_polyline(json_res['shape'])
    prev_t = 0
    for edge in json_res['edges']:
        way_length = edge["length"]
        t = edge["end_node"]["elapsed_time"]
        t_elapsed_on_way = t - prev_t  # Seconds

        # The elapsed time should be monotonically increasing. If not, this is a bad match and we will skip it
        if t < prev_t:
            print(
                "Skipping map match b/c time not monotonically increasing {} -> {}".format(
                    prev_t, t
                )
            )

        # If the elapsed time doesn't increase for some reason, we can't make any measurement here, so we will ignore it
        if t == prev_t:
            # json.dumps([{'lon': b['lon'], 'lat': b['lat'], 'type': b['type'], 'time': i} for i, b in
            #             enumerate(reversed(body['shape']))])
            continue

        kph = way_length / t_elapsed_on_way * 3600

        # Skip measurements that are going too fast
        if kph > maximum_speed:
            print(
                "Skipping map match b/c kph of {} > limit of {}".format(kph, maximum_speed)
            )
            continue
        edge["kph"] = kph
        edge["t_elapsed_on_way"] = t_elapsed_on_way
        edge["t"] = t
        edge["prev_t"] = prev_t
        prev_t = t

    json_res['data'] = data
    return json_res
```

**Comment by kevinkreiser** [comment]
both should do it but it seems if there is a problem with the match it doesn't do it then: https://github.com/valhalla/valhalla/blob/97cad0609c2085b98196286b6cb02b0e09128749/src/thor/map_matcher.cc#L188

off the top of my head I'm not sure why I did that. need to jog my memory..

**Comment by JacoBezuidenhout** [comment]
Thank you very much for the quick reply. I will try and get a workaround for this by looking at the matched points and then only sending in the matched points, would this work? Do you perhaps have a better idea? 


For example:
```
    ...
    {
      "lon": 18.52226,
      "lat": -33.876578,
      "type": "matched",
      "edge_index": 326,
      "distance_along_edge": 0.853627,
      "distance_from_trace_point": 4.177932
    },
    {
      "lon": 18.521898,
      "lat": -33.876577,
      "type": "matched",
      "edge_index": 326,
      "distance_along_edge": 1.0,
      "distance_from_trace_point": 46.125144
    },
// Split input shape here and rerun? Or should I just make the search radius bigger?
    {
      "lon": 18.521898,
      "lat": -33.876577,
      "type": "interpolated",
      "edge_index": 326,
      "distance_along_edge": 1.0,
      "distance_from_trace_point": 52.925438
    },
    {
      "lon": 18.521898,
      "lat": -33.876577,
      "type": "interpolated",
      "edge_index": 326,
      "distance_along_edge": 1.0,
      "distance_from_trace_point": 52.925438
    },
    {
      "lon": 18.521898,
      "lat": -33.876577,
      "type": "interpolated",
      "edge_index": 326,
      "distance_along_edge": 1.0,
      "distance_from_trace_point": 52.925438
    },
    {
      "lon": 18.521898,
      "lat": -33.876577,
      "type": "interpolated",
      "edge_index": 326,
      "distance_along_edge": 1.0,
      "distance_from_trace_point": 52.925438
    },
    ...
```
