### ISSUE TITLE
Minor distance differences when using route vs many_to_many

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#425]
(2016-08-11T22:10:25Z) @antoniomedrano : originally created valhalla/thor#417

There are minor differences in the results from valhalla route vs many_to_many. For example, I ran a query on [10 points in Los Angeles](https://github.com/arogi/network-tsp/blob/development/data/data_LA10.geojson) using the [LA metropolitan extract](https://s3.amazonaws.com/metro-extracts.mapzen.com/los-angeles_california.osm.pbf) for the underlying network. Here are the [route results](https://github.com/arogi/network-tsp/blob/development/data/LA10_route.txt), and here are the [many_to_many results](https://github.com/arogi/network-tsp/blob/development/data/LA10_m2m.txt), and here is [the diff](https://github.com/arogi/network-tsp/blob/development/data/LA10_diff.patch). The differences are minor, but a bit disconcerting nonetheless.

(2016-08-12T11:53:08Z) @kevinkreiser : does it have anything to do with using the `DirectedEdge::length` which is rounded to the nearest meter in the matrix stuff and using the actual shape to compute length in the route? Over many edges the rounding can accumulate and be off by some number of meters.

(2016-08-12T12:01:17Z) @kevinkreiser : nevermind, route uses the rounded edge lengths too: https://github.com/valhalla/thor/blob/master/src/thor/trippathbuilder.cc#L800

(2016-08-12T13:15:28Z) @dnesbitt61 : Can you isolate this to a single pair and provide lat,lon? I assume this is auto routes? I tried what I thought were locations 5 and 8 and they match for me (both using a Mapzen LA extract and against production). Here are 2 URLs that I tried:

http://localhost:8002/many_to_many?json={%22locations%22:[{%22lat%22:33.896637,%22lon%22:-118.298034},{%22lat%22:34.076549,%22lon%22:-117.920379}],%22costing%22:%22auto%22,%22units%22:%22km%22}

http://localhost:8002/route?json={%22locations%22:[{%22lat%22:33.896637,%22lon%22:-118.298034},{%22lat%22:34.076549,%22lon%22:-117.920379}],%22costing%22:%22auto%22,%22units%22:%22km%22}

My working theory is that bidirectional A\* uses a variable threshold once the forward and reverse paths meet while cost matrix uses a fixed value. I can experiment with changing cost matrix to use the same variable thresholding.

(2016-08-13T01:30:55Z) @antoniomedrano : The route query for those locations gets me this result:
{"trip":{"language":"en-US","summary":{"max_lon":-117.920097,"max_lat":34.076519,"time":2294,"length":**50.844**,"min_lat":33.891953,"min_lon":-118.298256},"locations":[{"side_of_street":"left","lon":-118.298035,"lat":33.896637,"type":"break"},{"side_of_street":"left","lon":-117.920380,"lat":34.076550,"type":"break"}],"units":"kilometers","legs": ...

The many_to_many got me this result:
{"many_to_many":[[{"distance":0.000,"time":0,"to_index":0,"from_index":0},{"distance":**54.217**,"time":2337,"to_index":1,"from_index":0}],[{"distance":53.092,"time":2290,"to_index":0,"from_index":1},{"distance":0.000,"time":0,"to_index":1,"from_index":1}]],"units":"km","locations":[[{"lon":-118.298035,"lat":33.896637},{"lon":-117.920380,"lat":34.076550}]]}

I built my Valhalla docker instance on August 9 with the following Dockerfile (.txt so it could be uploaded)
[Dockerfile.txt](https://github.com/valhalla/thor/files/416351/Dockerfile.txt)

(2016-08-19T19:57:41Z) @dnesbitt61 : In addition to the threshold, it appears that CostMatrix alternates between the forward search tree and the backward search tree while Bidirectional A\* expands on the lower cost tree (so the forward and backward search trees are not balanced). 

Wonder which is more correct in bidirectional A*?

  // Expand forward if sort cost < backward sort cost (from adj list)
  if (pred.sortcost() < pred2.sortcost()) {

or:

   // Alternate between forward and backward 
    iteration++;
    if ((iteration % 2) == 0) {

**Comment by dnesbitt61** [comment]
Closing this issue - recent changes with shortcut use in routes and CostMatrix may have fixed some of the discrepancies.
