### ISSUE TITLE
Elevation API - error "encoded_polyline" in url json param 

### ISSUE THREAD

**Issue by phsang198** [valhalla/valhalla#4261]
i have an error with encoded_polyline 

this is my json : 
{"shape_format":"polyline6","resample_distance":1000,"range":true,"encoded_polyline":"gnwsSmppvjEdDjZfF~f@pCrVpMjkAxMrnAtFff@zJr|@jDxZnA|KzC|V`I~o@tI|v@ec@vLwGfBcNvEiHvDsWbN_OlKmXrQgTrQw[tTyf@bXo`Ahh@{k@p[sLxGmGvDhHhHv[|`@jGtJbx@fnAxNhTfDbF~Ytc@zEhHnUb^pLjQh_AvwAzHjLfF~HjKvOdUb]f_@rk@|Tn]pi@jy@rHtL~H|LfItMnIdM~HvLtGvJzr@jfA|MfS|CrEzGfKlu@djAxCdEbDjD~DlD|FnCzIzB`JZ|HUzIkApSsFpDo@t^{GlGw@fdHki@vb@mBbNMrfA~AjMR?tGcA~@QxFg@dHgBnIcDjGyAxAyBbCLzBcB|GxHtU|GrSrW|x@fe@dyAc_@lM_ZhL_DFeRpIqmAbk@eAdCqCpAkOxHd@~Srg@~{@ak@t\cF}I"}
this request error : 
{
    "error_code": 100,
    "error": "Failed to parse json request",
    "status_code": 400,
    "status": "Bad Request"
}

But with this follow json : 
{"shape_format":"polyline6","resample_distance":1000,"range":true,"encoded_polyline":"gnwsSmppvjEdDjZfF~f@pCrVpMjkAxMrnAtFff@zJr|@jDxZnA|KzC|V`I~o@tI|v@ec@vLwGfBcNvEiHvDsWbN_OlKmXrQgTrQw[tTyf@bXo`Ahh@{k@p[sLxGmGvDhHhHv[|`@jGtJbx@fnAxNhTfDbF~Ytc@zEhHnUb^pLjQh_AvwAzHjLfF~HjKvOdUb]f_@rk@|Tn]pi@jy@rHtL~H|LfItMnIdM~HvLtGvJzr@jfA|MfS|CrEzGfKlu@djAxCdEbDjD~DlD|FnCzIzB`JZ|HUzIkApSsFpDo@t^{GlGw@fdHki@vb@mBbNMrfA~AjMR?tGcA~@QxFg@dHgBnIcDjGyAxAyBbCLzBcB|GxHtU|GrSrW|x@fe@dyAc_@lM_ZhL_DFeRpIqmAbk@eAdCqCpAkOxHd@~Srg@~{@ak@t\\cF}I"}

i can get result . 

This problem is  one "\\" charactor or two "\\\\" charactors

**Comment by phsang198** [comment]
i think when you read url json param , you save encoded_polyline in string , it have error

**Comment by kevinkreiser** [comment]
it's json so you need to escape those characters before you send them. in other words yes, it should be two slashes

**Comment by phsang198** [comment]
thank for your reply
