### ISSUE TITLE
Expansion output to LineStrings

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4266]
In the interest of response size/performance, we decided to output `MultiLineString`s for the expansion endpoint. That's fine for pure network visualization, however very inconvenient for more complex visualization or further analysis/debugging.

Should we allow a `verbose` output to create `LineString`s instead? Conveniently that can be turned off in the config. When doing that I think I'd like to add a GeoJSON utility, it's not the only place where we construct GeoJSON and it's pretty verbose.

**Comment by kevinkreiser** [comment]
what do you mean by geojson utility?

if expansion is still beta and I think it is, I'd be cool with just changing it and setting a very low limit in config for expansion size. previously you'll remember I just had it do the begin and end node to save on space. using the verbose flag is also a good idea though. we should probably just spend a but of time and consider more seriously the output options

**Comment by nilsnolde** [comment]
> what do you mean by geojson utility?

never mind, not very useful concept

Ok cool, then should we just change it to plain LineString, keep it BETA and discuss other options soon-ish? Another good argument to get MVT in:)

**Comment by nilsnolde** [comment]
I'm just really using the expansion service the first time for more detailed debugging of an annoying ferry matrix issue I'm trying to pinpoint.. The work is done mostly anyways, so I can just PR that.

**Comment by kevinkreiser** [comment]
mvt is an interesting suggestion but then we'd have new problems like what zoom level and how to return more than one of them (or could just let the coordinates run outside the bounds of a single tile though would have to worry about overflow also qgid clips mvt to tile bounds iirc). could also right size the zoom and resokution to fit in a single tile i guess as well. anyway yeah let's develope the idea some more along these lines.
