### ISSUE TITLE
Bike directions are not using bike path when they should

### ISSUE THREAD

**Issue by BjornRasmussen** [valhalla/valhalla#4270]
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=35.93270%2C-79.01844%3B35.93191%2C-79.02614

**Comment by kevinkreiser** [comment]
the route starts and ends where ther is no bike path. there I'd some bike path along the way that it could use but it would be more expensive in time and distance to do so thus the engine does not use it by default. if you want it to prefer bike paths more we do have an option for that but osm.org just uses the defaults.
