### ISSUE TITLE
Valhalla/Mapbox API Error 403

### ISSUE THREAD

**Issue by eric-walgenbach** [valhalla/valhalla#4285]
Dear community, 

I´m using the mapbox API to run calculations in Valhalla. With my 1.5 year old account it´s working. If my colleague with a newer account runs it we get a 403 error but there are no URL restrictions set up. I tried to reproduce the problem and made a new mapbox account and the token didn´t work anymore. Did anything change about Valhalla/Mapbox? Did anyone of you face this issue before? The discord of mapbox doesn´t have a solution for this problem. 

Thank you all in advance for your support! 

Best,
Eric

**Comment by nilsnolde** [comment]
I think mapbox closed access to their raw Valhalla endpoint a longer time ago. Surprised it’s even working for your old account. 

In any case, this isn’t a Valhalla issue but a Mapbox issue, so best take it up with them directly. We have a public instance for testing/demo purposes which we’re accountable for, on https://valhalla1.openstreetmap.de.
