### ISSUE TITLE
Updating traffic bidirectionally?

### ISSUE THREAD

**Issue by ChouBokYann** [valhalla/valhalla#4286]
Currently, I understand that one is capable of updating Valhalla via its tile_id using the the steps listed in https://gis-ops.com/traffic-in-valhalla/#user-content-historical-traffic-data. However, is it possible to update the road segment bidirectionally? For example, from A to B, the overall speed can be set to 50 km whereas from B to A, the speed can be set to 40km?

**Comment by nilsnolde** [comment]
dup of https://github.com/valhalla/valhalla/discussions/4180#discussioncomment-6909448
