### ISSUE TITLE
does directions builder support multiple languages for node and way names ?

### ISSUE THREAD

**Issue by mkandulavm** [valhalla/valhalla#4295]
Hi

does directions builder support loading and using multiple language names given with osm ?
It seems its only using the name:en. Is this true ?

If so, Can you please guide me as it will help validate my planned implementation ? I can try implementing and commit it for your review if I get it to work.

Cheers.

**Comment by nilsnolde** [comment]
See here: https://github.com/valhalla/valhalla/pull/4268

note that it’s not about supporting _any_ language for roads, but rather the country’s “official” ones, see the PR description for more detail (i.e. Russian name for a road in UK makes little sense, even you’d find that in OSM). AFAIU that’s not a limitation but intentional.

**Comment by mkandulavm** [comment]
@nilsnolde thank you the reply. Supporting a country's 1 or more default language will be great.

I have merged that branch, but I am not able to understand how to add the default language.  I see that admin.lua is probably the place, but I am not seeing how that script is getting called or used. Guess debugging data tools is hard ;)

can you give some guidance ?

**Comment by nilsnolde** [comment]
>  but I am not able to understand how to add the default language

You don't, it's in OSM AFAIU.

**Comment by gknisely** [comment]
@mkandulavm for that branch you need to build a new admins database.  Default languages will be created based on the OSM data.

**Comment by mkandulavm** [comment]
@gknisely thank you. I am building the admins db and I see the admins.sqlite generated before the build_tiles are called.
however I am not seeing the that the street names are using the default language in the route response still.

I understand more context will help. Could you rather tell me where I can put a breakpoint to check if the default language is loading and the street name is getting loaded ? These 2 points will help me to figure out the reason atleast.

**Comment by gknisely** [comment]
@mkandulavm Can you provide an example way with the language that you need processed.  I do have an override option for issues like this, but we may just want to update the data.  Does the Country in question have a default language or multiple?  Also, does the Country have Providences that have a supported language.  Good example of this is Canada's default language is `en` but in Quebec Providence we want to also process `fr` and favor `fr` streets over `en`

**Comment by gknisely** [comment]
@mkandulavm ok.  If you want to define an override for the default_language, you would do it here https://github.com/valhalla/valhalla/pull/4268/files#diff-687f31f02c6bb0a624827f33f233de7302f94e2c5c1099b33931752ff40d94aaR170-R184
