### ISSUE TITLE
Optional parameters in Valhalla routing

### ISSUE THREAD

**Issue by Sasha-Bachynskyi** [valhalla/valhalla#4296]
Hello developers!

I'm going through this article - [Valhalla routing service](https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/)

The **"name"** property in the **"locations"** property works fine for me as it is said in the article with this JSON request:
> {"locations":[
>     {"lat":43.654820,"lon":-79.362893,"name":"Place A"},
>     {"lat":38.892849,"lon":-77.035881,"name":"Place B"}
>     ],"costing": "truck"}

These properties actually appear in the response in the **"maneuvers"** property, which might be helpful:
> {
> "type": 5,
> "instruction": "Place B is on the right.",
> "verbal_transition_alert_instruction": "Place B will be on the right.",
> "verbal_pre_transition_instruction": "Place B is on the right.",
> ...
> }

What I don't understand is the purpose of the optional parameters like **"city"**, **"state"**, **"postal_code"**, **"country"**, and **"phone"** in **"locations"** property. Whether with these parameters or without them the response doesn't change.

Did someone use these parameters in their projects? If so, could you explain to me their purpose?

I'd appreciate any help in advance.

**Comment by kevinkreiser** [comment]
yeah those parameters were planned to be used but we never ended up making use of them. I had already removed them from the internal interface and they should be removed from documentation. sorry for the confusion
