### ISSUE TITLE
(optionally) return the matrix route geometries

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4300]
Since we already have the `RecostPaths` for the bidirectional dijkstra, it'd be quite natural to also return the path geometries for all connections. It's hardly any computation needed and would go a long way making sense of the results together with the new-ish /expansion for matrix.

**Comment by nilsnolde** [comment]
I’m just thinking how to enable that through parameters. Not much comes to mind other than e.g. a new “geometry” boolean. Could also be used for route to turn off getting the shape back. But it’s then a different default behavior than matrix.

**Comment by kevinkreiser** [comment]
what about the old `verbose` flag?

**Comment by nilsnolde** [comment]
came to mind but that's already taken since https://github.com/valhalla/valhalla/pull/3987.

**Comment by nilsnolde** [comment]
though tbh, as we later discovered, that PR is mostly another way of requesting with `format=osrm`. but osrm format also spits out the snapped `destinations` & `sources` (btw, there's another bug: with `format=valhalla` that's just the copy of the input locations, not the snapped ones). if it wasn't for that, I'd say we could remove that PR's code again and re-purpose `verbose` for geometry. wdyt?

**Comment by nilsnolde** [comment]
This'll come up soon. I don't think we should re-purpose `verbose=false` to return the geometries, it'd be a breaking change. Even it's kinda functionally redundant.. Everyone ok with a new `geometry` boolean for matrix, and also /route & /centroid?

**Comment by kevinkreiser** [comment]
i very much hesitate to add more api parameters :smile: can we use `shape_format`, add another value to it which is `none` and then update `worker.cc` to care about which action is being performed, ie route requires it but matrix, centroid and others do not and default to `none`?

**Comment by nilsnolde** [comment]
I'm with you on the not adding new params. Sure, I think shape_format would work.
