### ISSUE TITLE
CircleCI sunsets Intel Macs

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4309]
Just got an email, we have time until Jan 23, 2024. So it’s time to look into those isochrone issues. 

Any volunteers who‘re on M1?

**Comment by mahimairaja** [comment]
Hey buddy! I am new here to valhalla... I am here up with M1. What is the issue to be solved?

**Comment by nilsnolde** [comment]
This is the one: https://github.com/valhalla/valhalla/issues/4108. It’s not super straight forward, so 🤞.

**Comment by baileyheading** [comment]
I'm on board. I've been doing Mac arm builds and I've got a surface level understanding of how the isochrone code works

**Comment by nilsnolde** [comment]
circleci [extended the support for our current mac os resource class until june 28th 2024](https://circleci.com/docs/configuration-reference/#macos-execution-environment), so likely see you again on june 29th 2024 :laughing:

**Comment by nilsnolde** [comment]
Long done
