### ISSUE TITLE
Routes for trams, rail (was: costing models…)

### ISSUE THREAD

**Issue by rysson** [valhalla/valhalla#4316]
I there a way to find rail route for trams or for trains? 
I want to actualize (and visualize) some new or temporary lines. I have a list of stops (stations) only.
It works great for `bus` but I don't know how to find route for rail vehicles (trams and trains).

**Comment by nilsnolde** [comment]
For OSM that’s not possible, no. We only consider/allow public transit from GTFS. You can have a look if the public transit agency distributes a GTFS dataset which you can use. Altering those is not trivial though, depending on what you want you alter.

**Comment by rysson** [comment]
It's a great pity. I want to create GTFS for some the public transit agencies (mostly buses) and create a script to automatize some changes in another public transit agencies (all traction including rails).

It's way I'm looking something similar to navigate car (bus) but on rails not streets.

**Comment by kevinkreiser** [comment]
I'm a bit confused by the description but if you "create GTFS" valhalla will be able to use that. It can be non-trivial to create GTFS on your own but it's not too difficult a format to work with. The difficulty would lie in the lack of visual interface for the csv files that you would need to create. A lot of mental burden to think of all the connections without being able to see them on a map when creating them.

**Comment by rysson** [comment]
Sorry it was unclear.
I have access to schedule and I want to generate GTFS with route paths. 
I was hoping the Valhalla would help me plot routes.

**Comment by nilsnolde** [comment]
Have a look at https://podaris.com, they’re the only visual GTFS generator I know of. “Plot routes” is also very unclear. If you mean visualizing routes, then Valhalla is not the tool of choice, rather QGIS (there’s gtfs plugins). Even validating is not our goal, if it’s opaquely invalid GTFS data, Valhalla might not tell you what’s wrong.
