### ISSUE TITLE
date_time doesn't seem to work for isochrones (using public server)

### ISSUE THREAD

**Issue by dave42424242** [valhalla/valhalla#4317]
Here's the request I'm using:

https://valhalla1.openstreetmap.de/isochrone?json={"costing":"auto","contours":[{"time":2},{"time":10}],"locations":[{"lon":-84.389835,"lat":33.751034,"type":"break"}],"directions_options":{"units":"kilometers"},"date_time":{"value":"2023-09-01T09:00","type":1}}

No matter what I choose for the value of `date_time`, I get the exact same response. I've read that the tiles need to be built a specific way for the `date_time` param to work, so it's possible the public server doesn't have the additional metadata needed to work, but I wanted to check to make sure I understood how these requests were made and what I should expect in the response. Thanks in advance for any help!

**Comment by nilsnolde** [comment]
Depends on what you expect:) you don’t get much out of date_time other than some OSM conditional access restrictions which are quite few. Of course the public, non-profit volunteer-run & NGO-hosted Valhalla server doesn’t have any paid, commercial traffic data loaded. 

Valhalla can work with that data, but first you’ll have to get your hands on some. Contact me on enquiry@gis-ops.com if you want some commercial support around traffic in Valhalla.

**Comment by dave42424242** [comment]
That's what I assumed. We're using Inrix to give us TOD searching capabilities, but I wanted to confirm I was right about the public-hosted server. Thank you.
