### ISSUE TITLE
Transit Routes Failing

### ISSUE THREAD

**Issue by WohlstadterEWG** [valhalla/valhalla#4320]
I'm new to Valhalla and have run into an issue.  I'm using gtfs_feeds and the gtfs tiles appear to be building correctly.  However, attempts to use "multimodal" for costing result in OSRM_NO_ROUTE error.  Other costing options are working as expected.

I have also tried the demo hosted at Github https://valhalla.github.io/demos/routing/ and am also receiving an error when trying to general a transit route.
Error:
Travel Mode: multimodal, status code: 400, {"error_code":170,"error":"Locations are in unconnected regions. Go check\/edit the map at osm.org","status_code":400,"status":"Bad Request"}

Is transit routing currently supported?

**Comment by nilsnolde** [comment]
Hm, can’t say what’s wrong without looking more at the data. GTFS is still not widely tested AFAIK, so there’s bound to be problems still. The few ones I know of can route on their network though. There are a few limits though, maybe you’re hitting one of them. Also look at ped costing options, there’s a few important ones too. 

In your local installation, can you route from transit station to transit station (without walking)? Next best thing is to validate gtfs, see if it’s broken. If not, that’d likely be a bug. Can you post the link to the gtfs feed?

**Comment by nilsnolde** [comment]
And can you also post the log output of the build?

**Comment by WohlstadterEWG** [comment]
Reporting back.

I have been able to address the issues thus far as either my inexperience with Valhalla or errors in the GTFS data.  On the second point, I have been able to identify and correct anomalies in the GTFS data using the GTFS validator https://github.com/MobilityData/gtfs-validator.

I greatly appreciate Valhalla and I applaud your efforts.  Thanks!
