### ISSUE TITLE
If use the average of the distances from the starting point to multiple destinations as a heuristic will improve matrix performance?

### ISSUE THREAD

**Issue by xuruiray** [valhalla/valhalla#4321]
I find that long distance matrix takes a very long time, in the case of no route; So I'm wondering if this will speed up a little bit

**Comment by dnesbitt61** [comment]
Can you provide a bit more information? I'm not sure I understand how this can be used as a heuristic.

**Comment by nilsnolde** [comment]
And a heuristic for what?😄that code is Dijkstra, not A*. Might be interesting to try a many:many bidir A*, but likely only for weirdly distributed locations.
