### ISSUE TITLE
The Response Header of Valhalla service

### ISSUE THREAD

**Issue by ruanqizhen** [valhalla/valhalla#4328]
I noticed that in the response header that I have build from the source code, it contains only one line:
``` Access-Control-Allow-Origin: * ```
This is very likely the cause of a CORS problem that I posted in https://github.com/valhalla/valhalla/discussions/4324

Any idea how to add 2 more lines into the response header? 
```
Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS, HEAD
```

**Comment by kevinkreiser** [comment]
https://github.com/kevinkreiser/prime_server/pull/118
