### ISSUE TITLE
metrix API does not consider shortest: true flag, even if the shorted parth exists getting the longest past

### ISSUE THREAD

**Issue by shashikumarec088** [valhalla/valhalla#4332]
I am trying to get the shortest distance between the 2 locations using the matrix api, when I checked the same location with google I saw that there is a shorted path, and also saw the shorted path when I tried using the OSM API with other routing engines [link](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=38.5394%2C-90.1868%3B38.5476%2C-90.0715#map=13/38.5509/-90.1313). but with Matrix API I see that distance has deviation by 5 Kms even when the destination is away by 13 km. I tried to influence the route by using the request parameters suggested in the documentation like "shortest" and "disable_hierarchy_pruning" but these did not help. Wanted to know if is there a way to avoid using highways to consider the shortest paths for the less distant destinations. I am getting 18.3 Km as distance but the actual shortest distance is 13 km

API request:

`curl --location --request POST 'http://localhost:9000/sources_to_targets' \
--header 'Content-Type: application/json' \
--data-raw '{
    "sources": [
        {
            "lat": 38.539624,
            "lon": -90.1865434
        }
    ],
    "targets": [
        {
            "lat": 38.5476691,
            "lon": -90.0714467
        }
    ],
    "costing": "auto",
    "shortest":true
}'`

**Comment by kevinkreiser** [comment]
your request is incorrectly formatted.  specifying cost options like `shortest` needs to be nested inside other objects. have a look at examples in the api docs https://github.com/valhalla/valhalla/blob/master/docs/docs/api/turn-by-turn/api-reference.md#inputs-of-a-route

this part is important: `"costing":"auto","costing_options":{"auto":{"country_crossing_penalty":2000.0}}`

**Comment by nilsnolde** [comment]
Confirmed by testing, closing

**Comment by nilsnolde** [comment]
fwiw, the shortest route is terribly expensive in cost, 13000 vs 1600 for default route. can't really see what causes that, but must be smth that graphhopper doesn't really care about.

**Comment by shashikumarec088** [comment]
Hi @kevinkreiser and @nilsnolde 
thanks for the help with the formatting. I was able to get the shortest path after using the right cost formatting. 
@nilsnolde what I understand from your comment is using the shortest cost option might hinder the performance (in terms of response times), let me know if my understanding is right. 

@nilsnolde to give some context, I was trying to understand how the distances vary when compared with the google maps
I found that in most cases routing engine is great, and in some cases, it avoids using the residential roads, not sure if I can influence this when getting the shortest path between the locations, below is the example where Valhalla API shows 18.3 km but google maps gives 14 km and I see path exists OSM. 

valhalla car profile view in OSM directions shows 20 km:

[link](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=39.7689%2C-82.0919%3B39.7195%2C-82.2062#map=13/39.7345/-82.1511)

valhalla foot profile view in OSM directions shows 14 km:
[link](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_foot&route=39.7689%2C-82.0919%3B39.7195%2C-82.2062#map=13/39.7435/-82.1467)

API request got 18.3 km as distance:
`curl --location --request POST 'http://localhost:9000/sources_to_targets' \
--header 'Content-Type: application/json' \
--data-raw '{
    "sources": [
        {
            "lat": 39.7689572,
            "lon": -82.0920868
        }
    ],
    "targets": [
        {
            "lat": 39.7195319,
            "lon": -82.2061542
        }
    ],
    "costing": "auto",
    "costing_options":{"auto":{"shortest":true}}
}'`

google maps car directions shows 14 kms:
[link](https://www.google.com/maps/dir/39.7689572,%09-82.0920868/Circle+K,+254+E+Broadway+St,+New+Lexington,+OH+43764,+United+States/@39.7372184,-82.1819189,12.97z/data=!4m12!4m11!1m3!2m2!1d-82.0920868!2d39.7689572!1m5!1m1!1s0x8847fffe34433b5b:0xb0b15473c558c7f9!2m2!1d-82.206095!2d39.7195545!3e0?entry=ttu)

**Comment by nilsnolde** [comment]
Routing generally doesn’t work in terms of _distance_ but _cost_. If you always want the shortest path you’ll always need to put those parameters. If you want other things, you should dive into the api docs. There’s a zillion options to influence costing.

**Comment by nilsnolde** [comment]
Lastly, please don’t consider Google maps the gold standard. They do have live & historical traffic, which Valhalla can do, but likely you don’t have access to that data. That’s where their advantage stops, other than that (and somewhat performance), it’s only disadvantages/shortcomings for car travel compared to Valhalla.
