### ISSUE TITLE
exclude_unpaved seem doesn't work with motorcycle costing option

### ISSUE THREAD

**Issue by nvcnvn** [valhalla/valhalla#4336]
Here is an example: https://valhalla.openstreetmap.de/directions?profile=motorcycle&wps=106.80636763572694%2C10.81556536084666%2C106.80101931095123%2C10.813389203845343

Currently seem the exclude_unpaved don't really have any affect for motorcycle.

**Comment by nvcnvn** [comment]
Actually I'm not really sure it is related to unpaved road but it seem the case since it work with costing auto + exclude_unpaved=0

**Comment by nvcnvn** [comment]
Oh, I guess it also related to `kMinimumMotorcycleSurface = Surface::kDirt;`
https://github.com/valhalla/valhalla/blob/master/src/sif/motorcyclecost.cc#L33 

I feel the minimum surface should be `Surface::kImpassable` then merge with the exclude_unpaved path for motorcycle.

**Comment by kevinkreiser** [comment]
@nvcnvn have a look at the discussion over in #4281 it might be relevant to what you want

**Comment by nvcnvn** [comment]
OK, I will close and move to that issue
