### ISSUE TITLE
Missing commit ref in submodule

### ISSUE THREAD

**Issue by molind** [valhalla/valhalla#4337]
Tried to checkout last master commit.

```
Submodule 'third_party/just_gtfs' (https://github.com/valhalla/just_gtfs) registered for path 'third_party/just_gtfs'
fatal: remote error: upload-pack: not our ref 375be1cce2280baea3464019d3b19ddd4e3a4e5a
fatal: Fetched in submodule path 'third_party/just_gtfs', but it did not contain 375be1cce2280baea3464019d3b19ddd4e3a4e5a. Direct fetching of that commit failed.
```

**Comment by kevinkreiser** [comment]
interesting i did a fresh checkout like 2 days ago and i know we didnt change that..

**Comment by molind** [comment]
May be that's my local issues with git. I've checked it directly from github and it's present: https://github.com/valhalla/just_gtfs/commit/375be1cce2280baea3464019d3b19ddd4e3a4e5a

**Comment by kevinkreiser** [comment]
yeah of note is that we switched it from the original just_gtfs repo to our own version with speed improvements

**Comment by kevinkreiser** [comment]
i just tried this in a fresh docker container and at all works fine. i think perhaps if you try:

```
git fetch
git merge origin/master
git submodule update --init --recursive
```
you might repair your local check out
