### ISSUE TITLE
Valhalla failing to recognize sorted PBF file

### ISSUE THREAD

**Issue by moss-xyz** [valhalla/valhalla#4338]
I'm trying to load a quasi-synthetic OSM file into Valhalla. The file is based on real OSM data downloaded with [OSMnx](https://osmnx.readthedocs.io/en/stable/user-reference.html), but with modified attributes that I'm using for my own purposes.

I had exported the resulting graph as a geopackage, which I then converted to a PBF file with [ogr2osm](https://wiki.openstreetmap.org/wiki/Ogr2osm). When trying to load into Valhalla, I got the error `Detected unsorted input data` as the ways are being parsed.

I tried re-sorting it with Osmium after seeing that recommended on some other discussion threads, which was apparently successful (running `osmium fileinfo` returns `Objects ordered (by type and id): yes`), but Valhalla is still throwing the same error.

Anything else that might be causing this issue that I'm not aware of? Happy to share the PBF file too if that helps, it's just for a few blocks' worth of data.

**Comment by moss-xyz** [comment]
Whoops apologies, meant to post this as a Discussion topic instead of an Issue - let me know if I need to close this out and re-post there

**Comment by kevinkreiser** [comment]
yep sharing the pbf is the fastest way to get help

**Comment by ImreSamu** [comment]
> Sure thing, here are the original PBF and GPKG files!

imho:
The osmid cannot be negative, and this does not occur in the original OSM files. 
( in your file:   ` Smallest node ID: -9807` ; `Largest node ID: -1` ) 
However, since Valhalla tries to convert negative numbers to unsigned 64-bit integers, this causes sorting issues. 

Suggestion: 
* From the user's side, the IDs should be renumbered (using [osmium renumber](https://docs.osmcode.org/osmium/latest/osmium-renumber.html)  to renumber IDs in the OSM file). 
* In the Valhalla program, perhaps the error message can be made more precise: 
   * _'Detected unsorted input data or negative osm id'_

#### osmium fileinfo
```
$ osmium fileinfo -e  network_buckhead_original.osm.pbf 
File:
  Name: network_buckhead_original.osm.pbf
  Format: PBF
  Compression: none
  Size: 128459
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=osmium/1.7.1
    pbf_dense_nodes=true
[======================================================================] 100% 
Data:
  Bounding box: (-84.40022,33.819437,-84.339191,33.8599042)
  Timestamps:
    First: 
    Last: 1970-01-01T00:00:01Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 8211
  Number of ways: 1598
  Number of relations: 0
  Smallest changeset ID: 0
  Smallest node ID: -9807
  Smallest way ID: -9809
  Smallest relation ID: 0
  Largest changeset ID: 0
  Largest node ID: -1
  Largest way ID: -1157
  Largest relation ID: 0
  Number of buffers: 20 (avg 490 objects per buffer)
  Sum of buffer sizes: 1138432 (0.001 GB)
  Sum of buffer capacities: 1310720 (0.001 GB, 87% full)
Metadata:
  All objects have following metadata attributes: none
  Some objects have following metadata attributes: none
```

**Comment by ImreSamu** [comment]
Perhaps the best solution would be for the Valhalla program to check if OSM_ID > 0. 
If not, it should provide an appropriate error message like: 
* _**"OSM Ids must be bigger or equal to 1."**_ 

This would be similar to what the GraphHopper program does, as seen in this pull request: 
* https://github.com/graphhopper/graphhopper/pull/2652

**Comment by moss-xyz** [comment]
@ImreSamu thank you! I will try your renumbering suggestion and let you know. It seems I was using an old version of Osmium that was hiding the negative node IDs from me in the `FileInfo` output.

Interestingly, the node and way numbers appear correct in the geopackage. Do you have a suggestion on what to use to create a PBF file out of a geopackage? It seems that ogr2osm might have a bug in it causing the nodes to be ordered incorrectly.

**Comment by moss-xyz** [comment]
Can now confirm that renumbering the nodes and ways allowed the graph to be built correctly! Thank you for your help 🙏
