### ISSUE TITLE
how to run tyr::actor_t::matrix on multiple threads ?

### ISSUE THREAD

**Issue by mkandulavm** [valhalla/valhalla#4352]
Hi

On running a sample valhalla::tyr::actor_t::matrix call, I found that it runs the operations on a single CPU .
Is it not possible to deploy the computations across the multiple CPUs since the nature of this operation allows it ?

Thank you.

**Comment by nilsnolde** [comment]
You _could_ do that, however, an actor isn't thread-safe, or more specifically the underlying GraphReader isn't, mostly bcs of caches. You'd need one actor per thread and you'd do that using libvalhalla as a library. We wouldn't support that upstream, @danpat summarized it well recently: https://github.com/Project-OSRM/osrm-backend/issues/6721#issuecomment-1773002024.

You can also do it client-side, bit less performant but not by much..

**Comment by kevinkreiser** [comment]
i dont have anything new to add here but just wanted to provide a summary:

the simplest way to do one matrix in parallel is to break it into multiple requests and run those in parallel to a service configured for multiple threads/processes (the last argument on `valhalla_service`. yeah each request is single threaded but the whole process is just as parallel as you could have made it if the parallelism were inside the algorithm like you want it. the bonus of this approach is that the algorithm is still human legible :smile:
