### ISSUE TITLE
Static cast from unsigned int64 to int could be problematic

### ISSUE THREAD

**Issue by cduvenhorst** [valhalla/valhalla#4353]
https://github.com/valhalla/valhalla/blob/5b3cd9704ffd699b992b08bc4a5bf60e34d318f5/src/tyr/serializers.cc#L428

Shouldn't it be  "writer.Int64(static_cast<uint64_t>(alertc_code));"?

**Comment by kevinkreiser** [comment]
or should it be: `writer.Uint64(static_cast<uint64_t>(alertc_code));`
