### ISSUE TITLE
"motorcar:conditional" should not restrict motorcycle 

### ISSUE THREAD

**Issue by nvcnvn** [valhalla/valhalla#4355]
https://github.com/valhalla/valhalla/blob/master/src/mjolnir/pbfgraphparser.cc#L2390-L2393

Any particular reason to apply motorcar:conditional to motorcycle is a different kind?

**Comment by gknisely** [comment]
Not sure I understand the question.  It pertains to the type of vehicle.  Sometimes `hgv` are restricted while others may not be.  Same logic to motorcycles.  See https://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Comment by nvcnvn** [comment]
I mean "motorcar" != "motorcycle" right?

If "motorcar" != "motorcycle", why "motorcar:conditional" apply to motorcycle route?

**Comment by gknisely** [comment]
Ah ok.  Yes this looks like a bug.  `motorcar*` needs to be separated from `motor_vehicle*`  Do you have time to submit a PR?

Ref: https://wiki.openstreetmap.org/wiki/Key:motorcar

**Comment by nvcnvn** [comment]
Sure I will take a look and do some more testing on my side!
