### ISSUE TITLE
Ferry Approach Edge Reclassification - Recovers multiple edges from node on ShortestPath

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#4357]
I added a log statement in graphbuilder to identify driveways that are reclassified by the ferry_connections logic in mjolnir. I found that the ShortestPath method stores the node and its predecessor (and cost) along the ShortestPath from the ferry connection node. This can lead to multiple edges being reclassified when there are multiple edge between two nodes as in the case below:

![image](https://github.com/valhalla/valhalla/assets/1838768/79b5559b-73ac-41a2-b869-aeb5dccc5732)

This is on Long Island, NY - this driveway (https://www.openstreetmap.org/way/1003285180) ends up being reclassified. 

To fix this, we can add the edge wayindex to the node labels for the shortest path. Then when recovering the edges along the ShortestPath (edges to be reclassified) we can check for matching edge wayindex so we don't pick the higher cost path between 2 edges.

One point of discussion - ferry entrances with multiple "lanes" could benefit from this "bug" as it would reclassify more edges in these cases. However, in a route it would still construct shortest paths using only one lane so it likely doesn't matter if only one is reclassified and allows use in longer routes where road class hierarchy comes into play.

![image](https://github.com/valhalla/valhalla/assets/1838768/b6008453-a565-4f54-8f68-4fe76bf26bca)

**Comment by nilsnolde** [comment]
> To fix this, we can add the edge wayindex to the node labels for the shortest path

makes sense to me
