### ISSUE TITLE
CostMatrix can't handle deadends

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4371]
I can't give an example, this popped up in a TomTom graph: with the default radius it can happen that we only correlate a single edge and that edge is connected to:
- an edge it can't go on because of a turn restriction
- another edge which eventually ends up in a deadend

The bidir A* does it right and allows a uturn at the deadend so it can find its way back and take the other edge, but the CostMatrix doesn't. Looking at it, I might do a refactor first, before handling deadends. Interestingly TDMatrix computes the route in question, even though I can't see anything handling deadends there either. Might point to another bug in TDMatrix. :rabbit: :hole:

**Comment by kevinkreiser** [comment]
yeah not surprising. the reach calculation and bidir a* can handle uturns consistantly but the matrix expansion might have the old "hardcoded" dead ends. instead we changed it to figure out deadends on the fly via costing (which is better for sure anyway). we could dig up that pr just to refresh our memories i guess

**Comment by nilsnolde** [comment]
I think it's fine. after looking at it a bit more, it just needs to handle things similar to bidir a*. it's quite a bit of a refactor. but it's worth it. 

looking at timedistancematrix & isochrones, they also don't seem to care about uturns in the code, but both can fully expand my example locations where costmatrix couldn't. seems like they have 2 problems then, uturns and whatever the reason is why it's not failing like the costmatrix. but one after the other..
