### ISSUE TITLE
Building tiles with elevations is very very slow

### ISSUE THREAD

**Issue by ruanqizhen** [valhalla/valhalla#4377]
I'm working on building tiles that include elevation data. When I generated the data for a single city, the process was relatively quick, completing in less than an hour. However, when I attempted to generate data for the entire US, the challenge became evident. Without elevation data, it takes only a few hours. But with the elevation data, it's been running for a week, and the building script hasn't finished. Initially, I thought the script had stalled, but I've noticed new tiles are still being produced, just at a much slower rate. 
Is such a delay typical when working with elevation data? Any idea how to make it faster?

**Comment by nilsnolde** [comment]
FWIW, that's the fastest build stage usually. For the entire planet it takes some 10 mins or so. One common oversight is to not unzip the elevation tiles after downloading them. That's probably the case for you. Then Valhalla does the decompression on the fly and yes, that'll be terribly slow as it's jumping around between elevation tiles a lot. You can still do it now, next time you can run `valhalla_build_elevation` with `--decompress`.

**Comment by ruanqizhen** [comment]
> FWIW, that's the fastest build stage usually. For the entire planet it takes some 10 mins or so. One common oversight is to not unzip the elevation tiles after downloading them. That's probably the case for you. Then Valhalla does the decompression on the fly and yes, that'll be terribly slow as it's jumping around between elevation tiles a lot. You can still do it now, next time you can run `valhalla_build_elevation` with `--decompress`.
> 
> However, do be aware it'll take 25 MB per elevation tile once they're decompressed.

Ah, yes, I didn't unzip.  Thank you so much!
