### ISSUE TITLE
ARM & OSX test build failing the tar_index test

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4379]
https://app.circleci.com/pipelines/github/valhalla/valhalla/11448/workflows/0c56e848-36e5-440b-b153-f7933d1d459f/jobs/60292

I think I remember that one failing on M1.

**Comment by kevinkreiser** [comment]
so it only fails sometimes? i mean when i merged that pr it was passing right?

**Comment by kevinkreiser** [comment]
yeah it looks like only in the last commit this happened?

**Comment by nilsnolde** [comment]
can't see how it's a flaky test, but also not how that commit could make that test fail for anything related to the index.bin file.. that's running on utrecht tiles.

**Comment by nilsnolde** [comment]
I kicked it again

**Comment by nilsnolde** [comment]
well, at least it ran successfully on the second run. can't wrap my head around how that can be, too late for that..

**Comment by nilsnolde** [comment]
seems like it's fixed now
