### ISSUE TITLE
mjolnir.traffic_extract configuration ignored and even rewritten when set to directory which is different from tile dir

### ISSUE THREAD

**Issue by Ashen-Cz** [valhalla/valhalla#4380]
Due to some infrastructure issues, I need to keep traffic and tile files separated. So my config looks something like this:
```
    "tile_dir": "/custom_files/valhalla_tiles",
    "tile_extract": "/custom_files/valhalla_tiles.tar",
    "traffic_extract": "/valhalla/traffic.tar",
```
Interestingly, upon firing up Valhalla, I've noticed this on log: '(stat): **/custom_files/traffic.tar** No such file or directory'. I've double checked, modified traffic_extract to **/valhalla/traffic.tar** again, but it seems that every time I start Valhalla, the "traffic_extract" is rewritten back to **/custom_files/traffic.tar** . Is this by design and traffic must be in the same dir as tiles or is it bug?

**Comment by kevinkreiser** [comment]
not by design there mist be a copy paste in the code somewhere

**Comment by nilsnolde** [comment]
That's pretty sure about https://github.com/gis-ops/docker-valhalla. Can't transfer issues cross-org (that used to work though!), can you open the same there @Ashen-Cz ? Not sure yet if it's a bug or a feature:)
