### ISSUE TITLE
optimized_route issue in Japan

### ISSUE THREAD

**Issue by breketok** [valhalla/valhalla#4384]
Hi community.
I have strange problem with the optimized_route api using following input:

curl localhost:2103/optimized_route -X POST -d '{"locations":[{"lat":34.9739533333,"lon":135.9430016667},{"lat":34.9889883333,"lon":135.8379416667}],"costing":"auto"}'

Error message:
{"error_code":171,"error":"No suitable edges near location","status_code":400,"status":"Bad Request"}

Strange is that because my 12 month old valhalla instance with this region sends me correct answer with status 200.

You can check both locations. They are valid and placed on the highway. Could you please give me some ideas to debug my valhalla instance?

**Comment by breketok** [comment]
please somebody test this input on your valhalla docker instance with Japan

**Comment by breketok** [comment]
guys please run that 5 sec query to check if there are problem with valhalla in Japan

**Comment by nilsnolde** [comment]
closing as stale
