### ISSUE TITLE
Can't get a response from Valhalla - hangs (performance?)

### ISSUE THREAD

**Issue by coogle** [valhalla/valhalla#4398]
I'm trying to do a build of Valhalla (main branch) and having difficulty getting Valhalla to respond. I'm using the North America OSM data running on a smaller (t2.medium, 2 VCPU 4GB ram) AWS instance. After building the tiles and everything else (which took about 28 hrs) I am trying to run a request as a one-off and it just hangs. The behavior is the same if trying to do it via HTTP request:

```bash
valhalla_service conf/valhalla.json isochrone '{"verbose":true,"locations":[{"lat":42.358528,"lon":-83.271400}],"costing":"auto","contours":[{"time":10, "color":"ff0000"}], "show_locations":true}'
```

So far, this command has been running for a good 20+ minutes with no error and no output... The vCPUs have topped off at 50% which makes sense in a way, because I suspect it's only using a single CPU core available to me and its "hanging" because its still trying to compute the answer... Basically the problem may be that my instance is just too slow, which is okay but my questions then are:

- What would be what exactly are the server requirements for a reasonable response time (milliseconds) of a single instance? 
- I presume it's reasonable for me to tarball up the data directory I've built (like I said, took 28 hrs), store it in S3, and then pull it back down on a larger instance?
- Are there things I should be doing but aren't that can improve performance here?

Happy to answer any follow-up questions ... 

My goal is to create a server that can compute a Isochrone, elevations, or route for North America in milliseconds rather than minutes. Any suggestions and/or enlightenment of how to accomplish that would be very much appreciated!

**Comment by kevinkreiser** [comment]
well that shouldnt be the case! sounds like a regression (probably an infinite loop?). there are two ways to figure out what is going wrong:

1. make a debug build, wait for the service to hang and stop the debugger to see where the code is stuck
2. build progressively older versions of the software until the request no longer hangs

if you have time, i would suggest the second one. you dont need to rebuild the data, just rebuild the service for older versions of the code until your request starts passing and then report back where the software started working again.

if you dont have time you'll have to wait until someone else can pick it up.

**Comment by coogle** [comment]
Well I'm glad that I posted this then!

I'll go back and start rebuilding older versions, starting with the last released one. I built off dev because the elevation building script has a broken URL to fetch data in the latest release... but now that the data set is built I can try again with that tag. Will let you know.

**Comment by coogle** [comment]
Just an update here.. I've tried rebuilding against 3.4.0, 3.3.0, and now working on 3.2.1... still hangs. It seems to me that's unlikely that isochrone has literally not worked for so many versions and no one has noticed before?

**Comment by nilsnolde** [comment]
Right, it's working generally (and has been), but seems there's edge cases where it loops infinitely, see also https://github.com/valhalla/valhalla/issues/3823.

> (Side note, what is the best way to make sure / confirm the version I'm running? valhalla_service lacks a version parameter..)

Query the /status endpoint.

**Comment by nilsnolde** [comment]
I'll close here and keep the other one open. Feel free to update there if there's any more useful info from your side.

**Comment by coogle** [comment]
Yeah this isn't closed.. and it's not limited to Isochrone.

I can't get any response to work, here's another example of `route` which just hangs:

```
valhalla_service conf/valhalla.json route '{"locations":[{"lat":41.688980,"lon":-87.644064},{"lat":42.338583,"lon":-83.325412}],"costing":"auto"}'
```

Please reopen this ticket as it's not a duplicate.

**Comment by coogle** [comment]
FWIW I tried Isochrone on dev, 3.4.0, 3.3.0, 3.2.1 -- all hang. The hang I'm experiencing on `route` is also on 3.2.1.

**Comment by coogle** [comment]
I actually am trying to automate this process with an ansible task so I have a clear log of exactly what I'm doing:

Start with a AWS `t2.medium` instance running Ubuntu

1. Create Directories:

```bash
/opt/valhalla-data
/opt/valhalla-data/tiles
/opt/valhalla-data/elevation
/opt/valhalla-data/conf
``` 

2. Install Config file (will provide in separate comment)
3. Download PBF (in my case I have a copy in my AWS S3 bucket to make it faster to download)

```bash
aws s3 cp s3://valhalla-data-sa7f5nklm5ebt9ir/north-america-latest.osm.pbf /opt/valhalla-data/ --no-sign-request
```

4. Build Elevation
```bash
cd /opt/valhalla-data
valhalla_build_elevation -b "-169.1,14.8,-48.8,72.1" -o ./elevation -v
```

5. Build Admin
```bash
cd /opt/valhalla-data
valhalla_build_admins --config /opt/valhalla-data/conf/valhalla.json /opt/valhalla-data/north-america-latest.osm.pbf
```

6. Build Timezones
```bash
cd /opt/valhalla-data
valhalla_build_timezones > timezones.sqlite
```

7. Build Tiles (this took 28 hrs or so)
```bash
cd /opt/valhalla-data
valhalla_build_tiles -c /opt/valhalla-data/conf/valhalla.json /opt/valhalla-data/north-america-latest.osm.pbf
```

8. Create Tiles Tarball
```bash
cd /opt/valhalla-data
find tiles | sort -n | tar -cf tiles.tar --no-recursion -T -
```

**Comment by coogle** [comment]
Here is my configuration file
```json
{
  "additional_data": {
    "elevation": "/opt/valhalla-data/elevation/"
  },
  "httpd": {
    "service": {
      "drain_seconds": 28,
      "interrupt": "ipc:///tmp/interrupt",
      "listen": "tcp://*:80",
      "loopback": "ipc:///tmp/loopback",
      "shutdown_seconds": 1,
      "timeout_seconds": -1
    }
  },
  "loki": {
    "actions": [
      "locate",
      "route",
      "height",
      "sources_to_targets",
      "optimized_route",
      "isochrone",
      "trace_route",
      "trace_attributes",
      "transit_available",
      "expansion",
      "centroid",
      "status"
    ],
    "logging": {
      "color": true,
      "file_name": "/var/log/valhalla-loki.log",
      "long_request": 100.0,
      "type": "std_out"
    },
    "service": {
      "proxy": "ipc:///tmp/loki"
    },
    "service_defaults": {
      "heading_tolerance": 60,
      "minimum_reachability": 50,
      "node_snap_tolerance": 5,
      "radius": 0,
      "search_cutoff": 35000,
      "street_side_max_distance": 1000,
      "street_side_tolerance": 5
    },
    "use_connectivity": true
  },
  "meili": {
    "auto": {
      "search_radius": 50,
      "turn_penalty_factor": 200
    },
    "bicycle": {
      "turn_penalty_factor": 140
    },
    "customizable": [
      "mode",
      "search_radius",
      "turn_penalty_factor",
      "gps_accuracy",
      "interpolation_distance",
      "sigma_z",
      "beta",
      "max_route_distance_factor",
      "max_route_time_factor"
    ],
    "default": {
      "beta": 3,
      "breakage_distance": 2000,
      "geometry": false,
      "gps_accuracy": 5.0,
      "interpolation_distance": 10,
      "max_route_distance_factor": 5,
      "max_route_time_factor": 5,
      "max_search_radius": 100,
      "route": true,
      "search_radius": 50,
      "sigma_z": 4.07,
      "turn_penalty_factor": 0
    },
    "grid": {
      "cache_size": 100240,
      "size": 500
    },
    "logging": {
      "color": true,
      "file_name": "/var/log/valhalla-meili.log",
      "type": "std_out"
    },
    "mode": "auto",
    "multimodal": {
      "turn_penalty_factor": 70
    },
    "pedestrian": {
      "search_radius": 50,
      "turn_penalty_factor": 100
    },
    "service": {
      "proxy": "ipc:///tmp/meili"
    },
    "verbose": false
  },
  "mjolnir": {
    "admin": "/opt/valhalla-data/admin.sqlite",
    "data_processing": {
      "allow_alt_name": false,
      "apply_country_overrides": true,
      "infer_internal_intersections": true,
      "infer_turn_channels": true,
      "scan_tar": false,
      "use_admin_db": true,
      "use_direction_on_ways": false,
      "use_rest_area": false,
      "use_urban_tag": false
    },
    "global_synchronized_cache": false,
    "hierarchy": true,
    "id_table_size": 1300000000,
    "import_bike_share_stations": false,
    "include_bicycle": true,
    "include_construction": false,
    "include_driveways": true,
    "include_driving": true,
    "include_pedestrian": true,
    "include_platforms": false,
    "logging": {
      "color": true,
      "file_name": "/var/log/valhalla-mjolnir.log",
      "type": "std_out"
    },
    "lru_mem_cache_hard_control": false,
    "max_cache_size": 1000000000,
    "max_concurrent_reader_users": 1,
    "reclassify_links": true,
    "shortcuts": true,
    "tile_dir": "/opt/valhalla-data/tiles",
    "tile_extract": "/opt/valhalla-data/tiles.tar",
    "timezone": "/opt/valhalla-data/timezones.sqlite",
    "traffic_extract": "/opt/valhalla-data/traffic.tar",
    "transit_dir": "/opt/valhalla-data/transit",
    "transit_feeds_dir": "/opt/valhalla-data/transit_feeds",
    "transit_pbf_limit": 20000,
    "use_lru_mem_cache": false,
    "use_simple_mem_cache": false
  },
  "odin": {
    "logging": {
      "color": true,
      "file_name": "/var/log/valhalla-odin.log",
      "type": "std_out"
    },
    "markup_formatter": {
      "markup_enabled": false,
      "phoneme_format": "<TEXTUAL_STRING> (<span class=<QUOTES>phoneme<QUOTES>>/<VERBAL_STRING>/</span>)"
    },
    "service": {
      "proxy": "ipc:///tmp/odin"
    }
  },
  "service_limits": {
    "auto": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_location_pairs": 2500
    },
    "bicycle": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 200000.0,
      "max_matrix_location_pairs": 2500
    },
    "bikeshare": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 200000.0,
      "max_matrix_location_pairs": 2500
    },
    "bus": {
      "max_distance": 5000000.0,
      "max_locations": 50,
      "max_matrix_distance": 400000.0,
      "max_matrix_location_pairs": 2500
    },
    "centroid": {
      "max_distance": 200000.0,
      "max_locations": 5
    },
    "isochrone": {
      "max_contours": 4,
      "max_distance": 25000.0,
      "max_distance_contour": 200,
      "max_locations": 1,
      "max_time_contour": 120
    },
    "max_alternates": 2,
    "max_distance_disable_hierarchy_culling": 0,
    "max_exclude_locations": 50,
    "max_exclude_polygons_length": 10000,
    "max_radius": 200,
    "max_reachability": 100,
    "max_timedep_distance": 500000,
    "max_timedep_distance_matrix": 0,
    "motor_scooter": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 200000.0,
      "max_matrix_location_pairs": 2500
    },
    "motorcycle": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 200000.0,
      "max_matrix_location_pairs": 2500
    },
    "multimodal": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 0.0,
      "max_matrix_location_pairs": 0
    },
    "pedestrian": {
      "max_distance": 250000.0,
      "max_locations": 50,
      "max_matrix_distance": 200000.0,
      "max_matrix_location_pairs": 2500,
      "max_transit_walking_distance": 10000,
      "min_transit_walking_distance": 1
    },
    "skadi": {
      "max_shape": 750000,
      "min_resample": 10.0
    },
    "status": {
      "allow_verbose": false
    },
    "taxi": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_location_pairs": 2500
    },
    "trace": {
      "max_alternates": 3,
      "max_alternates_shape": 100,
      "max_distance": 200000.0,
      "max_gps_accuracy": 100.0,
      "max_search_radius": 100.0,
      "max_shape": 16000
    },
    "transit": {
      "max_distance": 500000.0,
      "max_locations": 50,
      "max_matrix_distance": 200000.0,
      "max_matrix_location_pairs": 2500
    },
    "truck": {
      "max_distance": 5000000.0,
      "max_locations": 20,
      "max_matrix_distance": 400000.0,
      "max_matrix_location_pairs": 2500
    }
  },
  "statsd": {
    "port": 8125,
    "prefix": "valhalla"
  },
  "thor": {
    "clear_reserved_memory": false,
    "extended_search": false,
    "logging": {
      "color": true,
      "file_name": "/var/log/valhalla-thor.log",
      "long_request": 110.0,
      "type": "std_out"
    },
    "max_reserved_labels_count_astar": 2000000,
    "max_reserved_labels_count_bidir_astar": 1000000,
    "max_reserved_labels_count_bidir_dijkstras": 2000000,
    "max_reserved_labels_count_dijkstras": 4000000,
    "service": {
      "proxy": "ipc:///tmp/thor"
    },
    "source_to_target_algorithm": "select_optimal"
  }
}
```

**Comment by nilsnolde** [comment]
Can you try the valhalla_build_extract tool? It adds an index.bin. I can’t imagine that it‘s broken for way you do it, but still good to make sure. Also, can you try to leave out the tar entirely and work off the plain tile dir?

If nothing else works, you could upload a tiny extract of your tarball, also valhalla_build_extract can be used for that, see its „—help“.

**Comment by coogle** [comment]
Btw I'd be happy to give you access to this machine as it's just being used for this if you want to reach out with an SSH key.

**Comment by coogle** [comment]
Just to close the loop on your other comment:

> It's likely not a OSM problem, I build the planet on a daily basis for the public server. Might be an extract problem with north america, but also that seems unlikely. Can't tell what the problem might be. You'll likely have to go in there, build debug and breakpoint into the code.

It's been awhile since I've had to fire up `gdb` so any details you could provide there would be helpful. I'm happy to give it a go -- is there a particular thing you're looking for I can provide?

**Comment by coogle** [comment]
I tried removing the `tiles.tar` file and running a route and I got something new:

```
valhalla_service conf/valhalla.json route '{"locations":[{"lat":41.688980,"lon":-87.644064},{"lat":42.338583,"lon":-83.325412}],"costing":"auto"}'
2023/11/17 18:32:33.41820 [ERROR] (stat): /opt/valhalla-data/tiles.tar No such file or directory
2023/11/17 18:32:33.41830 [WARN] Tile extract could not be loaded
2023/11/17 18:32:33.41833 [WARN] (stat): /valhalla-data/traffic.tar No such file or directory
2023/11/17 18:32:33.41835 [WARN] Traffic tile extract could not be loaded
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::ptree_bad_path>'
  what():  No such node (service_limits.max_distance_disable_hierarchy_culling.max_locations)
Aborted (core dumped)
```

I am going to run the extract now but that'll be awhile.

**Comment by nilsnolde** [comment]
Async might be better. It's super busy these days, not sure when someone will really get the time to look into it. It's also not happening for anyone else, which suggests some very specific fault. With a tiny extract (as tar.gz) we can have 5 mins whenever it fits in to have a look.

How about building another region? E.g. Andorra builds within seconds.

**Comment by coogle** [comment]
I appreciate you're busy, I was just offering if it would help as I've been literally struggling trying to build this thing on and off for about a month now and have never succeeded in getting anything useful from it. I really want it to work though, so I keep trying!

**Comment by nilsnolde** [comment]
If you need help on this on short notice, you can write me on enquiry@gis-ops.com for commercial support. I'm not very convinced this is a Valhalla problem, but in any case, that way I could easier make time for this.

**Comment by coogle** [comment]
I ran `valhalla-extract-tiles --config conf/valhalla.json -vv` and it produced the following:

```
2023-11-17 18:38:55,150 DEBUG: Adding tile 2/000/992/631.gph to the path
2023-11-17 18:38:55,151 DEBUG: Adding tile 2/000/994/069.gph to the path
2023-11-17 18:38:55,152 DEBUG: Adding tile 2/000/994/070.gph to the path
2023-11-17 18:38:55,153 DEBUG: Adding tile 2/000/994/071.gph to the path
2023-11-17 18:43:51,100  INFO: Finished tarring 28572 tiles to /opt/valhalla-data/tiles.tar
```

It produced a new `tiles.tar` file... which wasn't quite the same size as the one I produced:

```
-rw-r--r--  1 root root    34963456 Nov 14 21:10 admin.sqlite
drwxr-xr-x  2 root root        4096 Nov 17 18:25 conf
-rw-r--r--  1 root root          68 Nov 16 00:22 duplicateways.txt
drwxr-xr-x 61 root root        4096 Nov 16 17:55 elevation
-rw-r--r--  1 root root 13817444083 Oct 25 11:29 north-america-latest.osm.pbf
drwxr-xr-x  5 root root        4096 Nov 16 15:47 tiles
-rw-r--r--  1 root root 18290350592 Nov 17 18:31 tiles-old.tar
-rw-r--r--  1 root root 18902466560 Nov 17 18:43 tiles.tar
-rw-r--r--  1 root root    97624064 Nov 14 21:12 timezones.sqlite
```

I tried running a route, and I got the same crash I got before I posted about in an earlier ticket

```
valhalla_service conf/valhalla.json route '{"locations":[{"lat":41.688980,"lon":-87.644064},{"lat":42.338583,"lon":-83.325412}],"costing":"auto"}'
2023/11/17 18:46:07.54581 [INFO] Tile extract successfully loaded with tile count: 28572
2023/11/17 18:46:07.54845 [WARN] (stat): /valhalla-data/traffic.tar No such file or directory
2023/11/17 18:46:07.54847 [WARN] Traffic tile extract could not be loaded
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::ptree_bad_path>'
  what():  No such node (service_limits.max_distance_disable_hierarchy_culling.max_locations)
Aborted (core dumped)
```

As for commercial support, I can't justify that expense right now because I quite literally have never seen it working in my own environments. If we can get this up and running enough that we can actually use it in our stack, then certainly we'll want to discuss getting some commercial support in place. 

I can appreciate you don't think this is a Valhalla problem, but at every turn I've done what has been asked and I still can't get a single request to work. I've shown all my steps here as well, and no one can seem to find a problem with them, either. I'm not on a short notice clock, per se, as we can make due with OSRM and just disable Isochrone for now.. but I'd really love to crack this nut so I can consolidate the stack under Valhalla... assuming I can ever get it to work.

I've attached a small tarball of my tiles as well, generated using:

```
valhalla_build_extract --config conf/valhalla.json --bbox -68.96,45.13,-68.59,45.42
```

[tiles.tar.gz](https://github.com/valhalla/valhalla/files/13395547/tiles.tar.gz)

**Comment by kevinkreiser** [comment]
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::ptree_bad_path>'
  what():  No such node (service_limits.max_distance_disable_hierarchy_culling.max_locations)
Aborted (core dumped)
```

that is telling you that the config file you are using doesnt match the version of valhalla that you are running. that config arg is pretty new so probably your config file is just old.

**Comment by nilsnolde** [comment]
I actually did check the tiles and seems they're broken in some horrible way. Valhalla can't really read them, it can't find edges or nodes. It could be a corrupted up-/download, but likely not, since you're having trouble too. Not sure how that can happen on your side.. I can only recommend using another machine and/or try https://github.com/gis-ops/docker-valhalla.

**Comment by coogle** [comment]
Okay, I'm glad to hear at least it's not just me. I shot you an email to discuss further -- but I also don't want to leave this ticket swinging in the wind in case someone from Google comes along and finds it hoping for answers.

If I understand correctly, it seems that `valhalla-build-extract` is -- on my machine at least -- not producing correct tile files from the `.pbf` file I have? Am I understanding the problem correctly?

**Comment by nilsnolde** [comment]
We resolved this, it was an OOM in the end.
