### ISSUE TITLE
Valhalla Unresponsive, Bad Tiles?

### ISSUE THREAD

**Issue by coogle** [valhalla/valhalla#4399]
This is an add-on to #4398 which was closed prematurely presuming it was a duplicate bug.

I have found that no matter what I try to do, I can't get Valhalla not to hang. I have tried builds `dev`, `3.4.0`, `3.3.0`, `3.2.1` without success -- for `3.2.1` I tried both `isochrone` and `route` requests and the result is always the same -- an infinite loop / hang.

I have also tried the latest docker container with `route` and found the same problem.

Is there anything else I can try here to understand what's wrong? My natural thought leads me to this being a data problem now but I'd expect if that was the case there'd be some sort of error... this is with the latest North America data set:

```
-rw-r--r--  1 root root     34963456 Nov 14 21:10 admin.sqlite
drwxr-xr-x  2 root root         4096 Nov 17 17:11 conf
-rw-r--r--  1 root root           68 Nov 16 00:22 duplicateways.txt
drwxr-xr-x 61 root root         4096 Nov 16 17:55 elevation
-rw-r--r--  1 root root  13817444083 Oct 25 11:29 north-america-latest.osm.pbf
drwxr-xr-x  5 root root         4096 Nov 16 15:47 tiles
-rw-r--r--  1 root root 126381864960 Nov 16 17:30 tiles.tar
-rw-r--r--  1 root root     97624064 Nov 14 21:12 timezones.sqlite
```

**Comment by nilsnolde** [comment]
Ah you wrote it here.. Can we please keep things in one place, i.e. either close this or #4398, they're both the same.

It's likely not a OSM problem, I build the planet on a daily basis for the public server. Might be an extract problem with north america, but also that seems unlikely. Can't tell what the problem might be. You'll likely have to go in there, build debug and breakpoint into the code.

**Comment by coogle** [comment]
Since you reopened the original ticket we can close this one.
