### ISSUE TITLE
Hazmat ignored for truck routing

### ISSUE THREAD

**Issue by radekvermirovsky** [valhalla/valhalla#4401]
Hello, we've distilled an example of a truck route that does not adhere to hazmat restrictions.

On the route provided [https://valhalla.openstreetmap.de/directions?profile=truck&wps=15.272970199584963%2C49.57237520373628%2C14.960396289825441%2C49.75913196660811](url) there is a bridge with hazmat restrictions.

You can verify this using Overpass Turbo [https://overpass-turbo.eu/#](url) with the following script:

`[out:json][timeout:25];
// adjust the search radius (in meters) here
{{radius=1000}}
// gather results
nwr["hazmat"="no"](around:{{radius}},{{geocodeCoords:Vojslavický most}});
// print results
out geom;`

Even when we set up a route for a truck with hazardous materials, the route remains the same, as illustrated in the image below:

<img width="1771" alt="image" src="https://github.com/valhalla/valhalla/assets/149080356/ec2bc4fc-8df7-458d-a838-baa2ec1a830b">

Is this somehow related to the fact that this route is possibly part of a shortcut, and thus the hazmat restriction is not being respected?

**Comment by nilsnolde** [comment]
> Is this somehow related to the fact that this route is possibly part of a shortcut, and thus the hazmat restriction is not being respected?

Jep that's right!

**Comment by radekvermirovsky** [comment]
@nilsnolde I attempted to locate an already opened issue concerning the separation of shortcuts based on truck restrictions, but my search was unsuccessful. From my perspective, it seems that truck routing in Valhalla is currently facing challenges. IMHO effective truck routing heavily relies on accurate restriction handling, encompassing factors like height, weight, hazmat, and destination-only parameters. This not working on shortcuts is big deal for us. If i am getting this right it means that truck routing on paths with shortcuts is just simple car routing with different speeds.

I acknowledge the complexity of implementing such improvements without significant overhauls and potential performance impacts, if feasible at all. Could you please direct me to any existing issues addressing this matter? If there isn't one, would it be appropriate to close this issue (because now is more like by design than bug ), or should I await the creation of a related issue and corresponding pull request? I dont think that i am experienced enough to properly  open such complicated issue. Thx

**Comment by kevinkreiser** [comment]
there is another one and I have a pr open to fix it. havent had time  for it #4326

**Comment by radekvermirovsky** [comment]
@nilsnolde we tested this route with valhalla with [#4326 ](https://github.com/valhalla/valhalla/pull/4326) merged. We build new tiles so new functionality in shortcuts builder kicks in but looks like it is not working...if we use locate on that bridge it says access_restriction: false...but there is hazmat=no in osm data so i would expect that access restriction should be true on that edge.

params for locate request

```json
{ "costing": "auto", 
  "verbose": true, 
  "locations": [ { "lon": 15.207297, "lat": 49.596072 } ] }
```
result is:

```json
[
    {
        "input_lon": 15.207297,
        "nodes": [],
        "input_lat": 49.596072,
        "edges": [
            {
                "live_speed": {},
                "correlated_lon": 15.207297,
                "side_of_street": "neither",
                "linear_reference": "KwrQqSNEs0EXBP6yAAEBSGs=",
                "percent_along": 0.41935,
                "outbound_reach": 50,
                "distance": 0.7,
                "edge_info": {
                    "speed_limit": 130,
                    "mean_elevation": null,
                    "shape": "ambr}Awng_\\j@bT|@ze@\\bg@k@tv@sAdt@",
                    "names": [
                        "D1",
                        "E 50",
                        "E 65",
                        "Vojslavický most"
                    ],
                    "bike_network": {
                        "mountain": false,
                        "local": false,
                        "regional": false,
                        "national": false
                    },
                    "way_id": 6109868
                },
                "edge": {
                    "sidewalk_left": false,
                    "sidewalk_right": false,
                    "lane_count": 2,
                    "stop_sign": false,
                    "sac_scale": "none",
                    "yield_sign": false,
                    "not_thru": false,
                    "forward": true,
                    "end_node": {
                        "value": 2485611684128,
                        "id": 74077,
                        "tile_id": 3108,
                        "level": 0
                    },
                    "truck_route": false,
                    "speeds": {
                        "predicted": false,
                        "constrained_flow": 0,
                        "free_flow": 0,
                        "type": "tagged",
                        "default": 130
                    },
                    "bike_network": false,
                    "round_about": false,
                    "traffic_signal": false,
                    "access_restriction": false,
                    "destination_only": false,
                    "geo_attributes": {
                        "curvature": 0,
                        "max_down_slope": 0.00,
                        "max_up_slope": 0.00,
                        "weighted_grade": 0.00,
                        "length": 242
                    },
                    "start_restriction": {
                        "truck": false,
                        "pedestrian": false,
                        "wheelchair": false,
                        "taxi": false,
                        "HOV": false,
                        "emergency": false,
                        "motorcycle": false,
                        "car": false,
                        "moped": false,
                        "bus": false,
                        "bicycle": false
                    },
                    "cycle_lane": "none",
                    "end_restriction": {
                        "truck": false,
                        "pedestrian": false,
                        "wheelchair": false,
                        "taxi": false,
                        "HOV": false,
                        "emergency": false,
                        "motorcycle": false,
                        "car": false,
                        "moped": false,
                        "bus": false,
                        "bicycle": false
                    },
                    "seasonal": false,
                    "country_crossing": false,
                    "part_of_complex_restriction": false,
                    "has_sign": false,
                    "access": {
                        "truck": true,
                        "pedestrian": false,
                        "wheelchair": false,
                        "taxi": true,
                        "HOV": true,
                        "emergency": false,
                        "motorcycle": true,
                        "car": true,
                        "moped": false,
                        "bus": true,
                        "bicycle": false
                    },
                    "bridge": true,
                    "classification": {
                        "internal": false,
                        "link": false,
                        "surface": "paved_smooth",
                        "use": "road",
                        "classification": "motorway"
                    },
                    "toll": true,
                    "tunnel": false
                },
                "heading": 267.9,
                "inbound_reach": 50,
                "correlated_lat": 49.596066,
                "edge_id": {
                    "value": 5808473530656,
                    "id": 173106,
                    "tile_id": 3108,
                    "level": 0
                },
                "predicted_speeds": []
            }
        ]
    }
]
```

**Comment by nilsnolde** [comment]
Those kind of access restrictions are not getting serialized yet, see https://github.com/valhalla/valhalla/pull/4431. Also you’re calling it with car costing.
