### ISSUE TITLE
CostMatrix fails on trivial routes

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4433]
On trivial routes, the CostMatrix fails to connect on the correct edge. It always chooses the wrong direction it seems. Not sure yet if that's consistent, but seems so.

Found when working on #4432

**Comment by nilsnolde** [comment]
closing in favor of #4538

**Comment by nilsnolde** [comment]
this is referenced in the code and I realized I closed this prematurely. it has nothing to do with oneways, it's just confused about which directed edge is the right one. however, that's also affecting the results, it'll report the cost/time of the wrong edge, see https://github.com/valhalla/valhalla/pull/4634

**Comment by chrstnbwnkl** [comment]
I had a quick look, but haven't gotten very far. I just noticed that it doesn't _always_ connect on the wrong edge. In the example test in #4634 if you switch source and target, you'll see that it actually connects via the backward edge.

**Comment by chrstnbwnkl** [comment]
Fixed in #4634 and #5001
