### ISSUE TITLE
Enhancement request to create optimized route from existing legs

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#444]
(2016-10-20T23:41:05Z) @rmglennon : originally created valhalla/thor#456

This came in through email support, and adding it here to be tracked: 

User says: "I love your routing service and like to use it in a big project. The only thing I am missing is documentation / references to load a ‘plan’ based on legs (a custom route I earlier mad), rather than on just waypoints."

We think this means making an optimized route based off of already made legs of a trip, rather than waypoints. Currently this is not possible because you need all pairs to do the optimization. If 
you already have the pairs, then you can do simulated annealing algorithm to pick the 'optimal' sequence.

(2016-10-24T16:59:41Z) @dnesbitt61 : Not sure what this request means. 

(2016-10-24T20:29:52Z) @kevinkreiser : As you pointed out, you cant optimize the legs of an already made route, the optimization of a set of locations can only occur once you know the cost between all pairs of those locations. If you only have the `legs` of a previous route then you cannot optimize it because you don't have enough information. In order to optimize you must first compute the `matrix` of all possible pairs of locations. You can then find the minimum cost permutation of that set using simulated annealing. If the user wants to submit a matrix and get back an optimized route that is possible. But no optimization can be done on a route which only has legs: A->B, B->C ... Y->Z there simply isnt enough information.

**Comment by dnesbitt61** [comment]
I have no idea what this issue means. Closing this issue - if we get further information/requests can re-open.
