### ISSUE TITLE
Failed to build GraphTile. Error: GraphId level exceeds tile hierarchy max level

### ISSUE THREAD

**Issue by sonikq** [valhalla/valhalla#4441]
Hello, I am using a library to convert .osm.pbf file, golang lib: https://github.com/grab/gosm.
I set the following headers: OsmSchema-V0.6, DenseNodes.
I get this error when docker run -dt --name valhalla_gis-ops -p 8002:8002 -v $PWD/custom_files:/custom_files ghcr.io/gis-ops/docker-valhalla/valhalla:latest: [ERROR] Failed to build GraphTile. Error: GraphId level exceeds tile hierarchy max level
I am attaching the container logs:
INFO: Running container with user valhalla UID 59999 and GID 59999.

WARNING: Hash not found for: /custom_files/output.osm.pbf!
WARNING: No routing tiles found at /custom_files/valhalla_tiles.tar or /custom_files/valhalla_tiles, starting a new build
find: '/custom_files/transit_tiles': No such file or directory
INFO: Running build tiles with: /custom_files/valhalla.json /custom_files/output.osm.pbf

============================
= Build the initial graph. =
============================
2023/12/09 14:00:54.048309 [INFO] Running valhalla_build_tiles with 8 thread(s).
2023/12/09 14:00:54.048376 [INFO] Start stage = initialize End stage = build
2023/12/09 14:00:54.051675 [INFO] Parsing files for ways: /custom_files/output.osm.pbf
2023/12/09 14:00:54.052151 [INFO] Parsing ways...
2023/12/09 14:00:56.015759 [INFO] Added 0 culdesac roundabouts from 0 candidates.
2023/12/09 14:00:56.015809 [INFO] Finished with 0 routable ways containing 0 nodes
2023/12/09 14:00:56.015853 [INFO] Sorting osm access tags by way id...
2023/12/09 14:00:56.015889 [INFO] Finished
2023/12/09 14:00:56.016057 [INFO] Write OSMData to temp files
2023/12/09 14:00:56.016728 [INFO] Done
2023/12/09 14:00:56.018175 [INFO] Parsing files for relations: /custom_files/output.osm.pbf
2023/12/09 14:00:56.018457 [INFO] Parsing relations...
2023/12/09 14:00:56.807807 [INFO] Finished with 0 simple restrictions
2023/12/09 14:00:56.807848 [INFO] Finished with 0 lane connections
2023/12/09 14:00:56.807885 [INFO] Sorting complex restrictions by from id...
2023/12/09 14:00:56.807943 [INFO] Sorting complex restrictions by to id...
2023/12/09 14:00:56.807983 [INFO] Finished
2023/12/09 14:00:56.808162 [INFO] Write OSMData to temp files
2023/12/09 14:00:56.808883 [INFO] Done
2023/12/09 14:00:56.810647 [INFO] Parsing files for nodes: /custom_files/output.osm.pbf
2023/12/09 14:00:56.810690 [INFO] Sorting osm way node references by node id...
2023/12/09 14:00:56.810741 [INFO] Parsing nodes...
2023/12/09 14:00:58.770064 [INFO] Finished with 0 nodes contained in routable ways
2023/12/09 14:00:58.770106 [INFO] Sorting osm way node references by way index and node shape index...
2023/12/09 14:00:58.770175 [INFO] Finished: max_osm_id 251812420741428761
2023/12/09 14:00:58.770179 [INFO] Number of nodes with refs (exits) = 0
2023/12/09 14:00:58.770181 [INFO] Number of nodes with exit_to = 0
2023/12/09 14:00:58.770183 [INFO] Number of nodes with names = 0
2023/12/09 14:00:58.770185 [INFO] Number of way refs = 0
2023/12/09 14:00:58.770187 [INFO] Number of reverse way refs = 0
2023/12/09 14:00:58.770189 [INFO] Unique Node Strings (names, refs, etc.) = 0
2023/12/09 14:00:58.770191 [INFO] Unique Strings (names, refs, etc.) = 0
2023/12/09 14:00:58.770363 [INFO] Write OSMData to temp files
2023/12/09 14:00:58.770964 [INFO] Done
2023/12/09 14:00:58.771024 [INFO] Creating graph edges from ways...
2023/12/09 14:00:58.771493 [INFO] Finished with 0 graph edges
2023/12/09 14:00:58.771559 [INFO] Sorting graph...
2023/12/09 14:00:58.771640 [INFO] Nodes processed. Sorting begin and end nodes by edge.
2023/12/09 14:00:58.771672 [INFO] Sorting begin and end nodes done. Populating edges...
2023/12/09 14:00:58.771776 [INFO] Finished with 0 graph nodes
2023/12/09 14:00:58.771866 [INFO] Writing tile manifest to /custom_files/valhalla_tiles/tile_manifest.json
2023/12/09 14:00:58.771905 [INFO] Reclassifying_V2 link graph edges...
2023/12/09 14:00:58.771968 [INFO] Class: 0 exit count = 0
2023/12/09 14:00:58.771989 [INFO] Class: 1 exit count = 0
2023/12/09 14:00:58.771992 [INFO] Class: 2 exit count = 0
2023/12/09 14:00:58.771994 [INFO] Class: 3 exit count = 0
2023/12/09 14:00:58.771996 [INFO] Class: 4 exit count = 0
2023/12/09 14:00:58.771998 [INFO] Class: 5 exit count = 0
2023/12/09 14:00:58.772000 [INFO] Class: 6 exit count = 0
2023/12/09 14:00:58.772002 [INFO] Class: 7 exit count = 0
2023/12/09 14:00:58.772006 [INFO] Finished with 0 reclassified.  Turn channel count = 0
2023/12/09 14:00:58.772048 [INFO] Reclassifying ferry connection graph edges...
2023/12/09 14:00:58.772083 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 0, 0 edges reclassified. Failed both directions for 0 connections.
2023/12/09 14:00:58.811386 [INFO] Building 0 tiles with 8 threads...
2023/12/09 14:00:58.813912 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.813956 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.816690 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.816729 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.818849 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.818882 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.820369 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.820403 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.820593 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.820627 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.821332 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.821362 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.821626 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.821659 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.822171 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.822200 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023/12/09 14:00:58.822335 [INFO] Finished
2023/12/09 14:00:58.822735 [INFO] Node Count = 0
2023/12/09 14:00:58.822776 [INFO] Directed Edge Count = 0
2023/12/09 14:00:58.822780 [INFO] EdgeInfo Count = 0

===============================
= Enhancing the initial graph =
===============================
2023/12/09 14:00:58.877348 [INFO] Running valhalla_build_tiles with 8 thread(s).
2023/12/09 14:00:58.877643 [INFO] Start stage = enhance End stage = cleanup
2023/12/09 14:00:58.877736 [INFO] Read OSMData unique_names from temp file
2023/12/09 14:00:58.877783 [INFO] Done
2023/12/09 14:00:58.877790 [INFO] Enhancing local graph...
2023/12/09 14:00:58.882080 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.882079 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.882153 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.882096 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.883815 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.884699 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.885886 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.890262 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023/12/09 14:00:58.893849 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.895136 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.897324 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.898012 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.898502 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.899355 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.899420 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.901097 [INFO] Disabled default speeds assignment from config
2023/12/09 14:00:58.901348 [INFO] Finished with max_density 0.000000
2023/12/09 14:00:58.901372 [INFO] internal intersection = 0
2023/12/09 14:00:58.901506 [INFO] GraphFilter - nothing to filter. Skipping...
2023/12/09 14:00:58.901576 [INFO] Transit directory not found. Transit will not be added.
2023/12/09 14:00:58.901597 [INFO] HierarchyBuilder
2023/12/09 14:00:59.371493 [INFO] --Forward restrictions added: 0
2023/12/09 14:00:59.371519 [INFO] --Reverse restrictions added: 0
2023/12/09 14:00:59.371526 [INFO] Finished
2023/12/09 14:00:59.371538 [INFO] Validating, finishing and binning tiles...
2023/12/09 14:00:59.372334 [ERROR] Failed to build GraphTile. Error: GraphId level exceeds tile hierarchy max level
/valhalla/scripts/configure_valhalla.sh: line 210:    52 Segmentation fault      valhalla_build_tiles -c ${CONFIG_FILE} -s enhance ${files}

And for some reason I can’t find points and paths, although when I converted to xml they were there.

**Comment by ImreSamu** [comment]
> Hello, I am using a library to convert .osm.pbf file, golang lib 
> ... 
> ... [ERROR] Failed to build GraphTile. Error: GraphId level exceeds tile hierarchy max level

The issue you are experiencing with the Valhalla routing engine is likely due to improper input data, 
as commonly seen in this GitHub issue:  https://github.com/valhalla/valhalla/issues/4294 
I suggest investigating this as the potential cause of the problem.

Although I am not familiar with the Golang library you mentioned, the issue may stem from the internal consistency of the data (specifically, incorrect routing topology based on OSM tagging) rather than its structural format.

If you are converting a road network from another source to OSM, it is advisable to:
- Carefully examine the OSM XML file to ensure it contains the correct highway tags and that the connecting nodes are properly defined.
- Perform various checks using tools like:
    -  Osmium Check Refs : https://docs.osmcode.org/osmium/latest/osmium-check-refs.html
    - The Validator in the JOSM editor: https://wiki.openstreetmap.org/wiki/JOSM/Validator
    
These steps should help in identifying and resolving any issues with the data used in the Valhalla routing engine.

**Comment by nilsnolde** [comment]
Agreed. If you play around with the input data in curious ways, you should first make sure that the resulting data is even valid. Standard OSM data doesn't do this, neither properly converted OSM files (I do that a lot too, from both TomTom & HERE).

**Comment by neverset123** [comment]
> Agreed. If you play around with the input data in curious ways, you should first make sure that the resulting data is even valid. Standard OSM data doesn't fail like this, neither properly converted OSM files (I do that a lot too, from both TomTom & HERE).

 I am currently tryign to build valhalla graph from HERE map, do you have any tool suggestion on this? would it be better to convert it to osm file and using exiting tools for osm or would it be better to rewrite the graph_build tool?

**Comment by nilsnolde** [comment]
I had a commercial tool to convert into osm (yeah that's definitely the best and easiest way). The HERE implementation is not terribly well tested, all of my past clients wanted TomTom, which I'd also still recommend generally. Contact me on my private email if you want more information, pricing etc. It's a very good starting point but might some additional code to convert more features types (written in python).

**Comment by neverset123** [comment]
> ome additional code to c

OK, emailed to nilsnolde@proton.me

**Comment by neverset123** [comment]
> I had a commercial tool to convert into osm (yeah that's definitely the best and easiest way). The HERE implementation is not terribly well tested, all of my past clients wanted TomTom, which I'd also still recommend generally. Contact me on my private email if you want more information, pricing etc. It's a very good starting point but might some additional code to convert more features types (written in python).

@nilsnolde I actually only need the map matching parting of valhalla (Meili), in the meantime I took a look at graph.lua file in this repo, it seems that quite a lot of attributes are integrated in the graph construction. Are all these attributes really needed for map matching with Meili, how much will it effect the result if I only integrate node ids and directions in a simplified graph building?

**Comment by neverset123** [comment]
or maybe @ptpt  could offer some opinion on how to utilize Meili on a simplified graph built from other map source(not OSM) easily? as building graphs for whole valhalla is really heavy

**Comment by chrstnbwnkl** [comment]
There's currently no easy way to reduce the data structures stored in the graph to what you deem necessary. If by heavy you mean time it takes to build a whole planet then there's little you can do apart from throwing better hardware at the problem 😄 

if you want to reduce the final size of your graph, and you don't care about e.g. bicycle routing then there are options to throw out edges you won't be needing.

**Comment by chrstnbwnkl** [comment]
One idea that does come to mind is to come up with a converter that instead of converting HERE (or whatever proprietary data) to OSM protobuf, you could directly write to the temporary data structures that Valhalla converts the OSM data to during the graph build. Then you would immediately skip the first stage of the graph build.

The downside is these structures are kind of an implementation detail, so they're not well documented and you have to delve into the source code to figure out what Valhalla expects 😄
