### ISSUE TITLE
 The node has not initialized coordinates.

### ISSUE THREAD

**Issue by sonikq** [valhalla/valhalla#4444]
Hi, please tell me why this problem occurs:
2023/12/09 19:14:50.108770 [WARN] Node 189693758982344207 in way 15187653 has not had coordinates initialized
2023/12/09 19:14:50.108773 [WARN] Node 189702417636414826 in way 15187653 has not had coordinates initialized
2023/12/09 19:14:50.108775 [WARN] Node 189721830888590758 in way 15187653 has not had coordinates initialized
2023/12/09 19:14:50.108779 [WARN] Do not add edge!
2023/12/09 19:14:50.108786 [INFO] Finished with 0 graph edges

I run it like this: docker run -dt --name valhalla_gis-ops -p 8002:8002 -v $PWD/custom_files:/custom_files ghcr.io/gis-ops/docker-valhalla/valhalla:latest

Converted pbf to xml and checked these nodes - they are there!

**Comment by nilsnolde** [comment]
That usually means that those nodes weren't included as `<node>`, but referenced with their ID in the ways. It triggers when the lat/lon is invalid: https://github.com/valhalla/valhalla/blob/497507f325131f22d8d006fe1b1fb6361a4acb2b/src/mjolnir/graphbuilder.cc#L182-L184

**Comment by nilsnolde** [comment]
It can happen when extracting smth from an existing PBF with `osmium` and the strategy is `simple`. Other than that it can of course happen if a synthetic PBF is screwed up:)

**Comment by sonikq** [comment]
Please tell me, are the latitude and longitude indicated here incorrectly?

<node id="189693758982344207" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.20815" lon="42.14287"/>

<way id="15187653" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1">
    <nd ref="189693758982344207"/>
    <nd ref="189702417636414826"/>
    <nd ref="189721830888590758"/>
  </way>

**Comment by sonikq** [comment]
Please tell me, are the latitude and longitude indicated here incorrectly?

<node id="189693758982344207" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.20815" lon="42.14287"/>
<way id="15187653" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1">
    <nd ref="189693758982344207"/>
    <nd ref="189702417636414826"/>
    <nd ref="189721830888590758"/>
  </way>

**Comment by sonikq** [comment]
Please tell me, are the latitude and longitude indicated here incorrectly?
"<node id="189693758982344207" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.20815" lon="42.14287"/>"

"<way id="15187653" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1">
    <nd ref="189693758982344207"/>
    <nd ref="189702417636414826"/>
    <nd ref="189721830888590758"/>
  </way>"

**Comment by sonikq** [comment]
Please tell me, are the latitude and longitude indicated here incorrectly?
`<node id="189693758982344207" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.20815" lon="42.14287"/>`
`<way id="15187653" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1">
    <nd ref="189693758982344207"/>
    <nd ref="189702417636414826"/>
    <nd ref="189721830888590758"/>
  </way>`

**Comment by nilsnolde** [comment]
you only show 1 out of 3 nodes..

**Comment by nilsnolde** [comment]
btw, those are pretty high IDs. note, some software will have problems with those, e.g. OSRM (though I realize you might use Valhalla :D but sometimes both are good to support for a single use case).

**Comment by sonikq** [comment]
Is this a complete example?
And do you think it’s better to make the id smaller?
`<node id="189693758982344207" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.20815" lon="42.14287"/>`
`<node id="189702417636414826" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.21067" lon="42.1617"/>`
`<node id="189721830888590758" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1" lat="55.21632" lon="42.14182"/>`
`<way id="15187653" version="-1" timestamp="1969-12-31T23:59:59Z" changeset="-1"> <nd ref="189693758982344207"/> <nd ref="189702417636414826"/> <nd ref="189721830888590758"/> </way>`

**Comment by sonikq** [comment]
Could there be a problem with the version, timestamp and changeset?

**Comment by kevinkreiser** [comment]
I mean we don't support osm xml format so the likelihood is still that the pbf you have is missing these nodes. as nils said you have ways that reference the nodes but the nodes themselves are missing in the pbf. you can dump the contents of the pbf with osmium-cat and use the debug output format just to verify

**Comment by nilsnolde** [comment]
And yeah I’d try to keep IDs as low as possible. If they are derived from another dataset which has node & way IDs (most commercial datasets), that might be less important. As I said some software assumes IDs to be less than 40 bits or so, some software will be MUCH more expensive to run with higher IDs, eg osmium extract.

**Comment by sonikq** [comment]
Thanks for the quick replies
I rechecked pbf again (both through xml conversion and through osmium) - it did not help, the error remained the same.
Sorry, of course, for such a request, but can I somehow send you the pbf - maybe you will find the error?

**Comment by nilsnolde** [comment]
I can help you if you want, but not for free. You can send an email to enquiry@gis-ops.com, we can talk about details there.

**Comment by ImreSamu** [comment]
> I rechecked pbf again (both through xml conversion and through osmium) - it did not help, the error remained the same.

In general:

The data model for routing in OpenStreetMap (OSM) requires much more interconnected data than a simple CSV, XML, or PBF file. It's advisable to study the OSM data of your area - to understand the structure and labeling of roads. Therefore, it's also worth learning how to edit OSM data (using tools like the iD Editor or JOSM) or seek training from a local OSM user, who can also assist in checking JOSM data.

If you are interested in the OSM data model (more broadly than just routing), it would be good to watch Jochen's presentation:
* https://www.youtube.com/watch?v=rbxabz22ni4

or check this :
* https://wiki.openstreetmap.org/wiki/OSM_Routing_Data_Layer ( -> see "The original OSM Data might look as following" )

( copy from the wiki )
```xml
<way id="1" >
   <nd ref="1"/>
   <nd ref="2"/>
   <nd ref="3"/>
   <nd ref="4"/>
   <tag k="oneway" v="yes"/>
   <tag k="highway" v="secondary"/>
 </way>
<way id="2" >
   <nd ref="8"/>
   <nd ref="3"/>
   <nd ref="5"/>
   <nd ref="6"/>
   <tag k="highway" v="residential"/>
 </way>
 
 .... 
 
 <node id="1" lat="51.674714" lon="8.3470936">
   ..
 </node>
...
<node id="11" lat="51.674716" lon="8.3470934"">
   ..
 </node>
...
<node id="12" lat="51.674719" lon="8.3470931">
   <tag k="highway" v="gate"/>
   <tag k="access" v="no"/>
 </node>
 
```

My general routing workflow advice: 
* 1.) renumber ids - with osmium tool  : https://docs.osmcode.org/osmium/latest/osmium-renumber.html 
* 2.) convert renumbered  .pbf to osm.xml - with osmium tool : https://docs.osmcode.org/osmium/latest/osmium-cat.html
* 3.) check osm.xml with the JOSM validator :  https://josm.openstreetmap.de/wiki/Help/Dialog/Validator  to find : 
  - Duplicated nodes
  - Duplicated way nodes
  - Incomplete ways
  - Crossing ways ( Checks for ways (with highway tags) that crosses in same layer with no crossing node )
  - Overlapping (high)ways	( Checks for two (high)ways that share the same nodes )
  - Self-intersecting ways ( A way intersects itself, possibly sharing same nodes )
  -  ...
*  4.) convert validated osm.xml to pbf ..
* 5.) test with valhalla 
* 6.) modify/fix your code  and generate new version.
* 7.)  GOTO --> 1.)

**Comment by nilsnolde** [comment]
closing as stale, feel free to re-open
