### ISSUE TITLE
504 gateway errors

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#445]
(2016-10-26T14:22:00Z) @ethervoid : originally created valhalla/thor#457

Hello!

In every job we start using your matrix API, we're getting 504 errors. They don't arise inmediately but after some requests we're getting 504 always.

Here are the most relevant data to trace it (we have many more if you need them): 

Request

```
https://matrix.mapzen.com/one_to_many?json=%7B%22locations%22%3A+%5B%7B%22lat%22%3A+41.38981%2C+%22lon%22%3A+2.13491%7D%2C+%7B%22lat%22%3A+41.3905823487937%2C+%22lon%22%3A+2.13491%7D%2C+%7B%22lat%22%3A+41.3905560313394%2C+%22lon%22%3A+2.135176453254571%7D%2C+%7B%22lat%22%3A+41.390478872528966%2C+%22lon%22%3A+2.135424747549251%7D%2C+%7B%22lat%22%3A+41.390356130775565%2C+%22lon%22%3A+2.1356379615909598%7D%2C+%7B%22lat%22%3A+41.39019617095601%2C+%22lon%22%3A+2.1358015650314264%7D%2C+%7B%22lat%22%3A+41.390009894296824%2C+%22lon%22%3A+2.1359044087302657%7D%2C+%7B%22lat%22%3A+41.38980999541225%2C+%22lon%22%3A+2.135939484506594%7D%2C+%7B%22lat%22%3A+41.38961009714231%2C+%22lon%22%3A+2.1359044026151355%7D%2C+%7B%22lat%22%3A+41.389423822162364%2C+%22lon%22%3A+2.135801554439711%7D%2C+%7B%22lat%22%3A+41.38926386463668%2C+%22lon%22%3A+2.1356379493607%7D%2C+%7B%22lat%22%3A+41.38914112517715%2C+%22lon%22%3A+2.1354247369575354%7D%2C+%7B%22lat%22%3A+41.389063968045946%2C+%22lon%22%3A+2.1351764471394414%7D%2C+%7B%22lat%22%3A+41.389037651206294%2C+%22lon%22%3A+2.13491%7D%2C+%7B%22lat%22%3A+41.389063968045946%2C+%22lon%22%3A+2.1346435528605587%7D%2C+%7B%22lat%22%3A+41.38914112517715%2C+%22lon%22%3A+2.1343952630424647%7D%2C+%7B%22lat%22%3A+41.38926386463668%2C+%22lon%22%3A+2.1341820506393003%7D%2C+%7B%22lat%22%3A+41.389423822162364%2C+%22lon%22%3A+2.1340184455602893%7D%2C+%7B%22lat%22%3A+41.389410185723904%2C+%22lon%22%3A+2.1329212008850402%7D%2C+%7B%22lat%22%3A+41.38980999541225%2C+%22lon%22%3A+2.1338805154934057%7D%2C+%7B%22lat%22%3A+41.390009894296824%2C+%22lon%22%3A+2.1339155912697345%7D%2C+%7B%22lat%22%3A+41.39019617095601%2C+%22lon%22%3A+2.1340184349685734%7D%2C+%7B%22lat%22%3A+41.390356130775565%2C+%22lon%22%3A+2.13418203840904%7D%2C+%7B%22lat%22%3A+41.390478872528966%2C+%22lon%22%3A+2.134395252450749%7D%2C+%7B%22lat%22%3A+41.3905560313394%2C+%22lon%22%3A+2.1346435467454286%7D%5D%7D&api_key=api_Key&costing=pedestrian
```

Timestamp: 1477491103 - 2016-10-26 16:11:43

(2016-10-26T14:39:46Z) @dnesbitt61 : We will try to look at logs. This particular request is trivial and there must be other requests that are filling the queues.  Are you running many_to_many matrices or mostly one_to_many?

(2016-10-26T14:41:36Z) @rafatower : Thanks, @dnesbitt61 We're running just `one_to_many` matrices.

(2016-10-26T14:50:25Z) @dnesbitt61 : What timezone is your timestamp? It just occurred to me that if this was GMT it is in the future! 

(2016-10-26T14:57:54Z) @ethervoid : We're using CEST

(2016-10-26T15:27:45Z) @kevinkreiser : looking at our system i'm having a tough time finding evidence that its happening! lets continue this thread in email. sending one with more details now!

**Comment by dnesbitt61** [comment]
Closing issue - cannot isolate. If problems continue let us know and we can try to isolate.
