### ISSUE TITLE
Leaflet and Valhalla web app routes issue

### ISSUE THREAD

**Issue by giuliac89** [valhalla/valhalla#4454]
I'm trying to integrate the Valhalla web app with Leaflet and I have some issues with drawing the right route. 
I want to create a pedestrian route so I call the api https://valhalla1.openstreetmap.de after creating the json.
The issues are:

1. The points are connected well, but the routes are not drawn correctly (they don't follow the street)
2. If I change the "costing" value nothing change

My resulting json is 
```
{
   "costing":"pedestrian",
   "locations":[
         {"lon":"14.207994","lat":"41.110242","type":"via"},
         {"lon":"14.208491","lat":"41.109895","type":"via"},
         {"lon":"14.211598","lat":"41.107943","type":"via"},
         {"lon":"14.211446","lat":"41.108951","type":"via"},
         {"lon":"14.212708","lat":"41.109952","type":"via"},
         {"lon":"14.213006","lat":"41.110424","type":"via"},
         {"lon":"14.212892","lat":"41.11096","type":"via"},
         {"lon":"14.213697929872753","lat":"41.10965172126981","type":"via"},
         {"lon":"14.217564","lat":"41.106637","type":"via"},
         {"lon":"14.2126","lat":"41.107311","type":"via"},
         {"lon":"14.207614599551142","lat":"41.10673799401134","type":"via"}
    ],
   "language":"it-IT",
   "id":"map_routes"
}
```

And the call is https://valhalla1.openstreetmap.de/route?json={"costing":"pedestrian","locations":[{"lon":"14.207994","lat":"41.110242","type":"via"},{"lon":"14.208491","lat":"41.109895","type":"via"},{"lon":"14.211598","lat":"41.107943","type":"via"},{"lon":"14.211446","lat":"41.108951","type":"via"},{"lon":"14.212708","lat":"41.109952","type":"via"},{"lon":"14.213006","lat":"41.110424","type":"via"},{"lon":"14.212892","lat":"41.11096","type":"via"},{"lon":"14.213697929872753","lat":"41.10965172126981","type":"via"},{"lon":"14.217564","lat":"41.106637","type":"via"},{"lon":"14.2126","lat":"41.107311","type":"via"},{"lon":"14.207614599551142","lat":"41.10673799401134","type":"via"}],"language":"it-IT","id":"map_routes"}

Then I draw the leaflet polyline with the result (that seems correct)
`L.polyline(result.trip.locations, {color: '#eb0000'}).addTo(map);`

<img width="761" alt="Screenshot 2023-12-13 alle 10 48 00" src="https://github.com/valhalla/valhalla/assets/25961895/3174641e-c506-4b90-a471-af30e252650b">

But I get this (it seems it doesn't follow the streets)

<img width="995" alt="Screenshot 2023-12-13 alle 09 56 12" src="https://github.com/valhalla/valhalla/assets/25961895/32334f96-7782-4745-b7a9-7ebef215d314">

I can't figure out what I'm doing wrong. Can you help me?

**Comment by kevinkreiser** [comment]
here's a smiple one i made a while ago. maybe its helpful to you: https://github.com/valhalla/demos/blob/1ffaba5c5cd23cebe28a6ace6319e3d2e12af967/routing/simple.html

the part of the response you want to render on the map is called `shape`. here you are just using the returned input `locations`. to use the shape you also need to decode it. but yeah if you look at my example above it shows how to do all this. its not too complicated!

**Comment by giuliac89** [comment]
Thank you! :)
