### ISSUE TITLE
"verbose" has no effect on /sources_to_targets API

### ISSUE THREAD

**Issue by paro-** [valhalla/valhalla#4470]
Hi,
According to the [doc](https://valhalla.github.io/valhalla/api/matrix/api-reference/), /sources_to_targets accepts a "verbose" flag enabling to reduce the output.
However, the following requests yield the same result:

- curl 'http://$VALHALLA_URL/sources_to_targets' -d '{"sources": [{"lat": 48.8553, "lon": 2.3377, "radius": 200}], "targets": [{"lat": 48.846, "lon": 2.3197, "radius": 200}, {"lat": 48.848, "lon": 2.3173, "radius": 200}, {"lat": 48.8434, "lon": 2.3165, "radius": 200}], "costing": "auto", "verbose": false}'
- curl 'http://$VALHALLA_URL/sources_to_targets' -d '{"sources": [{"lat": 48.8553, "lon": 2.3377, "radius": 200}], "targets": [{"lat": 48.846, "lon": 2.3197, "radius": 200}, {"lat": 48.848, "lon": 2.3173, "radius": 200}, {"lat": 48.8434, "lon": 2.3165, "radius": 200}], "costing": "auto", "verbose": true}'

Am I passing something wrong?
This would help us reduce network costs if it worked as advertised :ok_hand: 

Best regards,
Paul

**Comment by nilsnolde** [comment]
Looks all fine. Reminder: you need to try master, not any release.

**Comment by paro-** [comment]
Hi,
Thanks for the quick answer.
I'm running version "run-3.3.0", the latest release, does it mean the issue has been fixed and will be available in the next release?
Paul

**Comment by nilsnolde** [comment]
It has never been an issue:) you’re looking at docs of latest master, while you’re using a version that’s easily 1 year old. Long time we’re not hosting stuff at dockerhub anymore, and those -run images are even longer out of fashion IIRC. You’ll need to watch the repo to get notified. You latest image or at least latest release (3.4.0).

And no matter what you use, ALWAYS try latest master before filing an issue, it’s the only thing that matters. We never backport anything to previous releases.

**Comment by nilsnolde** [comment]
One indicator is to request against the public instance. If you do that, you’ll see it’s working.

**Comment by paro-** [comment]
Actually addresses in [#3987](https://github.com/valhalla/valhalla/pull/3987)
