### ISSUE TITLE
Add Warning to Overview Section on Docker Hub for valhalla/valhalla

### ISSUE THREAD

**Issue by ImreSamu** [valhalla/valhalla#4471]
Based on my understanding, 
we can update the overview on https://hub.docker.com/r/valhalla/valhalla to reflect recent changes. 

I suggest we prominently place a large "WARNING" notice at the beginning of the text, highlighting:
- This Docker repository is no longer receiving updates.
- The new containers are now available at ghcr.io. ( https://github.com/orgs/valhalla/packages )

**Comment by kevinkreiser** [comment]
good point
