### ISSUE TITLE
truck `speed` shouldn't always be derived from trafffic

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4472]
All traffic I know is car-specific and on higher class roads both historical & live traffic can be MUCH higher than any HGV legally allowed speed, in Germany it can > 140 kmh. IMO we shouldn't take any speed for HGV that's higher than any `maxspeed:hgv` (which we translate to `truck_speed`). One would have to look at the OSM wiki for country-specific HGV speeds, but probably we could by default cap it at 90 kmh for HGV (`bus` has a similar problem..).

I'd like to do translate the country-specific maxspeed OSM wiki to our admin database soon anyways, which should eventually set `truck_speed` for lots of countries. Or very future, integrate https://github.com/westnordost/osm-legal-default-speeds (there's a discussion around this already somewhere).

**Comment by kevinkreiser** [comment]
yep I agree with this. short term fix could be to just add a single capped speed to truck by default

**Comment by nilsnolde** [comment]
Yep, I already suggested 90 kmh, which seems like an OK first pass according to the [wiki](https://wiki.openstreetmap.org/wiki/Default_speed_limits), where HGV speed outside settlements varies between 70 - 100 kmh, skewed towards the upper limit.

**Comment by radekvermirovsky** [comment]
@nilsnolde will using top_speed property help as quick solution? We have this problem now, some routes ends up with average speed for 18 ton truck as 123 km/h etc. So not usable in for truck routing...so until this will be fixed we thinking to overide it by top speed property? Should it help? Of course i am talking about sources_to_targets, not just simple route.

**Comment by nilsnolde** [comment]
Jep, good point, `top_speed` should help here. You'd only get bitten when `maxspeed:hgv` is actually lower than what you pass, but still a ton better than right now.
