### ISSUE TITLE
When hierarchies are not built, we should not reclassify links or ferry connections

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#4486]
Currently we always reclassify edges leading to ferry connections. However, if we are not creating hierarchies there is no reason to reclassify edges. The same holds for reclassifying links (ramps, turn channels). In fact, the reclassification can impact costing for bicycle routes (perhaps others) that use road classification in edge costing methods.

**Comment by kevinkreiser** [comment]
i didnt look at the code to refresh my memory but i wondered about the turn_channels, i thought we "created" them in the reclassifying step? would there be costing/directions problems if we never created them at all?

**Comment by dnesbitt61** [comment]
oops, forgot about that! We should keep that logic for sure. 
So we should always run ReclassifyLinks (at least if hierarchies are to be created AND infer_turn_channels is true in the config). One option could be to add a flag to ReclassifyLinks to say whether to actually change classifications. Set this to false if hierarchies are not created. Then in ReclassifyLinkGraph add this flag and if false do not actually change classifications (lines 853 - 860). This would do all the logic of forming turn channels  but would not reclassify the links.

**Comment by dnesbitt61** [comment]
which begs the question - what if the config has reclassify_links = false but infer_turn_channels = true. This combination fails to generate turn channels (I think) currently.

**Comment by kevinkreiser** [comment]
yep we are getting a bit tricky with data customizations and probably forgetting some of the interplay between those different knobs. im cool with more complicatitions if it helps use cases get smaller data and reduces tile build times. long term or in the next major version we'll probably want to reorganize a bit to make it harder for us to forget about these things though i havent considered how we would do that exactly :smile:
