### ISSUE TITLE
std::runtime_error when running valhalla_build_tiles

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#449]
(2016-11-23T18:59:36Z) @pavel-citymaps : originally created valhalla/mjolnir#569

(2016-11-23T19:22:34Z) @kevinkreiser : this could happen if your ways reference a node that isnt found in your nodes. so for example you might have clipped your osm data to a region, deleted the nodes that lay outside of that region but not truncated the ways in the same manner.

if its a full planet osm dump then im at a loss. we write intermediate memory mapped files which contain the OSMWayNodes. These are written when parsing ways. It would seem that we see the node for the way and then when we parse nodes we dont find it. i'll check the code to see if im not remember that wrong

(2016-11-23T19:34:51Z) @zerebubuth : There are two different types of PBF dumps from OpenStreetMap:

* The planet, which contains all the data at the current version, e.g: http://planet.openstreetmap.org/pbf/planet-161107.osm.pbf
* The _full history_ planet, which contains all the data ever, including old versions of the data, e.g: http://planet.openstreetmap.org/pbf/full-history/history-161107.osm.pbf

Valhalla needs the current planet, and isn't able to load the full history planet. It's confusing, as the file format is the same for both of them, but the data contained inside is different.

(2016-11-23T20:36:16Z) @pavel-citymaps : file.osm.pbf is just planet-latest.osm.pbf that I downloaded and renamed from an osm mirror, http://mirror2.shellbot.com/osm/
I'm fairly certain there is nothing wrong with the file (unless planet-latest was generated incorrectly by osm)
```
$ md5sum file.osm.pbf 
2a933d094d8e62efaab4e3f1a3c65bec  file.osm.pbf
```
the md5 matches to http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf.md5
```
2a933d094d8e62efaab4e3f1a3c65bec  planet-latest.osm.pbf
```

Are debug/vebosity flags that I can pass to build_valhalla_tiles? Should I try with an older osm dump?

(2016-11-25T19:05:39Z) @zerebubuth : I tried to reproduce this with the latest version of the code, but it seems to be working:

```
2016/11/25 00:03:07.114715 [INFO] Parsing files: /home/matt/Downloads/planet/planet-161107.osm.pbf
2016/11/25 00:03:07.114862 [INFO] Parsing ways...
2016/11/25 04:46:02.102155 [INFO] Finished with 99176463 routable ways containing 1086558289 nodes
2016/11/25 04:46:02.104120 [INFO] Parsing relations...
2016/11/25 05:29:19.441806 [INFO] skipping restriction with vias > the max allowed.  OSMID: 1414677
2016/11/25 05:29:19.441902 [INFO] skipping restriction with vias > the max allowed.  OSMID: 1414679
2016/11/25 05:30:35.741598 [INFO] Finished with 538640 simple restrictions
2016/11/25 05:30:35.776299 [INFO] Sorting complex restrictions by from id...
2016/11/25 05:30:35.813235 [INFO] Sorting osm way node references by node id...
2016/11/25 06:07:19.948413 [INFO] Finished
2016/11/25 06:07:19.949158 [INFO] Parsing nodes...
2016/11/25 09:56:13.381085 [INFO] Finished with 937154724 nodes contained in routable ways
2016/11/25 09:56:13.385279 [INFO] Sorting osm way node references by way index and node shape index...
2016/11/25 10:33:42.679094 [INFO] Sorting osm access tags by way id...
2016/11/25 10:33:48.816009 [INFO] Finished at changeset id 43455424
2016/11/25 10:33:48.848673 [INFO] Creating graph edges from ways...
2016/11/25 11:02:44.853740 [INFO] Finished with 213163010 graph edges
2016/11/25 11:02:45.143991 [INFO] Sorting graph...
2016/11/25 11:13:26.147217 [INFO] Finished with 162935908 graph nodes
2016/11/25 11:13:26.729611 [INFO] Reclassifying link graph edges...
2016/11/25 11:20:39.762344 [INFO] Finished with 502030 reclassified.
2016/11/25 11:20:40.246650 [INFO] Reclassifying ferry connection graph edges...
...
```

It hasn't finished yet, but it got further than parsing nodes.

I wonder if the issue might have been that different repos were out of sync earlier in the week as there were a few cross-repo commits. The version which produced the above is compiled from the `2.0.1` tag for all the valhalla repos (and `0.3.5-6-gdbf8ba4` for `prime_server`, although I'd be very surprised if that made a difference).

The planet file I used has the same name and hash as you've pasted.

Could you try compiling `2.0.1` and see if you get the exception again, please?

(2016-11-27T03:05:42Z) @pavel-citymaps : Still doesn't work. I'm starting to think it's something with the docker image.

I produced the build by running the following script: https://github.com/valhalla/docker/blob/master/scripts/install_from_source.sh except I added `git checkout tags/2.0.1` after lines 17 and 23. The image was built on docker for mac. And is executing on a docker 1.10, 64bit system. 

Using the https://hub.docker.com/r/mapzen/valhalla-source/ image and the Nov 11th OSM file
OR using self-built image with tags/2.0.1 and the Nov 11th file
I get the following error:
```
2016/11/26 02:59:51.562840 [INFO] Sorting osm way node references by node id...
terminate called after throwing an instance of 'std::runtime_error'
  what():  This file has an incorrect size for type
```
Using self-built image with master and Nov 11th file
OR using the self-built image with tags/2.0.1 and Nov 24th file
I get the following error:
```
2016/11/26 20:58:49.165972 [INFO] Parsing nodes...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Didn't find OSMWayNode for node id: 10
```

I wish I could provide more information. I'm not very familiar with the process, I'm using this issue https://github.com/valhalla/docker/issues/5 as a reference for which commands to run. The valhalla.conf file is the one provided in the docker image.

**Comment by dnesbitt61** [comment]
We did some recent work on validating nodes referenced by ways. This PR might help this: https://github.com/valhalla/valhalla/pull/492
We are also reworking Docker in the near future.
I am going to close this issue - feel free to open new issue if this persists
