### ISSUE TITLE
valhalla_export_edges logging interspersed with output

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla#4496]
On the current master branch, the expected output from valhalla_export_edges appears to be combined with logs. As far as I can tell, the standard logging facility must be going to stdout, which causes the output to be mixed. It seems the workaround for now is probably to create a new config specifically for exporting edges with `mjolnir.logging` configured to output to a file.

Long-term fix ideas:

* I would expect these to go to stderr, but I may be missing some reason why it's useful for these to go to stdout.
* Alternately, we could have valhalla_export_edges require a file argument to which the contents will be written. I don't know all the history, but the major use case for this command (Pelias) consumes a file on disk.

Thoughts?

**Comment by kevinkreiser** [comment]
it's a regression. we did a couple overhauls of all the executables and probably accidentally turned on logging for it when it wasn't on before. just need to patch it up to how it used to be

**Comment by kevinkreiser** [comment]
yep accidentally removed the logging to stderr. just need to put it back

**Comment by nilsnolde** [comment]
hmpf, my bad.. let me quickly update.
