### ISSUE TITLE
Enhancement:  "exclude_polygons" are not taken into account in Matrix

### ISSUE THREAD

**Issue by xlqian** [valhalla/valhalla#4499]
Hello, 

It seems to me that  "exclude_polygons" are not taken into account in Matrix after a couple of attempts of tests.  

Can you confirm that, please?  If that's not the case, I would love to implement that feature.

**Comment by kevinkreiser** [comment]
the costings enforce this via `IsUserAvoidEdge` called from the `Allowed` method. this would make me think we support this for matrix so long as we parse the polygon and fill out the edges at the beginning request (i guess its probably this that we dont do). anyway please go ahead and add it!

**Comment by xlqian** [comment]
my bad... @nilsnolde you were right, `exclude_polygons` are handled correctly for `Matrix`... sorry, guys
