### ISSUE TITLE
Invalid geometry returned during a route calculation or route optimisation.

### ISSUE THREAD

**Issue by coderon98** [valhalla/valhalla#4515]
I'm having a major problem with the "route" and "optimized_route" functions. In my opinion, the geometry or geometries returned are incorrectly encoded or erroneous for lorries, whereas for cars everything is fine.
Here's a concrete example, but the problem occurs in many places where there are tunnels or bridges nearby that are forbidden to lorries.

* auto case
```
http://localhost:8002/optimized_route?json={"directions_type":"none","language":"en","costing":"auto","units":"km","locations":[{"lat":47.98951507594949,"lon":0.18174245953559875},{"lat":47.98618054606361,"lon":0.17924800515174868}]}
```
![Capture d’écran du 2024-01-20 10-28-03](https://github.com/valhalla/valhalla/assets/47818458/e54ddf2d-d721-428c-a5f7-36cf5428e8b0)

* truck case
```
http://localhost:8002/optimized_route?json={"directions_type":"none","language":"en","costing":"truck","units":"km","locations":[{"lat":47.98951507594949,"lon":0.18174245953559875},{"lat":47.98618054606361,"lon":0.17924800515174868}]}
```
![Capture d’écran du 2024-01-20 10-55-01](https://github.com/valhalla/valhalla/assets/47818458/765671c0-ace0-4e98-8624-59435cb84d17)

I don't know what I can do to solve the problem. A solution?

**Comment by coderon98** [comment]
For further information, please note that the central roundabout has a subway reserved exclusively for vehicles less than 2.4 metres high. This explains the truck's bypass. It is the end of the journey that is incorrect. I'm certain that the polyline returned is invalid because when I try to convert it to geojson, I get an [index out of range] exception.

* polyline for the car
```
kn`pzAw|aJ??~ElAnErBfHdCnM`EnJjBjEp@l@HdDRtCPxC_@jEn@fATpH~ApBn@hLhEZNpG|C`OzIhJdLTXfFlG`TlZhA`BfDzExAdDbCxFpBlEdGdJ`FrJ
```
* polyline for the truck
```
kn`pzAw|aJ??xEfEvD~A~GbCrNfExQ|DtHdBjGpA|IdCxC`@xI|BbEpEdAvADhDNbCb@tCn@hC~@~BhAnBtA|A|AfAbBr@nB\\pABvAKvA]zDf@hBb@`B|@fBxAtBzBjQtUlBrBhFfGtJrNpGrH
```

**Comment by nilsnolde** [comment]
Unescaped backslash would be my guess..

**Comment by coderon98** [comment]
Hi @nilsnolde, do I need to escape the backslash before converting or are they already escaped and I need to do the reverse.

**Comment by coderon98** [comment]
You're right, it works. Thanks a lot! 
The issue can be closed!
![image](https://github.com/valhalla/valhalla/assets/47818458/3a48c531-dcf3-4710-8dea-b26f69722750)

**Comment by nilsnolde** [comment]
You can close issues as well when you open them
