### ISSUE TITLE
Funky pedestrian routing in conjunction with ferries

### ISSUE THREAD

**Issue by buttercookie42** [valhalla/valhalla#4518]
E.g. https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=-1.0601806640625002%2C50.81114153614715%2C-0.37490844726562506%2C49.18170338770663 gives some very strange routing between the port and Caen city centre:

![strange pedestrian routing 1](https://github.com/valhalla/valhalla/assets/7611366/7c535831-e9b3-43f3-96c7-00091b5f5eea)

If I [move the start to Brighton](https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=-0.087890625%2C50.84757295365389%2C-0.37490844726562506%2C49.18170338770663), the routing in Caen fixes itself, but instead there are weird detours in the Portsmouth area:

![strange pedestrian routing 2](https://github.com/valhalla/valhalla/assets/7611366/0a90991f-7a61-4cb9-835c-29042b752232)

**Comment by nilsnolde** [comment]
dup of https://github.com/valhalla/valhalla/issues/3941 :)
