### ISSUE TITLE
Feature request: multiple locations for the isochrone service

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#452]
(2016-12-01T21:33:15Z) @kkowalsky : originally created valhalla/thor#485

A support ticket following up on the introductory isochrone blog post asked about one of the hypothetical uses of the service "What would adding/removing this road/bus stop/bridge do to travel times?" and if we would be implementing multiple locations as a part of our service.

(2016-12-01T21:33:39Z) @kkowalsky : cc: @kevinkreiser 

(2016-12-01T22:09:55Z) @dnesbitt61 : We likely will not have time until Q1 next year to make any additions to the isochrone service. We do anticipate allowing multiple locations - it would return the composite contours representing the regions reachable from any of the locations within the contour time intervals. It would not create separate contours for each - those would still require separate requests.

Editing the graph network as you suggest is not on the near term roadmap. We do not have any ways to update individual road segments.

**Comment by dnesbitt61** [comment]
Code complete, still looking at how/when to launch in hosted service.
