### ISSUE TITLE
Config singleton multiple instantiation issue

### ISSUE THREAD

**Issue by akesmarki** [valhalla/valhalla#4521]
I wanted to use the new config singleton from valhalla/config.h and found out that it is not a real singleton, it's constuctor was called more than once. ( and, at the second time, I got a valhalla::ConfigUninitializedException() error )

Steps to reproduce (on Linux, Ubuntu): 
- call valhalla::config(_config_json_file_) from your main method (as usual)
- call valhalla::config() from a source file in the main valhalla library ( libvalhalla.a )
- Build and execute your modified valhalla_service/valhalla_... tool. A ConfigUninitializedException will be thrown. 
 
The second valhalla::config() call wants to create a second instance of your config_singleton_t singleton object, but, as it's argment is the default empty string, it will throw this exception. 
IMHO this error is caused by the fact that this "static" instance is not a singleton, one object will be created in each translation unit where config.h is included. 

A (proposed) solution to this problem is to create a config.cc source file, and put the static instance variable there. (checked it, and it worked)

**Comment by nilsnolde** [comment]
aaah, that makes a lot of sense! thanks for the (kinda obvious) pointer. actually here @johannes-no did that as well in another PR (not merged yet) and here's my comment https://github.com/valhalla/valhalla/pull/4340#discussion_r1429200940 :sweat_smile: wasn't thinking too hard about the internals obviously. good catch @akesmarki . you wanna PR just that bit?

**Comment by akesmarki** [comment]
Sure, I will do that.
