### ISSUE TITLE
Unknown: CHECK failed: (index) < (current_size_):

### ISSUE THREAD

**Issue by amrelhewy09** [valhalla/valhalla#4526]
can someone hint me on what might be the problem here? I get this error out of no where (it was working normally)

**Comment by amrelhewy09** [comment]
logs: FATAL ./google/protobuf/repeated_ptr_field.h:271] CHECK failed: (index) < (current_size_):

**Comment by nilsnolde** [comment]
Oops, you might’ve been onto this yesterday on slack @dnesbitt61. Likely this is happening when just before the serialization and pretty surely a bug. I have many clients using the matrix recently, hasnt popped up yet. let me have a look later

**Comment by dnesbitt61** [comment]
It seems that in CostMatrix, the date_time, time_zone_offset, and time_zone_name are added to the pbf matrix output only when if (time < kMaxCost). Probably need to add (empty strings) in an else case. It also seems like these are not added in timedistancebssmatrix code. In both cases, if these are not added then matrix serialization to JSON fails in serialize_row.

**Comment by nilsnolde** [comment]
I'll take a look at this again. my memory of past work is quite short tbh..
