### ISSUE TITLE
costmatrix algorithm do not respect oneway on trivial routes

### ISSUE THREAD

**Issue by radekvermirovsky** [valhalla/valhalla#4538]
If we use this request to route endpoint:

```json
{
	"locations": [
        {
		"lat": 50.22878,
		"lon": 15.83895
	},
        {
		"lat": 50.22888,
		"lon": 15.83918
	}
	],
       "verbose":false,
	"directions_type": "none",
	"costing": "auto",
	"prioritize_bidirectional": true
}
```
oneway is respected properly. 
Foggis
[https://valhalla.openstreetmap.de/directions?profile=car&wps=15.83895%2C50.22878%2C15.83918%2C50.22888](url)
Polyline
[https://valhalla.github.io/demos/polyline/?unescape=true&polyline6=true#qyux~Aguve%5DpUhx%40x%60%40%60uAjTiStQmQvQoQim%40smBu%40iC%7DSgu%40ox%40ju%40lDzL](url)
Screenshot:
<img width="832" alt="image" src="https://github.com/valhalla/valhalla/assets/149080356/e81c7e6f-ed06-439a-8334-e460b1e78130">

If we try find same route for matrix, using costmatrix algorithm:
```json
{
	"sources": [
		{
			"lat": 50.22878,
			"lon": 15.83895
		}
	],
	"targets": [
		{
			"lat": 50.22888,
			"lon": 15.83918
		}
	],
	"verbose": false,
        "shape_format":"polyline6",
	"costing": "auto",
	"prioritize_bidirectional": true
}
```
response is:

```json
{
    "algorithm": "costmatrix",
    "units": "kilometers",
    "sources_to_targets": {
        "shapes": [
            [
                "cyux~Aquve]wDyM"
            ]
        ],
        "durations": [
            [
                2
            ]
        ],
        "distances": [
            [
                0.020
            ]
        ]
    }
}
```
Polyline:
[https://valhalla.github.io/demos/polyline/?unescape=true&polyline6=true#cyux~Aquve%5DwDyM](url)
Screenshot:
<img width="930" alt="image" src="https://github.com/valhalla/valhalla/assets/149080356/dad0c1ef-9c8f-4e6e-99a4-1cadbf78053a">

**Comment by nilsnolde** [comment]
Actually I'll keep this open and close the other one, this has a test case

**Comment by radekvermirovsky** [comment]
We tested this, and indeed PR [4626](https://github.com/valhalla/valhalla/pull/4626)  fixes this for values. Thank you for fixing this. Travel time and distance are now computed properly, respecting one-way restrictions in matrix computation. However, the polyline in the matrix return is not accurate. Looks like polyline generation in matrix cant handle this special oneway trivial route? It seems like the first segment is in the polyline in both directions, making it appear like a polygon rather than a straight end line, as in route computation.
<img width="824" alt="image" src="https://github.com/valhalla/valhalla/assets/149080356/c730e391-ef3e-4aae-88f0-2be4b82c4de4">

**Comment by nilsnolde** [comment]
Yeah seems it’s getting confused about the percent_along.. I’ll take a look later.
