### ISSUE TITLE
search_radius does'nt seem to be consistent with distance_from_point

### ISSUE THREAD

**Issue by athuet** [valhalla/valhalla#4545]
Hello!
I tried using Valhalla this way: sending a request with a specific search_radius in input and then calculating the mean distance_from_point from the output. I was expecting to get distances smaller than the radius, since it shouldn't map anywhere beyond that radius, but that doesn't seem to be the case. Have I misunderstood something, or are there other parameters to take into account?

**Here is my request:**
{
    "shape": [
        {
            "lat": 45.8098399,
            "lon": 3.1477033,
            "distance_totale": 7.5016704,
            "time": 1.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8098249,
            "lon": 3.1477416,
            "distance_totale": 10.9099439,
            "time": 2.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8098216,
            "lon": 3.1477848,
            "distance_totale": 14.2835878,
            "time": 3.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8098266,
            "lon": 3.1478299,
            "distance_totale": 17.8269974,
            "time": 4.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.80983,
            "lon": 3.1478698,
            "distance_totale": 20.9547197,
            "time": 5.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8098416,
            "lon": 3.1479148,
            "distance_totale": 24.6771504,
            "time": 6.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.809865,
            "lon": 3.1480081,
            "distance_totale": 32.3714162,
            "time": 7.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8098766,
            "lon": 3.1480614,
            "distance_totale": 36.7038976,
            "time": 8.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8098983,
            "lon": 3.1481065,
            "distance_totale": 40.9500366,
            "time": 9.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8099216,
            "lon": 3.1481483,
            "distance_totale": 45.1036936,
            "time": 10.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8099566,
            "lon": 3.14818,
            "distance_totale": 49.7119886,
            "time": 11.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8100016,
            "lon": 3.1481997,
            "distance_totale": 54.9522235,
            "time": 12.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8100566,
            "lon": 3.1481614,
            "distance_totale": 61.7574975,
            "time": 13.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.81012,
            "lon": 3.1481215,
            "distance_totale": 69.4670097,
            "time": 14.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8101816,
            "lon": 3.1480966,
            "distance_totale": 76.5913307,
            "time": 15.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.810245,
            "lon": 3.1480733,
            "distance_totale": 83.8767549,
            "time": 16.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8103083,
            "lon": 3.1480599,
            "distance_totale": 90.9991738,
            "time": 17.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8103666,
            "lon": 3.1480516,
            "distance_totale": 97.5211364,
            "time": 18.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8104216,
            "lon": 3.1480583,
            "distance_totale": 103.6658564,
            "time": 19.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8104633,
            "lon": 3.1480614,
            "distance_totale": 108.3141604,
            "time": 20.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105,
            "lon": 3.1480566,
            "distance_totale": 112.4174948,
            "time": 21.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105366,
            "lon": 3.1480633,
            "distance_totale": 116.5252295,
            "time": 22.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.81059,
            "lon": 3.1481381,
            "distance_totale": 124.8390656,
            "time": 23.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105966,
            "lon": 3.1481733,
            "distance_totale": 127.6616586,
            "time": 24.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105916,
            "lon": 3.1482148,
            "distance_totale": 130.930594,
            "time": 25.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.81057,
            "lon": 3.1483166,
            "distance_totale": 139.1871915,
            "time": 26.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105666,
            "lon": 3.1483733,
            "distance_totale": 143.6022825,
            "time": 27.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105716,
            "lon": 3.1484349,
            "distance_totale": 148.4148073,
            "time": 28.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105783,
            "lon": 3.1484933,
            "distance_totale": 153.0083773,
            "time": 29.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.810575,
            "lon": 3.1485515,
            "distance_totale": 157.539582,
            "time": 30.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105833,
            "lon": 3.1486048,
            "distance_totale": 161.7772033,
            "time": 31.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105666,
            "lon": 3.1486483,
            "distance_totale": 165.6307876,
            "time": 32.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8105283,
            "lon": 3.1486766,
            "distance_totale": 170.4263899,
            "time": 33.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.810485,
            "lon": 3.1486949,
            "distance_totale": 175.4519279,
            "time": 34.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8104333,
            "lon": 3.14871,
            "distance_totale": 181.3253171,
            "time": 35.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8103833,
            "lon": 3.1487166,
            "distance_totale": 186.9150264,
            "time": 36.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8103366,
            "lon": 3.1487198,
            "distance_totale": 192.120672,
            "time": 37.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102933,
            "lon": 3.1487166,
            "distance_totale": 196.9463174,
            "time": 38.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102583,
            "lon": 3.1487233,
            "distance_totale": 200.8764934,
            "time": 39.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102383,
            "lon": 3.1487333,
            "distance_totale": 203.2334496,
            "time": 40.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102333,
            "lon": 3.1487348,
            "distance_totale": 203.8036994,
            "time": 41.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.810245,
            "lon": 3.1487198,
            "distance_totale": 205.5510189,
            "time": 42.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102566,
            "lon": 3.1487,
            "distance_totale": 207.5626714,
            "time": 43.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102666,
            "lon": 3.1486831,
            "distance_totale": 209.2786929,
            "time": 44.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.810275,
            "lon": 3.1486732,
            "distance_totale": 210.4921034,
            "time": 45.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.8102816,
            "lon": 3.1486649,
            "distance_totale": 211.47061712,
            "time": 46.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.81028,
            "lon": 3.1486665,
            "distance_totale": 211.70342063,
            "time": 47.0,
            "raw_or_map_matched": "raw"
        },
        {
            "lat": 45.81028,
            "lon": 3.1486683,
            "distance_totale": 211.83782983,
            "time": 48.0,
            "raw_or_map_matched": "raw"
        }
    ],
    "search_radius": "20",
    "shape_match": "map_snap",
    "costing": "auto",
    "format": "osrm"
}

**Here is the response I have:**
{
    "units": "kilometers",
    "osm_changeset": 11552227096,
    "shape": "}`akvAekc_EkCkh@",
    "confidence_score": 1.0,
    "raw_score": 300000000.0,
    "admins": [
        {
            "country_text": "None",
            "state_text": "None"
        }
    ],
    "edges": [
        {
            "truck_route": false,
            "density": 8,
            "sac_scale": 0,
            "shoulder": false,
            "sidewalk": "none",
            "bicycle_network": 0,
            "cycle_lane": "none",
            "lane_count": 1,
            "max_downward_grade": -500,
            "max_upward_grade": -500,
            "weighted_grade": 0.0,
            "way_id": 72045416,
            "id": 676564273634,
            "travel_mode": "drive",
            "vehicle_type": "car",
            "surface": "paved_smooth",
            "drive_on_right": false,
            "internal_intersection": false,
            "roundabout": false,
            "bridge": false,
            "tunnel": false,
            "unpaved": false,
            "toll": false,
            "use": "road",
            "traversability": "both",
            "end_shape_index": 1,
            "begin_shape_index": 0,
            "end_heading": 81,
            "begin_heading": 81,
            "road_class": "unclassified",
            "speed": 40,
            "length": 0.051,
            "source_percent_along": 0.432,
            "target_percent_along": 0.549,
            "names": [
                "Rue Benjamin Franklin"
            ],
            "end_node": {
                "elapsed_time": 4.677,
                "admin_index": 0,
                "type": "street_intersection",
                "fork": false,
                "transition_time": 0.0
            }
        }
    ],
    "matched_points": [
        {
            "lon": 3.147703,
            "lat": 45.809839,
            "type": "unmatched"
        },
        {
            "lon": 3.147741,
            "lat": 45.809824,
            "type": "unmatched"
        },
        {
            "lon": 3.147784,
            "lat": 45.809821,
            "type": "unmatched"
        },
        {
            "lon": 3.147829,
            "lat": 45.809826,
            "type": "unmatched"
        },
        {
            "lon": 3.147869,
            "lat": 45.80983,
            "type": "unmatched"
        },
        {
            "lon": 3.147914,
            "lat": 45.809841,
            "type": "unmatched"
        },
        {
            "lon": 3.148008,
            "lat": 45.809865,
            "type": "unmatched"
        },
        {
            "lon": 3.148061,
            "lat": 45.809876,
            "type": "unmatched"
        },
        {
            "lon": 3.148106,
            "lat": 45.809898,
            "type": "unmatched"
        },
        {
            "lon": 3.148148,
            "lat": 45.809921,
            "type": "unmatched"
        },
        {
            "lon": 3.14818,
            "lat": 45.809956,
            "type": "unmatched"
        },
        {
            "lon": 3.148199,
            "lat": 45.810001,
            "type": "unmatched"
        },
        {
            "lon": 3.148161,
            "lat": 45.810056,
            "type": "unmatched"
        },
        {
            "lon": 3.148121,
            "lat": 45.81012,
            "type": "unmatched"
        },
        {
            "lon": 3.148096,
            "lat": 45.810181,
            "type": "unmatched"
        },
        {
            "lon": 3.148073,
            "lat": 45.810245,
            "type": "unmatched"
        },
        {
            "lon": 3.14797,
            "lat": 45.810719,
            "type": "matched",
            "edge_index": 0,
            "end_route_discontinuity": true,
            "distance_along_edge": 0.432791,
            "distance_from_trace_point": 45.949926
        },
        {
            "lon": 3.147975,
            "lat": 45.810719,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.433538,
            "distance_from_trace_point": 39.480612
        },
        {
            "lon": 3.147993,
            "lat": 45.810721,
            "type": "matched",
            "edge_index": 0,
            "distance_along_edge": 0.436748,
            "distance_from_trace_point": 33.544668
        },
        {
            "lon": 3.148005,
            "lat": 45.810722,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.43884,
            "distance_from_trace_point": 29.021363
        },
        {
            "lon": 3.148008,
            "lat": 45.810723,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.439384,
            "distance_from_trace_point": 24.953802
        },
        {
            "lon": 3.148022,
            "lat": 45.810724,
            "type": "matched",
            "edge_index": 0,
            "distance_along_edge": 0.441907,
            "distance_from_trace_point": 21.029491
        },
        {
            "lon": 3.148107,
            "lat": 45.810733,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.456802,
            "distance_from_trace_point": 16.052026
        },
        {
            "lon": 3.148142,
            "lat": 45.810737,
            "type": "matched",
            "edge_index": 0,
            "distance_along_edge": 0.463119,
            "distance_from_trace_point": 15.73547
        },
        {
            "lon": 3.148182,
            "lat": 45.810741,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.47009,
            "distance_from_trace_point": 16.759604
        },
        {
            "lon": 3.148277,
            "lat": 45.810751,
            "type": "matched",
            "edge_index": 0,
            "distance_along_edge": 0.48684,
            "distance_from_trace_point": 20.292388
        },
        {
            "lon": 3.148332,
            "lat": 45.810757,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.496492,
            "distance_from_trace_point": 21.316488
        },
        {
            "lon": 3.148393,
            "lat": 45.810763,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.507302,
            "distance_from_trace_point": 21.478612
        },
        {
            "lon": 3.148451,
            "lat": 45.810769,
            "type": "matched",
            "edge_index": 0,
            "distance_along_edge": 0.517625,
            "distance_from_trace_point": 21.418061
        },
        {
            "lon": 3.148508,
            "lat": 45.810775,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.527539,
            "distance_from_trace_point": 22.448487
        },
        {
            "lon": 3.148561,
            "lat": 45.810781,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.537042,
            "distance_from_trace_point": 22.154331
        },
        {
            "lon": 3.1486,
            "lat": 45.810785,
            "type": "matched",
            "edge_index": 0,
            "distance_along_edge": 0.54392,
            "distance_from_trace_point": 24.480613
        },
        {
            "lon": 3.14862,
            "lat": 45.810787,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.54737,
            "distance_from_trace_point": 28.993488
        },
        {
            "lon": 3.148629,
            "lat": 45.810788,
            "type": "interpolated",
            "edge_index": 0,
            "distance_along_edge": 0.548909,
            "distance_from_trace_point": 33.937944
        },
        {
            "lon": 3.148632,
            "lat": 45.810788,
            "type": "matched",
            "edge_index": 0,
            "begin_route_discontinuity": true,
            "distance_along_edge": 0.549581,
            "distance_from_trace_point": 39.763934
        },
        {
            "lon": 3.148716,
            "lat": 45.810383,
            "type": "unmatched"
        },
        {
            "lon": 3.148719,
            "lat": 45.810336,
            "type": "unmatched"
        },
        {
            "lon": 3.148716,
            "lat": 45.810293,
            "type": "unmatched"
        },
        {
            "lon": 3.148723,
            "lat": 45.810258,
            "type": "unmatched"
        },
        {
            "lon": 3.148733,
            "lat": 45.810238,
            "type": "unmatched"
        },
        {
            "lon": 3.148734,
            "lat": 45.810233,
            "type": "unmatched"
        },
        {
            "lon": 3.148719,
            "lat": 45.810245,
            "type": "unmatched"
        },
        {
            "lon": 3.1487,
            "lat": 45.810256,
            "type": "unmatched"
        },
        {
            "lon": 3.148683,
            "lat": 45.810266,
            "type": "unmatched"
        },
        {
            "lon": 3.148673,
            "lat": 45.810275,
            "type": "unmatched"
        },
        {
            "lon": 3.148664,
            "lat": 45.810281,
            "type": "unmatched"
        },
        {
            "lon": 3.148666,
            "lat": 45.81028,
            "type": "unmatched"
        },
        {
            "lon": 3.148668,
            "lat": 45.81028,
            "type": "unmatched"
        }
    ],
    "alternate_paths": []
}

Thank you for your answer!!

**Comment by kevinkreiser** [comment]
i appreciate all the detail here but its hard to understand what is going on. are you saying that you set search_radius to 20 but sometimes the returned points are more than 20m away from their match location?

**Comment by jthiard** [comment]
Not sure it's relevant, but according to the [docs](https://valhalla.github.io/valhalla/api/map-matching/api-reference/#costing-models-and-other-options), the `search_radius` param must passed as an attribute of a top level `trace_options` object.

```json
{
  "shape": [],
  "trace_options": {
     "search_radius": 20
  }
}
```

**Comment by nilsnolde** [comment]
Eagle eyes 😄 didn’t even look at that huge unformatted json. Case in point to provide minimal examples.

**Comment by athuet** [comment]
That was the problem, thank you for your help !!
