### ISSUE TITLE
In isochrone: Infinite loop in bresenham_line, caused by Nan, caused by divide by zero, due to zero length edge

### ISSUE THREAD

**Issue by munckymagik** [valhalla/valhalla#4546]
# Summary

While generating isochrones for 160,000 locations, we found 2 locations that would result in no response from the isochrone API. Repeat attempts would gradually lock each handler thread until the server became entirely unresponsive. 

Debugging showed the handler threads were getting stuck in an infinite loop in `bresenham_line()`.

Sorry, may be a duplicate of #3823 but wanted to post a bit of detail so opening a new bug. Can move this there if preferred.

# Steps to reproduce

So far I've reproduced this in these versions
* `master` at `0cc7d6ec7` compiled on macOS M1
* 3.4.0 compiled for macOS M1
* 3.4.0 using the project Docker images

To make the steps easier to read, I'm going refer to the following requests from the steps below

isochrone-ok
```
curl --request GET --url 'http://localhost:8002/isochrone?json=%7B%22locations%22%3A%5B%7B%22lat%22%3A%2244.89%22%2C%22lon%22%3A%22-0.568%22%7D%5D%2C%22costing%22%3A%22auto%22%2C%22contours%22%3A%5B%7B%22time%22%3A10.0%7D%5D%7D'
```
isochrone-bad
```
curl --request GET --url 'http://localhost:8002/isochrone?json=%7B%22locations%22%3A%5B%7B%22lat%22%3A%2244.836048%22%2C%22lon%22%3A%22-0.565914%22%7D%5D%2C%22costing%22%3A%22auto%22%2C%22contours%22%3A%5B%7B%22time%22%3A10.0%7D%5D%7D'
```

1. Generate tile data (I think we might be using a slightly customised version of the car profile Lua script, I will need to check and confirm)
2. Start the service with 1 thread: `valhalla_service <path to config>.json 1`
3. Execute "isochrone-ok" request and confirm there is a response
4. Execute "isochrone-bad" request, there is no response, the client times out, the server process is using 100% of 1 CPU core.
5. Execute "isochrone-ok" request, there is no response, the client times out.

# Findings from debugging

Pausing the debugger while it's locked up showed up the problem loop. It is stuck in an endless loop in `bresenham_line()` in tiles.cc, because `x0` and `y0` are both `NaN`. 

![Screenshot 2024-01-23 at 18 05 28](https://github.com/valhalla/valhalla/assets/306583/0d629491-8009-4a41-887b-2deab3e50ae6)

Tracing this back it's because of a divide by zero in `OriginEdgeShape()`, here:

![Screenshot 2024-01-26 at 21 12 40](https://github.com/valhalla/valhalla/assets/306583/dee43b3b-6d65-46cf-bf68-2c0e8ed0eedb)

So it seems there is an edge in the tile data that has a zero length. On line 22 the Distance call returns 0.0 On line 25 that results in a divide by zero. It evaluates to NaN. This then carries forward polluting code that follows, which continues executing until it gets stuck in the loop in `bresenham_line()`.

Here's a diagram of the callstack with my notes:

![image](https://github.com/valhalla/valhalla/assets/306583/a70be530-39e9-41cc-ac5b-1f80d6c2e855)

# Open questions

This is as far as I've got. The two questions I have at this point are:

1. Why is there a zero length edge? 
  * Could it be there is something wrong with our tile data? 
  * Could this have been caused by a version mismatch between the server and the data processing scripts?
2. Is there a good place in the code that we could detect the 0 or the NaN?
  * Should `bresenham_line()` be responsible for checking for `NaN`? or `OriginEdgeShape()` for 0? Or could it be detected at boot or data load time?

**Comment by nilsnolde** [comment]
Hm, sounds and looks like that should/could be fixed in the graph build itself. It's perfectly possible that OSM nodes are on the exact same location and referenced in a way (which would clearly be a mapping error we should log out to fix in OSM), but I'm not proficient enough in the details of the graph build to know if that's not smth we might already be attempting to do but failing under some circumstances.

**Comment by kevinkreiser** [comment]
both of those things, the data parsing graph building and the bresenhams code are my doing. my gut says we are better off writing a unit test against the originedgeshape/bresenhams than trying to remove degenerate edges from the graph (there is a lot more room for trouble there than it may seem). to me it looks like it might be enough to put an if at the beginning of originedgeshape that just says:

```c++
  if (distance_along  == 0)
    return {pts.back(), pts.back()};
```

**Comment by kevinkreiser** [comment]
though i suppose its also true that an edge could have two shape points on top of each other in the middle of the edge which would also result in the same problem. in which case the function could maybe become:

template <typename PrecisionT>
std::vector<GeoPoint<PrecisionT>> OriginEdgeShape(const std::vector<GeoPoint<PrecisionT>>& pts,
                                                  double distance_along) {
  // just the endpoint really
  if (distance_along == 0) {
    return {pts.back(), pts.back()};
  }
  double suffix_len = 0;
  for (auto from = std::next(pts.rbegin()), to = pts.rbegin(); from != pts.rend(); ++from, ++to) {
    PrecisionT len = from->Distance(*to);
    suffix_len += len;
    // skip 0 length segments
    if (len == 0)
      continue;
    // we have enough distance now, lets find the exact stopping point along the geom    
    if (suffix_len >= distance_along) {
      auto interpolated = from->PointAlongSegment(*to, (suffix_len - distance_along) / len);
      std::vector<GeoPoint<PrecisionT>> res(pts.rbegin(), from);
      res.push_back(interpolated);
      std::reverse(res.begin(), res.end());
      return res;
    }
  }
  return pts;
}
