### ISSUE TITLE
Excessive disk space for planet build

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4548]
I just got a warning from our monitoring on the FOSSGIS instance with low disk space. Out of 1.7 TB we only have 100 GB left currently while the parsing stage is going on. A `ll valhalla_tiles` (at the end of parsing ways):
```
total 1.2T
-rw-r--r-- 1 valhalla valhalla  11G Feb  3 17:14 access.bin
-rw-r--r-- 1 valhalla valhalla  41M Feb  3 08:35 complex_from_restrictions.bin
-rw-r--r-- 1 valhalla valhalla  40M Feb  3 08:35 complex_to_restrictions.bin
-rw-r--r-- 1 valhalla valhalla  15G Feb  3 12:21 edges.bin
-rw-r--r-- 1 valhalla valhalla  90G Feb  3 11:31 nodes.bin
-rw-r--r-- 1 valhalla valhalla  20M Feb  3 11:18 osmdata_access_restrictions.bin
-rw-r--r-- 1 valhalla valhalla 100M Feb  3 11:18 osmdata_bike_relations.bin
-rw-r--r-- 1 valhalla valhalla   72 Feb  3 11:18 osmdata_counts.bin
-rw-r--r-- 1 valhalla valhalla    4 Feb  3 11:18 osmdata_lane_connectivity.bin
-rw-r--r-- 1 valhalla valhalla  740 Feb  3 11:18 osmdata_language_file.bin
-rw-r--r-- 1 valhalla valhalla 3.7M Feb  3 11:18 osmdata_node_names.bin
-rw-r--r-- 1 valhalla valhalla  78K Feb  3 11:18 osmdata_pronunciation_file.bin
-rw-r--r-- 1 valhalla valhalla 490M Feb  3 11:18 osmdata_restrictions.bin
-rw-r--r-- 1 valhalla valhalla 290M Feb  3 11:18 osmdata_unique_strings.bin
-rw-r--r-- 1 valhalla valhalla 1.2M Feb  3 11:18 osmdata_viaset.bin
-rw-r--r-- 1 valhalla valhalla 4.0M Feb  3 11:18 osmdata_way_refs.bin
-rw-r--r-- 1 valhalla valhalla 310K Feb  3 11:18 osmdata_way_refs_rev.bin
-rw-r--r-- 1 valhalla valhalla 1.4M Nov 25 06:06 pronunciation.bin
-rw-r--r-- 1 valhalla valhalla  15M Feb  3 11:34 tile_manifest.json
-rw-r--r-- 1 valhalla valhalla 838G Feb  3 17:15 way_nodes.bin
-rw-r--r-- 1 valhalla valhalla 196G Feb  3 17:15 ways.bin
```

I just updated to master (I think the build before that was from somewhere mid December, should've been just after the PR splitting shortcuts on access restrictions IIRC). 

Anyone remember which PR might have had an impact here? I also can't remember what disk space used to be, I usually don't monitor that, but wasn't it < 500 GB very recently?

**Comment by kevinkreiser** [comment]
this https://github.com/valhalla/valhalla/commit/0f6367af7b2c0f974f22340a497e34ee601b340a#diff-87881ad0664f8b3ec64493ebbc31fd0b677428c47f75197fc8de2d5e7cacbe01R61 added a whopping 40 bytes to the node which is used in all way_nodes even though we only really needed this addition for the regular graph nodes. we could take a pass to move the stuff that only applies to graph nodes and have two separate structions with the basic node stuff and then extended node stuff as a subclass. this owuld mean nodes.bin would still be pretty large but way_nodes would shrink dramatically.

**Comment by nilsnolde** [comment]
Thanks, makes sense. It’s fine for us atm close call though, in a year from now it’ll run out of space), but yeah eventually someone should look into that.

**Comment by nilsnolde** [comment]
OSMWay.h also got a good 100 bytes extra (didn't count). do those indices really need to be 32 bit or would 16 suffice?

**Comment by dnesbitt61** [comment]
There has to be a better (much better!) method of storing these names and indexes for both nodes and ways. Most of this is very sparse data and likely that most nodes and even ways have most of these indexes of 0.

**Comment by gknisely** [comment]
> There has to be a better (much better!) method of storing these names and indexes for both nodes and ways. Most of this is very sparse data and likely that most nodes and even ways have most of these indexes of 0.

I think landmark or BSS uses protocol buffers for storing the info.  We were talking about doing this at one point.  So nothing would be stored if there is no data or index of 0.
