### ISSUE TITLE
Error during a build phase in valhalla. 

### ISSUE THREAD

**Issue by coderon98** [valhalla/valhalla#4559]
I'd like to point out that I've already successfully built several builds on this machine. 
I have recovered the latest pbf planete.
I don't understand why it doesn't work. 

![image](https://github.com/valhalla/valhalla/assets/47818458/80b9b5c5-6f07-4868-8e9a-453dd04a89d2)

**Comment by nilsnolde** [comment]
surely a dup of https://github.com/valhalla/valhalla/issues/4548? do a `df -h`, likely you're out of space

**Comment by nilsnolde** [comment]
feel free to re-open, I'm quite sure it's that
