### ISSUE TITLE
route_serializer_osrm.cc:587:36: error: ‘outgoing_index’

### ISSUE THREAD

**Issue by iddqd2d** [valhalla/valhalla#4561]
Hi!
My steps:
- git clone --recurse-submodules https://github.com/valhalla/valhalla.git
- cd valhalla
- ./scripts/install-linux-deps.sh
- cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_WERROR=ON
- make -C build -j$(nproc)
, and I get some errors:
![image](https://github.com/valhalla/valhalla/assets/40464324/610825f5-e584-48a9-9339-2ae6a06b4356)

**Comment by nilsnolde** [comment]
please please, pretty please, no pictures of text! first of all, it's very terrible to look at, I need to actually click on smth to make it work. and blind users are likely out of luck (recently I got a bit more sensitivized to accessibility thanks to @grzezlo).

also, study the options you have in cmakelists.txt. the error is very explicit: warnings-as-errors. use the appropriate cmake flag to turn that off, `ENABLE_SINGLE_FILES_WERROR`.
