### ISSUE TITLE
costmatrix second pass configuration parameter name inconsistency in valhalla_build_config

### ISSUE THREAD

**Issue by radekvermirovsky** [valhalla/valhalla#4565]
Hello, we are testing new second pass feature in costmatrix [(4536)](https://github.com/valhalla/valhalla/pull/4536).

In src is taken "thor.costmatrix_allow_second_pass":
[worker_cc_line](https://github.com/valhalla/valhalla/blob/e406c10bbcc01c57a991ec8f3b9beace0113fbe4/src/thor/worker.cc#L104)

In python valhalla_build_config is parameter enabling this named "costmatrix_second_pass": [valhalla_build_config_line](https://github.com/valhalla/valhalla/blob/e406c10bbcc01c57a991ec8f3b9beace0113fbe4/scripts/valhalla_build_config#L122)

So IMHO valhalla_build_script is wrong and should be change current:
```json
costmatrix_second_pass': False,
```
should be change to:
```json
costmatrix_allow_second_pass': False,
```

**Comment by nilsnolde** [comment]
Oops, thanks! I wonder how the tests pass, since it defaults to False and should make it fail. I’ll look into this soon.
