### ISSUE TITLE
ignore `hgv=no` on second pass via costing option

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4568]
it's fairly common that `hgv=no` is tagged on a road, e.g. in inner cities, but certain companies have a legal permit to enter anyways. it's similar to `hgv=permit` but currently we handle that the same as `hgv=private` which is fine, that's a hardly used tag anyways and would make such an option data-driven when there's actually no such data. instead I'd propose to make it a costing option, e.g. `ignore_truck_access` which would switch a truck's access mask to a car's access mask (not sure if possible in code, but smth like that). ~~we already have a `ignore_restrictions` flag, but that's for all other restrictions (turn, dimensions etc), not base access.~~ (see below, we also have `ignore_access`)

also smth we could just turn on in a second pass.

I think that would help logistics companies a lot. any opinions on this?

**Comment by nilsnolde** [comment]
Ha, we do have `ignore_access` as costing option (really gotta get the docs in order..). It's doing too much though for the use case described above: it just cares if _any_ mode has access and if so, it grant the current mode access. so we'd go down ped/bike paths, ignore bollards etc.

**Comment by radekvermirovsky** [comment]
That would be greatly appreciated for our use case. We encounter many scenarios where our goal is to adhere to truck restrictions as much as possible. However, in cases where no alternative exists, we accept breaking restriction on edge to find a route at any cost. The 'hgv_access_penalty' appears to be precisely what would solve this issue. It would be a significant improvement over falling back to car mode routing, as it attempts to respect restrictions wherever possible, and only break it on edges where is no other choice. So, +1 from me
