### ISSUE TITLE
Ignore_restrictions for truck routing disregards physical real-world restrictions like maxweight and maxheight. Is it ok?

### ISSUE THREAD

**Issue by radekvermirovsky** [valhalla/valhalla#4571]
Hello, when the 'ignore_restrictions' option is set for truck routing, it disregards factors such as 'maxheight' and 'maxweight.' These are critical real-world physical restrictions that cannot be overlooked as they could lead to dangerous situations (hitting bridge e.g.). If someone wants a truck route where 'maxweight' or 'maxheight' is ignored, they can simply make a request where heigh and weight for vehicle is set to 0. Therefore, my question is: shouldn't these 'maxweight' and 'maxheight' restrictions still be adhered to even when 'ignore_restriction' is enabled for truck routing?

**Comment by nilsnolde** [comment]
IMO this makes perfect sense, especially considering your notion of "setting them to 0" in case it's really really wanted, so no functionality is actually lost. It's a one-line change too. Also it's not a documented costing option.

So +1 from my side:)

**Comment by nilsnolde** [comment]
just to make it more obvious that we'd need to take another path than we thought: https://github.com/valhalla/valhalla/pull/4574#issuecomment-1938794889.

**Comment by kevinkreiser** [comment]
yeah just to spell it out here as well, `ignore_restrictions` is meant to ignore any restrictions. if you are using it and expect it to respect certain restrictions then you misunderstand what it is meant to do, and fair enough, i didnt document it but it needs to continue to work the way it has if not only to at least live up to its name. if there are specific restrictions we want to ignore we could make options to target those. this could get quite cumbersome to maintain but this is how it is.
