### ISSUE TITLE
error in docs

### ISSUE THREAD

**Issue by uint64-t** [valhalla/valhalla#4586]
https://github.com/valhalla/valhalla/blob/master/docs/docs/tiles.md
-------------------------------
Get the Level or Hierarchy
get_tile_level(73160266) returns a level of 2. 73160266 is a Valhalla Graphid.
get_tile_level(142438865769) returns a level of 1. 142438865769 is an Open Traffic Segment id.

should be

Get the Level or Hierarchy
get_tile_level(73160266) returns a level of 2 is a Valhalla Graphid.
get_tile_level(142438865769) returns a level of 1 is an Open Traffic Segment id.

?
------------------------------

**Comment by nilsnolde** [comment]
>  142438865769 is an Open Traffic Segment id.

can't say much about this, not sure what open traffic segment id's exactly represent, but it looks off. probably it should also say `is a Valhalla Graphid`.

other than that: no, your sentence doesn't really make sense grammatically, neither semantically. that function _returns a level_ and _takes a graphid_.

**Comment by kevinkreiser** [comment]
this makes me want to do mass deletion of parts of our docs :smile: 

there has to be a better way to document software. to me there are like 2 major things:

1. the philosophy/strategy/purpose of a section of the library
2. the technical documentation for the classes/methods/free functions the implement the former

the latter is easily generated from comments in the code. the former needs writing and organization. i suppose the former is the place where we fail the most. would be interesting to have a "coverage" ci integration that reports how many p ublic apis have a docstring. we could at least work toward patching up the latter. the former needs time and energy

**Comment by nilsnolde** [comment]
> this makes me want to do mass deletion of parts of our docs

yeah, same.. I think it's really noble to do 1. and when starting a project it's fun to do and one has lots of energy for it, just before reality creeps in :D  then it will rot, especially a OSS project of only volunteers. I'd be happy to remove the vast majority of docs as well.

2. (or the lack thereof) is also annoying me a lot, but it's much easier to maintain and we all have a (at least future-us) self-interest in it. I think it got a lot better these days no? we seem to pay more attention with incoming PRs. lots of legacy stuff no one wants to do I guess :D

**Comment by uint64-t** [comment]
@nilsnolde 
But, is there  something wrong with the return value ?
------
get_tile_level(73160266) returns a level of 2. 73160266 
get_tile_level(142438865769) returns a level of 1. 142438865769 

should be

get_tile_level(73160266) returns a level of 2 
get_tile_level(142438865769) returns a level of 1 
-----

**Comment by uint64-t** [comment]
My mistake, I mistook the period as the decimal point of a floating point number.

  2. 73160266  => 2.73160266
