### ISSUE TITLE
geos packaging problem on 20.04

### ISSUE THREAD

**Issue by akifaktas** [valhalla/valhalla#4595]
Hi,

I'm currently at this stage in the Valhalla installation:

But I'm getting this error message, and I've tried everything here. The strange thing is that the geos package is installed on my machine.
Command:
` cmake ..   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_INSTALL_PREFIX=/usr   -DENABLE_BENCHMARKS=OFF
`
Response:
```
-- Configuring in release mode
-- Using protoc from /usr/bin/protoc
-- Using pbf headers from /usr/include
-- Using pbf libs from /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
-- Using pbf-lite
-- Found SQLite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- pybind11 v2.11.1 
-- Installing python modules to /usr/lib/python3/dist-packages
-- Checking for module 'geos'
--   No package 'geos' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  CMakeLists.txt:282 (pkg_check_modules)
```
  
 When I type find /usr -name "geos" into the terminal, it returns /usr/include/geos as the answer.

How can I overcome this issue? Thanks in advance.

**Comment by kevinkreiser** [comment]
`pkg-config` doesn't seem to see that you have geos installed. this command should show the version of geos installed:

    pkg-config --modversion geos

if it doesnt then you probably need to modify your `PKG_CONFIG_PATH` to include the location your geos is installed in

**Comment by nilsnolde** [comment]
What OS are you on? I’d hope that a pkg-config installation by default looks at the relevant paths for your OS or even all expected ones across distros.. I moved those things to pkg-config to make it more stable not less😅

**Comment by nilsnolde** [comment]
hmpf, this is a packaging problem on ubuntu/debian where both 22.04 & buster don't give you the .pc file in the `libgeos-dev` package:
https://pkgs.org/search/?q=libgeos-dev

previously we had our own FindGEOS.cmake file, but for the sake of maintenance, we moved to pkg-config. it's not hard to produce one yourself, but does require you to have a bit of knowledge around pkg-config/building.

or restore the FindGEOS.cmake file I removed here: https://github.com/valhalla/valhalla/pull/4253/files#diff-7602a77b86cd6ad607b9dbdf18a98271388970edd6a75137fc340297a8d0214e. and change the relevant line in our cmakelists.txt (basically revert that PR for geos).

**Comment by akifaktas** [comment]
Since the recent change you mentioned, I installed the previous version 3.3.0, and the issue was resolved. Thank you.

**Comment by nilsnolde** [comment]
3.4.0 will also work, though the difference isn’t that crazy. It’s a shame though.. lots of improvements in the past year. I’d consider a docket deployment, that just brings its own OS and removes that hassle.

**Comment by WindCrafter** [comment]
> Since the recent change you mentioned, I installed the previous version 3.3.0, and the issue was resolved. Thank you.

Can you give me instructions to install version 3.3.0? I'm new and stuck in the same situation. 

```
Sorting... Done
Full Text Search... Done
libgeos++-dev/focal,now 3.8.0-1build1 amd64 [installed]
  Geometry engine for GIS - C++ development files

libgeos-3.8.0/focal,now 3.8.0-1build1 amd64 [installed,automatic]
  Geometry engine for Geographic Information Systems - C++ Library

libgeos-c1v5/focal,now 3.8.0-1build1 amd64 [installed,automatic]
  Geometry engine for Geographic Information Systems - C Library

libgeos-dev/focal,now 3.8.0-1build1 amd64 [installed]
  Geometry engine for GIS - Development files

libgeos-doc/focal 3.8.0-1build1 all
  Documentation for the GEOS GIS geometry engine library
```

**Comment by nilsnolde** [comment]
For anyone running into this, just put this into `/usr/lib/pkgconfig/geos.pc`:
```
prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: GEOS
Description: Geometry Engine, Open Source - C API
Requires:
Version: 3.12.0
Cflags: -I${includedir}
Libs: -L${libdir} -lgeos_c
Libs.private: -lgeos -lstdc++ -lm
```

Then it'll just work
