### ISSUE TITLE
Unknown: Failed to parse intermediate request format

### ISSUE THREAD

**Issue by maakbaas** [valhalla/valhalla#4616]
If I try routing for many different coordinates I get:

{"error_code":299,"error":"Unknown: Failed to parse intermediate request format: Failed parsing pbf in Odin::Worker","status_code":400,"status":"Bad Request"}

One example is with the coordinate pair 53.83468, 10.61468 => 53.80018, 10.76709

I get this error when using the API on the free server https://valhalla1.openstreetmap.de

also reproducible in the web GUI with the url below:

https://valhalla.openstreetmap.de/directions?profile=car&wps=10.61475996%2C53.83483992%2C10.767828835733347%2C53.8008617

![image](https://github.com/valhalla/valhalla/assets/57539443/1736a14c-abd5-4826-8d49-a1a83154fc6a)

I don't have a local instance running (yet) with the same map so I am not able to verify if this is actually an issue here, or if it is an issue with how the FOSSGIS server is set up. But maybe somebody can verify this for me, or maybe somebody from the FOSSGIS team is reading along? Could this be related to issue #4600?

**Comment by nilsnolde** [comment]
> Could this be related to issue https://github.com/valhalla/valhalla/issues/4600?

jep, it is, but I didn't find the time yet to update the server. will happen soon.
