### ISSUE TITLE
Missing predecessor opp edge in DynamicCost::AllowedReverse

### ISSUE THREAD

**Issue by alexey-gl** [valhalla/valhalla#4617]
Working with custom "allow" logic based on current and predecessor edges I realize that for reverse search `DynamicCost::AllowedReverse` method missed info about opposing predecessor edge (i.e. the edge, that actually will leads from origin to destination in result route and which actually should be taken into consideration here).

By the way method comment say that it should be:
`...Both opposing edges (current and predecessor) are provided....`
But method attributes missed it.
https://github.com/valhalla/valhalla/blob/6648fb9e83e9e850f3a225b1c64d5d74c98a5ce9/valhalla/sif/dynamiccost.h#L245-L270

Also looking at another reverse search costing method `DynamicCost::TransitionCostReverse` I see that both `opp_edge` and `opp_pred_edge` which leads from origin to destination during reverse search are provided.
https://github.com/valhalla/valhalla/blob/6648fb9e83e9e850f3a225b1c64d5d74c98a5ce9/valhalla/sif/dynamiccost.h#L381-L401

For my need I actually looking for `opp_pred_edge graphId`.

Please correct me if I missed smth, but it looks like `DynamicCost::AllowedReverse` interface should be extended.

**Comment by nilsnolde** [comment]
> By the way method comment say that it should be:
...Both opposing edges (current and predecessor) are provided....
But method attributes missed it.

It's not missing it, you get both _edges_ in the `AllowedReverse` method, it's necessary for u-turn detection. 

> For my need I actually looking for opp_pred_edge graphId.

So you want the _predecessor_ opposing edge ID. You already have that, it's part of the predecessor's `EdgeLabel` interface.

I don't think anything is missing here. However, there's still a few problems in reverse search currently I think, e.g. https://github.com/valhalla/valhalla/issues/4456.

**Comment by alexey-gl** [comment]
@nilsnolde 
Thank's a lot! I've found it finally.
It is part of `BDEdgeLabel` interface and it is necessary to cast `const EdgeLabel& pred` in AllowedReverse before it is available. That's why I missed it at first.

Actually why don't `DynamicCost::AllowedReverse` need this cast and doesn't have `BDEdgeLabel` pred param type?

**Comment by nilsnolde** [comment]
Only some algos are using AllowedReverse() and BDEdgeLabel, but when they are, they pass it in as such, no casting necessary. Sounds you should use BDEdgeLabel to begin with?

**Comment by alexey-gl** [comment]
@nilsnolde 
I mean when I read `pred` value in `MyCustomCost::AllowedReverse` it comes here as `EdgeLabel`.
Algos send value as `BDEdgeLabel` and to read `BDEdgeLabel.opp_edgeid()` I have to cast incoming pred value to `BDEdgeLabel` (don't sure always is ok?)
If I understand you correctly.

```
// Checks if access is allowed for an edge on the reverse path (from
// destination towards origin). Both opposing edges are provided.
bool MyCustomCost::AllowedReverse(const baldr::DirectedEdge* edge,
                               const EdgeLabel& pred,   // <---- algos send BDEdgeLabel here (always?)
                               const baldr::DirectedEdge* opp_edge,
                               const graph_tile_ptr& tile,
                               const baldr::GraphId& opp_edgeid,
                               const uint64_t current_time,
                               const uint32_t tz_index,
                               uint8_t& restriction_idx) const {
}
```
