### ISSUE TITLE
mismatch comparing elevation stored in edges and elevation sampled from raw data

### ISSUE THREAD

**Issue by 333bkz** [valhalla/valhalla#4618]
**`api:route`** 
request json :
`{"locations":[{"lat":22.668295,"lon":114.14179,"radius":10},{"lat":22.666619,"lon":114.144737}],"costing":"bicycle","costing_options":{"bicycle":{"avoid_bad_surfaces":0.25,"bicycle_type":"Road","bss_return_cost":0,"cycling_speed":20,"gate_cost":30,"gate_penalty":300,"maneuver_penalty":5,"service_factor":1.0,"service_penalty":15,"shortest":true,"use_ferry":0.0,"use_hills":1.0,"use_living_streets":1.0,"use_roads":0.5}},"elevation_interval":30,"shape_match":"map_snap"}`
response shape:
`gfqfj@ahtuxEzY{bAnHsStGwOjHiO|IqOfJqNtJmMxCcD|GiD~FoBd@I`
response elevation:
`[53.7,53.3,52.8,51.7,50.1,49.6,50.6,51.3,51.1,50.4,50.5,51.8,52.5,52.6]`

**`api:height`**
response elevation:
`[54.3,50.4,49.9,51.0,51.6,51.1,50.7,51.4,52.2,52.8,53.0,53.0]`

the shape points size is 12  not equal elevation array size,  and shape first point elevation is 54.3 , last point elevation is 53.0.

**Comment by 333bkz** [comment]
What I'm trying to say is that the elevation data doesn't match the route points

**Comment by kevinkreiser** [comment]
i havent the time right now to check this out but i will say the way in which the elevation delivered to you is vastly different between the two requests. the first request gets the elevation that we store within the edges themselves where as the second gets it by sampling the raw elevation data directly.

in the former we sample the raw elevation at regular intervals along the edge geometry where as the latter samples the raw elevation data directly. you omitted the request for the latter, did you set the "resample" interval to 30 to match what you are doing in the map matching one? if they arent sampled at the same interval there will certainly be a difference. and yes respampling will cause the number of points to differ from the shape you input. the height api docs should explain this

**Comment by 333bkz** [comment]
Thanks. I like this new feature. I will try to solve this problem myself
