### ISSUE TITLE
Map Matching Service for GPS Tracks from Trams

### ISSUE THREAD

**Issue by jolumat** [valhalla/valhalla#4627]
Hi, 
I have a raw GPS track that I would like to map match. The data was recorded from a tram. Unfortunately, there is no costing model explicitly for trams, so the matching is very unreliable in areas where the track runs on its own route. Is it possible to implement a costing model for map matching GPS tracks from trams? As far as I know there is an OSM railway tag for trams.
Best regards

**Comment by nilsnolde** [comment]
as per [our docs](https://valhalla.github.io/valhalla/api/map-matching/api-reference/#costing-models-and-other-options), multimodal costings aren't supported:
> Costing for multimodal is not supported for map matching because it would be difficult to get favorable GPS traces.

that statement isn't true for trams of course, but that's also just a very very minor subset of transit options.

also we're not dealing with OSM transit things (no timetables etc), we're using (static) GTFS.

you might have some luck with this one: https://ad-publications.cs.uni-freiburg.de/theses/Bachelor_Michael_Fleig_2021.pdf. but even there, GTFS rules.
