### ISSUE TITLE
Custom Loss for Routing

### ISSUE THREAD

**Issue by cmb87** [valhalla/valhalla#4639]
Hello,
from viewing the documentation I'm not certain if the desired feature also works with realtime traffic as workaround. I'm looking for a routing engine with mobile coverage as constraint. So a way segment with no coverage should get a very high loss. Is this possible with Valhallah?

**Comment by nilsnolde** [comment]
loss=cost I assume?

hm sure you could use live traffic for that. just keep in mind that it’s a certain scale since it assumes it’s a speed value. 

for such static data it’s better to push it directly into the OSM PBF and have a valhalla fork which is customized to be able to read this property and make use of it during costing. it’s a low-medium effort if you perfectly know what you’re doing, but can easily become herculean if not. if that’s more interesting to you, I’d recommend to look at some past PRs which implemented new costing options, and maybe some which implementing parsing new props out of the PBF. 

in any case you’re largely on your own, but you can try to ask for support in **Discussions** if you should have any questions.

**Comment by cmb87** [comment]
Hi nilsnolde,
cost I meant, right. Thank you very much for confirming. I fear since mobile coverage is also quite time dependent, I have to go through the live traffic data. In the documentation, it is said that live updates happen through a file called traffic.tar. Is there a minimalistic example or similar how to bring in custom traffic data?
I only found this one:

https://github.com/alinmindroc/valhalla_traffic_poc

In any case thank you very much and very nice project!!

**Comment by nilsnolde** [comment]
> I fear since mobile coverage is also quite time dependent

oh really?! data transfer rate I could imagine, kinda usage patterns of people. live traffic would be hard then. better to use the historical “traffic” patterns. the repo you link to is certainly the most hands-on example, but last time I looked at it it had quite a few important omissions. there’s also tests in this repo, but also needs digging into the c++ sources.

**Comment by cmb87** [comment]
You're right. It's more about the data transfer pattern. It is for a mobile platform navigated remotely. Since it also contain cameras data transfer is important and I cannot allow routing through areas with bad transfer rates. Hence the idea to penalize edges where I know (from measurements) that the connection is bad. I previously checked out pgRouting, but I wasn't so happy with the performance and the low leveliness. Although, I liked that you could influence directly in the database. Alright, I'll give it a try with the demo repository from above. I got it running. I just need to figure out how to build that automatic data ingestion from my measurements.

**Comment by nilsnolde** [comment]
it's an interesting problem for sure. if you have your measurement as lat/lon, you can call /locate to get the closest road segment, grab its "edgeid.value" (some crazy long number) and use that to generate the "historical speed" with some normalized "speed" value(s) (0 - 255 with 2 resolution, i.e. 7 bit, is what's available). we support up to 5 mins bins for the whole week, i.e. 2016 values. once you got your own "per edge" normalization figured out (I guess there could be many observations per road segment), it's just a matter of writing an executable which will alter the graph tiles properly with your measurements. the thing you'll specifically want to pay attention to are shortcuts which need extra handling. that's the worst omission in that repo you were referring to.

for smaller regions and a faster TTL you could also try `exclude_locations` which allows inputting points on road segments you want to avoid. if those are in the few hundred segments and you can live without proper costing (i.e. either take it or not, not avoiding/favoring), that's likely the fastest way, both prep and runtime. then you'd control the time dimension client-side.

**Comment by cmb87** [comment]
This pretty much sounds like a plan to try. I also discovered "avoid_locations" which could be a very nice solution for regions, where there's constantly no coverage (like tunnels). @nilsnolde thank you for this valuable input!
