### ISSUE TITLE
Map Matching Big Data with API

### ISSUE THREAD

**Issue by poonehfamili** [valhalla/valhalla#4648]
I was wondering if it's possible to send like millions of different trip for map matching with one api attempt? or for each trip we have to call 1 api?

**Comment by nilsnolde** [comment]
If you wanna use the HTTP interface, yeah, 1:1. Probably could concoct different trips with “break” locations where they start/end, but I doubt that’s a good idea. With the C++ or even Python interface that’d be more efficient than HTTP.
