### ISSUE TITLE
Time-Distance Matrix integration with Traccar

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#465]
(2016-12-24T09:09:28Z) @kirantpatil : originally created valhalla/thor#538

Is thor meant for Time-Distance Matrix calculation ?

We at Traccar(https://github.com/tananaev/traccar/issues/2629#issuecomment-269040670) would like to go for the preferred Open source alternative for Google Distance Matrix solution, since Traccar is complete Opensource solution.

We felt valhalla project would make more sense since it is part of opentraffic (https://mapzen.com/blog/announcing-open-traffic/).

This will encourage Traccar users to join the hands for bigger cause such as Opentraffic, since Traccar is used for fleet management in various countries.

We need your help on this and how to go forward for integration with Traccar.

Regards,
Kiran.

(2016-12-24T13:11:59Z) @dnesbitt61 : Thor has open source code for computing a time-distance matrix. It relies on other repositories within Valhalla as well. You can try using our hosted service at mapzen.com - sign up for a developer key if you would like. Documentation of the service API is here: https://mapzen.com/documentation/mobility/matrix/api-reference/.

If you would like to check out Valhalla and build it for local use you can look into the various Valhalla repos (including valhalla-docs). The best place to find instructions for running your own server instance is: https://github.com/valhalla/tools.

Note that time distance matrix does not yet include any traffic influence. This will not occur until the Open Traffic project is further along and we have integration points in Valhalla completed. 

(2017-01-03T07:18:29Z) @kirantpatil : Hello @dnesbitt61: Happy new year :) , 

Thanks for your detailed response.

Does Opentraffic project includes valhalla time distance matrix along with route with traffice data ?

In that case we would like to use Opentraffic API for both time distance matrix along with route with traffic data.

Any guess estimate when will this integration be done ?

Thanks.

(2017-01-03T16:44:32Z) @dnesbitt61 : The Valhalla project will include the ability to integrate data from Open Traffic into both routing and time distance matrix. We are early in the Open Traffic project work so it is hard to estimate when the routing integration will be ready, but I would not expect it before the middle of the year.

(2017-01-04T05:21:42Z) @kirantpatil : Thank you @dnesbitt61. I congratulate Valhalla project and Team for supporting the most important cause.

**Comment by dnesbitt61** [comment]
closing this for now. As we get closer to Open Traffic integration we can follow-up. In the meantime if you have other questions or issues feel free to contact us or open new issues.
