### ISSUE TITLE
src/thor/unidirectional_astar.cc has an issue

### ISSUE THREAD

**Issue by TheTonda** [valhalla/valhalla#4652]
issue : src/thor/unidirectional_astar.cc doesnt work for date_time type 2, i.e. for arrival

steps to recreate: just make any long route(idk roughly around 1500 kms) with speed_type = 2(arrival), it will say "no route found".

solution: so just update the line:

  float mindist = astarheuristic_.GetDistance(origin_new);

with this one:

  float mindist = astarheuristic_.GetDistance(FORWARD?origin_new:destination_new);

its a minor fix i know but installing stuff and lint checking was too much for this so I'm just gonna tell it here.

![image](https://github.com/valhalla/valhalla/assets/32519975/009b16d7-255a-4c7b-a1fe-efaf19875851)

P.S. tell me if I can skip the guidelines for this one, and I'll raise a PR.

**Comment by kevinkreiser** [comment]
im not sure what you mean by the guidelines but yeah just make a pr, we're happy for any bug fixes.

**Comment by TheTonda** [comment]
okay then I hope its cool, here is my very first PR.
