### ISSUE TITLE
Question: No rule for benchmarks / how to benchmark

### ISSUE THREAD

**Issue by MKLOL** [valhalla/valhalla#4658]
Hi, I'm trying to run the benchmarks. I tried:

```
cmake -B build -DENABLE_BENCHMARKS=On
make benchmarks
```
But I get 
```
make: *** No rule to make target `benchmarks'.  Stop.
```

Am I doing something wrong? 

Also secondary question, what's the easiest way to load an OSM.PBF and give it lots of (lat,lon) pairs and compute the distance for it (want to try to benchmark it). Don't want to get the extra directional stuff or have to send an HTTP request.

**Comment by nilsnolde** [comment]
We removed the benchmark stuff, it was pointless. Why not HTTP, that’s fine for _benchmarking_? If you want _performance_ you’ll need to use the c++ api. Look at “valhalla_run_route”.
