### ISSUE TITLE
Documentation on ManeuverType is outdated

### ISSUE THREAD

**Issue by erikvullings** [valhalla/valhalla#4666]
While using [Jelmer's Rust-based client](https://github.com/jelmer/valhalla-client-rs) to query Valhalla's routing interface, I received many JSON serialization errors due to the fact that not all `ManeuverType` options were implemented. As it turned out, however, even the [Valhalla API documentation](https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/#trip-legs-and-maneuvers) does not mention them all. The actual list of values, as implemented in the code, can be found [here](https://github.com/valhalla/valhalla/blob/58929bd063981c8a2d8544afa56b069d78afa495/proto/directions.proto#L90C6-L94C26). Therefore, please add the missing enum values to your documentation, specifically:

- kElevatorEnter (value 39)
- kStepsEnter
- kEscalatorEnter
- kBuildingEnter
- kBuildingExit

**Comment by chrstnbwnkl** [comment]
This was fixed in #4675
