### ISSUE TITLE
Bollard with `motor_vehicle=yes` are considered "private gate" whereas the road is public

### ISSUE THREAD

**Issue by xlqian** [valhalla/valhalla#4676]
hi, 

We have encountered a quite baffling use case when computing a pedestrian path in an area full of bollards(https://overpass-turbo.eu/s/1Jyc).

![image](https://github.com/valhalla/valhalla/assets/6093486/d306a20d-9d0d-4a6c-bed5-65db4c62af75)

In the above figure, Valhalla suggested a path which is way off what had been expected(the red highlighted path.)

My first guess was that the algorithm was avoiding all the bollards. By tracking down in the codes, I found that a bollard tagged with `bollard=rising` is considered as a gate and with  ~`motor_vehicle=yes`~ `motor_vehicle=destination`, it is considered as if it has private access, which led me to this piece of code:

https://github.com/valhalla/valhalla/blob/master/src/sif/pedestriancost.cc#L545

Transitions through these bollards are penalised as if they are private gates!
 
The problem is all these bollard nodes DO grant access to the public on foot :
![image](https://github.com/valhalla/valhalla/assets/6093486/9dbcf662-cb8c-451e-9705-df6cbc0f27a2)

https://wiki.openstreetmap.org/wiki/Key:foot?uselang=en

If I understand correctly, in this case, the public should be able to access these roads notwithstanding `private_access=true`

To fix this issue, I would suggest to add an access check to the code in question: 

```c++
    c += private_access_cost_ * (node->type() == baldr::NodeType::kGate) * node->private_access() * !(node->access() | kPedestrianAccess);

```

Please let me know your take. 

regards

**Comment by xlqian** [comment]
I re-review the Lua script, it seems my 2 cents fix will not work because it will shortcircuit the case where `foot=private`... 

IMO the real problem here is we should separate `private_access` based on travel mode...

**Comment by nilsnolde** [comment]
yeah, that problem we have with many DirectedEdge attributes.. lots of tags are mode dependent, but we can't really assign 12 bits to all of these attributes. and valhalla, for the better or worse, is mostly prioritizing motor vehicles. mostly that's a v4 thing though I suppose.

> I found that a bollard tagged with bollard=rising is considered as a gate and with motor_vehicle=yes, it is considered as if it has private access

slight correction: it'll only turn `private_access` if there's a `motor_vehicle=destination/private/etc` not with `yes`. that's beside the point though.. IMO `destination` access could be kinda safely ignored for ped & bike. but unfortunately we're conflating _actual_ private access (is relevant for ped/bike) with "destination/residents-only" (irrelevant for bike/ped IMO). but also here it's too late to revert that. I think we're stuck with your case unfortunately..

**Comment by xlqian** [comment]
> but unfortunately we're conflating actual private access (is relevant for ped/bike) with "destination/residents-only" (irrelevant for bike/ped IMO)


Can we do something like private_access_motorist,  private_access_other to kind of split the private_access? 

Could it be performance/memory impacting?

**Comment by nilsnolde** [comment]
We have 1-2 bits left on NodeInfo IIRC, so it’d be possible, but should be well justified. This feels a bit very edgy tbh. I don’t really understand why the node has to be “destination” and not the road it leads to. That feels mistagged no? A node can block access but how can it be destination-only? That’s a road property for me.

**Comment by xlqian** [comment]
>  That’s a road property for me 

you're right I will first remove that property.

**Comment by dnesbitt61** [comment]
I would say this cost should be configurable per costing type.

**Comment by nilsnolde** [comment]
I think that’s also a place where we conflate “private” & “destination_only”, just for edges instead of nodes.

A per costing option we have today already, at least for pedestrian. Bike though uses the base class method.

**Comment by xlqian** [comment]
I kind of get this problem sorted by deleting the tag `motor_vehicle=destination`.  thank you for the enlightenment
