### ISSUE TITLE
The difference between locate and trace_attributes api in determining way_id

### ISSUE THREAD

**Issue by helloln** [valhalla/valhalla#4678]
Hello, I would like to know if the algorithms used by locate and trace_attributes to determine the way id based on the input longitude and latitude coordinates are the same? Sometimes their results are different for the same coordinates。If not, what is the algorithm principle of locate api?

**Comment by kevinkreiser** [comment]
`locate` uses only distance from the input point to determine which edges are returned. in fact you can send it a radius and get multiple results.

`trace_attributes` uses distance as well as the locations inclusion in a sequence of points denoting a route (so think optimality of that edge when used with the rest of the edges near the other input points). it too allows you to specify a radius but in the end it will only end up using one edge. the maximum radius is smaller than for `locate` iirc

**Comment by helloln** [comment]
thanks for your prompt reply！

**Comment by helloln** [comment]
Sorry to bother you again. I have two more questions: 

1. the first one is whether the `heading` returned in `locate` api is begin_heading or end_heading? 
2. The second one is whether the longitude and latitude contained in the `shape` returned in `trace_attributes` is corrected? I see that in `matched_points`, each point has a lon and lat, and their values are different from my input. May I ask what is the difference between the longitude and latitude in shape and those in matched_points, and what scenarios are they suitable for?
