### ISSUE TITLE
optimized_route endpoint not working?

### ISSUE THREAD

**Issue by paula4230** [valhalla/valhalla#4680]
Hello! Is `optimized_route` still available? I tried to access it via `http://valhalla1.openstreetmap.de/optimized_route` but I only get the following error. If not, may I know which endpoint produces a similar result to get the shortest distance between three points? 

Note: I am not capable of self-hosting for now so I had to use `http://valhalla1.openstreetmap.de`.

```
<html>

<head>
    <title>404 Not Found</title>
</head>

<body>
    <center>
        <h1>404 Not Found</h1>
    </center>
    <hr>
    <center>nginx/1.18.0 (Ubuntu)</center>
</body>

</html>
```

**Comment by nilsnolde** [comment]
It has never been available over the public instance IIRC. But that’s probably a silly restriction, it’s hardly more expensive than just the matrix. If I remember I’ll update it soon. In the meantime you can always install Valhalla yourself.

**Comment by paula4230** [comment]
thank you @nilsnolde. I'll use the `/route` endpoint instead

**Comment by nilsnolde** [comment]
actually I enabled it a few hours ago:) so you should be able to use it now

**Comment by paula4230** [comment]
great! thank you!
