### ISSUE TITLE
Retrieving Country-specific Distances for Cross-border Routes in API Response

### ISSUE THREAD

**Issue by nemi60596** [valhalla/valhalla#4685]
I am currently working with routes that cross international borders and am interested in a specific feature of the Valhalla routing API. I would like to know if there is an existing functionality or a possible method within the API that allows users to determine the distance traveled within each country for a given route. Specifically, is it possible to tag each maneuver in the route response with the country it occurs in, enabling the calculation of total distance traveled within each country?

This feature would greatly aid in detailed route analysis and planning. If it is not currently available, could you please advise on any potential workarounds or if there are plans to include such a feature in the future?

**Comment by nilsnolde** [comment]
hm, you could use /trace_attributes of the final route to retrieve the admin indices (look at the docs, or do a trace_attributes request and look at the response), then sum up the lengths of all edges with same admin index.

or do it yourself in a GIS-y application where you intersect e.g. natural earth country polygons with the route. though do note, we infer our own country/state geometries from OSM, which might or might not be the same thing, but I guess it matters little in the end.
