### ISSUE TITLE
question about heading in locate api and shape in trace_attributes api

### ISSUE THREAD

**Issue by helloln** [valhalla/valhalla#4691]
Sorry to bother you again. I have two more questions:

1. the first one is whether the heading returned in locate api is begin_heading or end_heading?
2. The second one is whether the longitude and latitude contained in the shape returned in trace_attributes is corrected? I see that in matched_points, each point has a lon and lat, and their values are different from my input. May I ask what is the difference between the longitude and latitude in shape and those in matched_points, and what scenarios are they suitable for?

**Comment by nilsnolde** [comment]
1. pretty sure it's the heading where the point correlates to on the edge in the direction of the edge
2. matched_point lat/lon should coincide with the final shape's lat/lon. but of course your input could be somewhere entirely else, we just snap the input to the closest edge/node which is the only thing we know about, so naturally they're usually not the same.
