### ISSUE TITLE
bad_alloc when building tiles

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#470]
(2017-01-18T23:17:52Z) @ptpt : originally created valhalla/mjolnir#593

While building tiles of North America http://download.geofabrik.de/north-america-latest.osm.pbf I got bad_alloc error.

```
2017/01/18 20:12:34.354834 [WARN] Admin db /data/valhalla/admin.sqlite not found.  Not saving admin information.
2017/01/18 20:12:34.354945 [WARN] Time zone db /data/valhalla/tz_world.sqlite not found.  Not saving time zone information.
2017/01/18 20:12:34.355502 [WARN] Admin db /data/valhalla/admin.sqlite not found.  Not saving admin information.
2017/01/18 20:12:34.355532 [WARN] Time zone db /data/valhalla/tz_world.sqlite not found.  Not saving time zone information.
2017/01/18 20:26:27.457509 [WARN] Too many names for edgeindex: 47016886
2017/01/18 20:48:39.866449 [INFO] Finished
2017/01/18 20:48:42.839487 [INFO] Enhancing local graph...
2017/01/18 20:48:42.846741 [WARN] Admin db /data/valhalla/admin.sqlite not found.  Not saving admin information.
2017/01/18 20:48:42.846770 [WARN] Admin db /data/valhalla/admin.sqlite not found.  Not saving admin information.
2017/01/18 21:35:42.191780 [INFO] Finished with max_density 29.820465 and unreachable 300669
2017/01/18 21:35:42.195163 [INFO] Transit directory not found. Transit will not be added.
2017/01/18 21:35:42.196260 [INFO] HierarchyBuilder
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Memory usage in the beginning of building:

```
ubuntu-16.04:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.9G        1.6G         43M         20M        2.3G        2.2G
Swap:            0B          0B          0B
```

Does it use up all 4GB memory? Is it possible to limit its memory usage?

(2017-01-19T00:16:53Z) @dnesbitt61 : Could be that it uses up that much memory - when we redesigned the HierarchyBuilder we did not take pains to make sure it works in low memory environments. We will take a look and see if there are obvious ways to reduce memory.

**Comment by dnesbitt61** [comment]
Investigating use of sequence to replace the unordered_map that associates original nodes with nodes across the hierarchies. This should reduce memory - need to validate performance on larger datasets.

**Comment by Melegy90** [comment]
@dnesbitt61 Good day! I see you've fixed this in a PR however I'm still facing the same error on an Ubuntu server with 2 GB Ram, however the pbf I'm trying to build the tiles for is fairly limited, and there is no option for extending the server specs at the moment.

Is there any optional parameters I can pass in that command that allows it to run with lower memory?

**Comment by dnesbitt61** [comment]
If this is running out of memory in the Hierarchy Builder stage you can set config options to disable hierarchies and shortcuts. Under the mjolnir section of hte config JSON set:
"hierarchy": false,
"shortcuts":false,
That may allow the OSM import and tile building to succeed. Longer driving routes may be slower to compute without shortcuts but should work.

**Comment by dnesbitt61** [comment]
If this is occurring in the Hierarchy builder stage you can try disabling this by updating your config JSON. Under the mjolnir section set:
"hierarchy": false,
"shortcuts": false,
This disables the creation of hierarchy levels and shortcuts which can lead to slower computation of longer driving routes but it still should work.
