### ISSUE TITLE
Feature request: ignoring roads/road blocks

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#471]
(2017-01-19T08:04:12Z) @BobbyBlue42 : originally created valhalla/thor#543

Hi there,

I'm currently looking for a mapping service to use for a project, and one of the things that are critical for this project is the ability to set certain roads as unusable, if required. Do you think this is a feature that could be implemented anytime soon? Or have I possibly missed some easy way to do this with the current API?

Thanks for your help,
Louis

(2017-01-19T14:07:33Z) @dnesbitt61 : There is not currently any way to do this outside of a custom code either to mark roads on data import as impassible. We will take this as a possible feature addition - though ways to communicate which road to avoid using an API is going to be tricky.

(2017-01-20T00:16:52Z) @BobbyBlue42 : I mean, I'm not an expert in APIs by any means, but would it perhaps be possible to add another parameter to the request such as "roadBlocks":[{"lat":32.9853,"lon":46.5371}], then find which road segment those co-ordinates lie on and mark it as impassible?

(2017-01-20T15:59:10Z) @dnesbitt61 : The seems reasonable but there are some potential issues/considerations.
1) Cost - a per request addition of a large number of road blocks would impact performance in a hosted system. Each lat,lon to edge lookup/search takes a couple ms so for our hosted service we would need to limit the number. One danger is users might think they could just gather lists of closed roads and pass them in on each request (even if the road block is nowhere near where the route is). What is the maximum number of road blocks you would need? We would most likely have a small limit (say 25) at the start.
2) Imprecision of lookup. Unless lat,lon positions are taken from OSM maps there is a danger of selecting the wrong road (creating support questions/issues).
3) Shortcut edges - we utilize shortcut edges for performance. We do not search for shortcut edges and adding them to the search/lookup may be complicated.
4) Need to hook the road block list into each of our costing methods. Maybe could be done in the base class.
5) Time needed for documentation and testing. We have other priorities right now - if you'd like to contribute to Valhalla open source feel free to offer and we can collaborate on this feature?

(2017-01-21T10:02:46Z) @BobbyBlue42 : Those are some very valid points you made. Unfortunately I don't really have any experience with C++ yet, let alone have any real idea where or how to start adding this sort of functionality, otherwise I would be more than happy to work with you for this.

**Comment by dnesbitt61** [comment]
We have added code in Valhalla to allow a client to pass in a list of "avoid_locations". We will be documenting this features and releasing it in the near future (perhaps as early as next week).

**Comment by dnesbitt61** [comment]
avoid_locations options has been pushed to production. Let us know if this works for you or if you have any follow-on questions.
