### ISSUE TITLE
Null Distance and Time but success=true response

### ISSUE THREAD

**Issue by paula4230** [valhalla/valhalla#4715]
Hello, is it possible for the `matrix` endpoint to have null distance and time results while having a `success=true` response? I initially thought that the happy path for it would be distance and time, but I just wanted to confirm and we'll handle it gracefully on our end.

<img width="1068" alt="Screenshot 2024-05-02 at 10 01 18 PM" src="https://github.com/valhalla/valhalla/assets/75438634/8c941241-4344-4965-8f61-10e05b40a87a">

**Comment by nilsnolde** [comment]
technically I think this should be a 404 or 400, but we don't have special logic for all routes failing (yet). could be added. maybe I'll do that real quick.

**Comment by paula4230** [comment]
got it, thank you @nilsnolde! 
placing the coordinates here also

`"to_address"=>{"latitude"=>"14.626294", "longitude"=>"120.987544"}, "from_address"=>{"latitude"=>"14.562013", "longitude"=>"121.040571"}, `
