### ISSUE TITLE
Isochrone API bug?

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#472]
(2017-01-20T03:19:18Z) @araichev : originally created valhalla/thor#546

Hi folks,

I used the Mapzen Mobility Explorer to draw walking isochrones:

https://mapzen.com/mobility/explorer/#/isochrones?bbox=174.74570274353027%2C-36.86698689106876%2C174.87616539001465%2C-36.82769917684917&isochrone_mode=pedestrian&pin=-36.84466680273936%2C174.7675895690918

Then i inspected the GET request used:

https://matrix.mapzen.com/isochrone?api_key=mapzen-jLrDBSP&json={"locations":[{"lat":"-36.84384255163255","lon":"174.76744794897968"}],"costing":"pedestrian","denoise":0.3,"polygons":true,"generalize":50,"costing_options":{"pedestrian":{"use_ferry":0}},"contours":[{"time":15},{"time":30},{"time":45},{"time":60}]}

Why is there the option {"use_ferry":0} in pedestrian costing?
Its use is undocumented at https://mapzen.com/documentation/mobility/turn-by-turn/api-reference/#pedestrian-costing-options.
It is also counterintuitive, because ferry is a transit mode.
Moreover, reissuing the request without the ferry option, yield isochrones far into the water, which seems to indicate that taking the ferry is a default option for walking isochrones.
Huh?

(2017-01-20T14:38:22Z) @dnesbitt61 : We will update documentation. use_ferry is documented for auto costing so you can reference its meaning here.

As for ferry being a transit mode, we get most ferries from OSM (without schedules) so routes of any type (not just multimodal) will generally use them. We may revisit this in the future when there are enough ferries with schedules obtained via GTFS imports.

**Comment by dnesbitt61** [comment]
Closing - I believe this was addressed with #705
