### ISSUE TITLE
Inconsistency in graph.lua for motor_vehicle_node["official"]

### ISSUE THREAD

**Issue by michaelhrabanek** [valhalla/valhalla#4723]
Looking at https://github.com/valhalla/valhalla/pull/4650 every other "official" mask for nodes was changed to 1, with exception of motor_vehicle_node, I guess it's just oversight.

**Comment by chrstnbwnkl** [comment]
Good catch! Although probably relevant only in few cases since `<access_mode>=official` is mostly thought for pedestrian/bicycle lanes, and discouraged in favor of something like `<access_mode>=designated` (https://wiki.openstreetmap.org/wiki/Tag:access%3Dofficial)
