### ISSUE TITLE
Question: Obtaining road data for a computed route?

### ISSUE THREAD

**Issue by thomthom** [valhalla/valhalla#4733]
Given a route computed with `route` I would also like to do some analysis on the road data for the calculated route. `route` itself doesn't appear to provide that, just a polyline of the geo locations.

But `trace_attributes` appear to yield the data that would be useful. However, would it be reliable to take the route positions from `route` and feed it into `trace_attributes`? Given that `route` would presumably return precise coordinates for the underlying data would `trace_attributes` reliably yield the map data for that route?

What made me wonder is that it takes a costing model. And while `route` accepts `motorcycle`, `trace_attributes` doesn't appear to support that. Could that result in data for different roads being returned?

Any other way to achieve this?

**Comment by chrstnbwnkl** [comment]
You can have a look at the [`shape_match`](https://valhalla.github.io/valhalla/api/map-matching/api-reference/#shape-matching-parameters) parameter that gives you control over the matching algorithm. You can use `edge_walk` for feeding the output shape from `route` back into the map matching. Regarding the missing of `motorcycle`  costing, I think that's just the docs being outdated, it should be supported for the map matching as well.

**Comment by thomthom** [comment]
Ah! I had missed that last sentence in the doc!

> so it should only be used when the shape is from a prior Valhalla route.

Thanks for clarifying! I'll see if I can contribute with some doc updates when I get back from my upcoming travel.
