### ISSUE TITLE
Request information on "ProcessTurnLanes" function

### ISSUE THREAD

**Issue by mkandulavm** [valhalla/valhalla#4740]
Hi 

I request on how ProcessTurnLanes works as I am finding it difficult to understand what it is doing.

here is a sample request
{"alternates":0,"costing":"auto","costing_options":null,"directions_options":{"units":"miles"},"locations":[{"lat":52.4913,"lon":13.2951},{"lat":52.4883,"lon":13.3041}]}

here is the route formed with it
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=52.49130%2C13.29510%3B52.48830%2C13.30410

I am printing the turn lanes information for each maneuver's segment (each segment is separated by ' -> '

0:  -> left|through|through|through ->  ->
1:  ->  -> left|left|through|through|through -> left|left -> left|left -> left&through|right ->  ->  ->  ->
2:  ->  -> left|through|through|right -> left|through|through|through|right -> left|through|through -> left|through|through ->  ->  ->  -> left|left|through|through|through ->  ->
3:  ->

I am not able to map this information to the actual route as I cross check it in openstreetmaps.org/edit and satellite image from google maps.

This is the function, I am using to collect and print the information.
``
//code
   std::vector<std::string> ManeuversBuilder::GetTurnLanes(std::list<Maneuver> &maneuvers) {
      std::vector<std::string> turn_lanes;
  
      int manID = 0;
      auto curr_man = maneuvers.begin();    
  
      while (curr_man != maneuvers.end()) {
          std::string maneuver_turn_lanes = "";
          std::string active_turn_lanes = "";
  
          if (curr_man->travel_mode() == TravelMode::kDrive) {
              for(int nidx = curr_man->begin_node_index(); nidx <= curr_man->end_node_index(); nidx++) {
  
              //auto prev_edge = trip_path_->GetPrevEdge(curr_man->begin_node_index());
              auto prev_edge = trip_path_->GetCurrEdge(nidx);
              if (prev_edge && (prev_edge->turn_lanes_size() > 0)) {
                  const auto &turn_lanes = prev_edge->turn_lanes();
                  for (const auto &turn_lane : turn_lanes) {
                      std::string lane_directions = "";
                      int dir_mask = turn_lane.directions_mask();
                      for (const auto &ttype : kTurnLaneNames) {
                          if (dir_mask & ttype.first) {
                              if (!lane_directions.empty()) {
                                  lane_directions += "&";
                              }
                              lane_directions += ttype.second;
                          }
                      }
                      maneuver_turn_lanes += lane_directions + "|";
  
                      int active_direction = turn_lane.active_direction();
                      if (dir_mask & active_direction) {
                          if (kTurnLaneNames.find(active_direction) != kTurnLaneNames.end()) {
                              if (!active_turn_lanes.empty()) {
                                  active_turn_lanes += "|";
                              }
                              active_turn_lanes += kTurnLaneNames.find(active_direction)->second;
                          } else {
                              if (!active_turn_lanes.empty()) {
                                  active_turn_lanes += "|";
                              }
                              active_turn_lanes += "*" + std::to_string(active_direction);
                          }
                      }
                  }
  
                  if (!maneuver_turn_lanes.empty()) {
                      maneuver_turn_lanes.pop_back(); // remove the last '|'
                  }
                  if (!active_turn_lanes.empty()) {
                      //std::cout << manID++ << ": " << maneuver_turn_lanes << "#" << active_turn_lanes << std::endl;
                  }
              }
              maneuver_turn_lanes += " -> ";
              }
          }
          turn_lanes.push_back(maneuver_turn_lanes);// + "#" + active_turn_lanes);
  
          curr_man++;
      }
  
      //print turn lanes
      for (int i = 0; i < turn_lanes.size(); i++) {
          std::cout << i << ": " << turn_lanes[i] << std::endl;
      }
      return turn_lanes;
  }

``

**Comment by nilsnolde** [comment]
> https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.49130%2C13.29510%3B52.48830%2C13.30410#map=16/52.4895/13.2955

you sure you're talking about the valhalla, not the osrm response?

**Comment by mkandulavm** [comment]
> > https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.49130%2C13.29510%3B52.48830%2C13.30410#map=16/52.4895/13.2955
> 
> you sure you're talking about the valhalla, not the osrm response?

I provided the link to refer the route and locations. The route is the same.

**Comment by mkandulavm** [comment]
my purpose is to extract the turn lanes information when the route is formed.

**Comment by mkandulavm** [comment]
Hi

I am posting a sample print where I took one of the maneuver and printing its osm id (as a link to open it)  and the edge->TurnLanesToString().   empty '->' indicate way not having turn lane information.

``

->  ->  ->  ->  ->  ->  -> https://www.openstreetmap.org/way/1099698929 : [ left;*through* ACTIVE | right ] -> https://www.openstreetmap.org/way/335462911 : [ *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | right ] -> https://www.openstreetmap.org/way/335462911 : [ left;*through* ACTIVE | right ] -> https://www.openstreetmap.org/way/335462911 : [ left | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE ] -> https://www.openstreetmap.org/way/355562350 : [ left | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE ] -> https://www.openstreetmap.org/way/355562350 : [ left | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE ] -> https://www.openstreetmap.org/way/1090272349 : [ *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE ] -> https://www.openstreetmap.org/way/4609242 : [ *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | right ] -> https://www.openstreetmap.org/way/4609241 : [ *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | *through* ACTIVE | right ] ->  ->  ->  ->  ->  ->  ->  ->  -> https://www.openstreetmap.org/way/320896582 : [ slight_left;slight_right | slight_right | slight_right ] -> https://www.openstreetmap.org/way/627460043 : [ slight_left;slight_right | slight_right | slight_right ] -> https://www.openstreetmap.org/way/627460043 : [ *through* ACTIVE | *through* ACTIVE | *through*;right ACTIVE | right ] -> https://www.openstreetmap.org/way/627460043 : [ *through* ACTIVE | right ] -> https://www.openstreetmap.org/way/627460043 : [ *through* ACTIVE | *through* ACTIVE | *through*;right ACTIVE ] -> https://www.openstreetmap.org/way/320896581 : [ slight_left;slight_right | slight_right | slight_right ] ->  -> https://www.openstreetmap.org/way/25185005 : [ *through* ACTIVE | *through* ACTIVE | *through*;right ACTIVE | right ] -> https://www.openstreetmap.org/way/25185005 : [ left | left | *through* ACTIVE | *through* ACTIVE | *through*;right ACTIVE ] ->  ->  -> https://www.openstreetmap.org/way/139880220 : [ *through* ACTIVE | *through* ACTIVE | *through*;right ACTIVE | right ] -> https://www.openstreetmap.org/way/25185008 : [ through | through | through;right | right ] ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  ->  -> #

``

here are the (some) observations, I request clarifications on

- way ID 1099698929
unable to interpret [left;*through* ACTIVE | right]  against the osm turn lanes "none|none|none|through|right"

- way ID 335462911
has 5 lanes in osm, but string shows only 4 lanes

2) way ID 320896581
out of [ slight_left;slight_right | slight_right | slight_right ]    does not indicate active  and also its implying only 3 lanes against 4 lanes present in the osm

I appreciate any insight please.

**Comment by mkandulavm** [comment]
update:
I narrowed it down to the following fact that during the triplegbuilder stage, in the function AddTripEdge(),
when the index is fetched with graphtile->turnlanes_offset(), its returning the turn lanes of previous edge which is couple of steps behind. 
I understand the concept that the string is stored with an offset, and the edges having similar turnlane strings are referred here. However, there seems to be a bug here. Still checking...
