### ISSUE TITLE
Valhalla installs *.pb.cc instead of *.pb.h as includes

### ISSUE THREAD

**Issue by JonasVautherin** [valhalla/valhalla#4759]
Similar to https://github.com/valhalla/valhalla/issues/4757, I am building `libvalhalla.so` with:

```sh
cmake -DENABLE_TOOLS=OFF -DENABLE_DATA_TOOLS=OFF -DENABLE_HTTP=OFF -DENABLE_PYTHON_BINDINGS=OFF -DENABLE_SERVICE=OFF -DENABLE_THREAD_SAFE_TILE_REF_COUNT=OFF -DENABLE_BENCHMARKS=OFF -DENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=ON -DENABLE_STATIC_LIBRARY_MODULES=ON -DENABLE_SINGLE_FILES_WERROR=OFF -DENABLE_ADDRESS_SANITIZER=OFF -DPREFER_SYSTEM_DEPS=OFF -DENABLE_GDAL=OFF -DENABLE_SERVICES=OFF -DCMAKE_INSTALL_PREFIX=valhalla/build/default/install -DCMAKE_PREFIX_PATH=$(pwd)/dependencies/build/default/install -Bvalhalla/build/default -Svalhalla
```

When I install it with `cmake --build valhalla/build/default --target install`, it appears to install `*.pb.cc` instead of `*.pb.h` in `include/valhalla/proto`:

```
% ls valhalla/build/default/install/include/valhalla/proto
api.pb.cc  common.pb.cc  directions.pb.cc  expansion.pb.cc  incidents.pb.cc  info.pb.cc  isochrone.pb.cc  matrix.pb.cc  options.pb.cc  sign.pb.cc  status.pb.cc  transit.pb.cc  transit_fetch.pb.cc  trip.pb.cc
```

Which then results in compilation errors in dependent projects, such as:

```
[ 50%] Building CXX object CMakeFiles/valhalla_wrapper.dir/api.cpp.o
In file included from /tmp/valhalla/build/default/install/include/valhalla/baldr/graphtile.h:6,
                 from /tmp/valhalla/build/default/install/include/valhalla/baldr/graphreader.h:14,
                 from /tmp/valhalla/build/default/install/include/valhalla/tyr/actor.h:8,
                 from /tmp/my-test/api.cpp:2:
/tmp/valhalla/build/default/install/include/valhalla/baldr/datetime.h:36:10: fatal error: valhalla/proto/common.pb.h: No such file or directory
   36 | #include <valhalla/proto/common.pb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Manually copying the `*.pb.h` in the installed `include` directory (`valhalla/build/default/install/include/valhalla/proto`) solves the problem. It seems to me that the headers should be installed instead of the sources.

Does it install the `*.pb.cc` and not the `*.pb.h` on purpose, or is that a bug in Valhalla's CMake configuration?

**Comment by kevinkreiser** [comment]
this looks like a bug to me. shouldnt be too hard to fix. give me a little bit!

**Comment by JonasVautherin** [comment]
I had another look but I just can't find where the `*.pb.cc` get installed in the CMakeLists :confused:.

**Comment by kevinkreiser** [comment]
I couldn't reproduce it. I opened a terminal in a fresh docker environment installed the dependencies and then built and installed valhalla and it only had h files in the installed include dir. are you using master and do you have modifications. what platform are you installing on?

**Comment by JonasVautherin** [comment]
Hmm you're right, I tried again from a fresh clone and it works as expected :thinking:. Maybe I messed up something (I made some changes in order to cross-compile)...

Sorry for the inconvenience, and thanks for the help!
