### ISSUE TITLE
Truck costing ignoring top_speed

### ISSUE THREAD

**Issue by corypisano** [valhalla/valhalla#4789]
Was looking to update from version 3.4.0 to a main branch build and noticed our truck routes were all ~20% slower. 

I see https://github.com/valhalla/valhalla/pull/4493 clamped truck speed to 90 KPH / 55 MPH. The intention there makes sense to me (avoiding unbounded truck speed), but 55 mph is a bit slow for some highways and doesn't seem like the new top_speed can be overridden with a costing_option?

> `top_speed` Top speed the vehicle can go. Also used to avoid roads with higher speeds than this value. top_speed must be between 10 and 252 KPH. The default value is 90 KPH for truck and 140 KPH for auto and bus.

For an example request, a small section of I-95 in Virginia, US: 
```
/route?json={"locations":[{"lat":37.858795,"lon":-77.453613,"type":"break"},{"lat":37.872482,"lon":-77.453914,"type":"break"}],"costing":"truck"}
```
 on our 3.4.0 build
```
"summary": {
      ...
      "time": 48.725,
      "length": 1.529,
      "cost": 45.071
},
```
vs on main branch
```
"summary": {
      ...
      "time": 61.177,
      "length": 1.529,
      "cost": 56.589
 },
```
This is okay on its own, but I expected raising `top_speed` would allow going up to the speed limit, which https://www.openstreetmap.org/way/48842029 has a tagged max speed of 70 MPH / 112 KPH. 

adding ~`"costing_options":{"top_speed":120}}`~  `"costing_options":{"truck":{"top_speed":120}}` doesn't take affect and still get the slower time that aligns with a speed of 90 KPH.

**Comment by chrstnbwnkl** [comment]
Costing options are specified per costing, i.e. `{"costing_options": {"truck": {"top_speed": 120}}`. But beware that the top speed will be clamped to the edge's speed in this case which would be 112. It should make it possible though to raise the assumed speed for trucks in your case.

**Comment by corypisano** [comment]
ah yes sorry the issue text is wrong, but 

`route?json={"locations":[{"lat":37.858795,"lon":-77.453613,"type":"break"},{"lat":37.872482,"lon":-77.453914,"type":"break"}],"costing":"truck","costing_options":{"truck":{"top_speed":120}}}`

still doesn't seem to take affect

**Comment by chrstnbwnkl** [comment]
Ah yeah, looking at it more closely, `top_speed` is indeed clamped to `kMaxAssumedTruckSpeed`. Doesn't really make sense, because `top_speed` defaults to `kMaxAssumedTruckSpeed` anyway, so we could probably just use that in case no tagged truck speed exists and clamp it to the edge's speed.
