### ISSUE TITLE
empty_street_name_labels not suited for foreign language (italian)

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#479]
(2017-01-26T20:22:51Z) @paolobenve : originally created valhalla/odin#399

(2017-01-26T20:46:50Z) @kevinkreiser : yes for some combinations our translations and directions can be somewhat robotic (dont sound like a real human speaking). in german for example we also drop some articles in certain places to avoid solving the issue of varying gender and case. if a general rule can be arrived at in this thread, we do have the ability to implement it in code. essentially we can write code to do the right thing if its more complex than just string replacement. do you think you could formulate a rule for us to implement to handle this preposition merging with an article case? or is it as simple as following the table you linked?

one possible rule/algorithm for this would be:
1. look for `su` preceeding any `empty_street_name_labels`
2. if there was a `su` and the first word in `empty_street_name_labels` is found in that table
3. then replace `su` and the first word by the combination of the two found in the table

(2017-01-26T21:35:01Z) @paolobenve : The italian issues we should manage are just the ones summarized in the table, but others issue could appear.

The possible rule/algorithm you write should be applyed with all the propositions affected, and after merging the translated strings, and only for italian.

More generally, I'd define a bidimensional array, with the language as first dimension and the pair to substitued ("preposition article") as the second one, the array value would be the "articulated preposition" ; and after the translation is performed I'd search & replace according to the array, checking for whole words.

This way german and other languages issues could be managed too.

**Comment by dgearhart** [comment]
@paolobenve I was hoping you could provide some clarification with the "articulated preposition"
Do these rules need to be created per instruction or are they global - that is: all ` su la ` should be replaced with ` sulla `?

**Comment by paolobenve** [comment]
"articulated preposition" means a preposition which is joined to the following article.

Yes, in italian `su la` doesn't exist, it always becomes `sulla`, and this is true for all the combinations in the table given in http://faculty.washington.edu/gtassone/uw/preposizionia.htm
