### ISSUE TITLE
Control `truck_route_factor` 

### ISSUE THREAD

**Issue by chrstnbwnkl** [valhalla/valhalla#4797]
It's a fixed value (0.85) right now, so there's a light preference for edges marked as truck routes in truck costing. Would be nice to expose this via the costing options, either  directly as a parameter `truck_route_factor` or as something like `use_truck_route` that translates to a factor internally.

**Comment by aidarbek** [comment]
Thank you @chrstnbwnkl for filling an issue, I'm interested in solving it, can I pick it up?
