### ISSUE TITLE
Associate edges should use "elapsed" time/distance for single edges.

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#481]
(2017-01-27T15:04:08Z) @zerebubuth : originally created valhalla/tools#132

When the edge association process finds a route between the start and next LRP points, it should pay attention to the `time_elapsed` returned in the `PathInfo`. This is used when only part of the edge is matched, and the distance should be calculated from this point, with the next step forced to continue along this edge.

Partial results at the first or last LRP point are also okay, as these are (will be?) used as "chunks" to build up many-to-many relationships.

(2017-02-01T11:54:54Z) @zerebubuth : Re-reading this, I think I wrote it very badly. My original hand-written note was:

> In per-LRP processing, takes end node rather than `elapsed_time` along edge.

So I think what I _meant_ was that the code checks the distance between the [end node of the edge](https://github.com/valhalla/tools/blob/c45ae05f3192c6a37140959ab868e3d8860f9009/src/valhalla_associate_segments.cc#L644) and the next coordinate, rather than the position `elapsed_time` along the edge and the next coordinate.

**Comment by dnesbitt61** [comment]
we have commented out the A* fallback when edge walking fails. I am closing this for now - if we resurrect the A* logic we can re-open this
