### ISSUE TITLE
valhalla_ways_to_edges not working correctly

### ISSUE THREAD

**Issue by Bichoshka** [valhalla/valhalla#4810]
I'm trying to add traffic to my local valhalla instance
Following the docs I just wait for the graph to be up and  then call 
`valhalla_ways_to_edges -c /custom_files/valhalla.json > /tmp/text.txt`
But the result is logging of some kind, not the mapping itself:

'valhalla@cf1b282d2537:~$ cd /tmp
valhalla@cf1b282d2537:/tmp$ ls
interrupt  loki_in  loki_out  loopback  odin_in  odin_out  text.txt  thor_in  thor_out
valhalla@cf1b282d2537:/tmp$ cat text.txt
2024/07/19 08:59:12.552588 [INFO] Tile extract successfully loaded with tile count: 7
2024/07/19 08:59:12.552900 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2024/07/19 08:59:12.552924 [WARN] Traffic tile extract could not be loaded
2024/07/19 08:59:12.562255 [INFO] Finished with 3987 ways.'

I'm using docker compose with ghcr.io/gis-ops/docker-valhalla/valhalla:latest
And the map file is the classic andorra-latest.osm.pbf (tried others with the same result except for the number of ways)

Do I need anything except running valhalla with ready-up graphs for that function to work properly?

**Comment by nilsnolde** [comment]
you need to check the right folder. the code is super simple:
https://github.com/valhalla/valhalla/blob/9725261d1c33d6fa361d3d0eec12404f79ca150d/src/mjolnir/valhalla_ways_to_edges.cc#L104-L105
