### ISSUE TITLE
Outliers on long routes

### ISSUE THREAD

**Issue by johannes-no** [valhalla/valhalla#4815]
Hello Valhalla community,

every now and then we come across a strange problem with long routes, where we leave the highway and go back on it again.
![image](https://github.com/user-attachments/assets/4dc58f8b-61e3-4659-bea0-3ddf26c9402f)

For shorter routes, everything works well and the road attributes such as classification also seem to be correct. 
We tested:
- Disable shortcuts -> still happens
- Disable/enable traffic -> still happens
- Test different cost profiles/ increase transition costs to ramps by a lot -> still happening
- Change start/end point -> sometimes happens

Does anyone have any idea why this behaviour occures and how to prevent it?

Greetings 
Johannes

**Comment by chrstnbwnkl** [comment]
Can you paste the request body as text as well? Makes it easier to reproduce

**Comment by johannes-no** [comment]
sure but i'm afraid that this won't help much as we do not use osm and i can't reproduce it in the valhalla demo tool.

[{"costing":"auto","locations":[{"lat":47.99803968890939,"lon":7.846266228328146},{"lat":52.512831514831134,"lon":13.407955937141187}]}]

**Comment by chrstnbwnkl** [comment]
The only thing that reminds me of is a similar discussion in https://github.com/valhalla/valhalla/issues/3584, but nothing came out of it (plus the linked minimal reproducible examples don't seem to produce the weird exit/enter behavior anymore)...

**Comment by chrstnbwnkl** [comment]
Have you looked at the `/expansion` output? That could give you some hints about whether the skipped edge was even put on the queue, or maybe if it's cost related

**Comment by kevinkreiser** [comment]
to me it looks like a problem with the graph. what i would do is use the `locate` tool to inspect the properties of the edges in the graph at that location. you can use a costing of `none` which sh ould allow looking at any/all edges in the area. i would pay very close attention to the node/edges where that ausfahrt leaves the autobahn. to me it seems the costing thinks it cannot use the outgoing edge that stays on the autobahn. specifically id look at the access mask and if that looks good id look for restrictions

**Comment by johannes-no** [comment]
Thank you both for the quick replies! I didn't know the expansion tool yet, i was able to finde the edge on the motorway with it but i'll continue debugging with it.

Regarding your comment @kevinkreiser, I checked the edges and nodes with the locate tool beforehand and couldn't find any anomalies. Also, if it's a map error, the problem should also occur if we start the route from e.g. Munich, right? But whether the error occurs depends on where i select the starting point, as can be seen in the picture below. Here we have Berlin as the end point and the problem at the blue point can only occur if the start point is in the red area.
For this reason, I have focussed on the algorithm, but I will take a closer look at the edges/node attributes you mentioned again and keep you updated.

![image](https://github.com/user-attachments/assets/34ba59e0-7fb5-4594-a125-ee2e64efa6ea)

**Comment by kevinkreiser** [comment]
what happens if you disable hierarchy limits? we have a heuristic in the algorithm that decides when to stop allowing downward transitions. the reason i mention this is because the length of the route determines when that limit will be enforced. perhaps the road class is messed up on that one segment in your data and so the hierarchy limits on the longer route force it to be disallowed.

**Comment by johannes-no** [comment]
So i did some testing with disabled hierarchy limits. Unfortunately, the detour still occurs.

**Comment by kevinkreiser** [comment]
dors the algorithm even evaluate the edge? get the edge ids from locate and print if it's even encountered or not or set a conditional breakpoint. If it is encountered what happens to it does it become an edge label?

**Comment by johannes-no** [comment]
I have found a fix. We have increased the turn_cost for ramps in TransitionCost but not in TransitionCost**Reverse**. Now that I have adjusted the penalty for a transition to ramps in both functions, it works fine for us. 
As you suspected, the cause probably lies in the map data. 

I also wanted to ask if we should move the turn_cost factor for ramps to a config or is this not that interesting for the FOSS community?

Thank you both @kevinkreiser and @chrstnbwnkl  again for the quick and detailed responses.

**Comment by kevinkreiser** [comment]
> I also wanted to ask if we should move the turn_cost factor for ramps to a config or is this not that interesting for the FOSS community?

can you say a little bit more about what the change would be? are you talking about making these configurable: https://github.com/valhalla/valhalla/blob/5c1eb841a29ed4344a71ac257fa1412158a812f9/src/sif/autocost.cc#L59-L65

there is a lot of "config" that lives inside the implementation details of costing. we used to have it all inside of config and ended up never having a usecase for tuning it frequently. however at that time we only worked with one data provider. i could see that maybe different data sources could cause you to want to have a different config per data source. i would not be opposed to making this configurable. we should give some thought about how that should work though. imho config should override defaults that are in code if possible. also need to think about how to get config to the costing as currently costing only knows about request time parameters if im not mistaken.

**Comment by chrstnbwnkl** [comment]
Loki and Thor workers have access to the config, so maybe those config parameters could be read during worker instantiation and passed on to  the costing factory?

**Comment by kevinkreiser** [comment]
yep we can pretty much do anything we want i just want to be sure we are sure of the details before we start the refactor. costing interface changes particularly around request options parsing and factory instantiation have been quite painful in the past (theres like a billion of these in the tests). it would be awesome if we could use a default parameter that does no overrides for example. i didnt look at the details for a while but we should before we continue is all im saying :smile:

**Comment by johannes-no** [comment]
I adjusted the turn_cost in https://github.com/valhalla/valhalla/blob/2272caf98546c5a64622bd15b977c67e6fca19f1/src/sif/autocost.cc#L568-L570 and in
https://github.com/valhalla/valhalla/blob/2272caf98546c5a64622bd15b977c67e6fca19f1/src/sif/autocost.cc#L636-L638

I agree that it is a big and quickly underestimated effort to customise the config here. 
What do you think about extracting this factor and storing it as `constexpr float kRampFactor = 1.5f;` similar to 
https://github.com/valhalla/valhalla/blob/2272caf98546c5a64622bd15b977c67e6fca19f1/src/sif/autocost.cc#L51
this would at least prevent you from forgetting to adjust both TransitionCost and TransitionCostReverse functions, as I did.

**Comment by kevinkreiser** [comment]
@johannes-no oh yeah easy stuff like unifying constants is great, please feel free to pr anything like that we can ship that super quick as its trivial

**Comment by johannes-no** [comment]
Thanks again for the quick and detailed help! I would now close this issue

**Comment by johannes-no** [comment]
Thanks again for the quick and detailed help!
