### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by hup333** [valhalla/valhalla#4819]
Doesn't want to take the road

Cabana Valea Stanciului Stefan

![Screenshot_20240729-023314](https://github.com/user-attachments/assets/07f24b26-bd1f-46b6-8762-56f340917dd7)
![Screenshot_20240729-023320](https://github.com/user-attachments/assets/550bd692-3231-41a2-b51e-a981af38fce5)

I am not allowed to navigation to a house?
![image](https://github.com/user-attachments/assets/177aeeca-d676-45cb-9fa6-ca508587270a)

https://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway

A driveway typically leads to a residential home or commercial building

Same here
55.47590, 9.50104
Its a problem all over the world in the map
highway	service
service	driveway

**Comment by hup333** [comment]
I had used that tag a lot

Now i have messed up the map ☹️

**Comment by kevinkreiser** [comment]
taging driveways as `service=driveway` is fine if that is what they are. we have options when creating data though to discard short ones if you prefer that. in residential areas its often the case that we have tons and tons of 20m driveways which add nothing to the routing graph but can severely impact performance and data size. anyway in your case this seems to not be the case? can you link the way so we can investigate why its not considered by the algorithm?

**Comment by kevinkreiser** [comment]
both leaving and arriving at that driveway work as they should:

https://valhalla.openstreetmap.de/directions?profile=car&wps=9.50269639492035%2C55.47519912819835%2C9.500829577445986%2C55.475910564423216

https://valhalla.openstreetmap.de/directions?profile=car&wps=9.500829577445986%2C55.475910564423216%2C9.50269639492035%2C55.47519912819835

now if you want to use a driveway in the middle of the route we do not allow that as it doesnt make sense if the way is actually a driveway

**Comment by hup333** [comment]
I did change it to acces road

The first screenshot show it didn't work

Oh, i see in the middle
That could be why it broke the navigation
It's a dirt road in the mountain
I added a driveway to the middle
Should of course have been dirt road, as the rest of the road
My bad
