### ISSUE TITLE
Error: locations are in unconnected regions

### ISSUE THREAD

**Issue by khamaileon** [valhalla/valhalla#4833]
Hi guys,

I'm trying to get an isochrone for transit in Paris. I had problems importing the GTFS data, which I temporarily resolved by keeping only the subway lines. However, when I tried to build an isochrone, I only got the walking part. So, I tried to make a simple route request and received this error message:

```
RouterApiError: 400 ({"error_code":170,"error":"Locations are in unconnected regions. Go check\/edit the map at osm.org","status_code":400,"status":"Bad Request"})
```

GTFS file: https://drive.proton.me/urls/8F2RCQ2D1M#mpINvc4SahHq
OSM file: https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf 

Request:
```json
{
  "headers": {
    "User-Agent": "routingpy/v0.0.post329+ga86cee6",
    "Content-Type": "application/json"
  },
  "timeout": 60,
  "json": {
    "costing": "multimodal",
    "narrative": false,
    "locations": [
      {
        "lon": 2.3011984232494793,
        "lat": 48.87181776522018
      },
      {
        "lon": 2.3687230894684905,
        "lat": 48.8529681443586
      }
    ],
    "date_time": {
      "type": 1,
      "value": "2024-08-16T10:00"
    }
  }
}
```

GTFS report: https://gtfs-validator-results.mobilitydata.org/edddbf99-8a1f-453f-9725-28c85ec0459e/report.html

**Comment by kevinkreiser** [comment]
this kind of thing usually means you dont have tiles built or your config is not pointing at the tiles correctly. it basically means there is no data covering the area of the globe where you are making the request

**Comment by khamaileon** [comment]
@kevinkreiser Thanks for the precisions.

I figured it out. I'm using docker-valhalla and I was building my tiles in 2 steps. First I build my OSM tiles and then the transit to avoid building the OSM every times. There must be a problem in the process. I restarted the build from scratch and it solved the problem.
