### ISSUE TITLE
valhalla build tiles Mac

### ISSUE THREAD

**Issue by baileyheading** [valhalla/valhalla#4838]
I want to build tiles without using docker on mac os arm. Is there a step I'm missing? All the steps I can find have valhalla_build_tiles as the first step

```
 build % ./valhalla_build_tiles --config ./valhalla.json ./australia-latest.osm.pbf              
[INFO] Running valhalla_build_tiles with 16 thread(s).
[INFO] Start stage = initialize End stage = cleanup
[INFO] Parsing files for ways: ./australia-latest.osm.pbf
libc++abi: terminating due to uncaught exception of type std::runtime_error: sequence: /data/valhalla/ways.bin: No such file or directory
zsh: abort      ./valhalla_build_tiles --config ./valhalla.json ./australia-latest.osm.pbf
```

Can anyone help me figure out what this first error is about?

**Comment by baileyheading** [comment]
hang on, I needed to run this first?
```
valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite --additional-data-elevation ${PWD}/elevation_tiles > valhalla.json
```
I had to search outside of the valhalla documentation to find this

**Comment by janusz-anue** [comment]
Yes you need to update these values in the valhalla config so the graph tiles are stored and later used in the correct directory. You can find the command along with other example commands that might be handy on the bottom of the "build from source" page in the documentation [here](https://valhalla.github.io/valhalla/building/#running-valhalla-server-on-unix) (its for linux but its similiar for mac)

**Comment by baileyheading** [comment]
oh, it seems to be my error here. I ended up in the wrong part of the documentation and missed the build from source part. I ended up in https://valhalla.github.io/valhalla/mjolnir/getting_started_guide/ as I had already built valhalla previously but I wanted to build the tiles and went straight to a section on tile building
