### ISSUE TITLE
Editing a routing graph

### ISSUE THREAD

**Issue by baileyheading** [valhalla/valhalla#4843]
Is there a straightforward way to add a new way between two existing nodes (or add new nodes) for a Valhalla routing graph, or are there other complexities involved?

The alternative is to edit the OSM data but there are clear speed downsides with that

**Comment by chrstnbwnkl** [comment]
The short answer is no, at least not in a straightforward way.

Valhalla uses its own binary file format to store graph data. From a very high level perspective, a graph tile file very roughly consists of the following:

- a file header
- fixed sized blocks for each edge/node (the number edges and nodes can be found in the header) 
- fixed sized blocks for access restrictions (weight etc., ordered by local index of the edge they apply to)
- variable sized information on edges, e.g. street names, edge geometries, etc.
- a spatial index for fast lookups of edges

And a lot more. No one's stopping you from mutating these file contents with the help of the Valhalla C++ library, and if you have a use case that's narrow enough, it might even work for you. But to generally support graph mutation, there are a lot of pitfalls one would need to consider (e.g. shortcuts, tile hierarchy, link/ferry reclassification, and especially the whole bookkeeping of updating counts, indices, rewriting the variable length data structures, and so on) that make this a very unappealing endeavour :smile:

**Comment by baileyheading** [comment]
Thanks for the detailed explanation!

I wanted to know if this was an easy win or a very uphill battle and you provided the exact info needed. I've found that if I limit the area to just what I need, it's somewhat feasible to rebuild the routing graph to support edits to the OSM. The use case I have in mind is the ability to quickly add missing roads (or add private roads that you have access to) into a private copy of the routing graph.

Following from that idea, if you were to just modify the OSM data (on the live map routing UI for example) that corresponds to that Valhalla routing tile (potentially not using shortcuts and other things), could that be done without causing issues, in theory?

**Comment by nilsnolde** [comment]
_adding_ ways/nodes could be done and its not that hard, as long as they don’t cross tile boundaries and you can live without all the optimizations we do. _removing_ ways/nodes is much easier as long as you keep them in the graph, eg by setting their access to none.

Generally editing topology can be modeled as adding or removing things. But that’s surely the hardest thing to do with a graph, especially if it’s crossing tile boundaries which you probably have little control on. 

Editing way attributes in graph tiles (most at least, most notably _not_ geometry) is very easy. Can’t tell you how though, you’ll have to dive into the graph build and figure it out.
