### ISSUE TITLE
Unable to build transit data

### ISSUE THREAD

**Issue by Gopid** [valhalla/valhalla#4844]
Hey team! I'm trying to build transit data for Budapest but I'm getting a lot of errors that suggest that the GTFS feed that I'm providing is missing trip entries from the calendar.txt file. An example error message: "Feed hungary, trip ID C848512778 can't be found or has no calendar.txt entry, skipping...". 

The calendar.txt file does not exist in this GTFS that I'm using. Based on what I've [found so far calendar.txt is an optional file](https://github.com/valhalla/valhalla/issues/3539) so I'm assuming the issue might be something else?

For reproduction:
I have seen others struggling with GTFS data because it wasn't fully covered by their OSM data so I'm trying with the OSM data for Hungary and GTFS data for Budapest.

You can download the GTFS data that I'm using from [here](https://go.bkk.hu/api/static/v1/public-gtfs/budapest_gtfs.zip) and the osm data from [here](https://download.geofabrik.de/europe/hungary-latest.osm.pbf).

I'm placing the osm data as hungary.osm.pbf in the root and the GTFS data inside gtfs_feeds/hungary (assuming this is correct because the files are found).

I'm trying to build transit data with the following command:
`docker run -e build_transit=True --name valhalla -p 8002:8002 -v $PWD/gtfs_feeds:/gtfs_feeds -v $PWD:/custom_files ghcr.io/gis-ops/docker-valhalla/valhalla`

My goal is to use the isochrone API with transit data, my understanding is that once I get this working I will be able to access the isochrone api with the transit costing option to retrieve transit isochrone data. 

Thanks a lot for your help in advance!

**Comment by K4ST0R** [comment]
I got the same issue with some GTFS from France.

According to this part of the code :
https://github.com/valhalla/valhalla/blob/8748f411e466cd183f76b106e8a42082a5dc65cc/src/mjolnir/ingest_transit.cc#L433
You must have an item in calendar.txt or it will skip the trip.

You can generate your own calendar.txt from calendar_dates.txt.

**Comment by Gopid** [comment]
Thanks! I was able to generate a calendar.txt from calendar_dates.txt and that resolved it!
