### ISSUE TITLE
got error when make -j$(nproc)

### ISSUE THREAD

**Issue by Leospearo** [valhalla/valhalla#4853]
error just like below:
src/libvalhalla.a(worker.cc.o)：在函数‘valhalla::serialize_error(valhalla::valhalla_exception_t const&, prime_server::http_request_info_t&, valhalla::Api&)’中：
worker.cc:(.text+0xee7a)：对‘prime_server::http_response_t::http_response_t(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, prime_server::caseless_predicates_t, prime_server::caseless_predicates_t, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
worker.cc:(.text+0xef12)：对‘prime_server::http_response_t::from_info(prime_server::http_request_info_t&)’未定义的引用
worker.cc:(.text+0xef1d)：对‘prime_server::http_response_t::to_string[abi:cxx11]() const’未定义的引用
worker.cc:(.text+0xefb0)：对‘prime_server::http_response_t::~http_response_t()’未定义的引用
...
worker.cc:(.text.unlikely+0x5c82)：对‘prime_server::http_response_t::~http_response_t()’未定义的引用
worker.cc:(.text.unlikely+0x5d22)：对‘prime_server::http_response_t::~http_response_t()’未定义的引用
[ 96%] Linking CXX executable valhalla_run_matrix
collect2: 错误：ld 返回 1
make[2]: *** [valhalla_run_isochrone] 错误 1
make[1]: *** [CMakeFiles/valhalla_run_isochrone.dir/all] 错误 2

 prime_server was already installed in my Centos

**Comment by kevinkreiser** [comment]
you are missing the `prime_server` dependency. please install it first and make sure its in your includes and library paths. you can see how we do this by checking out our dependencies script: https://github.com/valhalla/valhalla/blob/8748f411e466cd183f76b106e8a42082a5dc65cc/scripts/install-linux-deps.sh#L53

more details on building from source can be found here: https://valhalla.github.io/valhalla/building

**Comment by Leospearo** [comment]
Hi, prime_server was installed in my server,and i set includes and library as follows:
(base) [root@storage17 valhalla]# echo $LD_LIBRARY_PATH
/home/map-server/dependencies/luajit/include:/home/map-server/dependencies/spatialite/include:/home/map-server/dependencies/lz4/include:/home/map-server/dependencies/geos/include:/home/map-server/dependencies/prime_server/lib:/home/map-server/dependencies/zmq/lib:/home/map-server/dependencies/czmq/include:/home/map-server/dependencies/zmq/include:/home/map-server/dependencies/proj/lib:/usr/local/lib64:
(base) [root@storage17 valhalla]# echo $LIBRARY_PATH
/home/map-server/dependencies/prime_server/lib:/home/map-server/dependencies/zmq/lib:
(base) [root@storage17 valhalla]# echo $CPLUS_INCLUDE_PATH
/home/map-server/dependencies/prime_server/include:/home/map-server/dependencies/zmq/include:
(base) [root@storage17 valhalla]# pkg-config --cflags --libs libprime_server
-I/home/map-server/dependencies/czmq/include -I/usr/include/uuid  -L/home/map-server/dependencies/zmq/lib -L/home/map-server/dependencies/prime_server/lib -lprime_server -lzmq
(base) [root@storage17 valhalla]# nm -D /home/map-server/dependencies/prime_server/lib/libprime_server.so | grep prime_server
0000000000036340 T _ZN12prime_server13http_client_t16stream_responsesEPKvmRb
0000000000035fc0 T _ZN12prime_server13http_client_t5resetEv
0000000000036010 T _ZN12prime_server13http_client_tC1ERN3zmq9context_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFSt4pairIPKvmEvEERKSC_IFbSF_mEEm
0000000000036010 T _ZN12prime_server13http_client_tC2ERN3zmq9context_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFSt4pairIPKvmEvEERKSC_IFbSF_mEEm
000000000003c650 W _ZN12prime_server13http_client_tD0Ev
000000000003c5f0 W _ZN12prime_server13http_client_tD1Ev
000000000003c5f0 W _ZN12prime_server13http_client_tD2Ev
00000000000371d0 T _ZN12prime_server13http_entity_t12flush_streamENS0_7state_tE
0000000000036090 T _ZN12prime_server13http_entity_t13consume_untilEv
00000000000373b0 T _ZN12prime_server13http_entity_tC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt13unordered_mapIS6_S6_NS_21caseless_predicates_tESA_SaISt4pairIS7_S6_EEES8_
...

this server cannot connect to the Internet, so I downloaded and installed it manually. I configured the environment variables, but I still get above error. Is there any configuration I haven't changed?

**Comment by kevinkreiser** [comment]
you need to set LD_LIBRARY_PATH

**Comment by Leospearo** [comment]
yeah,I have already set LD_LIBRARY_PATH,just the first line of the code output above.

(base) [root@storage17 valhalla]# echo $LD_LIBRARY_PATH
/home/map-server/dependencies/luajit/include:/home/map-server/dependencies/spatialite/include:/home/map-server/dependencies/lz4/include:/home/map-server/dependencies/geos/include:/home/map-server/dependencies/prime_server/lib:/home/map-server/dependencies/zmq/lib:/home/map-server/dependencies/czmq/include:/home/map-server/dependencies/zmq/include:/home/map-server/dependencies/proj/lib:/usr/local/lib64:
...

**Comment by kevinkreiser** [comment]
can you build it with LANG=C so that everyone can read the errors?

**Comment by kevinkreiser** [comment]
it looks like linker errors. If that's the case either the linker can't see the path or the path doesn't have the shared object library in it. You can do VERBOSE=1 when doing make so we can see the full paths its using

**Comment by Leospearo** [comment]
sorry fro reply late cause i met another error when  make -j$(nproc) VERBOSE=1 
as follows:
/usr/local/lib64/libprotobuf-lite.a(extension_set.cc.o): In function `google::protobuf::internal::ExtensionSet::AddInt32(int, unsigned char, bool, int, google::protobuf::FieldDescriptor const*)':
extension_set.cc:(.text+0x1bb3): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20230802::string_view)'
extension_set.cc:(.text+0x1bd1): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()'
extension_set.cc:(.text+0x1cb8): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20230802::string_view)'
extension_set.cc:(.text+0x1cd6): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()'
extension_set.cc:(.text+0x1d62): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20230802::string_view)'
extension_set.cc:(.text+0x1d7a): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()'
extension_set.cc:(.text+0x1df1): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20230802::string_view)'
extension_set.cc:(.text+0x1e09): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()'
/usr/local/lib64/libprotobuf-lite.a(extension_set.cc.o): In function `google::protobuf::internal::ExtensionSet::GetInt64(int, long) const':
extension_set.cc:(.text+0x1f25): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20230802::string_view)'
extension_set.cc:(.text+0x1f3d): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()'
extension_set.cc:(.text+0x1fc6): undefined reference to `absl::lts_20230802::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20230802::string_view)'

**Comment by kevinkreiser** [comment]
looks like you need to install abseil

**Comment by Leospearo** [comment]
Thanks, I have installed it
