### ISSUE TITLE
not using some path for routing

### ISSUE THREAD

**Issue by farfromrefug** [valhalla/valhalla#4864]
I recently realized that in some cases, paths were ignore for rooting. I have not found out why yet.
Here is an example, you can see that there is a direct path to the destination that valhalla is not using
![image](https://github.com/user-attachments/assets/c82f8767-85cb-4ded-851d-9bbabc79cc20)

THis is the url of the demo app `index-internal.html#loc=17,45.141746,6.103930&directionsoptions={"language":"en-US"}&locations=[{"lat":45.14173069142558,"lon":6.107014417648315},{"lat":45.139361969889826,"lon":6.09890341758728}]&costing="auto"`

I am sure the tiles should contain the path https://www.openstreetmap.org/way/1082689564#map=17/45.140440/6.102015 because i use the same pbf to generate map tiles which show that path.
For some reason valhalla is ignoring it

**Comment by kevinkreiser** [comment]
what costing are you using? i see on the demo app you are using "auto" or some motorized vehicle because it says "drive." you'll need to use pedestrian for this since its tagged as a `path` with `foot=yes`. if you are using pedestrian costing then i also noticed that its tagged with `sac_scale=alpine_hiking`. the default max allowed difficulty we set for pedestrian costing is "hiking" but if you want to be allowed to go on harder stuff you need to set that yourself to something higher, in this case "alpine_hiking" which is a value of 4.

**Comment by farfromrefug** [comment]
@kevinkreiser Thanks indeed the demo app was using auto by default. It was also not switching to pedestrian automatically.
this still does not work `index-internal.html#loc=16,45.143865,6.104161&locations=[{%22lat%22:45.14179123253928,%22lon%22:6.106853485107422},{%22lat%22:45.13955116851685,%22lon%22:6.096982955932616}]&costing=%22pedestrian%22&max_hiking_difficulty=4`
In my app i use `max_hiking_difficulty:6` all the time 
![image](https://github.com/user-attachments/assets/00dc004f-5daf-49df-ae40-11fae69f2281)

**Comment by kevinkreiser** [comment]
im not sure the costing options are specified correctly. can you just curl the raw json request to the server you are running and post your curl results? i dont at all trust the permalink/anchor stuff from that front end application to translate what you have there into the right request to the server. costing_options in particular is a bit tricky to get right. has to be nested like `costing_options:{pedstrian:{max_hiking_difficulty:4}}`

**Comment by farfromrefug** [comment]
@kevinkreiser this one does not work:
`https://valhalla1.openstreetmap.de/route?json={%22locations%22:[{%22lat%22:45.14179123253928,%22lon%22:6.106853485107422,%22latLng%22:{%22lat%22:45.14179123253928,%22lng%22:6.106853485107422}},{%22lat%22:45.13955116851685,%22lon%22:6.096982955932616,%22latLng%22:{%22lat%22:45.13955116851685,%22lng%22:6.096982955932616}}],%22costing%22:%22pedestrian%22,%22directions_options%22:{%22language%22:%22en-US%22}}&access_token=`

While this one does
`https://valhalla1.openstreetmap.de/route?json={%22locations%22:[{%22lat%22:45.14179123253928,%22lon%22:6.106853485107422,%22latLng%22:{%22lat%22:45.14179123253928,%22lng%22:6.106853485107422}},{%22lat%22:45.13955116851685,%22lon%22:6.096982955932616,%22latLng%22:{%22lat%22:45.13955116851685,%22lng%22:6.096982955932616}}],%22costing%22:%22bicycle%22,%22directions_options%22:{%22language%22:%22en-US%22}}&access_token=`

**Comment by farfromrefug** [comment]
@kevinkreiser you were right it is working fine with the correct arguments:
`file:///home/mguillon/dev/valhalla--demos/routing/index-internal.html#loc=16,45.143403,6.103603&locations=[{%22lat%22:45.14179123253928,%22lon%22:6.106853485107422},{%22lat%22:45.13955116851685,%22lon%22:6.096982955932616}]&costing=%22pedestrian%22&directionsoptions={%22language%22:%22en-US%22}&costingoptions={%22pedestrian%22:{%22max_hiking_difficulty%22:6}}`

Will have to see why it fails here. 
THanks and sorry for the trouble

**Comment by kevinkreiser** [comment]
no worries, glad its figured out!
