### ISSUE TITLE
Question regarding historical traffic

### ISSUE THREAD

**Issue by simonpalmqvist** [valhalla/valhalla#4871]
Hi!

I'm trying to setup constrained speeds for a couple of ways but I have stumbled upon an issue.
I gather data with OSM way ids. Get the graph ID from the way_edges.txt and then I try to convert it into the correct format level/tile/id with the python script I found here: https://valhalla.github.io/valhalla/tiles/

The get_tile_level and get_tile_index returns the correct values but for some reason get_index does not.

The example I have tried with is: 
` "edge_id": {
          "value": 3643011566018,
          "id": 108570,
          "tile_id": 860472,
          "level": 2
        },`

But the id I get from the function get_index is 16 and not 108570. Is it maybe the wrong way to get the id? 

Any help here would be appreciated. If I correct the id manually I manage to import the traffic data.

**Comment by chrstnbwnkl** [comment]
Seems to be an issue with your implementation.

```python
print((3643011566018 >> (3 + 22)) & ((2**21)-1))
# 108570
```

**Comment by simonpalmqvist** [comment]
Thanks! Yes you are correct my implementation was in javascript and I needed to treat the value as a BigInt instead of a Number. Now its correct. 🙏

**Comment by chrstnbwnkl** [comment]
Keep in mind that there are a couple of things easily missed when enriching a graph with historical speeds, most notably shortcuts. You may want to include these as well when writing the historical traffic tiles.
