### ISSUE TITLE
Logging (still) interspersed with valhalla_export_edges stdout

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla#4891]
This was originally raised in #4496 and believed to be fixed. I never followed up, but that didn't really fix it since initializing the graph reader does some logging upfront and it appears that once configured (with the default logger?), the logging config reset is basically a no-op (didn't dig into the details, but that appears to be what's happening).

I have a fix though and will open a PR shortly :)

**Comment by kevinkreiser** [comment]
logger is a singleton son the first time it's configured thats it. we talked about making it reconfigurable but haven't done it.  For best results configure logging first in any executable
