### ISSUE TITLE
ETA discrepancy between local and FOSSGIS instance (default speeds?)

### ISSUE THREAD

**Issue by ianthetechie** [valhalla/valhalla#4894]
I ran into a weird issue today that smelled similar to https://github.com/gis-ops/docker-valhalla/issues/135. My initial instinct (before finding the issue) was that since the routes were nearly identical except for the ETAs, the FOSSIGS instance (valhalla1.openstreetmap.de) was running with the OSM Default Speeds enabled (I was not locally). The issue suggest that the FOSSGIS instance does run with default speeds.

I assume I'm "holding it wrong" and missing some difference in configs. Is there anything else different about the FOSSGIS instance that I'm missing?

Repro steps with docker image (full local build with `master` as of today yielded the same result):

1. Make a blank dir (ex: `custom_files`)
2. Download https://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf to `custom_files`
3. `docker pull ghcr.io/gis-ops/docker-valhalla/valhalla:latest` (current digest is `sha256:16e2731163f4c689f5c46270e0fe34ad893f73732a12be20cf715bde5054712c`)
4. `docker run -dt --name valhalla_gis-ops -p 8002:8002 -v $PWD/custom_files:/custom_files -e force_rebuild=True -e use_default_speeds_config=True -e build_admins=True -e build_time_zones=True ghcr.io/gis-ops/docker-valhalla/valhalla:latest`

Example request JSON:

```
{"costing":"auto","locations":[{"lon":34.705338478088386,"lat":31.308071816223425,"type":"break"},{"lon":34.77499008178712,"lat":31.186224547734263,"type":"break"}],"units":"kilometers"}
```

Time from localhost: 4651 (~77min). Time from `https://valhalla1.openstreetmap.de/route`: 2606 (~43min).

**Comment by ianthetechie** [comment]
Ooh, I hadn't noticed that... Good catch. For some reason I thought the FOSSGIS instance was running a bit newer code. I _think_ @nilsnolde set that up; is it actually running the 3.4.0 release, or something slightly newer that't reporting interim code as 3.4.0?

**Comment by kevinkreiser** [comment]
yeah we have a github action to deploy it there and havent updated it in a bit. maybe @chrstnbwnkl and i can look at it tomorrow

**Comment by ianthetechie** [comment]
Cool; that might explain it... If someone could ping me when that goes out I'd be curious to re-check. Assuming that resolves the discrepancy, I guess I then need to do a bit more digging into what changed 😂 I'm told by someone with local knowledge that the demo instance is quite a bit more accurate for this area ETA-wise. Tracks definitely play some role here (I deconstructed a few routes), as it's not a very descriptive tag without surface info.

**Comment by kevinkreiser** [comment]
in general accurate ETAs are very hard to come by without at least low-res (constrained and freeflow) historical data. the supplemental speeds that we offer through https://github.com/OpenStreetMapSpeeds/schema/blob/master/default_speeds.json can be fairly accurate but only in places where mapillary (where we derived the data) has/had higher coverage

**Comment by chrstnbwnkl** [comment]
We updated the FOSSGIS instances to use latest master, and we should have the process in place that keeps this up to date from now on. It won't use the new service binary right away, but if you check the version in `/status` in the next 24h or so, you should see 3.5.0 being used eventually :-) I'm not convinced it will change anything about the discrepancy you're describing here though, because I think the previous version was from only a couple of months ago, and I don't know what change could have introduced such different behavior in routing since then.

**Comment by ianthetechie** [comment]
> in general accurate ETAs are very hard to come by without at least low-res (constrained and freeflow) historical data

Yeah, I know ;) The only reason I opened this issue is because I couldn't believe the magnitude of the difference and I mistakenly thought that the "continuous build" cycle also meant pulling Docker images every day.

Thanks for the update @chrstnbwnkl! Will check that later and see what's up. I had not updated my code in a few months either (end of May), so I assumed the FOSSGIS instance was either running newer code or had been configured differently (hence trying to repro with the Docker images to get something a bit more reproducible than the Ansible setup that runs on our servers).

> and also faster ETAs are generally caused by not using the default speeds data that i linked above which could actually mean a misconfiguration on our part on the public service

Yeah, that's usually been my experience. In this particular route, the weird thing is that the best I can reproduce on my own is ~2x _longer_ without default speeds (default speeds with newer code is faster ETA, but sometimes different routes).

**Comment by kevinkreiser** [comment]
this is beginning to underscore the extreme need (for many years at this point) for us to be doing integration testing on every merge to master. we have plenty of unit tests for regression detection however what we dont capture:

1. performance metrics (are algorithms getting slower or faster)
2. quality metrics (are the choice of route and its estimation getting better or worse)

the good news is we have a very simple script that lets us do this given a suite of requests. i talked to @chrstnbwnkl about this recently and i think that, when we merge, part of that process should be to, on the data building machine, run this integration tests suite and publish the output. id really like that to land in a series of graphs so that we can look at trends over time and determine when things may make significant differences (positive or negative).

its a bunch of work tbh but it would go a long way to avoiding regressions that are super important but arent easily tested via unit test. i should probably make an issue out of this comment..

**Comment by ImreSamu** [comment]
(related note / comment / wish )
After reading several Github issues, it seems the community's debugging process might be easier 
if the `/status` API ( https://valhalla1.openstreetmap.de/status )  also displayed:

* The full-version, which would include the Valhalla version, commit hash, and commit ISO date. 
    * e.g., `"full_version": "3.5.0-c411feb3096-2024-09-19:12:54"`
    * and `"valhalla_commit": "c411feb309618c956b5fa7170d3845fb9fa75a06"`
* A list of deviations from the default Valhalla configuration. 
* some information about the server (e.g., nproc, CPU architecture: arm64 vs amd64, operating system version, RAM, etc.)

And based on the FOSSGIS server's `/status` `valhalla_commit: c411feb309618c956b5fa7170d3845fb9fa75a06`, we can configure the [Dockerfile](https://github.com/valhalla/valhalla/blob/master/Dockerfile) with this commit, allowing us to create an almost identical version locally.

**Comment by chrstnbwnkl** [comment]
I just checked and I'm very confident the public instance uses the speed config correctly. I'm just wildly guessing but it may have to do with this block of code here? 

https://github.com/valhalla/valhalla/blob/9e02e3b24747ed6211f221d429aedac817059b51/src/mjolnir/speed_assigner.h#L349-L352

...and the surface set for tracks may come from here:
https://github.com/valhalla/valhalla/blob/58a289de51638c55f479101bf5352160902e0182/src/mjolnir/pbfgraphparser.cc#L2908-L2910

...and the default speed set for tracks:
https://github.com/valhalla/valhalla/blob/77f4c387b723178bd8be9ff360dbc198cf174d64/lua/graph.lua#L1680-L1681 

Which to me in combination translates to "for a generic track road, if no speed config is used, set the speed to 2 km/h. Maybe you can validate this when querying the destination of your example request against locate @ianthetechie ?

```
{
	"costing": "auto",
	"locations": [

		{
			"lon": 34.77499008178712,
			"lat": 31.186224547734263,
			"type": "break"
		}
	],
	"units": "kilometers",
	"verbose": true
}
```

On the public instance it gives me a speed of 9, which was likely set through the speed configuration JSON.

**Comment by ianthetechie** [comment]
Yeah, that's what I'd expect it's coming from too code-wise...

Oh man, you guys are gonna laugh...

First, I can confirm that the public instance has a speed of 9, which is strange, since 5 is actually what shows up in the default speeds file on GitHub.

Digging a bit deeper, I ran a query with admins, and it looks like it's classifying this as somewhere unspecified within the US. So, TL;DR the public server is indeed running the same software and OSM data and default speeds, but admins must be either invalid or missing, so it's using US rural track speeds, which are indeed 9kph in the default speeds file 😂 

FOSSGIS server:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/6c709a46-dced-46f1-80c6-7406e9989139">

Local:

<img width="639" alt="image" src="https://github.com/user-attachments/assets/9480abe4-d466-472b-8c36-8c4320e28467">

**Comment by chrstnbwnkl** [comment]
Oh man... just looked at the admin sqlite we're using there, and there's a suspiciously high amount of entries whose parent admin is the US :smile: I'll try to fix that in the coming week. Hope I can find a planet distribution with working admins :crossed_fingers:

**Comment by ianthetechie** [comment]
LOL! I mean, I think there's perpetual "breakage" of some sort, but in the end I've never really experienced issues as a result. I think @kevinkreiser and I were talking about that one time and determined it wasn't really worth chasing the "perfect" planet too much. (We don't at Stadia Maps. I just build admins infrequently, open the file in QGIS to spot check ,and cut a "release").

Thanks for the help on tracking this down, everyone! Mystery solved!

**Comment by kevinkreiser** [comment]
yeah in practice its best to just make a good admin db that you know is decent and stick with it for a long time

**Comment by chrstnbwnkl** [comment]
FYI, I recently updated the planet admin DB for the public server. Not sure how good it really is but a quick check revealed it's way better than what we had before :smile:
