### ISSUE TITLE
Ignore height/width restriction for specific section of road

### ISSUE THREAD

**Issue by gesch-ridezum** [valhalla/valhalla#4901]
I would like a way to be able to ignore the height and width restrictions for a particular section of road during routing. This need arises mostly when we run into a road segment where the data is incorrect in OSM or there are specific context which allow a vehicle to pass through a road with restrictions that would normally break the restrictions.

For the data issues, we fix them as we find them. Unfortunately, given dump delays and replication of the data, it may still take time before the data fix appears in our local image. Given that these discoveries occur at a time-sensitive time and need to be resolved quickly, we need a way to temporarily override the restriction.

**Comment by chrstnbwnkl** [comment]
I have heard this request before. I don't think this is something  particularly interesting for the public project, but it's easy to solve this using a simple script that manipulates the respective graph tile, if you are okay with re-starting the service once you modified the graph data.
