### ISSUE TITLE
Fix build procedure on README.md

### ISSUE THREAD

**Issue by bradh** [valhalla/valhalla#491]
The description of the repos and build process needs update after the great merge of Feb 17.

**Comment by glennon** [comment]
:heavy_check_mark: Indeed -- for example, in the Organization section, links to the various libraries should be changed from their separate, individual repos: https://github.com/valhalla/midgard to their new unified location in the main repo (e.g., perhaps https://github.com/valhalla/valhalla/tree/master/valhalla/midgard ). A few of the libraries seem to have substantial changes, so I did not perform a pull request. I made changes to my forked README for consideration: https://github.com/glennon/valhalla/blob/master/README.md

**Comment by kevinkreiser** [comment]
the build process was updated here:
https://github.com/valhalla/valhalla#building-and-using
is it not working for you?

correct about the links for the main sections of the library. they shouldnt
link to the old repos they should link to the subsections of the docs. feel
free to pr or we'll get taken care of in a bit.

2017-02-04 3:07 GMT-05:00 Alan Glennon <notifications@github.com>:

**Comment by bradh** [comment]
It works, but only if you do a recursive checkout (or there is a release, presumably). I did see a problem with parallel builds, but can't reproduce.

I was mainly thinking about the old "module" descriptive part, but a link to https://github.com/valhalla/valhalla/blob/master/docs/overview.md would probably also be useful.

**Comment by bradh** [comment]
Linking the the usage part still would have been useful...

**Comment by kevinkreiser** [comment]
@bradh which part do you mean? everything that was in `overview.md` is now part of `README.md`. Do you mean usage as in how to run the programs once built? let us know what you were thinking about or feel free to pr it. ill reopen this so you can let us know what you meant here.
