### ISSUE TITLE
Error when building on WSL

### ISSUE THREAD

**Issue by Akmal4163** [valhalla/valhalla#4910]
I build Valhalla as a shared library on WSL2, my operating system was Ubuntu 22.04.3, i got error when i call `sudo make -C build -j$(nproc)` here is my error :

 ` [ 77%] Building CXX object CMakeFiles/valhalla_benchmark_loki.dir/src/valhalla_benchmark_loki.cc.o
[ 81%] Building CXX object CMakeFiles/valhalla_benchmark_skadi.dir/src/valhalla_benchmark_skadi.cc.o
[ 81%] Building CXX object CMakeFiles/valhalla_run_map_match.dir/src/meili/valhalla_run_map_match.cc.o
[ 81%] Building CXX object CMakeFiles/valhalla_run_isochrone.dir/src/valhalla_run_isochrone.cc.o
[ 81%] Linking CXX executable valhalla_benchmark_skadi
/usr/bin/ld: src/baldr/libvalhalla-baldr.a(curler.cc.o): undefined reference to symbol 'curl_easy_cleanup@@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/valhalla_benchmark_skadi.dir/build.make:126: valhalla_benchmark_skadi] Error 1
make[2]: Leaving directory '/home/user/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:1080: CMakeFiles/valhalla_benchmark_skadi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 81%] Linking CXX executable valhalla_run_map_match
/usr/bin/ld: src/baldr/libvalhalla-baldr.a(curler.cc.o): undefined reference to symbol 'curl_easy_cleanup@@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/valhalla_run_map_match.dir/build.make:126: valhalla_run_map_match] Error 1
make[2]: Leaving directory '/home/user/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:1006: CMakeFiles/valhalla_run_map_match.dir/all] Error 2
[ 81%] Linking CXX executable valhalla_run_isochrone
/usr/bin/ld: src/baldr/libvalhalla-baldr.a(curler.cc.o): undefined reference to symbol 'curl_easy_cleanup@@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/valhalla_run_isochrone.dir/build.make:126: valhalla_run_isochrone] Error 1
make[2]: Leaving directory '/home/user/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:1117: CMakeFiles/valhalla_run_isochrone.dir/all] Error 2
[ 85%] Linking CXX executable valhalla_benchmark_loki
/usr/bin/ld: src/baldr/libvalhalla-baldr.a(curler.cc.o): undefined reference to symbol 'curl_easy_cleanup@@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/valhalla_benchmark_loki.dir/build.make:126: valhalla_benchmark_loki] Error 1
make[2]: Leaving directory '/home/user/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:1043: CMakeFiles/valhalla_benchmark_loki.dir/all] Error 2
make[1]: Leaving directory '/home/user/valhalla/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/home/user/valhalla/build'`

when i type `cmake -B build -DCMAKE_BUILD_TYPE=Release` there's nothing wrong in process, no error, but when i build using make, i got that error.

i tried to use included docker images too, and still got same error

`[ 89%] Linking CXX executable valhalla_benchmark_skadi
1220.0 /usr/bin/ld: src/skadi/libvalhalla-skadi.a(sample.cc.o): undefined reference to symbol 'LZ4F_isError'
1220.0 /usr/bin/ld: /usr/lib/x86_64-linux-gnu/liblz4.so: error adding symbols: DSO missing from command line
1220.0 collect2: error: ld returned 1 exit status
1220.0 make[2]: *** [CMakeFiles/valhalla_benchmark_skadi.dir/build.make:114: valhalla_benchmark_skadi] Error 1
1220.0 make[1]: *** [CMakeFiles/Makefile2:390: CMakeFiles/valhalla_benchmark_skadi.dir/all] Error 2
1220.0 make[1]: *** Waiting for unfinished jobs....`

is there any solution for this?

thanks for your attention, any solution will be appreciated

**Comment by kevinkreiser** [comment]
both of these errors are complaining that you dont have the required libraries installed. you need to install both lz4 and curl packages because valhalla wants to link those.

**Comment by Akmal4163** [comment]
liblz4 is already installed on my machine

![image-5](https://github.com/user-attachments/assets/f0c0362b-e93f-4a86-99b4-bfa1ab908b01)
![image-6](https://github.com/user-attachments/assets/941eba5d-41cd-464c-acbd-2e14f23e11d4)
![image-7](https://github.com/user-attachments/assets/383540fe-f447-4db9-952e-f6c2924063b4)

but i still got the error

**Comment by kevinkreiser** [comment]
I don't know much about WSL but that is the problem. the linker wants to link those libraries but can't find the library files. If you can set your LD_LIBRARY_PATH properly that might fix it but I don't know how that works with wsl. I'd suggest you do some searching on the internet about this as I'm certain it's not an issue with our project specifically but rather your configuration
