### ISSUE TITLE
Are costing_options honoured during isochrone calculation

### ISSUE THREAD

**Issue by sohaibiftikhar** [valhalla/valhalla#4929]
As the title says. I was checking if top speed and fixed speed have an effect on isochrone calculation and it seems that it has no effect.
https://valhalla.openstreetmap.de/
The demo react app at the link above also gave the same results.

Just want to confirm if this is a usage issue or it does not work.

**Comment by chrstnbwnkl** [comment]
It does, it just seems that the app doesn't include these options for some reason.

If you try it directly, you should see it work:
```
{
	"locations": [
		{
			"lon": 7.623224,
			"lat": 51.962303
		}
	],
	"costing": "auto",
	"costing_options": {
		"auto": {
			"top_speed": 10
		}
	},
	"contours": [
		{
			"time": 15
		}
	]
}
```
