### ISSUE TITLE
Double free or corruption (out) - Core dumped error

### ISSUE THREAD

**Issue by akifaktas** [valhalla/valhalla#4932]
Hi everyone,

I tried running Valhalla for the planet file on my server with 200GB RAM, 1TB SSD, and 42 CPUs. However, I encountered an error around the second day.

```
| 2024/10/12 02:29:44.598544 [WARN] Restrictions mask exceeds allowable limit on wayid: 934453698
valhalla_1  | 2024/10/12 02:29:44.598575 [WARN] Restrictions mask exceeds allowable limit: 2039
valhalla_1  | 2024/10/12 03:07:54.784557 [WARN] Restrictions mask exceeds allowable limit on wayid: 363907564
valhalla_1  | 2024/10/12 03:07:54.786197 [WARN] Restrictions mask exceeds allowable limit: 509
valhalla_1  | 2024/10/12 03:34:02.291465 [WARN] Restrictions mask exceeds allowable limit on wayid: 6639638
valhalla_1  | 2024/10/12 03:34:02.292722 [WARN] Restrictions mask exceeds allowable limit: 1021
valhalla_1  | double free or corruption (out)
valhalla_1  | /valhalla/scripts/configure_valhalla.sh: line 228:    64 Aborted                 (core dumped) valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
valhalla_valhalla_1 exited with code 1
```

```
valhalla_1  | 2024/10/10 22:43:25.071856 [INFO] Parsing files: /custom_files/planet-latest.osm.pbf
valhalla_1  | 2024/10/12 03:34:02.292722 [WARN] Restrictions mask exceeds allowable limit: 1021
```
There were some warning logs at the start and end. As you can see from these logs, the process started, but the error occurred after approximately 1.5 days.

By the way, the planet file size is 78GB, and the total disk usage is 432GB.

What could be insufficient on the server?

I set it up using Docker. Also, I only need the Matrix API and turn-by-turn Route API. Would it help to streamline the setup to only include these? If the answer is yes, how can I do that?

I'd appreciate any help you can provide.

**Comment by chrstnbwnkl** [comment]
Looks very much like a duplicate of #4904

**Comment by chrstnbwnkl** [comment]
Thanks for the report though! We've been trying to get to the bottom of this, but the error seems difficult to reproduce.
