### ISSUE TITLE
Generate mbtiles from valhalla tiles.

### ISSUE THREAD

**Issue by MJokar67** [valhalla/valhalla#4934]
hello, I wanted to know how I can make the tiles made in Valhalla in the form of an SQLite file with the fields ('zoom_level', 'tile_column', 'tile_row', 'tile_data').
Or are there any tricks to convert generated tiles by Valhalla to SQLite format?

The main problem is I don't know how to get tiles rows and columns from such kind of hierarchy naming:
valhalla_tiles/2/000/743/936.gph

**Comment by chrstnbwnkl** [comment]
Valhalla's vector tile format is very different from the mbtiles one, so this is a non-trivial task. There is a related discussion already: https://github.com/valhalla/valhalla/issues/1703

**Comment by chrstnbwnkl** [comment]
if you want zoom/row/column information per tile  from the hierarchy naming, you can have a look at https://github.com/valhalla/valhalla/blob/master/docs/docs/tiles.md and https://github.com/valhalla/valhalla/blob/master/valhalla/midgard/tiles.h

**Comment by MJokar67** [comment]
> if you want zoom/row/column information per tile from the hierarchy naming, you can have a look at https://github.com/valhalla/valhalla/blob/master/docs/docs/tiles.md and https://github.com/valhalla/valhalla/blob/master/valhalla/midgard/tiles.h

Thank you very much for your reply.
I compiled Valhalla from the source, and then using the tile generator tool, I created the tiles from the PBF file, and even did the routing test with those tiles, and everything is correct. My problem is that I don't know where to get the following parameters and whether the Python code sample that you mentioned in the documentation section has a general application or do I have to change its parameters. I need to save the tiles in the row, column, and tom level for use in another library.

Where did these 'size' numbers come from? --> (0.25, 1.0, 1.0)
Are these parameters constant?

 valhalla_tiles = [{'level': 2, 'size': 0.25}, {'level': 1, 'size': 1.0}, {'level': 0, 'size': 4.0}]
 
LEVEL_BITS = 3
TILE_INDEX_BITS = 22
ID_INDEX_BITS = 21

**Comment by chrstnbwnkl** [comment]
I'm not sure what you mean with using the tiles in another library, but just to be clear: the tile format is not at all compatible with any other vector tile format such as MapBox' vector tile format. The concept of "levels" in Valhalla is very different from the concept of zoom levels in vector tile formats used for rendering. And even if you were to save the tiles in a  way that is compliant with a mbtiles renderer, the file contents are not at all compatible with that format.

**Comment by chrstnbwnkl** [comment]
Sorry, I wasn't quite aware of what mbtiles exactly is and was mistaking it with MapBox' vector tile specification. If you want to simply store the hierarchy in a way that's compatible with mbtiles, you should be able to do it with the information I pointed to. I don't know enough about this specification though, so maybe someone else can chime in on this.

**Comment by MJokar67** [comment]
> I'm not sure what you mean with using the tiles in another library, but just to be clear: the tile format is not at all compatible with any other vector tile format such as MapBox' vector tile format. The concept of "levels" in Valhalla is very different from the concept of zoom levels in vector tile formats used for rendering. And even if you were to save the tiles in a way that is compliant with a mbtiles renderer, the file contents are not at all compatible with that format.

I know that the format and structure of the tiles are different. I do not intend to draw them. I just want to save the generated tiles in a file in such a way that they are stored in each record of the tiles with the fields that I said and in my program I do the routing based on the coordinates of each tile and the tiles I will fetch it myself and give it to Valhalla.
I just want to know how to get each tile's row and column. that's all. I have a 'nutiteq' .vtiless routing package which perfectly works and covers my needs, but I can't duplicate such .vtiles on my own.

![Screenshot from 2024-10-14 12-27-00](https://github.com/user-attachments/assets/d8cdb533-cc14-48ce-b79f-06cce459d0d5)
![Screenshot from 2024-10-14 12-26-38](https://github.com/user-attachments/assets/04c3b2b5-ea20-4a06-a031-87798ea858a4)
