### ISSUE TITLE
Consider smoothness in default bicycle profile

### ISSUE THREAD

**Issue by osmuser63783** [valhalla/valhalla#4935]
Please consider supporting the smoothness tag in the default bicycle profile (which I assume is the one deployed at https://www.openstreetmap.org - do you know if this is the case?).

At the moment, the profile seems to completely ignore smoothness, because even ways with `smoothness=impassable` are routed over.

Exactly which smoothness values should get penalties and which ones should be avoided completely depends on what kind of bike the profile is aimed at (road bikes, general purpose / hybrid / city bikes, mountain bikes). See [Wiki](https://wiki.openstreetmap.org/wiki/Key:smoothness#Values).

Examples of ways with `smoothness=impassable`:

* Way [4905783](https://www.openstreetmap.org/way/4905783), and [route](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=55.92495%2C-3.42926%3B55.92070%2C-3.43475)
* Way [829106990](https://www.openstreetmap.org/way/829106990), and [route](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=57.295280%2C-3.414090%3B57.296900%2C-3.405030)

What I don't really understand is why the following way is avoided: way [1087976687](https://www.openstreetmap.org/way/1087976687), and [route](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=47.273668%2C11.369600%3B47.275451%2C11.368243)

It has very similar tags to the other two.

[Overpass query to find more](https://overpass-ultra.us/#m=16.33/47.2745/11.3712&q=PQKgUAKgFglgzgAngghgOwQUwB4oLYAOANpggPIBumATgSnIgI4CuNAngHSTVtIAuCAPbMBAI14FqmBjDQBzBHyikASswyiRfQRhSjBVAIRgQwMAG1R+7AC4A3nauDsAXxcBdANxgAFGADuKGzmsHJQgWwAvHRK7uZweIKCSmjScJEwhPRweiRxhqIwAMZsRXnmhlSwZZj5idrUAPpVxeWGOUWNcEUoed4AlN7CAkWYaHw0nkIiCHKYgnieQA)

**Comment by osmuser63783** [comment]
This is common to all the routers on osm.org, so I have also created tickets for [Graphhopper](https://github.com/graphhopper/graphhopper/issues/3068) and [OSRM](https://github.com/fossgis-routing-server/cbf-routing-profiles/issues/20). Just linking these to each other for completeness, in case there is discussion the comments on the others may be worth reading.

**Comment by gknisely** [comment]
@osmuser63783 this looks like a bug.  I will take a look at this issue

**Comment by chrstnbwnkl** [comment]
Looks like valhalla doesn't consider the `smoothness` tag, only the `surface` tag. According to the OSM wiki, the smoothness tag seems to be more closely related to the passability of vehicles than `surface=*`, but it's also a lot less common. I could see how smoothness could be additionally considered when deciding on a surface type for a given edge.

**Comment by gknisely** [comment]
@chrstnbwnkl I want to consider it for access as you described.  Not putting on the DE.

**Comment by dnesbitt61** [comment]
seems like smoothness should be applied to the DirectedEdge surface setting

**Comment by chrstnbwnkl** [comment]
Duh, the reason for differing bike access despite the same tags is due to the country defaults :smile: In Austria, cyclists have to dismount on paths: https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Austria which maps to no bicycle access in Valhalla.

**Comment by kevinkreiser** [comment]
I came here to say what Dave said :)

**Comment by ianthetechie** [comment]
@chrstnbwnkl this is a very interesting point. Korea has a similar problem when it comes to crossings which do not additionally have designated cycle lanes. This makes a rather perverse incentive to map incorrectly / omit details.

I've been mulling this over for a bit and working on some ways to visualize the graph data + OSM recently which I hope will let us come up with some solutions.
