### ISSUE TITLE
preferred_side parameter is incorrect

### ISSUE THREAD

**Issue by mabilinab** [valhalla/valhalla#4950]
Hi,
It seems like the "preferred_side" parameter incorrectly assigns a desired street side.
Example: France (driving on the right side), if you use the following request
```
    "locations": [
        {
            "lat": 48.8921468930852, 
            "lon":  2.332453949369806
        },
        {
            "lat": 48.892382, 
            "lon": 2.332075 ,
            "preferred_side": "same"
        }
    ],
    "costing": "auto",
    "directions_options": {
        "units": "kilometers"
    }

```
it will output this result:

```
[
    {
        "type": "break",
        "lat": 48.892146,
        "lon": 2.332453,
        "side_of_street": "right",
        "original_index": 0
    },
    {
        "type": "break",
        "lat": 48.892382,
        "lon": 2.332075,
        "side_of_street": "left",
        "original_index": 1
    }
]
```
Using "same" normally should route you to the point so that it's on your right-side, however, here it routes you to the point so that it's on your opposite side, which is the left side.

Seems like either this is an error or the documentation is incorrect:

> Otherwise the determined side of street is used to determine whether or not the location should be visited from the same, opposite or either side of the road with respect to the side of the road the given locale drives on. In Germany (driving on the right side of the road), passing a value of same will only allow you to leave from or arrive at a location such that the location will be on your right. In Australia (driving on the left side of the road), passing a value of same will force the location to be on your left. A value of opposite will enforce arriving/departing from a location on the opposite side of the road from that which you would be driving on while a value of either will make no attempt limit the side of street that is available for the route.

Am I missing something here?
Thank you!

**Comment by kevinkreiser** [comment]
did you test this on your own data? if so its important to note that you must build the data with proper admin area polygons. these make sure to properly set the side of street driving in the data. the default when no admin is present is left side of street driving which means france would be set incorrectly if the admin data was not present or has some other geometric issue

**Comment by mabilinab** [comment]
Thanks for the reply!
Not sure I understand what you mean by :
> you must build the data with proper admin area polygons. these make sure to properly set the side of street driving in the data.

I've just built the graphs on top of France OSM data. Am I supposed to configure something else?

**Comment by mabilinab** [comment]
I see but am I supposed to set anything manually? Doesn't Valhalla automatically assign the right driving side for each country?

**Comment by radekvermirovsky** [comment]
> Hi there. @kevinkreiser @chrstnbwnkl Any help on this please 🙏🏼? Am I supposed to set anything manually? Doesn't Valhalla automatically assign the right driving side for each country?

By default, 'drive on right' is set to false. Without proper admins, the system assumes you're driving on the left.
