### ISSUE TITLE
Tag smoothness=impassable breaks pedestrian routing

### ISSUE THREAD

**Issue by szymone** [valhalla/valhalla#4967]
The smoothness tag shouldn't impact pedestrian routing, as this tag is meaningful only for vehicles (https://wiki.openstreetmap.org/wiki/Key:smoothness). During graph.lua processing, ways with smoothness=impassable get kv["pedestrian_forward"] = "false" and kv["pedestrian_backward"] = "false". This issue started after https://github.com/valhalla/valhalla/commit/329c4e62428a249c9b59a674baf1241e6bb8ef8d commit. 

For example: https://www.openstreetmap.org/directions?engine=fossgis_valhalla_foot&route=52.43489%2C14.82347%3B52.43359%2C14.82847

**Comment by gknisely** [comment]
@szymone I agree with you.  Let me take a look at this issue.
