### ISSUE TITLE
Consider tunnel and bridge entrance as step.(Custom step)

### ISSUE THREAD

**Issue by MJokar67** [valhalla/valhalla#4976]
hello to all
How can I tell Valhalla to consider the entrance of bridges and tunnels as steps? Or how can I create customized steps and output the properties of the edges per steps in final JSON? Note that I only want to get the answer with a single request.

**Comment by chrstnbwnkl** [comment]
A request parameter "type" under pedestrian costing options (added in #3694) should enable maneuvers for bridges and tunnels IIRC.

**Comment by MJokar67** [comment]
Hi. Thank you. Is that only works on pedestrian, or its can be used by other route types? For example car bike and etc..

**Comment by kevinkreiser** [comment]
its limited to pedestrian at the moment. using it is documented: https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/#pedestrian-costing-options

you would add pedestrian costing options like `{...,"costing_options":{"pedestrian":{"type":"blind"}}}` note that this will get  you other maneuver stuff that is specific to blind mode users which might not be what you want but at the moment its the only place where we give the option to hear about bridges and tunnels in the maneuvers.

**Comment by MJokar67** [comment]
Thank you very much bro. I'll try to find a way to add such a functionality to other route options.
