### ISSUE TITLE
[bug] Matrix API: `costmatrix` failed, while `timedistancematrix` succeeded

### ISSUE THREAD

**Issue by tobwen** [valhalla/valhalla#4982]
### Executed query
``` sh
curl -skL \
--url 'http://localhost:8002/sources_to_targets' \
--url-query costing=auto \
--data '{"sources" : [{"lat" : 47.339023, "lon" : 10.266448}], "targets" : [{"lat" : 47.446327, "lon" : 10.242097}]}' 
```

### Observed behavior
``` json
{
  "error_code": 442,
  "error": "No path could be found for input",
  "status_code": 400,
  "status": "Bad Request"
}
```

### Expected behavior
``` json
{
  "algorithm": "WHATEVER",
  "units": "kilometers",
  "sources": [
    {
      "lon": 10.266448,
      "lat": 47.339023
    }
  ],
  "targets": [
    {
      "lon": 10.242097,
      "lat": 47.446327
    }
  ],
  "sources_to_targets": [
    [
      {
        "distance": 18.835,
        "time": 1362,
        "to_index": 0,
        "from_index": 0
      }
    ]
  ]
}
```
### Analysis
- The matrix routing works for `costing=pedestrian`, which uses `"algorithm": "timedistancematrix"`.
- `costing=auto` uses `"algorithm": "costmatrix"`.
- _valhalla.json_ has `"source_to_target_algorithm": "select_optimal"`

### Workaround
Changing _valhalla.json_ to `"source_to_target_algorithm": "timedistancematrix"` does the trick!
Seems like _costmatrix_ has in issue here.

Disadvantage: Matrix for `auto` is now **EXTREMELY** slow. It's 70 times slower than `pedestrian`.

### Version used
https://github.com/valhalla/valhalla/commit/d377c8ace9ea88dfa989466258bf738b1080f22a

**Comment by tobwen** [comment]
Nope, another pair, which doesn't work for `/source_to_target_algorithm`, but for `/route`:

``` sh
curl -skL 'http://localhost:8002/route?costing=auto' -d '{"locations": [{"lat" : 47.369646, "lon" : 10.257327}, {"lat" : 47.405799, "lon" : 10.277356}]}' 
```

It neither works with _costmatrix_ nor with _timedistancematrix_ when `costing=auto`, but always for `costing=pedestrian`.

**Comment by radekvermirovsky** [comment]
> Nope, another pair, which doesn't work for `/source_to_target_algorithm`, but for `/route`:
> 
> ```shell
> curl -skL 'http://localhost:8002/route?costing=auto' \
> -d '{"locations": [{"lat" : 47.369646, "lon" : 10.257327}, {"lat" : 47.405799, "lon" : 10.277356}]}' 
> ```
> 
> It neither works with _costmatrix_ nor with _timedistancematrix_ when `costing=auto`, but always for `costing=pedestrian`:
> 
> ```shell
> curl -skL 'http://localhost:8002/sources_to_targets?costing=auto' \
> -d '{"sources": [{"lat" :  47.369646, "lon" : 10.257327}], "targets": [{"lat" : 47.405799, "lon" : 10.277356}]}'
> ```

What are your values for these two settings in your valhalla.json file?

"costmatrix_allow_second_pass" and "costmatrix_check_reverse_connection"

Try enabling these settings. Check issue [#4956](https://github.com/valhalla/valhalla/issues/4956) for more information.

**Comment by tobwen** [comment]
> What are your values for these two settings in your valhalla.json file?

both were set to `false`
 
> "costmatrix_allow_second_pass" and "costmatrix_check_reverse_connection"

Thanks, that did it! I'm getting this warning now, but _distance_ and _time_ got calculated:
``` json
  "warnings": [
    {
      "text": "CostMatrix turned off destination-only on a second pass for connections: 5,8,9",
      "code": 400
    }
  ]
```

**Comment by tobwen** [comment]
Update: It take exactly twice the time of `costing=pedestrian`. Confusing.

**Comment by tobwen** [comment]
> If by time you mean computation time then
> 
> On the contrary, it actually makes sense: the second pass does exactly this—it computes the first time, but since "destination only" applies, the first pass doesn’t succeed. Therefore, it runs again, this time ignoring the "destination only" restriction, so the process happens twice.

Yes, computation time. Thanks for explaining it. After all, computing took 3 times longer here (I'm doing more than 4 million calculations). I think I'll move to a 96-core server for this.

> i just wanted to comment that its beautiful to see others familiar enough with the code to be able to confidiently explain what is going on! very nice @radekvermirovsky thank you for your service to our little corner of the internet 😄

Definitely. Thanks for help! I'm closing this, since it's no real bug, but a duplicate.
