### ISSUE TITLE
valhalla prefers to route bicycle on busy and dangerous and unpleasant highway=primary over dedicated bicycle bridge with a slight detour

### ISSUE THREAD

**Issue by matkoniecz** [valhalla/valhalla#4990]
yes, city build this bicycle bridge in a bit weird location but is still clearly preferable

https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=50.031478%2C19.948912%3B50.036289%2C19.941198#map=17/50.033927/19.945056&layers=N

![screen14](https://github.com/user-attachments/assets/4093d659-722a-45d4-a0f0-eb480a71b905)

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=50.031478%2C19.948912%3B50.036289%2C19.941198#map=17/50.033927/19.945164&layers=N
![screen15](https://github.com/user-attachments/assets/8a8d5561-b74f-4a7c-9f23-cf880fadd146)

Cycling along thing like

![screen04](https://github.com/user-attachments/assets/d69a5d1d-bb2a-446a-be8e-66095010d169)
https://www.google.pl/maps/@50.0324319,19.9476798,3a,75y,314.49h,89.6t/data=!3m7!1e1!3m5!1sW_ErPhOUFiAIF0GIrVGCgw!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D0.3952568953477993%26panoid%3DW_ErPhOUFiAIF0GIrVGCgw%26yaw%3D314.4923304336384!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTExOS4yIKXMDSoASAFQAw%3D%3D

is not really pleasant. Various road attributes are tagged in OSM already, see https://www.openstreetmap.org/way/29285576 with `lanes=4`

BTW, in https://github.com/organicmaps/organicmaps/pull/9692 I made quite substantial review and hunting for bicycle routing test units for router. This is just one of them. If there would be any interest at all I can create an issue listing them.

Overall Valhalla seems really uninterested in sending cyclists onto cycleways (opposite problem of current Organic Maps router)

**Comment by kevinkreiser** [comment]
so we have parameters that control how much you prefer bike safety and perhaps our defaults arent to your liking. there is a parameter in bicycle costing called `use_roads`. if you decrease it it should prefer more cycleways. currently i dont think its possible to mess with this on osm.org but its just always going to be the case that the default isnt perfect to all situations or peoples intuitions about what route should be taken. its a hard problem in general

**Comment by matkoniecz** [comment]
oh definitely, and there are differences in what people will prefer

though this case is among more extreme, close to being just clearly and blatantly wrong

Valhalla in general is not really trying to use cycleways and in this case it leads to a clear blunder. And Valhalla systematically does not really try to use cycleways, so it is part of general pattern.

Bicycle router with such preferences as in this case is really weird. I admit that it is possible that osm.org instance is misconfigured/

**Comment by chrstnbwnkl** [comment]
> It is equivalent of sending car on 100km of highway=track surface=mud instead of using a bot longer surface=asphalt highway=primary

Seems a bit unfair, if you move the end point just a tiny bit onto the cycle way, it will go your proposed path, so obviously the costing is not completely off. I remember adding back Valhalla as a router option on osm.org, but I'm pretty sure I didn't set any custom request parameters. Maybe this is something to consider, although as @kevinkreiser points out, configuring costing as a one-size-fits-all is difficult. 

You can configure your requests in this web app, and for your example, lowering `use_roads` to 0.2 does the trick: https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=19.94929432868958%2C50.03131499413366%2C19.9420040845871%2C50.03576004447995

I'm going to close, since it's not an issue with the software directly.

**Comment by matkoniecz** [comment]
If moving the end point just a tiny bit onto the road would no longer lead car into mud but onto asphalt I would still consider defaults quite silly.

I will try to ask is it possible to apply that 0.2 on osm.org but at least in my (not very important) opinion it should work out of the box with default settings.
