### ISSUE TITLE
Newhaven, England to Dieppe, France ignores ferry

### ISSUE THREAD

**Issue by mtmail** [valhalla/valhalla#5]
Hi,
Looking at https://mapzen.com/projects/turn-by-turn/ it's not clear where/how to report bugs. The README in this repository lists multiple sub-projects but as outsider it's not entirely clear where a routing bug would make most sense.

1. go to http://www.openstreetmap.org/
2. search Newhaven, England => Dieppe, France and select `Car (Mapzen)`
3. the proposed route is 339km (4:20) via the Dover => Calais Eurotunnel

Other routing engines propose the ferry (about 4 hours). I could understand preferring the Eurotunnel when looking strictly at time-taken since the ferry runs only 4x per day.

When selecting `Foot (Mapzen)` I see `Distance: 130km. Time: 25:34.`. The time is odd since a person wouldn't walk the 130km.

**Comment by gknisely** [comment]
@mtmail thank you for reporting this issue.  I will look at it today.  

Thanks  --Greg.

**Comment by gknisely** [comment]
@mtmail I will let you know when this is updated on our production environment.  Thank you again for reporting this issue.

**Comment by gknisely** [comment]
@mtmail this issue has bee fixed.  Thank you.
