### ISSUE TITLE
Narrative/Directions Translations via TranslateWiki

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#510]
@nemobis @nikerabbit are main contributors to the TranslateWiki project and I'd reached out to them a few weeks ago at this point to see what it would take to create a project for valhalla's [narrative file](https://github.com/valhalla/valhalla/blob/21d0c4b3fb5b0ecc5dd494944b9c34bf0ce76d65/locales/en-US.json)

They seem to support json but there are open questions about translating something that isnt just a file of strings but does its own text replacement etc within the routing engine.

I just wanted to create this issue to get the ball rolling on discussing feasibility of such a project.

**Comment by nemobis** [comment]
Thanks! IIRC the main work needed is to [add message documentation](https://translatewiki.net/wiki/Translating:Localisation_for_developers#Message_documentation) as a qqq.json format and have a writeup somewhere about the format and source of the variables you use so that translators understand it.

The JSON format in itself should be supported but I had not looked in detail and I defer to Niklas for that.

For reference our main documentation pages are:
* https://translatewiki.net/wiki/Translating:New_project (intro)
* https://translatewiki.net/wiki/Translating:Localisation_for_developers
* https://translatewiki.net/wiki/Setup_of_a_new_project (configuration on our end, open to patches)
* https://www.mediawiki.org/wiki/Help:Extension:Translate (everything else)

**Comment by Nikerabbit** [comment]
I wrote a [WIP patch](https://gerrit.wikimedia.org/r/332941). It can parse the JSON, but as we do not support lists (as the length can be variable), those are exported as maps.

**Comment by kevinkreiser** [comment]
that seems ok to me! we can easily do the work to turn maps back into lists with a few lines of python. i noticed your changeset had a reference to the `odin` repo. we've migrated everything into this single repo.

**Comment by Nikerabbit** [comment]
Example diff: https://translatewiki.net/static/temp/valhalla.diff (It's large because all the formatting changes).

It's actually little bit more complicated: If the array indexes are consecutive from zero upwards, then PHP decides it's a list, otherwise a map.

Also, if you need the country codes to be always present, then there is some work to do to add those language code mappings.

**Comment by kevinkreiser** [comment]
ah ok no worries. all we'd have to do then in python is check the type. if `phrases` came out as `list` then we'd change it back into a map with consecutive indices starting at `0`. if it came back as a map it looks like its already correct.

i guess my question is, where would this code go? is there a way we can make per project modifications to the output within the translatewiki workflow. so that i could add the code to handle the above case? or does one normally pull request it and then do the modification in/via the pull request?

**Comment by Nikerabbit** [comment]
I'm reluctant to make any exceptions on our side. To keep overhead low, all projects go through same set of scripts with minimal human intervention. For GitHub we don't even support pull requests. Direct pushes are the only option. The frequency of updates coming to you would be about two per week, while we import updates from you multiple times a day.

Oh, you likely already are aware of this, but with lists, it's not possible to remove or add items except in the end, because otherwise the way we identify messages goes off as the rest get renumbered.

**Comment by Nikerabbit** [comment]
There is no support for different filenames on export. We can export to a different branch, though not recommended by us.

There is https://phabricator.wikimedia.org/T139942 which involves a similar type of thing (automating something about exports that depends on a project), but if that requires running code (which is not controlled by us) on our server, that has obvious security implications that would need to be taken care of.

**Comment by kevinkreiser** [comment]
now im a bit confused! i would assume that in most cases someone would be translating `en-US.json` surely on export the file coming back wouldnt be named `en-US.json` right? It would instead be named whatever the target langauge code is like `de-CH.json`? in any case what about this:

we duplicate `en-US.json` and name it something like `en-US.json.translate-wiki` and have that be the file that is translated. then the new file that land in our directory are not named with the `.json` extension and so they wont be picked up automatically. this will give us a chance to fix the formatting and add the appropriate unit tests. would this be possible?

**Comment by kevinkreiser** [comment]
ps. sorry for moving so slowly on this, i havent had time to take a deep look at how it all works. i very much appreciate all the time you are spending teaching us the ropes on how this works!

**Comment by Nikerabbit** [comment]
I mean that if we read existing translations from fi-FI.json, then we also export to fi-FI.json. The only thing that varies is the language code.

What you suggest could perhaps be possible, but I very strongly advice against any manual human intervention that would be required for *every* update. One primary goal is to deliver the translations to the users as quickly as possible. For Wikipedia we do it in couple of days. Of course we cannot control your release or deployment process, but for updates at least we would prefer them to be automated and frequent, so that the translations are there when someone does git clone or you make a release :)

**Comment by kevinkreiser** [comment]
then it does seem that we are left with option 1, support arrays or maps. i can think of some hacks to force this downstream php code to always see it as a map just add a key at the begging or end.

this brings up some more questions as im begginning to understand.

1. how do new languages which have 0 coverage in our system come into the system? so lets do Finnish. We are missing `fi-FI.json` at present. Does our repository need to have `fi-FI.json` there for someone to do a Finnish translation? If so that is quite unfortunate for us because what it means is that our system will show Finnish as an option but inside will just be 100% english (until we get translations from you guys upstream).

2. When the format changes at all, what happens. As the software gains new abilities sometimes we need to make additions to these files. When we do that we will do the english ones and then copy the english ones as place holders into the other files. How will the translate-wiki project react to changes such as these? This could be simple and just add new blocks of phrases at the end of the file, but sometimes its more convenient (logical) to add phrases to an existing block.

Thanks again for all of your insight!

**Comment by Nikerabbit** [comment]
1) It will be created once translation coverage for the language is over threshold (35% is the default). Like I said above, and as you can see in the diff, it would be created as fi.json unless we add language code mappings.

2) Additions are okay (except in lits where it would case renumeration). Changes to existing strings are also okay (we track which translations need to be updated). Deletions are okay (except in lists where it would case renumeration). Renames are okay if you give us heads-up and avoid doing content changes at the same time. You should not add English to other language files as our software would treat that as a valid translation (which it isn't).

**Comment by kevinkreiser** [comment]
1. will be a bit of a problem for us as our api uses these code mappings as the means of specifying which language/locale you want. we wont be able to change those mapping as its written into the api. to work with the translate-wiki does it mean that we will have to rename all of our existing files, or does it mean that just the new ones from translate-wiki will be missing the locale or?

2. great we can work around having it being seen as a list by simply adding a useless key in there. or we could just name are keys as:

```json
{
  "0.": "foo",
  "1.": "bar",
}
```
Not adding english as a placeholder represents a bit of a problem for us. Currently our software checks that a given language file json is valid by making sure it has everything that the english file has. We could easily change this to be robust to things like missing phrases by simply in software grabbing the english one. But when it comes to other things such as lists that dont have the right number of translated things it's a little more unclear. Say we have:

   "cardinal_directions": ["north", "northeast", "east", "southeast", "south", "southwest", "west", "northwest"],

if someone translates the first and last entries but none of the others, what does the output from translate-wiki look like? will it have the english filled in or? even for the map keys like:

```json
{
  "0.": "foo",
  "1.": "bar",
}
```

What do we need to have in the file, if say `bar` is not yet translated but `foo` was. do we have `"1.": null` or `"1.": ""` or just not have the key `"1."` at all?

**Comment by Nikerabbit** [comment]
1) New files will be missing the country part, unless we add a code map.

2) WRT to missing keys/items: it would be best if you could fallback to English. In PHP I would do array_merge_recursive (and treating all lists as maps while doing so). If a list is missing items, then it is exported as a map.

**Comment by kevinkreiser** [comment]
is there any way that you could run en-US.json through this process, omit some of the translation strings so that they will come out as if they would when say a file is only 35% translated, and then attach it to this issue? then we can go off and see if we can write our software to do all of the fallback logic. if not, could you point me to some software from your repositories so i could have a go at it myself.

what would we need to do to add a code map so that we could get the locale in there? i guess from wikis point of view there is no difference in locale, english is english and it would be foolish to have a en.gb.wiki...org but for us there is a slight distinction, specifically around units and number and date formatting (ie. stuff that posix locales do for us).

**Comment by kevinkreiser** [comment]
@Nikerabbit i was also wondering how one should begin creating a `qqq.json`. from my understanding this is the file which gives guidance to translators as they do their translations. can you point us to the guidelines for this.

**Comment by Nikerabbit** [comment]
GitHub doesn't allow attaching json files: https://translatewiki.net/static/temp/en-US.json

For message documentation, please see https://translatewiki.net/wiki/Translating:Localisation_for_developers#Message_documentation

**Comment by kevinkreiser** [comment]
this is great! i'm going to make a branch with t his file in there and see if i can get the code to make use of it without error. i'll see if i cna make a test that also randomly removes some of the values so that we are robust to falling back to `en-US` as well.

**Comment by kevinkreiser** [comment]
created a branch: https://github.com/valhalla/valhalla/tree/kk_wikitranslate

ill get some tests going that load this file and it should fail when:

* it treats things as arrays that are maps
* it looks for values that arent there

i'll then look into making the api:

* falling back to map key access when the array isnt working
* falling back to en-US when a given key doesnt exist

after these features are added i think we would be robust to translate wiki formatting changes. then have to figure out how to add new things, lets say to en-US.json (when we develop new features that need more language). also we need to get @Nikerabbit or @nemobis commit access right?

**Comment by Nikerabbit** [comment]
The above sounds good. Adding things to en-US.json is easy (just keep in mind the limitations I mentioned above). For commit access, we use @translatewiki account, which will push commits.

**Comment by Nikerabbit** [comment]
Any updates on the testing?

**Comment by kevinkreiser** [comment]
@Nikerabbit i still have the branch hanging out there with the file you provided i currently dont have any time to spent towards it but as soon as i do i will take a look. thanks for checking in an reminding me!

**Comment by Nikerabbit** [comment]
Just checking, are you still planning to have a look?

**Comment by kevinkreiser** [comment]
@Nikerabbit i do think i will have a look still yes. the problem is the priority is very low right now and we have many other initiatives. i dont think it will be that big of a deal to get the code working with the format changes but i just dont have the time to spend on it yet, im sorry for such a long delay (i know its a similar story for many open source projects :frowning_face: )

**Comment by kevinkreiser** [comment]
see #2413

**Comment by nemobis** [comment]
Kevin Kreiser, 09/06/20 00:23:
> see #2413

That's very disappointing. Where can I read more about how you reached 
the decision to opt for a proprietary service rather than free software?

**Comment by danpaz** [comment]
@nemobis I can answer that. Transifex is a tool we use at Mapbox for other projects, so there is some familiarity there that makes it easier for us to adopt. It's also free for public projects like Valhalla. Note that Transifex only augments the current translation workflow and didn't require any changes to the existing language source files, so we are not locked in to using it.
