### ISSUE TITLE
Catalan is missing from available languages

### ISSUE THREAD

**Issue by rroset** [valhalla/valhalla#518]
I could translate the strings file to catalan (ca-ES, Catalan – Catalan,  0x0403,  CAT) which is now missing and thus have the routing instructions in my own language. If it makes sense to you.

**Comment by kevinkreiser** [comment]
@rroset that would be fantastic! please let us know if you have questions.

**Comment by dgearhart** [comment]
@rroset please follow instructions here: https://github.com/valhalla/valhalla/blob/master/locales/README.md
Thanks!
