### ISSUE TITLE
valhalla_build_tiles cant find – doesn't create? – admins.sqlite & timezones.sqlite

### ISSUE THREAD

**Issue by erictheise** [valhalla/valhalla#562]
I'm running `valhalla_build_tiles` as described in the [Running](https://github.com/valhalla/valhalla#running) section. Whether I do this using the Ubuntu PPA or an OS X Homebrew installation, the result is the same; many such warnings:

```
2017/02/24 21:03:35.070529 [WARN] Admin db /path/to/valhalla_tiles/admins.sqlite not found.  Not saving admin information.
2017/02/24 21:03:35.070559 [WARN] Time zone db /path/to/valhalla_tiles/timezones.sqlite not found.  Not saving time zone information.
```

I've replaced my real path, which is correct, to `/path/to`.

If I `touch` these files, the procedure does not produce any warnings, seems to run for much longer, but results in 0 byte `.sqlite` files. No idea if this is expected behavior.

**Comment by gknisely** [comment]
Hey @erictheise 

You need to build the admins and the timezone db.  More information can be found here:  https://github.com/valhalla/valhalla/blob/master/docs/mjolnir/getting_started_guide.md

Let me know if you need more help or have more questions.

--Greg.

**Comment by erictheise** [comment]
Thanks @gknisely. For the admins db, I get 18 of these:
```
2017/02/25 03:26:22.273354 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract.
```
I am using a Geofabrik extract for the state of California and this message suggests to me that I should not ignore the error. Advice?

For the timezones db, I get
```
jq not found which is required.  Please install via:  sudo apt-get install jq
```
which, since I am on OS X, I can install via
```
brew install jq
```
Which gets me to 
```
spatialite not found which is required.  Please install via:  sudo apt-get install spatialite-bin
```
which has no direct correlate in OS X. `libspatialite` is already installed.
```
brew install spatialite-tools
```
seems to work.
```
valhalla_build_timezones --config valhalla.json
```
does not work because why be consistent across tools but
```
valhalla_build_timezones valhalla.json
```
does and the dbs seem to be filling.

Do let me know if I should be worried about that NOT NULL error above given my context, and thanks for your help on a Friday night.

**Comment by gknisely** [comment]
You should not worry about the Not Null admin errors as you are just dealing with CA.  So sorry about the timezone issues....I will make sure to get it up to date/consistent.  Thank you for reporting this!

**Comment by erictheise** [comment]
Thanks again for your help, @gknisely.
