### ISSUE TITLE
Unable to parse command line options because: too many positional options have been specified on the command line

### ISSUE THREAD

**Issue by erictheise** [valhalla/valhalla#564]
I need times & distances for 49 origin-destination pairs across Southern California. Distances exceed the 200km `max_distance` you provide through your public API. I am slogging through @burritojustice's support email in order to get a local install working. I find few differences between the Ubuntu PPA and the OS X install via Homebrew and am working with the latter.

I believe the diagnostic message highlighted in the issue to be incorrect and ask you to please provide a minimal, working example of a command line argument to `valhalla_run_matrix` that is equivalent to a call to `matrix.mapzen.com/many_to_many`.

Though I started with the 49 California locations, then winnowed away all but a few, I have most recently tried several permutations of
```
valhalla_run_matrix --config valhalla.json --matrixtype many_to_many  -j {"locations":[{"lat":40.748174,"lon":-73.984984,"type":"break","heading":200,"name":"Empire State Building","street":"350 5th Avenue","city":"New York","state":"NY","postal_code":"10118-0110","country":"US"},{"lat":40.749231,"lon":-73.968703,"type":"break","name":"United Nations Headquarters","street":"405 East 42nd Street","city":"New York","state":"NY","postal_code":"10017-3507","country":"US"}],"costing":"auto","directions_options":{"units":"miles"}}
```
which is based on what comes back from `valhalla_run_matrix --help`. I understand that a New York query against California data is likely to run into some problem, but __too many positional options__ is not that problem.

There were gaps in the valhalla installation docs and @gknisely's [helped me](https://github.com/valhalla/valhalla/issues/562) to create the mjolnir `admins` and `timezones` sqlite dbs. I have upped `max_distance` in my `valhalla.js` file tenfold.
```
"sources_to_targets": {
    "max_distance": 2000000.0,
    "max_locations": 50
}
```
The error message is immediate.

I could really use some help, thank you.

**Comment by dnesbitt61** [comment]
valhalla_run_matrix is a test program You could run the valhalla server (valhalla_route_service) and then send JSON requests to localhost as you would to the hosted service. 

To use the JSON in this program it seems that you need to enclose it with single quotes (').

./valhalla_run_matrix --config valhalla.json --matrixtype many_to_many -t auto -j '{"locations":[{"lat":40.748174,"lon":-73.984984,"type":"break","heading":200,"name":"Empire State Building","street":"350 5th Avenue","city":"New York","state":"NY","postal_code":"10118-0110","country":"US"},{"lat":40.749231,"lon":-73.968703,"type":"break","name":"United Nations Headquarters","street":"405 East 42nd Street","city":"New York","state":"NY","postal_code":"10017-3507","country":"US"}],"costing":"auto","directions_options":{"units":"miles"}}'

I don't have NY data here at home but hopefully this works - if not get back to us.

**Comment by dnesbitt61** [comment]
closing this issue
