### ISSUE TITLE
foot route doesn't continue on a surface=compacted way

### ISSUE THREAD

**Issue by paolobenve** [valhalla/valhalla#565]
See:

http://www.openstreetmap.org/directions?engine=mapzen_foot&route=44.42990%2C8.80924%3B44.43027%2C8.80886#map=19/44.42997/8.80915

I expect that the route continues on the surface=compacted way, but it stops where it begins

**Comment by dnesbitt61** [comment]
It looks like this way was just added yesterday? It takes somewhere between 1-2 days for data edits in OSM to be imported into our routing solution.

**Comment by paolobenve** [comment]
Now the foot route is ok, but there is something weird, because the only change that was made to the road was setting a part of it as a tunnel, in a point which isn't inside the calculated route...

**Comment by dnesbitt61** [comment]
Do you have an an example of what the new is?
