### ISSUE TITLE
Polylines build is missing some previously available streets

### ISSUE THREAD

**Issue by dianashk** [valhalla/valhalla#578]
Hi Valhalla friends! Thanks for the awesome polylines build we use regularly for street information.

In the recent builds, some streets that used to be there are missing. 😱  
Here's a list of those that our acceptance tests identified as missing. We know these tests used to pass and still do on our production build, so something in the latest build is funky. Let us know if there is any additional information needed that can help in your investigation.

* [North Charlotte Street, Lancaster, PA, USA](https://www.openstreetmap.org/way/56115733)
* [Calle de Lago, Socorro, NM, USA](https://www.openstreetmap.org/way/14629097)
* [Glen Rd, Kelburn](https://www.openstreetmap.org/way/16715054)
* [Warwickshire Rd, Buckingham PA](https://www.openstreetmap.org/way/12248533)

Many thanks,
Search Team ❤️

**Comment by dnesbitt61** [comment]
this was fixed by #587 - will update production so that early next week should have updated and complete data.
