### ISSUE TITLE
Compiling Valhalla on up-to-date system

### ISSUE THREAD

**Issue by TimRepke** [valhalla/valhalla#659]
Hi,
I tried to compile on my computer running Arch Linux, which appears to be a big problem. `czmq` and `prime_server` aren't in the official repositories, nor AUR, so I compiled them from source (4.0.2 and 0.6.3 respectively). They are installed inside my project library root so I don't clog up my system.

Then I ran
```
git clone git@github.com:valhalla/valhalla.git
cd valhalla
git checkout tags/2.1.8
git submodule update --init --recursive
./autogen.sh
CFLAGS=-I$HOME/workspace/satnavpi/libs/include LDFLAGS=-L$HOME/workspace/satnavpi/libs/lib PKG_CONFIG_PATH=$HOME/workspace/satnavpi/libs/lib/pkgconfig ./configure --prefix=$HOME/workspace/satnavpi/libs
make test -j1
```
of which I pasted the relevant output in a gist (so this issue isn't huge): https://gist.github.com/TimRepke/f13bbb74f34d4c97d10742601a4a0406

I tried other tags as well as master. Error is always the same. I even cloned the (deprecated) midgard repository and tried to compile it. Fails at the same places.

I'm not too familiar with C++, a friend, whom I consider a pro, managed to get the project to compile after some changes in the source (with an older gcc), but he couldn't reproduce my issues.
As a last resort, I'd like to kindly ask you, the experts of this project, to point me to the right direction.

Some information that might be helpful:
```
.../valhalla (git)-[2.1.8] % uname -v    
#1 SMP PREEMPT Fri Mar 31 16:50:19 CEST 2017

.../valhalla (git)-[2.1.8] % gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.3.1 20170306 (GCC) 
```

PS: Docker is not an option, since I'm planning to run this on a raspberry pi in my car, so that would waste too much resources.

**Comment by kevinkreiser** [comment]
no worries i'll take a look at it quick this morning!

**Comment by kevinkreiser** [comment]
i've left comments on your gist let me know if that works for you

**Comment by TimRepke** [comment]
@kevinkreiser 
Thanks for your help! I installed gcc5 (5.4.0) to check if that works. It does! But not without some changes! Apparently some libs aren't linked by default, so I ran this small script, which includes `cmath` and `cstdint` where needed:
```
for i in $(find . -name '*.cc' -or -name '*.cpp' -or -name '*.h'); do
grep -E 'std::abs' $i >& /dev/null && sed -ri '1 i #include <cmath>' $i
grep -E 'uint[0-9]+_t' $i >& /dev/null && sed -ri '1 i #include <cstdint>' $i
done
```
By default gcc5 uses c++98, so the updated, quite lengthy configure command:
```
CFLAGS="-I$HOME/workspace/satnavpi/libs/include -std=gnu++11 $CFLAGS" LDFLAGS="-L$HOME/workspace/satnavpi/libs/lib -std=gnu++11" CXXFLAGS="-std=gnu++11" PKG_CONFIG_PATH=$HOME/workspace/satnavpi/libs/lib/pkgconfig CC=gcc-5 CXX=g++-5 ./configure --prefix=$HOME/workspace/satnavpi/libs
```
I left a comment over at the gist as well. There are some odd behaviours with gcc6, so all in all I think supporting gcc6 would be cool, but requires some more knowledge about specifics.
I'll keep an eye on this project, until now I'll compile valhalla using gcc5.

One take-away from this ticket before closing: maybe consider being more specific with required versions.

Again, thanks a lot!

**Comment by kevinkreiser** [comment]
@TimRepke wrt missing headers: it seems to me that its quite possible that we take advantage of headers that got included through other headers in some places (its a lot of code). surely in the stl that shipped with gcc6 those headers just happened to be removed for wherever we were taking advantage of them. if you could it would be helpful to get the list of the files that reference these but dont explicitly include those things. we can fix that right away.

with respect to support for gcc6, i find it quite odd that code would stop compiling there so long as it was still targeting c++11. our configure script checks for the presence of c++11 as it is required. right now we dont target c++14 or 17 so if gcc6 is using those by default and our configure magic isnt setting `-std=c++11` then this may explain what was going on.
