### ISSUE TITLE
valhalla_build_admins segfault

### ISSUE THREAD

**Issue by slvlirnoff** [valhalla/valhalla#671]
Hi,

Using latest valhalla-bin from ppa on a fresh ubuntu Xenial and running build_admins on either Switzerland latest pbf or planet latest pbf yield a segmentation fault when populating database. 

Looking at the code seems related to uniq_ptr for geos (version 3.5) not initialized. Will test more later but any pointer would be appreciated. 

Best,
Cyprien

**Comment by kevinkreiser** [comment]
thanks, we'll take a look!

**Comment by slvlirnoff** [comment]
Thanks, in fact I used 3g network in the train to dive a bit more into it.
See attached pull request, it seems to fix the issue.
