### ISSUE TITLE
Feature suggestion: map_match_service should optionally return associated EdgeInfo

### ISSUE THREAD

**Issue by chrisfosterelli** [valhalla/valhalla#679]
The map_match_service is great, but need it to return some attributes from each matched point's `EdgeInfo`. I've already made some basic code changes to do this, but if this is a useful feature I would be happy to make a pull request (then I don't have to maintain a fork).

So this issue is:
1. Would this be a desirable feature?
2. If so, what should the returned JSON look like and how should this be configured?

**Comment by dnesbitt61** [comment]
We have a method called trace_attributes that does this. It is not yet an announced, hosted service but it should be soon. You can see the draft API here: https://github.com/valhalla/valhalla-docs/blob/master/map-matching/api-reference.md. Let us know if this fits your needs

**Comment by chrisfosterelli** [comment]
@dnesbitt61 Thanks for the quick response David! That sounds very similar to what I am looking for, I didn't think at all to look at the other services. I will test it out and report back.

**Comment by chrisfosterelli** [comment]
After some experimenting it looks like this will work for us. Thanks @dnesbitt61!
