### ISSUE TITLE
Turn-by-turn success and time-distance matrix failure

### ISSUE THREAD

**Issue by araichev** [valhalla/valhalla#692]
Hi all,

I'm running a local installation of Valhalla.

When i call the routing API with `http://localhost:8002/route?json={"locations": [{"lon": 174.611507840056, "lat": -36.15063488488492}, {"lon": 174.777249, "lat": -41.289736}], "costing": "auto"}`, i get a reasonable route that's 750 km long.

But when i call the time-distance API with the same origin and destination via `http://localhost:8002/sources_to_targets?json={"targets": [{"lon": 174.777249, "lat": -41.289736}], "sources": [{"lon": 174.611507840056, "lat": -36.15063488488492}], "costing": "auto"}`, i get null times and distances: `{'sources': [[{'lat': -36.150635, 'lon': 174.611511}]],
 'sources_to_targets': [[{'distance': None,
    'from_index': 0,
    'time': None,
    'to_index': 0}]],
 'targets': [[{'lat': -41.289738, 'lon': 174.777252}]],
 'units': 'km'}`

What's happening here, and how can i fix it?

By the way, in my ``valhalla.json`` configuration file i set the max distance to 5000 km via
`    "sources_to_targets": {
      "max_distance": 5000000.0,
      "max_locations": 100
    }`, which is enough to cover the length of the route.

**Comment by dnesbitt61** [comment]
There is another threshold in code that needs to be adjusted. In valhalla/thor/costmatrix.h there is a constexpr:

constexpr float kCostThresholdDefault = 14400.0f;   // 4 hours

if you increase this to 57600 your test works. I am adding an issue to set this threshold based on the spacing of incoming locations and transport mode, but for now you can just edit this value.

**Comment by araichev** [comment]
Thanks for the tip, dnesbitt61!
Do i need to build Valhalla from source to edit `valhalla/thor/costmatrix.h` or is there a way via my PPA installation (ppa:valhalla-routing/valhalla)?

**Comment by araichev** [comment]
OK, i did the following.

1. Uninstalled Valhalla
2. Cloned the Valhalla Github repository
3. Updated `valhalla/thor/costmatrix.h` to `constexpr float kCostThresholdDefault = 57600.0f; // 16 hours`
4. Built Valhalla from source
5. Build the routing tiles for New Zealand
6. Edited `valhalla.json` to increase the sources-to-targets max distance as above
7. Ran the routing server
8. Ran the queries above

Then i received the same responses: routing between the points works, but the matrix call between the points returns null values.

Does the matrix call work you, @dnesbitt61?
Do i need to configure something else?

**Comment by dnesbitt61** [comment]
This worked for me with the updated kCostThresholdDefault and the config change.

**Comment by araichev** [comment]
After more testing, it appears that my change to `valhalla/thor/costmatrix.h` is not taking effect; i'm still stuck with a 14400 second time threshold.
To rebuild Valhalla from source and run it after i change the threshold, do i need to follow any extra steps besides the ones i followed below (taken from the Github page)?

```
it submodule update --init --recursive
./autogen.sh
# on macOS you need to tell linkers how to reach home-brewed sqlite3
# export LDFLAGS="-L/usr/local/opt/sqlite/lib/ -lsqlite3"
./configure
make test -j$(nproc)
sudo make install

# change to my testing directory
cd ~/try-valhalla

#download some data and make tiles out of it
#NOTE: you can feed multiple extracts into pbfgraphbuilder
wget http://download.geofabrik.de/europe/new-zealand-latest.osm.pbf
#get the config and setup
mkdir -p valhalla_tiles
valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json
#build routing tiles
#TODO: run valhalla_build_admins?
valhalla_build_tiles -c valhalla.json new-zealand-latest.osm.pbf
#tar it up for running the server
find valhalla_tiles | sort -n | tar cf valhalla_tiles.tar --no-recursion -T -

#start up the server
valhalla_route_service valhalla.json 1

```

**Comment by dnesbitt61** [comment]
maybe need to make clean before make test?

**Comment by araichev** [comment]
OK, i rebuilt everything, this time inserting ``make clean`` before ``make test``.
Didn't work, and i'm still apparently stuck at a 14400 second time threshold.
Hmm, i'm out of ideas at present.

**Comment by kevinkreiser** [comment]
are you sure you are running the copy of valhalla that you built from source and not the one you installed from ppa?  make sure you dont have any valhalla installed from ppa:

    sudo apt-get purge libvalhalla* valhalla*

**Comment by araichev** [comment]
Aha, that did it.
Thanks!
I used ``sudo apt-get remove valhalla-bin``, but apparently that was not enough.
