### ISSUE TITLE
Build Valhalla without data tools will fail

### ISSUE THREAD

**Issue by ptpt** [valhalla/valhalla#693]
```
./configure --enable-data-tools=no && make test -j 4
```
will give tons of errors as follows
```
/source/valhalla/test/search.cc:71: undefined reference to `valhalla::mjolnir::DirectedEdgeBuilder::DirectedEdgeBuilder(valhalla::mjolnir::OSMWay const&, valhalla::baldr::GraphId const&, bool, unsigned int, unsigned int, unsigned int, unsigned int, valhalla::baldr::Use, valhalla::baldr::RoadClass, unsigned int, bool, unsigned int, unsigned int)'
```

It seems that some tests still use `mjolnir` to build tiles.

**Comment by kevinkreiser** [comment]
thats true definitely loki does. this is a tough issue because the only options are, always force people to make data tools or remove what appear to be non data tests when they disable data tools... i think ill do the latter
