### ISSUE TITLE
runtime error: (GraphTile DirectedEdge index out of bounds) when building tiles with transit

### ISSUE THREAD

**Issue by slvlirnoff** [valhalla/valhalla#698]
I'm trying to build a graph with extra transit information. and at the validation & binning step I get the following crash:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  GraphTile DirectedEdge index out of bounds: 805712,3,15 directededgecount= 15
```

I might have got an error when adding the transit tiles that is related:

```
2017/05/04 20:01:56.569339 [ERROR] Stop Alzey has no connections to OSM! Start Node Tile: 804272 End Node Tile: 804272
```
It seems to be a stop that is on the same line as the route that goes through the crashing tile.

Here's others errors I got when using transit information during build process (minus maximum admin index error):
https://gist.github.com/slvlirnoff/9fff473bf44dd9051493cd80079fdbc2

During valhalla_build_transit I got the following errors:
```
many:
2017/05/04 08:00:37.096104 [ERROR] TransitDeparture: Exceeded maximum transit departure time
and
2017/05/04 08:07:43.391095 [ERROR] There were 11666 nodes with no directed edges
```

Relevant tile output: 
```
valhalla_build_transit:
2017/05/04 07:34:36.822993 [INFO] Tile 805712: added 5 transit edges, and 6 nodes. time = 1118 ms
2017/05/04 07:34:36.823042 [INFO] Tile 805712: added 6 stops, 10 shapes, 1 routes, and 70 departures
valhalla_build_tiles:
2017/05/04 20:01:57.437222 [INFO] Tile 805712: added 10 connection edges, 6 nodes. time = 867 ms

```
Without transit, graph creation goes smoothly, with only a few too many admin index errors.

If needed I might be able to pull together a small extract of the transit information & osm to try to reproduce more easily. I would probably need help to determine relevant bounding box based on tileId

Any clues on how to debug it further and potentially fix it? Is it a known issue?

Best,
Cyprien

**Comment by gknisely** [comment]
Hi Cyprien, 
What feed did you obtain with valhalla_build_transit?
--Greg

**Comment by slvlirnoff** [comment]
(with others) the official gtfs feed for Switzerland, it's unfortunately quite big and not yet imported into transit.land.

I'll try to create a smaller test case, any tips on how to convert a tile id to a bounding box? I could do smaller osm/transit extract base on that I guess.

**Comment by gknisely** [comment]
Actually, I wanted to try to reproduce your issue.  So if you can send me the the feed onstopid that is having the issue, I can try it here.  

Code to get bbox given tile Id 786664 (assumes level 2 - additional steps to do different hierarchies)

const auto& tl = reader.GetTileHierarchy().levels().rbegin();
Tiles<PointLL> tiles = tl->second.tiles;
AABB2<PointLL> bb = tiles.TileBounds(786664);
LOG_INFO("LL = " + std::to_string(bb.minpt().lat()) + ","  + std::to_string(bb.minpt().lng()) + " to " + std::to_string(bb.maxpt().lat()) + ","  + std::to_string(bb.maxpt().lng()));

**Comment by slvlirnoff** [comment]
Here's the smallest extract that I was manage to create that have this crash:
The zip contains a config, a transit directory with two tiles and a small osm extract that cover the area.

[extract.zip](https://github.com/valhalla/valhalla/files/992057/extract.zip)

I can't give you a onestopid because i'm not sure which stop is problematic and the feed I've used isn't currently imported on https://transit.land/ but only in my local setup

**Comment by gknisely** [comment]
@slvlirnoff please get the latest code and you should be all set.

**Comment by slvlirnoff** [comment]
Thanks a lot! I will compile binaries on the server and re-test a full graph build.

I can probably report tomorrow on the success.

**Comment by slvlirnoff** [comment]
Seems to works all fine now! Thanks a lot @gknisely, I'll close it.
