### ISSUE TITLE
Allow GTFS Import into Valhalla

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#699]
Several changes are needed to allow import of GTFS into Valhalla. Here is a proposed design:

- Publish the transit tile protocol buffer format (pbf).
- Program an application to convert GTFS into pbf tiles.
- Split the _valhalla_build_transit_ application into 2 parts: 1st part queries Transitland and generates transit pbf tiles. 2nd part creates Valhalla transit graph tiles from the transit pbf tiles.

**Comment by araichev** [comment]
Can some at Valhalla do the first task above: publish the transit tile protocol buffer format?
Then i could look into the second task.

**Comment by dnesbitt61** [comment]
We hope to have a proto specification in the next week or tow, but then we have to write the importer from that specification into Valhalla tiles. This is on our near term plan so we hope to get to that soon.

**Comment by phildonovan** [comment]
@dnesbitt61 Any progress regarding the protocols? It would be fantastic to be able to do this, and I'm happy to help Alex. Of course, if I could help with the protocols then I'd be happy to as well.

**Comment by dnesbitt61** [comment]
We are starting work on this after we finish a couple of Open Traffic tasks. Hopefully have something in November. Ping us in a couple of weeks and we can see if there are any areas we need assistance.

**Comment by araichev** [comment]
Hi @dnesbitt61 , any word on this issue?

**Comment by dnesbitt61** [comment]
Well, we have moved to Mapbox now that Mapzen is shutting down. So there has been no progress. Will have to see where transit falls in our priority list when things settle. Transitland is also in a holding pattern, though I think a couple folks are going to continue to maintain that.

**Comment by Rui-Santos** [comment]
> Transitland is also in a holding pattern, though I think a couple folks are going to continue to maintain that.

Well, if you could make Valhalla not download the whole world transit data from the Transitland API I'm sure that would help them keep it live longer. It doesn't even make any sense. Why not use the same restriction that are used to build the admins DB? I understand the feed from transitland gives the whole data they have, but why not pick it by what osm.pbf files are loaded?

**Comment by dnesbitt61** [comment]
Transit data is retrieved from Transitland using the valhallla_fetch_transit application. This is run independently and prior to valhalla_build_transit and valhalla_build_tiles. There is logic in this application to specify a single feed. If you would like to work on some updates to this process to accept a bounding box or some other geographic constraint to limit the volume of data downloaded from Transitland we would be likely to accept such an update.

**Comment by Rui-Santos** [comment]
> Transit data is retrieved from Transitland using the valhallla_fetch_transit application. This is run independently and prior to valhalla_build_transit

I didn't see that on Valhalla documentation. You only reference valhalla_build_transit on all your issues that talk about transit and on mjolnir documentation. I didn't see a single reference to valhalla_fetch_transit, sorry. I already fixed my Valhalla to only fetch a bounding box, by passing it on the valhalla_build_transit command. I didn't even knew I had to run valhalla_fetch_transit first. About contributing my changes, I'm not even sure you will want to accept them. First time ever that I opened a source code file in C++ and tried to make it do what I wanted. But I will submit a pull request with my modification to valhalla_fetch_transit and valhalla_build_transit, no problem, I just need to include what I modified on valhalla_build_transit on valhalla_fetch_transit. It may take a few days, cause I'm kind of busy.

Thanks a lot for your answer, you helped me more than you even imagine.

**Comment by araichev** [comment]
Hi folks, any updates on this issue of importing custom GTFS feeds, preferably without dependence on TransitLand? Additionally, i'm wondering if Mapbox is going to fund Valhalla transit development.

**Comment by dnesbitt61** [comment]
No updates. The team is working on other priorities at the moment. I can't say for sure what the plans are for further transit development. I suspect it will be in the future roadmap but it isn't currently in the near-term roadmap.

**Comment by maestroIgor** [comment]
Hello everyone. 
Is there any activity on publishing the transit tile protocol buffer format (pbf)?

**Comment by kevinkreiser** [comment]
cc @drewda @irees

**Comment by kevinkreiser** [comment]
@maestroIgor we have the protocobuffer input specification here: https://github.com/valhalla/valhalla/blob/master/proto/transit.proto

if you can get gtfs data into this format (which is quite specific to transitland) then you should be able to add gtfs data to valhalla

**Comment by araichev** [comment]
@kevinkreiser @drewda does the TransitLand codebase already contain a GTFS -> Valhalla protobuf converter?

**Comment by araichev** [comment]
@kevinkreiser can you elaborate on the intended meaning of the protobuf fields of the spec? That will help whoever works on this task translate concepts between GTFS and the protobuf spec.

**Comment by kevinkreiser** [comment]
i think @drewda would be best to answer those questions as hes the key maintainer of transitland!

**Comment by toton6868** [comment]
@kevinkreiser, I am afraid whether @drewda or any other from transitland will response or not. I saw some bitter conversion between @drewda and @Rui-Santos related to this. After that, I didn't see @drewda make any comment here in Valhalla repo. 

@Rui-Santos, Did you solve this issue? 

> Beauty is in the eyes of the beholder

Learned from your comment. Here you made a commitment at early 2018. But you didn't make any commit related to custom GTFS import. Seems like we have to move to GraphHopper as there is no GTFS restriction. Can't blame Valhalla team too as they are now part of Mapbox and they must follow the priorities of Mapbox. Moreover, Mapbox changed its Navigation SDK licensing policy. Seems like there will be no open source navigation solution in near future

**Comment by kevinkreiser** [comment]
@toton6868 at the moment we dont have any bandwidth for devoting time to custom GTFS imports. I do think one could get this going on their own if they were willing to both read our protobuf defintion for the data that comes from transit land and then write a tool to translate gtfs into protobuf messages in that format. im sorry we can't help you at the moment but you are welcome to try it in your own of course!

**Comment by toton6868** [comment]
@kevinkreiser Thanks. I know you guys are busy. I am not a code-savvy guy. I am tracking this issue since you provided the [transit.proto](https://github.com/valhalla/valhalla/blob/master/proto/transit.proto) but I am not capable of conversion. Anyway, thanks. At least you replied that makes me happy. In other forum members/contributors even does not reply.

**Comment by karimhm** [comment]
Any updates regarding this feature?

**Comment by pranavpandey1998official** [comment]
hi @kevinkreiser and @dnesbitt61 from reading your code I think part 1 and 3 are done only part 2 `Program an application to convert GTFS into pbf tiles.` remains so If I can convert the GTFS to your probuf I think everything should work, If that is correct I want to take up this

**Comment by kevinkreiser** [comment]
@pranavpandey1998official yes that is correct. if you could take raw gtfs and convert it to the pbf format tiles directly then the rest should "just work". ill say that you should very closely read and understand the `valhalla_fetch_transit` source file and model the pbf building from that. i would also perhaps opening up a new discussion in the discussions tab of this repo so we can answer more specific implementation questions as they come up.

thanks and good luck!

**Comment by kevinkreiser** [comment]
This issue has grown out of date but the idea is still a good one. I'm going to close this and open a new issue with details on how to implement what is left to get this working. Thanks everyone for the input and effort so far!
