### ISSUE TITLE
Valhalla as a library, not service

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#706]
As a part of learning Valhalla, I am looking into its dependencies and the ways I can use it to provide offline routing on mobile. For me, it would be easier to use Valhalla as a library and not as a service. This is due to the fact that I am already providing a service that allows to render/search/route offline. Having an additional service would step out of the current design and may require changes in client programs (not that its impossible, but would be reasonable to avoid).

As far as I understand, my use case would be similar to `valhalla_run_route`. From the dependencies (`ldd`) of `valhalla_run_route`, I can still find zmq and prime_server. Hence the questions:

* Is it possible to use Valhalla as a library and communicate with the modules via C++ function calls? In this usage scenario, if possible, is ZMQ/prime_server still required?

If it is all very complicated, I can look into deployment as an additional service as well. However, would be great to know the options.

**Comment by kevinkreiser** [comment]
you are correct that zmq/prime_server is not required for this scenario however we havent yet taken the pains needed to separate these bits of code out from the regular libvalhalla.so target within our makefile. 

one can semi-easily achieve this by making the service parts of the build conditional (like the data-tools) and also moving the service dependencies (`$(DEPS)`) in `configure.ac` into their own variable (call it `$(SERVICE_DEPS)`) and only link those with the conditional service build targets. let me know if this makes sense to you. it'd be great to get a pr with this functionality from you. if you arent familiar with autotools then we'll have to take care of it when we get a spare moment.

**Comment by rinigus** [comment]
It makes sense. I will evaluate then valhalla on mobile properly and, if all is fine, look into changing the build files. Give me 1-2 weeks, since I have to finish few other things first, and, if no-one will beat me to that, I'll look on fixing the build.

**Comment by rinigus** [comment]
As a follow up: does `valhalla_build_tiles` need ZMQ/prime_server? Or it can be built without services?

**Comment by kevinkreiser** [comment]
`valhalla_build_tiles` does not depend on the service dependencies no, it doesn't depend on zmq/prime_server

**Comment by rinigus** [comment]
OK, the first tests on mobile passed - its impressive! In addition to modification of Makefile.am and configure.ac, I had to make small changes in 

```
src/baldr/location.cc
src/thor/route_matcher.cc
```
One of them was ambiguity (in the eyes of compiler) of radius_ (I presume it should be `uint64_t`, in `src/baldr/location.cc`) and inclusion of non-needed `service.hpp` (`src/thor/route_matcher.cc`). 

Before submitting PR, I probably would go through the code that I sent to SERVICES part to check whether service.hpp was included for convenience or was needed.

**Comment by rinigus** [comment]
while this issue can be considered as a general one, maybe we should close it now since the specific problem got resolved

**Comment by kevinkreiser** [comment]
sounds good
