### ISSUE TITLE
Installing on debian jessie

### ISSUE THREAD

**Issue by oliverbienert** [valhalla/valhalla#708]
Hello,
in your readme you write:

> To install on a Debian or Ubuntu system you need to install its dependencies with:
> `sudo add-apt-repository -y ppa:valhalla-core/valhalla`
> `sudo apt-get update`
> `sudo apt-get install -y autoconf automake...`

But there is no package for jessie:
`Failed to fetch http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found`

Also, when I try to install dependencies, the the following errors occur:
```
E: Unable to locate package libprime-server0.6.3-dev
E: Couldn't find any package by regex 'libprime-server0.6.3-dev'
E: Unable to locate package prime-server0.6.3-bin
E: Couldn't find any package by regex 'prime-server0.6.3-bin'
```
Instructions obviously only work for Ubuntu? How do I install this on a debian jessie system?

Regards Oliver

**Comment by kevinkreiser** [comment]
thats right, although debian and ubuntu are very closely related we dont specifically build packages for the various debian releases. i have not tried it, but does this process work for you: https://wiki.debian.org/CreatePackageFromPPA

i think we would happily publish debian packages but we aren't sure of the process of becoming a debian developer. any help on this would be appreciated

**Comment by PayasR** [comment]
Hey @kevinkreiser! How about fedora/RHEL? I couldn't find any COPR repositories. Any ideas?

**Comment by kevinkreiser** [comment]
@PayasR We'd love to support as many distros as possible! If you have any knowledge of how to build rpms etc we'd love to see contributions. At this time we dont have any plans to spend time on these types of things but we'd love to provide info to people who are more experts in packaging for different platforms. let us know if you want to work on this and we can open an issue and we can answer questions as you or someone else is working towards it.

**Comment by PayasR** [comment]
@kevinkreiser I'd love to! 
I just had a look at https://github.com/valhalla/packaging . 
I shall open an issue there, and I've created a COPR project at https://copr.fedorainfracloud.org/coprs/payasr/valhalla/

**Comment by carlos-mg89** [comment]
It doesn't even work on Ubuntu 17.10 and on Ubuntu 18.04 (tested both yesterday and today).

For Ubuntu 18.04 the error I got when `sudo add-apt-repository -y ppa:valhalla-core/valhalla` is:

> Ign:6 http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu bionic InRelease                                                  
> Err:7 http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu bionic Release                        
>   404  Not Found [IP: 91.189.95.83 80]

While checking the http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu  I can see that the last Ubuntu version that's supported is 16.04. Could you add Ubuntu 18.04 too since it's LTS and it's the last Ubuntu version?

Thanks in advance
P.S. An alternative way to build Valhalla will work for me as well.

**Comment by kevinkreiser** [comment]
we want to add 18.04 support but to do so we need to do a little work because we moved from autotools to cmake so our tooling around doing a ppa release is out of date. we need to spend some time updating but dont have a lot of extra time for that at the moment. in the mean time just follow the directions in the readme for building valhalla from source @carlos-mg89

**Comment by kevinkreiser** [comment]
@carlos-mg89 right right. those assume you can use the ppa to get at some of the other dependencies... ok you'll need to build one other thing from source with is [prime_server](https://github.com/kevinkreiser/prime_server/). go clone that and follow its readme to get it built and installed on your system, then valhalla should build. alternatively, if you dont want to build the http server components of valhalla you can just build valhalla from source without `prime_server` by configuring cmake with: `cmake .. -DENABLE_SERVICES=OFF` then make should work. If you want `apt-get` to not error because of missing packages you can skip these packages: `libprime-server0.6.3-dev` `prime-server0.6.3-bin`

**Comment by carlos-mg89** [comment]
Mmm, it seems I'm almost there.

I successfully ran `cmake .. -DENABLE_SERVICES=OFF`. But when I run `make`, I got the following error log:

```
[  0%] Running C++ protocol buffer compiler on transit_fetch.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: transit_fetch.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  0%] Running C++ protocol buffer compiler on directions_options.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: directions_options.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: tripcommon.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  2%] Running C++ protocol buffer compiler on navigator.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: navigator.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  2%] Running C++ protocol buffer compiler on route.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: route.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  2%] Running C++ protocol buffer compiler on tripcommon.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: tripcommon.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  2%] Running C++ protocol buffer compiler on tripdirections.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: tripdirections.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: tripcommon.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[  2%] Running C++ protocol buffer compiler on trippath.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: trippath.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: tripcommon.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
make[2]: *** No rule to make target 'proto/fileformat.proto', needed by 'src/valhalla/proto/fileformat.pb.cc'.  Stop.
CMakeFiles/Makefile2:1105: recipe for target 'src/valhalla/proto/CMakeFiles/valhalla-proto.dir/all' failed
make[1]: *** [src/valhalla/proto/CMakeFiles/valhalla-proto.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

If I run it, again, I get:

```
make[2]: *** No rule to make target 'proto/fileformat.proto', needed by 'src/valhalla/proto/fileformat.pb.cc'.  Stop.
CMakeFiles/Makefile2:1105: recipe for target 'src/valhalla/proto/CMakeFiles/valhalla-proto.dir/all' failed
make[1]: *** [src/valhalla/proto/CMakeFiles/valhalla-proto.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

I have previously executed this line:

`sudo apt-get install -y autoconf automake make libtool pkg-config g++ gcc jq lcov protobuf-compiler vim-common libboost-all-dev libboost-all-dev libcurl4-openssl-dev zlib1g-dev liblz4-dev libprotobuf-dev`

So I'm a bit out of ideas on how to continue...

**Comment by kevinkreiser** [comment]
you need to get the submodules of the repository. try this:

    git submodule sync
    git submodule update --init --recursive

**Comment by carlos-mg89** [comment]
I got Valhalla up and running, or at least some of it. If I run valhalla_run_route like this:

`valhalla_run_route -j '{"locations":[{"lat":41.81021999190292,"lon":2.142791803926229},{"lat":41.86342467181004,"lon":1.4643860422074795}],"costing":"pedestrian","directionsoptions":{"language":"en-US"}}' --config ./valhalla.json`

Then I get a list of routing instructions in the terminal (with the [NARRATIVE] tag next to it). But I don't see any response anywhere with route details as I read here https://github.com/valhalla/valhalla/blob/2.6/docs/api/turn-by-turn/api-reference.md perhaps there's a file where the output with the route details is written?

Rethinking about the prime_server, I revisited your guide (above on this issue) to build Valhalla with the prime_server, thinking it might be what I was looking for. ss I can have the API server up and running locally. I have successfully built the prime_server, or that's what I think. And after that, I believe I rebuilt Valhalla properly. But I don't find a way of setting up the Valhalla server, so I can run calls like this:

```
#start up the server
valhalla_service valhalla.json 1 // In my case, I cannot find valhalla_service
#curl it directly if you like:
curl http://localhost:8002/route --data '{"locations":[{"lat":40.285488,"lon":-76.650597,"type":"break","city":"Hershey","state":"PA"},{"lat":40.794025,"lon":-77.860695,"type":"break","city":"State College","state":"PA"}],"costing":"auto","directions_options":{"units":"miles"}}' | jq '.'
```

Could you give me a hand @kevinkreiser ?

**Comment by dnesbitt61** [comment]
maybe try:
./valhalla_service valhalla.json 1

**Comment by kevinkreiser** [comment]
right so when you build without `prime_server` earlier you disabled the building of `valhalla_service`. you'll need to recompile valhalla with prime_server support. so this time around dont pass `cmake` the option `-DENABLE_SERVICE=OFF` this will build a couple extra executables including `valhalla_service` which make use of prime_server

**Comment by carlos-mg89** [comment]
That's what I just tried, and now I got the valhalla_service created.

I had to run `sudo ldconfig` as well, since I was getting a shared library not found error:

> valhalla_service valhalla.json 1
> valhalla_service: error while loading shared libraries: libprime_server.so.0: cannot open shared object file: No such file or directory

Now I have been able to run the `valhalla_service` and I can send HTTP requests against it.

Thanks to both of you!

**Comment by kevinkreiser** [comment]
@oliverbienert at this point in time we dont target debian package repositories but our latest builds do have cmake support for creating debian packages (`.deb`) files. please have a go at those and open an issue if they dont work for you!

**Comment by oliverbienert** [comment]
@kevinkreiser thank you for the feedback. I think I finally installed and used it successfully on a Ubuntu box  back then. Sadly, after the sudden death of mapzen, however, we stopped using pelias. As I recall, I used valhalla to compute polylines. Thank you nevertheless and keep the good work!
