### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by albertotn** [valhalla/valhalla#716]
Hi!  In my company we are using valhalla for routing and we are facing a strange behaviour.

Our pipeline consist in: extracting osm data using metroextract, using valhalla as a service to generate routing between points.

The problem is generated using these points: https://www.openstreetmap.org/directions?engine=osrm_car&route=44.1702%2C12.2999%3B44.1935%2C12.2807#map=15/44.1819/12.2889

And the result in our application is the following:

<img width="309" alt="1" src="https://cloud.githubusercontent.com/assets/12526457/26064405/265ca1c8-3991-11e7-8d91-0b2a7ebb545f.png">

detail:

<img width="550" alt="2" src="https://cloud.githubusercontent.com/assets/12526457/26064419/2fd2511c-3991-11e7-89dd-659409cb3a5b.png">

As you can see Valhalla result is a small geometry with no connection with starting and ending point.

The log on valhalla side is the following:

2017/05/15 14:54:15.674773 POST /route HTTP/1.1
2017/05/15 14:54:15.674846 [INFO] Got Loki Request 60
2017/05/15 14:54:15.674973 [ANALYTICS] locations_count::2
2017/05/15 14:54:15.674994 [ANALYTICS] costing_type::bus
2017/05/15 14:54:15.675064 [ANALYTICS] location_distance::3.020359km
2017/05/15 14:54:15.675874 [INFO] Got Thor Request 60
2017/05/15 14:54:15.676257 [ANALYTICS] travel_mode::0
2017/05/15 14:54:15.678458 [ANALYTICS] admin_state_iso::
2017/05/15 14:54:15.678481 [ANALYTICS] admin_country_iso::
2017/05/15 14:54:15.678648 [INFO] Got Odin Request 60
2017/05/15 14:54:15.679016 [INFO] trip_path_->node_size()=2
2017/05/15 14:54:15.679111 [INFO] maneuver_count::2
2017/05/15 14:54:15.679246 [INFO] Got Tyr Request 60
2017/05/15 14:54:15.679473 [ANALYTICS] language::en-US
2017/05/15 14:54:15.679565 [ANALYTICS] trip_length::0.061001km

Could someone please help us ? Thanks in advance!

**Comment by kevinkreiser** [comment]
the link you sent, if you switch it to mapzen (which is valhalla) works perfectly. to me it looks like (given the second picture you posted) you dont have data loaded for that region of the map.

it will snap your input to the closest part of the map you have data for and run that route.

also, i noticed your costing is `bus`. i tried the above request with `bus` but it didnt make a difference. in both cases `bus` and `auto` drive 366 seconds 4.456.

make sure your extract contains that entire region. if you have the extract please let us know where you got it.

**Comment by albertotn** [comment]
Thanks for quick answer.

I've tried, following your suggestion, to generate the route using mapzen today and the result is the following:

![image 3](https://cloud.githubusercontent.com/assets/12526457/26096522/c035d36a-3a21-11e7-994b-09432517940f.png)

for the region we selected a big region ( just be clear, the route is near Cesena, as you can see from the selection is bigger than that):

![image 2](https://cloud.githubusercontent.com/assets/12526457/26096568/e5a832d2-3a21-11e7-87bc-667e32d5f944.png)

**Comment by kevinkreiser** [comment]
this is very interesting and could be a regression from #711 ill have a look

**Comment by albertotn** [comment]
Thanks, we made a check with last version of Valhalla ( one with #722 fixed ) and now works, on openstreetmap and in our installation:

![image](https://cloud.githubusercontent.com/assets/12526457/26254482/f8da620c-3cb6-11e7-9ec5-c24205682c4b.png)

Thanks!
