### ISSUE TITLE
Weird rectangular pedestrian isochrones

### ISSUE THREAD

**Issue by tarakc02** [valhalla/valhalla#721]
When using the isochrone service for pedestrian isochrones in specific locations, I end up with rectangular regions that don't seem correct. For instance, when looking for the region within 15 minutes walk of Gamla Stan station in Stockholm using the following JSON:

`{"locations":[{"lon":18.0672,"lat":59.3234}],"costing":"pedestrian","contours":[{"time":15,"color":"feedde"}]}`

I get a (to me) unexpectedly sharp rectangular shape:

https://matrix.mapzen.com/isochrone?api_key=mapzen-XXXXXXX&json=%7B%22locations%22%3A%5B%7B%22lon%22%3A18.0672%2C%22lat%22%3A59.3234%7D%5D%2C%22costing%22%3A%22pedestrian%22%2C%22contours%22%3A%5B%7B%22time%22%3A15%2C%22color%22%3A%22feedde%22%7D%5D%7D

I see the same thing when I use mobility explorer (and note there are no contours for 15, 30, 45, 60 -- just the single rectangle):

https://mapzen.com/mobility/explorer/#/isochrones?bbox=17.994747161865234%2C59.305466971009466%2C18.140058517456055%2C59.341068461392275&isochrone_mode=pedestrian&pin=59.323229%2C18.06744

Anyway, that happens for some locations, whereas with most locations I see the expected contours.

**Comment by dnesbitt61** [comment]
We just fixed a bug in isochrone code that should address this. It is disallowing pedestrian only roads/paths. We will try to get a bug fix into production soon.

**Comment by gknisely** [comment]
@tarakc02  production has been updated.  Can you let us know if the issue has been resolved?

**Comment by tarakc02** [comment]
@gknisely - Yup, I'm not seeing the issue anymore. Thanks!

**Comment by tarakc02** [comment]
I've found another instance of what seems to be the same problem. Here is the json, looking for isochrones within 60 minutes driving distance of Gothenburg:

```locations":[{"lon":12.0143,"lat":57.7356}],"costing":"auto","contours":[{"time":60,"color":"feedde"}]```

It results in a little sharp-edged rectangle:

https://matrix.mapzen.com/isochrone?api_key=mapzen-XXXXXX&json=%7B%22locations%22%3A%5B%7B%22lon%22%3A12.0143%2C%22lat%22%3A57.7356%7D%5D%2C%22costing%22%3A%22auto%22%2C%22contours%22%3A%5B%7B%22time%22%3A60%2C%22color%22%3A%22feedde%22%7D%5D%7D&id=test1

This was discovered by @duleise and reported at tarakc02/rmapzen#10
Thanks

**Comment by dnesbitt61** [comment]
This is due to the service road: http://www.openstreetmap.org/way/372104821. That is the closest OSM way that allows auto use, but it is not connected to other OSM ways. If you know this area you can make OSM edits to improve the connectivity of roads. We are working on a fix to find other nearby OSM ways that allow auto use.
