### ISSUE TITLE
Add edges, as well as avoid?

### ISSUE THREAD

**Issue by kuanb** [valhalla/valhalla#725]
Notes before I continue: Apologies in advance for any ignorance in the codebase in this issue, I just started digging into it a little. Also, I didn’t notice a Gitter or the like so I assume that this question/idea is “ok” for a GH issue - if it is not, apologies for that as well and happy to move the conversation elsewhere.

Observation: I see a late Feb PR [0] that adds an avoid edge parameter in the Dynamic Costing stage of Valhalla, (within a submodule named Sif). [1] 

While this is effective at observing the impacts of a removed critical edge in a graph, it seems as though there remains an opportunity to also include support for a user to introduce new edges to the graph and see "positive" impacts of increased network accessibility. 

I’m not sure where this would occur and acknowledge that its more complex than knocking out a preexisting edge, but it seems like the analysis for edges in the isochrone analysis is aggregated to (for walk for example) a 200m grid, so one could theoretically simply introduce a new network element that reduces the cost to go from one summary matrix cell to another (or a few of these) and then appends these edge observations after costs from each matrix cell is calculated (that is, if new edge is lower in time/dist/cost than what has been calculated, then swap out for added feature).

Again, don’t want to pretend I’m much use in C++ so I don’t know for sure where this would go, but it seems like the IsoTile construction in the Thor submodule produces the reference matrix that is then used to evaluate access and it’s soon after this is produced that the logic could be introduced. 

This intervention would allow for both addition and removal of edges, and remove the need for the avoidance tag in the dynamic costing stage.

[0] https://github.com/valhalla/valhalla/pull/567
[1] https://github.com/valhalla/valhalla/blob/master/src/sif/dynamiccost.cc#L58
[2] https://github.com/valhalla/valhalla/blob/master/src/thor/isochrone.cc#L72

**Comment by dnesbitt61** [comment]
Routing and isochrones use a routing network or graph composed of nodes (intersections) and edge (roads and paths). There is no notion of a "grid" - though there are many standard algorithms for shortest path through a grid, but we do not construct such a grid (with costs and such). If our routing was based on a grid based approach like this then we could do what you say, but this is not supported at this time.

**Comment by kuanb** [comment]
Thanks for the note, @dnesbitt61 - I clearly misunderstood the section where the region is broken up into `n` meter grids for walk or bike or car. I suppose that raster is generated solely for the purposes of rendering the isochrone.

Below: Follow up ques. I'll close this issue though so as to not clutter your Issues feed + understand / no worries if no time to answer further questions - mostly just curious for myself. :)

Where in the Valhalla codebase does the are paths determined for the isochrone? Does it occur as a database query? I feel like, if it occurred outside the database it would still be possible to somewhat easily inject additional edges during the calculations of possible route paths and assessment of associated costs? I'm guessing this would be in Thor, but I can't find it at the moment.

**Comment by dnesbitt61** [comment]
Code to generate the "isotile" (grid with times to get to each grid cell) is in thor/isochrone.cc. This basically expands from a location in a "lowest cost" / shortest path way until the time threshold is crossed. Each graph edge that is expanded is used to update the isotile grid cells that the edge intersects (if the time / cost is lower than what is stored in the grid cell).

**Comment by kuanb** [comment]
Sorry I incorrectly wrote when asking where the code was for the paths used in the isochrone. I mean to ask where are paths/routes determined generally. 

That is, where is the graph of edges traversed when attempting to identify possible paths? I'm curious if that is done in a way such that edges could be introduced during that calculation.

**Comment by dnesbitt61** [comment]
The routing graph is built from OpenStreetMap data using applications/code within the valhalla/mjolnir directory. Classes to read / access the rouing within path algorithms in thor are contained within the baldr directory. The routing graph is static (takes many hours) and there is no way (currently) to add graph edges (the routing graph is not editable - only the costing of particular edges is).

**Comment by kuanb** [comment]
Thanks again, I'll take a look.

This whole thought came to mind because I was mocking out adding and removing edges and then converting them to a network with [Pandana](https://github.com/UDST/pandana) and noticed that Mapzen's isochrones were raster. I thought that, perhaps, at the time the isochrones were calculated one could theoretically introduce a secondary, ad hoc network that computed its own costs to each matrix cell and would then supplant the results from the standard Valhalla outputs in cases where its costs to a given cell were lower than those calculated through the "default" process. 

Thanks again for responses.
