### ISSUE TITLE
docker: locally hosted valhalla server cannot parse encoded urls

### ISSUE THREAD

**Issue by mxndrwgrdnr** [valhalla/valhalla#740]
Running valhalla/docker container locally, this url (http://localhost:8002/route?json=%7B%22locations%22%3A+%5B%7B%22lat%22%3A+37.75286%2C+%22type%22%3A+%22break%22%2C+%22lon%22%3A+-122.40486%7D%2C+%7B%22lat%22%3A+37.790168%2C+%22type%22%3A+%22break%22%2C+%22lon%22%3A+-122.402264%7D%5D%2C+%22costing%22%3A+%22auto%22%2C+%22id%22%3A+%22my_work_route%22%7D) does not work, while this url (http://localhost:8002/route?json={"locations":[{"lat":37.75286,"type":"break","lon":-122.40486},{"lat":37.790168,"type":"break","lon":-122.402264}],"costing":"auto","id":"my_work_route"}) works fine. Both urls work fine using the valhalla.mapzen.com-hosted API, so it seems that the dockerized version is having trouble with encoded URL's.

Steps the recreate bug:

1. `VALHALLA_DOCKER_DATAPATH=<path/to/tiles.tar> docker-compose -f docker-compose-ppa.yml up`
2. Click on the URLs above.

**Comment by dnesbitt61** [comment]
The first URL is not valid JSON (try jsonlint), so it fails regardless (Docker has no impact).  Where did you get this URL from?

**Comment by kevinkreiser** [comment]
yeah it looks like whatever you have doing the encoding is encoding `:` when it doesnt need to. the properly encoded get line would be:


    http://localhost:8002/route?json=%7B%22locations%22:%5B%7B%22lat%22:37.75286,%22type%22:%22break%22,%22lon%22:-122.40486%7D,%7B%22lat%22:37.790168,%22type%22:%22break%22,%22lon%22:-122.402264%7D%5D,%22costing%22:%22auto%22,%22id%22:%22my_work_route%22%7D

**Comment by mxndrwgrdnr** [comment]
It seems like jsonlint doesn't validate the first URL b/c its a localhost URL. If you replace `localhost:8002` with `valhalla.mapzen.com` then jsonlint validates it. Similarly, if you actually navigate to the url after replacing localhost with the valhalla host, the URL works. I'm generating the URLs in Python using the Requests library.

**Comment by dnesbitt61** [comment]
I just validate the part of the URL after json=.  No clue how this works in production.

**Comment by mxndrwgrdnr** [comment]
Maybe this is just my lack of familiarity with jsonlint, but the properly encoded json from Kevin's post above doesn't seem to validate in jsonlint either?

**Comment by kevinkreiser** [comment]
the thing i pasted was urlencoded you first need to url decode it. the way valhalla works is that we use curl to url decode the query params portion (the bit after `route?`) of the url. it turns out the problem here is that you have a `+` after the encoded `:` (`%3A`). so when curl decodes it this is what happens:

```console
kkreiser@HP-ZBook-15:/data/sandbox/valhalla/valhalla$ cat a.cpp 
#include <curl/curl.h>
#include <iostream>

  std::string url_decode(const std::string& encoded) {
    char* decoded = curl_unescape(encoded.c_str(), static_cast<int>(encoded.size()));
    if(decoded == nullptr)
      throw std::runtime_error("url decoding failed");
    std::string decoded_str(decoded);
    curl_free(decoded);
    return decoded_str;
  }

int main(void) {

  auto s = url_decode(R"(%7B%22locations%22%3A+%5B%7B%22lat%22%3A+37.75286%2C+%22type%22%3A+%22break%22%2C+%22lon%22%3A+-122.40486%7D%2C+%7B%22lat%22%3A+37.790168%2C+%22type%22%3A+%22break%22%2C+%22lon%22%3A+-122.402264%7D%5D%2C+%22costing%22%3A+%22auto%22%2C+%22id%22%3A+%22my_work_route%22%7D)");
  std::cout << s << std::endl;
return 0;

}
kkreiser@HP-ZBook-15:/data/sandbox/valhalla/valhalla$ g++ -std=c++11 a.cpp -lcurl
kkreiser@HP-ZBook-15:/data/sandbox/valhalla/valhalla$ ./a.out 
{"locations":+[{"lat":+37.75286,+"type":+"break",+"lon":+-122.40486},+{"lat":+37.790168,+"type":+"break",+"lon":+-122.402264}],+"costing":+"auto",+"id":+"my_work_route"}
```

notice it has `+` all over in there. so yeah whatever is putting that `+` char in there shouldnt do that :smile:

**Comment by mxndrwgrdnr** [comment]
OK so this was just a flub on my part. Should have just been using POST requests from the get go. The only weird thing here is that the production API is able to parse the improperly formatted JSON in the first place. Closing this.
