### ISSUE TITLE
Add support for per mode restrictions

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#747]
e.g., restriction:bus tags

Add these as "complex" restrictions which currently support per mode lookup (unlike simple restrictions which are assumed to apply to all driving modes).

**Comment by mmajan87** [comment]
Hi @dnesbitt61 and @gknisely ...how easy/complicated is this? It is important for us (esentially for buses), so would be great to know your thoughts on the matter and when do you think you might be able to handle it in valhalla.
Thanks in advance

**Comment by dnesbitt61** [comment]
I think this should mostly be updates to data ingestion (valhalla_build_tiles) which makes it somewhat less complicated but with a longer turn around. Probably would take one week once we find time to focus on this.

**Comment by mmajan87** [comment]
Ok, thanks a lot for the info. Please keep me posted as this is very important to us!

Thanks!

**Comment by gknisely** [comment]
I have found an issue with the new logic.  I have a fix and I am in the process of testing it.
