### ISSUE TITLE
Return Corrected Shape in trace_attributes

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#75]
(2017-01-23T18:10:25Z) @kevinkreiser : originally created valhalla/thor#549

currently we dont returned the matched shape points. this is useful for many applications and is the original application map mathcing within valhalla was implemented (by @ptpt) to solve. it would be nice if we could return this information as well. this could be a good first step to migrating meili on service bits to thor so that they could run along with all of the rest of the services. eventually we'll want to actually allow asking for the original geojson response as well via a separate url. for that we should be able to make use of the original code directly.

(2017-01-26T16:07:54Z) @ptpt : Thanks bringing it up. Will manage to work on importing some code to Thor this weekend. Should I add it to a new action called `trace_shape` or add it to `trace_attributes`?

(2017-01-30T17:03:38Z) @dgearhart : @ptpt we would like to have it for trace_attributes. Please let us know your progress

(2017-02-01T09:17:37Z) @ptpt : It's not started yet. If it isn't urgent, I will do it when the Great Migration is done.

Two priorities ahead for me:
1. [x] Add a text box at http://valhalla.github.io/demos/map_matching/ to support GeoJSON input (copy&paste) for easier debugging
2. [x] Fix https://github.com/valhalla/meili/issues/76

**Comment by dgearhart** [comment]
@ptpt any progress on this one?

**Comment by ptpt** [comment]
I'm going to do it today. Where should I read the incoming shape and place the match shape?

1. send shapes (GeoJSON) to `POST /trace_attributes` and get matched shape from the response, as meili does https://github.com/valhalla/valhalla/blob/master/docs/meili/service_api.md
2. or put shape in the `json` URL parameter and place match shape in the `shape` property as `trace_attributes` does https://github.com/valhalla/valhalla-docs/blob/master/map-matching/api-reference.md ?

**Comment by kevinkreiser** [comment]
if i understand you correctly, i think we want to do both in the end.

1. it would be nice to deprecate the meili stand alone service and just be able to access it via `valhalla_route_service` like the rest of the services. the thing about that option is that it will take a lot more work

2. i think this one will be a lot easier. basically we just need to also return (in the json) the matched shape. and only for trace_attributes. the implementation would be something like:

- the request would have an optional `matched_shape: true|false` defaulted to `false` (`auto matched_shape = request_pt.get<bool>("matched_shape", false);`)
- if the above option was true we copy the matched shape out of the matching objects and stuff it into a `matched_shape` key on the return. it should should be polyline encoded

@ptpt @dgearhart @dnesbitt61 what do you think?

**Comment by dnesbitt61** [comment]
Yes, I like this approach. Only on trace_attributes (since modifying a route result would be much harder) with an input to specify whether you want the optional return.
