### ISSUE TITLE
No real testing for matrices

### ISSUE THREAD

**Issue by acwilton** [valhalla/valhalla#759]
We have no testing at all for CostMatrix or TimeDistanceMatrix. Perhaps some unit tests could be made for some of the individual parts of CostMatrix and TimeDistanceMatrix. Then maybe some tests comparing the matrices' distances and times to that of the actual routing algorithms using random routes and/or some predetermined ones? Though, it may be necessary to fix issue #425 to do that. (If that issue is still valid)

**Comment by dnesbitt61** [comment]
Could some tests be added that use the Utrecht data (similar to how map-matching tests use it)?

**Comment by kevinkreiser** [comment]
yeah go for it!

**Comment by acwilton** [comment]
Closed by #884
