### ISSUE TITLE
use customizable map matching options in traffic segment matcher

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#769]
we want to allow requests to traffic segment matcher change map matching parameters on the fly (just like in meili service and trace_* services). to do so we need to basically copy this method:

https://github.com/valhalla/valhalla/blob/master/src/thor/service.cc#L302-L330

into a protected method of the traffic_segment_matcher and then use of it when constructing the mapmatcher shared_ptr. after that requests should be able to change anything in the customizable list via adding to the request something like `"trace_options":{"sigma_z": 5.3}`

**Comment by kevinkreiser** [comment]
while we're at it we should start respecting the mode of travel, ie require the `costing` be passed

**Comment by drewda** [comment]
@dnesbitt61 is debugging to see if this is working

**Comment by drewda** [comment]
Works now. You just need to make sure to specify which parameters are customizable by request:

```json
   "customizable": [
      "mode",
      "search_radius",
      "turn_penalty_factor",
      "gps_accuracy",
      "beta",
      "sigma_z"
    ],
```
