### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by eson57** [valhalla/valhalla#775]
Hi guys!
Because of [OSM Scout Server](https://openrepos.net/content/rinigus/osm-scout-server), I'm trying to translate valhalla into Swedish and found that it is really, really hard to find an acceptable Swedish solution for the <CARDINAL_DIRECTION> block. So I was thinking, maybe there is Swedish people involved in this project, that can come up with suggestions/ideas?

**Comment by kevinkreiser** [comment]
@eson57 what are you finding difficult? maybe we can give some advice. Can you give some examples and the problems they raise? As we add support for new languages we may need to add new ways of handling certain linguistic constructs. If you could give us some details maybe we can get it figured out! Ha det bra!

**Comment by eson57** [comment]
OK, lets see if can explain this in English.

The main problem is the initial three "Head <CARDINAL_DIRECTION>" strings. To make sense in Swedish I have to remove "Head" and therefore, <CARDINAL_DIRECTION> sometimes needs to start in upper case and sometimes not.
Swedish people may think that I could keep the "Head", translated to "Mot", but that will work only in some cases. For most strings, that solution will result in really bad Swedish.

This is, in my opinion, the best translation for the cardinal_directions, that will work everywhere but as said... sometimes there will be a need for leading upper case.

`      "cardinal_directions": ["norrut", "mot nordost", "österut", "mot sydost", "söderut", "mot sydväst", "västerut", "mot nordväst"],`

Please let me know if I need to explain this further.

**Comment by kevinkreiser** [comment]
thats perfectly fine. we can override the swedish narrative builder to capitalize these in the code. if you can make a pull request with the language file we can make the code changes to capitalize when it appears at the beginning of the phrase. tack igen!

**Comment by eson57** [comment]
Great, if you can do that. 👍  PR coming up as soon as I am ready translating. I kind of put it on hold, because of this.  :)
