### ISSUE TITLE
Combine short becomes maneuver with previous maneuver

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#82]
(2015-11-09T20:28:22Z) @dgearhart : originally created valhalla/odin#157

Investigate and implement without negatively impacting other routes

-j '{"locations":[{"lat":40.256802,"lon":-76.709160,"street":"Middletown Road"},{"lat":40.259254,"lon":-76.714989,"street":"US 322 West"}],"costing":"auto","directions_options":{"units":"miles"}}' --config ../conf/valhalla.json

Current output:
1: Head north on Middletown Road. 
   VERBAL_PRE: Head north on Middletown Road for 1 tenth of a mile.

2: Continue on South Hanover Street. 
   VERBAL_ALERT: Continue on South Hanover Street.
   VERBAL_PRE: Continue on South Hanover Street for 40 feet.

3: Turn left to take the US 322 West ramp toward Harrisburg. 
   VERBAL_ALERT: Turn left to take the U.S. 3 22 West ramp.
   VERBAL_PRE: Turn left to take the U.S. 3 22 West ramp toward Harrisburg.

4: Merge onto US 322 West. 
   VERBAL_ALERT: Merge onto U.S. 3 22 West.
   VERBAL_PRE: Merge onto U.S. 3 22 West.
   VERBAL_POST: Continue for 2 tenths of a mile.

5: You have arrived at US 322 West. 
   VERBAL_ALERT: You will arrive at U.S. 3 22 West.
   VERBAL_PRE: You have arrived at U.S. 3 22 West.

(2016-01-15T19:44:02Z) @nvkelso : +1

**Comment by nvkelso** [comment]
Heck ya!
