### ISSUE TITLE
Look into penalizing walking a bit more for Multimodal routes

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#821]
Instead of waiting for a bus or train we will sometimes walk excessively.  Please see
mapzen/eraser-map#828

Changing use_bus = 1.0 does fix this issue
37.42013,-122.13588
37.44473,-122.16245

**Comment by dgearhart** [comment]
Example route: https://github.com/valhalla/valhalla/blob/master/test_requests/nyc_transit_routes.txt#L5
Walking too far at origin - from 25th st down to 14th st

Example route: https://github.com/valhalla/valhalla/blob/master/test_requests/nyc_transit_routes.txt#L9
Walking too far at origin and dest
![screenshot from 2017-07-11 11-20-30](https://user-images.githubusercontent.com/7515853/28075996-2eeae91e-662b-11e7-8145-2183ed054dcf.png)
![screenshot from 2017-07-11 11-21-04](https://user-images.githubusercontent.com/7515853/28076002-3bd81fb6-662b-11e7-9e72-a39bb019e97f.png)

**Comment by gknisely** [comment]
Using onestops from TL.  This appears to have the same issue.  s-c29r8y86wy-southboundyaleathodgins to s-c29r8ehemw-southboundvedderatelder
