### ISSUE TITLE
Ferry Route isn't using duration tag

### ISSUE THREAD

**Issue by cliffordsnow** [valhalla/valhalla#839]
Looking at the [Mukilteo-Clinton](http://www.openstreetmap.org/way/5901929#map=14/47.9621/-122.3271) the [router](http://www.openstreetmap.org/directions?engine=mapzen_car&route=47.9495%2C-122.3048%3B47.9747%2C-122.3495) returns a trip duration of 13 minutes yet the duration tag shows a duration of 20 minutes.

**Comment by gknisely** [comment]
Thank you!  We will add this in as soon as we can do so.
