### ISSUE TITLE
Unable to request transit isochrones with contours beyond 120 minutes

### ISSUE THREAD

**Issue by uqekizig** [valhalla/valhalla#849]
Result: {"error_code":151,"error":"Exceeded max time:120","status_code":400,"status":"Bad Request"}

I realize this is intended to happen, but it would be nice to be able to get isochrones beyond 2 hours, considering the large size and slow transit of some American metroplexes (for example in the DFW metroplex, it takes 3 hours to get from a Dallas suburb to a Fort Worth suburb with public transit, and that can't be represented unfortunately due to this 120 minute limitation).

**Comment by dnesbitt61** [comment]
Are you running Valhalla locally? If so you can update configuration to increase the limits.

**Comment by uqekizig** [comment]
I'm using the Mapzen API isochrone service as described here: https://mapzen.com/documentation/mobility/isochrone/api-reference/
