### ISSUE TITLE
Validate lane counts for two-way roads

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#863]
Seems that lane counts on two-way carriageways are incorrect:

example: way Id 369702856
has lanes:2 tag
Each directed edge has lanecount = 2 (instead of 1). Need to consider oneway logic when assigning lane counts (question might be what to do if an odd number of lanes).

**Comment by acwilton** [comment]
I think the only logical thing we can do if there is an odd number of lanes on a two-way road without additional tagging is to just assume the extra lane is in the "forward" direction as drawn in OSM.
