### ISSUE TITLE
Distance Matrix: Many-to-Many instead of Any-to-Any

### ISSUE THREAD

**Issue by porg** [valhalla/valhalla#870]
**Mapzen Time Distance Matrix** — demo at http://valhalla.github.io/demos/matrix/

## My application is the following

I have two data sets:
A) Apartment Candidates
B) Supermarkets (and Schools)

I want to get a table with all distances from each entry in A to each entry in B, and take this as a criteria, which apartment is most attractive location-wise.

## Current situation
This is what I expected from the option "many-to-many". But instead many-to-many is indeed any-to-any (any point to any point within one data set).

And the other options One-to-Many and Many-to-One only allow a single apartment against all schools or one school against all apartments.

## Alternatives

There is a readily available commercial solution for my application at:
https://mapline.com/distance-between-all-locations-in-two-data-sets/
the example given there is distribution-centers and retail-stores.
I wanted to see whether there is a freeware available for my private purposes, and your solution looked promising.

**Comment by kevinkreiser** [comment]
This exists in our api as well, and its called `sources_to_targets`. Simple set the candidates in `A` as the sources and the candidates in `B` as the targets. Please see here for more info: https://github.com/valhalla/valhalla-docs/blob/master/matrix/api-reference.md#matrix-service-actions

Let me know if I've misunderstood what you need.

**Comment by porg** [comment]
Wow, first off, impressive instant reply, thanks!
Is there a ready-to-use demo of sources_to_targets ?

**Comment by kevinkreiser** [comment]
hmmm a demo... not really, but the underlying algorithm works the same as any matrix. Basically the other matrix operations are just special cases of sources_to_targets. We should refactor the github.io demo to make use of sources to targets but its just using the various matrix types because that was the first interface we had. Historical reasons sadly :frowning: Anyway we can look into it! Please close this issue if it answered your question!

**Comment by porg** [comment]
My question has been answered, so in this regard it could be closed.

But developers or software-buyers/consultants likely want to see the feature in action within the demo, before taking any effort of setting up a development-environment to play around with the API.

So please consider updating your demo. Thanks!
