### ISSUE TITLE
Broken isochrone for multimodal?

### ISSUE THREAD

**Issue by slvlirnoff** [valhalla/valhalla#896]
Using the latest version of valhalla on my local setup I only get small square in response from isochrone with costing multimodal.

I see the same behavior using mapzen mobility explorer here for instance: 
https://mapzen.com/mobility/explorer/#/isochrones?bbox=-74.06364440917969%2C40.67894566107212%2C-73.94828796386719%2C40.74959782183326&isochrone_mode=multimodal&pin=40.71455760597044%2C-74.00105204433203

Walk, auto and bike isochrone works just fine.

Any idea?

Best,
Cyprien

**Comment by dnesbitt61** [comment]
PR https://github.com/valhalla/valhalla/pull/897 fixes this. Will try to update our hosted services early Tuesday (EDT)

**Comment by slvlirnoff** [comment]
Thanks @dnesbitt61 sounds good.
