### ISSUE TITLE
Pedestrian Routes Yield Strange Results when Ferries are Taken

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#906]
This is due to the A* heurisitic. It currently uses a factor based on the walking speed, but needs to use a factor based on the max. ferry speed. However, this leads to a large performance drop even when no ferries are taken. Maybe some factoring of the ferry penalties and use ferry factors can alleviate some of the performance drop?

http://www.openstreetmap.org/directions?engine=mapzen_foot&route=46.5127%2C6.4936%3B46.2223%2C6.0547#map=11/46.3562/6.2790

**Comment by Stedewa** [comment]
Hi, I've reported the bug yesterday to Mapzen, thanks to follow it here.
What is also strange, it's the maze done in the village of Yvoire (too in Geneva):
http://www.openstreetmap.org/directions?engine=mapzen_foot&route=46.5127%2C6.4936%3B46.2223%2C6.0547#map=15/46.3657/6.3304
A detail:
http://www.openstreetmap.org/directions?engine=mapzen_foot&route=46.5127%2C6.4936%3B46.2223%2C6.0547#map=19/46.36846/6.32529
But if i take two points of the way, it calculates a shorter way:
http://www.openstreetmap.org/directions?engine=mapzen_foot&route=46.36911%2C6.33187%3B46.36624%2C6.31349#map=16/46.3688/6.3227
When I put the two points near the pier, it goes by boat:
http://www.openstreetmap.org/directions?engine=mapzen_foot&route=46.37102%2C6.32450%3B46.36548%2C6.30582#map=16/46.3687/6.3131

Best regards and good luck to solve it
