### ISSUE TITLE
Strange ordering for optimized route results with this query

### ISSUE THREAD

**Issue by rmglennon** [valhalla/valhalla#919]
This came in through support (see Desk 956). 

Query to reproduce:

https://matrix.mapzen.com/optimized_route

 {'json': '{"locations": [{"lat": 38.92547, "lon": -92.28772, "name": "start"}, {"lat": 38.336223, "lon": -92.653129, "name": 270221}, {"lat": 38.35063676, "lon": -92.61344025, "name": 270224}, {"lat": 38.35358264, "lon": -92.61237244, "name": 270225}, {"lat": 38.34644808, "lon": -92.59998869, "name": 270202}, {"lat": 38.34720627, "lon": -92.59437404, "name": 270199}, {"lat": 38.35125923, "lon": -92.56724297, "name": 270194}, {"lat": 38.35862153, "lon": -92.56309789, "name": 270192}, {"lat": 38.36081594, "lon": -92.57393463, "name": 270195}, {"lat": 38.36005718, "lon": -92.57973391, "name": 270191}, {"lat": 38.35467625, "lon": -92.57705502, "name": 270189}, {"lat": 38.35283692, "lon": -92.57577124, "name": 270190}, {"lat": 38.34765581, "lon": -92.57932641, "name": 270197}, {"lat": 38.3447, "lon": -92.58389941, "name": 270201}, {"lat": 38.30234865, "lon": -92.56909129, "name": 270198}, {"lat": 38.2882055, "lon": -92.57830303, "name": 270200}, {"lat": 38.27012682, "lon": -92.60421901, "name": 270209}, {"lat": 38.29304364, "lon": -92.61347181, "name": 270196}, {"lat": 38.25211048, "lon": -92.68973765, "name": 270217}, {"lat": 38.29798368, "lon": -92.76266732, "name": 270222}, {"lat": 38.31719264, "lon": -92.80379187, "name": 270226}, {"lat": 38.2977732, "lon": -92.72822681, "name": 270220}, {"lat": 38.28508634, "lon": -92.70912166, "name": 270219}, {"lat": 38.28140078, "lon": -92.70527442, "name": 270218}, {"lat": 38.25123204, "lon": -92.73541443, "name": 270223}, {"lat": 38.24103389, "lon": -92.72060212, "name": 270216}, {"lat": 38.2422711, "lon": -92.70873663, "name": 270215}, {"lat": 38.23131491, "lon": -92.69651543, "name": 270214}, {"lat": 38.23486739, "lon": -92.67647606, "name": 270213}, {"lat": 38.22956636, "lon": -92.67020905, "name": 270212}, {"lat": 38.2363922, "lon": -92.65965538, "name": 270211}, {"lat": 38.235816, "lon": -92.656027, "name": 270210}, {"lat": 38.24498474, "lon": -92.63827678, "name": 270208}, {"lat": 38.24564429, "lon": -92.61391708, "name": 270204}, {"lat": 38.2453592, "lon": -92.59726881, "name": 270205}, {"lat": 38.25655565, "lon": -92.58136218, "name": 270207}, {"lat": 38.25765343, "lon": -92.57295806, "name": 270203}, {"lat": 38.24781514, "lon": -92.53787316, "name": 270206}, {"lat": 38.30990419, "lon": -92.47253699, "name": 270193}, {"lat": 38.31439555, "lon": -92.47728536, "name": 270187}, {"lat": 38.34128522, "lon": -92.46286839, "name": 270188}, {"lat": 38.9254736, "lon": -92.2876847, "name": "end"}], "costing": "auto", "directions_options": {"units": "miles"}}'}

![screen shot 2017-09-05 at 12 39 30 pm](https://user-images.githubusercontent.com/4380498/30184150-dad284e8-93d1-11e7-99f1-d91d8de70c42.png)

![screen shot 2017-09-05 at 12 37 26 pm](https://user-images.githubusercontent.com/4380498/30184156-e045645e-93d1-11e7-873e-7d7415705141.png)

**Comment by dnesbitt61** [comment]
The order in the returned JSON locations array is the order of the optimal positions. It looks to me like the labels for the locations are not the order in which the locations are visited? Can you check that the number used for the label is the index within the returned JSON locations array? Alternatively, is there a simpler (less locations) case that illustrates the issue?

**Comment by jyunis** [comment]
@dnesbitt61 - I will double-check and get back to you. Thank you for looking at this!

**Comment by jyunis** [comment]
@dnesbitt61 - I'm getting a slightly different ordering today, but a generally similar sequence. I checked to make sure I'm using the order that is returned in the JSON 'locations' array. Is there any way for you to provide a visualization (or at least lat/lon ordering) that you're seeing when you optimize this route? Then I can check that against what I'm seeing to get to the bottom of this.

Thanks again!

**Comment by dnesbitt61** [comment]
I don't have a good way to visualize this. Do you see correct behavior on smaller requests (less locations)? That would be much easier to verify locations and label behavior. We have a demo (under valhalla/demos repo) but it uses point and click to enter locations (rather than an input URL).

**Comment by dnesbitt61** [comment]
I definitely get different results each time I run this request with different overall length and time.  Will have to dig deeper.

**Comment by jyunis** [comment]
Thanks. I'll see about finding similar results with a smaller dataset.

**Comment by jyunis** [comment]
I cut the stops in half at random from the example route above and am still seeing somewhat unexpected route ordering.
![screen shot 2017-09-11 at 10 36 09 am](https://user-images.githubusercontent.com/942432/30283236-2288140c-96dd-11e7-8c01-116996a62b4d.png)

**Comment by jyunis** [comment]
@dnesbitt61 : Is there any other info I can send to help with this? I'm definitely willing to dig up more examples if that would be helpful (assuming I can reproduce this reliably). Let me know, and thank you!

**Comment by dnesbitt61** [comment]
We have this on our radar to investigate in Q4, but likely won't be able to get to this for a couple of weeks. We will let you know if we have questions. Sorry for the delay but have been trying to wrap up a couple of other projects.

**Comment by jyunis** [comment]
No problem, thanks for the update.

**Comment by dnesbitt61** [comment]
Finally got time to update this. Have a look!

**Comment by jyunis** [comment]
Great! I'll give it another go when I have a moment.

**Comment by dnesbitt61** [comment]
We will likely update our production systems later today - so maybe wait until tomorrow if you are hitting our production service!

**Comment by jyunis** [comment]
No prob, I probably won't get to it for a couple of days anyway.
