### ISSUE TITLE
Add transition penalty between different road types in map-matching

### ISSUE THREAD

**Issue by ptpt** [valhalla/valhalla#930]
In multimodal, since meili doesn't know a trace's transport mode, it considers all road types, and it considers transitions between all road types equivalent. This leads that a trace may match road segments in very different road types, e.g. highway -> sidewalk -> highway -> ferry -> etc. which doesn't look that correct. Although we can guess a trace's transport mode by GPX timestamps (average speed), we don't have timestamps available all the time.

A solution is to define a matrix that defines penalty costs from a road type to another road type. Then use this table to popularize matching single transport modes.

**Comment by dnesbitt61** [comment]
Do you need to support multiple modes? Walking, bicycling, auto are fine, but public transit modes are risky since we do not always have good geometry for rail lines. Without timestamps I think this is going to be hard.

**Comment by kevinkreiser** [comment]
it seems like in this case multimodal doesnt have anything to do with rail, ie transitland data. it seems like in this case multimodal just means take any edges that match the case. in other words a costing that doesnt filter edges and therefore just lets the GPX match whatever shapes match the edges (whichever those are) best

**Comment by ptpt** [comment]
@dnesbitt61 yes, multiple modes, only walking, bicycling, and auto.

@kevinkreiser yes, matching whatever edges often result in wrong matches. What I proposed is like a `single` mode. In this mode, it considers all roads as `multimodal` does, but it assumes that the trace is recorded in a single mode -- walking, bicycling or auto, we don't know. In a single mode, it's unlikely to match segments like `highway -> sidewalk -> highway`. Instead they should be either `highway -> highway -> highway`, or `sidewalk -> sidewalk -> sidewalk`. If we add a cost penalty from highway to sidewalk, then the we are more likely to get a more consistent, and more correct matches.

**Comment by kevinkreiser** [comment]
@migurski i heard you might be asking for something like this, where mapmatching kind of guesses the costing model. just wanted to clue you into this issue in case you wanted to follow along

**Comment by migurski** [comment]
Thanks Kevin! I'm definitely interested in a broad, general match, to make it possible to match any road segment navigable by any means. We're using this to prototype a visual tool, so it's important that results "look roadlike" and not important that they be legal. Hope that makes sense.

**Comment by ptpt** [comment]
Yeah, "given a trace, detecting its travel mode" would be another useful output.

**Comment by ptpt** [comment]
It seems that the best and simplest approach is just: map match with different modes, and find one match route with the best score.
