### ISSUE TITLE
valhalla_build_tiles core dump

### ISSUE THREAD

**Issue by geochasm** [valhalla/valhalla#931]
I followed the ppa-based instructions on a ubuntu 16.04 system and the installation completed with no issues; when I run valhalla_build_tiles I am getting a core dump - see below; not sure if it is something in my valhalla.json config file or if I am calling the valhalla_build_tiles incorrectly; core dump happened with absolute paths to config and pbf file as well. See error below. I can also provide gdb output of the core dump if that would help; basically indicates a file not found issue. I configured everything correctly for all the "mjolnir" settings in valhallay.json but perhaps I am missing some required paths or files. Let me know what else I can provide to troubleshoot and thank you!

~/valhalla$ valhalla_build_tiles -c valhalla.json switzerland-latest.osm.pbf
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
~/valhalla$ terminate called after throwing an instance of 'std::bad_alloc'

**Comment by kevinkreiser** [comment]
that means you are out of memory. we do have some minimum requirements as far as ram goes but i think it should be in the single digit gigabytes. how much ram do you have in your system? i think i would suggest at least 4gb

**Comment by geochasm** [comment]
Apparently my EC2 t2.micro instance with 1 GB of ram was not  up to the task; I have things working now with a larger instance. Thank you for the quick reply!
