### ISSUE TITLE
valhalla_build_config error on Ubuntu 16.04

### ISSUE THREAD

**Issue by geochasm** [valhalla/valhalla#936]
I am having no issues with Valhalla running on an AWS EC2 instance with Ubuntu 14.04.

However, on an EC2 instance with Ubuntu 16.04 the valhalla_build_config step throws this error - "/usr/bin/env: âpythonâ: No such file or directory"

Here are the steps to reproduce:
Launch a new 16.04 EC2 instance
sudo apt-get update
sudo apt-get upgrade
sudo add-apt-repository -y ppa:valhalla-core/valhalla
sudo apt-get update
sudo apt-get install -y valhalla-bin	
wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
mkdir -p valhalla_tiles
valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json

**Comment by kevinkreiser** [comment]
Looks like you don't have either env or python which is really strange. Make sure python is installed. I suppose we should make python a dep of valhalla-bin

**Comment by dnesbitt61** [comment]
closing, if this is still an issue please reopen
