### ISSUE TITLE
missing test/data/tmp_utrecht_tiles

### ISSUE THREAD

**Issue by mcheung610** [valhalla/valhalla#941]
I am getting image not found when I ran `make test`. It looks like it is missing `test/data/tmp_utrecht_tiles`

```
Building Utrecht Tiles...
dyld: Library not loaded: libboost_thread.dylib
  Referenced from: ..../git/valhalla/valhalla/.libs/valhalla_build_tiles
  Reason: image not found
/bin/sh: line 1: 98948 Abort trap: 6           ./valhalla_build_tiles --inline-config '{"mjolnir":{"tile_dir":"test/data/tmp_utrecht_tiles","concurrency":1,"logging":{"type":""}}}' test/data/utrecht_netherlands.osm.pbf
make[2]: *** [Makefile:9917: test/data/utrecht_tiles] Error 134
make[2]: Leaving directory '/Users/mcheung/git/valhalla/valhalla'
make[1]: *** [Makefile:9639: check-am] Error 2
make[1]: Leaving directory '/Users/mcheung/git/valhalla/valhalla'
make: *** [Makefile:9642: check] Error 2
```

**Comment by kevinkreiser** [comment]
It looks like to me that something is going wrong with the linking when it runs the program. There is a make target that builds these tmp utrecht tiles which we use for tests. When that program runs it seems from your output, that its failing to link the proper libraries and so it fails to run. I dont know much about how this works on macs but id see if you can run the command in the target that is currently failing outside of running make. if that works then something is wrong with the make environment on your mac.

**Comment by mcheung610** [comment]
ah thanks. I got this resolved now. Please correct me if I am wrong. For anyone who is trying to build this on mac, you will need to upgrade gcc for c++11 and recompile some of its dependencies, like boost and protobuf, and re-create the symlink in /usr/local/include
