### ISSUE TITLE
How to debug valhalla crashes?

### ISSUE THREAD

**Issue by mcheung610** [valhalla/valhalla#942]
I followed the instructions in https://github.com/valhalla/valhalla#command-line-tools to build the command line tool in mac osx, but I am getting `Abort trap: 6` when running the command below. Nothing seems to be logging to the path I specified in the `valhalla.json` file. I am not sure if that's normal. I am wondering if there is a way to turn on the logging, so I can see what is going on here. Thanks in advance.

```
./valhalla_run_route -j '{"locations":[{"lat":40.285488,"lon":-76.650597,"type":"break","city":"Hershey","state":"PA"},{"lat":40.794025,"lon":-77.860695,"type":"break","city":"State College","state":"PA"}],"costing":"auto","directions_options":{"units":"miles"}}' --config /Users/mcheung/data/valhalla.json 
2017/09/28 22:41:59.967189 [INFO] Tile extract successfully loaded
2017/09/28 22:41:59.972656 [INFO] routetype: auto
Abort trap: 6
```

**Comment by kevinkreiser** [comment]
i dont have a lot of ideas about doing this on mac but if you have gdb and libtool, you should be able to build valhalla in debug mode and run the program with gdb to see where its aborting. libtool complicates this a bit, so on linux debugging it requires you to first configure and rebuild it with debug info, something like this:

    ./configure CFLAGS="-O0 -g -ggdb" CXXFLAGS="-O0 -g -ggdb"
    make clean && make -j4

and then debug it using libtool/gdb would be something like this:

    libtool --mode=execute gdb --args ./valhalla_run_route -j {"locations":[{"lat":40.285488,"lon":-76.650597,"type":"break","city":"Hershey","state":"PA"},{"lat":40.794025,"lon":-77.860695,"type":"break","city":"State College","state":"PA"}],"costing":"auto","directions_options":{"units":"miles"}}' --config /Users/mcheung/data/valhalla.json

when the program aborts it gdb should be able to give you a stack and you will be able to see in code where its aborted.

**Comment by dnesbitt61** [comment]
Also note that working output should be like this:

2017/09/29 15:47:23.843089 ^[[33;1m[WARN]^[[0m Tile extract could not be loaded
2017/09/29 15:47:23.843159 ^[[32;1m[INFO]^[[0m routetype: auto
2017/09/29 15:47:23.867446 ^[[32;1m[INFO]^[[0m Location Processing took 24 ms
2017/09/29 15:47:24.416432 ^[[32;1m[INFO]^[[0m PathAlgorithm GetBestPath took 548 ms

So something seems to be going wrong in the location processing. If gdb is not helpful you can try adding cout or printf to parts of the code to trace where things might go wrong.

**Comment by dnesbitt61** [comment]
closing this issue since no further updates. If you are still working this issue feel free to re-open and add more details.
