### ISSUE TITLE
Roundabout Inconsistencies

### ISSUE THREAD

**Issue by farough** [valhalla/valhalla#947]
Hi,

I've started to implement Mapzen into our mobile apps, but I'm having issues with the directions regarding Roundabouts. We're using biking directions and I'm finding many of the roundabouts give inconsistent and often inaccurate values for the exit number. Even going to a single roundabout and making a request for each different exit, I often get the same exit number in both the exit count and the description to the user in which exit to take.

This roundabout in particular:
https://www.google.ca/maps/place/49%C2%B004'39.9%22N+6%C2%B006'04.7%22E/@49.077756,6.0999106,17z/data=!3m1!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d49.0777564!4d6.1013132

Coming from the North East, the exit number says to take the first exit for the first 3 exits and the 4th and 5th exit say take the 2nd exit.

Thanks.

**Comment by dgearhart** [comment]
https://www.openstreetmap.org/directions?engine=mapzen_car&route=49.07855%2C6.10254%3B49.07699%2C6.10004#map=19/49.07776/6.10131

Car works correctly
![roundabout_car](https://user-images.githubusercontent.com/7515853/31192892-7f1ced2e-a910-11e7-84d8-2a982656bd6e.png)


Bicycle is not correct
![roundabout_bicycle](https://user-images.githubusercontent.com/7515853/31192910-87f3a3f2-a910-11e7-99b2-2e70849598b9.png)

Pedestrian is not correct
![roundabout_foot](https://user-images.githubusercontent.com/7515853/31192922-8ddfc674-a910-11e7-9573-eb11e4380ef1.png)

**Comment by farough** [comment]
That's good to know, we're only using Bicycling for our application, so it would be great if this bug could be addressed.

**Comment by dgearhart** [comment]
Added test routes here:
https://github.com/valhalla/valhalla/blob/master/test_requests/eu_roundabout_routes.txt#L12-L29

**Comment by dgearhart** [comment]
@farough we are planning to have in production next week
