### ISSUE TITLE
Occasional No Path Found without an obvious reason

### ISSUE THREAD

**Issue by farough** [valhalla/valhalla#953]
Hi,

I've noticed that there are certain locations where Mapzen returns:
{"error_code":442,"error":"No path could be found for input","status_code":400,"status":"Bad Request"}

However, there is no obvious reason for this failure. Locations very close to this location will snap to the closest road and create a path. Even some farther away from the road. 

The following location option is such an example.
json={%22costing%22:%22bicycle%22,%22costing_options%22:{%22bicycle_type%22:%22Road%22,%22cycling_speed%22:18,%22use_ferry%22:0.5,%22use_hills%22:0.5,%22use_roads%22:0.5},%22directions_options%22:{%22language%22:%22en_US%22,%22narrative%22:%22true%22,%22units%22:%22kilometers%22},%22locations%22:[{%22heading_tolerance%22:60,%22lat%22:45.5268073,%22lon%22:-73.5964626,%22maximum_reachability%22:50,%22radius%22:0},{%22heading_tolerance%22:60,%22lat%22:45.532008403679015,%22lon%22:-73.58745513115389,%22maximum_reachability%22:50,%22radius%22:0}]}

Please advise why I would receive this response.

**Comment by kevinkreiser** [comment]
you have specified that you want a bike route. the only way that has bike access and is near your destination location is: http://www.openstreetmap.org/way/272850874

all the ways it connects to dont have bike access so the route fails. this should be solved by the fact that you sent in a reachability of 50 though (this edge only has reachability 1) so i'll have a look at this to see why its not ignoring this edge completely and checking other candidates.

**Comment by kevinkreiser** [comment]
ok first thing is that the parameter isn't called `maximum_reachability` but rather `minimum_reachability`. the idea being that youd want to only use locations that are reachable from **at least** `n` nodes. lets simplify the request down:

    {"costing":"bicycle","locations":[{"lat":45.526807,"lon":-73.596462,"minimum_reachability":50,"radius":0},{"lat":45.532008,"lon":-73.587455,"minimum_reachability":50,"radius":0}]}

now this still fails but sending in the destination to loki i do see it return another result that is on `Rue de Brébeuf`. I'll have a look at why its not then just using that location to find the the path.

**Comment by kevinkreiser** [comment]
ok so the issue was that requests around this area were sometimes using the A* algorithm in lieu of the bidirectional A* algorithm. thats why it was only occasionally failing. it turned out there was a typo in the A* algorithm and we have a PR in review to fix this. Thanks very much @farough for pointing this out, @dnesbitt61 had seen this problem before and had the fix for it, we just hadnt gotten it in for review yet!
