### ISSUE TITLE
Possible routing inconsistency or else unexpected tag handling

### ISSUE THREAD

**Issue by BobC76** [valhalla/valhalla#955]
I discovered an inconsistency in the routing when comparing the mapzen routing available on OSM with that of other tools. 
This route http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=51.46407%2C-2.55384%3B51.46336%2C-2.55103#map=19/51.46372/-2.55244
 takes the most optimum path, whereas http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=51.46336%2C-2.55103%3B51.46407%2C-2.55384#map=19/51.46370/-2.55244 takes a less ideal detour rather than the reverse.

**Comment by dnesbitt61** [comment]
It takes 1 to 2 days for OSM edits to make it through our system into the routing engine. I see that there have been a lot of edits in the area over the last day. If this is still happening in a few days please re-open the issue and we can investigate.
