### ISSUE TITLE
Map matching train traces fails

### ISSUE THREAD

**Issue by araichev** [valhalla/valhalla#972]
Hi all,

Judging by my experiments with Mapzen Mobility Explorer, looks like map matching train traces fails using walking, cycling, and driving modes.
Attached is a sample train trace from Auckland, New Zealand (zipped so Github accepts it) and a screen shot for the walking-mode match on Mobility Explorer.

[train_route.gpx.zip](https://github.com/valhalla/valhalla/files/1393075/train_route.gpx.zip)
![train_example](https://user-images.githubusercontent.com/4087432/31695874-8b6755c0-b409-11e7-9512-70080b40d3d9.png)

**Comment by kevinkreiser** [comment]
@araichev we dont store any edges in our routing graph for osm train tracks as we currently dont support any mode of travel that would use this data. cars, pedestrians, bikes, they all dont use train tracks to travel. now we do support multi-modal which can allow a pedestrian to walk sections and ride public transit for other sections of their route. these routes use edges that are created from transit.land data. we dont currently support map matching along multi-modal routes for many reasons but one important reason is that we dont always have the actual geometry between two stops on a given public transit route. another reason is the time constraints and schedule lookup and how that would fit in the hidden markov model based map matching algorithm we currently employ. unfortunately this is a pretty complex situation that we just dont handle at the moment. sorry for the inconvenience.
