### ISSUE TITLE
Top K Map Matching Results Remove Hardcoded Uniqueness Limit

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#978]
In #970 we noted that there were a number of possible paths that can come out of the candidates for the given input points. In #975 we made a change to take care of that but after doing so it was noticed that the bulk of time is spent going through and rejecting thousands of redundant paths. To combat this very long loop that essentially produces hardly any results we put a hardcoded cap in place that basically says dont compute any more than 20 different permutations of candidates.

@ptpt noted that instead we could possibly remove candidates that would produce only redundant paths thereby greatly reducing the number of permutations one would have to visit to find all unique paths for a given input. indeed this approach would gaurantee that you'd only see the unique paths for a given input (i think). his original comment was:

>  After we get the red path (the best one), we can remove candidates which are impossible to be used to construct distinct paths from the red path. For example, the candidate 1 and candidate 2 can be removed. Because their paths to the candidates at next time (3, 4, 5, 6) can't make any difference from the path starting from candidate 0 (via 4TH ST). By removing these "obviously impossible" candidates, we should be able to get the green path in a few iterations or just next iteration.

![intro](https://user-images.githubusercontent.com/87357/31930100-c5a78770-b89e-11e7-8ac1-eefa93c11f09.png)

**Comment by kevinkreiser** [comment]
with respect to the image above, a potential algorithm for removing those candidates with redundant paths was proposed as follows, its correctness or feasibility has yet to be determined:

Ok so we compute the red path as:

    time 0 = 0 -> 4
    time 1 = 4 -> 9
    time 2 = 9 -> 11

Then when we remove that path we could also remove some candidate pairs that have redundancies with the red route:

    time = 0 has candidates 0,1,2
    paths from 0 to 3,4,5,6 contain or are contained in the paths from 1 to 3,4,5,6, so remove 1
    paths from 0 to 3,4,5,6 contain or are contained in the paths from 2 to 3,4,5,6, so remove 2
    time = 1 has candidates 3,4,5,6
    paths from 4 to 7,8,9,10 contain or are contained in the paths from 3 to 7,8,9,10, so remove 3
    time = 2 has candidates 7,8,910
    paths from 9 to 11,12 contain or are contained in the paths from 7 to 11,12, so remove 7
    paths from 9 to 11,12 contain or are contained in the paths from 8 to 11,12, so remove 8
    paths from 9 to 11,12 contain or are contained in the paths from 10 to 11,12, so remove 10

Then we run again and find the green path as the next most optimal:

    time 0 = 0 -> 6
    time 1 = 6 -> 9
    time 2 = 9 -> 11

Then when we remove that path we could also remove some candidate pairs that have redundancies with the green route:

    time = 0 has candidate 0
    no more candidates to remove
    time = 1 has candidates 4,5,6
    paths from 6 to 7,8,9,10 contain or are contained in the paths from 5 to 7,8,9,10, so remove 5
    time = 2 has candidates 9
    no more candidates to remove

And if we ran again i suppose we'd get the path that looked like the red path but ended at candidate 12, at which point we'd remove candidate 11 maybe? I cant tell if we can remove candidates from the last time slot. Does this algorithm seem correct, I'm still mulling over whether its logically sound or not.

**Comment by ptpt** [comment]
I can't find anything incorrect. One note is that if there exists at least one distinct path from the previous candidates to the current candidate, we should keep the current candidate, despite all paths from the current candidate to next candidates are contained or being contained.

**Comment by ptpt** [comment]
> And if we ran again i suppose we'd get the path that looked like the red path but ended at candidate 12, at which point we'd remove candidate 11 maybe? I cant tell if we can remove candidates from the last time slot. Does this algorithm seem correct, I'm still mulling over whether its logically sound or not.

I supposed that candidate 12 is not reachable by previous candidates (7, 8, 9, 10), therefore there isn't exists path ending at 12.

The candidates at last time can be removed by checking if there is any distinct path from any previous candidate to current candidate.

**Comment by kevinkreiser** [comment]
ok so ive implemented the above but it doesnt work as well as it could. essentially you still have to throw out some duplicate paths because of the way the algorithm chooses which candidate to remove. let me explain further. heres a trace that goes from east to west:

![input](https://user-images.githubusercontent.com/697548/32285007-6b9c5b7c-beff-11e7-90f1-6ffabc00a0f9.png)

heres the winner path:

![winner](https://user-images.githubusercontent.com/697548/32285189-e9ceeb54-beff-11e7-9d20-1bf01ff5311b.png)

but even after removing redundant candidates, we still get a redundant second most probable result:

![redundant](https://user-images.githubusercontent.com/697548/32285311-49761bea-bf00-11e7-98e1-0f4cdd50da1d.png)

this is because the algorithm above seeks to do the most damage in one iteration, that is remove all the paths from a candidate. in this instance the first point of the trace had a candidate that had most paths redundant with the intial winner but it had a single path that was not redundant using that dashed line edge that cuts the corner.

what this means is that the assumption that the above algorithm will remove all redundant paths and  have the effect that a subsequent call to viterbi search will give back a unique path is incorrect.

this lead me to the idea that we dont really need to look at all paths from a candidate. really we just want to remove paths that are redundant with any full paths we've seen so far. so referencing the original drawing from @ptpt at the top of this issue:

```
k=0
  get red path as (0,4,9,11)

k=1
  remove path (0,4,9,11)

  candidates for time = 0 to time = 1

  examine candidate 0:
    remove path (0,3,9,11)
    cant remove (0,4,9,11) (already removed it)
    cant remove (0,5,9,11)
    cant remove (0,6,9,11)

  examine candidate 1:
    remove path (1,4,9,11)
    remove path (1,3,9,11)
    cant remove (1,5,9,11)
    cant remove (1,6,9,11)

  examine candidate 2:
    remove path (2,4,9,11)
    remove path (2,3,9,11)
    cant remove (2,5,9,11)
    cant remove (2,6,9,11)

  candidates for time = 1 to time = 2

  examine candidate 3:
    cant remove (0,3,7,11)
    cant remove (0,3,8,11)
    remove path (0,3,9,11)
    cant remove (0,3,10,11)
 
  examine candidate 4 and so on...

  at this point we've removed all paths with candidate pairs that were redundant with the red path
  so we get the green path as (0,6,9,11)
```

the algorithm is basically go through all the state pairs (time=n, time=n+1) and all the candidate pairs between the two states and if the sub path between the two candidates is redundant with the current best path, then remove that path containing that permutation of those two candidates.
