### ISSUE TITLE
Segmentation fault on Building Tiles

### ISSUE THREAD

**Issue by pschlieker** [valhalla/valhalla#991]
Hello,

I was just trying to move my meili instances to Google Cloud Computing, when I ran into problems building the tiles. I am completely following these [instructions](https://github.com/valhalla/valhalla/blob/cf0a1353163ef713b5899518fadb6aca5ec3afc9/docs/meili/run_service_in_docker.md). 

The Docker Container would just crash, right after launch
![image](https://user-images.githubusercontent.com/12111198/32239497-ff21ef64-be6a-11e7-861b-46368710e9ce.png)

Updating or building the container myself didn't help. Now i found out, that the problem seems to be related to the current oberbayern-latest.osm.pbf. Using data from about 2 months ago the tiles are building fine.

The error seems to be reproducible by downloading [oberbayern-latest.osm.pbf ](http://download.geofabrik.de/europe/germany/bayern/oberbayern.html) of 2017-10-30T21:43:02Z

**Comment by dnesbitt61** [comment]
Also, I just downloaded this from Geofabrik and it works for me on Ubuntu.

**Comment by pschlieker** [comment]
@kevinkreiser Thank you very much for your fast response :) I actually just used the old map material, which is fine for me.

@dnesbitt61 that is very weird. Just tried it on my laptop running ubuntu 16.04 and ran into the same segmentation fault.
![parsingerrormeili](https://user-images.githubusercontent.com/12111198/32265464-6e62e93c-bee3-11e7-812d-98408513c64b.png)

**Comment by kevinkreiser** [comment]
@pschlieker that docker image is quite old. at this point we are using the valhalla docker instance: https://hub.docker.com/r/valhalla/docker/

**Comment by dnesbitt61** [comment]
Closing this issue. If there are still problems with the updated Valhalla Docker please open a new issue
